import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {readFileSync} from "node:fs";
import {resolve} from "node:path";
import {after,before,test} from "node:test";
import {ConflictException,ForbiddenException} from "@nestjs/common";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {DataSource} from "typeorm";
import type {AuditService} from "../audit/audit.service";
import {HrJobChangeService} from "./hr-job-change.service";

const enabled=process.env.HR_APPROVED_EMPLOYMENT_JOB_CHANGE_PG_REQUIRED==="1",scope={tenantId:"approval-fulfillment-tenant",parkId:"approval-fulfillment-park"};
let admin:DataSource,db:DataSource|undefined,service:HrJobChangeService,fixtureSchema:string,actorId:string,employeeId:string,otherEmployeeId:string,thirdEmployeeId:string,oldOrg:string,newOrg:string,oldPosition:string,newPosition:string;
const actor=(permissions:string[]=[])=>({sub:actorId,username:"synthetic-fulfillment",tenantId:scope.tenantId,parkId:scope.parkId,roles:[],permissions});
const draft=(employeeIdValue=employeeId)=>({applicationName:"Synthetic approved employment fulfillment",employeeId:employeeIdValue,applicationDate:"2026-10-10",effectiveDate:"2026-10-10",changeType:"transfer",afterOrgId:newOrg,afterPositionId:newPosition,reason:"Synthetic transaction validation"});
const addApproval=async(version=1,subjectEmployeeId=employeeId,requestType="employment_change",status="approved")=>{const id=randomUUID();await db!.query(`INSERT INTO hr_approval_request(id,tenant_id,park_id,request_no,request_type,subject_employee_id,title,payload,status,completed_at,version) VALUES($1,$2,$3,$4,$5,$6,'Synthetic approved request','{"description":"Synthetic only"}',$7,now(),$8)`,[id,scope.tenantId,scope.parkId,`APP-${id.slice(0,8)}`,requestType,subjectEmployeeId,status,version]);return id;};

before(async()=>{if(!enabled)return;const port=Number(process.env.POSTGRES_PORT);if(process.env.POSTGRES_HOST!=="127.0.0.1"||![55491,55497].includes(port)||process.env.POSTGRES_DB!=="postgres")throw Error("Requires the owned approval-fulfillment PostgreSQL fixture");fixtureSchema=`hr_approval_fulfillment_${randomUUID().replaceAll("-","")}`;const connection={type:"postgres" as const,host:"127.0.0.1",port,username:process.env.POSTGRES_USER??"postgres",password:process.env.POSTGRES_PASSWORD,database:"postgres"};admin=new DataSource(connection);await admin.initialize();await admin.query(`CREATE SCHEMA "${fixtureSchema}"; CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);db=new DataSource({...connection,extra:{options:`-c search_path=${fixtureSchema},public`}});await db.initialize();
 await db.query(`CREATE TABLE sys_org(id uuid PRIMARY KEY,tenant_id text,park_id text,org_name text,status text,is_deleted boolean DEFAULT false);CREATE TABLE hr_position(id uuid PRIMARY KEY,tenant_id text,park_id text,org_id uuid,position_name text,status text,is_deleted boolean DEFAULT false);CREATE TABLE hr_employee(id uuid PRIMARY KEY,tenant_id text,park_id text,employee_code text,full_name text,primary_org_id uuid,position_id uuid,employment_status text,is_deleted boolean DEFAULT false);CREATE TABLE hr_approval_request(id uuid PRIMARY KEY,tenant_id text NOT NULL,park_id text NOT NULL,request_no text,request_type text,subject_employee_id uuid,title text,payload jsonb,status text,completed_at timestamptz,version integer,is_deleted boolean DEFAULT false,UNIQUE(tenant_id,park_id,id));CREATE TABLE hr_job_change_application(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id text NOT NULL,park_id text NOT NULL,application_no text,application_name text,applicant_user_id uuid,subject_employee_id uuid,application_date date,effective_date date,change_type text,before_org_id uuid,before_position_id uuid,after_org_id uuid,after_position_id uuid,reason text,before_snapshot jsonb,after_snapshot jsonb,status text DEFAULT 'draft',review_comment text,reviewed_at timestamptz,applied_at timestamptz,version integer DEFAULT 1,is_deleted boolean DEFAULT false,create_by uuid,create_time timestamptz DEFAULT now(),update_by uuid,update_time timestamptz DEFAULT now(),UNIQUE(tenant_id,park_id,id));CREATE UNIQUE INDEX uq_hr_job_change_active_employee ON hr_job_change_application(tenant_id,park_id,subject_employee_id) WHERE is_deleted=false AND status IN('draft','submitted','returned','approved');CREATE TABLE hr_job_change_action(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id text,park_id text,application_id uuid,sequence_no integer,action text,from_status text,to_status text,comment text,actor_user_id uuid);CREATE TABLE hr_employment_event(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id text,park_id text,event_no text);`);
 await db.query(readFileSync(resolve(__dirname,"../../../../../database/migrations/000354_hr_approved_employment_job_change_fulfillment.sql"),"utf8"));
 actorId=randomUUID();employeeId=randomUUID();otherEmployeeId=randomUUID();thirdEmployeeId=randomUUID();oldOrg=randomUUID();newOrg=randomUUID();oldPosition=randomUUID();newPosition=randomUUID();await db.query(`INSERT INTO sys_org VALUES($1,$2,$3,'Old','enabled',false),($4,$2,$3,'New','enabled',false)`,[oldOrg,scope.tenantId,scope.parkId,newOrg]);await db.query(`INSERT INTO hr_position VALUES($1,$2,$3,$4,'Old role','enabled',false),($5,$2,$3,$6,'New role','enabled',false)`,[oldPosition,scope.tenantId,scope.parkId,oldOrg,newPosition,newOrg]);await db.query(`INSERT INTO hr_employee VALUES($1,$2,$3,'EMP-1','Synthetic employee',$4,$5,'active',false),($6,$2,$3,'EMP-2','Other synthetic employee',$4,$5,'active',false),($7,$2,$3,'EMP-3','Third synthetic employee',$4,$5,'active',false)`,[employeeId,scope.tenantId,scope.parkId,oldOrg,oldPosition,otherEmployeeId,thirdEmployeeId]);service=new HrJobChangeService(db,{recordOperationRequired:async()=>undefined} as unknown as AuditService);
});
after(async()=>{if(db?.isInitialized)await db.destroy();if(admin?.isInitialized){await admin.query(`DROP SCHEMA IF EXISTS "${fixtureSchema.replace(/"/g,'""')}" CASCADE`);await admin.destroy();}});

test("owned PostgreSQL: approved employment fulfillment locks source, preserves draft-only effect and rolls back link failures",{skip:!enabled,timeout:60_000},async()=>{
 const permitted=actor([HR_PERMISSIONS.HR_APPROVAL_PARK_REVIEW,HR_PERMISSIONS.HR_JOB_CHANGE_MANAGE,HR_PERMISSIONS.HR_JOB_CHANGE_READ]);const source=await addApproval();const created=await service.createFromApproval(scope,permitted,source,{...draft(),expectedApprovalVersion:1}) as {id:string;applicationNo:string;status:string;sourceApprovalId:string;sourceApprovalVersion:number};assert.equal(created.status,"draft");assert.equal(created.sourceApprovalId,source);assert.equal(created.sourceApprovalVersion,1);assert.equal((await db!.query(`SELECT count(*)::int n FROM hr_employee WHERE id=$1 AND primary_org_id=$2`,[employeeId,oldOrg]))[0].n,1);assert.equal((await db!.query(`SELECT count(*)::int n FROM hr_employment_event`))[0].n,0);const ordinary=await service.list(scope,permitted,{page:1,page_size:20});assert.deepEqual((ordinary.items as Array<{id:string;sourceApprovalId:string;sourceApprovalVersion:number}>).find(item=>item.id===created.id),{...(ordinary.items as Array<Record<string,unknown>>).find(item=>item.id===created.id),sourceApprovalId:source,sourceApprovalVersion:1});const queue=await service.approvedEmploymentRequests(scope,permitted,{page:1,page_size:20});assert.deepEqual((queue.items as Array<{id:string;jobChange:{id:string;status:string}}>).find(item=>item.id===source)?.jobChange,{id:created.id,applicationNo:created.applicationNo,status:"draft"});await assert.rejects(service.update(scope,permitted,created.id,draft(otherEmployeeId)),/must retain/i);assert.deepEqual((await db!.query(`SELECT subject_employee_id,status FROM hr_job_change_application WHERE id=$1`,[created.id]))[0],{subject_employee_id:employeeId,status:"draft"});assert.deepEqual((await db!.query(`SELECT approval_request_id,job_change_application_id FROM hr_job_change_approval_fulfillment WHERE job_change_application_id=$1`,[created.id]))[0],{approval_request_id:source,job_change_application_id:created.id});
 await assert.rejects(service.createFromApproval(scope,permitted,source,{...draft(),expectedApprovalVersion:1}),ConflictException);const stale=await addApproval(2);await assert.rejects(service.createFromApproval(scope,permitted,stale,{...draft(),expectedApprovalVersion:1}),ConflictException);const mismatch=await addApproval();await assert.rejects(service.createFromApproval(scope,permitted,mismatch,{...draft(otherEmployeeId),expectedApprovalVersion:1}),/must match/i);const pending=await addApproval(1,employeeId,"employment_change","submitted"),wrongType=await addApproval(1,employeeId,"profile_change");await assert.rejects(service.createFromApproval(scope,permitted,pending,{...draft(),expectedApprovalVersion:1}),/not found/i);await assert.rejects(service.createFromApproval(scope,permitted,wrongType,{...draft(),expectedApprovalVersion:1}),/not found/i);const filtered=await service.approvedEmploymentRequests(scope,permitted,{page:1,page_size:20});assert.ok(!(filtered.items as Array<{id:string}>).some(item=>item.id===pending||item.id===wrongType));await assert.rejects(service.createFromApproval(scope,actor([HR_PERMISSIONS.HR_JOB_CHANGE_MANAGE]),await addApproval(),{...draft(),expectedApprovalVersion:1}),ForbiddenException);await assert.rejects(service.createFromApproval({...scope,parkId:"foreign"},permitted,await addApproval(),{...draft(),expectedApprovalVersion:1}),ForbiddenException);
 const rollback=await addApproval(1,otherEmployeeId);await db!.query(`ALTER TABLE hr_job_change_approval_fulfillment ADD CONSTRAINT reject_rollback_source CHECK(approval_request_id<>'${rollback}'::uuid)`);await assert.rejects(service.createFromApproval(scope,permitted,rollback,{...draft(otherEmployeeId),expectedApprovalVersion:1}));assert.equal((await db!.query(`SELECT count(*)::int n FROM hr_job_change_application WHERE application_name='Synthetic approved employment fulfillment'`))[0].n,1);await db!.query(`ALTER TABLE hr_job_change_approval_fulfillment DROP CONSTRAINT reject_rollback_source`);
 const firstSource=await addApproval(1,otherEmployeeId),secondSource=await addApproval(1,otherEmployeeId),results=await Promise.allSettled([service.createFromApproval(scope,permitted,firstSource,{...draft(otherEmployeeId),expectedApprovalVersion:1}),service.createFromApproval(scope,permitted,secondSource,{...draft(otherEmployeeId),expectedApprovalVersion:1})]);assert.equal(results.filter(result=>result.status==="fulfilled").length,1);assert.equal(results.filter(result=>result.status==="rejected").length,1);assert.equal((await db!.query(`SELECT count(*)::int n FROM hr_job_change_application WHERE subject_employee_id=$1 AND status='draft'`,[otherEmployeeId]))[0].n,1);assert.equal((await db!.query(`SELECT count(*)::int n FROM hr_job_change_approval_fulfillment WHERE approval_request_id IN ($1,$2)`,[firstSource,secondSource]))[0].n,1);
 const sameSource=await addApproval(1,thirdEmployeeId),sameResults=await Promise.allSettled([service.createFromApproval(scope,permitted,sameSource,{...draft(thirdEmployeeId),expectedApprovalVersion:1}),service.createFromApproval(scope,permitted,sameSource,{...draft(thirdEmployeeId),expectedApprovalVersion:1})]);assert.equal(sameResults.filter(result=>result.status==="fulfilled").length,1);assert.equal((await db!.query(`SELECT count(*)::int n FROM hr_job_change_approval_fulfillment WHERE approval_request_id=$1`,[sameSource]))[0].n,1);
});
