import assert from "node:assert/strict";
import { after,before,describe,it } from "node:test";
import { DataSource } from "typeorm";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { HrAttendanceCalculationVersionEntity,HrAttendancePunchEventEntity,HrAttendanceRequestEntity,HrAttendanceShiftEntity,HrEmployeeAttendanceDailyResultEntity,HrEmployeeEntity,HrEmployeeScheduleEntity } from "./entities/hr.entities";
import { HrService } from "./hr.service";

const required=process.env.HR_ATTENDANCE_CALC_PG_REQUIRED==="1";if(required&&!process.env.POSTGRES_PASSWORD)throw new Error("POSTGRES_PASSWORD is required for the attendance calculation PostgreSQL gate");const suite=required?describe:describe.skip;
suite("HR attendance calculation PostgreSQL gate",()=>{
 let dataSource:DataSource,service:HrService;const scope={tenantId:"10000001",parkId:"20000001"},user="00000000-0000-4000-8000-00000000d001",employee="00000000-0000-4000-8000-00000000d101",actor:JwtPrincipal={sub:user,username:"attendance-gate",tenantId:scope.tenantId,parkId:scope.parkId,roles:[],permissions:["hr:attendance:read"]};
 before(async()=>{dataSource=new DataSource({type:"postgres",host:process.env.POSTGRES_HOST??"127.0.0.1",port:Number(process.env.POSTGRES_PORT??"5432"),database:process.env.POSTGRES_DB??"jinhu_smart_park",username:process.env.POSTGRES_USER??"jinhu",password:process.env.POSTGRES_PASSWORD,entities:[HrEmployeeEntity,HrAttendanceRequestEntity,HrAttendanceShiftEntity,HrEmployeeScheduleEntity,HrAttendancePunchEventEntity,HrAttendanceCalculationVersionEntity,HrEmployeeAttendanceDailyResultEntity]});await dataSource.initialize();const args=Array(32).fill(undefined);args[0]=dataSource.getRepository(HrEmployeeEntity);args[26]=dataSource.getRepository(HrAttendanceRequestEntity);args[30]=dataSource;args[31]={recordOperationRequired:async()=>undefined};service=Reflect.construct(HrService,args) as HrService;await dataSource.query("INSERT INTO sys_user(id,tenant_id,park_id,username,display_name,password_hash) VALUES ($1,$2,$3,'M6-CALC','考勤计算测试','not-a-login-hash')",[user,scope.tenantId,scope.parkId]);await dataSource.query("INSERT INTO hr_employee(id,tenant_id,park_id,employee_code,full_name,user_id,employment_status) VALUES ($1,$2,$3,'M6-CALC','跨夜员工',$4,'active')",[employee,scope.tenantId,scope.parkId,user]);});
 after(async()=>{if(dataSource?.isInitialized){await dataSource.query("DELETE FROM hr_employee_attendance_daily_result WHERE employee_id=$1",[employee]);await dataSource.query("DELETE FROM hr_attendance_calculation_version WHERE tenant_id=$1 AND park_id=$2 AND triggered_by=$3",[scope.tenantId,scope.parkId,user]);await dataSource.query("DELETE FROM hr_attendance_punch_event WHERE employee_id=$1",[employee]);await dataSource.query("DELETE FROM hr_employee_schedule WHERE employee_id=$1",[employee]);await dataSource.query("DELETE FROM hr_attendance_request WHERE employee_id=$1",[employee]);await dataSource.query("DELETE FROM hr_attendance_shift WHERE shift_code='M6-NIGHT'");await dataSource.query("DELETE FROM hr_employee WHERE id=$1",[employee]);await dataSource.query("DELETE FROM sys_user WHERE id=$1",[user]);await dataSource.destroy();}});
 it("deduplicates exact events, rejects changed payloads, and calculates a cross-midnight Shanghai business day",async()=>{const shift=await service.createAttendanceShift(scope,actor,{shiftCode:"M6-NIGHT",shiftName:"跨夜班",startLocal:"23:00",endLocal:"07:00",ruleVersion:"night-v1"}),schedule=await service.createEmployeeSchedule(scope,actor,{employeeId:employee,shiftId:shift.id,workDate:"2026-08-24"});assert.equal(schedule.workDate,"2026-08-24");const first=await service.createAttendancePunch(scope,actor,{employeeId:employee,eventKey:"M6-IN",occurredAt:"2026-08-24T23:05:00+08:00",eventType:"clock_in",source:"terminal"}),duplicate=await service.createAttendancePunch(scope,actor,{employeeId:employee,eventKey:"M6-IN",occurredAt:"2026-08-24T23:05:00+08:00",eventType:"clock_in",source:"terminal"});assert.equal(duplicate.id,first.id);await assert.rejects(service.createAttendancePunch(scope,actor,{employeeId:employee,eventKey:"M6-IN",occurredAt:"2026-08-24T23:05:00+08:00",eventType:"clock_in",source:"terminal",deviceCode:"changed-device"}),/different event data/);const independentSource=await service.createAttendancePunch(scope,actor,{employeeId:employee,eventKey:"M6-IN",occurredAt:"2026-08-24T23:05:00+08:00",eventType:"clock_in",source:"mobile"});assert.notEqual(independentSource.id,first.id);const last=await service.createAttendancePunch(scope,actor,{employeeId:employee,eventKey:"M6-OUT",occurredAt:"2026-08-25T07:00:00+08:00",eventType:"clock_out",source:"terminal"});const result=await service.recalculateAttendanceDay(scope,actor,{employeeId:employee,workDate:"2026-08-24",ruleVersion:"night-v1"});assert.equal(result.workedMinutes,475);assert.equal(result.lateMinutes,5);assert.equal(result.resultStatus,"late");const stored=await dataSource.getRepository(HrEmployeeAttendanceDailyResultEntity).findOneByOrFail({id:result.id});assert.equal(stored.sourceTrace.scheduleId,schedule.id);assert.deepEqual(stored.sourceTrace.punchEventIds,[first.id,independentSource.id,last.id]);assert.equal(stored.sourceTrace.timezone,"Asia/Shanghai");assert.equal(stored.sourceTrace.eventWindowStart,"2026-08-24T09:00:00.000Z");assert.equal(stored.sourceTrace.eventWindowEnd,"2026-08-25T05:00:00.000Z");});
 it("uses an approved correction as traceable source and appends an immutable recalculation version",async()=>{const correction="00000000-0000-4000-8000-00000000d201";await dataSource.query("INSERT INTO hr_attendance_request(id,tenant_id,park_id,request_no,employee_id,request_type,attendance_date,duration_minutes,reason,status) VALUES ($1,$2,$3,'M6-CORRECTION',$4,'correction','2026-08-24',0,'测试更正','approved')",[correction,scope.tenantId,scope.parkId,employee]);const historyBefore=Number((await dataSource.query("SELECT count(*)::int AS count FROM hr_attendance_day"))[0].count),result=await service.recalculateAttendanceDay(scope,actor,{employeeId:employee,workDate:"2026-08-24",ruleVersion:"night-v2"}),stored=await dataSource.getRepository(HrEmployeeAttendanceDailyResultEntity).findOneByOrFail({id:result.id}),versions=await dataSource.query("SELECT calculation_version_id FROM hr_employee_attendance_daily_result WHERE employee_id=$1 AND work_date='2026-08-24' ORDER BY create_time,id",[employee]),latest=await service.listAttendanceDaily(scope,actor,{page:1,page_size:20,from:"2026-08-24",to:"2026-08-24"});assert.equal(result.resultStatus,"corrected");assert.equal(stored.correctionRequestId,correction);assert.equal(stored.sourceTrace.correctionRequestId,correction);assert.equal(versions.length,2);assert.notEqual(versions[0].calculation_version_id,versions[1].calculation_version_id);assert.equal(latest.total,1);assert.equal(latest.items[0]?.calculationVersionId,result.calculationVersionId);assert.equal(Number((await dataSource.query("SELECT count(*)::int AS count FROM hr_attendance_day"))[0].count),historyBefore);});
 it("serializes concurrent recalculations while retaining every immutable version",async()=>{const [first,second]=await Promise.all([service.recalculateAttendanceDay(scope,actor,{employeeId:employee,workDate:"2026-08-24",ruleVersion:"race-a"}),service.recalculateAttendanceDay(scope,actor,{employeeId:employee,workDate:"2026-08-24",ruleVersion:"race-b"})]),rows=await dataSource.query("SELECT id,calculation_version_id FROM hr_employee_attendance_daily_result WHERE employee_id=$1 AND work_date='2026-08-24'",[employee]);assert.notEqual(first.id,second.id);assert.notEqual(first.calculationVersionId,second.calculationVersionId);assert.equal(rows.length,4);assert.equal(new Set(rows.map((row:{calculation_version_id:string})=>row.calculation_version_id)).size,4);});
});
