import "reflect-metadata";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { after,before,test } from "node:test";
import { BadRequestException,ConflictException,ForbiddenException,NotFoundException } from "@nestjs/common";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { DataSource } from "typeorm";
import { HrService } from "./hr.service";
import { HrEmployeeEntity,HrEmployeeProfileEntity } from "./entities/hr.entities";

const enabled=process.env.HR_APPROVED_PROFILE_FULFILLMENT_PG_REQUIRED==="1",scope={tenantId:"profile-fulfillment-tenant",parkId:"profile-fulfillment-park"};
let admin:DataSource,db:DataSource,left:DataSource,right:DataSource,schema:string,actorId:string,employeeId:string,audits=0;
const actor=(permissions:string[]=[])=>({sub:actorId,username:"synthetic",tenantId:scope.tenantId,parkId:scope.parkId,roles:[],permissions});
const dto=(expectedVersion:number)=>({employeeId,expectedVersion,expectedApprovalVersion:1,nativePlace:"Synthetic locality",remark:"Synthetic profile fulfillment"});
const service=(source:DataSource)=>{const value=Object.create(HrService.prototype) as HrService;Object.assign(value,{dataSource:source,employees:source.getRepository(HrEmployeeEntity),sensitiveData:{identityProfile:()=>{throw new Error("unexpected identity encryption");}},auditService:{recordOperationRequired:async()=>{audits+=1;}}});Object.assign(value,{detailEmployee:async(s:typeof scope,id:string)=>source.getRepository(HrEmployeeEntity).findOneByOrFail({...s,id,isDeleted:false})});return value;};
const add=async(version=1,status="approved",description="Synthetic approved profile request",requestType="profile_change",subjectEmployeeId=employeeId)=>{const id=randomUUID();await db.query(`INSERT INTO hr_approval_request(id,tenant_id,park_id,request_no,request_type,subject_employee_id,title,payload,status,completed_at,version) VALUES($1,$2,$3,$4,$5,$6,'Synthetic profile',$7::jsonb,$8,now(),$9)`,[id,scope.tenantId,scope.parkId,`PF-${id.slice(0,8)}`,requestType,subjectEmployeeId,JSON.stringify({description}),status,version]);return id;};

 before(async()=>{if(!enabled)return;const port=Number(process.env.POSTGRES_PORT);if(process.env.POSTGRES_HOST!=="127.0.0.1"||![55491,55497].includes(port)||process.env.POSTGRES_DB!=="postgres")throw Error("Requires owned loopback PostgreSQL fixture on 55491/55497");schema=`hr_profile_fulfillment_${randomUUID().replaceAll("-","")}`;const options={type:"postgres" as const,host:"127.0.0.1",port,username:process.env.POSTGRES_USER??"postgres",password:process.env.POSTGRES_PASSWORD,database:"postgres"};admin=new DataSource(options);await admin.initialize();await admin.query(`CREATE SCHEMA "${schema}"; CREATE EXTENSION IF NOT EXISTS "uuid-ossp";`);const make=async(name:string)=>{const source=new DataSource({...options,entities:[HrEmployeeEntity,HrEmployeeProfileEntity],extra:{options:`-c search_path=${schema},public`,application_name:name,max:1}});await source.initialize();return source;};db=await make("profile-fulfillment-main");left=await make("profile-fulfillment-left");right=await make("profile-fulfillment-right");await db.synchronize();await db.query(`CREATE UNIQUE INDEX uq_hr_employee_scope_id ON hr_employee(tenant_id,park_id,id); CREATE UNIQUE INDEX uq_hr_employee_profile_wrong_scope ON hr_employee_profile(tenant_id,id,park_id); CREATE TABLE hr_approval_request(id uuid PRIMARY KEY,tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,request_no text,title text,payload jsonb NOT NULL DEFAULT '{}'::jsonb,request_type text NOT NULL,subject_employee_id uuid NOT NULL,status text NOT NULL,completed_at timestamptz,version integer NOT NULL,is_deleted boolean NOT NULL DEFAULT false);`);await db.query(readFileSync(resolve(__dirname,"../../../../../database/migrations/000355_hr_approved_profile_fulfillment.sql"),"utf8"));actorId=randomUUID();employeeId=randomUUID();await db.getRepository(HrEmployeeEntity).save({id:employeeId,...scope,employeeCode:"PF-1",fullName:"Synthetic employee",employmentType:"full_time",employmentStatus:"active"});});
after(async()=>{await Promise.all([db,left,right].filter(Boolean).map(source=>source.destroy()));if(admin?.isInitialized){await admin.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);await admin.destroy();}});

test("owned loopback PostgreSQL: approved profile fulfillment serializes sources, profiles and receipts",{skip:!enabled,timeout:60_000},async()=>{const permitted=actor([HR_PERMISSIONS.HR_APPROVAL_PARK_REVIEW,HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE]);const a=service(left),b=service(right),ordinary=service(db);const first=await add();const one=await a.fulfillApprovedProfile(scope,permitted,first,dto(0));assert.equal(one.afterVersion,1);const second=await add(1,"approved","Second keyword");const two=await a.fulfillApprovedProfile(scope,permitted,second,{...dto(1),expectedApprovalVersion:1,nativePlace:"Second"});assert.equal(two.afterVersion,2);assert.equal((await db.query(`SELECT count(*)::int n FROM hr_profile_approval_fulfillment WHERE profile_id=$1`,[one.profileId]))[0].n,2);
 const queue=await a.approvedProfileFulfillments(scope,permitted,{page:1,page_size:1,keyword:"Second"});assert.equal(queue.total,1);assert.equal(queue.items[0].description,"Second keyword");assert.ok(queue.items[0].fulfillment);const page=await a.approvedProfileFulfillments(scope,permitted,{page:2,page_size:1});assert.equal(page.items.length,1);assert.equal(audits,2);
 const rejectedLinks=await db.query("SELECT count(*)::int n FROM hr_profile_approval_fulfillment");await assert.rejects(a.fulfillApprovedProfile(scope,permitted,await add(2),{...dto(2),expectedApprovalVersion:1}),ConflictException);await assert.rejects(a.fulfillApprovedProfile(scope,permitted,await add(1,"submitted"),dto(2)),NotFoundException);await assert.rejects(a.fulfillApprovedProfile(scope,permitted,await add(1,"approved","wrong type","employment_change"),dto(2)),NotFoundException);await assert.rejects(a.fulfillApprovedProfile(scope,permitted,await add(1,"approved","wrong subject","profile_change",randomUUID()),dto(2)),BadRequestException);await assert.rejects(a.fulfillApprovedProfile({...scope,parkId:"foreign"},permitted,await add(),dto(2)),ForbiddenException);await assert.rejects(a.fulfillApprovedProfile(scope,actor([HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE]),await add(),dto(2)),ForbiddenException);assert.deepEqual(await db.query("SELECT count(*)::int n FROM hr_profile_approval_fulfillment"),rejectedLinks);
 const same=await add(),sameResults=await Promise.allSettled([a.fulfillApprovedProfile(scope,permitted,same,{...dto(2),expectedApprovalVersion:1}),b.fulfillApprovedProfile(scope,permitted,same,{...dto(2),expectedApprovalVersion:1})]);assert.equal(sameResults.filter(row=>row.status==="fulfilled").length,1);
 const sourceA=await add(),sourceB=await add(),different=await Promise.allSettled([a.fulfillApprovedProfile(scope,permitted,sourceA,{...dto(3),expectedApprovalVersion:1}),b.fulfillApprovedProfile(scope,permitted,sourceB,{...dto(3),expectedApprovalVersion:1})]);assert.equal(different.filter(row=>row.status==="fulfilled").length,1);
 const rollback=await add();await db.query(`ALTER TABLE hr_profile_approval_fulfillment ADD CONSTRAINT reject_profile_link CHECK(approval_request_id<>'${rollback}'::uuid)`);const before=await db.getRepository(HrEmployeeProfileEntity).findOneByOrFail({id:one.profileId}),linksBefore=await db.query("SELECT count(*)::int n FROM hr_profile_approval_fulfillment");await assert.rejects(a.fulfillApprovedProfile(scope,permitted,rollback,{...dto(4),expectedApprovalVersion:1}));assert.deepEqual(await db.getRepository(HrEmployeeProfileEntity).findOneByOrFail({id:one.profileId}),before);assert.deepEqual(await db.query("SELECT count(*)::int n FROM hr_profile_approval_fulfillment"),linksBefore);await db.query("ALTER TABLE hr_profile_approval_fulfillment DROP CONSTRAINT reject_profile_link");const normal=await ordinary.updateEmployeeProfile(scope,actor(),employeeId,{expectedVersion:4,nativePlace:"Ordinary"});assert.equal(normal.version,5);
});
