import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { randomBytes,randomUUID } from "node:crypto";
import { setTimeout as delay } from "node:timers/promises";
import { test } from "node:test";
import { ForbiddenException } from "@nestjs/common";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { DataSource } from "typeorm";
import { HrService } from "./hr.service";

const enabled=process.env.HR_COMPENSATION_ASSIGNMENT_LEDGER_PG_REQUIRED==="1",scope={tenantId:"comp-ledger-tenant",parkId:"comp-ledger-park"};
test("isolated PostgreSQL: compensation assignment ledger scopes, escapes, pages and audits",{skip:!enabled,timeout:90_000},async()=>{const suffix=randomBytes(8).toString("hex"),name=`hr-comp-ledger-${suffix}`,database=`hr_comp_ledger_${suffix}`,password=randomBytes(24).toString("hex"),env={...process.env,POSTGRES_PASSWORD:password};const docker=(args:string[])=>execFileSync("docker",args,{encoding:"utf8",env,stdio:["ignore","pipe","pipe"],timeout:20000}).trim();let db:DataSource|undefined,created=false;
 try{docker(["image","inspect","postgres:16-alpine","--format","{{.Id}}"]);docker(["run","--detach","--name",name,"--label",`hr-comp-ledger=${suffix}`,"--tmpfs","/var/lib/postgresql/data","--publish","127.0.0.1::5432","--env","POSTGRES_PASSWORD","--env",`POSTGRES_DB=${database}`,"postgres:16-alpine"]);created=true;let port=0;for(let i=0;i<60;i++){try{const endpoint=docker(["port",name,"5432/tcp"]);port=Number(endpoint.split(":").at(-1));if(port)break;}catch{/* Docker may not publish the port until startup completes. */}await delay(250);}assert.ok(port,"isolated PostgreSQL did not expose a port");for(let i=0;i<60;i++){try{db=new DataSource({type:"postgres",host:"127.0.0.1",port,database,username:"postgres",password});await db.initialize();break;}catch{if(db?.isInitialized)await db.destroy();db=undefined;await delay(250);}}assert.ok(db,"isolated PostgreSQL did not accept connections");await db.query(`CREATE TABLE hr_employee(id uuid PRIMARY KEY,tenant_id varchar(64),park_id varchar(64),employee_code text,full_name text,employment_status text,is_deleted boolean default false)`);await db.query(`CREATE TABLE hr_compensation_plan(id uuid PRIMARY KEY,tenant_id varchar(64),park_id varchar(64),plan_code text,plan_name text,is_deleted boolean default false)`);await db.query(`CREATE TABLE hr_employee_compensation(id uuid PRIMARY KEY,tenant_id varchar(64),park_id varchar(64),employee_id uuid,plan_id uuid,effective_from date,effective_to date,base_salary numeric(18,2),allowance_amount numeric(18,2),variable_target numeric(18,2),status text,version integer,is_deleted boolean default false)`);
  const employee=randomUUID(),plan=randomUUID(),departed=randomUUID(),literal=randomUUID(),literalPlan=randomUUID(),foreign=randomUUID(),deletedEmployee=randomUUID(),deletedPlan=randomUUID();for(const [id,code,name,status,deleted,tenant,park] of [[employee,"EMP-1","Current","active",false,scope.tenantId,scope.parkId],[departed,"EMP-2","Departed","departed",false,scope.tenantId,scope.parkId],[literal,"E%_\\","Literal %_\\","active",false,scope.tenantId,scope.parkId],[foreign,"FOREIGN","Foreign","active",false,"foreign","foreign"],[deletedEmployee,"DEL","Deleted","active",true,scope.tenantId,scope.parkId]] as const)await db.query(`INSERT INTO hr_employee VALUES($1,$2,$3,$4,$5,$6,$7)`,[id,tenant,park,code,name,status,deleted]);for(const [id,code,name,deleted,tenant,park] of [[plan,"PLAN-1","Base",false,scope.tenantId,scope.parkId],[literalPlan,"P%_\\","Literal plan",false,scope.tenantId,scope.parkId],[deletedPlan,"DEL","Deleted",true,scope.tenantId,scope.parkId]] as const)await db.query(`INSERT INTO hr_compensation_plan VALUES($1,$2,$3,$4,$5,$6)`,[id,tenant,park,code,name,deleted]);for(const [employeeId,planId,date,amount,deleted,tenant,park] of [[employee,plan,"2026-02-01","1234.50",false,scope.tenantId,scope.parkId],[departed,plan,"2026-01-01","2000.00",false,scope.tenantId,scope.parkId],[literal,literalPlan,"2026-03-01","333.30",false,scope.tenantId,scope.parkId],[foreign,plan,"2026-04-01","999.00",false,"foreign","foreign"],[deletedEmployee,plan,"2026-05-01","1.00",false,scope.tenantId,scope.parkId],[employee,deletedPlan,"2026-06-01","2.00",false,scope.tenantId,scope.parkId],[employee,plan,"2026-07-01","3.00",true,scope.tenantId,scope.parkId]] as const)await db.query(`INSERT INTO hr_employee_compensation VALUES($1,$2,$3,$4,$5,$6,NULL,$7,0,0,'active',1,$8)`,[randomUUID(),tenant,park,employeeId,planId,date,amount,deleted]);
  const source=db,originalTransaction=source.transaction.bind(source) as unknown as (...args:unknown[])=>Promise<unknown>;let transactionCalls=0,audits=0,failAudit=false;(source as unknown as {transaction:(...args:unknown[])=>Promise<unknown>}).transaction=(...args)=>{transactionCalls+=1;return originalTransaction(...args);};const service=Object.create(HrService.prototype) as HrService;Object.assign(service,{dataSource:source,auditService:{recordOperationRequired:async()=>{audits+=1;if(failAudit)throw new Error("audit unavailable");}}});const actor={sub:randomUUID(),username:"ledger",tenantId:scope.tenantId,parkId:scope.parkId,roles:[],permissions:[HR_PERMISSIONS.HR_COMPENSATION_READ]};
  const first=await service.listCompensationAssignments(scope,actor,{page:1,page_size:2});assert.equal(first.total,3);assert.equal(first.items.length,2);assert.equal(first.items[0].baseSalary,"333.30");assert.equal(first.items[0].effectiveFrom,"2026-03-01");const second=await service.listCompensationAssignments(scope,actor,{page:2,page_size:2});assert.equal(second.items.length,1);assert.equal(second.items[0].employeeName,"Departed");const empty=await service.listCompensationAssignments(scope,actor,{page:3,page_size:2});assert.equal(empty.items.length,0);const literalResult=await service.listCompensationAssignments(scope,actor,{page:1,page_size:20,keyword:"%_\\"});assert.equal(literalResult.total,1);assert.equal(literalResult.items[0].baseSalary,"333.30");assert.equal(audits,4);const beforeForbidden=transactionCalls;await assert.rejects(service.listCompensationAssignments(scope,{...actor,permissions:[]},{page:1,page_size:20}),ForbiddenException);await assert.rejects(service.listCompensationAssignments(scope,{...actor,parkId:"foreign"},{page:1,page_size:20}),ForbiddenException);assert.equal(transactionCalls,beforeForbidden);failAudit=true;await assert.rejects(service.listCompensationAssignments(scope,actor,{page:1,page_size:20}),/audit unavailable/);
 }finally{if(db?.isInitialized)await db.destroy();if(created)docker(["rm","--force",name]);assert.equal(docker(["ps","-aq","--filter",`label=hr-comp-ledger=${suffix}`]),"");}
});
