import assert from "node:assert/strict";
import {after,before,describe,it} from "node:test";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {DataSource} from "typeorm";
import type {JwtPrincipal} from "../../shared/types/jwt-principal";
import {HrContractReminderService} from "./hr-contract-reminder.service";
const required=process.env.HR_CONTRACT_REMINDER_PG_REQUIRED==="1",suite=required?describe:describe.skip;
suite("HR contract reminder PostgreSQL gate",()=>{
 let db:DataSource,service:HrContractReminderService,actor:JwtPrincipal;
 const s={tenantId:"10000001",parkId:"20000001"},user="00000000-0000-4000-8000-00000000d400",employee="00000000-0000-4000-8000-00000000d401",contract="00000000-0000-4000-8000-00000000d402";
 const managerUser="00000000-0000-4000-8000-00000000d410",managerEmployee="00000000-0000-4000-8000-00000000d411",managedUser="00000000-0000-4000-8000-00000000d412",managedEmployee="00000000-0000-4000-8000-00000000d413",managedContract="00000000-0000-4000-8000-00000000d414",outsideUser="00000000-0000-4000-8000-00000000d420",outsideEmployee="00000000-0000-4000-8000-00000000d421",outsideContract="00000000-0000-4000-8000-00000000d422";let audits=0;
 before(async()=>{db=new DataSource({type:"postgres",host:process.env.POSTGRES_HOST??"127.0.0.1",port:Number(process.env.POSTGRES_PORT??"5432"),database:process.env.POSTGRES_DB,username:process.env.POSTGRES_USER??"jinhu",password:process.env.POSTGRES_PASSWORD});await db.initialize();const type=(await db.query(`SELECT id FROM hr_contract_type WHERE tenant_id=$1 AND park_id=$2 AND is_deleted=false LIMIT 1`,[s.tenantId,s.parkId]))[0];assert.ok(type);await db.query(`INSERT INTO sys_user(id,tenant_id,park_id,username,display_name,password_hash,is_enabled)VALUES($1,$2,$3,'p04-reminder-gate','P04 reminder gate','not-a-login-secret',true),($4,$2,$3,'p04-manager','P04 manager','not-a-login-secret',true),($5,$2,$3,'p04-managed','P04 managed','not-a-login-secret',true),($6,$2,$3,'p04-outside','P04 outside','not-a-login-secret',true)`,[user,s.tenantId,s.parkId,managerUser,managedUser,outsideUser]);actor={sub:user,username:"p04-reminder-gate",tenantId:s.tenantId,parkId:s.parkId,roles:["HR_MANAGER"],permissions:[HR_PERMISSIONS.HR_CONTRACT_REMINDER_PARK_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE,HR_PERMISSIONS.HR_CONTRACT_REMINDER_RUN]};service=new HrContractReminderService(db,{recordOperationRequired:async()=>{audits++;}} as never);await db.query(`INSERT INTO hr_employee(id,tenant_id,park_id,employee_code,full_name,user_id,manager_employee_id,employment_status)VALUES($1,$2,$3,'P04-EMP','P04 employee',$4,NULL,'active'),($5,$2,$3,'P04-MANAGER','P04 manager',$6,NULL,'active'),($7,$2,$3,'P04-MANAGED','P04 managed',$8,$5,'active'),($9,$2,$3,'P04-OUTSIDE','P04 outside',$10,NULL,'active')`,[employee,s.tenantId,s.parkId,user,managerEmployee,managerUser,managedEmployee,managedUser,outsideEmployee,outsideUser]);await db.query(`INSERT INTO hr_contract(id,tenant_id,park_id,employee_id,contract_type_id,contract_no,start_date,end_date,probation_end_date,status,is_historical_import)VALUES($1,$2,$3,$4,$5,'P04-CONTRACT',current_date-interval '1 year',current_date+interval '30 days',current_date+interval '30 days','active',false),($6,$2,$3,$7,$5,'P04-MANAGED-CONTRACT',current_date-interval '1 year',current_date+interval '30 days',NULL,'active',false),($8,$2,$3,$9,$5,'P04-OUTSIDE-CONTRACT',current_date-interval '1 year',current_date+interval '30 days',NULL,'active',false)`,[contract,s.tenantId,s.parkId,employee,type.id,managedContract,managedEmployee,outsideContract,outsideEmployee]);});
 after(async()=>{if(db?.isInitialized){const contracts=[contract,managedContract,outsideContract];await db.query(`DELETE FROM hr_contract_reminder_outbox WHERE reminder_id IN(SELECT id FROM hr_contract_reminder WHERE contract_id=ANY($1::uuid[]))`,[contracts]);await db.query(`DELETE FROM hr_contract_reminder_action WHERE reminder_id IN(SELECT id FROM hr_contract_reminder WHERE contract_id=ANY($1::uuid[]))`,[contracts]);await db.query(`DELETE FROM hr_contract_reminder WHERE contract_id=ANY($1::uuid[])`,[contracts]);await db.query(`DELETE FROM hr_contract WHERE id=ANY($1::uuid[])`,[contracts]);await db.query(`DELETE FROM hr_employee WHERE id=ANY($1::uuid[])`,[[employee,managerEmployee,managedEmployee,outsideEmployee]]);await db.query(`DELETE FROM sys_user WHERE id=ANY($1::uuid[])`,[[user,managerUser,managedUser,outsideUser]]);await db.destroy();}});
 it("deduplicates concurrent scheduler runs and cancels stale reminders",async()=>{await Promise.all([service.run(s,actor),service.run(s,actor)]);const first=Number((await db.query(`SELECT count(*)::int n FROM hr_contract_reminder WHERE contract_id=$1`,[contract]))[0].n);assert.ok(first>0);assert.equal((await service.run(s,actor)).created,0);assert.equal(Number((await db.query(`SELECT count(*)::int n FROM hr_contract_reminder WHERE contract_id=$1`,[contract]))[0].n),first);await db.transaction(m=>service.cancelStale(m,s,contract,actor.sub,"CONTRACT_RENEWED"));assert.equal(Number((await db.query(`SELECT count(*)::int n FROM hr_contract_reminder WHERE contract_id=$1 AND status='cancelled'`,[contract]))[0].n),first);assert.ok(audits>=3);});
 it("enforces team and self scope, direct UUID safe not-found, and required audit",async()=>{const manager:JwtPrincipal={sub:managerUser,username:"p04-manager",tenantId:s.tenantId,parkId:s.parkId,roles:["DEPARTMENT_MANAGER"],permissions:[HR_PERMISSIONS.HR_CONTRACT_REMINDER_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK]};const self:JwtPrincipal={sub:managedUser,username:"p04-managed",tenantId:s.tenantId,parkId:s.parkId,roles:["EMPLOYEE_SELF_SERVICE"],permissions:[HR_PERMISSIONS.HR_CONTRACT_REMINDER_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK]};const team=await service.list(s,manager,{page:1,page_size:100});assert.ok(team.items.length>0);assert.ok(team.items.every(item=>item.employeeId===managedEmployee));const selfPage=await service.list(s,self,{page:1,page_size:100});assert.ok(selfPage.items.length>0);assert.ok(selfPage.items.every(item=>item.employeeId===managedEmployee));const outside=(await db.query(`SELECT id FROM hr_contract_reminder WHERE contract_id=$1 LIMIT 1`,[outsideContract]))[0] as {id:string};await assert.rejects(service.detail(s,manager,outside.id),/not found/i);await assert.rejects(service.action(s,manager,outside.id,{action:"acknowledge"}),/not found/i);const holder=service as unknown as {audit:unknown};const original=holder.audit;holder.audit={recordOperationRequired:async()=>{throw new Error("audit unavailable");}};await assert.rejects(service.detail(s,self,selfPage.items[0]!.id),/audit unavailable/);holder.audit=original;});
 it("completes acknowledge, resolve and cancel transitions with append-only actions and required audit",async()=>{const manager:JwtPrincipal={sub:managerUser,username:"p04-manager",tenantId:s.tenantId,parkId:s.parkId,roles:["DEPARTMENT_MANAGER"],permissions:[HR_PERMISSIONS.HR_CONTRACT_REMINDER_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK]};const open=(await db.query(`SELECT id FROM hr_contract_reminder WHERE tenant_id=$1 AND park_id=$2 AND employee_id=$3 AND recipient_user_id=$4 AND status='open' ORDER BY id LIMIT 1`,[s.tenantId,s.parkId,managedEmployee,managerUser]))[0] as {id:string};assert.ok(open?.id);assert.deepEqual(await service.action(s,manager,open.id,{action:"acknowledge"}),{id:open.id,status:"acknowledged"});assert.deepEqual(await service.action(s,actor,open.id,{action:"resolve"}),{id:open.id,status:"resolved"});const cancellable=(await db.query(`SELECT id FROM hr_contract_reminder WHERE tenant_id=$1 AND park_id=$2 AND status='open' ORDER BY id LIMIT 1`,[s.tenantId,s.parkId]))[0] as {id:string};assert.ok(cancellable?.id);assert.deepEqual(await service.action(s,actor,cancellable.id,{action:"cancel"}),{id:cancellable.id,status:"cancelled"});const actions=await db.query(`SELECT reminder_id,sequence_no,action FROM hr_contract_reminder_action WHERE tenant_id=$1 AND park_id=$2 AND reminder_id=ANY($3::uuid[]) ORDER BY reminder_id,sequence_no`,[s.tenantId,s.parkId,[open.id,cancellable.id]]) as Array<{reminder_id:string;sequence_no:number;action:string}>;assert.ok(actions.some(row=>row.reminder_id===open.id&&row.sequence_no===1&&row.action==="acknowledge"));assert.ok(actions.some(row=>row.reminder_id===open.id&&row.sequence_no===2&&row.action==="resolve"));assert.ok(actions.some(row=>row.reminder_id===cancellable.id&&row.sequence_no===1&&row.action==="cancel"));assert.ok(audits>0);});
});
