import assert from "node:assert/strict";
import {after,before,describe,it} from "node:test";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {DataSource} from "typeorm";
import type {JwtPrincipal} from "../../shared/types/jwt-principal";
import {HrContractReminderService} from "./hr-contract-reminder.service";
const required=process.env.HR_CONTRACT_REMINDER_PG_REQUIRED==="1",suite=required?describe:describe.skip;
suite("HR contract reminder PostgreSQL gate",()=>{
 let db:DataSource,service:HrContractReminderService,actor:JwtPrincipal;
 const s={tenantId:"10000001",parkId:"20000001"},user="00000000-0000-4000-8000-00000000d400",employee="00000000-0000-4000-8000-00000000d401",contract="00000000-0000-4000-8000-00000000d402";let audits=0;
 before(async()=>{db=new DataSource({type:"postgres",host:process.env.POSTGRES_HOST??"127.0.0.1",port:Number(process.env.POSTGRES_PORT??"5432"),database:process.env.POSTGRES_DB,username:process.env.POSTGRES_USER??"jinhu",password:process.env.POSTGRES_PASSWORD});await db.initialize();const type=(await db.query(`SELECT id FROM hr_contract_type WHERE tenant_id=$1 AND park_id=$2 AND is_deleted=false LIMIT 1`,[s.tenantId,s.parkId]))[0];assert.ok(type);await db.query(`INSERT INTO sys_user(id,tenant_id,park_id,username,display_name,password_hash,is_enabled)VALUES($1,$2,$3,'p04-reminder-gate','P04 reminder gate','not-a-login-secret',true)`,[user,s.tenantId,s.parkId]);actor={sub:user,username:"p04-reminder-gate",tenantId:s.tenantId,parkId:s.parkId,roles:["HR_MANAGER"],permissions:[HR_PERMISSIONS.HR_CONTRACT_REMINDER_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE,HR_PERMISSIONS.HR_CONTRACT_REMINDER_RUN]};service=new HrContractReminderService(db,{recordOperationRequired:async()=>{audits++;}} as never);await db.query(`INSERT INTO hr_employee(id,tenant_id,park_id,employee_code,full_name,user_id,employment_status)VALUES($1,$2,$3,'P04-EMP','P04 employee',$4,'active')`,[employee,s.tenantId,s.parkId,user]);await db.query(`INSERT INTO hr_contract(id,tenant_id,park_id,employee_id,contract_type_id,contract_no,start_date,end_date,probation_end_date,status,is_historical_import)VALUES($1,$2,$3,$4,$5,'P04-CONTRACT',current_date-interval '1 year',current_date+interval '30 days',current_date+interval '30 days','active',false)`,[contract,s.tenantId,s.parkId,employee,type.id]);});
 after(async()=>{if(db?.isInitialized){await db.query(`DELETE FROM hr_contract_reminder_outbox WHERE reminder_id IN(SELECT id FROM hr_contract_reminder WHERE contract_id=$1)`,[contract]);await db.query(`DELETE FROM hr_contract_reminder_action WHERE reminder_id IN(SELECT id FROM hr_contract_reminder WHERE contract_id=$1)`,[contract]);await db.query(`DELETE FROM hr_contract_reminder WHERE contract_id=$1`,[contract]);await db.query(`DELETE FROM hr_contract WHERE id=$1`,[contract]);await db.query(`DELETE FROM hr_employee WHERE id=$1`,[employee]);await db.query(`DELETE FROM sys_user WHERE id=$1`,[user]);await db.destroy();}});
 it("deduplicates concurrent scheduler runs and cancels stale reminders",async()=>{await Promise.all([service.run(s,actor),service.run(s,actor)]);const first=Number((await db.query(`SELECT count(*)::int n FROM hr_contract_reminder WHERE contract_id=$1`,[contract]))[0].n);assert.ok(first>0);assert.equal((await service.run(s,actor)).created,0);assert.equal(Number((await db.query(`SELECT count(*)::int n FROM hr_contract_reminder WHERE contract_id=$1`,[contract]))[0].n),first);await db.transaction(m=>service.cancelStale(m,s,contract,actor.sub,"CONTRACT_RENEWED"));assert.equal(Number((await db.query(`SELECT count(*)::int n FROM hr_contract_reminder WHERE contract_id=$1 AND status='cancelled'`,[contract]))[0].n),first);assert.ok(audits>=3);});
});
