import {Body,Controller,Get,Param,ParseUUIDPipe,Post,Query,UseInterceptors} from "@nestjs/common";
import {HR_PERMISSIONS,type TenantParkScope} from "@jinhu/shared";
import {CurrentScope} from "../../shared/decorators/current-scope.decorator";import {CurrentUser} from "../../shared/decorators/current-user.decorator";import {RequireModule} from "../../shared/decorators/modules.decorator";import {RequirePermissions} from "../../shared/decorators/permissions.decorator";import {IdempotencyInterceptor} from "../../shared/interceptors/idempotency.interceptor";import type {JwtPrincipal} from "../../shared/types/jwt-principal";import {AuditLog} from "../audit/decorators/audit-log.decorator";
import {HrContractReminderActionDto,HrContractReminderQueryDto} from "./dto/hr-contract-reminder.dto";import {HrContractReminderService} from "./hr-contract-reminder.service";
@Controller("hr/contract-reminders") @RequireModule("hr") export class HrContractReminderController{constructor(private readonly service:HrContractReminderService){}
 @Get() @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_REMINDER_READ) list(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrContractReminderQueryDto){return this.service.list(s,a,q);}
 @Post("run") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_REMINDER_RUN) @AuditLog({module:"人力资源管理",resource:"hr.contract_reminder",action:"运行合同提醒",bizType:"hr_contract_reminder",captureBody:false}) run(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.run(s,a);}
 @Post(":id/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK) @AuditLog({module:"人力资源管理",resource:"hr.contract_reminder",action:"办理合同提醒",bizType:"hr_contract_reminder",bizIdParam:"id",captureBody:false}) action(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrContractReminderActionDto){return this.service.action(s,a,id,d);}
}
