import assert from "node:assert/strict";
import test from "node:test";
import { randomBytes } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { DataSource } from "typeorm";
import { ConfigService } from "@nestjs/config";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { PartySensitiveDataService } from "../../shared/security/party-sensitive-data.service";
import { HrService } from "./hr.service";
import { HrCustomValueService } from "./hr-custom-value.service";

test("custom maintenance transactions serialize concurrent creation and preserve encrypted audit", { skip: process.env.HR_CUSTOM_VALUE_PG_REQUIRED !== "1", timeout: 60000 }, async () => {
  assert.equal(process.env.POSTGRES_HOST, "127.0.0.1");
  assert.equal(Number(process.env.POSTGRES_PORT), 55494);
  const database = `jinhu_hr_custom_value_lab_${randomBytes(12).toString("hex")}`;
  const options = { type: "postgres" as const, host: "127.0.0.1", port: 55494, username: process.env.POSTGRES_USER, password: process.env.POSTGRES_PASSWORD };
  const admin = new DataSource({ ...options, database: "postgres" });
  await admin.initialize();
  let db: DataSource | undefined, second: DataSource | undefined, created = false;
  try {
    await admin.query(`CREATE DATABASE "${database}" TEMPLATE template0`); created = true;
    db = new DataSource({ ...options, database }); await db.initialize();
    second = new DataSource({ ...options, database }); await second.initialize();
    assert.equal((await db.query("SELECT current_database() AS name"))[0].name, database);
    await db.query(`CREATE EXTENSION "uuid-ossp";
      CREATE TABLE hr_employee(tenant_id varchar(64),park_id varchar(64),id uuid,is_deleted boolean DEFAULT false,UNIQUE(tenant_id,park_id,id));
      CREATE TABLE hr_custom_field_definition(tenant_id varchar(64),park_id varchar(64),id uuid,value_type varchar(16),field_code text DEFAULT 'def1',display_label text DEFAULT 'Synthetic field',field_group text,sort_order integer DEFAULT 0,status varchar(16) DEFAULT 'enabled',is_deleted boolean DEFAULT false,UNIQUE(tenant_id,park_id,id));`);
    await db.query(`CREATE TABLE hr_employee_custom_value(tenant_id varchar(64),park_id varchar(64),employee_id uuid,definition_id uuid,value_status varchar(16),text_value text,numeric_value numeric(28,8),date_value date,boolean_value boolean,is_deleted boolean DEFAULT false)`);
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000332_hr_employee_custom_value_maintenance.sql"), "utf8"));
    const employeeId = "00000000-0000-4000-8000-000000000011", definitionId = "00000000-0000-4000-8000-000000000021";
    const scope = { tenantId: "test-tenant", parkId: "test-park" };
    const actor = { sub: "00000000-0000-4000-8000-000000000001", username: "synthetic", ...scope, roles: [], permissions: [HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE] };
    await db.query("INSERT INTO hr_employee VALUES($1,$2,$3,false)", [scope.tenantId, scope.parkId, employeeId]);
    await db.query("INSERT INTO hr_custom_field_definition(tenant_id,park_id,id,value_type) VALUES($1,$2,$3,'text')", [scope.tenantId, scope.parkId, definitionId]);
    await db.query("INSERT INTO hr_employee_custom_value(tenant_id,park_id,employee_id,definition_id,value_status,text_value) VALUES($1,$2,$3,$4,'invalid','synthetic-original')",[scope.tenantId,scope.parkId,employeeId,definitionId]);
    const original = await db.query("SELECT * FROM hr_employee_custom_value");
    const sensitive = new PartySensitiveDataService(new ConfigService({ PARTY_DATA_ENCRYPTION_KEY: "synthetic-custom-value-key-12345678901234567890" }));
    const service = new HrCustomValueService(db, sensitive), rival = new HrCustomValueService(second, sensitive);
    const args=Array(33).fill({});args[30]=db;args[32]=sensitive;
    const reader=Reflect.construct(HrService,args) as {employeeCustomFields:(actualScope:typeof scope,id:string)=>Promise<Array<{value:string|null;sourceValid:boolean;version:number}>>};
    const originalRead=await reader.employeeCustomFields(scope,employeeId);
    assert.equal(originalRead[0]!.value,"synthetic-original");assert.equal(originalRead[0]!.sourceValid,false);
    await assert.rejects(service.update(scope, { ...actor, permissions: [] }, employeeId, definitionId, { expectedVersion: 0, value: "denied" }));
    await assert.rejects(service.update({ ...scope, parkId: "foreign" }, actor, employeeId, definitionId, { expectedVersion: 0, value: "denied" }));
    const results = await Promise.allSettled([service.update(scope, actor, employeeId, definitionId, { expectedVersion: 0, value: "one" }), rival.update(scope, actor, employeeId, definitionId, { expectedVersion: 0, value: "two" })]);
    assert.equal(results.filter(result => result.status === "fulfilled").length, 1);
    assert.equal(results.filter(result => result.status === "rejected").length, 1);
    const row = (await db.query("SELECT * FROM hr_employee_custom_value_maintenance"))[0];
    assert.equal(row.version, 1);
    assert.match(row.value_encrypted, /^enc:v1:/);
    assert.ok(["one", "two"].includes(JSON.parse(sensitive.decrypt(row.value_encrypted)!).value));
    const effective=await reader.employeeCustomFields(scope,employeeId);assert.equal(effective[0]!.sourceValid,true);assert.equal(effective[0]!.version,1);
    await service.update(scope, actor, employeeId, definitionId, { expectedVersion: 1, value: null });
    await assert.rejects(rival.update(scope, actor, employeeId, definitionId, { expectedVersion: 1, value: "stale" }));
    const cleared = (await db.query("SELECT * FROM hr_employee_custom_value_maintenance"))[0];
    assert.equal(cleared.value_status, "null"); assert.equal(cleared.version, 2);
    assert.deepEqual(JSON.parse(sensitive.decrypt(cleared.value_encrypted)!), { value: null });
    const clearedRead=await reader.employeeCustomFields(scope,employeeId);assert.equal(clearedRead[0]!.value,null);assert.equal(clearedRead[0]!.version,2);
    assert.deepEqual(await db.query("SELECT * FROM hr_employee_custom_value"),original);
    await db.query("CREATE FUNCTION synthetic_reject_audit() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'SYNTHETIC_AUDIT_FAILURE'; END $$; CREATE TRIGGER synthetic_reject_audit BEFORE INSERT ON hr_employee_custom_value_change FOR EACH ROW EXECUTE FUNCTION synthetic_reject_audit()");
    await assert.rejects(service.update(scope, actor, employeeId, definitionId, { expectedVersion: 2, value: "must-roll-back" }));
    assert.deepEqual((await db.query("SELECT * FROM hr_employee_custom_value_maintenance"))[0], cleared);
    assert.equal(Number((await db.query("SELECT count(*) AS count FROM hr_employee_custom_value_change"))[0].count), 2);
    await assert.rejects(db.query("UPDATE hr_employee_custom_value_change SET version=99"));
    await db.query("UPDATE hr_custom_field_definition SET status='disabled'");
    await assert.rejects(service.update(scope, actor, employeeId, definitionId, { expectedVersion: 2, value: "disabled" }));
  } finally {
    if (second?.isInitialized) await second.destroy();
    if (db?.isInitialized) await db.destroy();
    if (created) await admin.query(`DROP DATABASE "${database}"`);
    assert.equal((await admin.query("SELECT datname FROM pg_database WHERE datname=$1", [database])).length, 0);
    await admin.destroy();
  }
});
