import {BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException} from "@nestjs/common";
import {HR_PERMISSIONS,type TenantParkScope} from "@jinhu/shared";
import {DataSource,EntityManager} from "typeorm";
import type {JwtPrincipal} from "../../shared/types/jwt-principal";
import {AuditService} from "../audit/audit.service";
import {HrDepartureActionDto,HrDepartureArchiveDto,HrDepartureHandoverDto,HrDepartureInterviewDto,HrDepartureListDto,HrDepartureReviewDto,HrDepartureSurveyDto,HrDepartureWageDto,SaveHrDepartureDto} from "./dto/hr-departure.dto";
import {recordHrSensitiveRead} from "./hr-sensitive-read-audit";

type Access="park"|"managed_org_tree"|"self"|"none";
type Row=Record<string,unknown>&{id:string;application_no:string;application_name:string;applicant_user_id:string;subject_employee_id:string;application_date:string|Date;planned_departure_date:string|Date;departure_type:string;reason:string;before_snapshot:Record<string,unknown>;status:string;interview_status:string;survey_status:string;handover_status:string;wage_status:string;archive_status:string};
type DateOnlyFormatter={
 (value:string|Date):string;
 (value:null|undefined):null;
 (value:string|Date|null|undefined):string|null;
};
const dateOnly=((value:string|Date|null|undefined)=>value==null?null:value instanceof Date?new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(value):value.slice(0,10)) as DateOnlyFormatter;
const businessToday=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());

@Injectable()
export class HrDepartureService {
 constructor(private readonly db:DataSource,private readonly audit:AuditService){}
 private has(a:JwtPrincipal,p:string){return Boolean(a.isSuper||a.permissions.includes("*")||a.permissions.includes(p));}
 private require(a:JwtPrincipal,p:string){if(!this.has(a,p))throw new ForbiddenException("Departure operation permission required");}
 private access(a:JwtPrincipal):Access{if(this.has(a,HR_PERMISSIONS.HR_DEPARTURE_READ))return "park";if(this.has(a,HR_PERMISSIONS.HR_DEPARTURE_TEAM_READ))return "managed_org_tree";if(this.has(a,HR_PERMISSIONS.HR_DEPARTURE_SELF_READ))return "self";return "none";}
 private sensitive(a:JwtPrincipal){return this.has(a,HR_PERMISSIONS.HR_DEPARTURE_READ)||this.has(a,HR_PERMISSIONS.HR_DEPARTURE_MANAGE);}
 private managedOrgSql(actorParam:string){return `WITH RECURSIVE managed_org AS(SELECT id FROM sys_org WHERE tenant_id=$1 AND park_id=$2 AND leader_user_id=${actorParam} AND is_deleted=false AND status='enabled' UNION ALL SELECT c.id FROM sys_org c JOIN managed_org p ON c.parent_id=p.id WHERE c.tenant_id=$1 AND c.park_id=$2 AND c.is_deleted=false AND c.status='enabled') SELECT id FROM managed_org`;}

 async list(s:TenantParkScope,a:JwtPrincipal,q:HrDepartureListDto){
  const access=this.access(a);if(access==="none")return {items:[],total:0,page:q.page,page_size:q.page_size};
  const args:unknown[]=[s.tenantId,s.parkId],where=["d.tenant_id=$1","d.park_id=$2","d.is_deleted=false"];
  if(access!=="park"){args.push(a.sub);const actor=`$${args.length}`;where.push(access==="self"?`(d.applicant_user_id=${actor} OR e.user_id=${actor})`:`e.primary_org_id IN(${this.managedOrgSql(actor)})`);}
  if(q.status){args.push(q.status);where.push(`d.status=$${args.length}`);}if(q.keyword){args.push(`%${q.keyword}%`);where.push(`(d.application_no ILIKE $${args.length} OR d.application_name ILIKE $${args.length} OR e.employee_code ILIKE $${args.length} OR e.full_name ILIKE $${args.length})`);}
  const from=`FROM hr_departure_application d JOIN hr_employee e ON e.tenant_id=d.tenant_id AND e.park_id=d.park_id AND e.id=d.subject_employee_id LEFT JOIN sys_org o ON o.tenant_id=e.tenant_id AND o.park_id=e.park_id AND o.id=e.primary_org_id WHERE ${where.join(" AND ")}`;
  const count=await this.db.query(`SELECT count(*)::int total ${from}`,args) as Array<{total:number}>;args.push(q.page_size,(q.page-1)*q.page_size);
  const rows=await this.db.query(`SELECT d.*,e.employee_code,e.full_name employee_name,o.org_name ${from} ORDER BY d.application_date DESC,d.create_time DESC,d.id LIMIT $${args.length-1} OFFSET $${args.length}`,args) as Row[];
  const sensitive=access==="park"||this.has(a,HR_PERMISSIONS.HR_DEPARTURE_MANAGE);const items=rows.map(r=>this.project(r,sensitive));await recordHrSensitiveRead(this.audit,s,a,{resource:"hr.departure_application",action:"读取离职流程",bizType:"hr_departure_application",bizId:null,path:"/hr/departure-applications",fieldGroups:sensitive?["work_content"]:[],projection:access==="managed_org_tree"?"team":access,itemCount:items.length});return {items,total:Number(count[0]?.total??0),page:q.page,page_size:q.page_size};
 }

 async options(s:TenantParkScope,a:JwtPrincipal){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_MANAGE);const park=this.has(a,HR_PERMISSIONS.HR_DEPARTURE_READ),args:unknown[]=[s.tenantId,s.parkId],filter=park?"":(args.push(a.sub),` AND e.primary_org_id IN(${this.managedOrgSql("$3")})`);const employees=await this.db.query(`SELECT e.id,e.employee_code "employeeCode",e.full_name "employeeName",e.primary_org_id "orgId",o.org_name "orgName",e.employment_status "employmentStatus" FROM hr_employee e LEFT JOIN sys_org o ON o.tenant_id=e.tenant_id AND o.park_id=e.park_id AND o.id=e.primary_org_id WHERE e.tenant_id=$1 AND e.park_id=$2 AND e.is_deleted=false AND e.employment_status IN('probation','active','suspended')${filter} ORDER BY e.full_name,e.id LIMIT 500`,args);return {employees};}

 async create(s:TenantParkScope,a:JwtPrincipal,d:SaveHrDepartureDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_MANAGE);this.validate(d);try{return await this.db.transaction(async m=>{const employee=await this.employeeFacts(m,s,a,d.employeeId);const no=await this.nextNo(m,s,d.plannedDepartureDate);const rows=await m.query(`INSERT INTO hr_departure_application(tenant_id,park_id,application_no,application_name,applicant_user_id,subject_employee_id,application_date,planned_departure_date,departure_type,reason,before_snapshot,create_by,update_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$5,$5) RETURNING *`,[s.tenantId,s.parkId,no,d.applicationName,a.sub,d.employeeId,d.applicationDate,d.plannedDepartureDate,d.departureType,d.reason,JSON.stringify(this.snapshot(employee))]) as Row[];await this.append(m,s,rows[0]!.id,"created",null,"draft",a.sub);return this.detail(m,s,rows[0]!.id,this.sensitive(a));});}catch(e){this.translate(e);}}
 async update(s:TenantParkScope,a:JwtPrincipal,id:string,d:SaveHrDepartureDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_MANAGE);this.validate(d);try{return await this.db.transaction(async m=>{const row=await this.lock(m,s,id);if(!["draft","returned"].includes(row.status))throw new ConflictException("Only draft or returned departure applications can be edited");await this.assertOperationScope(m,s,a,row.subject_employee_id);const employee=await this.employeeFacts(m,s,a,d.employeeId,id);const applicationNo=dateOnly(row.planned_departure_date)!.slice(0,7)===d.plannedDepartureDate.slice(0,7)?row.application_no:await this.nextNo(m,s,d.plannedDepartureDate);await m.query(`UPDATE hr_departure_application SET application_no=$1,application_name=$2,subject_employee_id=$3,application_date=$4,planned_departure_date=$5,departure_type=$6,reason=$7,before_snapshot=$8,update_by=$9,update_time=now(),version=version+1 WHERE id=$10`,[applicationNo,d.applicationName,d.employeeId,d.applicationDate,d.plannedDepartureDate,d.departureType,d.reason,JSON.stringify(this.snapshot(employee)),a.sub,id]);await this.append(m,s,id,"updated",row.status,row.status,a.sub);return this.detail(m,s,id,this.sensitive(a));});}catch(e){this.translate(e);}}
 async act(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureActionDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_MANAGE);return this.db.transaction(async m=>{const row=await this.lock(m,s,id);await this.assertOperationScope(m,s,a,row.subject_employee_id);const allowed:Record<string,string[]>={submit:["draft"],resubmit:["returned"],cancel:["draft","submitted","returned"]};if(!allowed[d.action]?.includes(row.status))throw new ConflictException("Departure action is not allowed from current status");const next=d.action==="cancel"?"cancelled":"submitted",action=d.action==="submit"?"submitted":d.action==="resubmit"?"resubmitted":"cancelled";await m.query(`UPDATE hr_departure_application SET status=$1,review_comment=NULL,reviewed_by=NULL,reviewed_at=NULL,update_by=$2,update_time=now(),version=version+1 WHERE id=$3`,[next,a.sub,id]);await this.append(m,s,id,action,row.status,next,a.sub);return this.detail(m,s,id,this.sensitive(a));});}
 async review(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureReviewDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_REVIEW);return this.db.transaction(async m=>{const row=await this.lock(m,s,id);await this.assertOperationScope(m,s,a,row.subject_employee_id);if(row.status!=="submitted")throw new ConflictException("Only submitted departure applications can be reviewed");if(row.applicant_user_id===a.sub)throw new ForbiddenException("Applicants cannot review their own departure application");if(d.action==="return"&&!d.comment?.trim())throw new BadRequestException("A return comment is required");const next=d.action==="approve"?"approved":"returned";await m.query(`UPDATE hr_departure_application SET status=$1,review_comment=$2,reviewed_by=$3,reviewed_at=now(),update_by=$3,update_time=now(),version=version+1 WHERE id=$4`,[next,d.comment??null,a.sub,id]);await this.append(m,s,id,next,"submitted",next,a.sub);return this.detail(m,s,id,this.sensitive(a));});}

 async interview(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureInterviewDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_INTERVIEW);return this.clearance(s,a,id,"interview",d.status,{interview_place:d.place??null,interview_summary:d.summary});}
 async survey(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureSurveyDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_SURVEY);return this.clearance(s,a,id,"survey",d.status,{survey_reason_codes:JSON.stringify([...new Set(d.reasonCodes.map(x=>x.trim()).filter(Boolean))]),survey_summary:d.summary});}
 async handover(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureHandoverDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_HANDOVER);return this.db.transaction(async m=>{const row=await this.lockApproved(m,s,a,id);if(row.handover_status!=="pending")throw new ConflictException("Departure handover evidence is already closed");if(d.status==="completed"&&!d.handoverToEmployeeId)throw new BadRequestException("A handover recipient is required");if(d.handoverToEmployeeId){const target=(await m.query(`SELECT id FROM hr_employee WHERE tenant_id=$1 AND park_id=$2 AND id=$3 AND is_deleted=false AND employment_status IN('probation','active','suspended')`,[s.tenantId,s.parkId,d.handoverToEmployeeId]))[0];if(!target||d.handoverToEmployeeId===row.subject_employee_id)throw new BadRequestException("Handover recipient is unavailable");}await m.query(`UPDATE hr_departure_application SET handover_status=$1,handover_by=$2,handover_at=now(),handover_to_employee_id=$3,handover_summary=$4,update_by=$2,update_time=now(),version=version+1 WHERE id=$5`,[d.status,a.sub,d.handoverToEmployeeId??null,d.summary,id]);await this.append(m,s,id,`handover_${d.status}`,"approved","approved",a.sub);return this.detail(m,s,id,this.sensitive(a));});}
 async wage(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureWageDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_WAGE_SETTLE);return this.clearance(s,a,id,"wage",d.status,{wage_note:d.note});}
 async archive(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrDepartureArchiveDto){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_ARCHIVE_CLOSE);return this.db.transaction(async m=>{const row=await this.lockApproved(m,s,a,id);if(row.archive_status!=="open")throw new ConflictException("Departure archive is already closed");if(!["completed","waived"].includes(row.interview_status)||!["completed","waived"].includes(row.survey_status)||!["completed","waived"].includes(row.handover_status)||!["settled","waived"].includes(row.wage_status))throw new ConflictException("Interview, survey, handover and wage settlement must be closed first");await m.query(`UPDATE hr_departure_application SET archive_status='closed',archive_by=$1,archive_at=now(),archive_note=$2,update_by=$1,update_time=now(),version=version+1 WHERE id=$3`,[a.sub,d.note,id]);await this.append(m,s,id,"archive_closed","approved","approved",a.sub);return this.detail(m,s,id,this.sensitive(a));});}

 async apply(s:TenantParkScope,a:JwtPrincipal,id:string){this.require(a,HR_PERMISSIONS.HR_DEPARTURE_APPLY);try{return await this.db.transaction(async m=>{const row=await this.lock(m,s,id);await this.assertOperationScope(m,s,a,row.subject_employee_id);if(row.status!=="approved")throw new ConflictException("Only approved departure applications can be applied");if(dateOnly(row.planned_departure_date)>businessToday())throw new ConflictException("A future-dated departure cannot be applied yet");if(!["completed","waived"].includes(row.interview_status)||!["completed","waived"].includes(row.survey_status)||!["completed","waived"].includes(row.handover_status)||!["settled","waived"].includes(row.wage_status)||row.archive_status!=="closed")throw new ConflictException("Departure clearance is incomplete");const employee=(await m.query(`SELECT id,employee_code,full_name,user_id,primary_org_id,position_id,manager_employee_id,employment_type,employment_status,hire_date,departure_date FROM hr_employee WHERE tenant_id=$1 AND park_id=$2 AND id=$3 AND is_deleted=false FOR UPDATE`,[s.tenantId,s.parkId,row.subject_employee_id]))[0] as Record<string,unknown>|undefined;if(!employee)throw new NotFoundException("Employee not found");const before=row.before_snapshot;if(employee.employment_status!==before.employmentStatus||employee.primary_org_id!==before.primaryOrgId||employee.position_id!==before.positionId||employee.manager_employee_id!==before.managerEmployeeId||employee.employment_type!==before.employmentType||dateOnly(employee.hire_date as string|Date)!==dateOnly(before.hireDate as string|Date))throw new ConflictException("Employee assignment or status changed after approval; return and refresh the application");const updateResult=await m.query(`UPDATE hr_employee SET employment_status='departed',departure_date=$1,update_by=$2,update_time=now(),version=version+1 WHERE id=$3 RETURNING id,employee_code,full_name,user_id,primary_org_id,position_id,manager_employee_id,employment_type,employment_status,hire_date,departure_date`,[row.planned_departure_date,a.sub,row.subject_employee_id]),updated=Array.isArray(updateResult[0])?updateResult[0][0]:updateResult[0];const event=(await m.query(`INSERT INTO hr_employment_event(tenant_id,park_id,employee_id,event_no,event_type,effective_date,before_snapshot,after_snapshot,reason,status,is_historical_import,create_by,update_by) VALUES($1,$2,$3,$4,'depart',$5,$6,$7,$8,'effective',false,$9,$9) RETURNING id`,[s.tenantId,s.parkId,row.subject_employee_id,row.application_no,row.planned_departure_date,JSON.stringify(employee),JSON.stringify(updated),String(row.reason).slice(0,500),a.sub]))[0];await m.query(`UPDATE hr_departure_application SET status='applied',applied_by=$1,applied_at=now(),employment_event_id=$2,update_by=$1,update_time=now(),version=version+1 WHERE id=$3`,[a.sub,event.id,id]);await this.append(m,s,id,"applied","approved","applied",a.sub);return this.detail(m,s,id,this.sensitive(a));});}catch(e){this.translate(e);}}

 private async clearance(s:TenantParkScope,a:JwtPrincipal,id:string,kind:"interview"|"survey"|"wage",status:string,fields:Record<string,unknown>){return this.db.transaction(async m=>{const row=await this.lockApproved(m,s,a,id);if(row[`${kind}_status`]!=="pending")throw new ConflictException(`Departure ${kind} evidence is already closed`);const actor=`${kind}_by`,at=`${kind}_at`,statusCol=`${kind}_status`,entries=Object.entries(fields),sets=[`${statusCol}=$1`,`${actor}=$2`,`${at}=now()`],args:unknown[]=[status,a.sub];for(const [key,value] of entries){args.push(value);sets.push(`${key}=$${args.length}`);}args.push(a.sub,id);sets.push(`update_by=$${args.length-1}`,"update_time=now()","version=version+1");await m.query(`UPDATE hr_departure_application SET ${sets.join(",")} WHERE id=$${args.length}`,args);await this.append(m,s,id,`${kind}_${status}`,"approved","approved",a.sub);return this.detail(m,s,id,this.sensitive(a));});}
 private validate(d:SaveHrDepartureDto){if(d.plannedDepartureDate<d.applicationDate)throw new BadRequestException("Planned departure date cannot be earlier than application date");}
 private async employeeFacts(m:EntityManager,s:TenantParkScope,a:JwtPrincipal,employeeId:string,currentId?:string){await this.assertOperationScope(m,s,a,employeeId);const employee=(await m.query(`SELECT e.id,e.employee_code,e.full_name,e.user_id,e.primary_org_id,e.position_id,e.manager_employee_id,e.employment_type,e.employment_status,e.hire_date,e.departure_date,o.org_name,p.position_name FROM hr_employee e LEFT JOIN sys_org o ON o.tenant_id=e.tenant_id AND o.park_id=e.park_id AND o.id=e.primary_org_id LEFT JOIN hr_position p ON p.tenant_id=e.tenant_id AND p.park_id=e.park_id AND p.id=e.position_id WHERE e.tenant_id=$1 AND e.park_id=$2 AND e.id=$3 AND e.is_deleted=false AND e.employment_status IN('probation','active','suspended') FOR SHARE OF e`,[s.tenantId,s.parkId,employeeId]))[0];if(!employee)throw new NotFoundException("Employee not found");const active=await m.query(`SELECT id FROM hr_departure_application WHERE tenant_id=$1 AND park_id=$2 AND subject_employee_id=$3 AND is_deleted=false AND status IN('draft','submitted','returned','approved') AND ($4::uuid IS NULL OR id<>$4::uuid) LIMIT 1`,[s.tenantId,s.parkId,employeeId,currentId??null]);if(active.length)throw new ConflictException("Employee already has an active departure application");return employee;}
 private snapshot(e:Record<string,unknown>){return {employeeId:e.id,employeeCode:e.employee_code,employeeName:e.full_name,userId:e.user_id,primaryOrgId:e.primary_org_id,orgName:e.org_name,positionId:e.position_id,positionName:e.position_name,managerEmployeeId:e.manager_employee_id,employmentType:e.employment_type,employmentStatus:e.employment_status,hireDate:e.hire_date,departureDate:e.departure_date};}
 private async assertOperationScope(m:EntityManager,s:TenantParkScope,a:JwtPrincipal,employeeId:string){if(this.has(a,HR_PERMISSIONS.HR_DEPARTURE_READ))return;if(!this.has(a,HR_PERMISSIONS.HR_DEPARTURE_TEAM_READ))throw new ForbiddenException("Departure employee is outside the permitted scope");const r=await m.query(`SELECT 1 FROM hr_employee e WHERE e.tenant_id=$1 AND e.park_id=$2 AND e.id=$3 AND e.is_deleted=false AND e.primary_org_id IN(${this.managedOrgSql("$4")}) LIMIT 1`,[s.tenantId,s.parkId,employeeId,a.sub]);if(!r[0])throw new ForbiddenException("Departure employee is outside the managed organization tree");}
 private async lockApproved(m:EntityManager,s:TenantParkScope,a:JwtPrincipal,id:string){const row=await this.lock(m,s,id);if(row.status!=="approved")throw new ConflictException("Departure clearance requires an approved application");await this.assertOperationScope(m,s,a,row.subject_employee_id);return row;}
 private async nextNo(m:EntityManager,s:TenantParkScope,date:string){const period=date.slice(0,7).replace("-",""),pattern=`^LZ${period}[0-9]{4}$`;await m.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`${s.tenantId}:${s.parkId}:LZ:${period}`]);const x=(await m.query(`SELECT COALESCE(MAX(right(candidate_no,4)::int),0)+1 n FROM (SELECT application_no candidate_no FROM hr_departure_application WHERE tenant_id=$1 AND park_id=$2 AND application_no ~ $3 UNION ALL SELECT event_no candidate_no FROM hr_employment_event WHERE tenant_id=$1 AND park_id=$2 AND event_no ~ $3) candidate`,[s.tenantId,s.parkId,pattern]))[0];const n=Number(x.n);if(n>9999)throw new ConflictException("Monthly departure number capacity is exhausted");return `LZ${period}${String(n).padStart(4,"0")}`;}
 private async lock(m:EntityManager,s:TenantParkScope,id:string){const rows=await m.query(`SELECT * FROM hr_departure_application WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`,[id,s.tenantId,s.parkId]) as Row[];if(!rows[0])throw new NotFoundException("Departure application not found");return rows[0];}
 private async detail(m:EntityManager,s:TenantParkScope,id:string,sensitive:boolean){const rows=await m.query(`SELECT d.*,e.employee_code,e.full_name employee_name,o.org_name FROM hr_departure_application d JOIN hr_employee e ON e.tenant_id=d.tenant_id AND e.park_id=d.park_id AND e.id=d.subject_employee_id LEFT JOIN sys_org o ON o.tenant_id=e.tenant_id AND o.park_id=e.park_id AND o.id=e.primary_org_id WHERE d.id=$1 AND d.tenant_id=$2 AND d.park_id=$3 AND d.is_deleted=false`,[id,s.tenantId,s.parkId]) as Row[];if(!rows[0])throw new NotFoundException("Departure application not found");return this.project(rows[0],sensitive);}
 private async append(m:EntityManager,s:TenantParkScope,id:string,action:string,from:string|null,to:string,actor:string){await m.query(`INSERT INTO hr_departure_action(tenant_id,park_id,application_id,sequence_no,action,from_status,to_status,actor_user_id,evidence_snapshot) SELECT $1::varchar,$2::varchar,$3::uuid,COALESCE(MAX(sequence_no),0)+1,$4::varchar,$5::varchar,$6::varchar,$7::uuid,jsonb_build_object('action',$4::varchar,'toStatus',$6::varchar) FROM hr_departure_action WHERE tenant_id=$1::varchar AND park_id=$2::varchar AND application_id=$3::uuid`,[s.tenantId,s.parkId,id,action,from,to,actor]);}
 private project(r:Row,sensitive:boolean){return {id:r.id,applicationNo:r.application_no,applicationName:r.application_name,employeeId:r.subject_employee_id,employeeCode:r.employee_code,employeeName:r.employee_name,orgName:r.org_name,applicationDate:dateOnly(r.application_date),plannedDepartureDate:dateOnly(r.planned_departure_date),departureType:r.departure_type,reason:sensitive?r.reason:undefined,status:r.status,reviewComment:sensitive?r.review_comment??null:undefined,interviewStatus:r.interview_status,surveyStatus:r.survey_status,handoverStatus:r.handover_status,wageStatus:r.wage_status,archiveStatus:r.archive_status,...(sensitive?{interviewPlace:r.interview_place??null,interviewSummary:r.interview_summary??null,surveyReasonCodes:r.survey_reason_codes??[],surveySummary:r.survey_summary??null,handoverToEmployeeId:r.handover_to_employee_id??null,handoverSummary:r.handover_summary??null,wageNote:r.wage_note??null,archiveNote:r.archive_note??null}:{}),appliedAt:r.applied_at??null};}
 private translate(error:unknown):never{const e=error as {code?:string;message?:string};if(e.code==="23505")throw new ConflictException("Departure application number or active employee already exists");if(e.message?.includes("HR_DEPARTURE_TRANSITION_INVALID"))throw new ConflictException("Departure application state changed concurrently");throw error;}
}
