import {Body,Controller,Get,Param,ParseUUIDPipe,Post,Put,Query,UseInterceptors} from "@nestjs/common";
import {HR_PERMISSIONS,type TenantParkScope} from "@jinhu/shared";
import {CurrentScope} from "../../shared/decorators/current-scope.decorator";
import {CurrentUser} from "../../shared/decorators/current-user.decorator";
import {RequireModule} from "../../shared/decorators/modules.decorator";
import {RequireAnyPermissions,RequirePermissions} from "../../shared/decorators/permissions.decorator";
import {IdempotencyInterceptor} from "../../shared/interceptors/idempotency.interceptor";
import type {JwtPrincipal} from "../../shared/types/jwt-principal";
import {AuditLog} from "../audit/decorators/audit-log.decorator";
import {HrDepartureActionDto,HrDepartureArchiveDto,HrDepartureHandoverDto,HrDepartureInterviewDto,HrDepartureListDto,HrDepartureReviewDto,HrDepartureSurveyDto,HrDepartureWageDto,SaveHrDepartureDto} from "./dto/hr-departure.dto";
import {HrDepartureService} from "./hr-departure.service";

@Controller("hr/departure-applications") @RequireModule("hr")
export class HrDepartureController {
 constructor(private readonly service:HrDepartureService){}
 @Get() @RequireAnyPermissions(HR_PERMISSIONS.HR_DEPARTURE_READ,HR_PERMISSIONS.HR_DEPARTURE_TEAM_READ,HR_PERMISSIONS.HR_DEPARTURE_SELF_READ) list(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrDepartureListDto){return this.service.list(s,a,q);}
 @Get("options") @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_MANAGE) options(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.options(s,a);}
 @Post() @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"创建离职申请",bizType:"hr_departure_application",captureBody:false}) create(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:SaveHrDepartureDto){return this.service.create(s,a,d);}
 @Put(":id") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"修改离职申请",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) update(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SaveHrDepartureDto){return this.service.update(s,a,id,d);}
 @Post(":id/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"提交或取消离职申请",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) act(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureActionDto){return this.service.act(s,a,id,d);}
 @Post(":id/review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"审核离职申请",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) review(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureReviewDto){return this.service.review(s,a,id,d);}
 @Post(":id/interview") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_INTERVIEW) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"记录离职面谈",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) interview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureInterviewDto){return this.service.interview(s,a,id,d);}
 @Post(":id/survey") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_SURVEY) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"记录离职调查",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) survey(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureSurveyDto){return this.service.survey(s,a,id,d);}
 @Post(":id/handover") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_HANDOVER) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"确认离职交接",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) handover(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureHandoverDto){return this.service.handover(s,a,id,d);}
 @Post(":id/wage-settlement") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_WAGE_SETTLE) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"确认离职工资结算",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) wage(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureWageDto){return this.service.wage(s,a,id,d);}
 @Post(":id/archive") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_ARCHIVE_CLOSE) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"关闭离职人事档案",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) archive(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrDepartureArchiveDto){return this.service.archive(s,a,id,d);}
 @Post(":id/apply") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_DEPARTURE_APPLY) @AuditLog({module:"人力资源管理",resource:"hr.departure_application",action:"生效员工离职",bizType:"hr_departure_application",bizIdParam:"id",captureBody:false}) apply(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.apply(s,a,id);}
}
