import "reflect-metadata";
import assert from "node:assert/strict";
import {test} from "node:test";
import {BadRequestException,ForbiddenException,ValidationPipe} from "@nestjs/common";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrFeedback360Service} from "./hr-feedback360.service";
import {HrFeedback360Controller} from "./hr-feedback360.controller";
import {HrFeedback360EmployeeOptionsDto,HrFeedback360SubjectOptionsDto} from "./dto/hr-feedback360-options.dto";
import {ANY_PERMISSIONS_KEY,PERMISSIONS_KEY} from "../../shared/decorators/permissions.decorator";
const scope={tenantId:'tenant',parkId:'park'},actor={...scope,sub:'actor',username:'synthetic',roles:[],permissions:[H.HR_FEEDBACK_CYCLE_MANAGE] as string[]};
function fixture(auditFailure=false){const calls:{sql:string;params:unknown[]}[]=[],audits:Record<string,unknown>[]=[],isolations:string[]=[];const manager={query:async(sql:string,params:unknown[])=>{calls.push({sql,params});return sql.startsWith('SELECT count')?[{total:601}]:[{id:'candidate',employeeCode:'SYN-601',fullName:'合成员工',orgId:'not-projected',cycleCode:'SYN',cycleName:'合成周期',subjectName:'合成对象',status:'responding',private:'excluded'}];}};const s=new HrFeedback360Service({query:manager.query,transaction:async(isolation:string,job:(m:typeof manager)=>Promise<unknown>)=>{isolations.push(isolation);return job(manager)}} as never,{recordOperationRequired:async(d:Record<string,unknown>)=>{if(auditFailure)throw Error('audit unavailable');audits.push(d)}} as never,{} as never);return{s,calls,audits,isolations};}
test('paged employee projection uses exact operation permission, shared snapshot and scope',async()=>{const {s,calls,audits,isolations}=fixture();assert.deepEqual(await s.employeeOptions(scope,actor,{page:31,page_size:20}),{items:[{id:'candidate',employeeCode:'SYN-601',fullName:'合成员工'}],total:601,page:31,page_size:20});assert.deepEqual(isolations,['REPEATABLE READ']);assert.match(calls[0]!.sql,/employment_status='active'/);assert.match(calls[0]!.sql,/ORDER BY employee_code,id LIMIT \$3 OFFSET \$4/);assert.deepEqual(calls[0]!.params,['tenant','park',20,600]);assert.deepEqual(audits[0]!.afterJson,{fieldGroups:['identity'],projection:'park',itemCount:1});});
test('unrelated atoms and foreign super principals fail before query or transaction',async()=>{for(const permissions of [[],[H.HR_EMPLOYEE_READ],[H.HR_FEEDBACK_READ],[H.HR_FEEDBACK_NOMINATION_REVIEW],[H.HR_FEEDBACK_RESPOND]]){const {s,calls,isolations}=fixture();await assert.rejects(s.employeeOptions(scope,{...actor,permissions},{page:1,page_size:20}),ForbiddenException);assert.equal(calls.length+isolations.length,0);}for(const isSuper of [false,true]){const {s,calls,isolations}=fixture();const foreign={...actor,parkId:'foreign',isSuper};await assert.rejects(s.employeeOptions(scope,foreign,{page:1,page_size:20}),ForbiddenException);await assert.rejects(s.cycleOptions(scope,foreign),ForbiddenException);await assert.rejects(s.subjectOperationOptions(scope,foreign,{page:1,page_size:20,purpose:'publish'}),ForbiddenException);assert.equal(calls.length+isolations.length,0);}});
test('nomination candidates preserve managed-tree and self relationship scope',async()=>{for(const team of [false,true]){const {s,calls}=fixture();await s.employeeOptions(scope,{...actor,permissions:[H.HR_FEEDBACK_NOMINATE,...(team?[H.HR_FEEDBACK_TEAM_READ]:[])]},{page:1,page_size:20});assert.equal(calls[0]!.params[2],'actor');assert.match(calls[0]!.sql,team?/WITH RECURSIVE managed_org/:/candidate.manager_employee_id=me.id/);}});
test('purpose requires its own exact atom and operational subject states',async()=>{for(const purpose of ['nominate','publish'] as const){const permissions=[purpose==='publish'?H.HR_FEEDBACK_RESULT_PUBLISH:H.HR_FEEDBACK_NOMINATE],{s,calls}=fixture();const result=await s.subjectOperationOptions(scope,{...actor,permissions},{page:31,page_size:20,purpose});assert.deepEqual(Object.keys(result.items[0]!).sort(),['cycleCode','cycleName','employeeCode','id','status','subjectName']);assert.match(calls[0]!.sql,purpose==='publish'?/x.status IN\('responding','closed'\)/:/x.status IN\('nominating','responding'\)/);const denied=fixture();await assert.rejects(denied.s.subjectOperationOptions(scope,{...actor,permissions},{page:1,page_size:20,purpose:purpose==='publish'?'nominate':'publish'}),ForbiddenException);assert.equal(denied.calls.length,0);}});
test('literal keyword bound values do not enter required audit',async()=>{for(const subjects of [false,true]){const {s,calls,audits}=fixture();if(subjects)await s.subjectOperationOptions(scope,{...actor,permissions:[H.HR_FEEDBACK_RESULT_PUBLISH]},{page:1,page_size:20,purpose:'publish',keyword:' A_%\\ '});else await s.employeeOptions(scope,actor,{page:1,page_size:20,keyword:' A_%\\ '});assert.equal(calls[0]!.params[2],'%A\\_\\%\\\\%');assert.ok(!JSON.stringify(audits).includes('A_'));assert.ok(!calls[0]!.sql.includes('A_'));}});
test('required audit failure prevents each operation response',async()=>{const {s}=fixture(true);await assert.rejects(s.employeeOptions(scope,actor,{page:1,page_size:20}),/audit unavailable/);await assert.rejects(s.subjectOperationOptions(scope,{...actor,permissions:[H.HR_FEEDBACK_RESULT_PUBLISH]},{page:1,page_size:20,purpose:'publish'}),/audit unavailable/);await assert.rejects(s.cycleOptions(scope,actor),/audit unavailable/);});
test('cycle metadata never queries employee or subject directory',async()=>{const {s,calls}=fixture();await s.cycleOptions(scope,actor);assert.equal(calls.length,2);assert.ok(calls.every(c=>!c.sql.includes('FROM hr_employee')&&!c.sql.includes('hr_feedback360_subject')));const denied=fixture();await assert.rejects(denied.s.cycleOptions(scope,{...actor,permissions:[H.HR_FEEDBACK_MODEL_MANAGE]}),ForbiddenException);assert.equal(denied.calls.length,0);});
test('controller metadata and HTTP validation enforce scalar bounds and purpose',async()=>{assert.deepEqual(Reflect.getMetadata(ANY_PERMISSIONS_KEY,HrFeedback360Controller.prototype.employeeOptions),[H.HR_FEEDBACK_CYCLE_MANAGE,H.HR_FEEDBACK_NOMINATE]);assert.deepEqual(Reflect.getMetadata(ANY_PERMISSIONS_KEY,HrFeedback360Controller.prototype.subjectOperationOptions),[H.HR_FEEDBACK_NOMINATE,H.HR_FEEDBACK_RESULT_PUBLISH]);assert.deepEqual(Reflect.getMetadata(PERMISSIONS_KEY,HrFeedback360Controller.prototype.cycleOptions),[H.HR_FEEDBACK_CYCLE_MANAGE]);const pipe=new ValidationPipe({transform:true,whitelist:true,forbidNonWhitelisted:true});for(const metatype of [HrFeedback360EmployeeOptionsDto,HrFeedback360SubjectOptionsDto]){const meta={type:'query' as const,metatype};for(const q of [{page:[]},{page:['1']},{page:true},{page:null},{page:'1e2'},{page:'0x10'},{page:''},{page:'2147483648'},{page_size:'101'},{keyword:['name']},{keyword:'a'.repeat(101)},{unknown:'x'}])await assert.rejects(pipe.transform(q,meta),BadRequestException);const defaults=await pipe.transform({},meta);assert.equal(defaults.page,1);assert.equal(defaults.page_size,20);}for(const purpose of [[],['publish'],'unknown',null])await assert.rejects(pipe.transform({purpose},{type:'query',metatype:HrFeedback360SubjectOptionsDto}),BadRequestException);const valid=await pipe.transform({page:'31',page_size:'100',keyword:' SYN-601 ',purpose:'publish'},{type:'query',metatype:HrFeedback360SubjectOptionsDto});assert.equal(valid.keyword,'SYN-601');assert.equal(valid.page,31);});
