import {Body,Controller,Delete,Get,Param,ParseUUIDPipe,Post,Put,Query,UseInterceptors} from "@nestjs/common";
import {HR_PERMISSIONS,type TenantParkScope} from "@jinhu/shared";
import {CurrentScope} from "../../shared/decorators/current-scope.decorator";
import {CurrentUser} from "../../shared/decorators/current-user.decorator";
import {RequireModule} from "../../shared/decorators/modules.decorator";
import {RequireAnyPermissions,RequirePermissions} from "../../shared/decorators/permissions.decorator";
import {IdempotencyInterceptor} from "../../shared/interceptors/idempotency.interceptor";
import type {JwtPrincipal} from "../../shared/types/jwt-principal";
import {AuditLog} from "../audit/decorators/audit-log.decorator";
import {ChangeHrGoalDto,CreateHrGoalCycleT6Dto,CreateHrGoalT6Dto,HrGoalActionDto,HrGoalCheckinT6Dto,HrGoalCycleActionDto,HrGoalListQueryDto,ReviewHrWorkReportT6Dto,SaveHrWorkReportDraftDto} from "./dto/hr-goal-report.dto";
import {HrGoalReportService} from "./hr-goal-report.service";

@Controller("hr") @RequireModule("hr")
export class HrGoalReportController{
 constructor(private readonly service:HrGoalReportService){}
 @Get("goal-cycles") @RequireAnyPermissions(HR_PERMISSIONS.HR_GOAL_READ,HR_PERMISSIONS.HR_GOAL_TEAM_READ,HR_PERMISSIONS.HR_GOAL_SELF_READ,HR_PERMISSIONS.HR_GOAL_MANAGE,HR_PERMISSIONS.HR_GOAL_CYCLE_MANAGE) cycles(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.listCycles(s,a);}
 @Post("goal-cycles") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_CYCLE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.goal_cycle",action:"创建目标周期",bizType:"hr_goal_cycle",captureBody:false}) createCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrGoalCycleT6Dto){return this.service.createCycle(s,a,d);}
 @Post("goal-cycles/:id/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_CYCLE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.goal_cycle",action:"办理目标周期状态",bizType:"hr_goal_cycle",bizIdParam:"id",captureBody:false}) cycleAction(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrGoalCycleActionDto){return this.service.cycleAction(s,a,id,d);}
 @Get("goals") @RequireAnyPermissions(HR_PERMISSIONS.HR_GOAL_READ,HR_PERMISSIONS.HR_GOAL_TEAM_READ) goals(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrGoalListQueryDto){return this.service.listGoals(s,a,q);}
 @Get("goals/me") @RequirePermissions(HR_PERMISSIONS.HR_GOAL_SELF_READ) myGoals(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrGoalListQueryDto){return this.service.listSelfGoals(s,a,q);}
 @Post("goals") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.goal",action:"创建目标",bizType:"hr_goal",captureBody:false}) createGoal(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrGoalT6Dto){return this.service.createGoal(s,a,d);}
 @Get("goals/options") @RequirePermissions(HR_PERMISSIONS.HR_GOAL_MANAGE) options(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.goalOptions(s,a);}
 @Put("goals/:id") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_CHANGE) @AuditLog({module:"人力资源管理",resource:"hr.goal",action:"变更目标口径",bizType:"hr_goal",bizIdParam:"id",captureBody:false}) changeGoal(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ChangeHrGoalDto){return this.service.changeGoal(s,a,id,d);}
 @Post("goals/:id/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.goal",action:"办理目标状态",bizType:"hr_goal",bizIdParam:"id",captureBody:false}) goalAction(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrGoalActionDto){return this.service.goalAction(s,a,id,d);}
 @Get("goals/:id/checkins") @RequireAnyPermissions(HR_PERMISSIONS.HR_GOAL_READ,HR_PERMISSIONS.HR_GOAL_TEAM_READ,HR_PERMISSIONS.HR_GOAL_SELF_READ) checkins(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.goalCheckins(s,a,id);}
 @Post("goals/:id/checkins") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_CHECKIN) @AuditLog({module:"人力资源管理",resource:"hr.goal_checkin",action:"更新本人目标进度",bizType:"hr_goal",bizIdParam:"id",captureBody:false}) checkin(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrGoalCheckinT6Dto){return this.service.checkin(s,a,id,d);}
 @Get("work-reports/me") @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_SELF_READ) myReports(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.myReports(s,a);}
 @Post("work-reports/me") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_DRAFT) @AuditLog({module:"人力资源管理",resource:"hr.work_report",action:"创建工作汇报草稿",bizType:"hr_work_report",captureBody:false}) createDraft(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:SaveHrWorkReportDraftDto){return this.service.createDraft(s,a,d);}
 @Put("work-reports/:id") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_DRAFT) @AuditLog({module:"人力资源管理",resource:"hr.work_report",action:"更新工作汇报草稿",bizType:"hr_work_report",bizIdParam:"id",captureBody:false}) updateDraft(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SaveHrWorkReportDraftDto){return this.service.updateDraft(s,a,id,d);}
 @Delete("work-reports/:id") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_DRAFT) @AuditLog({module:"人力资源管理",resource:"hr.work_report",action:"撤销工作汇报草稿",bizType:"hr_work_report",bizIdParam:"id",captureBody:false}) cancel(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.cancel(s,a,id);}
 @Post("work-reports/:id/submit") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_SUBMIT) @AuditLog({module:"人力资源管理",resource:"hr.work_report",action:"提交工作汇报",bizType:"hr_work_report",bizIdParam:"id",captureBody:false}) submit(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.submit(s,a,id);}
 @Get("work-reports/team") @RequireAnyPermissions(HR_PERMISSIONS.HR_WORK_REPORT_TEAM_READ,HR_PERMISSIONS.HR_WORK_REPORT_REVIEW) teamReports(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.teamReports(s,a);}
 @Post("work-reports/:id/review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.work_report",action:"审核工作汇报",bizType:"hr_work_report",bizIdParam:"id",captureBody:false}) review(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ReviewHrWorkReportT6Dto){return this.service.review(s,a,id,d);}
 @Get("work-reports/:id/actions") @RequireAnyPermissions(HR_PERMISSIONS.HR_WORK_REPORT_SELF_READ,HR_PERMISSIONS.HR_WORK_REPORT_TEAM_READ,HR_PERMISSIONS.HR_WORK_REPORT_REVIEW) actions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.reportActions(s,a,id);}
}
