import "reflect-metadata";
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {test} from "node:test";
import {DataSource} from "typeorm";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrGoalReportService} from "./hr-goal-report.service";
test("PostgreSQL operation contexts include only writable drafts and owned active checkins",{skip:process.env.HR_GOAL_CONTEXT_PG_REQUIRED!=="1"},async()=>{
 assert.equal(process.env.POSTGRES_HOST,"127.0.0.1");assert.equal(process.env.POSTGRES_PORT,"15483");const config={type:"postgres" as const,host:"127.0.0.1",port:15483,username:"postgres"},name=`hr_goal_context_${randomUUID().replaceAll("-","")}`;const admin=new DataSource({...config,database:"postgres"});let db:DataSource|undefined,created=false;
 try{await admin.initialize();await admin.query(`CREATE DATABASE ${name}`);created=true;db=new DataSource({...config,database:name});await db.initialize();await db.query(`CREATE TABLE sys_org(id uuid PRIMARY KEY,tenant_id text,park_id text,parent_id uuid,leader_user_id uuid,org_name text,status text DEFAULT 'enabled',is_deleted boolean DEFAULT false);CREATE TABLE hr_employee(id uuid PRIMARY KEY,tenant_id text,park_id text,user_id uuid,primary_org_id uuid,full_name text,is_deleted boolean DEFAULT false);CREATE TABLE hr_goal(id uuid PRIMARY KEY,tenant_id text,park_id text,cycle_id uuid,parent_goal_id uuid,goal_level text,goal_name text,owner_org_id uuid,owner_employee_id uuid,weight numeric DEFAULT 1,metric_type text DEFAULT 'numeric',metric_name text DEFAULT 'Synthetic metric',target_value numeric DEFAULT 0,current_value numeric DEFAULT 0,unit text DEFAULT 'items',progress numeric DEFAULT 0,start_date date DEFAULT '2026-10-01',due_date date DEFAULT '2026-10-31',status text,current_version_no int DEFAULT 1,create_time timestamptz DEFAULT now(),is_deleted boolean DEFAULT false)`);
 const scope={tenantId:"t",parkId:"p"},manager=randomUUID(),self=randomUUID(),root=randomUUID(),child=randomUUID(),sibling=randomUUID(),employee=randomUUID(),other=randomUUID(),deleted=randomUUID(),cycle=randomUUID();
 await db.query(`INSERT INTO sys_org(id,tenant_id,park_id,parent_id,leader_user_id,org_name)VALUES($1,'t','p',NULL,$4,'Root'),($2,'t','p',$1,NULL,'Child'),($3,'t','p',NULL,NULL,'Sibling')`,[root,child,sibling,manager]);
 await db.query(`INSERT INTO hr_employee(id,tenant_id,park_id,user_id,primary_org_id,full_name,is_deleted)VALUES($1,'t','p',$4,$5,'Owned',false),($2,'t','p',$6,$5,'Other',false),($3,'t','p',$4,$5,'Deleted',true)`,[employee,other,deleted,self,child,randomUUID()]);
 const put=async(label:string,level:string,status:string,org:string|null=null,owner:string|null=null,t="t",p="p",gone=false)=>{const id=randomUUID();await db!.query(`INSERT INTO hr_goal(id,tenant_id,park_id,cycle_id,goal_level,goal_name,owner_org_id,owner_employee_id,status,is_deleted)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,t,p,cycle,level,label,org,owner,status,gone]);return id;};
 const groupDraft=await put("Group draft","group","draft"),groupActive=await put("Group active","group","active"),department=await put("Own department draft","department","draft",root),nested=await put("Nested department draft","department","draft",child),owned=await put("Own active","employee","active",null,employee),ownDraft=await put("Own draft","employee","draft",null,employee),others=await put("Other active","employee","active",null,other);
 const outsider=await put("Sibling draft","department","draft",sibling);await put("Foreign tenant","department","draft",root,null,"foreign");await put("Foreign park","employee","active",null,employee,"t","foreign");await put("Deleted employee","employee","active",null,deleted);await put("Deleted goal","employee","active",null,employee,"t","p",true);await put("Own completed","employee","completed",null,employee);
 const actor={...scope,sub:manager,username:"synthetic",roles:[],permissions:[H.HR_GOAL_MANAGE]},audits:unknown[]=[];const service=new HrGoalReportService(db,{} as never,{recordOperationRequired:async(a:unknown)=>{audits.push(a)}} as never);const context=await service.managementGoalContext(scope,actor);const ids=context.items.map(g=>g.id);for(const id of [department,nested,owned,ownDraft,others])assert.ok(ids.includes(id));for(const id of [groupDraft,groupActive,outsider])assert.ok(!ids.includes(id));assert.equal(context.items.length,6);assert.deepEqual(new Set(context.parents.map(g=>g.id)),new Set([groupActive,department,nested]));assert.equal("ownerEmployeeId" in context.parents[0]!,false);assert.equal("tenant_id" in context.items[0]!,false);
 const own=await service.goalCheckinContext(scope,{...actor,sub:self,permissions:[H.HR_GOAL_CHECKIN]});assert.deepEqual(own.map(g=>g.id),[owned]);assert.equal(own[0]?.currentValue,"0");const empty=await service.goalCheckinContext(scope,{...actor,sub:randomUUID(),permissions:[H.HR_GOAL_CHECKIN]});assert.deepEqual(empty,[]);const park=await service.managementGoalContext(scope,{...actor,permissions:[H.HR_GOAL_MANAGE,H.HR_GOAL_READ]});assert.ok(park.items.some(g=>g.id===groupDraft));assert.ok(park.items.some(g=>g.id===outsider));assert.equal(audits.length,4);
 }finally{if(db?.isInitialized)await db.destroy();if(admin.isInitialized){if(created){await admin.query(`DROP DATABASE ${name}`);assert.equal((await admin.query("SELECT count(*)::int n FROM pg_database WHERE datname=$1",[name]))[0].n,0);}await admin.destroy();}}
});
