import { BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException } from "@nestjs/common";
import { HR_PERMISSIONS,type TenantParkScope } from "@jinhu/shared";
import { DataSource,EntityManager } from "typeorm";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { AuditService } from "../audit/audit.service";
import { HrJobChangeActionDto,HrJobChangeListDto,HrJobChangeReviewDto,SaveHrJobChangeDto } from "./dto/hr-job-change.dto";
import { firstHrMutationRow } from "./hr-query-result";
import { recordHrSensitiveRead } from "./hr-sensitive-read-audit";

type Access="park"|"managed_org_tree"|"self"|"none";
type Row=Record<string,unknown>&{id:string;application_no:string;application_name:string;applicant_user_id:string;subject_employee_id:string;application_date:string;effective_date:string;status:string;before_org_id:string;before_position_id:string|null;after_org_id:string;after_position_id:string|null;before_snapshot:Record<string,unknown>;after_snapshot:Record<string,unknown>};

@Injectable()
export class HrJobChangeService {
 constructor(private readonly db:DataSource,private readonly audit:AuditService){}
 private has(a:JwtPrincipal,p:string){return Boolean(a.isSuper||a.permissions.includes("*")||a.permissions.includes(p));}
 private access(a:JwtPrincipal):Access{if(this.has(a,HR_PERMISSIONS.HR_JOB_CHANGE_READ))return "park";if(this.has(a,HR_PERMISSIONS.HR_JOB_CHANGE_TEAM_READ))return "managed_org_tree";if(this.has(a,HR_PERMISSIONS.HR_JOB_CHANGE_SELF_READ))return "self";return "none";}
 private managedOrgSql(actorParam:string){return `WITH RECURSIVE managed_org AS(SELECT id FROM sys_org WHERE tenant_id=$1 AND park_id=$2 AND leader_user_id=${actorParam} AND is_deleted=false AND status='enabled' UNION ALL SELECT c.id FROM sys_org c JOIN managed_org p ON c.parent_id=p.id WHERE c.tenant_id=$1 AND c.park_id=$2 AND c.is_deleted=false AND c.status='enabled') SELECT id FROM managed_org`;}

 async list(s:TenantParkScope,a:JwtPrincipal,q:HrJobChangeListDto){
  const access=this.access(a);if(access==="none")return {items:[],total:0,page:q.page,page_size:q.page_size};
  const args:unknown[]=[s.tenantId,s.parkId],where=["j.tenant_id=$1","j.park_id=$2","j.is_deleted=false"];
  if(access!=="park"){args.push(a.sub);const actor=`$${args.length}`;where.push(access==="self"?`(j.applicant_user_id=${actor} OR e.user_id=${actor})`:`e.primary_org_id IN(${this.managedOrgSql(actor)})`);}
  if(q.status){args.push(q.status);where.push(`j.status=$${args.length}`);}
  if(q.keyword){args.push(`%${q.keyword}%`);where.push(`(j.application_no ILIKE $${args.length} OR j.application_name ILIKE $${args.length} OR e.employee_code ILIKE $${args.length} OR e.full_name ILIKE $${args.length})`);}
  const from=`FROM hr_job_change_application j JOIN hr_employee e ON e.tenant_id=j.tenant_id AND e.park_id=j.park_id AND e.id=j.subject_employee_id LEFT JOIN sys_org bo ON bo.tenant_id=j.tenant_id AND bo.park_id=j.park_id AND bo.id=j.before_org_id LEFT JOIN sys_org ao ON ao.tenant_id=j.tenant_id AND ao.park_id=j.park_id AND ao.id=j.after_org_id LEFT JOIN hr_position bp ON bp.tenant_id=j.tenant_id AND bp.park_id=j.park_id AND bp.id=j.before_position_id LEFT JOIN hr_position ap ON ap.tenant_id=j.tenant_id AND ap.park_id=j.park_id AND ap.id=j.after_position_id WHERE ${where.join(" AND ")}`;
  const count=await this.db.query(`SELECT count(*)::int total ${from}`,args) as Array<{total:number}>;args.push(q.page_size,(q.page-1)*q.page_size);
  const rows=await this.db.query(`SELECT j.*,e.employee_code,e.full_name employee_name,bo.org_name before_org_name,ao.org_name after_org_name,bp.position_name before_position_name,ap.position_name after_position_name ${from} ORDER BY j.application_date DESC,j.create_time DESC,j.id LIMIT $${args.length-1} OFFSET $${args.length}`,args) as Row[];
  const items=rows.map(r=>this.project(r));await recordHrSensitiveRead(this.audit,s,a,{resource:"hr.job_change_application",action:"读取岗位变更申请",bizType:"hr_job_change_application",bizId:null,path:"/hr/job-change-applications",fieldGroups:[],projection:access==="managed_org_tree"?"team":access,itemCount:items.length});
  return {items,total:Number(count[0]?.total??0),page:q.page,page_size:q.page_size};
 }

 async options(s:TenantParkScope,a:JwtPrincipal){
  const park=this.has(a,HR_PERMISSIONS.HR_JOB_CHANGE_READ),args:unknown[]=[s.tenantId,s.parkId],employeeFilter=park?"":(args.push(a.sub),` AND e.primary_org_id IN(${this.managedOrgSql("$3")})`);
  const [employees,orgs,positions]=await Promise.all([
   this.db.query(`SELECT e.id,e.employee_code "employeeCode",e.full_name "employeeName",e.primary_org_id "orgId",e.position_id "positionId",o.org_name "orgName",p.position_name "positionName" FROM hr_employee e LEFT JOIN sys_org o ON o.tenant_id=e.tenant_id AND o.park_id=e.park_id AND o.id=e.primary_org_id LEFT JOIN hr_position p ON p.tenant_id=e.tenant_id AND p.park_id=e.park_id AND p.id=e.position_id WHERE e.tenant_id=$1 AND e.park_id=$2 AND e.is_deleted=false AND e.employment_status IN('probation','active','suspended')${employeeFilter} ORDER BY e.full_name,e.id LIMIT 500`,args),
   this.db.query(`SELECT id,org_name "orgName" FROM sys_org WHERE tenant_id=$1 AND park_id=$2 AND is_deleted=false AND status='enabled' ORDER BY sort_order,org_name,id`,[s.tenantId,s.parkId]),
   this.db.query(`SELECT id,org_id "orgId",position_code "positionCode",position_name "positionName" FROM hr_position WHERE tenant_id=$1 AND park_id=$2 AND is_deleted=false AND status='enabled' ORDER BY position_name,id`,[s.tenantId,s.parkId])
  ]);return {employees,orgs,positions};
 }

 async create(s:TenantParkScope,a:JwtPrincipal,d:SaveHrJobChangeDto){this.validate(d);try{return await this.db.transaction(async m=>{
  const facts=await this.facts(m,s,a,d);const no=await this.nextNo(m,s,d.effectiveDate);
  const rows=await m.query(`INSERT INTO hr_job_change_application(tenant_id,park_id,application_no,application_name,applicant_user_id,subject_employee_id,application_date,effective_date,change_type,before_org_id,before_position_id,after_org_id,after_position_id,reason,before_snapshot,after_snapshot,create_by,update_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$5,$5) RETURNING *`,[s.tenantId,s.parkId,no,d.applicationName,a.sub,d.employeeId,d.applicationDate,d.effectiveDate,d.changeType,facts.employee.primary_org_id,facts.employee.position_id,d.afterOrgId,d.afterPositionId??null,d.reason,JSON.stringify(facts.before),JSON.stringify(facts.after)]) as Row[];
  await this.append(m,s,rows[0]!.id,"created",null,"draft",a.sub,null);return this.detail(m,s,rows[0]!.id);
 });}catch(e){this.translate(e);}}

 async update(s:TenantParkScope,a:JwtPrincipal,id:string,d:SaveHrJobChangeDto){this.validate(d);try{return await this.db.transaction(async m=>{
  const row=await this.lock(m,s,id);if(!["draft","returned"].includes(row.status))throw new ConflictException("Only draft or returned job-change applications can be edited");await this.assertManageScope(m,s,a,row.subject_employee_id);const facts=await this.facts(m,s,a,d,id);
  await m.query(`UPDATE hr_job_change_application SET application_name=$1,subject_employee_id=$2,application_date=$3,effective_date=$4,change_type=$5,before_org_id=$6,before_position_id=$7,after_org_id=$8,after_position_id=$9,reason=$10,before_snapshot=$11,after_snapshot=$12,update_by=$13,update_time=now(),version=version+1 WHERE id=$14`,[d.applicationName,d.employeeId,d.applicationDate,d.effectiveDate,d.changeType,facts.employee.primary_org_id,facts.employee.position_id,d.afterOrgId,d.afterPositionId??null,d.reason,JSON.stringify(facts.before),JSON.stringify(facts.after),a.sub,id]);
  await this.append(m,s,id,"updated",row.status,row.status,a.sub,null);return this.detail(m,s,id);
 });}catch(e){this.translate(e);}}

 async act(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrJobChangeActionDto){return this.db.transaction(async m=>{
  const row=await this.lock(m,s,id);await this.assertManageScope(m,s,a,row.subject_employee_id);const allowed:Record<string,string[]>={submit:["draft"],resubmit:["returned"],cancel:["draft","submitted","returned"]};if(!allowed[d.action]?.includes(row.status))throw new ConflictException("Job-change action is not allowed from current status");
  const next=d.action==="cancel"?"cancelled":"submitted",action=d.action==="submit"?"submitted":d.action==="resubmit"?"resubmitted":"cancelled";
  await m.query(`UPDATE hr_job_change_application SET status=$1,review_comment=NULL,reviewed_by=NULL,reviewed_at=NULL,update_by=$2,update_time=now(),version=version+1 WHERE id=$3`,[next,a.sub,id]);await this.append(m,s,id,action,row.status,next,a.sub,d.comment??null);return this.detail(m,s,id);
 });}

 async review(s:TenantParkScope,a:JwtPrincipal,id:string,d:HrJobChangeReviewDto){return this.db.transaction(async m=>{
  const row=await this.lock(m,s,id);if(row.status!=="submitted")throw new ConflictException("Only submitted job-change applications can be reviewed");if(row.applicant_user_id===a.sub)throw new ForbiddenException("Applicants cannot review their own job-change application");if(d.action==="return"&&!d.comment?.trim())throw new BadRequestException("A return comment is required");
  const next=d.action==="approve"?"approved":"returned";await m.query(`UPDATE hr_job_change_application SET status=$1,review_comment=$2,reviewed_by=$3,reviewed_at=now(),update_by=$3,update_time=now(),version=version+1 WHERE id=$4`,[next,d.comment??null,a.sub,id]);await this.append(m,s,id,next,"submitted",next,a.sub,d.comment??null);return this.detail(m,s,id);
 });}

 async apply(s:TenantParkScope,a:JwtPrincipal,id:string){try{return await this.db.transaction(async m=>{
  const row=await this.lock(m,s,id);if(row.status!=="approved")throw new ConflictException("Only approved job-change applications can be applied");if(row.effective_date>new Date().toISOString().slice(0,10))throw new ConflictException("A future-dated job change cannot be applied yet");
  const employee=(await m.query(`SELECT id,employee_code,full_name,primary_org_id,position_id,employment_status FROM hr_employee WHERE tenant_id=$1 AND park_id=$2 AND id=$3 AND is_deleted=false FOR UPDATE`,[s.tenantId,s.parkId,row.subject_employee_id]))[0] as Record<string,unknown>|undefined;if(!employee)throw new NotFoundException("Employee not found");if(employee.primary_org_id!==row.before_org_id||employee.position_id!==row.before_position_id)throw new ConflictException("Employee organization or position changed after approval; return and refresh the application");
  await this.assertTarget(m,s,row.after_org_id,row.after_position_id);const updated=firstHrMutationRow<Record<string,unknown>>(await m.query(`UPDATE hr_employee SET primary_org_id=$1,position_id=$2,update_by=$3,update_time=now(),version=version+1 WHERE id=$4 RETURNING id,employee_code,full_name,primary_org_id,position_id,employment_status`,[row.after_org_id,row.after_position_id,a.sub,row.subject_employee_id]));if(!updated)throw new ConflictException("Employee changed concurrently");
  const event=(await m.query(`INSERT INTO hr_employment_event(tenant_id,park_id,employee_id,event_no,event_type,effective_date,before_snapshot,after_snapshot,reason,status,is_historical_import,create_by,update_by) VALUES($1,$2,$3,$4,'transfer',$5,$6,$7,$8,'effective',false,$9,$9) RETURNING id`,[s.tenantId,s.parkId,row.subject_employee_id,row.application_no,row.effective_date,JSON.stringify(employee),JSON.stringify(updated),String(row.reason??"").slice(0,500),a.sub]))[0];
  await m.query(`UPDATE hr_job_change_application SET status='applied',applied_by=$1,applied_at=now(),employment_event_id=$2,update_by=$1,update_time=now(),version=version+1 WHERE id=$3`,[a.sub,event.id,id]);await this.append(m,s,id,"applied","approved","applied",a.sub,null);return this.detail(m,s,id);
 });}catch(e){this.translate(e);}}

 private validate(d:SaveHrJobChangeDto){if(d.effectiveDate<d.applicationDate)throw new BadRequestException("Effective date cannot be earlier than application date");}
 private async facts(m:EntityManager,s:TenantParkScope,a:JwtPrincipal,d:SaveHrJobChangeDto,currentId?:string){
  const employee=(await m.query(`SELECT e.id,e.employee_code,e.full_name,e.primary_org_id,e.position_id,o.org_name,p.position_name FROM hr_employee e JOIN sys_org o ON o.tenant_id=e.tenant_id AND o.park_id=e.park_id AND o.id=e.primary_org_id LEFT JOIN hr_position p ON p.tenant_id=e.tenant_id AND p.park_id=e.park_id AND p.id=e.position_id WHERE e.tenant_id=$1 AND e.park_id=$2 AND e.id=$3 AND e.is_deleted=false AND e.employment_status IN('probation','active','suspended') FOR SHARE OF e,o`,[s.tenantId,s.parkId,d.employeeId]))[0];if(!employee)throw new NotFoundException("Employee not found");await this.assertManageScope(m,s,a,d.employeeId);const target=await this.assertTarget(m,s,d.afterOrgId,d.afterPositionId??null);if(employee.primary_org_id===d.afterOrgId&&employee.position_id===(d.afterPositionId??null))throw new BadRequestException("Target organization and position must differ from the current assignment");
  const active=await m.query(`SELECT id FROM hr_job_change_application WHERE tenant_id=$1 AND park_id=$2 AND subject_employee_id=$3 AND is_deleted=false AND status IN('draft','submitted','returned','approved') AND ($4::uuid IS NULL OR id<>$4::uuid) LIMIT 1`,[s.tenantId,s.parkId,d.employeeId,currentId??null]);if(active.length)throw new ConflictException("Employee already has an active job-change application");
  return {employee,before:{employeeId:employee.id,employeeCode:employee.employee_code,employeeName:employee.full_name,orgId:employee.primary_org_id,orgName:employee.org_name,positionId:employee.position_id,positionName:employee.position_name},after:{employeeId:employee.id,employeeCode:employee.employee_code,employeeName:employee.full_name,orgId:target.org_id,orgName:target.org_name,positionId:target.position_id,positionName:target.position_name}};
 }
 private async assertTarget(m:EntityManager,s:TenantParkScope,orgId:string,positionId:string|null){const org=(await m.query(`SELECT id org_id,org_name FROM sys_org WHERE tenant_id=$1 AND park_id=$2 AND id=$3 AND is_deleted=false AND status='enabled' FOR SHARE`,[s.tenantId,s.parkId,orgId]))[0];if(!org)throw new NotFoundException("Target organization not found");if(!positionId)return {...org,position_id:null,position_name:null};const p=(await m.query(`SELECT id position_id,position_name,org_id FROM hr_position WHERE tenant_id=$1 AND park_id=$2 AND id=$3 AND org_id=$4 AND is_deleted=false AND status='enabled' FOR SHARE`,[s.tenantId,s.parkId,positionId,orgId]))[0];if(!p)throw new BadRequestException("Target position is unavailable or does not belong to the target organization");return {...org,...p};}
 private async assertManageScope(m:EntityManager,s:TenantParkScope,a:JwtPrincipal,employeeId:string){if(this.has(a,HR_PERMISSIONS.HR_JOB_CHANGE_READ))return;const r=await m.query(`SELECT 1 FROM hr_employee e WHERE e.tenant_id=$1 AND e.park_id=$2 AND e.id=$3 AND e.is_deleted=false AND e.primary_org_id IN(${this.managedOrgSql("$4")}) LIMIT 1`,[s.tenantId,s.parkId,employeeId,a.sub]);if(!r[0])throw new ForbiddenException("Employee is outside the managed organization tree");}
 private async nextNo(m:EntityManager,s:TenantParkScope,effectiveDate:string){const period=effectiveDate.slice(0,7).replace("-",""),pattern=`^DZ${period}[0-9]{4}$`;await m.query(`SELECT pg_advisory_xact_lock(hashtextextended($1,0))`,[`${s.tenantId}:${s.parkId}:DZ:${period}`]);const x=(await m.query(`SELECT COALESCE(MAX(right(candidate_no,4)::int),0)+1 n FROM (SELECT application_no candidate_no FROM hr_job_change_application WHERE tenant_id=$1 AND park_id=$2 AND application_no ~ $3 UNION ALL SELECT event_no candidate_no FROM hr_employment_event WHERE tenant_id=$1 AND park_id=$2 AND event_no ~ $3) candidate`,[s.tenantId,s.parkId,pattern]))[0];const n=Number(x.n);if(n>9999)throw new ConflictException("Monthly job-change number capacity is exhausted");return `DZ${period}${String(n).padStart(4,"0")}`;}
 private async lock(m:EntityManager,s:TenantParkScope,id:string){const rows=await m.query(`SELECT * FROM hr_job_change_application WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`,[id,s.tenantId,s.parkId]) as Row[];if(!rows[0])throw new NotFoundException("Job-change application not found");return rows[0];}
 private async detail(m:EntityManager,s:TenantParkScope,id:string){const rows=await m.query(`SELECT j.*,e.employee_code,e.full_name employee_name,bo.org_name before_org_name,ao.org_name after_org_name,bp.position_name before_position_name,ap.position_name after_position_name FROM hr_job_change_application j JOIN hr_employee e ON e.tenant_id=j.tenant_id AND e.park_id=j.park_id AND e.id=j.subject_employee_id LEFT JOIN sys_org bo ON bo.tenant_id=j.tenant_id AND bo.park_id=j.park_id AND bo.id=j.before_org_id LEFT JOIN sys_org ao ON ao.tenant_id=j.tenant_id AND ao.park_id=j.park_id AND ao.id=j.after_org_id LEFT JOIN hr_position bp ON bp.tenant_id=j.tenant_id AND bp.park_id=j.park_id AND bp.id=j.before_position_id LEFT JOIN hr_position ap ON ap.tenant_id=j.tenant_id AND ap.park_id=j.park_id AND ap.id=j.after_position_id WHERE j.id=$1 AND j.tenant_id=$2 AND j.park_id=$3 AND j.is_deleted=false`,[id,s.tenantId,s.parkId]) as Row[];if(!rows[0])throw new NotFoundException("Job-change application not found");return this.project(rows[0]);}
 private async append(m:EntityManager,s:TenantParkScope,id:string,action:string,from:string|null,to:string,actor:string,comment:string|null){await m.query(`INSERT INTO hr_job_change_action(tenant_id,park_id,application_id,sequence_no,action,from_status,to_status,comment,actor_user_id) SELECT $1::varchar,$2::varchar,$3::uuid,COALESCE(MAX(sequence_no),0)+1,$4::varchar,$5::varchar,$6::varchar,$7::text,$8::uuid FROM hr_job_change_action WHERE tenant_id=$1::varchar AND park_id=$2::varchar AND application_id=$3::uuid`,[s.tenantId,s.parkId,id,action,from,to,comment,actor]);}
 private project(r:Row){return {id:r.id,applicationNo:r.application_no,applicationName:r.application_name,employeeId:r.subject_employee_id,employeeCode:r.employee_code,employeeName:r.employee_name,applicationDate:r.application_date,effectiveDate:r.effective_date,changeType:r.change_type,beforeOrgId:r.before_org_id,beforeOrgName:r.before_org_name,beforePositionId:r.before_position_id,beforePositionName:r.before_position_name,afterOrgId:r.after_org_id,afterOrgName:r.after_org_name,afterPositionId:r.after_position_id,afterPositionName:r.after_position_name,reason:r.reason,status:r.status,reviewComment:r.review_comment??null,reviewedAt:r.reviewed_at??null,appliedAt:r.applied_at??null};}
 private translate(error:unknown):never{const e=error as {code?:string;message?:string};if(e.code==="23505")throw new ConflictException("Job-change application number or active employee already exists");if(e.message?.includes("HR_JOB_CHANGE_TRANSITION_INVALID"))throw new ConflictException("Job-change application state changed concurrently");throw error;}
}
