import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {after,before,test} from "node:test";
import {DataSource} from "typeorm";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {HrJobChangeService} from "./hr-job-change.service";
import {HrJobChangeEmployeeOptionsDto} from "./dto/hr-job-change.dto";

const enabled=process.env.HR_JOB_CHANGE_SELECTION_PG_TEST==="1",scope={tenantId:"tenant",parkId:"park"},schema=`job_change_selection_${randomUUID().replaceAll("-","")}`;
const leader=randomUUID(),root=randomUUID(),child=randomUUID(),otherOrg=randomUUID();let db:DataSource,service:HrJobChangeService;
const actor=(permissions:string[])=>({sub:leader,username:"selection-test",...scope,roles:[],permissions});
const query=(value:Partial<HrJobChangeEmployeeOptionsDto>={})=>Object.assign(new HrJobChangeEmployeeOptionsDto(),value);

before(async()=>{if(!enabled)return;if(process.env.POSTGRES_HOST!=="127.0.0.1"||process.env.POSTGRES_PORT!=="55499"||process.env.POSTGRES_DB!=="hr_selection_synthetic")throw new Error("Requires the owned job-change selection PostgreSQL fixture");db=new DataSource({type:"postgres",host:"127.0.0.1",port:55499,username:"jinhu",password:process.env.POSTGRES_PASSWORD,database:"hr_selection_synthetic",extra:{options:`-c search_path=${schema}`}});await db.initialize();await db.query(`CREATE SCHEMA "${schema}"; CREATE TABLE sys_org(id uuid PRIMARY KEY,tenant_id text NOT NULL,park_id text NOT NULL,parent_id uuid,leader_user_id uuid,is_deleted boolean NOT NULL DEFAULT false,status text NOT NULL DEFAULT 'enabled'); CREATE TABLE hr_employee(id uuid PRIMARY KEY,tenant_id text NOT NULL,park_id text NOT NULL,employee_code text NOT NULL,full_name text NOT NULL,primary_org_id uuid,is_deleted boolean NOT NULL DEFAULT false,employment_status text NOT NULL)`);await db.query(`INSERT INTO sys_org(id,tenant_id,park_id,parent_id,leader_user_id) VALUES($1,'tenant','park',NULL,$2),($3,'tenant','park',$1,NULL),($4,'tenant','park',NULL,NULL)`,[root,leader,child,otherOrg]);await db.query(`INSERT INTO hr_employee SELECT gen_random_uuid(),'tenant','park','EMP-'||lpad(n::text,4,'0'),'Employee '||lpad(n::text,4,'0'),$1,false,CASE WHEN n%3=0 THEN 'probation' WHEN n%3=1 THEN 'active' ELSE 'suspended' END FROM generate_series(1,521)n`,[child]);await db.query(`INSERT INTO hr_employee VALUES(gen_random_uuid(),'tenant','park','LITERAL','Literal %_\\',$1,false,'active'),(gen_random_uuid(),'tenant','park','OUTSIDE','Outside',$2,false,'active'),(gen_random_uuid(),'tenant','foreign','FOREIGN-PARK','Foreign',$1,false,'active'),(gen_random_uuid(),'tenant','park','DEPARTED','Departed',$1,false,'departed'),(gen_random_uuid(),'tenant','park','DELETED','Deleted',$1,true,'active')`,[child,otherOrg]);service=new HrJobChangeService(db,{recordOperationRequired:async()=>undefined} as never);});
after(async()=>{if(!db?.isInitialized)return;try{await db.query(`DROP SCHEMA "${schema}" CASCADE`);}finally{await db.destroy();}});

test("actual PostgreSQL job-change candidates page beyond 500 with literal search and scope",{skip:!enabled},async()=>{const team=actor([HR_PERMISSIONS.HR_JOB_CHANGE_MANAGE]),seen=new Set<string>();for(let page=1;page<=27;page++){const result=await service.employeeOptions(scope,team,query({page,page_size:20}));assert.equal(result.total,522);for(const item of result.items){assert.deepEqual(Object.keys(item).sort(),["employeeCode","fullName","id"]);assert.ok(!seen.has(item.id));seen.add(item.id);}}assert.equal(seen.size,522);const page26=await service.employeeOptions(scope,team,query({page:26}));assert.equal(page26.items[0]?.employeeCode,"EMP-0501");const found=await service.employeeOptions(scope,team,query({keyword:"EMP-0501"}));assert.equal(found.total,1);assert.equal(found.items[0]?.id,page26.items[0]?.id);const literal=await service.employeeOptions(scope,team,query({keyword:"%_\\"}));assert.equal(literal.total,1);assert.equal(literal.items[0]?.employeeCode,"LITERAL");const park=await service.employeeOptions(scope,actor([HR_PERMISSIONS.HR_JOB_CHANGE_MANAGE,HR_PERMISSIONS.HR_JOB_CHANGE_READ]),query());assert.equal(park.total,523);assert.ok(!park.items.some((item:{employeeCode:string})=>item.employeeCode==="FOREIGN-PARK"));const auditFailure=new HrJobChangeService(db,{recordOperationRequired:async()=>{throw new Error("audit unavailable");}} as never);await assert.rejects(auditFailure.employeeOptions(scope,team,query()),/audit unavailable/);});
