import {Body,Controller,Get,Param,ParseUUIDPipe,Post,Query,UseInterceptors} from "@nestjs/common";
import {HR_PERMISSIONS,type TenantParkScope} from "@jinhu/shared";
import {CurrentScope} from "../../shared/decorators/current-scope.decorator";import {CurrentUser} from "../../shared/decorators/current-user.decorator";import {RequireModule} from "../../shared/decorators/modules.decorator";import {RequireAnyPermissions,RequirePermissions} from "../../shared/decorators/permissions.decorator";import {IdempotencyInterceptor} from "../../shared/interceptors/idempotency.interceptor";import type {JwtPrincipal} from "../../shared/types/jwt-principal";import {AuditLog} from "../audit/decorators/audit-log.decorator";
import {AddHrPerformanceCalibrationEntryDto,CreateHrPerformanceCalibrationBatchDto,CreateHrPerformanceReviewCycleDto,CreateHrPerformanceTemplateDto,HrPerformanceCycleQueryDto,HrPerformanceReviewQueryDto,PreviewHrPerformanceScoreDto,ResolveHrPerformanceAppealDto,SubmitHrPerformanceAppealDto,SubmitHrPerformanceReviewDto} from "./dto/hr-performance-review.dto";import {HrPerformanceEvaluationService} from "./hr-performance-evaluation.service";import {HrPerformanceReviewService} from "./hr-performance-review.service";
@Controller("hr/performance-v2") @RequireModule("hr") export class HrPerformanceReviewController{constructor(private readonly service:HrPerformanceReviewService,private readonly evaluation:HrPerformanceEvaluationService){}
 @Get("templates") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE) templates(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.templates(s,a);}
 @Get("options") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) options(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.options(s,a);}
 @Post("templates") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_template",action:"创建绩效模板版本",bizType:"hr_performance_template",captureBody:false}) createTemplate(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrPerformanceTemplateDto){return this.service.createTemplate(s,a,d);}
 @Post("templates/:id/publish") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_template",action:"发布绩效模板版本",bizType:"hr_performance_template",bizIdParam:"id",captureBody:false}) publishTemplate(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.publishTemplate(s,a,id);}
 @Get("cycles") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEAM_READ,HR_PERMISSIONS.HR_PERFORMANCE_SELF_READ) cycles(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrPerformanceCycleQueryDto){return this.service.cycles(s,a,q);}
 @Post("cycles") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_cycle",action:"创建现代绩效周期",bizType:"hr_performance_review_cycle",captureBody:false}) createCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrPerformanceReviewCycleDto){return this.service.createCycle(s,a,d);}
 @Post("cycles/:id/publish") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_cycle",action:"发布现代绩效周期",bizType:"hr_performance_review_cycle",bizIdParam:"id",captureBody:false}) publishCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.publishCycle(s,a,id);}
 @Post("score-preview") @UseInterceptors(new IdempotencyInterceptor()) @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE,HR_PERMISSIONS.HR_PERFORMANCE_SELF_REVIEW,HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.performance_review",action:"预览绩效评分",bizType:"hr_performance_review",captureBody:false}) preview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:PreviewHrPerformanceScoreDto){return this.service.previewScore(s,a,d);}
 @Get("reviews") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEAM_READ,HR_PERMISSIONS.HR_PERFORMANCE_SELF_READ) reviews(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrPerformanceReviewQueryDto){return this.evaluation.reviews(s,a,q);}
 @Get("calibration-options") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE) calibrationOptions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.evaluation.calibrationOptions(s,a);}
 @Get("calibration-batches") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE) batches(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.evaluation.batches(s,a);}
 @Get("reviews/:id/actions") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEAM_READ,HR_PERMISSIONS.HR_PERFORMANCE_SELF_READ) actions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.evaluation.actions(s,a,id);}
 @Post("reviews/:id/self-review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_SELF_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.performance_review",action:"提交绩效自评",bizType:"hr_performance_review",bizIdParam:"id",captureBody:false}) selfReview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SubmitHrPerformanceReviewDto){return this.evaluation.submitSelf(s,a,id,d);}
 @Post("reviews/:id/manager-review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.performance_review",action:"提交主管评价",bizType:"hr_performance_review",bizIdParam:"id",captureBody:false}) managerReview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SubmitHrPerformanceReviewDto){return this.evaluation.submitManager(s,a,id,d);}
 @Post("calibration-batches") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE) @AuditLog({module:"人力资源管理",resource:"hr.performance_calibration",action:"创建绩效校准会",bizType:"hr_performance_calibration",captureBody:false}) createBatch(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrPerformanceCalibrationBatchDto){return this.evaluation.createBatch(s,a,d);}
 @Post("calibration-batches/:id/entries") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE) @AuditLog({module:"人力资源管理",resource:"hr.performance_calibration",action:"记录绩效校准调整",bizType:"hr_performance_calibration",bizIdParam:"id",captureBody:false}) addCalibration(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:AddHrPerformanceCalibrationEntryDto){return this.evaluation.addCalibration(s,a,id,d);}
 @Post("calibration-batches/:id/complete") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE) @AuditLog({module:"人力资源管理",resource:"hr.performance_calibration",action:"完成绩效校准",bizType:"hr_performance_calibration",bizIdParam:"id",captureBody:false}) completeBatch(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.evaluation.completeBatch(s,a,id);}
 @Post("reviews/:id/acknowledge") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_ACKNOWLEDGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_review",action:"签收绩效结果",bizType:"hr_performance_review",bizIdParam:"id",captureBody:false}) acknowledge(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.evaluation.acknowledge(s,a,id);}
 @Post("reviews/:id/appeals") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_APPEAL) @AuditLog({module:"人力资源管理",resource:"hr.performance_appeal",action:"提交绩效申诉",bizType:"hr_performance_appeal",bizIdParam:"id",captureBody:false}) appeal(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SubmitHrPerformanceAppealDto){return this.evaluation.appeal(s,a,id,d);}
 @Post("appeals/:id/resolve") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_APPEAL_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.performance_appeal",action:"处理绩效申诉",bizType:"hr_performance_appeal",bizIdParam:"id",captureBody:false}) resolveAppeal(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ResolveHrPerformanceAppealDto){return this.evaluation.resolveAppeal(s,a,id,d);}
}
