import "reflect-metadata";
import assert from "node:assert/strict";
import test from "node:test";
import { randomUUID } from "node:crypto";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { DataSource } from "typeorm";
import { BadRequestException, ConflictException, ForbiddenException, NotFoundException } from "@nestjs/common";
import { HR_PERMISSIONS } from "@jinhu/shared";
import type { AuditService } from "../audit/audit.service";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { HrPayrollFormalInputService } from "./hr-payroll-formal-input.service";
import { HrPayrollFormalRuleService } from "./hr-payroll-formal-rule.service";
import { HrPayrollFormalRunService } from "./hr-payroll-formal-run.service";
import type { HrPayrollFormalDefinitionDto } from "./dto/hr-payroll-formal-rule.dto";

const required = process.env.HR_PAYROLL_FORMAL_RULE_PG_REQUIRED === "1";
test("actual rule migration and service enforce draft concurrency, review, effective months, scope and audit rollback", { skip: !required }, async () => {
  assert.equal(process.env.POSTGRES_HOST, "127.0.0.1");
  assert.equal(process.env.POSTGRES_PORT, "15490");
  const database = `jinhu_hr_rules_lab_${randomUUID().replaceAll("-", "")}`;
  const admin = new DataSource({ type: "postgres", host: "127.0.0.1", port: 15490, username: "postgres", database: "postgres" });
  await admin.initialize();
  let db: DataSource | undefined;
  try {
    await admin.query(`CREATE DATABASE "${database}"`);
    db = new DataSource({ type: "postgres", host: "127.0.0.1", port: 15490, username: "postgres", database });
    await db.initialize();
    // Only original catalog FK prerequisite is a fixture. The entire new migration is executed unchanged.
    await db.query(`CREATE EXTENSION "uuid-ossp"; CREATE TABLE hr_payroll_book(
      id uuid,tenant_id varchar(64),park_id varchar(64),is_deleted boolean DEFAULT false,
      UNIQUE(tenant_id,park_id,id));
      CREATE TABLE hr_payroll_period(id uuid PRIMARY KEY,tenant_id varchar(64),park_id varchar(64),period_month date,start_date date,end_date date,status text,is_deleted boolean DEFAULT false);
      CREATE TABLE hr_employee(id uuid PRIMARY KEY,tenant_id varchar(64),park_id varchar(64),version int,hire_date date,departure_date date,is_deleted boolean DEFAULT false,employee_code text DEFAULT 'SYNTHETIC',full_name text DEFAULT '合成员工');
      CREATE TABLE test_required_audit(id uuid DEFAULT uuid_generate_v4(), metadata jsonb NOT NULL);`);
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000347_hr_payroll_formal_rules.sql"), "utf8"));
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000348_hr_payroll_formal_inputs.sql"), "utf8"));
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000233_hr_compensation_payroll.sql"), "utf8"));
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000247_hr_attendance_month_close.sql"), "utf8"));
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000243_hr_payroll_concurrency_integrity.sql"), "utf8"));
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000349_hr_payroll_formal_run_evidence.sql"), "utf8"));
    await db.query(readFileSync(resolve(__dirname, "../../../../../database/migrations/000350_hr_payroll_formal_run_ledger_bridge.sql"), "utf8"));
    const tenantId = randomUUID(), parkId = randomUUID(), scope = { tenantId, parkId };
    const creator: JwtPrincipal = { sub: randomUUID(), username: "synthetic-author", tenantId, parkId, roles: [], permissions: [HR_PERMISSIONS.HR_PAYROLL_READ, HR_PERMISSIONS.HR_PAYROLL_DETAIL_READ, HR_PERMISSIONS.HR_EMPLOYEE_READ, HR_PERMISSIONS.HR_PAYROLL_REVIEW, HR_PERMISSIONS.HR_PAYROLL_MANAGE, HR_PERMISSIONS.HR_PAYROLL_RULE_READ, HR_PERMISSIONS.HR_PAYROLL_FORMULA_REVIEW] };
    const reviewer = { ...creator, sub: randomUUID(), username: "synthetic-reviewer" };
    let failAudit = false;
    const audit = { recordOperationRequired: async (value: { afterJson: unknown }, manager?: { query: DataSource["query"] }) => {
      if (failAudit) throw new Error("required audit unavailable");
      await (manager ?? db!).query("INSERT INTO test_required_audit(metadata) VALUES($1::jsonb)", [JSON.stringify(value.afterJson)]);
    } } as unknown as AuditService;
    const service = new HrPayrollFormalRuleService(db, audit);
    const definition: HrPayrollFormalDefinitionDto = { roundingPolicy: "line_items_half_up", items: [
      { code: "收入", role: "earning", expression: null },
      { code: "税", role: "tax", expression: null },
      { code: "应发", role: "gross", expression: "[收入]" },
      { code: "实发", role: "net", expression: "[应发]-[税]" },
    ] };
    await assert.rejects(() => service.listSets(scope, { ...creator, permissions: [] }, { page: 1, pageSize: 20 }), ForbiddenException);
    const sourceBook = randomUUID(), foreignBook = randomUUID();
    await db.query("INSERT INTO hr_payroll_book(id,tenant_id,park_id) VALUES($1,$2,$3),($4,$2,$5)", [sourceBook, tenantId, parkId, foreignBook, randomUUID()]);
    await assert.rejects(() => service.createSet(scope, creator, { ruleCode: "FOREIGN", displayName: "异园区引用", sourceBookId: foreignBook }), NotFoundException);
    const mapped = await service.createSet(scope, creator, { ruleCode: "MAPPED", displayName: "延续业务账套", sourceBookId: sourceBook });
    assert.equal(mapped.sourceBookId, sourceBook);
    await assert.rejects(() => service.createSet(scope, creator, { ruleCode: "DUPLICATE", displayName: "重复映射", sourceBookId: sourceBook }), ConflictException);
    const rules = await service.createSet(scope, creator, { ruleCode: "SYNTHETIC", displayName: "合成测试工资规则" });
    const input = { expectedHeadRevision: 0, definition, reason: "合成规则并发测试" };
    const parallel = await Promise.allSettled([service.createVersion(scope, creator, rules.id, input), service.createVersion(scope, creator, rules.id, input)]);
    assert.equal(parallel.filter(result => result.status === "fulfilled").length, 1);
    assert.equal(parallel.filter(result => result.status === "rejected").length, 1);
    const initial = parallel.find(result => result.status === "fulfilled");
    assert.ok(initial?.status === "fulfilled");
    const draft = initial.value;
    assert.equal(draft.revisionNo, 1);
    const edited = await service.updateVersion(scope, creator, draft.id, { expectedVersion: 1, definition, reason: "明确项目和精度" });
    await assert.rejects(() => service.updateVersion(scope, creator, draft.id, { expectedVersion: 1, definition, reason: "过期修改" }), ConflictException);
    const submitted = await service.submitVersion(scope, creator, draft.id, { expectedVersion: edited.version });
    await assert.rejects(() => service.reviewVersion(scope, creator, draft.id, { expectedVersion: submitted.version, decision: "approve", effectiveFrom: "2026-10", reason: "自审必须拒绝" }), ForbiddenException);
    failAudit = true;
    await assert.rejects(() => service.reviewVersion(scope, reviewer, draft.id, { expectedVersion: submitted.version, decision: "approve", effectiveFrom: "2026-10", reason: "审核审计失败" }), /audit unavailable/);
    failAudit = false;
    assert.equal((await db.query("SELECT status FROM hr_payroll_rule_version WHERE id=$1", [draft.id]))[0].status, "submitted");
    const approved = await service.reviewVersion(scope, reviewer, draft.id, { expectedVersion: submitted.version, decision: "approve", effectiveFrom: "2026-10", reason: "独立复核" });
    assert.equal(approved.status, "approved");
    const [{ hash_matches }] = await db.query("SELECT definition_sha256=encode(sha256(convert_to(jsonb_build_object('definition',definition,'evidence',definition_evidence)::text,'UTF8')),'hex') AND definition_sha256<>repeat('0',64) AS hash_matches FROM hr_payroll_rule_version WHERE id=$1", [draft.id]);
    assert.equal(hash_matches, true);
    assert.equal((await service.effective(scope, creator, rules.id, { month: "2026-10" })).id, draft.id);
    await assert.rejects(() => service.effective(scope, creator, rules.id, { month: "2026-09" }), ConflictException);
    await assert.rejects(() => service.listVersions({ ...scope, parkId: randomUUID() }, creator, rules.id, { page: 1, pageSize: 20 }), NotFoundException);
    await assert.rejects(() => db!.query("UPDATE hr_payroll_rule_version SET reason='overwrite',version=version+1 WHERE id=$1", [draft.id]), /immutable/);
    await assert.rejects(() => db!.query("DELETE FROM hr_payroll_rule_version WHERE id=$1", [draft.id]), /cannot be deleted/);
    failAudit = true;
    await assert.rejects(() => service.createVersion(scope, creator, rules.id, { ...input, expectedHeadRevision: 1 }), /audit unavailable/);
    failAudit = false;
    assert.equal((await db.query("SELECT head_revision FROM hr_payroll_rule_set WHERE id=$1", [rules.id]))[0].head_revision, 1);
    assert.equal((await db.query("SELECT count(*)::int AS n FROM hr_payroll_rule_version WHERE rule_set_id=$1", [rules.id]))[0].n, 1);
    const next = await service.createVersion(scope, creator, rules.id, { ...input, expectedHeadRevision: 1 });
    const secondSubmitted = await service.submitVersion(scope, creator, next.id, { expectedVersion: 1 });
    await assert.rejects(() => service.reviewVersion(scope, reviewer, next.id, { expectedVersion: secondSubmitted.version, decision: "approve", effectiveFrom: "2026-10", reason: "重复生效月份" }), ConflictException);
    await service.reviewVersion(scope, reviewer, next.id, { expectedVersion: secondSubmitted.version, decision: "approve", effectiveFrom: "2026-11", reason: "次月生效" });
    assert.equal((await service.effective(scope, creator, rules.id, { month: "2026-10" })).id, draft.id);
    assert.equal((await service.effective(scope, creator, rules.id, { month: "2026-11" })).id, next.id);
    await assert.rejects(() => db!.transaction(manager => service.lockEffectiveVersion(manager, scope, rules.id, "2026-11", draft.id)), ConflictException);
    const third = await service.createVersion(scope, creator, rules.id, { ...input, expectedHeadRevision: 2 });
    const thirdEdited = await service.updateVersion(scope, reviewer, third.id, { expectedVersion: 1, definition, reason: "另一位作者维护" });
    const thirdSubmitted = await service.submitVersion(scope, reviewer, third.id, { expectedVersion: thirdEdited.version });
    await assert.rejects(() => service.reviewVersion(scope, reviewer, third.id, { expectedVersion: thirdSubmitted.version, decision: "approve", effectiveFrom: "2026-12", reason: "最终作者不得自审" }), ForbiddenException);
    await assert.rejects(() => db!.query("UPDATE hr_payroll_rule_version SET definition=definition || '{\"injected\":true}'::jsonb,status='approved',reviewed_by=$2,reviewed_at=now(),review_reason='illegal',effective_from='2026-12-01',version=version+1 WHERE id=$1", [third.id, randomUUID()]), /frozen/);
    const checker = { ...creator, sub: randomUUID() };
    const approvalRequest = { expectedVersion: thirdSubmitted.version, decision: "approve" as const, effectiveFrom: "2026-12", reason: "并发复核" };
    const reviewRace = await Promise.allSettled([service.reviewVersion(scope, checker, third.id, approvalRequest), service.reviewVersion(scope, { ...checker, sub: randomUUID() }, third.id, approvalRequest)]);
    assert.equal(reviewRace.filter(result => result.status === "fulfilled").length, 1);
    assert.equal(reviewRace.filter(result => result.status === "rejected").length, 1);
    const fourth = await service.createVersion(scope, creator, rules.id, { ...input, expectedHeadRevision: 3 });
    await db.query("UPDATE hr_payroll_rule_version SET definition_evidence=definition_evidence || '{\"formulaEngineVersion\":\"unexpected\"}'::jsonb,version=version+1 WHERE id=$1", [fourth.id]);
    await assert.rejects(() => service.submitVersion(scope, creator, fourth.id, { expectedVersion: 2 }), /evidence changed/);
    const repaired = await service.updateVersion(scope, creator, fourth.id, { expectedVersion: 2, definition, reason: "重新生成明确的解析证据" });
    await service.submitVersion(scope, creator, fourth.id, { expectedVersion: repaired.version });
    const inputService = new HrPayrollFormalInputService(db, service, audit);
    const periodId = randomUUID(), employeeId = randomUUID();
    await db.query("INSERT INTO hr_payroll_period VALUES($1,$2,$3,'2026-10-01','2026-10-01','2026-10-31','open',false)", [periodId, tenantId, parkId]);
    await db.query("INSERT INTO hr_employee(id,tenant_id,park_id,version,hire_date,departure_date,is_deleted) VALUES($1,$2,$3,1,'2026-10-15',null,false)", [employeeId, tenantId, parkId]);
    const payload = { periodId, ruleSetId: rules.id, ruleVersionId: draft.id, expectedHeadRevision: 0,
      employees: [{ employeeId, expectedEmployeeVersion: 1, directItems: { 收入: "123.4500", 税: "0" } }], reason: "明确当期工资范围" };
    await assert.rejects(() => inputService.create(scope, creator, { ...payload, employees: [payload.employees[0]!, payload.employees[0]!] }), BadRequestException);
    await assert.rejects(() => inputService.create(scope, creator, { ...payload, employees: [{ ...payload.employees[0]!, directItems: { 收入: "1" } }] }), BadRequestException);
    const ready=await inputService.preparation(scope,creator,{periodId,ruleSetId:rules.id,page:1,pageSize:1});
    assert.equal(ready.rule.id,draft.id);
    assert.equal(ready.expectedHeadRevision,0);
    assert.equal(ready.total,1);
    assert.deepEqual(ready.items[0]!.eligibility,{eligibleStart:"2026-10-15",eligibleEnd:"2026-10-31",basis:"employment_dates"});
    assert.equal(ready.items[0]!.expectedEmployeeVersion,1);
    assert.equal(JSON.stringify(ready).includes("snapshot_sha256"),false);
    assert.equal((await inputService.preparation(scope,creator,{periodId,ruleSetId:rules.id,page:2,pageSize:1})).total,1);
    assert.equal((await inputService.preparation(scope,creator,{periodId,ruleSetId:rules.id,keyword:"missing",page:1,pageSize:1})).total,0);
    const unknownEmployee=randomUUID(),foreignEmployee=randomUUID();
    await db.query("INSERT INTO hr_employee(id,tenant_id,park_id,version,hire_date,employee_code) VALUES($1,$2,$3,2,null,'EXCEPTION'),($4,$2,$5,1,null,'FOREIGN')",[unknownEmployee,tenantId,parkId,foreignEmployee,randomUUID()]);
    const exception=await inputService.preparation(scope,creator,{periodId,ruleSetId:rules.id,keyword:"EXCEPTION",page:1,pageSize:20});
    assert.equal(exception.total,1);assert.equal(exception.items[0]!.requiresSettlementWindow,true);assert.equal(exception.items[0]!.eligibility,null);
    assert.equal((await inputService.preparation(scope,creator,{periodId,ruleSetId:rules.id,keyword:"FOREIGN",page:1,pageSize:20})).total,0);
    await assert.rejects(()=>inputService.preparation({...scope,parkId:randomUUID()},creator,{periodId,ruleSetId:rules.id,page:1,pageSize:20}),NotFoundException);
    failAudit=true;
    await assert.rejects(()=>inputService.preparation(scope,creator,{periodId,ruleSetId:rules.id,page:1,pageSize:20}),/audit unavailable/);
    failAudit=false;
    const inputDraft = await inputService.create(scope, creator, payload);
    assert.equal(inputDraft.employees[0]!.directItems.税, "0.0000");
    const listedInputs = await inputService.list(scope, creator, { periodId, page: 1, pageSize: 20 });
    assert.equal(listedInputs.total, 1);
    assert.equal(JSON.stringify(listedInputs).includes("123.4500"), false);
    const inputDetail = await inputService.detail(scope, creator, inputDraft.id, { page: 1, pageSize: 20 });
    assert.equal(inputDetail.canEdit,true);assert.equal(inputDetail.canConfirm,false);
    assert.equal((await inputService.detail(scope,reviewer,inputDraft.id,{page:1,pageSize:20})).canConfirm,true);
    assert.equal(JSON.stringify(inputDetail).includes("authored_by"),false);
    assert.equal(inputDetail.employees[0]!.fullName, "合成员工");
    assert.equal(inputDetail.employees[0]!.directItems.收入, "123.4500");
    await assert.rejects(() => inputService.detail(scope, { ...creator, permissions: [HR_PERMISSIONS.HR_PAYROLL_READ] }, inputDraft.id, { page: 1, pageSize: 20 }), ForbiddenException);
    await assert.rejects(() => inputService.detail({ ...scope, parkId: randomUUID() }, creator, inputDraft.id, { page: 1, pageSize: 20 }), NotFoundException);
    failAudit = true;
    await assert.rejects(() => inputService.detail(scope, creator, inputDraft.id, { page: 1, pageSize: 20 }), /audit unavailable/);
    failAudit = false;

    await assert.rejects(() => inputService.confirm(scope, creator, inputDraft.id, { expectedVersion: 1 }), ForbiddenException);
    await db.query("UPDATE hr_employee SET version=2 WHERE id=$1", [employeeId]);
    await assert.rejects(() => inputService.confirm(scope, reviewer, inputDraft.id, { expectedVersion: 1 }), ConflictException);
    const inputEdited = await inputService.update(scope, creator, inputDraft.id, { expectedVersion: 1,
      employees: [{ ...payload.employees[0]!, expectedEmployeeVersion: 2 }], reason: "重新核对员工版本" });
    failAudit = true;
    await assert.rejects(() => inputService.confirm(scope, reviewer, inputDraft.id, { expectedVersion: inputEdited.version }), /audit unavailable/);
    failAudit = false;
    assert.equal((await db.query("SELECT status FROM hr_payroll_formal_input WHERE id=$1", [inputDraft.id]))[0].status, "draft");
    const confirmedInput = await inputService.confirm(scope, reviewer, inputDraft.id, { expectedVersion: inputEdited.version });
    assert.equal(confirmedInput.status, "confirmed");
    const preparation = await db.transaction(manager => inputService.lockConfirmedInput(manager, scope, creator, inputDraft.id, confirmedInput.version));
    assert.equal(preparation.rule.id, payload.ruleVersionId);
    assert.equal(preparation.input.employees[0]!.directItems.收入, "123.4500");
    assert.match(preparation.input.snapshotSha256, /^[a-f0-9]{64}$/u);
    await assert.rejects(() => db!.transaction(manager => inputService.lockConfirmedInput(manager, scope, creator, inputDraft.id, 1)), ConflictException);
    await assert.rejects(() => db!.transaction(manager => inputService.lockConfirmedInput(manager, { ...scope, parkId: randomUUID() }, creator, inputDraft.id, confirmedInput.version)), NotFoundException);
    await db.query("UPDATE hr_employee SET version=3 WHERE id=$1", [employeeId]);
    await assert.rejects(() => db!.transaction(manager => inputService.lockConfirmedInput(manager, scope, creator, inputDraft.id, confirmedInput.version)), /employee changed/);
    await db.query("UPDATE hr_employee SET version=2 WHERE id=$1", [employeeId]);
    await db.query("UPDATE hr_payroll_period SET status='closed' WHERE id=$1", [periodId]);
    await assert.rejects(() => db!.transaction(manager => inputService.lockConfirmedInput(manager, scope, creator, inputDraft.id, confirmedInput.version)), /period is closed/);
    await db.query("UPDATE hr_payroll_period SET status='open' WHERE id=$1", [periodId]);
    await assert.rejects(() => db!.query("UPDATE hr_payroll_formal_input SET reason='overwrite',version=version+1 WHERE id=$1", [inputDraft.id]), /immutable/);
    await assert.rejects(() => inputService.create(scope, creator, { ...payload, expectedHeadRevision: 1,
      employees: [{ ...payload.employees[0]!, expectedEmployeeVersion: 2, directItems: { 收入: 10 as unknown as string, 税: "0" } }] }), BadRequestException);
    await db.query("UPDATE hr_employee SET hire_date=null WHERE id=$1", [employeeId]);
    const missingDate = { ...payload, expectedHeadRevision: 1, employees: [{ ...payload.employees[0]!, expectedEmployeeVersion: 2 }] };
    await assert.rejects(() => inputService.create(scope, creator, missingDate), /settlement reason/);
    await assert.rejects(() => inputService.create(scope, creator, { ...missingDate, employees: [{ ...missingDate.employees[0]!, eligibilityReason: "仅说明理由仍无日期" }] }), /settlement window/);
    const explicitRoster = { ...missingDate, employees: [{ ...missingDate.employees[0]!, eligibilityReason: "经业务核对的当期结算范围", settlementStart: "2026-10-01", settlementEnd: "2026-10-31" }] };
    const secondInput = await inputService.create(scope, creator, explicitRoster);
    await assert.rejects(() => db!.transaction(manager => inputService.lockConfirmedInput(manager, scope, creator, secondInput.id, secondInput.version)), /not confirmed/);
    const settlementDetail = await inputService.detail(scope, creator, secondInput.id, { page: 1, pageSize: 20 });
    assert.equal(settlementDetail.employees[0]!.settlementStart, "2026-10-01");
    assert.equal(settlementDetail.employees[0]!.settlementEnd, "2026-10-31");
    assert.equal((await db.query("SELECT hire_date FROM hr_employee WHERE id=$1", [employeeId]))[0].hire_date, null);
    const thirdInput = await inputService.create(scope, creator, { ...explicitRoster, expectedHeadRevision: 2 });
    await assert.rejects(() => inputService.confirm(scope, reviewer, secondInput.id, { expectedVersion: 1 }), /newer payroll input revision/);
    assert.equal((await inputService.detail(scope,reviewer,secondInput.id,{page:1,pageSize:20})).canConfirm,false);
    const thirdConfirmed = await inputService.confirm(scope, reviewer, thirdInput.id, { expectedVersion: 1 });
    const lockedDetail=await inputService.detail(scope,creator,thirdInput.id,{page:1,pageSize:20});assert.equal(lockedDetail.canEdit,false);assert.equal(lockedDetail.canConfirm,false);
    await assert.rejects(() => db!.transaction(manager => inputService.lockConfirmedInput(manager, scope, creator, inputDraft.id, confirmedInput.version)), /newer confirmed/);
    const runService = new HrPayrollFormalRunService(db, inputService, audit);
    const runPayload = { inputId: thirdInput.id, expectedInputVersion: thirdConfirmed.version };
    failAudit = true;
    await assert.rejects(() => runService.create(scope, creator, runPayload), /audit unavailable/);
    failAudit = false;
    assert.equal((await db.query("SELECT count(*)::int AS n FROM hr_payroll_run"))[0].n, 0);
    assert.equal((await db.query("SELECT count(*)::int AS n FROM hr_payslip"))[0].n, 0);
    const optionsQuery={inputId:thirdInput.id,expectedInputVersion:thirdConfirmed.version,page:1,pageSize:20};
    const beforeRun=await runService.options(scope,creator,optionsQuery);
    assert.equal(beforeRun.canCreateBase,true);assert.deepEqual(beforeRun.requires,{compensation:false,attendance:false,insurance:false});assert.equal(beforeRun.items.length,1);assert.equal(beforeRun.items[0]!.insuranceSource,null);
    assert.equal((await runService.options(scope,creator,{...optionsQuery,page:2})).total,1);
    await assert.rejects(()=>runService.options({...scope,parkId:randomUUID()},creator,optionsQuery),NotFoundException);
    await assert.rejects(()=>runService.options(scope,creator,{...optionsQuery,expectedInputVersion:1}),ConflictException);
    failAudit=true;await assert.rejects(()=>runService.options(scope,creator,optionsQuery),/audit unavailable/);failAudit=false;
    const formalRun = await runService.create(scope, creator, runPayload);
    assert.equal(formalRun.netAmount, "123.45");
    assert.equal(formalRun.employeeCount, 1);
    const [storedSlip] = await db.query("SELECT net_amount::text,compensation_snapshot FROM hr_payslip WHERE run_id=$1", [formalRun.id]);
    assert.equal(storedSlip.net_amount, "123.45");
    assert.equal(storedSlip.compensation_snapshot.eligibility.basis, "explicit_settlement");
    assert.equal((await db.query("SELECT count(*)::int AS n FROM hr_payslip_item"))[0].n, 4);
    const [storedEvidence] = await db.query("SELECT snapshot_sha256,snapshot FROM hr_payroll_formal_run_evidence WHERE run_id=$1", [formalRun.id]);
    assert.match(storedEvidence.snapshot_sha256, /^[a-f0-9]{64}$/u);
    assert.equal(storedEvidence.snapshot.input.version, thirdConfirmed.version);
    await assert.rejects(() => runService.create(scope, creator, runPayload), /already have a run/);
    await assert.rejects(() => db!.query("UPDATE hr_payroll_formal_run_evidence SET snapshot='{}' WHERE run_id=$1", [formalRun.id]), /immutable/);
    await assert.rejects(() => db!.query("UPDATE hr_payslip SET net_amount=0 WHERE run_id=$1", [formalRun.id]), /frozen/);
    await assert.rejects(() => db!.query("UPDATE hr_payroll_run SET net_total=0 WHERE id=$1", [formalRun.id]), /frozen/);
    await assert.rejects(() => db!.query("UPDATE hr_payslip_item SET amount=0"), /frozen/);
    await assert.rejects(() => runService.create(scope, creator, { ...runPayload, correctionOfRunId: formalRun.id, correctionReason: "更正核算" }), /confirmed run/);
    await assert.rejects(() => db!.query("UPDATE hr_payroll_run SET status='confirmed' WHERE id=$1", [formalRun.id]), /governed payroll/);
    await assert.rejects(() => runService.transition(scope, creator, formalRun.id, "review", { expectedVersion: formalRun.version, reason: "自行复核" }), ForbiddenException);
    failAudit = true;
    await assert.rejects(() => runService.transition(scope, reviewer, formalRun.id, "review", { expectedVersion: formalRun.version, reason: "核对项目和金额" }), /audit unavailable/);
    failAudit = false;
    assert.equal((await db.query("SELECT status FROM hr_payroll_run WHERE id=$1", [formalRun.id]))[0].status, "calculated");
    assert.equal((await db.query("SELECT count(*)::int AS n FROM hr_payroll_formal_run_action"))[0].n, 0);
    const payrollReviewRace = await Promise.allSettled([1, 2].map(() => runService.transition(scope, reviewer, formalRun.id, "review", { expectedVersion: formalRun.version, reason: "独立复核工资项目和金额" })));
    assert.equal(payrollReviewRace.filter(result => result.status === "fulfilled").length, 1);
    assert.equal(payrollReviewRace.filter(result => result.status === "rejected").length, 1);
    const reviewedRun = payrollReviewRace.flatMap(result => result.status === "fulfilled" ? [result.value] : [])[0]!;
    const confirmer = { ...reviewer, permissions: [...reviewer.permissions, HR_PERMISSIONS.HR_PAYROLL_CONFIRM] };
    const runDetail = await runService.detail(scope, confirmer, formalRun.id, { page: 1, pageSize: 20 });
    assert.equal(runDetail.canConfirm, true);
    assert.equal(runDetail.items[0]!.netAmount, "123.45");
    assert.equal(runDetail.items[0]!.items.length, 4);
    assert.equal((await runService.detail(scope, confirmer, formalRun.id, { page: 2, pageSize: 20 })).items.length, 0);
    assert.equal(JSON.stringify(runDetail).includes('"snapshot"'), false);
    assert.equal(JSON.stringify(runDetail).includes('"create_by"'), false);
    failAudit = true;
    await assert.rejects(() => runService.detail(scope, confirmer, formalRun.id, { page: 1, pageSize: 20 }), /audit unavailable/);
    failAudit = false;
    await assert.rejects(() => runService.detail(scope, { ...confirmer, permissions: [HR_PERMISSIONS.HR_PAYROLL_READ] }, formalRun.id, { page: 1, pageSize: 20 }), ForbiddenException);
    await assert.rejects(() => runService.transition(scope, { ...creator, permissions: confirmer.permissions }, formalRun.id, "confirm", { expectedVersion: reviewedRun.version, reason: "计算人自行确认" }), ForbiddenException);
    await assert.rejects(() => runService.transition(scope, confirmer, formalRun.id, "confirm", { expectedVersion: 1, reason: "过期页面" }), ConflictException);
    failAudit = true;
    await assert.rejects(() => runService.transition(scope, confirmer, formalRun.id, "confirm", { expectedVersion: reviewedRun.version, reason: "确认发放前的核算结果" }), /audit unavailable/);
    failAudit = false;
    assert.equal((await db.query("SELECT status FROM hr_payroll_run WHERE id=$1", [formalRun.id]))[0].status, "reviewing");
    assert.equal((await db.query("SELECT status FROM hr_payslip WHERE run_id=$1", [formalRun.id]))[0].status, "draft");
    const payrollConfirmRace = await Promise.allSettled([1, 2].map(() => runService.transition(scope, confirmer, formalRun.id, "confirm", { expectedVersion: reviewedRun.version, reason: "确认发放前的核算结果" })));
    assert.equal(payrollConfirmRace.filter(result => result.status === "fulfilled").length, 1);
    assert.equal(payrollConfirmRace.filter(result => result.status === "rejected").length, 1);
    const confirmedRun = payrollConfirmRace.flatMap(result => result.status === "fulfilled" ? [result.value] : [])[0]!;
    assert.equal(confirmedRun.status, "confirmed");
    assert.equal((await db.query("SELECT status FROM hr_payslip WHERE run_id=$1", [formalRun.id]))[0].status, "confirmed");
    await assert.rejects(() => db!.query("UPDATE hr_payroll_formal_run_action SET reason='overwrite' WHERE run_id=$1", [formalRun.id]), /immutable/);
    const correctionOptions=await runService.options(scope,creator,optionsQuery);assert.equal(correctionOptions.canCreateBase,false);assert.equal(correctionOptions.overlappingEmployeeCount,1);assert.equal(correctionOptions.correctionRuns[0]!.id,formalRun.id);
    const corrected = await runService.create(scope, creator, { ...runPayload, correctionOfRunId: formalRun.id, correctionReason: "经复核重新结算" });
    assert.equal(corrected.runNo, 2);
    assert.equal((await runService.options(scope,creator,optionsQuery)).correctionRuns.length,0);
    assert.equal((await db.query("SELECT correction_of_run_id FROM hr_payroll_run WHERE id=$1", [corrected.id]))[0].correction_of_run_id, formalRun.id);
    await assert.rejects(() => runService.create(scope, creator, { ...runPayload, correctionOfRunId: formalRun.id, correctionReason: "重复更正" }), /active correction/);
    const salaryEmployeeId = randomUUID(), planId = randomUUID();
    await db.query("INSERT INTO hr_employee(id,tenant_id,park_id,version,hire_date) VALUES($1,$2,$3,1,'2026-10-01')", [salaryEmployeeId, tenantId, parkId]);
    await db.query("INSERT INTO hr_compensation_plan(id,tenant_id,park_id,plan_code,plan_name,effective_from,status) VALUES($1,$2,$3,'SYNTHETIC','合成薪酬','2026-10-01','active')", [planId, tenantId, parkId]);
    await db.query("INSERT INTO hr_employee_compensation(tenant_id,park_id,employee_id,plan_id,effective_from,effective_to,base_salary,status) VALUES($1,$2,$3,$4,'2026-10-01','2026-10-15',3100,'active'),($1,$2,$3,$4,'2026-10-16',null,6200,'active')", [tenantId, parkId, salaryEmployeeId, planId]);
    const salaryRules = await service.createSet(scope, creator, { ruleCode: "salary-test", displayName: "工资与考勤合成验证" });
    const salaryDefinition: HrPayrollFormalDefinitionDto = { roundingPolicy: "line_items_half_up", compensationPolicy: "calendar_day_prorated", items: [
      { code: "工资", role: "earning", expression: "[人事系统.基本工资]" },
      { code: "缺勤", role: "deduction", expression: "[人事系统.缺勤天数]*100" },
      { code: "税", role: "tax", expression: null },
      { code: "应发", role: "gross", expression: "[工资]" },
      { code: "实发", role: "net", expression: "[应发]-[缺勤]-[税]" },
    ] };
    const salaryDraft = await service.createVersion(scope, creator, salaryRules.id, { expectedHeadRevision: 0, definition: salaryDefinition, reason: "测试当期调薪" });
    const salarySubmitted = await service.submitVersion(scope, creator, salaryDraft.id, { expectedVersion: salaryDraft.version });
    await service.reviewVersion(scope, reviewer, salaryDraft.id, { expectedVersion: salarySubmitted.version, decision: "approve", effectiveFrom: "2026-10", reason: "独立复核计算口径" });
    const salaryInput = await inputService.create(scope, creator, { periodId, ruleSetId: salaryRules.id, ruleVersionId: salaryDraft.id, expectedHeadRevision: 0,
      employees: [{ employeeId: salaryEmployeeId, expectedEmployeeVersion: 1, directItems: { 税: "80.10" } }], reason: "当期工资来源验证" });
    const salaryConfirmed = await inputService.confirm(scope, reviewer, salaryInput.id, { expectedVersion: salaryInput.version });
    const attendancePeriodId = randomUUID(), attendanceBatchId = randomUUID(), summaryId = randomUUID();
    await db.query("INSERT INTO hr_attendance_period(id,tenant_id,park_id,period_month,status,active_version) VALUES($1,$2,$3,'2026-10-01','closed',1)", [attendancePeriodId, tenantId, parkId]);
    await db.query("INSERT INTO hr_attendance_month_summary(id,tenant_id,park_id,period_id,employee_id,summary_version,absence_days) VALUES($1,$2,$3,$4,$5,1,1)", [summaryId, tenantId, parkId, attendancePeriodId, salaryEmployeeId]);
    await db.query("INSERT INTO hr_attendance_payroll_input_batch(id,tenant_id,park_id,period_id,batch_no,batch_type,created_from_summary_version) VALUES($1,$2,$3,$4,1,'close',1)", [attendanceBatchId, tenantId, parkId, attendancePeriodId]);
    await db.query("INSERT INTO hr_attendance_payroll_input_item(tenant_id,park_id,batch_id,employee_id,source_summary_id,worked_minutes,late_minutes,early_minutes,absence_days,missing_punch_days) VALUES($1,$2,$3,$4,$5,1000,0,0,1,0)", [tenantId, parkId, attendanceBatchId, salaryEmployeeId, summaryId]);
    const salaryPayload = { inputId: salaryInput.id, expectedInputVersion: salaryConfirmed.version, attendanceInputBatchId: attendanceBatchId };
    await assert.rejects(() => runService.create(scope, creator, { ...salaryPayload, attendanceInputBatchId: undefined }), /attendance batch must be selected/);
    const salaryOptions=await runService.options(scope,creator,{inputId:salaryInput.id,expectedInputVersion:salaryConfirmed.version,page:1,pageSize:20});
    assert.deepEqual(salaryOptions.requires,{compensation:true,attendance:true,insurance:false});assert.equal(salaryOptions.attendanceBatches[0]!.id,attendanceBatchId);assert.equal(salaryOptions.attendanceBatches[0]!.missingEmployeeCount,0);
    const salaryRun = await runService.create(scope, creator, salaryPayload);
    assert.equal(salaryRun.grossAmount, "4700.00");
    assert.equal(salaryRun.deductionAmount, "100.00");
    assert.equal(salaryRun.personalTax, "80.10");
    assert.equal(salaryRun.netAmount, "4519.90");
    const [salaryEvidence] = await db.query("SELECT snapshot FROM hr_payroll_formal_run_evidence WHERE run_id=$1", [salaryRun.id]);
    assert.equal(salaryEvidence.snapshot.results[0].frozenSources.compensations.length, 2);
    assert.equal(salaryEvidence.snapshot.results[0].frozenSources.attendance.batchId, attendanceBatchId);
    const metadataReader = { ...creator, permissions: [HR_PERMISSIONS.HR_PAYROLL_READ] };
    const runPage = await runService.list(scope, metadataReader, { page: 1, pageSize: 2, month: "2026-10" });
    assert.equal(runPage.total, 3); assert.equal(runPage.items.length, 2);
    assert.equal(JSON.stringify(runPage).includes("4519.90"), false);
    assert.equal(JSON.stringify(runPage).includes("snapshot"), false);
    assert.equal((await runService.list(scope, metadataReader, { page: 2, pageSize: 2 })).items.length, 1);
    assert.equal((await runService.list(scope, metadataReader, { page: 3, pageSize: 2 })).total, 3);
    assert.equal((await runService.list(scope, metadataReader, { page: 1, pageSize: 20, status: "confirmed" })).total, 1);
    assert.equal((await runService.list({ ...scope, parkId: randomUUID() }, metadataReader, { page: 1, pageSize: 20 })).total, 0);
    failAudit = true;
    await assert.rejects(() => runService.list(scope, metadataReader, { page: 1, pageSize: 20 }), /audit unavailable/);
    failAudit = false;
    const [{ n }] = await db.query("SELECT count(*)::int AS n FROM test_required_audit");
    assert.ok(n > 0);
    // Owned insurance source prerequisites are fixtures here; producer guards are a separate suite.
    await db.query("CREATE TABLE hr_insurance_owned_preview(id uuid,tenant_id varchar(64),park_id varchar(64),snapshot_sha256 text,result jsonb); CREATE TABLE hr_insurance_owned_revision(id uuid,tenant_id varchar(64),park_id varchar(64),employee_id uuid,period_month date,preview_id uuid,revision_no int)");
    const insuredEmployee=randomUUID();await db.query("INSERT INTO hr_employee(id,tenant_id,park_id,version,hire_date) VALUES($1,$2,$3,1,'2026-10-01')",[insuredEmployee,tenantId,parkId]);
    const insuranceRules=await service.createSet(scope,creator,{ruleCode:"INSURANCE",displayName:"保险工资规则"});
    const insuranceDefinition:HrPayrollFormalDefinitionDto={roundingPolicy:"line_items_half_up",items:[{code:"收入",role:"earning",expression:null},{code:"扣款",role:"deduction",expression:"[人事系统.养老保险个人金额]"},{code:"税",role:"tax",expression:null},{code:"应发",role:"gross",expression:"[收入]"},{code:"实发",role:"net",expression:"[应发]-[扣款]-[税]"}]};
    const insuranceDraft=await service.createVersion(scope,creator,insuranceRules.id,{expectedHeadRevision:0,definition:insuranceDefinition,reason:"确认保险来源"});
    const insuranceSubmitted=await service.submitVersion(scope,creator,insuranceDraft.id,{expectedVersion:insuranceDraft.version});await service.reviewVersion(scope,reviewer,insuranceDraft.id,{expectedVersion:insuranceSubmitted.version,decision:"approve",effectiveFrom:"2026-10",reason:"独立核对保险口径"});
    const insuranceInput=await inputService.create(scope,creator,{periodId,ruleSetId:insuranceRules.id,ruleVersionId:insuranceDraft.id,expectedHeadRevision:0,employees:[{employeeId:insuredEmployee,expectedEmployeeVersion:1,directItems:{收入:"100.0000",税:"0.0000"}}],reason:"当期保险输入"});
    const insuranceConfirmed=await inputService.confirm(scope,reviewer,insuranceInput.id,{expectedVersion:insuranceInput.version});const insuranceQuery={inputId:insuranceInput.id,expectedInputVersion:insuranceConfirmed.version,page:1,pageSize:20};
    const missingInsurance=await runService.options(scope,creator,insuranceQuery);assert.equal(missingInsurance.requires.insurance,true);assert.equal(missingInsurance.items[0]!.insuranceSource,null);
    const preview1=randomUUID(),preview2=randomUUID(),insurance1=randomUUID(),insurance2=randomUUID();
    const sourceResult={items:[{insuranceKind:"oldage",amounts:{base:"100.00",employer:"30.00",employee:"25.00",supplement:"0.00"}}]};
    await db.query("INSERT INTO hr_insurance_owned_preview VALUES($1,$3,$4,$5,$7::jsonb),($2,$3,$4,$6,$7::jsonb)",[preview1,preview2,tenantId,parkId,"a".repeat(64),"b".repeat(64),JSON.stringify(sourceResult)]);
    await db.query("INSERT INTO hr_insurance_owned_revision VALUES($1,$3,$4,$5,'2026-10-01',$6,1),($2,$3,$4,$5,'2026-10-01',$7,2)",[insurance1,insurance2,tenantId,parkId,insuredEmployee,preview1,preview2]);
    const insuredOptions=await runService.options(scope,creator,insuranceQuery);const choice=insuredOptions.items[0]!.insuranceSource!;assert.equal(choice.sourceId,insurance2);assert.equal(choice.expectedVersion,2);assert.equal(choice.expectedHash,"b".repeat(64));
    await assert.rejects(()=>runService.create(scope,creator,{inputId:insuranceInput.id,expectedInputVersion:insuranceConfirmed.version}),/insurance versions/);
    await assert.rejects(()=>runService.create(scope,creator,{inputId:insuranceInput.id,expectedInputVersion:insuranceConfirmed.version,insuranceSources:[{...choice,sourceId:insurance1,expectedVersion:1,expectedHash:"a".repeat(64)}]}),/stale/);
    const insuranceRun=await runService.create(scope,creator,{inputId:insuranceInput.id,expectedInputVersion:insuranceConfirmed.version,insuranceSources:[choice]});assert.equal(insuranceRun.grossAmount,"100.00");assert.equal(insuranceRun.deductionAmount,"25.00");assert.equal(insuranceRun.netAmount,"75.00");
    const [insuranceEvidence]=await db.query("SELECT snapshot FROM hr_payroll_formal_run_evidence WHERE run_id=$1",[insuranceRun.id]);assert.equal(insuranceEvidence.snapshot.results[0].frozenSources.insurance.id,insurance2);
  } finally {
    if (db?.isInitialized) await db.destroy();
    await admin.query(`DROP DATABASE IF EXISTS "${database}" WITH(FORCE)`);
    assert.equal((await admin.query("SELECT datname FROM pg_database WHERE datname=$1", [database])).length, 0);
    await admin.destroy();
  }
});
