import {Body,Controller,Get,Param,ParseUUIDPipe,Post,Query,UseInterceptors} from "@nestjs/common";
import {HR_PERMISSIONS,type TenantParkScope} from "@jinhu/shared";
import {CurrentScope} from "../../shared/decorators/current-scope.decorator";import {CurrentUser} from "../../shared/decorators/current-user.decorator";import {RequireModule} from "../../shared/decorators/modules.decorator";import {RequireAnyPermissions,RequirePermissions} from "../../shared/decorators/permissions.decorator";import {IdempotencyInterceptor} from "../../shared/interceptors/idempotency.interceptor";import type {JwtPrincipal} from "../../shared/types/jwt-principal";import {AuditLog} from "../audit/decorators/audit-log.decorator";
import {CreateHrPerformanceReviewCycleDto,CreateHrPerformanceTemplateDto,HrPerformanceCycleQueryDto,PreviewHrPerformanceScoreDto} from "./dto/hr-performance-review.dto";import {HrPerformanceReviewService} from "./hr-performance-review.service";
@Controller("hr/performance-v2") @RequireModule("hr") export class HrPerformanceReviewController{constructor(private readonly service:HrPerformanceReviewService){}
 @Get("templates") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE) templates(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.templates(s,a);}
 @Get("options") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) options(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.options(s,a);}
 @Post("templates") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_template",action:"创建绩效模板版本",bizType:"hr_performance_template",captureBody:false}) createTemplate(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrPerformanceTemplateDto){return this.service.createTemplate(s,a,d);}
 @Post("templates/:id/publish") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_template",action:"发布绩效模板版本",bizType:"hr_performance_template",bizIdParam:"id",captureBody:false}) publishTemplate(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.publishTemplate(s,a,id);}
 @Get("cycles") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEAM_READ,HR_PERMISSIONS.HR_PERFORMANCE_SELF_READ) cycles(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrPerformanceCycleQueryDto){return this.service.cycles(s,a,q);}
 @Post("cycles") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_cycle",action:"创建现代绩效周期",bizType:"hr_performance_review_cycle",captureBody:false}) createCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrPerformanceReviewCycleDto){return this.service.createCycle(s,a,d);}
 @Post("cycles/:id/publish") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.performance_cycle",action:"发布现代绩效周期",bizType:"hr_performance_review_cycle",bizIdParam:"id",captureBody:false}) publishCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.publishCycle(s,a,id);}
 @Post("score-preview") @RequireAnyPermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE,HR_PERMISSIONS.HR_PERFORMANCE_SELF_REVIEW,HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) preview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:PreviewHrPerformanceScoreDto){return this.service.previewScore(s,a,d);}
}
