import { Body,Controller,Get,Param,ParseUUIDPipe,Post,Put,Query,UseInterceptors } from "@nestjs/common";
import { HR_PERMISSIONS,type TenantParkScope } from "@jinhu/shared";
import { CurrentScope } from "../../shared/decorators/current-scope.decorator";
import { CurrentUser } from "../../shared/decorators/current-user.decorator";
import { RequireModule } from "../../shared/decorators/modules.decorator";
import { RequireAnyPermissions,RequirePermissions } from "../../shared/decorators/permissions.decorator";
import { IdempotencyInterceptor } from "../../shared/interceptors/idempotency.interceptor";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { AuditLog } from "../audit/decorators/audit-log.decorator";
import { CreateHrCandidateDto,CreateHrRequisitionDto,HrCandidateConvertDto,HrCandidateStageActionListDto,HrCandidateStageDto,HrRecruitmentListDto,SaveHrCandidateAssessmentDto } from "./dto/hr-recruitment.dto";
import { HrRecruitmentService } from "./hr-recruitment.service";
import { HrCandidateProfileIdempotencyInterceptor } from "./hr-candidate-profile-idempotency.interceptor";
import { HrCandidateProfileService } from "./hr-candidate-profile.service";
import { HrCandidateProfileListDto,SaveHrCandidateProfileDto } from "./dto/hr-candidate-profile.dto";
import { HrCandidateInterviewService } from "./hr-candidate-interview.service";
import { HrCandidateInterviewListDto,SaveHrCandidateInterviewDto } from "./dto/hr-candidate-interview.dto";
@Controller("hr/recruitment") @RequireModule("hr")
export class HrRecruitmentController {
 constructor(private readonly service:HrRecruitmentService,private readonly interviews:HrCandidateInterviewService,private readonly profiles:HrCandidateProfileService){}
 @Get("requisitions") @RequireAnyPermissions(HR_PERMISSIONS.HR_REQUISITION_READ,HR_PERMISSIONS.HR_REQUISITION_TEAM_READ) listRequisitions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrRecruitmentListDto){return this.service.listRequisitions(s,a,q);}
 @Post("requisitions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_REQUISITION_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.requisition",action:"创建招聘需求",bizType:"hr_recruitment_requisition",captureBody:false}) createRequisition(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrRequisitionDto){return this.service.createRequisition(s,a,d);}
 @Get("candidates") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) listCandidates(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrRecruitmentListDto){return this.service.listCandidates(s,a,q);}
 @Get("candidates/:id/stage-actions") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) stageActions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Query()q:HrCandidateStageActionListDto){return this.service.listCandidateStageActions(s,a,id,q);}
 @Get("candidates/:id/profile") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) profile(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.profiles.current(s,a,id);}
 @Get("candidates/:id/profile-history") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) profileHistory(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Query()q:HrCandidateProfileListDto){return this.profiles.history(s,a,id,q);}
 @Get("candidates/:id/profile/requisition-options") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ,HR_PERMISSIONS.HR_CANDIDATE_MANAGE) profileRequisitions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Query()q:HrCandidateProfileListDto){return this.profiles.requisitionOptions(s,a,id,q);}
 @Put("candidates/:id/profile") @UseInterceptors(HrCandidateProfileIdempotencyInterceptor) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ,HR_PERMISSIONS.HR_CANDIDATE_MANAGE) saveProfile(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SaveHrCandidateProfileDto){return this.profiles.update(s,a,id,d);}
 @Get("candidates/:id/assessment") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) assessment(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.candidateAssessment(s,a,id);}
 @Get("candidates/:id/assessment-history") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) assessmentHistory(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Query()q:HrCandidateStageActionListDto){return this.service.listCandidateAssessmentHistory(s,a,id,q);}
 @Get("candidates/:id/interviews") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) interviewsList(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Query()q:HrCandidateInterviewListDto){return this.interviews.list(s,a,id,q);}
 @Get("candidates/:id/interviews/:interviewId") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) interviewDetail(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Param("interviewId",new ParseUUIDPipe())interviewId:string){return this.interviews.detail(s,a,id,interviewId);}
 @Get("candidates/:id/interviews/:interviewId/history") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ) interviewHistory(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Param("interviewId",new ParseUUIDPipe())interviewId:string,@Query()q:HrCandidateInterviewListDto){return this.interviews.history(s,a,id,interviewId,q);}
 @Get("candidates/:id") @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_READ,HR_PERMISSIONS.HR_CANDIDATE_SENSITIVE_READ) candidateDetail(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.candidateDetail(s,a,id);}
 @Post("candidates") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.candidate",action:"创建候选人",bizType:"hr_candidate",captureBody:false}) createCandidate(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrCandidateDto){return this.service.createCandidate(s,a,d);}
 @Post("candidates/:id/stage-actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_STAGE) @AuditLog({module:"人力资源管理",resource:"hr.candidate_stage",action:"办理候选人阶段",bizType:"hr_candidate",bizIdParam:"id",captureBody:false}) move(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrCandidateStageDto){return this.service.moveCandidate(s,a,id,d);}
 @Put("candidates/:id/assessment") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_MANAGE) saveAssessment(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SaveHrCandidateAssessmentDto){return this.service.saveCandidateAssessment(s,a,id,d);}
 @Post("candidates/:id/interviews") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_MANAGE) createInterview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SaveHrCandidateInterviewDto){return this.interviews.create(s,a,id,d);}
 @Put("candidates/:id/interviews/:interviewId") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_MANAGE) updateInterview(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Param("interviewId",new ParseUUIDPipe())interviewId:string,@Body()d:SaveHrCandidateInterviewDto){return this.interviews.update(s,a,id,interviewId,d);}
 @Post("candidates/:id/convert") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CANDIDATE_CONVERT) @AuditLog({module:"人力资源管理",resource:"hr.candidate_conversion",action:"候选人转预入职",bizType:"hr_candidate",bizIdParam:"id",captureBody:false}) convert(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrCandidateConvertDto){return this.service.convert(s,a,id,d);}
}
