import "reflect-metadata";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import test from "node:test";
import { DataSource, type EntityManager } from "typeorm";
import { HR_PERMISSIONS, type TenantParkScope } from "@jinhu/shared";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { HrRecruitmentService } from "./hr-recruitment.service";
import { HrRequisitionService } from "./hr-requisition.service";

const enabled=process.env.HR_REQUISITION_PG==="1";
test("full-schema requisition maintenance: CAS, frozen history, references, lifecycle and conversion version",{skip:!enabled,timeout:60_000},async()=>{
 assert.equal(process.env.HR_REQUISITION_ISOLATED,"yes");assert.equal(process.env.POSTGRES_HOST,"127.0.0.1");assert.equal(process.env.POSTGRES_PORT,"15432");assert.match(process.env.POSTGRES_DB??"",/^jinhu_hr_migration_lab_review_final_[0-9_]+$/);
 const db=new DataSource({type:"postgres",host:"127.0.0.1",port:15432,username:process.env.POSTGRES_USER,password:process.env.POSTGRES_PASSWORD,database:process.env.POSTGRES_DB});await db.initialize();
 try{
  const scope:TenantParkScope={tenantId:"10000001",parkId:"20000001"},actorId=randomUUID(),orgId=randomUUID(),nextOrgId=randomUUID(),positionId=randomUUID(),suffix=randomUUID().slice(0,8);
  await db.query("CREATE TABLE IF NOT EXISTS fixture_requisition_audit(id bigserial primary key,payload jsonb not null)");
  await db.query("INSERT INTO sys_user(id,tenant_id,park_id,username,display_name,password_hash,status) VALUES($1,$2,$3,$4,'需求合成办理人','not-a-login-hash','enabled')",[actorId,scope.tenantId,scope.parkId,`req-${suffix}`]);
  for(const [id,code,name] of [[orgId,`RQ-${suffix}`,`需求初始组织-${suffix}`],[nextOrgId,`RX-${suffix}`,`需求目标组织-${suffix}`]])await db.query("INSERT INTO sys_org(id,tenant_id,park_id,org_code,org_name,org_type,status,leader_user_id,create_by,update_by) VALUES($1,$2,$3,$4,$5,'department','enabled',$6,$6,$6)",[id,scope.tenantId,scope.parkId,code,name,actorId]);
  await db.query("INSERT INTO hr_position(id,tenant_id,park_id,org_id,position_code,position_name,status) VALUES($1,$2,$3,$4,$5,$6,'enabled')",[positionId,scope.tenantId,scope.parkId,nextOrgId,`P-${suffix}`,`需求岗位-${suffix}`]);
  const actor:JwtPrincipal={...scope,sub:actorId,username:"req",roles:[],permissions:["*"]};let failAudit=false;const audit={recordOperationRequired:async(event:unknown,manager?:EntityManager)=>{if(failAudit)throw new Error("required audit unavailable");assert.ok(manager);await manager!.query("INSERT INTO fixture_requisition_audit(payload) VALUES($1::jsonb)",[JSON.stringify(event)]);}} as never;
  const recruitment=new HrRecruitmentService(db,{identityProfile:(value:string)=>({encrypted:`enc:${value}`,masked:"***",hash:`hash:${value}`})} as never,audit),service=new HrRequisitionService(db,audit);
  const created=await recruitment.createRequisition(scope,actor,{requisitionCode:`REQ-${suffix}`,title:"初始需求",orgId,headcount:1,ownerUserId:actorId,status:"open"});const id=created.id as string;
  const first=await service.current(scope,actor,id);assert.equal(first.version,1);assert.equal(first.hiredCount,0);
  const changed=await service.update(scope,actor,id,{expectedVersion:1,changeReason:"调整标题",title:"更新需求"});assert.equal(changed.version,2);assert.equal(changed.title,"更新需求");
  const history=await service.history(scope,actor,id,{page:1,page_size:20});assert.equal(history.total,1);assert.equal(history.items[0]!.before.title,"初始需求");await db.query("UPDATE hr_recruitment_requisition SET title='外部名称' WHERE id=$1",[id]);assert.equal((await service.history(scope,actor,id,{page:1,page_size:20})).items[0]!.after.title,"更新需求");
  await assert.rejects(service.update(scope,actor,id,{expectedVersion:1,changeReason:"陈旧",title:"拒绝"}),/HR_REQUISITION_VERSION_CONFLICT/);await assert.rejects(service.update(scope,actor,id,{expectedVersion:2,changeReason:"重复",requisitionCode:`REQ-${suffix}`}),/no effective/);
  const duplicate=await recruitment.createRequisition(scope,actor,{requisitionCode:`DUP-${suffix}`,title:"重复源",orgId,headcount:1,ownerUserId:actorId,status:"draft"});await assert.rejects(service.update(scope,actor,id,{expectedVersion:2,changeReason:"编号冲突",requisitionCode:duplicate.requisitionCode}),/HR_REQUISITION_CODE_CONFLICT/);
  const options=await service.referenceOptions(scope,actor,id,{kind:"organization",page:1,page_size:1,keyword:suffix}),optionsPage2=await service.referenceOptions(scope,actor,id,{kind:"organization",page:2,page_size:1,keyword:suffix}),positionOptions=await service.referenceOptions(scope,actor,id,{kind:"position",orgId:nextOrgId,page:1,page_size:1,keyword:suffix}),ownerOptions=await service.referenceOptions(scope,actor,id,{kind:"owner",page:1,page_size:1,keyword:"需求合成办理人"});assert.equal(options.total,2);assert.equal(optionsPage2.items.length,1);assert.equal(positionOptions.total,1);assert.equal(positionOptions.items[0]!.orgId,nextOrgId);assert.ok(ownerOptions.total>=1);await assert.rejects(service.update(scope,actor,id,{expectedVersion:2,changeReason:"跨范围",orgId:randomUUID()}),/Organization is unavailable/);await assert.rejects(service.current({...scope,parkId:"foreign"},actor,id),/not found/);await assert.rejects(service.update(scope,{...actor,permissions:[HR_PERMISSIONS.HR_REQUISITION_READ]},id,{expectedVersion:2,changeReason:"只读",title:"拒绝"}),/permission/);
  const moved=await service.update(scope,actor,id,{expectedVersion:2,changeReason:"调整组织岗位",orgId:nextOrgId,positionId});assert.equal(moved.orgId,nextOrgId);await db.query("UPDATE sys_org SET status='disabled' WHERE id=$1",[nextOrgId]);await db.query("UPDATE hr_position SET status='disabled' WHERE id=$1",[positionId]);await db.query("UPDATE sys_user SET status='disabled' WHERE id=$1",[actorId]);const retained=await service.update(scope,actor,id,{expectedVersion:3,changeReason:"失效当前引用不重绑",approvalNote:"保留"});assert.equal(retained.version,4);await db.query("UPDATE sys_org SET status='enabled' WHERE id=$1",[nextOrgId]);await db.query("UPDATE hr_position SET status='enabled' WHERE id=$1",[positionId]);await db.query("UPDATE sys_user SET status='enabled' WHERE id=$1",[actorId]);
  const candidate=await recruitment.createCandidate(scope,actor,{requisitionId:id,candidateNo:`C-${suffix}`,fullName:"需求候选人"});for(const toStage of ["screening","interview","offer"])await recruitment.moveCandidate(scope,actor,candidate.id,{toStage});const raceVersion=Number((await service.current(scope,actor,id)).version);const race=await Promise.allSettled([service.update(scope,actor,id,{expectedVersion:raceVersion,changeReason:"与转换竞争",title:"竞争更新"}),recruitment.convert(scope,actor,candidate.id,{employeeCode:`E-${suffix}`})]);assert.equal(race.filter(item=>item.status==="fulfilled"&&"employeeId" in item.value).length,1);assert.ok(race.some(item=>item.status==="fulfilled")&&race.some(item=>item.status==="rejected")||race.filter(item=>item.status==="fulfilled").length===2);const converted=await service.current(scope,actor,id);assert.equal(converted.hiredCount,1);assert.equal(converted.status,"closed");
  assert.equal(converted.version,raceVersion+race.filter(item=>item.status==="fulfilled").length);
  for(const outcome of race)if(outcome.status==="rejected")assert.match(String(outcome.reason),/HR_REQUISITION_VERSION_CONFLICT/);
  await assert.rejects(service.update(scope,actor,id,{expectedVersion:Number(converted.version),changeReason:"满额重开",status:"open"}),/HR_REQUISITION_HEADCOUNT_CONFLICT/);const reopened=await service.update(scope,actor,id,{expectedVersion:Number(converted.version),changeReason:"扩容重开",headcount:2,status:"open"});assert.equal(reopened.status,"open");assert.equal(reopened.headcount,2);
  const concurrent=await Promise.allSettled([service.update(scope,actor,id,{expectedVersion:Number(reopened.version),changeReason:"并发甲",approvalNote:"甲"}),service.update(scope,actor,id,{expectedVersion:Number(reopened.version),changeReason:"并发乙",approvalNote:"乙"})]);
  assert.equal(concurrent.filter(item=>item.status==="fulfilled").length,1);
  assert.match(String((concurrent.find(item=>item.status==="rejected") as PromiseRejectedResult).reason),/HR_REQUISITION_VERSION_CONFLICT/);
  const beforeFailure=await service.current(scope,actor,id),historyCount=(await db.query("SELECT count(*)::int total FROM hr_requisition_history WHERE requisition_id=$1",[id]))[0].total;failAudit=true;await assert.rejects(service.update(scope,actor,id,{expectedVersion:Number(beforeFailure.version),changeReason:"审计回滚",title:"不得保存"}),/required audit/);failAudit=false;assert.equal((await service.current(scope,actor,id)).version,beforeFailure.version);assert.equal((await db.query("SELECT count(*)::int total FROM hr_requisition_history WHERE requisition_id=$1",[id]))[0].total,historyCount);
  const auditRows=await db.query("SELECT payload FROM fixture_requisition_audit");assert.ok(auditRows.length>0);await assert.rejects(db.query("UPDATE hr_requisition_history SET change_reason='tampered' WHERE requisition_id=$1",[id]),/append-only/);
 }finally{await db.destroy();}
 // Root creates, migrates, runs and drops this guarded isolated database.
});
