import { BadRequestException, ConflictException, ForbiddenException, Injectable, NotFoundException } from "@nestjs/common";
import { HR_PERMISSIONS, type TenantParkScope } from "@jinhu/shared";
import { plainToInstance } from "class-transformer";
import { validate } from "class-validator";
import { DataSource, type EntityManager } from "typeorm";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { AuditService } from "../audit/audit.service";
import { HrRequisitionHistoryListDto, HrRequisitionReferenceOptionsDto, SaveHrRequisitionDto } from "./dto/hr-recruitment.dto";

type Row = Record<string, unknown>;
const own = (value: object, key: string) => Object.prototype.hasOwnProperty.call(value, key) && (value as Row)[key] !== undefined;
const editable = { requisitionCode: "requisition_code", title: "title", orgId: "org_id", positionId: "position_id", ownerUserId: "owner_user_id", headcount: "headcount", plannedOnboardDate: "planned_onboard_date", approvalNote: "approval_note", status: "status" } as const;
const transitions: Record<string, string[]> = { draft: ["open", "cancelled"], open: ["paused", "closed", "cancelled"], paused: ["open", "closed", "cancelled"], closed: ["open"], cancelled: [] };

@Injectable()
export class HrRequisitionService {
  constructor(private readonly db: DataSource, private readonly audit: AuditService) {}
  private can(actor: JwtPrincipal, permission: string) { return Boolean(actor.isSuper || actor.permissions.includes("*") || actor.permissions.includes(permission)); }
  private requireRead(actor: JwtPrincipal) { if (!this.can(actor, HR_PERMISSIONS.HR_REQUISITION_READ) && !this.can(actor, HR_PERMISSIONS.HR_REQUISITION_TEAM_READ)) throw new ForbiddenException("Recruitment requisition read permission is required"); }
  private requireWrite(actor: JwtPrincipal) { if (!this.can(actor, HR_PERMISSIONS.HR_REQUISITION_READ) || !this.can(actor, HR_PERMISSIONS.HR_REQUISITION_MANAGE)) throw new ForbiddenException("Recruitment requisition manage permission is required"); }
  private first(value: unknown): Row | undefined { return Array.isArray(value) && Array.isArray(value[0]) ? value[0][0] as Row | undefined : Array.isArray(value) ? value[0] as Row | undefined : undefined; }
  private date(value: unknown) { return value == null ? null : value instanceof Date ? `${String(value.getFullYear()).padStart(4,"0")}-${String(value.getMonth()+1).padStart(2,"0")}-${String(value.getDate()).padStart(2,"0")}` : String(value).slice(0,10); }
  private teamPredicate(actorParam: number) { return `EXISTS (WITH RECURSIVE manager_employee AS (SELECT primary_org_id FROM hr_employee WHERE tenant_id=r.tenant_id AND park_id=r.park_id AND user_id=$${actorParam} AND is_deleted=false LIMIT 1), managed_org AS (SELECT primary_org_id AS id FROM manager_employee WHERE primary_org_id IS NOT NULL UNION ALL SELECT child.id FROM sys_org child JOIN managed_org parent ON child.parent_id=parent.id WHERE child.tenant_id=r.tenant_id AND child.park_id=r.park_id AND child.is_deleted=false) SELECT 1 FROM managed_org WHERE managed_org.id=r.org_id)`; }
  private async requisition(manager: EntityManager, scope: TenantParkScope, actor: JwtPrincipal, id: string, lock = false) {
    const params: unknown[] = [id, scope.tenantId, scope.parkId]; const scopeSql = this.can(actor, HR_PERMISSIONS.HR_REQUISITION_READ) ? "" : ` AND ${this.teamPredicate(params.push(actor.sub))}`;
    const row = this.first(await manager.query(`SELECT r.id,r.version,r.requisition_code "requisitionCode",r.title,r.org_id "orgId",o.org_name "orgName",r.position_id "positionId",p.position_name "positionName",r.headcount,r.hired_count "hiredCount",r.owner_user_id "ownerUserId",u.display_name "ownerName",r.planned_onboard_date::text "plannedOnboardDate",r.status,r.approval_note "approvalNote",r.update_time "updatedAt" FROM hr_recruitment_requisition r JOIN sys_org o ON o.id=r.org_id AND o.tenant_id=r.tenant_id AND o.park_id=r.park_id LEFT JOIN hr_position p ON p.id=r.position_id AND p.tenant_id=r.tenant_id AND p.park_id=r.park_id LEFT JOIN sys_user u ON u.id=r.owner_user_id AND u.tenant_id=r.tenant_id AND u.park_id=r.park_id WHERE r.id=$1 AND r.tenant_id=$2 AND r.park_id=$3 AND r.is_deleted=false${scopeSql}${lock ? " FOR UPDATE OF r" : ""}`, params));
    if (!row) throw new NotFoundException("Recruitment requisition not found");
    return this.snapshot(row);
  }
  private snapshot(row: Row): Row { return { id: String(row.id), version: Number(row.version), requisitionCode: String(row.requisitionCode), title: String(row.title), orgId: String(row.orgId), orgName: row.orgName == null ? null : String(row.orgName), positionId: row.positionId == null ? null : String(row.positionId), positionName: row.positionName == null ? null : String(row.positionName), headcount: Number(row.headcount), hiredCount: Number(row.hiredCount), ownerUserId: String(row.ownerUserId), ownerName: row.ownerName == null ? null : String(row.ownerName), plannedOnboardDate: this.date(row.plannedOnboardDate), status: String(row.status), approvalNote: row.approvalNote == null ? null : String(row.approvalNote), updatedAt: row.updatedAt == null ? null : new Date(row.updatedAt as string | Date).toISOString() }; }
  private validDate(value: string) { const match = /^(\d{4})-(\d{2})-(\d{2})$/u.exec(value); if (!match || match[1] === "0000") return false; const date = new Date(Number(match[1]), Number(match[2])-1, Number(match[3])); return date.getFullYear() === Number(match[1]) && date.getMonth() === Number(match[2])-1 && date.getDate() === Number(match[3]); }
  async current(scope: TenantParkScope, actor: JwtPrincipal, id: string) { this.requireRead(actor); return this.db.transaction("REPEATABLE READ", manager => this.requisition(manager, scope, actor, id)); }
  async history(scope: TenantParkScope, actor: JwtPrincipal, id: string, query: HrRequisitionHistoryListDto) { this.requireRead(actor); return this.db.transaction("REPEATABLE READ", async manager => { await this.requisition(manager, scope, actor, id); const count = this.first(await manager.query("SELECT count(*)::int total FROM hr_requisition_history WHERE tenant_id=$1 AND park_id=$2 AND requisition_id=$3", [scope.tenantId,scope.parkId,id])); const items = await manager.query(`SELECT h.id,h.after_version "version",h.change_reason "changeReason",COALESCE(NULLIF(u.display_name,''),'系统用户') "actorName",h.occurred_at "createdAt",h.before_snapshot "before",h.after_snapshot "after" FROM hr_requisition_history h LEFT JOIN sys_user u ON u.id=h.actor_user_id AND u.tenant_id=h.tenant_id AND u.park_id=h.park_id AND u.is_deleted=false WHERE h.tenant_id=$1 AND h.park_id=$2 AND h.requisition_id=$3 ORDER BY h.after_version DESC,h.id DESC LIMIT $4 OFFSET $5`, [scope.tenantId,scope.parkId,id,query.page_size,(query.page-1)*query.page_size]); return { items, total:Number(count?.total ?? 0), page:query.page, page_size:query.page_size }; }); }
  async referenceOptions(scope: TenantParkScope, actor: JwtPrincipal, id: string, query: HrRequisitionReferenceOptionsDto) { this.requireWrite(actor); return this.db.transaction("REPEATABLE READ", async manager => { await this.requisition(manager,scope,actor,id); const limit=query.page_size, offset=(query.page-1)*limit, term=query.keyword?`%${query.keyword}%`:null; let countSql:string, itemsSql:string, params:unknown[];
      if(query.kind==="organization"){params=[scope.tenantId,scope.parkId,term,limit,offset];countSql="SELECT count(*)::int total FROM sys_org o WHERE o.tenant_id=$1 AND o.park_id=$2 AND o.is_deleted=false AND o.status='enabled' AND ($3::text IS NULL OR o.org_name ILIKE $3)";itemsSql="SELECT o.id,o.org_name label FROM sys_org o WHERE o.tenant_id=$1 AND o.park_id=$2 AND o.is_deleted=false AND o.status='enabled' AND ($3::text IS NULL OR o.org_name ILIKE $3) ORDER BY o.org_name,o.id LIMIT $4 OFFSET $5";}
      else if(query.kind==="position"){params=[scope.tenantId,scope.parkId,query.orgId??null,term,limit,offset];countSql="SELECT count(*)::int total FROM hr_position p WHERE p.tenant_id=$1 AND p.park_id=$2 AND p.is_deleted=false AND p.status='enabled' AND ($3::uuid IS NULL OR p.org_id=$3) AND ($4::text IS NULL OR p.position_name ILIKE $4)";itemsSql="SELECT p.id,p.position_name label,p.org_id \"orgId\" FROM hr_position p WHERE p.tenant_id=$1 AND p.park_id=$2 AND p.is_deleted=false AND p.status='enabled' AND ($3::uuid IS NULL OR p.org_id=$3) AND ($4::text IS NULL OR p.position_name ILIKE $4) ORDER BY p.position_name,p.id LIMIT $5 OFFSET $6";}
      else {params=[scope.tenantId,scope.parkId,term,limit,offset];countSql="SELECT count(*)::int total FROM sys_user u WHERE u.tenant_id=$1 AND u.park_id=$2 AND u.is_deleted=false AND u.status='enabled' AND ($3::text IS NULL OR u.display_name ILIKE $3)";itemsSql="SELECT u.id,u.display_name label FROM sys_user u WHERE u.tenant_id=$1 AND u.park_id=$2 AND u.is_deleted=false AND u.status='enabled' AND ($3::text IS NULL OR u.display_name ILIKE $3) ORDER BY u.display_name,u.id LIMIT $4 OFFSET $5";}
      const count=this.first(await manager.query(countSql,params.slice(0,-2))); const items=await manager.query(itemsSql,params); return {items,total:Number(count?.total??0),page:query.page,page_size:query.page_size}; }); }
  async update(scope: TenantParkScope, actor: JwtPrincipal, id: string, input: SaveHrRequisitionDto) { this.requireWrite(actor); if (!input || typeof input!=="object" || Array.isArray(input)) throw new BadRequestException("Recruitment requisition input is invalid"); const dto=plainToInstance(SaveHrRequisitionDto,input); if((await validate(dto,{whitelist:true,forbidNonWhitelisted:true})).length) throw new BadRequestException("Recruitment requisition input is invalid"); if(own(input,"plannedOnboardDate") && dto.plannedOnboardDate != null && !this.validDate(dto.plannedOnboardDate)) throw new BadRequestException("plannedOnboardDate is invalid");
    try { return await this.db.transaction(async manager => { const before=await this.requisition(manager,scope,actor,id,true); if(before.version!==dto.expectedVersion) throw new ConflictException("HR_REQUISITION_VERSION_CONFLICT"); const values:unknown[]=[id,scope.tenantId,scope.parkId,dto.expectedVersion,actor.sub]; const assignments:string[]=[]; const put=(column:string,value:unknown)=>{values.push(value);assignments.push(`${column}=$${values.length}`);}; const hiredCount=Number(before.hiredCount), headcount=Number(before.headcount), effectiveHeadcount=own(input,"headcount") ? Number(dto.headcount) : headcount;
      if(before.status==="cancelled" && Object.keys(editable).some(field=>field!=="status"&&own(input,field))) throw new ConflictException("HR_REQUISITION_STATE_CONFLICT");
      for(const [field,column] of Object.entries(editable)){ if(!own(input,field)) continue; const next=dto[field as keyof typeof editable]; if(next===before[field]) continue; if(field==="status"){if(before.status==="cancelled" || !transitions[String(before.status)]?.includes(String(next))) throw new ConflictException("HR_REQUISITION_STATE_CONFLICT"); if(next==="cancelled" && hiredCount>0) throw new ConflictException("HR_REQUISITION_STATE_CONFLICT"); if((next==="open") && effectiveHeadcount<=hiredCount) throw new ConflictException("HR_REQUISITION_HEADCOUNT_CONFLICT");} if(field==="headcount" && Number(next)<hiredCount) throw new ConflictException("HR_REQUISITION_HEADCOUNT_CONFLICT"); if((field==="orgId"||field==="positionId") && hiredCount>0) throw new ConflictException("HR_REQUISITION_HIRED_REFERENCE_CONFLICT"); put(column,next); }
      if(!assignments.length) throw new BadRequestException("Recruitment requisition has no effective changes"); const effectiveOrg=own(input,"orgId") ? dto.orgId! : String(before.orgId), effectivePosition=own(input,"positionId") ? dto.positionId ?? null : before.positionId, effectiveOwner=own(input,"ownerUserId") ? dto.ownerUserId! : String(before.ownerUserId); const changedOrg=own(input,"orgId")&&dto.orgId!==before.orgId,changedPosition=own(input,"positionId")&&dto.positionId!==before.positionId,changedOwner=own(input,"ownerUserId")&&dto.ownerUserId!==before.ownerUserId;
      if(changedOrg){const org=this.first(await manager.query("SELECT id FROM sys_org WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false AND status='enabled' FOR SHARE",[effectiveOrg,scope.tenantId,scope.parkId]));if(!org)throw new NotFoundException("Organization is unavailable");} if(changedOrg||changedPosition){if(effectivePosition!==null){const position=this.first(await manager.query("SELECT id FROM hr_position WHERE id=$1 AND org_id=$2 AND tenant_id=$3 AND park_id=$4 AND is_deleted=false AND status='enabled' FOR SHARE",[effectivePosition,effectiveOrg,scope.tenantId,scope.parkId]));if(!position)throw new NotFoundException("Position is unavailable");}} if(changedOwner){const owner=this.first(await manager.query("SELECT id FROM sys_user WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false AND status='enabled' FOR SHARE",[effectiveOwner,scope.tenantId,scope.parkId]));if(!owner)throw new NotFoundException("Owner is unavailable");}
      const saved=this.first(await manager.query(`UPDATE hr_recruitment_requisition SET ${assignments.join(",")},version=version+1,update_by=$5,update_time=now() WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND version=$4 AND is_deleted=false RETURNING id`,values)); if(!saved) throw new ConflictException("HR_REQUISITION_VERSION_CONFLICT"); const after=await this.requisition(manager,scope,actor,id); await manager.query("INSERT INTO hr_requisition_history(tenant_id,park_id,requisition_id,before_version,after_version,before_snapshot,after_snapshot,change_reason,actor_user_id) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,$9)",[scope.tenantId,scope.parkId,id,before.version,after.version,JSON.stringify(before),JSON.stringify(after),dto.changeReason,actor.sub]); await this.audit.recordOperationRequired({tenantId:scope.tenantId,parkId:scope.parkId,userId:actor.sub,module:"人力资源管理",resource:"hr.requisition",action:"维护招聘需求",bizType:"hr_recruitment_requisition",bizId:id,beforeJson:{version:before.version,status:before.status},afterJson:{version:after.version,status:after.status},method:"PUT",path:"/hr/recruitment/requisitions/:id",success:true,requestId:null},manager); return after; }); } catch(error) { const pg=error as {code?:string;constraint?:string;driverError?:{code?:string;constraint?:string}}; const cause=pg.driverError??pg; if(cause.code==="23505" && cause.constraint==="uq_hr_requisition_code") throw new ConflictException("HR_REQUISITION_CODE_CONFLICT"); throw error; } }
}
