import "reflect-metadata";
import assert from "node:assert/strict";
import test from "node:test";
import {BadRequestException,ConflictException,ForbiddenException,NotFoundException,ValidationPipe} from "@nestjs/common";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {PERMISSIONS_KEY} from "../../shared/decorators/permissions.decorator";
import type {JwtPrincipal} from "../../shared/types/jwt-principal";
import {HrRewardCategoryVersionsQueryDto} from "./dto/hr-reward-category-versions.dto";
import {VersionHrRewardCategoryDto} from "./dto/hr-rewards.dto";
import {HrRewardsController} from "./hr-rewards.controller";
import {HrRewardsService} from "./hr-rewards.service";
const scope={tenantId:"tenant",parkId:"park"},actor:JwtPrincipal={...scope,sub:"synthetic",username:"synthetic",roles:[],permissions:[H.HR_REWARD_MANAGE]};
const body={kind:"reward",name:"合成新版",impactLevel:"normal",description:"保留说明",expectedVersionNo:2};
function fixture({missing=false,auditFailure=false}={}){
 const calls:{sql:string;params:unknown[]}[]=[],audits:unknown[]=[],isolation:string[]=[];
 const query=async(sql:string,params:unknown[])=>{calls.push({sql,params});if(sql.includes('FOR UPDATE'))return missing?[]:[{id:'category',current_version_no:2}];if(sql.startsWith('SELECT id,category_code'))return missing?[]:[{id:'category',code:'SYN',status:'enabled',currentVersionNo:2}];if(sql.startsWith('SELECT count'))return [{total:22}];if(sql.startsWith('SELECT id,version_no'))return [{id:'v1',versionNo:1,kind:'reward',name:'合成旧版',impactLevel:'normal',description:'旧说明',createdAt:'2026-10-09'}];if(sql.startsWith('INSERT'))return [{id:'v3',versionNo:3,...body}];return [];};
 const service=new HrRewardsService({transaction:async(level:unknown,fn?: (m:unknown)=>Promise<unknown>)=>{if(typeof level==='function')return level({query});isolation.push(String(level));return fn!({query});}} as never,{recordOperationRequired:async(v:unknown)=>{audits.push(v);if(auditFailure)throw Error('required audit unavailable');}} as never);
 return {service,calls,audits,isolation};
}
test('category version history uses exact manage scope, bounded same-snapshot header/items/count and required metadata audit',async()=>{const f=fixture();const result=await f.service.categoryVersions(scope,actor,'category',{page:2,page_size:20});assert.equal(result.total,22);assert.equal(result.category.currentVersionNo,2);assert.equal(result.items[0].description,'旧说明');assert.deepEqual(f.isolation,['REPEATABLE READ']);assert.deepEqual(f.calls[1]!.params,['tenant','park','category',20,20]);assert.match(f.calls[1]!.sql,/ORDER BY version_no DESC,id LIMIT \$4 OFFSET \$5/);assert.ok(f.calls.every(c=>!c.sql.includes('hr_employee')&&!c.sql.includes('hr_reward_discipline_case')));assert.deepEqual(Reflect.getMetadata(PERMISSIONS_KEY,HrRewardsController.prototype.categoryVersions),[H.HR_REWARD_MANAGE]);assert.ok(!JSON.stringify(f.audits).includes('旧说明'));});
test('read-only and foreign principals including super fail before any category transaction',async()=>{for(const a of [{...actor,permissions:[H.HR_REWARD_READ]},{...actor,tenantId:'foreign'},{...actor,parkId:'foreign',isSuper:true}]){const f=fixture();await assert.rejects(f.service.categoryVersions(scope,a,'category',{page:1,page_size:20}),ForbiddenException);await assert.rejects(f.service.versionCategory(scope,a,'category',body),ForbiddenException);assert.equal(f.calls.length,0);}});
test('missing category and failed required history audit never succeed',async()=>{await assert.rejects(fixture({missing:true}).service.categoryVersions(scope,actor,'category',{page:1,page_size:20}),NotFoundException);await assert.rejects(fixture({auditFailure:true}).service.categoryVersions(scope,actor,'category',{page:1,page_size:20}),/required audit unavailable/);});
test('stale expected version rejects while locked before insert and compatible omitted revision still appends',async()=>{const f=fixture();await assert.rejects(f.service.versionCategory(scope,actor,'category',{...body,expectedVersionNo:1}),ConflictException);assert.equal(f.calls.length,1);assert.match(f.calls[0]!.sql,/FOR UPDATE/);const good=fixture();await good.service.versionCategory(scope,actor,'category',body);assert.equal(good.calls.filter(c=>c.sql.startsWith('INSERT')).length,1);assert.equal(good.calls[1]!.params[3],3);assert.ok(!good.calls.some(c=>/UPDATE hr_reward_discipline_case|UPDATE hr_reward_discipline_category_version/.test(c.sql)));const legacy=fixture();const oldBody={kind:body.kind,name:body.name,impactLevel:body.impactLevel,description:body.description};await legacy.service.versionCategory(scope,actor,'category',oldBody);assert.equal(legacy.calls.filter(c=>c.sql.startsWith('INSERT')).length,1);});
test('actual ValidationPipe preserves strict pagination and optional numeric expected revision',async()=>{const pipe=new ValidationPipe({transform:true,whitelist:true,forbidNonWhitelisted:true});const q=(value:unknown)=>pipe.transform(value,{type:'query',metatype:HrRewardCategoryVersionsQueryDto});assert.deepEqual(await q({page:'2',page_size:'20'}),Object.assign(new HrRewardCategoryVersionsQueryDto(),{page:2,page_size:20}));for(const value of [{page:['1','2']},{page:'1e2'},{page_size:101},{keyword:'unexpected'}])await assert.rejects(q(value),BadRequestException);const dto=(value:unknown)=>pipe.transform(value,{type:'body',metatype:VersionHrRewardCategoryDto});for(const expectedVersionNo of [null,'2',0,1.5,2147483648])await assert.rejects(dto({...body,expectedVersionNo}),BadRequestException);await assert.rejects(dto({...body,name:"  "}),BadRequestException);assert.equal((await dto(body)).expectedVersionNo,2);const oldBody={kind:body.kind,name:body.name,impactLevel:body.impactLevel,description:body.description};assert.equal((await dto(oldBody)).expectedVersionNo,undefined);});
