import { Body,Controller,Get,Param,ParseUUIDPipe,Post,Query,UseInterceptors } from "@nestjs/common";
import { HR_PERMISSIONS,type TenantParkScope } from "@jinhu/shared";
import { CurrentScope } from "../../shared/decorators/current-scope.decorator";
import { CurrentUser } from "../../shared/decorators/current-user.decorator";
import { RequireModule } from "../../shared/decorators/modules.decorator";
import { RequireAnyPermissions,RequirePermissions } from "../../shared/decorators/permissions.decorator";
import { IdempotencyInterceptor } from "../../shared/interceptors/idempotency.interceptor";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { AuditLog } from "../audit/decorators/audit-log.decorator";
import { CreateHrTrainingCourseDto,CreateHrTrainingCourseVersionDto,CreateHrTrainingPlanDto,CreateHrTrainingPositionRequirementDto,HrTrainingCorrectionDto,HrTrainingListDto,HrTrainingParticipantResultDto } from "./dto/hr-training.dto";
import { HrTrainingService } from "./hr-training.service";
@Controller("hr/training") @RequireModule("hr")
export class HrTrainingController {
 constructor(private readonly service:HrTrainingService){}
 @Get("courses") @RequireAnyPermissions(HR_PERMISSIONS.HR_TRAINING_READ,HR_PERMISSIONS.HR_TRAINING_TEAM_READ,HR_PERMISSIONS.HR_TRAINING_SELF_READ) courses(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.listCourses(s,a);}
 @Get("plan-options") @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) planOptions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.planOptions(s,a);}
 @Get("requirement-options") @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE) requirementOptions(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.requirementOptions(s,a);}
 @Get("position-requirements") @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE) positionRequirements(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.listPositionRequirements(s,a);}
 @Get("position-requirement-gaps") @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) positionRequirementGaps(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.positionRequirementGaps(s,a);}
 @Post("courses") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_course",action:"创建培训课程",bizType:"hr_training_course",captureBody:false}) createCourse(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrTrainingCourseDto){return this.service.createCourse(s,a,d);}
 @Post("courses/:id/versions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_course_version",action:"发布课程版本",bizType:"hr_training_course",bizIdParam:"id",captureBody:false}) versionCourse(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:CreateHrTrainingCourseVersionDto){return this.service.versionCourse(s,a,id,d);}
 @Post("position-requirements") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_position_requirement",action:"设置岗位必修课程",bizType:"hr_training_position_requirement",captureBody:false}) createPositionRequirement(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrTrainingPositionRequirementDto){return this.service.createPositionRequirement(s,a,d);}
 @Post("position-requirements/:id/disable") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_position_requirement",action:"停用岗位必修课程",bizType:"hr_training_position_requirement",bizIdParam:"id",captureBody:false}) disablePositionRequirement(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.disablePositionRequirement(s,a,id);}
 @Get("plans") @RequireAnyPermissions(HR_PERMISSIONS.HR_TRAINING_READ,HR_PERMISSIONS.HR_TRAINING_TEAM_READ,HR_PERMISSIONS.HR_TRAINING_SELF_READ) plans(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Query()q:HrTrainingListDto){return this.service.listPlans(s,a,q);}
 @Get("plans/:id") @RequireAnyPermissions(HR_PERMISSIONS.HR_TRAINING_READ,HR_PERMISSIONS.HR_TRAINING_TEAM_READ,HR_PERMISSIONS.HR_TRAINING_SELF_READ) plan(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.planDetail(s,a,id);}
 @Post("plans") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_plan",action:"创建培训计划",bizType:"hr_training_plan",captureBody:false}) createPlan(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Body()d:CreateHrTrainingPlanDto){return this.service.createPlan(s,a,d);}
 @Post("plans/:id/publish") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_plan",action:"发布培训计划",bizType:"hr_training_plan",bizIdParam:"id",captureBody:false}) publish(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.publish(s,a,id);}
 @Post("plans/:id/start") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_plan",action:"开始培训计划",bizType:"hr_training_plan",bizIdParam:"id",captureBody:false}) start(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.start(s,a,id);}
 @Post("plans/:id/complete") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_plan",action:"完成培训计划",bizType:"hr_training_plan",bizIdParam:"id",captureBody:false}) completePlan(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.completePlan(s,a,id);}
 @Post("plans/:id/cancel") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_plan",action:"取消培训计划",bizType:"hr_training_plan",bizIdParam:"id",captureBody:false}) cancel(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.cancel(s,a,id);}
 @Post("participants/:id/check-in") @UseInterceptors(new IdempotencyInterceptor()) @RequireAnyPermissions(HR_PERMISSIONS.HR_TRAINING_PROGRESS_MANAGE,HR_PERMISSIONS.HR_TRAINING_SELF_ACTION) @AuditLog({module:"人力资源管理",resource:"hr.training_participant",action:"培训签到",bizType:"hr_training_participant",bizIdParam:"id",captureBody:false}) checkIn(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.checkIn(s,a,id);}
 @Post("participants/:id/complete") @UseInterceptors(new IdempotencyInterceptor()) @RequireAnyPermissions(HR_PERMISSIONS.HR_TRAINING_PROGRESS_MANAGE,HR_PERMISSIONS.HR_TRAINING_SELF_ACTION) @AuditLog({module:"人力资源管理",resource:"hr.training_participant",action:"记录培训完成",bizType:"hr_training_participant",bizIdParam:"id",captureBody:false}) complete(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrTrainingParticipantResultDto){return this.service.completeParticipant(s,a,id,d);}
 @Post("participants/:id/corrections") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PROGRESS_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_result_correction",action:"更正培训结果",bizType:"hr_training_participant",bizIdParam:"id",captureBody:false}) correct(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrTrainingCorrectionDto){return this.service.correct(s,a,id,d);}
 @Post("overdue-reminders") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.training_overdue",action:"生成培训逾期提醒",bizType:"hr_training_plan",captureBody:false}) overdue(@CurrentScope()s:TenantParkScope,@CurrentUser()a:JwtPrincipal){return this.service.sendOverdueReminders(s,a);}
}
