import "reflect-metadata";
import assert from "node:assert/strict";
import {randomUUID} from "node:crypto";
import {test} from "node:test";
import {DataSource} from "typeorm";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrGoalReportService} from "./hr-goal-report.service";
const enabled=process.env.HR_WORK_REPORT_PAGE_PG_REQUIRED==="1";
test("PostgreSQL reports preserve own/managed-tree scope, stable pages, full summaries and exact links",{skip:!enabled},async()=>{
 assert.equal(process.env.POSTGRES_HOST,"127.0.0.1");assert.equal(process.env.POSTGRES_PORT,"15483");const connection={type:"postgres" as const,host:"127.0.0.1",port:15483,username:"postgres"},name=`hr_report_page_${randomUUID().replaceAll("-","")}`;
 const admin=new DataSource({...connection,database:"postgres"});let db:DataSource|undefined,created=false;
 try{await admin.initialize();await admin.query(`CREATE DATABASE ${name}`);created=true;db=new DataSource({...connection,database:name});await db.initialize();assert.equal((await db.query("SELECT current_database() name"))[0].name,name);
 await db.query(`CREATE TABLE sys_org(id uuid PRIMARY KEY,tenant_id text,park_id text,parent_id uuid,leader_user_id uuid,is_deleted boolean DEFAULT false,status text DEFAULT 'enabled');CREATE TABLE hr_employee(id uuid PRIMARY KEY,tenant_id text,park_id text,user_id uuid,primary_org_id uuid,manager_employee_id uuid,full_name text,is_deleted boolean DEFAULT false);CREATE TABLE hr_work_report(id uuid PRIMARY KEY,tenant_id text,park_id text,employee_id uuid,report_type text,period_start date,period_end date,title text,completed_work text,next_plan text,risks text,questions_and_suggestions text,collaboration_needs text,hours numeric,status text,submission_no int DEFAULT 0,review_comment text,submitted_at timestamptz,reviewed_at timestamptz,create_time timestamptz DEFAULT '2026-10-01',is_deleted boolean DEFAULT false);CREATE TABLE hr_goal(id uuid PRIMARY KEY,tenant_id text,park_id text,goal_name text);CREATE TABLE hr_work_report_goal(report_id uuid,goal_id uuid,tenant_id text,park_id text,proposed_progress numeric,proposed_current_value numeric,suggestion_summary text,is_deleted boolean DEFAULT false)`);
 const tenant="tenant-a",park="park-a",manager=randomUUID(),self=randomUUID(),root=randomUUID(),child=randomUUID(),sibling=randomUUID(),employee=randomUUID(),rootEmployee=randomUUID(),childEmployee=randomUUID(),foreignEmployee=randomUUID(),deletedEmployee=randomUUID(),siblingEmployee=randomUUID();
 await db.query(`INSERT INTO sys_org(id,tenant_id,park_id,parent_id,leader_user_id) VALUES($1,$4,$5,NULL,$6),($2,$4,$5,$1,NULL),($3,$4,$5,NULL,NULL)`,[root,child,sibling,tenant,park,manager]);
 for(const [id,user,org,deleted,t,p] of [[employee,self,child,false,tenant,park],[rootEmployee,randomUUID(),root,false,tenant,park],[childEmployee,randomUUID(),child,false,tenant,park],[siblingEmployee,randomUUID(),sibling,false,tenant,park],[foreignEmployee,randomUUID(),child,false,"other",park],[deletedEmployee,randomUUID(),child,true,tenant,park]])await db.query(`INSERT INTO hr_employee(id,tenant_id,park_id,user_id,primary_org_id,full_name,is_deleted)VALUES($1,$2,$3,$4,$5,'Synthetic employee',$6)`,[id,t,p,user,org,deleted]);
 const statuses=["draft","submitted","resubmitted","confirmed","returned"],ids:string[]=[];
 const insert=async(id:string,employeeId:string,status:string,type="daily",t=tenant,p=park,deleted=false)=>db!.query(`INSERT INTO hr_work_report(id,tenant_id,park_id,employee_id,report_type,period_start,period_end,title,completed_work,hours,status,is_deleted)VALUES($1,$2,$3,$4,$5,'2026-10-01','2026-10-01','Synthetic title','Synthetic work',0,$6,$7)`,[id,t,p,employeeId,type,status,deleted]);
 for(let n=1;n<=45;n++){const id=randomUUID();ids.push(id);await insert(id,employee,statuses[n%5]!,n===44?"weekly":"daily");}
 await insert(randomUUID(),rootEmployee,"draft");await insert(randomUUID(),childEmployee,"returned");await insert(randomUUID(),siblingEmployee,"submitted");await insert(randomUUID(),foreignEmployee,"submitted","daily","other");await insert(randomUUID(),employee,"submitted","daily",tenant,"other");await insert(randomUUID(),deletedEmployee,"submitted");await insert(randomUUID(),employee,"submitted","daily",tenant,park,true);
 const goal=randomUUID();await db.query("INSERT INTO hr_goal VALUES($1,$2,$3,'Synthetic goal')",[goal,tenant,park]);await db.query("INSERT INTO hr_work_report_goal VALUES($1,$2,$3,$4,0,0,'Synthetic suggestion',false)",[ids[0],goal,tenant,park]);
 const audit:unknown[]=[];const service=new HrGoalReportService(db,{} as never,{recordOperationRequired:async(input:unknown)=>{audit.push(input)}} as never);const scope={tenantId:tenant,parkId:park},actor={...scope,sub:self,username:"synthetic",roles:[],permissions:[H.HR_WORK_REPORT_SELF_READ]};const seen=new Set<string>();let foundLink=false;
 for(let page=1;page<=3;page++){const result=await service.reportsPage(scope,actor,{page,page_size:20});assert.equal(result.total,45);assert.deepEqual(result.summary,{pending:18,returned:9});assert.equal(result.items.length,page===3?5:20);for(const row of result.items){const id=String(row.id);assert.ok(!seen.has(id));seen.add(id);assert.ok(ids.includes(id));assert.equal("tenant_id" in row,false);assert.equal(row.hours,"0");if(row.goalSuggestions.length){foundLink=true;assert.deepEqual(row.goalSuggestions,[{goalId:goal,goalName:"Synthetic goal",proposedProgress:"0",proposedCurrentValue:"0",suggestionSummary:"Synthetic suggestion"}]);}}}
 assert.equal(seen.size,45);assert.ok(foundLink);const team=await service.reportsPage(scope,{...actor,sub:manager,permissions:[H.HR_WORK_REPORT_REVIEW]},{page:1,page_size:20},true);assert.equal(team.total,47);assert.deepEqual(team.summary,{pending:18,returned:10});assert.equal(team.items[0]?.employeeName,"Synthetic employee");const filtered=await service.reportsPage(scope,actor,{page:1,page_size:20,report_type:"weekly",status:"returned"});assert.equal(filtered.total,1);assert.equal(filtered.items[0]?.id,ids[43]);const empty=await service.reportsPage(scope,actor,{page:999,page_size:20});assert.equal(empty.total,45);assert.deepEqual(empty.items,[]);assert.equal(audit.length,6);await assert.rejects(service.reportsPage(scope,{...actor,sub:randomUUID()},{page:1,page_size:20}),/No employee profile/);
 }finally{if(db?.isInitialized)await db.destroy();if(admin.isInitialized){if(created){await admin.query(`DROP DATABASE ${name}`);assert.equal((await admin.query("SELECT count(*)::int total FROM pg_database WHERE datname=$1",[name]))[0].total,0);}await admin.destroy();}}
});
