import { Body,Controller,Get,Param,ParseUUIDPipe,Post,Put,Query,UseInterceptors } from "@nestjs/common";
import { HR_PERMISSIONS,type TenantParkScope } from "@jinhu/shared";
import { CurrentScope } from "../../shared/decorators/current-scope.decorator";
import { CurrentUser } from "../../shared/decorators/current-user.decorator";
import { RequireModule } from "../../shared/decorators/modules.decorator";
import { RequireAnyPermissions,RequirePermissions } from "../../shared/decorators/permissions.decorator";
import { IdempotencyInterceptor } from "../../shared/interceptors/idempotency.interceptor";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { AuditLog } from "../audit/decorators/audit-log.decorator";
import { AdjustHrPayslipDto,AssignHrCompensationDto,CreateHrApprovalDto,CreateHrAttendancePunchDto,CreateHrAttendanceRequestDto,CreateHrAttendanceShiftDto,CreateHrCompensationPlanDto,CreateHrContractChangeDto,CreateHrContractDto,CreateHrEmployeeDto,CreateHrEmployeeScheduleDto,CreateHrFeedbackAssignmentDto,CreateHrFeedbackCycleDto,CreateHrGoalCheckinDto,CreateHrGoalCycleDto,CreateHrGoalDto,CreateHrPayrollPeriodDto,CreateHrPayrollRunDto,CreateHrPerformanceCycleDto,CreateHrPerformancePlanDto,CreateHrPositionDto,CreateHrWorkReportDto,HrApprovalActionDto,HrAttendanceCalendarQueryDto,HrAttendanceDailyQueryDto,HrAttendanceRequestListQueryDto,HrContractActionDto,HrContractChangeActionDto,HrContractListQueryDto,HrEmploymentTransitionDto,HrInsurancePeriodQueryDto,HrListQueryDto,RecalculateHrAttendanceDto,ReviewHrAttendanceRequestDto,ReviewHrWorkReportDto,ScoreHrPerformanceDto,SubmitHrFeedbackDto,UpdateHrEmployeeDto,UpdateHrEmployeeProfileDto } from "./dto/hr.dto";
import { HrService } from "./hr.service";

@Controller("hr") @RequireModule("hr")
export class HrController {
 constructor(private readonly service:HrService){}
 @Get("employees") @RequireAnyPermissions(HR_PERMISSIONS.HR_EMPLOYEE_READ,HR_PERMISSIONS.HR_EMPLOYEE_SELF_READ,HR_PERMISSIONS.HR_WORK_REPORT_TEAM_REVIEW,HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) employees(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrListQueryDto){return this.service.listEmployees(s,u,q);}
 @Get("employees/me") @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYEE_SELF_READ) me(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.myEmployee(s,u);}
 @Get("employees/:id") @RequireAnyPermissions(HR_PERMISSIONS.HR_EMPLOYEE_READ,HR_PERMISSIONS.HR_EMPLOYEE_SELF_READ,HR_PERMISSIONS.HR_WORK_REPORT_TEAM_REVIEW,HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) employee(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.detailEmployeeForActor(s,u,id);}
 @Get("employees/:id/events") @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYMENT_EVENT_READ) events(@CurrentScope()s:TenantParkScope,@Param("id",new ParseUUIDPipe())id:string){return this.service.employeeEvents(s,id);}
 @Get("employees/:id/profile") @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_READ) profile(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.employeeProfile(s,u,id);}
 @Put("employees/:id/profile") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.employee_profile",action:"更新员工敏感档案",bizType:"hr_employee",bizIdParam:"id",captureBody:false}) updateProfile(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:UpdateHrEmployeeProfileDto){return this.service.updateEmployeeProfile(s,u,id,d);}
 @Post("employees/:id/transitions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYMENT_TRANSITION) @AuditLog({module:"人力资源管理",resource:"hr.employment",action:"办理员工任职变动",bizType:"hr_employee",bizIdParam:"id",captureBody:false}) transition(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrEmploymentTransitionDto){return this.service.transitionEmployment(s,u,id,d);}
 @Post("employees") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYEE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.employee",action:"创建员工档案",bizType:"hr_employee",captureBody:false}) createEmployee(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrEmployeeDto){return this.service.createEmployee(s,u,d);}
 @Put("employees/:id") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_EMPLOYEE_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.employee",action:"更新员工档案",bizType:"hr_employee",bizIdParam:"id",captureBody:false}) updateEmployee(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:UpdateHrEmployeeDto){return this.service.updateEmployee(s,u,id,d);}
 @Get("positions") @RequirePermissions(HR_PERMISSIONS.HR_POSITION_READ) positions(@CurrentScope()s:TenantParkScope){return this.service.listPositions(s);}
 @Post("positions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_POSITION_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.position",action:"创建岗位",bizType:"hr_position"}) createPosition(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrPositionDto){return this.service.createPosition(s,u,d);}
 @Get("contracts") @RequireAnyPermissions(HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_SELF_READ) contracts(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrContractListQueryDto){return this.service.listContracts(s,u,q);}
 @Get("contracts/me") @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_SELF_READ) myContracts(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrContractListQueryDto){return this.service.listMyContracts(s,u,q);}
 @Get("contract-types") @RequireAnyPermissions(HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_MANAGE) contractTypes(@CurrentScope()s:TenantParkScope){return this.service.listContractTypes(s);}
 @Post("contracts") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.contract",action:"新建劳动合同草稿",bizType:"hr_contract",captureBody:false}) createContract(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrContractDto){return this.service.createContract(s,u,d);}
 @Post("contracts/:id/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.contract",action:"办理劳动合同状态",bizType:"hr_contract",bizIdParam:"id",captureBody:false}) contractAction(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrContractActionDto){return this.service.actContract(s,u,id,d);}
 @Post("contracts/:id/changes") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.contract_change",action:"新建劳动合同变更草稿",bizType:"hr_contract",bizIdParam:"id",captureBody:false}) createContractChange(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:CreateHrContractChangeDto){return this.service.createContractChange(s,u,id,d);}
 @Post("contracts/:id/changes/:changeId/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_CONTRACT_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.contract_change",action:"办理劳动合同变更状态",bizType:"hr_contract_change",bizIdParam:"changeId",captureBody:false}) contractChangeAction(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Param("changeId",new ParseUUIDPipe())changeId:string,@Body()d:HrContractChangeActionDto){return this.service.actContractChange(s,u,id,changeId,d);}
 @Get("contracts/:id") @RequireAnyPermissions(HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_SELF_READ) contract(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.contractDetail(s,u,id);}
 @Get("attendance/calendars") @RequireAnyPermissions(HR_PERMISSIONS.HR_ATTENDANCE_READ,HR_PERMISSIONS.HR_ATTENDANCE_TEAM_READ,HR_PERMISSIONS.HR_ATTENDANCE_SELF_READ) attendanceCalendars(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrAttendanceCalendarQueryDto){return this.service.listAttendanceCalendars(s,u,q);}
 @Get("attendance/requests") @RequireAnyPermissions(HR_PERMISSIONS.HR_ATTENDANCE_READ,HR_PERMISSIONS.HR_ATTENDANCE_TEAM_READ,HR_PERMISSIONS.HR_ATTENDANCE_SELF_READ) attendanceRequests(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrAttendanceRequestListQueryDto){return this.service.listAttendanceRequests(s,u,q);}
 @Post("attendance/requests") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_REQUEST) @AuditLog({module:"人力资源管理",resource:"hr.attendance_request",action:"创建考勤申请草稿",bizType:"hr_attendance_request",captureBody:false}) createAttendanceRequest(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrAttendanceRequestDto){return this.service.createAttendanceRequest(s,u,d);}
 @Post("attendance/requests/:id/submit") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_REQUEST) @AuditLog({module:"人力资源管理",resource:"hr.attendance_request",action:"提交考勤申请",bizType:"hr_attendance_request",bizIdParam:"id",captureBody:false}) submitAttendanceRequest(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.submitAttendanceRequest(s,u,id);}
 @Post("attendance/requests/:id/cancel") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_REQUEST) @AuditLog({module:"人力资源管理",resource:"hr.attendance_request",action:"取消考勤申请",bizType:"hr_attendance_request",bizIdParam:"id",captureBody:false}) cancelAttendanceRequest(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.cancelAttendanceRequest(s,u,id);}
 @Post("attendance/requests/:id/approve") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_APPROVE) @AuditLog({module:"人力资源管理",resource:"hr.attendance_request",action:"批准考勤申请",bizType:"hr_attendance_request",bizIdParam:"id",captureBody:false}) approveAttendanceRequest(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ReviewHrAttendanceRequestDto){return this.service.reviewAttendanceRequest(s,u,id,"approve",d);}
 @Post("attendance/requests/:id/reject") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_APPROVE) @AuditLog({module:"人力资源管理",resource:"hr.attendance_request",action:"退回考勤申请",bizType:"hr_attendance_request",bizIdParam:"id",captureBody:false}) rejectAttendanceRequest(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ReviewHrAttendanceRequestDto){return this.service.reviewAttendanceRequest(s,u,id,"reject",d);}
 @Get("attendance/shifts") @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_OPERATE) attendanceShifts(@CurrentScope()s:TenantParkScope){return this.service.listAttendanceShifts(s);}
 @Post("attendance/shifts") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_OPERATE) @AuditLog({module:"人力资源管理",resource:"hr.attendance_shift",action:"创建考勤班次",bizType:"hr_attendance_shift",captureBody:false}) createAttendanceShift(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrAttendanceShiftDto){return this.service.createAttendanceShift(s,u,d);}
 @Post("attendance/schedules") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_OPERATE) @AuditLog({module:"人力资源管理",resource:"hr.employee_schedule",action:"创建员工排班",bizType:"hr_employee_schedule",captureBody:false}) createAttendanceSchedule(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrEmployeeScheduleDto){return this.service.createEmployeeSchedule(s,u,d);}
 @Post("attendance/punch-events") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_OPERATE) @AuditLog({module:"人力资源管理",resource:"hr.attendance_punch_event",action:"接收考勤打卡事件",bizType:"hr_attendance_punch_event",captureBody:false}) createAttendancePunch(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrAttendancePunchDto){return this.service.createAttendancePunch(s,u,d);}
 @Get("attendance/daily-results") @RequireAnyPermissions(HR_PERMISSIONS.HR_ATTENDANCE_READ,HR_PERMISSIONS.HR_ATTENDANCE_TEAM_READ,HR_PERMISSIONS.HR_ATTENDANCE_SELF_READ) attendanceDaily(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrAttendanceDailyQueryDto){return this.service.listAttendanceDaily(s,u,q);}
 @Post("attendance/daily-results/recalculate") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_ATTENDANCE_OPERATE) @AuditLog({module:"人力资源管理",resource:"hr.attendance_daily",action:"重算员工日考勤",bizType:"hr_employee_attendance_daily_result",captureBody:false}) recalculateAttendance(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:RecalculateHrAttendanceDto){return this.service.recalculateAttendanceDay(s,u,d);}
 @Get("insurance/periods") @RequireAnyPermissions(HR_PERMISSIONS.HR_INSURANCE_READ,HR_PERMISSIONS.HR_INSURANCE_TEAM_READ,HR_PERMISSIONS.HR_INSURANCE_SELF_READ) insurancePeriods(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrInsurancePeriodQueryDto){return this.service.listInsurancePeriods(s,u,q);}
 @Get("insurance/periods/me") @RequirePermissions(HR_PERMISSIONS.HR_INSURANCE_SELF_READ) myInsurancePeriods(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Query()q:HrInsurancePeriodQueryDto){return this.service.listInsurancePeriods(s,u,q,true);}
 @Get("insurance/periods/:id") @RequireAnyPermissions(HR_PERMISSIONS.HR_INSURANCE_READ,HR_PERMISSIONS.HR_INSURANCE_TEAM_READ,HR_PERMISSIONS.HR_INSURANCE_SELF_READ) insurancePeriod(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.insurancePeriodDetail(s,u,id);}
 @Get("goal-cycles") @RequirePermissions(HR_PERMISSIONS.HR_GOAL_READ) goalCycles(@CurrentScope()s:TenantParkScope){return this.service.listGoalCycles(s);}
 @Post("goal-cycles") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_MANAGE) createGoalCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrGoalCycleDto){return this.service.createGoalCycle(s,u,d);}
 @Get("goals") @RequirePermissions(HR_PERMISSIONS.HR_GOAL_READ) goals(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.listGoals(s,u);}
 @Get("goals/me") @RequirePermissions(HR_PERMISSIONS.HR_GOAL_SELF_READ) myGoals(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.listGoals(s,u,true);}
 @Post("goals") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_MANAGE) createGoal(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrGoalDto){return this.service.createGoal(s,u,d);}
 @Get("goals/:id/checkins") @RequirePermissions(HR_PERMISSIONS.HR_GOAL_SELF_READ) goalCheckins(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.goalCheckins(s,u,id);}
 @Post("goals/:id/checkins") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_GOAL_SELF_READ) createGoalCheckin(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:CreateHrGoalCheckinDto){return this.service.createGoalCheckin(s,u,id,d);}
 @Get("work-reports/me") @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_SELF_MANAGE) myReports(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.myWorkReports(s,u);}
 @Post("work-reports/me") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_SELF_MANAGE) createMyReport(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrWorkReportDto){return this.service.createMyWorkReport(s,u,d);}
 @Get("work-reports/team") @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_TEAM_REVIEW) teamReports(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.teamWorkReports(s,u);}
 @Post("work-reports/:id/review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_WORK_REPORT_TEAM_REVIEW) reviewReport(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ReviewHrWorkReportDto){return this.service.reviewWorkReport(s,u,id,d);}
 @Get("performance/cycles") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_READ) performanceCycles(@CurrentScope()s:TenantParkScope){return this.service.listPerformanceCycles(s);}
 @Post("performance/cycles") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) createPerformanceCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrPerformanceCycleDto){return this.service.createPerformanceCycle(s,u,d);}
 @Post("performance/plans") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGE) createPerformancePlan(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrPerformancePlanDto){return this.service.createPerformancePlan(s,u,d);}
 @Get("performance/plans/me") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_SELF_REVIEW) myPerformance(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.myPerformancePlans(s,u);}
 @Post("performance/plans/:id/self-review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_SELF_REVIEW) selfReview(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ScoreHrPerformanceDto){return this.service.selfReviewPerformance(s,u,id,d);}
 @Get("performance/plans/team") @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) managerPerformance(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.managerPerformancePlans(s,u);}
 @Post("performance/plans/:id/manager-review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_MANAGER_REVIEW) managerReview(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ScoreHrPerformanceDto){return this.service.managerReviewPerformance(s,u,id,d);}
 @Post("performance/plans/:id/calibrate") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE) calibrate(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:ScoreHrPerformanceDto){return this.service.calibratePerformance(s,u,id,d);}
 @Post("feedback/cycles") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_FEEDBACK_MANAGE) createFeedbackCycle(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrFeedbackCycleDto){return this.service.createFeedbackCycle(s,u,d);}
 @Get("feedback/cycles") @RequirePermissions(HR_PERMISSIONS.HR_FEEDBACK_MANAGE) feedbackCycles(@CurrentScope()s:TenantParkScope){return this.service.listFeedbackCycles(s);}
 @Post("feedback/assignments") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_FEEDBACK_MANAGE) assignFeedback(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrFeedbackAssignmentDto){return this.service.createFeedbackAssignment(s,u,d);}
 @Get("feedback/assignments/me") @RequirePermissions(HR_PERMISSIONS.HR_FEEDBACK_RESPOND) myFeedback(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.myFeedbackAssignments(s,u);}
 @Post("feedback/assignments/:id/submit") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_FEEDBACK_RESPOND) submitFeedback(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:SubmitHrFeedbackDto){return this.service.submitFeedback(s,u,id,d);}
 @Get("feedback/cycles/:cycleId/subjects/:employeeId/result") @RequirePermissions(HR_PERMISSIONS.HR_FEEDBACK_RESULT_READ) feedbackResult(@CurrentScope()s:TenantParkScope,@Param("cycleId",new ParseUUIDPipe())cycleId:string,@Param("employeeId",new ParseUUIDPipe())employeeId:string){return this.service.feedbackResult(s,employeeId,cycleId);}
 @Get("compensation/plans") @RequirePermissions(HR_PERMISSIONS.HR_COMPENSATION_READ) compensationPlans(@CurrentScope()s:TenantParkScope){return this.service.listCompensationPlans(s);}
 @Post("compensation/plans") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_COMPENSATION_MANAGE) createCompensationPlan(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrCompensationPlanDto){return this.service.createCompensationPlan(s,u,d);}
 @Post("compensation/assignments") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_COMPENSATION_MANAGE) assignCompensation(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:AssignHrCompensationDto){return this.service.assignCompensation(s,u,d);}
 @Get("payroll/periods") @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_READ) payrollPeriods(@CurrentScope()s:TenantParkScope){return this.service.listPayrollPeriods(s);}
 @Post("payroll/periods") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_MANAGE) createPayrollPeriod(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrPayrollPeriodDto){return this.service.createPayrollPeriod(s,u,d);}
 @Get("payroll/runs") @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_READ) payrollRuns(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.listPayrollRuns(s,u);}
 @Get("payroll/runs/:id/payslips") @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_READ) payrollRunPayslips(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.payrollRunPayslips(s,u,id);}
 @Post("payroll/runs") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.payroll_run",action:"生成工资批次",bizType:"hr_payroll_run",captureBody:false}) createPayrollRun(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrPayrollRunDto){return this.service.createPayrollRun(s,u,d);}
 @Post("payroll/runs/:id/review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.payroll_run",action:"提交工资复核",bizType:"hr_payroll_run",bizIdParam:"id",captureBody:false}) reviewPayroll(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.transitionPayrollRun(s,u,id,"review");}
 @Post("payroll/runs/:id/confirm") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_CONFIRM) @AuditLog({module:"人力资源管理",resource:"hr.payroll_run",action:"确认并冻结工资",bizType:"hr_payroll_run",bizIdParam:"id",captureBody:false}) confirmPayroll(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.transitionPayrollRun(s,u,id,"confirm");}
 @Put("payroll/runs/:runId/payslips/:payslipId") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_PAYROLL_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.payslip",action:"调整工资单",bizType:"hr_payslip",bizIdParam:"payslipId",captureBody:false}) adjustPayslip(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("runId",new ParseUUIDPipe())runId:string,@Param("payslipId",new ParseUUIDPipe())payslipId:string,@Body()d:AdjustHrPayslipDto){return this.service.adjustPayslip(s,u,runId,payslipId,d);}
 @Get("payslips/me") @RequirePermissions(HR_PERMISSIONS.HR_PAYSLIP_SELF_READ) myPayslips(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.myPayslips(s,u);}
 @Get("approvals/me") @RequirePermissions(HR_PERMISSIONS.HR_APPROVAL_SELF_MANAGE) myApprovals(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal){return this.service.myApprovals(s,u);}
 @Post("approvals") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_APPROVAL_SELF_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.approval",action:"创建人事申请",bizType:"hr_approval",captureBody:false}) createApproval(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateHrApprovalDto){return this.service.createApproval(s,u,d);}
 @Post("approvals/:id/actions") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_APPROVAL_SELF_MANAGE) @AuditLog({module:"人力资源管理",resource:"hr.approval",action:"提交或撤回人事申请",bizType:"hr_approval",bizIdParam:"id",captureBody:false}) approvalAction(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrApprovalActionDto){return this.service.actApproval(s,u,id,d,false);}
 @Get("approvals/pending") @RequirePermissions(HR_PERMISSIONS.HR_APPROVAL_REVIEW) pendingApprovals(@CurrentScope()s:TenantParkScope){return this.service.pendingApprovals(s);}
 @Post("approvals/:id/review") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(HR_PERMISSIONS.HR_APPROVAL_REVIEW) @AuditLog({module:"人力资源管理",resource:"hr.approval",action:"审核人事申请",bizType:"hr_approval",bizIdParam:"id",captureBody:false}) reviewApproval(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HrApprovalActionDto){return this.service.actApproval(s,u,id,d,true);}
}
