import { HrPositionMaintenanceController } from "./hr-position-maintenance.controller";
import { HrPositionMaintenanceService } from "./hr-position-maintenance.service";
import { HrPayrollPeriodLifecycleController } from "./hr-payroll-period-lifecycle.controller";
import { HrPayrollPeriodLifecycleService } from "./hr-payroll-period-lifecycle.service";
import { HrPayrollFormalRunController } from "./hr-payroll-formal-run.controller";
import { HrPayrollFormalRunService } from "./hr-payroll-formal-run.service";
import { HrPayrollFormalInputController } from "./hr-payroll-formal-input.controller";
import { HrPayrollFormalInputService } from "./hr-payroll-formal-input.service";
import { HrPayrollFormalRuleController } from "./hr-payroll-formal-rule.controller";
import { HrPayrollFormalRuleService } from "./hr-payroll-formal-rule.service";
import { HrCustomValueController } from "./hr-custom-value.controller";
import { HrCustomValueService } from "./hr-custom-value.service";
import { DataScopesModule } from "../data-scopes/data-scopes.module";
import { Module } from "@nestjs/common";
import { TypeOrmModule } from "@nestjs/typeorm";
import { OrgEntity } from "../orgs/entities/org.entity";
import { UserEntity } from "../users/entities/user.entity";
import { UserMessageEntity } from "../workflow/entities/user-message.entity";
import { AuditModule } from "../audit/audit.module";
import { HR_ENTITIES } from "./entities/hr.entities";
import { HrController } from "./hr.controller";
import { HrNotificationService } from "./hr-notification.service";
import { HrPayrollHistoryController } from "./hr-payroll-history.controller";
import { HrPayrollHistoryService } from "./hr-payroll-history.service";
import { HrService } from "./hr.service";
import { HrRecruitmentController } from "./hr-recruitment.controller";
import { HrRecruitmentService } from "./hr-recruitment.service";
import { HrCandidateProfileIdempotencyInterceptor } from "./hr-candidate-profile-idempotency.interceptor";
import { HrCandidateProfileService } from "./hr-candidate-profile.service";
import { HrRequisitionService } from "./hr-requisition.service";
import { HrCandidateInterviewService } from "./hr-candidate-interview.service";
import { PartySensitiveDataService } from "../../shared/security/party-sensitive-data.service";
import { HrLifecycleController } from "./hr-lifecycle.controller";
import { HrLifecycleService } from "./hr-lifecycle.service";
import { HrTrainingController } from "./hr-training.controller";
import { HrTrainingService } from "./hr-training.service";
import {HrRewardsController} from "./hr-rewards.controller";import {HrRewardsService} from "./hr-rewards.service";
import {HrGoalReportController} from "./hr-goal-report.controller";import {HrGoalReportService} from "./hr-goal-report.service";
import {HrPerformanceReviewController} from "./hr-performance-review.controller";import {HrPerformanceReviewService} from "./hr-performance-review.service";
import {HrPerformanceEvaluationService} from "./hr-performance-evaluation.service";
import {HrFeedback360Controller} from "./hr-feedback360.controller";import {HrFeedback360Service} from "./hr-feedback360.service";
import {HrTalentController} from "./hr-talent.controller";import {HrTalentService} from "./hr-talent.service";
import {HrOnboardingController} from "./hr-onboarding.controller";import {HrOnboardingService} from "./hr-onboarding.service";
import {HrProbationController} from "./hr-probation.controller";import {HrProbationService} from "./hr-probation.service";
import {HrJobChangeController} from "./hr-job-change.controller";import {HrJobChangeService} from "./hr-job-change.service";
import {HrDepartureController} from "./hr-departure.controller";import {HrDepartureService} from "./hr-departure.service";
import {HrLegacyDictionaryController} from "./hr-legacy-dictionary.controller";import {HrLegacyDictionaryService} from "./hr-legacy-dictionary.service";
import {HrContractReminderController} from "./hr-contract-reminder.controller";import {HrContractReminderService} from "./hr-contract-reminder.service";
import {HrLegacyArchiveController} from "./hr-legacy-archive.controller";import {HrLegacyArchiveService} from "./hr-legacy-archive.service";
import {HrCustomFieldDefinitionController} from "./hr-custom-field-definition.controller";import {HrCustomFieldDefinitionService} from "./hr-custom-field-definition.service";import {HrCustomFieldDefinitionEntity,HrCustomFieldLegacyReviewEntity} from "./entities/hr-custom-field-definition.entity";
import {HrPerformanceLegacyController} from "./hr-performance-legacy.controller";import {HrPerformanceLegacyService} from "./hr-performance-legacy.service";
import {HrPerformanceLegacyRelationsController} from "./hr-performance-legacy-relations.controller";import {HrPerformanceLegacyRelationsService} from "./hr-performance-legacy-relations.service";
import { HrInsurancePolicyVersionController } from "./hr-insurance-policy-version.controller";
import { HrInsurancePolicyVersionService } from "./hr-insurance-policy-version.service";
import { HrInsurancePreviewController } from "./hr-insurance-preview.controller";
import { HrInsurancePreviewService } from "./hr-insurance-preview.service";
import { HrInsuranceOwnedPeriodController } from "./hr-insurance-owned-period.controller";
import { HrInsuranceOwnedPeriodService } from "./hr-insurance-owned-period.service";
import { HrYuzhouIncrementalImportController } from "./hr-yuzhou-incremental-import.controller";
import { HrYuzhouIncrementalImportService } from "./hr-yuzhou-incremental-import.service";
import { HrPreparedProfileBatchRepository } from "./hr-prepared-profile-batch.repository";
import { HrPreparedProfileBatchService } from "./hr-prepared-profile-batch.service";
import { HrPreparedProfileBatchController } from "./hr-prepared-profile-batch.controller";
@Module({imports:[DataScopesModule,TypeOrmModule.forFeature([...HR_ENTITIES,HrCustomFieldDefinitionEntity,HrCustomFieldLegacyReviewEntity,OrgEntity,UserEntity,UserMessageEntity]),AuditModule],controllers:[HrPositionMaintenanceController,HrPayrollPeriodLifecycleController,HrPayrollFormalRunController,HrPayrollFormalInputController,HrPayrollFormalRuleController,HrPreparedProfileBatchController,HrCustomValueController,HrYuzhouIncrementalImportController,HrInsuranceOwnedPeriodController,HrInsurancePolicyVersionController,HrInsurancePreviewController,HrController,HrCustomFieldDefinitionController,HrContractReminderController,HrLegacyDictionaryController,HrLegacyArchiveController,HrGoalReportController,HrPerformanceReviewController,HrPerformanceLegacyController,HrPerformanceLegacyRelationsController,HrFeedback360Controller,HrTalentController,HrPayrollHistoryController,HrRecruitmentController,HrOnboardingController,HrProbationController,HrJobChangeController,HrDepartureController,HrLifecycleController,HrTrainingController,HrRewardsController],providers:[HrPositionMaintenanceService,HrPayrollPeriodLifecycleService,HrPayrollFormalRunService,HrPayrollFormalInputService,HrPayrollFormalRuleService,{provide:HrPreparedProfileBatchRepository,useFactory:()=>new HrPreparedProfileBatchRepository()},HrPreparedProfileBatchService,HrCustomValueService,HrYuzhouIncrementalImportService,HrInsuranceOwnedPeriodService,HrInsurancePolicyVersionService,HrInsurancePreviewService,HrService,HrCustomFieldDefinitionService,HrContractReminderService,HrLegacyDictionaryService,HrLegacyArchiveService,HrGoalReportService,HrPerformanceReviewService,HrPerformanceLegacyService,HrPerformanceLegacyRelationsService,HrPerformanceEvaluationService,HrFeedback360Service,HrTalentService,HrNotificationService,HrPayrollHistoryService,HrRecruitmentService,HrCandidateProfileService,HrRequisitionService,HrCandidateProfileIdempotencyInterceptor,HrCandidateInterviewService,HrOnboardingService,HrProbationService,HrJobChangeService,HrDepartureService,HrLifecycleService,HrTrainingService,HrRewardsService,PartySensitiveDataService],exports:[HrYuzhouIncrementalImportService,HrService,HrCustomFieldDefinitionService,HrContractReminderService,HrLegacyDictionaryService,HrLegacyArchiveService,HrGoalReportService,HrPerformanceReviewService,HrPerformanceLegacyService,HrPerformanceLegacyRelationsService,HrPerformanceEvaluationService,HrFeedback360Service,HrTalentService,HrNotificationService,HrPayrollHistoryService,HrRecruitmentService,HrCandidateProfileService,HrRequisitionService,HrCandidateProfileIdempotencyInterceptor,HrCandidateInterviewService,HrOnboardingService,HrProbationService,HrJobChangeService,HrDepartureService,HrLifecycleService,HrTrainingService,HrRewardsService]})
export class HrModule {}
