import { BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import type { PaginatedResult,TenantParkScope } from "@jinhu/shared";
import { DataSource,ILike,IsNull,Not,type Repository } from "typeorm";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { OrgEntity } from "../orgs/entities/org.entity";
import { UserEntity } from "../users/entities/user.entity";
import type { AdjustHrPayslipDto,AssignHrCompensationDto,CreateHrApprovalDto,CreateHrCompensationPlanDto,CreateHrEmployeeDto,CreateHrFeedbackAssignmentDto,CreateHrFeedbackCycleDto,CreateHrGoalCheckinDto,CreateHrGoalCycleDto,CreateHrGoalDto,CreateHrPayrollPeriodDto,CreateHrPayrollRunDto,CreateHrPerformanceCycleDto,CreateHrPerformancePlanDto,CreateHrPositionDto,CreateHrWorkReportDto,HrApprovalActionDto,HrEmploymentTransitionDto,HrListQueryDto,ReviewHrWorkReportDto,ScoreHrPerformanceDto,SubmitHrFeedbackDto,UpdateHrEmployeeDto,UpdateHrEmployeeProfileDto } from "./dto/hr.dto";
import { HrApprovalActionEntity,HrApprovalRequestEntity,HrCompensationPlanEntity,HrEmployeeCompensationEntity,HrEmployeeEntity,HrEmployeeProfileEntity,HrEmploymentEventEntity,HrFeedbackAssignmentEntity,HrFeedbackCycleEntity,HrFeedbackResponseEntity,HrGoalCheckinEntity,HrGoalCycleEntity,HrGoalEntity,HrPayrollPeriodEntity,HrPayrollRunEntity,HrPayslipEntity,HrPerformanceCycleEntity,HrPerformanceItemEntity,HrPerformancePlanEntity,HrPositionEntity,HrWorkReportEntity,HrWorkReportGoalEntity } from "./entities/hr.entities";
import { HrNotificationService } from "./hr-notification.service";
import { hrCentsToMoney, hrMoneyToCents, normalizeHrMoney } from "./hr-money";

@Injectable()
export class HrService {
 constructor(
  @InjectRepository(HrEmployeeEntity) private readonly employees:Repository<HrEmployeeEntity>,
  @InjectRepository(HrPositionEntity) private readonly positions:Repository<HrPositionEntity>,
  @InjectRepository(HrEmploymentEventEntity) private readonly events:Repository<HrEmploymentEventEntity>,
  @InjectRepository(HrEmployeeProfileEntity) private readonly profiles:Repository<HrEmployeeProfileEntity>,
  @InjectRepository(HrGoalCycleEntity) private readonly goalCycles:Repository<HrGoalCycleEntity>,
  @InjectRepository(HrGoalEntity) private readonly goals:Repository<HrGoalEntity>,
  @InjectRepository(HrGoalCheckinEntity) private readonly goalCheckinRepo:Repository<HrGoalCheckinEntity>,
  @InjectRepository(HrWorkReportEntity) private readonly reports:Repository<HrWorkReportEntity>,
  @InjectRepository(HrPerformanceCycleEntity) private readonly performanceCycles:Repository<HrPerformanceCycleEntity>,
  @InjectRepository(HrPerformancePlanEntity) private readonly performancePlans:Repository<HrPerformancePlanEntity>,
  @InjectRepository(HrFeedbackCycleEntity) private readonly feedbackCycles:Repository<HrFeedbackCycleEntity>,
  @InjectRepository(HrFeedbackAssignmentEntity) private readonly feedbackAssignments:Repository<HrFeedbackAssignmentEntity>,
  @InjectRepository(HrFeedbackResponseEntity) private readonly feedbackResponses:Repository<HrFeedbackResponseEntity>,
  @InjectRepository(HrCompensationPlanEntity) private readonly compensationPlans:Repository<HrCompensationPlanEntity>,
  @InjectRepository(HrEmployeeCompensationEntity) private readonly employeeCompensations:Repository<HrEmployeeCompensationEntity>,
  @InjectRepository(HrPayrollPeriodEntity) private readonly payrollPeriods:Repository<HrPayrollPeriodEntity>,
  @InjectRepository(HrPayrollRunEntity) private readonly payrollRuns:Repository<HrPayrollRunEntity>,
  @InjectRepository(HrPayslipEntity) private readonly payslips:Repository<HrPayslipEntity>,
  @InjectRepository(HrApprovalRequestEntity) private readonly approvalRequests:Repository<HrApprovalRequestEntity>,
  @InjectRepository(OrgEntity) private readonly orgs:Repository<OrgEntity>,
  @InjectRepository(UserEntity) private readonly users:Repository<UserEntity>,
  private readonly notifications:HrNotificationService,
  private readonly dataSource:DataSource
 ){}

 async listEmployees(scope:TenantParkScope,q:HrListQueryDto):Promise<PaginatedResult<HrEmployeeEntity>>{
  const where={tenantId:scope.tenantId,parkId:scope.parkId,isDeleted:false,...(q.status?{employmentStatus:q.status}:{}),...(q.org_id?{primaryOrgId:q.org_id}:{}),...(q.keyword?{fullName:ILike(`%${q.keyword}%`)}:{})};
  const [items,total]=await this.employees.findAndCount({where,order:{employeeCode:"ASC"},skip:(q.page-1)*q.page_size,take:q.page_size});
  return {items,total,page:q.page,page_size:q.page_size};
 }
 async detailEmployee(scope:TenantParkScope,id:string){const row=await this.employees.findOne({where:{id,...scope,isDeleted:false}});if(!row)throw new NotFoundException("Employee not found");return row;}
 async myEmployee(scope:TenantParkScope,actor:JwtPrincipal){const row=await this.employees.findOne({where:{...scope,userId:actor.sub,isDeleted:false}});if(!row)throw new NotFoundException("No employee profile is linked to current user");return row;}
 async employeeEvents(scope:TenantParkScope,id:string){await this.detailEmployee(scope,id);return this.events.find({where:{...scope,employeeId:id,isDeleted:false},order:{effectiveDate:"DESC",createTime:"DESC"}});}
 async employeeProfile(scope:TenantParkScope,id:string){await this.detailEmployee(scope,id);return this.profiles.findOne({where:{...scope,employeeId:id,isDeleted:false}});}

 async updateEmployeeProfile(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:UpdateHrEmployeeProfileDto){
  await this.detailEmployee(scope,id);
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeProfileEntity);
   let row=await repo.findOne({where:{...scope,employeeId:id,isDeleted:false},lock:{mode:"pessimistic_write"}});
   if(!row)row=repo.create({...scope,employeeId:id,createBy:actor.sub});
   Object.assign(row,{...dto,idType:dto.idType??null,idNumberMasked:dto.idNumberMasked??null,personalMobile:dto.personalMobile??null,personalEmail:dto.personalEmail??null,address:dto.address??null,emergencyContactName:dto.emergencyContactName??null,emergencyContactMobile:dto.emergencyContactMobile??null,remark:dto.remark??null,updateBy:actor.sub});
   return repo.save(row);
  });
 }

 async transitionEmployment(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HrEmploymentTransitionDto){
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeEntity),eventRepo=manager.getRepository(HrEmploymentEventEntity);
   const row=await repo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
   if(!row)throw new NotFoundException("Employee not found");
   const targetByAction:Record<string,string>={start_probation:"probation",confirm_employment:"active",suspend:"suspended",resume:"active",depart:"departed"};
   const allowed:Record<string,string[]>={preboarding:["start_probation","confirm_employment","depart"],probation:["confirm_employment","depart"],active:["transfer","suspend","depart"],suspended:["resume","depart"],departed:[]};
   if(!allowed[row.employmentStatus]?.includes(dto.action))throw new BadRequestException(`Action ${dto.action} is not allowed from ${row.employmentStatus}`);
   if(dto.action==="transfer"){
    if(!dto.primaryOrgId)throw new BadRequestException("Transfer requires primary organization");
    await this.validateEmployeeReferences(scope,{employeeCode:row.employeeCode,fullName:row.fullName,primaryOrgId:dto.primaryOrgId,positionId:dto.positionId,managerEmployeeId:dto.managerEmployeeId},id);
   }
   const before=this.eventSnapshot(row);
   if(dto.action==="transfer")Object.assign(row,{primaryOrgId:dto.primaryOrgId,positionId:dto.positionId??null,managerEmployeeId:dto.managerEmployeeId??null});
   else row.employmentStatus=targetByAction[dto.action]!;
   if(dto.action==="confirm_employment")row.probationEndDate=dto.effectiveDate;
   if(dto.action==="depart")row.departureDate=dto.effectiveDate;
   if(dto.action==="resume")row.departureDate=null;
   row.updateBy=actor.sub;
   const saved=await repo.save(row);
   await eventRepo.save(eventRepo.create({...scope,employeeId:id,eventType:dto.action,effectiveDate:dto.effectiveDate,beforeSnapshot:before,afterSnapshot:this.eventSnapshot(saved),reason:dto.reason,status:"effective",createBy:actor.sub,updateBy:actor.sub}));
   return saved;
  });
 }

 async createEmployee(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrEmployeeDto){
  await this.validateEmployeeReferences(scope,dto);
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeEntity),eventRepo=manager.getRepository(HrEmploymentEventEntity);
   if(await repo.exists({where:{...scope,employeeCode:dto.employeeCode,isDeleted:false}}))throw new ConflictException("Employee code already exists");
   if(dto.userId&&await repo.exists({where:{...scope,userId:dto.userId,isDeleted:false}}))throw new ConflictException("User is already linked to another employee");
   const row=await repo.save(repo.create({...scope,...dto,userId:dto.userId??null,primaryOrgId:dto.primaryOrgId??null,positionId:dto.positionId??null,managerEmployeeId:dto.managerEmployeeId??null,employmentType:dto.employmentType??"full_time",employmentStatus:"preboarding",hireDate:dto.hireDate??null,probationEndDate:null,departureDate:null,workLocation:dto.workLocation??null,workMobile:dto.workMobile??null,workEmail:dto.workEmail??null,remark:dto.remark??null,createBy:actor.sub,updateBy:actor.sub}));
   await eventRepo.save(eventRepo.create({...scope,employeeId:row.id,eventType:"created",effectiveDate:dto.hireDate??new Date().toISOString().slice(0,10),beforeSnapshot:{},afterSnapshot:this.eventSnapshot(row),reason:"创建员工档案",createBy:actor.sub,updateBy:actor.sub}));
   return row;
  });
 }
 async updateEmployee(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:UpdateHrEmployeeDto){
  await this.validateEmployeeReferences(scope,dto,id);
  if(dto.userId&&await this.employees.exists({where:{...scope,userId:dto.userId,isDeleted:false,id:Not(id)}}))throw new ConflictException("User is already linked to another employee");
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeEntity),eventRepo=manager.getRepository(HrEmploymentEventEntity);
   const row=await repo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!row)throw new NotFoundException("Employee not found");
   if(dto.employmentStatus!==row.employmentStatus)throw new BadRequestException("Employment status must be changed through a lifecycle action");
   if(await repo.exists({where:{...scope,employeeCode:dto.employeeCode,isDeleted:false,id:Not(id)}}))throw new ConflictException("Employee code already exists");
   const before=this.eventSnapshot(row);Object.assign(row,{...dto,userId:dto.userId??null,primaryOrgId:dto.primaryOrgId??null,positionId:dto.positionId??null,managerEmployeeId:dto.managerEmployeeId??null,hireDate:dto.hireDate??null,probationEndDate:dto.probationEndDate??null,departureDate:dto.departureDate??null,workLocation:dto.workLocation??null,workMobile:dto.workMobile??null,workEmail:dto.workEmail??null,remark:dto.remark??null,updateBy:actor.sub});
   const saved=await repo.save(row);await eventRepo.save(eventRepo.create({...scope,employeeId:id,eventType:"profile_updated",effectiveDate:new Date().toISOString().slice(0,10),beforeSnapshot:before,afterSnapshot:this.eventSnapshot(saved),reason:"更新员工档案",createBy:actor.sub,updateBy:actor.sub}));return saved;
  });
 }
 async listPositions(scope:TenantParkScope){return this.positions.find({where:{...scope,isDeleted:false},order:{positionCode:"ASC"}});}
 async createPosition(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPositionDto){await this.mustOrg(scope,dto.orgId);if(await this.positions.exists({where:{...scope,positionCode:dto.positionCode,isDeleted:false}}))throw new ConflictException("Position code already exists");return this.positions.save(this.positions.create({...scope,...dto,jobFamily:dto.jobFamily??null,jobLevel:dto.jobLevel??null,headcountLimit:dto.headcountLimit??null,status:dto.status??"enabled",remark:dto.remark??null,createBy:actor.sub,updateBy:actor.sub}));}

 async listGoalCycles(scope:TenantParkScope){return this.goalCycles.find({where:{...scope,isDeleted:false},order:{startDate:"DESC"}});}
 async createGoalCycle(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrGoalCycleDto){if(dto.endDate<dto.startDate)throw new BadRequestException("Goal cycle end date must not precede start date");if(await this.goalCycles.exists({where:{...scope,cycleCode:dto.cycleCode,isDeleted:false}}))throw new ConflictException("Goal cycle code already exists");return this.goalCycles.save(this.goalCycles.create({...scope,...dto,status:"draft",createBy:actor.sub,updateBy:actor.sub}));}
 async listGoals(scope:TenantParkScope,actor:JwtPrincipal,selfOnly=false){const employee=selfOnly?await this.myEmployee(scope,actor):null;return this.goals.find({where:{...scope,isDeleted:false,...(employee?{ownerEmployeeId:employee.id}:{})},order:{createTime:"ASC"}});}
 async createGoal(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrGoalDto){
  const cycle=await this.goalCycles.findOne({where:{id:dto.cycleId,...scope,isDeleted:false}});if(!cycle)throw new BadRequestException("Goal cycle is unavailable in current scope");
  if(dto.startDate<cycle.startDate||dto.dueDate>cycle.endDate||dto.dueDate<dto.startDate)throw new BadRequestException("Goal dates must stay inside the cycle");
  let parent:HrGoalEntity|null=null;if(dto.parentGoalId){parent=await this.goals.findOne({where:{id:dto.parentGoalId,...scope,isDeleted:false}});if(!parent||parent.cycleId!==dto.cycleId)throw new BadRequestException("Parent goal is unavailable in this cycle");}
  const order={group:0,department:1,employee:2};if(parent&&order[dto.goalLevel as keyof typeof order]!==order[parent.goalLevel as keyof typeof order]+1)throw new BadRequestException("Goals must cascade from group to department to employee");
  if(parent){const weightRow=await this.goals.createQueryBuilder("g").where("g.tenant_id=:tenantId AND g.park_id=:parkId AND g.parent_goal_id=:parentId AND g.is_deleted=false",{...scope,parentId:parent.id}).select("COALESCE(SUM(g.weight),0)","total").getRawOne<{total:string}>();if(Number(weightRow?.total??0)+dto.weight>1.0000001)throw new BadRequestException("Child goal weights cannot exceed 100 percent");}
  if(dto.goalLevel==="group"&&(dto.ownerOrgId||dto.ownerEmployeeId))throw new BadRequestException("Group goal must not have an organization or employee owner");
  if(dto.goalLevel==="department"){if(!dto.ownerOrgId||dto.ownerEmployeeId)throw new BadRequestException("Department goal requires an organization owner");await this.mustOrg(scope,dto.ownerOrgId);}
  if(dto.goalLevel==="employee"){if(!dto.ownerEmployeeId||dto.ownerOrgId)throw new BadRequestException("Employee goal requires an employee owner");await this.detailEmployee(scope,dto.ownerEmployeeId);}
  return this.goals.save(this.goals.create({...scope,...dto,parentGoalId:dto.parentGoalId??null,ownerOrgId:dto.ownerOrgId??null,ownerEmployeeId:dto.ownerEmployeeId??null,weight:String(dto.weight),metricName:dto.metricName??null,targetValue:dto.targetValue===undefined?null:String(dto.targetValue),currentValue:null,unit:dto.unit??null,progress:"0",status:"draft",createBy:actor.sub,updateBy:actor.sub}));
 }
 async goalCheckins(scope:TenantParkScope,actor:JwtPrincipal,id:string){const employee=await this.myEmployee(scope,actor);if(!await this.goals.exists({where:{id,...scope,ownerEmployeeId:employee.id,isDeleted:false}}))throw new NotFoundException("Goal not found");return this.goalCheckinRepo.find({where:{...scope,goalId:id,isDeleted:false},order:{createTime:"DESC"}});}
 async createGoalCheckin(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:CreateHrGoalCheckinDto){return this.dataSource.transaction(async manager=>{const goalRepo=manager.getRepository(HrGoalEntity),checkinRepo=manager.getRepository(HrGoalCheckinEntity);const goal=await goalRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!goal)throw new NotFoundException("Goal not found");if(goal.status==="completed"||goal.status==="cancelled")throw new BadRequestException("Closed goal cannot accept progress check-ins");if(goal.ownerEmployeeId){const employee=await manager.getRepository(HrEmployeeEntity).findOne({where:{id:goal.ownerEmployeeId,...scope,userId:actor.sub,isDeleted:false}});if(!employee)throw new BadRequestException("Employee goals can only be updated by their owner");}goal.progress=String(dto.progress);goal.currentValue=dto.currentValue===undefined?goal.currentValue:String(dto.currentValue);goal.status=dto.progress===1?"completed":"active";goal.updateBy=actor.sub;await goalRepo.save(goal);return checkinRepo.save(checkinRepo.create({...scope,goalId:id,progress:String(dto.progress),currentValue:dto.currentValue===undefined?null:String(dto.currentValue),summary:dto.summary,risks:dto.risks??null,evidenceFileId:dto.evidenceFileId??null,createBy:actor.sub,updateBy:actor.sub}));});}
 async myWorkReports(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);return this.reports.find({where:{...scope,employeeId:employee.id,isDeleted:false},order:{periodStart:"DESC"}});}
 async createMyWorkReport(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrWorkReportDto){
  const employee=await this.myEmployee(scope,actor);if(dto.periodEnd<dto.periodStart)throw new BadRequestException("Report end date must not precede start date");
  if(await this.reports.exists({where:{...scope,employeeId:employee.id,reportType:dto.reportType,periodStart:dto.periodStart,isDeleted:false}}))throw new ConflictException("A report already exists for this period");
  return this.dataSource.transaction(async manager=>{const repo=manager.getRepository(HrWorkReportEntity),linkRepo=manager.getRepository(HrWorkReportGoalEntity);const report=await repo.save(repo.create({...scope,employeeId:employee.id,reportType:dto.reportType,periodStart:dto.periodStart,periodEnd:dto.periodEnd,completedWork:dto.completedWork,nextPlan:dto.nextPlan??null,risks:dto.risks??null,collaborationNeeds:dto.collaborationNeeds??null,hours:dto.hours===undefined?null:String(dto.hours),status:"submitted",reviewerEmployeeId:employee.managerEmployeeId,reviewComment:null,submittedAt:new Date(),reviewedAt:null,createBy:actor.sub,updateBy:actor.sub}));for(const goalId of dto.goalIds??[]){const goal=await manager.getRepository(HrGoalEntity).findOne({where:{id:goalId,...scope,ownerEmployeeId:employee.id,isDeleted:false}});if(!goal)throw new BadRequestException("Work report can only link the employee's own goals");await linkRepo.save(linkRepo.create({...scope,reportId:report.id,goalId,progressDelta:null,createBy:actor.sub,updateBy:actor.sub}));}await this.notifications.publishWorkReportSubmitted(scope,actor,report,manager);return report;});
 }
 async teamWorkReports(scope:TenantParkScope,actor:JwtPrincipal){const ids=await this.managedEmployeeIds(scope,actor);if(!ids.length)return [];return this.reports.createQueryBuilder("r").where("r.tenant_id=:tenantId AND r.park_id=:parkId AND r.is_deleted=false",scope).andWhere("r.employee_id IN (:...ids)",{ids}).orderBy("r.period_start","DESC").getMany();}
 async reviewWorkReport(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ReviewHrWorkReportDto){const managerEmployee=await this.myEmployee(scope,actor);const report=await this.reports.findOne({where:{id,...scope,isDeleted:false}});if(!report)throw new NotFoundException("Work report not found");const managedIds=await this.managedEmployeeIds(scope,actor);if(!managedIds.includes(report.employeeId))throw new ForbiddenException("Work report is outside the manager organization scope");if(report.status!=="submitted")throw new BadRequestException("Only submitted reports can be reviewed");return this.dataSource.transaction(async manager=>{const repo=manager.getRepository(HrWorkReportEntity);report.status=dto.action;report.reviewComment=dto.comment;report.reviewerEmployeeId=managerEmployee.id;report.reviewedAt=new Date();report.updateBy=actor.sub;const saved=await repo.save(report);await this.notifications.publishWorkReportReviewed(scope,actor,saved,manager);return saved;});}

 async listPerformanceCycles(scope:TenantParkScope){return this.performanceCycles.find({where:{...scope,isDeleted:false},order:{startDate:"DESC"}});}
 async createPerformanceCycle(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPerformanceCycleDto){if(dto.endDate<dto.startDate)throw new BadRequestException("Performance cycle end date must not precede start date");if(await this.performanceCycles.exists({where:{...scope,cycleCode:dto.cycleCode,isDeleted:false}}))throw new ConflictException("Performance cycle code already exists");return this.performanceCycles.save(this.performanceCycles.create({...scope,...dto,selfReviewEnd:dto.selfReviewEnd??null,managerReviewEnd:dto.managerReviewEnd??null,calibrationEnd:dto.calibrationEnd??null,status:"active",createBy:actor.sub,updateBy:actor.sub}));}
 async createPerformancePlan(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPerformancePlanDto){const cycle=await this.performanceCycles.findOne({where:{id:dto.cycleId,...scope,isDeleted:false}});if(!cycle||cycle.status!=="active")throw new BadRequestException("Performance cycle is unavailable");const employee=await this.detailEmployee(scope,dto.employeeId);return this.dataSource.transaction(async manager=>{const planRepo=manager.getRepository(HrPerformancePlanEntity),itemRepo=manager.getRepository(HrPerformanceItemEntity);if(await planRepo.exists({where:{...scope,cycleId:dto.cycleId,employeeId:dto.employeeId,isDeleted:false}}))throw new ConflictException("Employee already has a plan in this cycle");const goals=await manager.getRepository(HrGoalEntity).createQueryBuilder("g").where("g.tenant_id=:tenantId AND g.park_id=:parkId AND g.owner_employee_id=:employeeId AND g.is_deleted=false",{...scope,employeeId:dto.employeeId}).andWhere("g.status IN ('active','completed') AND g.start_date<=:endDate AND g.due_date>=:startDate",{startDate:cycle.startDate,endDate:cycle.endDate}).orderBy("g.create_time","ASC").getMany();if(!goals.length)throw new BadRequestException("Employee has no active goals in this performance cycle");const totalWeight=goals.reduce((sum,goal)=>sum+Number(goal.weight),0);if(totalWeight>1.0000001)throw new BadRequestException("Performance goal weights cannot exceed 100 percent");const plan=await planRepo.save(planRepo.create({...scope,cycleId:dto.cycleId,employeeId:dto.employeeId,managerEmployeeId:employee.managerEmployeeId,status:"self_review",selfScore:null,managerScore:null,calibratedScore:null,finalScore:null,selfSummary:null,managerComment:null,calibrationComment:null,confirmedAt:null,createBy:actor.sub,updateBy:actor.sub}));for(const goal of goals)await itemRepo.save(itemRepo.create({...scope,planId:plan.id,goalId:goal.id,itemName:goal.goalName,weight:goal.weight,targetSnapshot:{metricName:goal.metricName,targetValue:goal.targetValue,unit:goal.unit,dueDate:goal.dueDate},selfScore:null,managerScore:null,finalScore:null,comment:null,createBy:actor.sub,updateBy:actor.sub}));return plan;});}
 async myPerformancePlans(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);return this.performancePlans.find({where:{...scope,employeeId:employee.id,isDeleted:false},order:{createTime:"DESC"}});}
 async selfReviewPerformance(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ScoreHrPerformanceDto){const employee=await this.myEmployee(scope,actor);const plan=await this.performancePlans.findOne({where:{id,...scope,employeeId:employee.id,isDeleted:false}});if(!plan)throw new NotFoundException("Performance plan not found");if(plan.status!=="self_review")throw new BadRequestException("Plan is not in self review");plan.selfScore=String(dto.score);plan.selfSummary=dto.comment;plan.status="manager_review";plan.updateBy=actor.sub;return this.performancePlans.save(plan);}
 async managerPerformancePlans(scope:TenantParkScope,actor:JwtPrincipal){const ids=await this.managedEmployeeIds(scope,actor);if(!ids.length)return [];return this.performancePlans.createQueryBuilder("p").where("p.tenant_id=:tenantId AND p.park_id=:parkId AND p.is_deleted=false",scope).andWhere("p.employee_id IN (:...ids)",{ids}).orderBy("p.create_time","DESC").getMany();}
 async managerReviewPerformance(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ScoreHrPerformanceDto){const plan=await this.performancePlans.findOne({where:{id,...scope,isDeleted:false}});if(!plan)throw new NotFoundException("Performance plan not found");const managedIds=await this.managedEmployeeIds(scope,actor);if(!managedIds.includes(plan.employeeId))throw new ForbiddenException("Performance plan is outside the manager organization scope");if(plan.status!=="manager_review")throw new BadRequestException("Plan is not in manager review");plan.managerScore=String(dto.score);plan.managerComment=dto.comment;plan.status="calibrating";plan.updateBy=actor.sub;return this.performancePlans.save(plan);}
 async calibratePerformance(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ScoreHrPerformanceDto){const plan=await this.performancePlans.findOne({where:{id,...scope,isDeleted:false}});if(!plan)throw new NotFoundException("Performance plan not found");if(plan.status!=="calibrating")throw new BadRequestException("Plan is not ready for calibration");plan.calibratedScore=String(dto.score);plan.finalScore=String(dto.score);plan.calibrationComment=dto.comment;plan.status="confirmed";plan.confirmedAt=new Date();plan.updateBy=actor.sub;return this.performancePlans.save(plan);}
 async createFeedbackCycle(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrFeedbackCycleDto){if(!await this.performanceCycles.exists({where:{id:dto.performanceCycleId,...scope,isDeleted:false}}))throw new BadRequestException("Performance cycle is unavailable");return this.feedbackCycles.save(this.feedbackCycles.create({...scope,...dto,anonymous:dto.anonymous??true,minimumAnonymousResponses:dto.minimumAnonymousResponses??3,status:"active",createBy:actor.sub,updateBy:actor.sub}));}
 async listFeedbackCycles(scope:TenantParkScope){return this.feedbackCycles.find({where:{...scope,isDeleted:false},order:{createTime:"DESC"}});}
 async createFeedbackAssignment(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrFeedbackAssignmentDto){await Promise.all([this.detailEmployee(scope,dto.subjectEmployeeId),this.detailEmployee(scope,dto.reviewerEmployeeId)]);if(dto.relationType==="self"&&dto.subjectEmployeeId!==dto.reviewerEmployeeId)throw new BadRequestException("Self feedback must be assigned to the subject");if(dto.relationType!=="self"&&dto.subjectEmployeeId===dto.reviewerEmployeeId)throw new BadRequestException("Non-self feedback requires another reviewer");if(!await this.feedbackCycles.exists({where:{id:dto.feedbackCycleId,...scope,status:"active",isDeleted:false}}))throw new BadRequestException("Feedback cycle is unavailable");if(await this.feedbackAssignments.exists({where:{...scope,feedbackCycleId:dto.feedbackCycleId,subjectEmployeeId:dto.subjectEmployeeId,reviewerEmployeeId:dto.reviewerEmployeeId,isDeleted:false}}))throw new ConflictException("Feedback assignment already exists");return this.feedbackAssignments.save(this.feedbackAssignments.create({...scope,...dto,weight:String(dto.weight),status:"pending",submittedAt:null,createBy:actor.sub,updateBy:actor.sub}));}
 async myFeedbackAssignments(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);return this.feedbackAssignments.find({where:{...scope,reviewerEmployeeId:employee.id,isDeleted:false},order:{createTime:"DESC"}});}
 async submitFeedback(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:SubmitHrFeedbackDto){const employee=await this.myEmployee(scope,actor);return this.dataSource.transaction(async manager=>{const assignmentRepo=manager.getRepository(HrFeedbackAssignmentEntity),responseRepo=manager.getRepository(HrFeedbackResponseEntity);const assignment=await assignmentRepo.findOne({where:{id,...scope,reviewerEmployeeId:employee.id,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!assignment)throw new NotFoundException("Feedback assignment not found");if(assignment.status!=="pending")throw new ConflictException("Feedback has already been submitted");const response=await responseRepo.save(responseRepo.create({...scope,assignmentId:id,score:String(dto.score),strengths:dto.strengths??null,improvements:dto.improvements??null,submittedAt:new Date(),createBy:actor.sub,updateBy:actor.sub}));assignment.status="submitted";assignment.submittedAt=new Date();assignment.updateBy=actor.sub;await assignmentRepo.save(assignment);return response;});}
 async feedbackResult(scope:TenantParkScope,subjectEmployeeId:string,feedbackCycleId:string){const cycle=await this.feedbackCycles.findOne({where:{id:feedbackCycleId,...scope,isDeleted:false}});if(!cycle)throw new NotFoundException("Feedback cycle not found");const rows=await this.feedbackResponses.createQueryBuilder("r").innerJoin(HrFeedbackAssignmentEntity,"a","a.id=r.assignment_id AND a.tenant_id=r.tenant_id AND a.park_id=r.park_id AND a.is_deleted=false").where("r.tenant_id=:tenantId AND r.park_id=:parkId AND r.is_deleted=false",scope).andWhere("a.subject_employee_id=:subjectEmployeeId",{subjectEmployeeId}).andWhere("a.feedback_cycle_id=:feedbackCycleId",{feedbackCycleId}).select("COUNT(*)","count").addSelect("AVG(r.score)","average").getRawOne<{count:string;average:string|null}>();const count=Number(rows?.count??0);if(cycle.anonymous&&count<cycle.minimumAnonymousResponses)throw new ForbiddenException("Anonymous result threshold has not been reached");return {subjectEmployeeId,feedbackCycleId,responseCount:count,averageScore:rows?.average===null?null:Number(rows?.average)};}
 async listCompensationPlans(scope:TenantParkScope){return this.compensationPlans.find({where:{...scope,isDeleted:false},order:{effectiveFrom:"DESC"}});}
 async createCompensationPlan(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrCompensationPlanDto){if(dto.effectiveTo&&dto.effectiveTo<dto.effectiveFrom)throw new BadRequestException("Compensation plan dates are invalid");if(await this.compensationPlans.exists({where:{...scope,planCode:dto.planCode,isDeleted:false}}))throw new ConflictException("Compensation plan code already exists");return this.compensationPlans.save(this.compensationPlans.create({...scope,...dto,effectiveTo:dto.effectiveTo??null,status:"active",currency:"CNY",createBy:actor.sub,updateBy:actor.sub}));}
 async assignCompensation(scope:TenantParkScope,actor:JwtPrincipal,dto:AssignHrCompensationDto){await this.detailEmployee(scope,dto.employeeId);if(!await this.compensationPlans.exists({where:{id:dto.planId,...scope,status:"active",isDeleted:false}}))throw new BadRequestException("Compensation plan is unavailable");if(dto.effectiveTo&&dto.effectiveTo<dto.effectiveFrom)throw new BadRequestException("Compensation dates are invalid");return this.employeeCompensations.save(this.employeeCompensations.create({...scope,...dto,effectiveTo:dto.effectiveTo??null,baseSalary:normalizeHrMoney(dto.baseSalary,"baseSalary"),allowanceAmount:normalizeHrMoney(dto.allowanceAmount??"0","allowanceAmount"),variableTarget:normalizeHrMoney(dto.variableTarget??"0","variableTarget"),status:"active",approvedBy:actor.sub,createBy:actor.sub,updateBy:actor.sub}));}
 async listPayrollPeriods(scope:TenantParkScope){return this.payrollPeriods.find({where:{...scope,isDeleted:false},order:{periodMonth:"DESC"}});}
 async createPayrollPeriod(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPayrollPeriodDto){const month=`${dto.periodMonth.slice(0,7)}-01`;if(dto.periodMonth!==month)throw new BadRequestException("Payroll period month must be the first day of month");if(dto.endDate<dto.startDate)throw new BadRequestException("Payroll period dates are invalid");if(await this.payrollPeriods.exists({where:{...scope,periodMonth:month,isDeleted:false}}))throw new ConflictException("Payroll period already exists");return this.payrollPeriods.save(this.payrollPeriods.create({...scope,...dto,periodMonth:month,status:"open",createBy:actor.sub,updateBy:actor.sub}));}
 async listPayrollRuns(scope:TenantParkScope){return this.payrollRuns.find({where:{...scope,isDeleted:false},order:{createTime:"DESC"}});}
 async payrollRunPayslips(scope:TenantParkScope,runId:string){if(!await this.payrollRuns.exists({where:{id:runId,...scope,isDeleted:false}}))throw new NotFoundException("Payroll run not found");return this.payslips.find({where:{...scope,runId,isDeleted:false},order:{createTime:"ASC"}});}
 async createPayrollRun(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPayrollRunDto){return this.dataSource.transaction(async manager=>{const periodRepo=manager.getRepository(HrPayrollPeriodEntity),runRepo=manager.getRepository(HrPayrollRunEntity),slipRepo=manager.getRepository(HrPayslipEntity);const period=await periodRepo.findOne({where:{id:dto.periodId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!period||period.status!=="open")throw new BadRequestException("Payroll period is unavailable");if(dto.correctionOfRunId){const original=await runRepo.findOne({where:{id:dto.correctionOfRunId,...scope,periodId:dto.periodId,status:"confirmed",isDeleted:false}});if(!original)throw new BadRequestException("Correction must reference a confirmed run");}else if(await runRepo.exists({where:{...scope,periodId:dto.periodId,correctionOfRunId:IsNull(),isDeleted:false}}))throw new ConflictException("Base payroll run already exists");const latest=await runRepo.findOne({where:{...scope,periodId:dto.periodId,isDeleted:false},order:{runNo:"DESC"}});const run=await runRepo.save(runRepo.create({...scope,periodId:dto.periodId,runNo:(latest?.runNo??0)+1,correctionOfRunId:dto.correctionOfRunId??null,status:"draft",employeeCount:0,grossTotal:"0",deductionTotal:"0",netTotal:"0",calculatedAt:null,reviewedAt:null,confirmedAt:null,confirmedBy:null,createBy:actor.sub,updateBy:actor.sub}));const employees=await manager.getRepository(HrEmployeeEntity).find({where:{...scope,employmentStatus:"active",isDeleted:false}});let gross=0n;for(const employee of employees){const comp=await manager.getRepository(HrEmployeeCompensationEntity).createQueryBuilder("c").where("c.tenant_id=:tenantId AND c.park_id=:parkId AND c.employee_id=:employeeId AND c.is_deleted=false AND c.status='active'",{...scope,employeeId:employee.id}).andWhere("c.effective_from<=:endDate AND (c.effective_to IS NULL OR c.effective_to>=:startDate)",{endDate:period.endDate,startDate:period.startDate}).orderBy("c.effective_from","DESC").getOne();if(!comp)continue;const amount=hrMoneyToCents(comp.baseSalary)+hrMoneyToCents(comp.allowanceAmount)+hrMoneyToCents(comp.variableTarget);gross+=amount;await slipRepo.save(slipRepo.create({...scope,runId:run.id,employeeId:employee.id,compensationSnapshot:{planId:comp.planId,effectiveFrom:comp.effectiveFrom,baseSalary:comp.baseSalary,allowanceAmount:comp.allowanceAmount,variableTarget:comp.variableTarget},grossAmount:hrCentsToMoney(amount),deductionAmount:"0.00",personalTax:"0.00",netAmount:hrCentsToMoney(amount),status:"draft",createBy:actor.sub,updateBy:actor.sub}));}run.employeeCount=await slipRepo.count({where:{...scope,runId:run.id,isDeleted:false}});run.grossTotal=hrCentsToMoney(gross);run.netTotal=hrCentsToMoney(gross);run.status="calculated";run.calculatedAt=new Date();return runRepo.save(run);});}
 async transitionPayrollRun(scope:TenantParkScope,actor:JwtPrincipal,id:string,action:"review"|"confirm"){const run=await this.payrollRuns.findOne({where:{id,...scope,isDeleted:false}});if(!run)throw new NotFoundException("Payroll run not found");if(action==="review"&&run.status!=="calculated")throw new BadRequestException("Only calculated payroll can enter review");if(action==="confirm"&&run.status!=="reviewing")throw new BadRequestException("Only reviewed payroll can be confirmed");run.status=action==="review"?"reviewing":"confirmed";if(action==="review")run.reviewedAt=new Date();else{run.confirmedAt=new Date();run.confirmedBy=actor.sub;await this.payslips.update({runId:id,...scope,isDeleted:false},{status:"confirmed",updateBy:actor.sub});}run.updateBy=actor.sub;return this.payrollRuns.save(run);}
 async adjustPayslip(scope:TenantParkScope,actor:JwtPrincipal,runId:string,payslipId:string,dto:AdjustHrPayslipDto){return this.dataSource.transaction(async manager=>{const runRepo=manager.getRepository(HrPayrollRunEntity),slipRepo=manager.getRepository(HrPayslipEntity);const run=await runRepo.findOne({where:{id:runId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!run)throw new NotFoundException("Payroll run not found");if(!["calculated","reviewing"].includes(run.status))throw new BadRequestException("Confirmed payroll cannot be adjusted; create a correction run");const slip=await slipRepo.findOne({where:{id:payslipId,runId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!slip)throw new NotFoundException("Payslip not found");const deduction=hrMoneyToCents(dto.deductionAmount,"deductionAmount");const tax=hrMoneyToCents(dto.personalTax,"personalTax");const net=hrMoneyToCents(slip.grossAmount)-deduction-tax;if(net<0n)throw new BadRequestException("Deductions and tax cannot exceed gross amount");slip.deductionAmount=hrCentsToMoney(deduction);slip.personalTax=hrCentsToMoney(tax);slip.netAmount=hrCentsToMoney(net);slip.remark=dto.reason;slip.updateBy=actor.sub;await slipRepo.save(slip);const totals=await slipRepo.createQueryBuilder("s").where("s.tenant_id=:tenantId AND s.park_id=:parkId AND s.run_id=:runId AND s.is_deleted=false",{...scope,runId}).select("COALESCE(SUM(s.gross_amount),0)","gross").addSelect("COALESCE(SUM(s.deduction_amount+s.personal_tax),0)","deduction").addSelect("COALESCE(SUM(s.net_amount),0)","net").getRawOne<{gross:string;deduction:string;net:string}>();run.grossTotal=normalizeHrMoney(totals?.gross??"0","grossTotal");run.deductionTotal=normalizeHrMoney(totals?.deduction??"0","deductionTotal");run.netTotal=normalizeHrMoney(totals?.net??"0","netTotal");run.updateBy=actor.sub;await runRepo.save(run);return slip;});}
 async myPayslips(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);return this.payslips.find({where:{...scope,employeeId:employee.id,status:"confirmed",isDeleted:false},order:{createTime:"DESC"}});}
 async myApprovals(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);return this.approvalRequests.find({where:{...scope,applicantEmployeeId:employee.id,isDeleted:false},order:{createTime:"DESC"}});}
 async pendingApprovals(scope:TenantParkScope){return this.approvalRequests.find({where:{...scope,status:"submitted",isDeleted:false},order:{submittedAt:"ASC"}});}
 async createApproval(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrApprovalDto){const employee=await this.myEmployee(scope,actor);return this.approvalRequests.save(this.approvalRequests.create({...scope,requestNo:`HR-${Date.now()}-${crypto.randomUUID().slice(0,8)}`,requestType:dto.requestType,applicantEmployeeId:employee.id,subjectEmployeeId:employee.id,title:dto.title,payload:dto.payload,status:"draft",currentApproverId:null,submittedAt:null,completedAt:null,createBy:actor.sub,updateBy:actor.sub}));}
 async actApproval(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HrApprovalActionDto,reviewer:boolean){return this.dataSource.transaction(async manager=>{const requestRepo=manager.getRepository(HrApprovalRequestEntity),actionRepo=manager.getRepository(HrApprovalActionEntity);const request=await requestRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!request)throw new NotFoundException("HR approval request not found");const employee=reviewer?null:await manager.getRepository(HrEmployeeEntity).findOne({where:{id:request.applicantEmployeeId,...scope,userId:actor.sub,isDeleted:false}});if(!reviewer&&!employee)throw new ForbiddenException("Only the applicant can change this request");const allowed=reviewer?{approve:["submitted"],return:["submitted"]}:{submit:["draft"],resubmit:["returned"],withdraw:["submitted"]};const expected=allowed[dto.action as keyof typeof allowed];if(!expected||!expected.includes(request.status))throw new BadRequestException("Approval action is not allowed from current status");const before=request.status;const next={submit:"submitted",resubmit:"submitted",withdraw:"withdrawn",approve:"approved",return:"returned"}[dto.action]!;request.status=next;if(next==="submitted")request.submittedAt=new Date();if(["approved","withdrawn"].includes(next))request.completedAt=new Date();else request.completedAt=null;request.currentApproverId=null;request.updateBy=actor.sub;await requestRepo.save(request);await actionRepo.save(actionRepo.create({...scope,requestId:id,action:dto.action,actorUserId:actor.sub,comment:dto.comment??null,beforeStatus:before,afterStatus:next,createBy:actor.sub,updateBy:actor.sub}));return request;});}

 private async validateEmployeeReferences(scope:TenantParkScope,dto:CreateHrEmployeeDto,selfId?:string){if(dto.userId&&!await this.users.exists({where:{id:dto.userId,...scope,isDeleted:false,isEnabled:true}}))throw new BadRequestException("User is unavailable in current scope");if(dto.primaryOrgId)await this.mustOrg(scope,dto.primaryOrgId);if(dto.positionId){const p=await this.positions.findOne({where:{id:dto.positionId,...scope,isDeleted:false,status:"enabled"}});if(!p)throw new BadRequestException("Position is unavailable in current scope");if(dto.primaryOrgId&&p.orgId!==dto.primaryOrgId)throw new BadRequestException("Position does not belong to primary organization");}if(dto.managerEmployeeId){if(dto.managerEmployeeId===selfId)throw new BadRequestException("Employee cannot manage themselves");if(!await this.employees.exists({where:{id:dto.managerEmployeeId,...scope,isDeleted:false}}))throw new BadRequestException("Manager employee is unavailable in current scope");}}
 private async mustOrg(scope:TenantParkScope,id:string){if(!await this.orgs.exists({where:{id,...scope,isDeleted:false,status:"enabled"}}))throw new BadRequestException("Organization is unavailable in current scope");}
 private async managedEmployeeIds(scope:TenantParkScope,actor:JwtPrincipal):Promise<string[]>{const manager=await this.myEmployee(scope,actor);const rows=await this.dataSource.query(`WITH RECURSIVE managed_org AS (SELECT id FROM sys_org WHERE tenant_id=$1 AND park_id=$2 AND leader_user_id=$3 AND is_deleted=false AND status='enabled' UNION ALL SELECT child.id FROM sys_org child JOIN managed_org parent ON child.parent_id=parent.id WHERE child.tenant_id=$1 AND child.park_id=$2 AND child.is_deleted=false AND child.status='enabled') SELECT DISTINCT employee.id FROM hr_employee employee WHERE employee.tenant_id=$1 AND employee.park_id=$2 AND employee.is_deleted=false AND employee.id<>$4 AND (employee.manager_employee_id=$4 OR employee.primary_org_id IN (SELECT id FROM managed_org))`,[scope.tenantId,scope.parkId,actor.sub,manager.id]) as Array<{id:string}>;return rows.map(row=>row.id);}
 private eventSnapshot(row:HrEmployeeEntity){return {employeeCode:row.employeeCode,fullName:row.fullName,userId:row.userId,primaryOrgId:row.primaryOrgId,positionId:row.positionId,managerEmployeeId:row.managerEmployeeId,employmentType:row.employmentType,employmentStatus:row.employmentStatus,hireDate:row.hireDate,departureDate:row.departureDate};}
}
