import { BadRequestException,ConflictException,ForbiddenException,Injectable,NotFoundException } from "@nestjs/common";
import { InjectRepository } from "@nestjs/typeorm";
import { HR_PERMISSIONS,type PaginatedResult,type TenantParkScope } from "@jinhu/shared";
import { DataSource,ILike,In,IsNull,Not,type Repository } from "typeorm";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { OrgEntity } from "../orgs/entities/org.entity";
import { UserEntity } from "../users/entities/user.entity";
import type { AdjustHrPayslipDto,AssignHrCompensationDto,CreateHrApprovalDto,CreateHrAttendanceRequestDto,CreateHrCompensationPlanDto,CreateHrContractChangeDto,CreateHrContractDto,CreateHrEmployeeDto,CreateHrFeedbackAssignmentDto,CreateHrFeedbackCycleDto,CreateHrGoalCheckinDto,CreateHrGoalCycleDto,CreateHrGoalDto,CreateHrPayrollPeriodDto,CreateHrPayrollRunDto,CreateHrPerformanceCycleDto,CreateHrPerformancePlanDto,CreateHrPositionDto,CreateHrWorkReportDto,HrApprovalActionDto,HrAttendanceCalendarQueryDto,HrAttendanceRequestListQueryDto,HrContractActionDto,HrContractChangeActionDto,HrContractListQueryDto,HrEmploymentTransitionDto,HrInsurancePeriodQueryDto,HrListQueryDto,ReviewHrAttendanceRequestDto,ReviewHrWorkReportDto,ScoreHrPerformanceDto,SubmitHrFeedbackDto,UpdateHrEmployeeDto,UpdateHrEmployeeProfileDto } from "./dto/hr.dto";
import { HrApprovalActionEntity,HrApprovalRequestEntity,HrAttendanceCalendarSourceEntity,HrAttendanceDayEntity,HrAttendanceRequestEntity,HrCompensationPlanEntity,HrContractChangeEntity,HrContractEntity,HrContractTypeEntity,HrEmployeeCompensationEntity,HrEmployeeEntity,HrEmployeeInsuranceItemEntity,HrEmployeeInsurancePeriodEntity,HrEmployeeProfileEntity,HrEmploymentEventEntity,HrFeedbackAssignmentEntity,HrFeedbackCycleEntity,HrFeedbackResponseEntity,HrGoalCheckinEntity,HrGoalCycleEntity,HrGoalEntity,HrPayrollPeriodEntity,HrPayrollRunEntity,HrPayslipEntity,HrPerformanceCycleEntity,HrPerformanceItemEntity,HrPerformancePlanEntity,HrPositionEntity,HrWorkReportEntity,HrWorkReportGoalEntity } from "./entities/hr.entities";
import { HrNotificationService } from "./hr-notification.service";
import { AuditService } from "../audit/audit.service";
import { recordHrSensitiveRead } from "./hr-sensitive-read-audit";
import { hrCentsToMoney, hrMoneyToCents, normalizeHrMoney } from "./hr-money";
import { HR_MANAGED_EMPLOYEE_IDS_SQL,isHrEmployeeIdAccessible,projectHrApproval,projectHrEmployeeProfile,projectHrFeedbackAssignment,projectHrGoal,projectHrPayrollRun,projectHrPayslip,projectHrPerformancePlan,projectHrWorkReport,resolveHrAttendanceAccessScope,resolveHrContractAccessScope,resolveHrEmployeeAccessScope,resolveHrInsuranceAccessScope,type HrLedgerAccessScope } from "./hr-access-policy";

@Injectable()
export class HrService {
 constructor(
  @InjectRepository(HrEmployeeEntity) private readonly employees:Repository<HrEmployeeEntity>,
  @InjectRepository(HrPositionEntity) private readonly positions:Repository<HrPositionEntity>,
  @InjectRepository(HrEmploymentEventEntity) private readonly events:Repository<HrEmploymentEventEntity>,
  @InjectRepository(HrEmployeeProfileEntity) private readonly profiles:Repository<HrEmployeeProfileEntity>,
  @InjectRepository(HrGoalCycleEntity) private readonly goalCycles:Repository<HrGoalCycleEntity>,
  @InjectRepository(HrGoalEntity) private readonly goals:Repository<HrGoalEntity>,
  @InjectRepository(HrGoalCheckinEntity) private readonly goalCheckinRepo:Repository<HrGoalCheckinEntity>,
  @InjectRepository(HrWorkReportEntity) private readonly reports:Repository<HrWorkReportEntity>,
  @InjectRepository(HrPerformanceCycleEntity) private readonly performanceCycles:Repository<HrPerformanceCycleEntity>,
  @InjectRepository(HrPerformancePlanEntity) private readonly performancePlans:Repository<HrPerformancePlanEntity>,
  @InjectRepository(HrFeedbackCycleEntity) private readonly feedbackCycles:Repository<HrFeedbackCycleEntity>,
  @InjectRepository(HrFeedbackAssignmentEntity) private readonly feedbackAssignments:Repository<HrFeedbackAssignmentEntity>,
  @InjectRepository(HrFeedbackResponseEntity) private readonly feedbackResponses:Repository<HrFeedbackResponseEntity>,
  @InjectRepository(HrCompensationPlanEntity) private readonly compensationPlans:Repository<HrCompensationPlanEntity>,
  @InjectRepository(HrEmployeeCompensationEntity) private readonly employeeCompensations:Repository<HrEmployeeCompensationEntity>,
  @InjectRepository(HrPayrollPeriodEntity) private readonly payrollPeriods:Repository<HrPayrollPeriodEntity>,
  @InjectRepository(HrPayrollRunEntity) private readonly payrollRuns:Repository<HrPayrollRunEntity>,
  @InjectRepository(HrPayslipEntity) private readonly payslips:Repository<HrPayslipEntity>,
  @InjectRepository(HrApprovalRequestEntity) private readonly approvalRequests:Repository<HrApprovalRequestEntity>,
  @InjectRepository(HrContractTypeEntity) private readonly contractTypes:Repository<HrContractTypeEntity>,
  @InjectRepository(HrContractEntity) private readonly contracts:Repository<HrContractEntity>,
  @InjectRepository(HrContractChangeEntity) private readonly contractChanges:Repository<HrContractChangeEntity>,
  @InjectRepository(HrAttendanceCalendarSourceEntity) private readonly attendanceCalendars:Repository<HrAttendanceCalendarSourceEntity>,
  @InjectRepository(HrAttendanceDayEntity) private readonly attendanceDays:Repository<HrAttendanceDayEntity>,
  @InjectRepository(HrEmployeeInsurancePeriodEntity) private readonly insurancePeriods:Repository<HrEmployeeInsurancePeriodEntity>,
  @InjectRepository(HrEmployeeInsuranceItemEntity) private readonly insuranceItems:Repository<HrEmployeeInsuranceItemEntity>,
  @InjectRepository(HrAttendanceRequestEntity) private readonly attendanceRequests:Repository<HrAttendanceRequestEntity>,
  @InjectRepository(OrgEntity) private readonly orgs:Repository<OrgEntity>,
  @InjectRepository(UserEntity) private readonly users:Repository<UserEntity>,
  private readonly notifications:HrNotificationService,
  private readonly dataSource:DataSource,
  private readonly auditService:AuditService
 ){}

 async listEmployees(scope:TenantParkScope,actor:JwtPrincipal,q:HrListQueryDto):Promise<PaginatedResult<HrEmployeeEntity>>{
  const accessScope=resolveHrEmployeeAccessScope(actor);
  if(accessScope==="none")return {items:[],total:0,page:q.page,page_size:q.page_size};
  const employee=accessScope==="self"?await this.myEmployee(scope,actor):null;
  const managedIds=accessScope==="managed_org_tree"?await this.managedEmployeeIds(scope,actor):null;
  const baseWhere={tenantId:scope.tenantId,parkId:scope.parkId,isDeleted:false,...(employee?{id:employee.id}:{}),...(managedIds?{id:In(managedIds.length?managedIds:["00000000-0000-0000-0000-000000000000"])}:{}),...(q.status?{employmentStatus:q.status}:{}),...(q.org_id?{primaryOrgId:q.org_id}:{})};
  const where=q.keyword?[{...baseWhere,fullName:ILike(`%${q.keyword}%`)},{...baseWhere,employeeCode:ILike(`%${q.keyword}%`)}]:baseWhere;
  const [items,total]=await this.employees.findAndCount({where,order:{employeeCode:"ASC"},skip:(q.page-1)*q.page_size,take:q.page_size});
  return {items,total,page:q.page,page_size:q.page_size};
 }
 async detailEmployee(scope:TenantParkScope,id:string){const row=await this.employees.findOne({where:{id,...scope,isDeleted:false}});if(!row)throw new NotFoundException("Employee not found");return row;}
 async detailEmployeeForActor(scope:TenantParkScope,actor:JwtPrincipal,id:string){const accessScope=resolveHrEmployeeAccessScope(actor);if(accessScope==="park")return this.detailEmployee(scope,id);if(accessScope==="none")throw new NotFoundException("Employee not found");const employee=await this.myEmployee(scope,actor);const managedIds=accessScope==="managed_org_tree"?await this.managedEmployeeIds(scope,actor):[];if(!isHrEmployeeIdAccessible(accessScope,id,employee.id,managedIds))throw new NotFoundException("Employee not found");return employee.id===id?employee:this.detailEmployee(scope,id);}
 async myEmployee(scope:TenantParkScope,actor:JwtPrincipal){const row=await this.employees.findOne({where:{...scope,userId:actor.sub,isDeleted:false}});if(!row)throw new NotFoundException("No employee profile is linked to current user");return row;}
 async employeeEvents(scope:TenantParkScope,id:string){await this.detailEmployee(scope,id);return this.events.find({where:{...scope,employeeId:id,isDeleted:false},order:{effectiveDate:"DESC",createTime:"DESC"}});}
 async employeeProfile(scope:TenantParkScope,actor:JwtPrincipal,id:string){await this.detailEmployee(scope,id);const row=await this.profiles.findOne({where:{...scope,employeeId:id,isDeleted:false}});const canReadFull=actor.isSuper||actor.permissions.includes("*")||actor.permissions.includes(HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE);const projected=projectHrEmployeeProfile(row,canReadFull);await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.employee_profile",action:"读取员工敏感档案",bizType:"hr_employee",bizId:id,path:"/hr/employees/:id/profile",fieldGroups:["identity","contact"],projection:canReadFull?"full":"masked",itemCount:projected?1:0});return projected;}

 async updateEmployeeProfile(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:UpdateHrEmployeeProfileDto){
  await this.detailEmployee(scope,id);
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeProfileEntity);
   let row=await repo.findOne({where:{...scope,employeeId:id,isDeleted:false},lock:{mode:"pessimistic_write"}});
   if(!row)row=repo.create({...scope,employeeId:id,createBy:actor.sub});
   Object.assign(row,{...dto,idType:dto.idType??null,idNumberMasked:dto.idNumberMasked??null,personalMobile:dto.personalMobile??null,personalEmail:dto.personalEmail??null,address:dto.address??null,emergencyContactName:dto.emergencyContactName??null,emergencyContactMobile:dto.emergencyContactMobile??null,remark:dto.remark??null,updateBy:actor.sub});
   return repo.save(row);
  });
 }

 async transitionEmployment(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HrEmploymentTransitionDto){
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeEntity),eventRepo=manager.getRepository(HrEmploymentEventEntity);
   const row=await repo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
   if(!row)throw new NotFoundException("Employee not found");
   const targetByAction:Record<string,string>={start_probation:"probation",confirm_employment:"active",suspend:"suspended",resume:"active",depart:"departed"};
   const allowed:Record<string,string[]>={preboarding:["start_probation","confirm_employment","depart"],probation:["confirm_employment","depart"],active:["transfer","suspend","depart"],suspended:["resume","depart"],departed:[]};
   if(!allowed[row.employmentStatus]?.includes(dto.action))throw new BadRequestException(`Action ${dto.action} is not allowed from ${row.employmentStatus}`);
   if(dto.action==="transfer"){
    if(!dto.primaryOrgId)throw new BadRequestException("Transfer requires primary organization");
    await this.validateEmployeeReferences(scope,{employeeCode:row.employeeCode,fullName:row.fullName,primaryOrgId:dto.primaryOrgId,positionId:dto.positionId,managerEmployeeId:dto.managerEmployeeId},id);
   }
   const before=this.eventSnapshot(row);
   if(dto.action==="transfer")Object.assign(row,{primaryOrgId:dto.primaryOrgId,positionId:dto.positionId??null,managerEmployeeId:dto.managerEmployeeId??null});
   else row.employmentStatus=targetByAction[dto.action]!;
   if(dto.action==="confirm_employment")row.probationEndDate=dto.effectiveDate;
   if(dto.action==="depart")row.departureDate=dto.effectiveDate;
   if(dto.action==="resume")row.departureDate=null;
   row.updateBy=actor.sub;
   const saved=await repo.save(row);
   await eventRepo.save(eventRepo.create({...scope,employeeId:id,eventType:dto.action,effectiveDate:dto.effectiveDate,beforeSnapshot:before,afterSnapshot:this.eventSnapshot(saved),reason:dto.reason,status:"effective",createBy:actor.sub,updateBy:actor.sub}));
   return saved;
  });
 }

 async createEmployee(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrEmployeeDto){
  await this.validateEmployeeReferences(scope,dto);
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeEntity),eventRepo=manager.getRepository(HrEmploymentEventEntity);
   if(await repo.exists({where:{...scope,employeeCode:dto.employeeCode,isDeleted:false}}))throw new ConflictException("Employee code already exists");
   if(dto.userId&&await repo.exists({where:{...scope,userId:dto.userId,isDeleted:false}}))throw new ConflictException("User is already linked to another employee");
   const row=await repo.save(repo.create({...scope,...dto,userId:dto.userId??null,primaryOrgId:dto.primaryOrgId??null,positionId:dto.positionId??null,managerEmployeeId:dto.managerEmployeeId??null,employmentType:dto.employmentType??"full_time",employmentStatus:"preboarding",hireDate:dto.hireDate??null,probationEndDate:null,departureDate:null,workLocation:dto.workLocation??null,workMobile:dto.workMobile??null,workEmail:dto.workEmail??null,remark:dto.remark??null,createBy:actor.sub,updateBy:actor.sub}));
   await eventRepo.save(eventRepo.create({...scope,employeeId:row.id,eventType:"created",effectiveDate:dto.hireDate??new Date().toISOString().slice(0,10),beforeSnapshot:{},afterSnapshot:this.eventSnapshot(row),reason:"创建员工档案",createBy:actor.sub,updateBy:actor.sub}));
   return row;
  });
 }
 async updateEmployee(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:UpdateHrEmployeeDto){
  await this.validateEmployeeReferences(scope,dto,id);
  if(dto.userId&&await this.employees.exists({where:{...scope,userId:dto.userId,isDeleted:false,id:Not(id)}}))throw new ConflictException("User is already linked to another employee");
  return this.dataSource.transaction(async manager=>{
   const repo=manager.getRepository(HrEmployeeEntity),eventRepo=manager.getRepository(HrEmploymentEventEntity);
   const row=await repo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!row)throw new NotFoundException("Employee not found");
   if(dto.employmentStatus!==row.employmentStatus)throw new BadRequestException("Employment status must be changed through a lifecycle action");
   if(await repo.exists({where:{...scope,employeeCode:dto.employeeCode,isDeleted:false,id:Not(id)}}))throw new ConflictException("Employee code already exists");
   const before=this.eventSnapshot(row);Object.assign(row,{...dto,userId:dto.userId??null,primaryOrgId:dto.primaryOrgId??null,positionId:dto.positionId??null,managerEmployeeId:dto.managerEmployeeId??null,hireDate:dto.hireDate??null,probationEndDate:dto.probationEndDate??null,departureDate:dto.departureDate??null,workLocation:dto.workLocation??null,workMobile:dto.workMobile??null,workEmail:dto.workEmail??null,remark:dto.remark??null,updateBy:actor.sub});
   const saved=await repo.save(row);await eventRepo.save(eventRepo.create({...scope,employeeId:id,eventType:"profile_updated",effectiveDate:new Date().toISOString().slice(0,10),beforeSnapshot:before,afterSnapshot:this.eventSnapshot(saved),reason:"更新员工档案",createBy:actor.sub,updateBy:actor.sub}));return saved;
  });
 }
 async listPositions(scope:TenantParkScope){return this.positions.find({where:{...scope,isDeleted:false},order:{positionCode:"ASC"}});}
 async createPosition(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPositionDto){await this.mustOrg(scope,dto.orgId);if(await this.positions.exists({where:{...scope,positionCode:dto.positionCode,isDeleted:false}}))throw new ConflictException("Position code already exists");return this.positions.save(this.positions.create({...scope,...dto,jobFamily:dto.jobFamily??null,jobLevel:dto.jobLevel??null,headcountLimit:dto.headcountLimit??null,status:dto.status??"enabled",remark:dto.remark??null,createBy:actor.sub,updateBy:actor.sub}));}

 async listContracts(scope:TenantParkScope,actor:JwtPrincipal,q:HrContractListQueryDto){
  const access=resolveHrContractAccessScope(actor);
  if(!access.park&&!access.managedOrgTree&&!access.self)return {items:[],total:0,page:q.page,page_size:q.page_size};
  const accessibleIds=await this.contractEmployeeIds(scope,actor);
  const result=await this.findContracts(scope,q,accessibleIds);
  const projected=access.self&&!access.park&&!access.managedOrgTree?{...result,items:result.items.map(row=>this.projectSelfContract(row))}:result;
  await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.contract",action:"读取劳动合同台账",bizType:"hr_contract",bizId:null,path:"/hr/contracts",fieldGroups:["employment_contract"],projection:access.park?"park":access.managedOrgTree?"team":"self",itemCount:result.items.length});
  return projected;
 }
 async listContractTypes(scope:TenantParkScope){const rows=await this.contractTypes.find({where:{...scope,status:"enabled",isDeleted:false},order:{typeCode:"ASC"}});return rows.map(row=>({id:row.id,typeCode:row.typeCode,typeName:row.typeName,isHistoricalImport:row.isHistoricalImport}));}
 async listAttendanceCalendars(scope:TenantParkScope,actor:JwtPrincipal,q:HrAttendanceCalendarQueryDto){
  const access=resolveHrAttendanceAccessScope(actor);
  if(access==="none")return {items:[],total:0,page:q.page,page_size:q.page_size};
  const qb=this.attendanceCalendars.createQueryBuilder("calendar").where("calendar.tenant_id=:tenantId AND calendar.park_id=:parkId AND calendar.is_deleted=false",scope);
  if(q.year)qb.andWhere("calendar.calendar_year=:year",{year:q.year});if(q.month)qb.andWhere("calendar.calendar_month=:month",{month:q.month});
  const total=await qb.getCount();
  const calendars=await qb.clone().select(["calendar.id","calendar.calendarName","calendar.calendarYear","calendar.calendarMonth"]).orderBy("calendar.calendar_year","DESC").addOrderBy("calendar.calendar_month","DESC").addOrderBy("calendar.id","ASC").skip((q.page-1)*q.page_size).take(q.page_size).getMany();
  const ids=calendars.map(row=>row.id),days=ids.length?await this.attendanceDays.createQueryBuilder("day").where("day.tenant_id=:tenantId AND day.park_id=:parkId AND day.is_deleted=false",scope).andWhere("day.calendar_source_id IN (:...ids)",{ids}).select(["day.id","day.calendarSourceId","day.attendanceDate","day.legacySymbol","day.symbolStatus","day.normalizedKind"]).orderBy("day.attendance_date","ASC").getMany():[];
  const items=calendars.map(calendar=>({id:calendar.id,calendarName:calendar.calendarName,year:calendar.calendarYear,month:calendar.calendarMonth,dayCount:days.filter(day=>day.calendarSourceId===calendar.id).length,days:days.filter(day=>day.calendarSourceId===calendar.id).map(day=>({date:day.attendanceDate,legacySymbol:day.legacySymbol,symbolStatus:day.symbolStatus,normalizedKind:day.normalizedKind}))}));
  await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.attendance_calendar",action:"读取历史考勤月历",bizType:"hr_attendance_calendar",bizId:null,path:"/hr/attendance/calendars",fieldGroups:["attendance"],projection:access==="park"?"park":access==="managed_org_tree"?"team":"self",itemCount:items.length});
  return {items,total,page:q.page,page_size:q.page_size};
 }
 async listInsurancePeriods(scope:TenantParkScope,actor:JwtPrincipal,q:HrInsurancePeriodQueryDto,forceSelf=false){
  const canReadSelf=actor.isSuper||actor.permissions.includes("*")||actor.permissions.includes(HR_PERMISSIONS.HR_INSURANCE_SELF_READ);
  const access:HrLedgerAccessScope=forceSelf?(canReadSelf?"self":"none"):resolveHrInsuranceAccessScope(actor);
  if(access==="none")return {items:[],total:0,page:q.page,page_size:q.page_size};
  const employeeIds=await this.ledgerEmployeeIds(scope,actor,access);
  if(employeeIds!==null&&!employeeIds.length){await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.employee_insurance",action:"读取员工社保台账",bizType:"hr_employee_insurance_period",bizId:null,path:forceSelf?"/hr/insurance/periods/me":"/hr/insurance/periods",fieldGroups:["financial","insurance"],projection:access==="managed_org_tree"?"team":"self",itemCount:0});return {items:[],total:0,page:q.page,page_size:q.page_size};}
  const qb=this.insurancePeriods.createQueryBuilder("period").innerJoin(HrEmployeeEntity,"employee","employee.id=period.employee_id AND employee.tenant_id=period.tenant_id AND employee.park_id=period.park_id AND employee.is_deleted=false").where("period.tenant_id=:tenantId AND period.park_id=:parkId AND period.is_deleted=false",scope);
  if(employeeIds!==null)qb.andWhere("period.employee_id IN (:...employeeIds)",{employeeIds});if(q.year)qb.andWhere("period.period_year=:year",{year:q.year});if(q.month)qb.andWhere("period.period_month=:month",{month:q.month});if(q.needs_review!==undefined)qb.andWhere("period.needs_review=:needsReview",{needsReview:q.needs_review});if(q.keyword)qb.andWhere("(employee.full_name ILIKE :keyword OR employee.employee_code ILIKE :keyword)",{keyword:`%${q.keyword}%`});
  const total=await qb.getCount();
  const rows=await qb.clone().select(["period.id AS id","period.employee_id AS employee_id","employee.employee_code AS employee_code","employee.full_name AS employee_name","period.period_year AS period_year","period.period_month AS period_month","period.needs_review AS needs_review"]).orderBy("period.period_year","DESC").addOrderBy("period.period_month","DESC").addOrderBy("employee.employee_code","ASC").addOrderBy("period.id","ASC").offset((q.page-1)*q.page_size).limit(q.page_size).getRawMany<Record<string,unknown>>();
  const items=await Promise.all(rows.map(row=>this.projectInsurancePeriod(scope,row,access)));
  await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.employee_insurance",action:"读取员工社保台账",bizType:"hr_employee_insurance_period",bizId:null,path:forceSelf?"/hr/insurance/periods/me":"/hr/insurance/periods",fieldGroups:["financial","insurance"],projection:access==="park"?"park":access==="managed_org_tree"?"team":"self",itemCount:items.length});
  return {items,total,page:q.page,page_size:q.page_size};
 }
 async insurancePeriodDetail(scope:TenantParkScope,actor:JwtPrincipal,id:string){
  const access=resolveHrInsuranceAccessScope(actor);if(access==="none")throw new NotFoundException("Insurance period not found");
  const employeeIds=await this.ledgerEmployeeIds(scope,actor,access);
  const qb=this.insurancePeriods.createQueryBuilder("period").innerJoin(HrEmployeeEntity,"employee","employee.id=period.employee_id AND employee.tenant_id=period.tenant_id AND employee.park_id=period.park_id AND employee.is_deleted=false").where("period.id=:id AND period.tenant_id=:tenantId AND period.park_id=:parkId AND period.is_deleted=false",{id,...scope});
  if(employeeIds!==null){if(!employeeIds.length)throw new NotFoundException("Insurance period not found");qb.andWhere("period.employee_id IN (:...employeeIds)",{employeeIds});}
  const row=await qb.select(["period.id AS id","period.employee_id AS employee_id","employee.employee_code AS employee_code","employee.full_name AS employee_name","period.period_year AS period_year","period.period_month AS period_month","period.needs_review AS needs_review"]).getRawOne<Record<string,unknown>>();if(!row)throw new NotFoundException("Insurance period not found");
  const projected=await this.projectInsurancePeriod(scope,row,access,true);await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.employee_insurance",action:"读取员工社保明细",bizType:"hr_employee_insurance_period",bizId:id,path:"/hr/insurance/periods/:id",fieldGroups:["financial","insurance"],projection:access==="park"?"park":access==="managed_org_tree"?"team":"self",itemCount:1});return projected;
 }
 private async ledgerEmployeeIds(scope:TenantParkScope,actor:JwtPrincipal,access:HrLedgerAccessScope){if(access==="park")return null;if(access==="self")return [(await this.myEmployee(scope,actor)).id];const ids=await this.managedEmployeeIds(scope,actor);if(actor.permissions.includes(HR_PERMISSIONS.HR_INSURANCE_SELF_READ))ids.push((await this.myEmployee(scope,actor)).id);return [...new Set(ids)];}
 private async projectInsurancePeriod(scope:TenantParkScope,row:Record<string,unknown>,access:HrLedgerAccessScope,includeItems=false){
  const id=String(row.id);const entities=await this.insuranceItems.find({where:{...scope,periodId:id,isDeleted:false},order:{insuranceKind:"ASC"}});const sum=(field:"totalAmount"|"employerAmount"|"employeeAmount"|"supplementAmount")=>entities.reduce((value,item)=>value+hrMoneyToCents(item[field]??"0"),0n);const full=access==="park";
  const base={id,periodYear:Number(row.period_year),periodMonth:Number(row.period_month),needsReview:Boolean(row.needs_review),employeeAmount:hrCentsToMoney(sum("employeeAmount")),supplementAmount:hrCentsToMoney(sum("supplementAmount")),itemCount:entities.length,...(access==="self"?{}:{employeeId:String(row.employee_id),employeeCode:String(row.employee_code),employeeName:String(row.employee_name)}),...(full?{employerAmount:hrCentsToMoney(sum("employerAmount")),totalAmount:hrCentsToMoney(sum("totalAmount"))}:{})};
  if(!includeItems||access==="managed_org_tree")return base;return {...base,items:entities.map(item=>({insuranceKind:item.insuranceKind,contributionBase:item.contributionBase,employeeAmount:item.employeeAmount,supplementAmount:item.supplementAmount,legacyBaseNegative:item.legacyBaseNegative,...(full?{employerAmount:item.employerAmount,totalAmount:item.totalAmount}:{})}))};
 }
 async listAttendanceRequests(scope:TenantParkScope,actor:JwtPrincipal,q:HrAttendanceRequestListQueryDto){
  const access=resolveHrAttendanceAccessScope(actor);if(access==="none")return {items:[],total:0,page:q.page,page_size:q.page_size};const employeeIds=await this.attendanceRequestEmployeeIds(scope,actor,access);if(employeeIds!==null&&!employeeIds.length){await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.attendance_request",action:"读取考勤申请",bizType:"hr_attendance_request",bizId:null,path:"/hr/attendance/requests",fieldGroups:["attendance"],projection:access==="managed_org_tree"?"team":"self",itemCount:0});return {items:[],total:0,page:q.page,page_size:q.page_size};}
  const qb=this.attendanceRequests.createQueryBuilder("request").innerJoin(HrEmployeeEntity,"employee","employee.id=request.employee_id AND employee.tenant_id=request.tenant_id AND employee.park_id=request.park_id AND employee.is_deleted=false").where("request.tenant_id=:tenantId AND request.park_id=:parkId AND request.is_deleted=false",scope);if(employeeIds!==null)qb.andWhere("request.employee_id IN (:...employeeIds)",{employeeIds});if(q.type)qb.andWhere("request.request_type=:type",{type:q.type});if(q.status)qb.andWhere("request.status=:status",{status:q.status});const total=await qb.getCount();const rows=await qb.clone().select(["request.id AS id","request.request_no AS request_no","request.employee_id AS employee_id","employee.employee_code AS employee_code","employee.full_name AS employee_name","employee.user_id AS employee_user_id","request.request_type AS request_type","request.start_at AS start_at","request.end_at AS end_at","request.attendance_date AS attendance_date","request.duration_minutes AS duration_minutes","request.reason AS reason","request.status AS status","request.submitted_at AS submitted_at","request.reviewed_at AS reviewed_at","request.review_comment AS review_comment"]).orderBy("request.create_time","DESC").offset((q.page-1)*q.page_size).limit(q.page_size).getRawMany<Record<string,unknown>>();const items=rows.map(row=>this.projectAttendanceRequest(row,access,actor.sub));await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.attendance_request",action:"读取考勤申请",bizType:"hr_attendance_request",bizId:null,path:"/hr/attendance/requests",fieldGroups:["attendance"],projection:access==="park"?"park":access==="managed_org_tree"?"team":"self",itemCount:items.length});return {items,total,page:q.page,page_size:q.page_size};
 }
 async createAttendanceRequest(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrAttendanceRequestDto){const timing=this.validateAttendanceRequest(dto);try{return await this.dataSource.transaction(async manager=>{const employeeRepo=manager.getRepository(HrEmployeeEntity),requestRepo=manager.getRepository(HrAttendanceRequestEntity),approvalRepo=manager.getRepository(HrApprovalRequestEntity);const employee=await employeeRepo.findOne({where:{...scope,userId:actor.sub,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!employee)throw new NotFoundException("No employee profile is linked to current user");const requestNo=`ATT-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const approval=await approvalRepo.save(approvalRepo.create({...scope,requestNo,requestType:"attendance_request",applicantEmployeeId:employee.id,subjectEmployeeId:employee.id,title:this.attendanceRequestLabel(dto.requestType),payload:{requestType:dto.requestType},status:"draft",currentApproverId:null,submittedAt:null,completedAt:null,createBy:actor.sub,updateBy:actor.sub}));const row=await requestRepo.save(requestRepo.create({...scope,requestNo,employeeId:employee.id,requestType:dto.requestType,startAt:timing.startAt,endAt:timing.endAt,attendanceDate:timing.attendanceDate,durationMinutes:timing.durationMinutes,reason:dto.reason,status:"draft",approvalRequestId:approval.id,submittedAt:null,reviewedAt:null,reviewedBy:null,reviewComment:null,createBy:actor.sub,updateBy:actor.sub}));return this.projectAttendanceRequestEntity(row,"self");});}catch(error){if((error as {code?:string}).code==="23505")throw new ConflictException("Attendance request conflicts with an existing request");throw error;}}
 async submitAttendanceRequest(scope:TenantParkScope,actor:JwtPrincipal,id:string){const existing=await this.attendanceRequests.findOne({where:{id,...scope,isDeleted:false}});if(!existing)throw new NotFoundException("Attendance request not found");return this.dataSource.transaction(async manager=>{const employeeRepo=manager.getRepository(HrEmployeeEntity),requestRepo=manager.getRepository(HrAttendanceRequestEntity),approvalRepo=manager.getRepository(HrApprovalRequestEntity),actionRepo=manager.getRepository(HrApprovalActionEntity);const employee=await employeeRepo.findOne({where:{id:existing.employeeId,...scope,userId:actor.sub,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!employee)throw new NotFoundException("Attendance request not found");const row=await requestRepo.findOne({where:{id,...scope,employeeId:employee.id,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!row)throw new NotFoundException("Attendance request not found");if(!["draft","returned"].includes(row.status))throw new ConflictException("Only draft or returned attendance requests can be submitted");await this.assertNoAttendanceRequestOverlap(manager,scope,row);const approval=await approvalRepo.findOne({where:{id:row.approvalRequestId!,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!approval)throw new ConflictException("Attendance approval projection is unavailable");const before=approval.status,action=row.status==="returned"?"resubmit":"submit";row.status="submitted";row.submittedAt=new Date();row.reviewedAt=null;row.reviewedBy=null;row.reviewComment=null;row.updateBy=actor.sub;approval.status="submitted";approval.submittedAt=row.submittedAt;approval.completedAt=null;approval.updateBy=actor.sub;await requestRepo.save(row);await approvalRepo.save(approval);await actionRepo.save(actionRepo.create({...scope,requestId:approval.id,action,actorUserId:actor.sub,comment:null,beforeStatus:before,afterStatus:"submitted",createBy:actor.sub,updateBy:actor.sub}));await this.notifications.publishAttendanceRequestSubmitted(scope,actor,row,manager);return this.projectAttendanceRequestEntity(row,"self");});}
 async cancelAttendanceRequest(scope:TenantParkScope,actor:JwtPrincipal,id:string){const existing=await this.attendanceRequests.findOne({where:{id,...scope,isDeleted:false}});if(!existing)throw new NotFoundException("Attendance request not found");return this.dataSource.transaction(async manager=>{const employee=await manager.getRepository(HrEmployeeEntity).findOne({where:{id:existing.employeeId,...scope,userId:actor.sub,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!employee)throw new NotFoundException("Attendance request not found");const requestRepo=manager.getRepository(HrAttendanceRequestEntity),row=await requestRepo.findOne({where:{id,...scope,employeeId:employee.id,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!row)throw new NotFoundException("Attendance request not found");if(!["draft","submitted","returned"].includes(row.status))throw new ConflictException("Terminal attendance requests are immutable");const approvalRepo=manager.getRepository(HrApprovalRequestEntity),approval=await approvalRepo.findOne({where:{id:row.approvalRequestId!,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!approval)throw new ConflictException("Attendance approval projection is unavailable");const before=approval.status;row.status="cancelled";row.updateBy=actor.sub;approval.status="withdrawn";approval.completedAt=new Date();approval.updateBy=actor.sub;await requestRepo.save(row);await approvalRepo.save(approval);await manager.getRepository(HrApprovalActionEntity).save(manager.getRepository(HrApprovalActionEntity).create({...scope,requestId:approval.id,action:"withdraw",actorUserId:actor.sub,comment:null,beforeStatus:before,afterStatus:"withdrawn",createBy:actor.sub,updateBy:actor.sub}));return this.projectAttendanceRequestEntity(row,"self");});}
 async reviewAttendanceRequest(scope:TenantParkScope,actor:JwtPrincipal,id:string,decision:"approve"|"reject",dto:ReviewHrAttendanceRequestDto){if(decision==="reject"&&!dto.comment?.trim())throw new BadRequestException("A return comment is required");const existing=await this.attendanceRequests.findOne({where:{id,...scope,isDeleted:false}});if(!existing)throw new NotFoundException("Attendance request not found");return this.dataSource.transaction(async manager=>{const employeeRepo=manager.getRepository(HrEmployeeEntity),employee=await employeeRepo.findOne({where:{id:existing.employeeId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!employee||employee.userId===actor.sub)throw new ForbiddenException("Reviewers cannot approve their own attendance request");const access=resolveHrAttendanceAccessScope(actor);if(access!=="park"){if(access!=="managed_org_tree"||(await this.managedEmployeeIds(scope,actor)).includes(employee.id)===false)throw new NotFoundException("Attendance request not found");}const requestRepo=manager.getRepository(HrAttendanceRequestEntity),row=await requestRepo.findOne({where:{id,...scope,employeeId:employee.id,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!row)throw new NotFoundException("Attendance request not found");if(row.status!=="submitted")throw new ConflictException("Only submitted attendance requests can be reviewed");if(decision==="approve")await this.assertNoAttendanceRequestOverlap(manager,scope,row);const approvalRepo=manager.getRepository(HrApprovalRequestEntity),approval=await approvalRepo.findOne({where:{id:row.approvalRequestId!,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!approval||approval.status!=="submitted")throw new ConflictException("Attendance approval projection is not submitted");row.status=decision==="approve"?"approved":"returned";row.reviewedAt=new Date();row.reviewedBy=actor.sub;row.reviewComment=dto.comment??null;row.updateBy=actor.sub;approval.status=decision==="approve"?"approved":"returned";approval.completedAt=decision==="approve"?row.reviewedAt:null;approval.updateBy=actor.sub;await requestRepo.save(row);await approvalRepo.save(approval);await manager.getRepository(HrApprovalActionEntity).save(manager.getRepository(HrApprovalActionEntity).create({...scope,requestId:approval.id,action:decision==="approve"?"approve":"return",actorUserId:actor.sub,comment:dto.comment??null,beforeStatus:"submitted",afterStatus:approval.status,createBy:actor.sub,updateBy:actor.sub}));await this.notifications.publishAttendanceRequestReviewed(scope,actor,row,manager);return this.projectAttendanceRequestEntity(row,access);});}
 private validateAttendanceRequest(dto:CreateHrAttendanceRequestDto){const correction=dto.requestType==="correction";if(!dto.reason.trim())throw new BadRequestException("Attendance request reason is required");if(correction){if(!dto.attendanceDate||dto.startAt||dto.endAt||!/^\d{4}-\d{2}-\d{2}$/.test(dto.attendanceDate)||new Date(`${dto.attendanceDate}T00:00:00Z`).toISOString().slice(0,10)!==dto.attendanceDate)throw new BadRequestException("Correction requests require one valid attendance date");return {startAt:null,endAt:null,attendanceDate:dto.attendanceDate,durationMinutes:0};}if(dto.attendanceDate||!dto.startAt||!dto.endAt||!/(?:Z|[+-]\d{2}:\d{2})$/.test(dto.startAt)||!/(?:Z|[+-]\d{2}:\d{2})$/.test(dto.endAt))throw new BadRequestException("Timed attendance requests require start and end time with timezone");const startAt=new Date(dto.startAt),endAt=new Date(dto.endAt),duration=endAt.getTime()-startAt.getTime();if(!Number.isFinite(duration)||duration<=0||startAt.getTime()%60000!==0||endAt.getTime()%60000!==0)throw new BadRequestException("Attendance request times must form positive whole minutes");const durationMinutes=duration/60000;if(durationMinutes>44640)throw new BadRequestException("Attendance request cannot exceed 31 days");return {startAt,endAt,attendanceDate:null,durationMinutes};}
 private async assertNoAttendanceRequestOverlap(manager:import("typeorm").EntityManager,scope:TenantParkScope,row:HrAttendanceRequestEntity){const qb=manager.getRepository(HrAttendanceRequestEntity).createQueryBuilder("other").where("other.tenant_id=:tenantId AND other.park_id=:parkId AND other.employee_id=:employeeId AND other.id<>:id AND other.is_deleted=false AND other.status IN ('submitted','approved')",{...scope,employeeId:row.employeeId,id:row.id});if(row.requestType==="correction")qb.andWhere("other.request_type='correction' AND other.attendance_date=:attendanceDate",{attendanceDate:row.attendanceDate});else qb.andWhere("other.request_type<>'correction' AND other.start_at<:endAt AND other.end_at>:startAt",{startAt:row.startAt,endAt:row.endAt});if(await qb.getExists())throw new ConflictException("Attendance request overlaps an existing submitted or approved request");}
 private async attendanceRequestEmployeeIds(scope:TenantParkScope,actor:JwtPrincipal,access:HrLedgerAccessScope){if(access==="park")return null;if(access==="self")return [(await this.myEmployee(scope,actor)).id];const ids=await this.managedEmployeeIds(scope,actor);if(actor.permissions.includes(HR_PERMISSIONS.HR_ATTENDANCE_SELF_READ))ids.push((await this.myEmployee(scope,actor)).id);return [...new Set(ids)];}
 private projectAttendanceRequest(row:Record<string,unknown>,access:HrLedgerAccessScope,actorUserId?:string){return {id:String(row.id),requestNo:String(row.request_no),requestType:String(row.request_type),startAt:row.start_at===null?null:new Date(String(row.start_at)).toISOString(),endAt:row.end_at===null?null:new Date(String(row.end_at)).toISOString(),attendanceDate:row.attendance_date===null?null:String(row.attendance_date),durationMinutes:Number(row.duration_minutes),reason:String(row.reason),status:String(row.status),submittedAt:row.submitted_at===null?null:new Date(String(row.submitted_at)).toISOString(),reviewedAt:row.reviewed_at===null?null:new Date(String(row.reviewed_at)).toISOString(),reviewComment:row.review_comment===null?null:String(row.review_comment),isSelf:actorUserId!==undefined&&String(row.employee_user_id)===actorUserId,...(access==="self"?{}:{employeeId:String(row.employee_id),employeeCode:String(row.employee_code),employeeName:String(row.employee_name)})};}
 private projectAttendanceRequestEntity(row:HrAttendanceRequestEntity,access:HrLedgerAccessScope){return {id:row.id,requestNo:row.requestNo,requestType:row.requestType,startAt:row.startAt?.toISOString()??null,endAt:row.endAt?.toISOString()??null,attendanceDate:row.attendanceDate,durationMinutes:row.durationMinutes,reason:row.reason,status:row.status,submittedAt:row.submittedAt?.toISOString()??null,reviewedAt:row.reviewedAt?.toISOString()??null,reviewComment:row.reviewComment,isSelf:access==="self",...(access==="self"?{}:{employeeId:row.employeeId})};}
 private attendanceRequestLabel(type:string){return {leave:"请假申请",overtime:"加班申请",business_trip:"出差申请",correction:"考勤更正申请"}[type]??"考勤申请";}
 async createContract(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrContractDto){
  if(dto.endDate&&dto.endDate<dto.startDate)throw new BadRequestException("Contract end date cannot precede start date");
  if(dto.probationEndDate&&(dto.probationEndDate<dto.startDate||(dto.endDate&&dto.probationEndDate>dto.endDate)))throw new BadRequestException("Probation end date must be within the contract term");
  try{return await this.dataSource.transaction(async manager=>{
   const employeeRepo=manager.getRepository(HrEmployeeEntity),typeRepo=manager.getRepository(HrContractTypeEntity),contractRepo=manager.getRepository(HrContractEntity);
   const employee=await employeeRepo.findOne({where:{id:dto.employeeId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
   if(!employee)throw new BadRequestException("Employee is unavailable in current scope");
   const type=await typeRepo.findOne({where:{id:dto.contractTypeId,...scope,status:"enabled",isDeleted:false}});
   if(!type)throw new BadRequestException("Contract type is unavailable in current scope");
   if(await contractRepo.exists({where:{...scope,employeeId:dto.employeeId,status:In(["draft","active"]),isDeleted:false}}))throw new ConflictException("Employee already has an active or draft contract");
   if(await contractRepo.exists({where:{...scope,contractNo:dto.contractNo,isDeleted:false}}))throw new ConflictException("Contract number already exists");
   const row=await contractRepo.save(contractRepo.create({...scope,employeeId:dto.employeeId,contractTypeId:dto.contractTypeId,contractNo:dto.contractNo,startDate:dto.startDate,endDate:dto.endDate??null,probationEndDate:dto.probationEndDate??null,status:"draft",isHistoricalImport:false,sourceSnapshot:{},remark:dto.remark??null,createBy:actor.sub,updateBy:actor.sub}));
   return this.projectContract(row,employee,type);
  });}catch(error){if((error as {code?:string}).code==="23505")throw new ConflictException("Contract draft conflicts with an existing record");throw error;}
 }
 async actContract(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HrContractActionDto){return this.dataSource.transaction(async manager=>{
  const employeeRepo=manager.getRepository(HrEmployeeEntity),typeRepo=manager.getRepository(HrContractTypeEntity),contractRepo=manager.getRepository(HrContractEntity);
  const contract=await contractRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
  if(!contract)throw new NotFoundException("Contract not found");
  if(contract.isHistoricalImport)throw new ConflictException("Historical imported contracts are immutable");
  if(contract.status!=="draft")throw new ConflictException("Only a draft online contract can be activated or cancelled");
  const employee=await employeeRepo.findOne({where:{id:contract.employeeId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}}),type=await typeRepo.findOne({where:{id:contract.contractTypeId,...scope,isDeleted:false}});
  if(!employee||!type)throw new ConflictException("Contract references are unavailable");
  if(dto.action==="activate"&&await contractRepo.exists({where:{...scope,employeeId:contract.employeeId,status:"active",isDeleted:false}}))throw new ConflictException("Employee already has an active contract");
  contract.status=dto.action==="activate"?"active":"cancelled";contract.updateBy=actor.sub;
  return this.projectContract(await contractRepo.save(contract),employee,type);
 });}
 async createContractChange(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:CreateHrContractChangeDto){
  if(dto.newEndDate&&dto.newEndDate<dto.newStartDate)throw new BadRequestException("Contract change end date cannot precede start date");
  try{return await this.dataSource.transaction(async manager=>{
   const contractRepo=manager.getRepository(HrContractEntity),changeRepo=manager.getRepository(HrContractChangeEntity);
   const contract=await contractRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
   if(!contract)throw new NotFoundException("Contract not found");
   if(contract.isHistoricalImport)throw new ConflictException("Historical imported contracts are immutable");
   if(contract.status!=="active")throw new ConflictException("Only an active online contract can create a change draft");
   if(dto.changeType==="renewal"&&contract.endDate&&dto.newStartDate<=contract.endDate)throw new BadRequestException("Renewal must start after the current contract ends");
   if(dto.changeType==="termination"&&!dto.newEndDate)throw new BadRequestException("Termination requires an end date");
   if(dto.changeType==="termination"&&contract.startDate&&dto.newEndDate&&dto.newEndDate<contract.startDate)throw new BadRequestException("Termination cannot precede the contract start date");
   if(await changeRepo.exists({where:{...scope,contractId:id,status:"draft",isDeleted:false}}))throw new ConflictException("Contract already has a pending change draft");
   const latest=await changeRepo.findOne({where:{...scope,contractId:id,isDeleted:false},order:{sequenceNo:"DESC"}});
   const row=await changeRepo.save(changeRepo.create({...scope,contractId:id,sequenceNo:(latest?.sequenceNo??0)+1,changeType:dto.changeType,previousStartDate:contract.startDate,previousEndDate:contract.endDate,newStartDate:dto.newStartDate,newEndDate:dto.newEndDate??null,signedAt:null,status:"draft",isHistoricalImport:false,sourceSnapshot:{},remark:dto.remark??null,createBy:actor.sub,updateBy:actor.sub}));
   return this.projectContractChange(row);
  });}catch(error){if((error as {code?:string}).code==="23505")throw new ConflictException("Contract already has a pending change draft");throw error;}
 }
 async actContractChange(scope:TenantParkScope,actor:JwtPrincipal,contractId:string,changeId:string,dto:HrContractChangeActionDto){return this.dataSource.transaction(async manager=>{
  const contractRepo=manager.getRepository(HrContractEntity),changeRepo=manager.getRepository(HrContractChangeEntity);
  const contract=await contractRepo.findOne({where:{id:contractId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
  if(!contract)throw new NotFoundException("Contract not found");
  if(contract.isHistoricalImport)throw new ConflictException("Historical imported contracts are immutable");
  const change=await changeRepo.findOne({where:{id:changeId,contractId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});
  if(!change)throw new NotFoundException("Contract change not found");
  if(change.isHistoricalImport)throw new ConflictException("Historical imported contract changes are immutable");
  if(change.status!=="draft")throw new ConflictException("Only a draft contract change can be applied or cancelled");
  if(dto.action==="apply"){
   if(contract.status!=="active")throw new ConflictException("Only an active online contract can apply a change");
   if(change.changeType==="termination"){contract.endDate=change.newEndDate;contract.status="terminated";}else{contract.startDate=change.newStartDate;contract.endDate=change.newEndDate;}
   contract.updateBy=actor.sub;await contractRepo.save(contract);change.status="effective";change.signedAt=new Date();
  }else change.status="cancelled";
  change.updateBy=actor.sub;return this.projectContractChange(await changeRepo.save(change));
 });}
 async listMyContracts(scope:TenantParkScope,actor:JwtPrincipal,q:HrContractListQueryDto){
  const employee=await this.myEmployee(scope,actor);
  const result=await this.findContracts(scope,q,[employee.id]);
  await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.contract",action:"读取本人劳动合同",bizType:"hr_employee",bizId:employee.id,path:"/hr/contracts/me",fieldGroups:["employment_contract"],projection:"self",itemCount:result.items.length});
  return {...result,items:result.items.map(row=>this.projectSelfContract(row))};
 }
 async contractDetail(scope:TenantParkScope,actor:JwtPrincipal,id:string){
  const accessibleIds=await this.contractEmployeeIds(scope,actor);
  const row=await this.contracts.findOne({where:{id,...scope,isDeleted:false}});
  if(!row||(accessibleIds!==null&&!accessibleIds.includes(row.employeeId)))throw new NotFoundException("Contract not found");
  const [employee,type,changes]=await Promise.all([
   this.employees.findOne({where:{id:row.employeeId,...scope,isDeleted:false}}),
   this.contractTypes.findOne({where:{id:row.contractTypeId,...scope,isDeleted:false}}),
   this.contractChanges.find({where:{contractId:id,...scope,isDeleted:false},order:{sequenceNo:"ASC"}})
  ]);
  if(!employee||!type)throw new NotFoundException("Contract not found");
  const access=resolveHrContractAccessScope(actor),main=this.projectContract(row,employee,type);
  const result={...(access.self&&!access.park&&!access.managedOrgTree?this.projectSelfContract(main):main),changes:changes.map(change=>this.projectContractChange(change))};
  await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.contract",action:"读取劳动合同详情",bizType:"hr_contract",bizId:id,path:"/hr/contracts/:id",fieldGroups:["employment_contract"],projection:access.park?"park":access.managedOrgTree?"team":"self",itemCount:1});
  return result;
 }

 private async findContracts(scope:TenantParkScope,q:HrContractListQueryDto,employeeIds:string[]|null):Promise<PaginatedResult<ReturnType<HrService["projectContractRaw"]>>>{
  if(employeeIds!==null&&!employeeIds.length)return {items:[],total:0,page:q.page,page_size:q.page_size};
  const query=this.contracts.createQueryBuilder("contract")
   .innerJoin(HrEmployeeEntity,"employee","employee.id=contract.employee_id AND employee.tenant_id=contract.tenant_id AND employee.park_id=contract.park_id AND employee.is_deleted=false")
   .innerJoin(HrContractTypeEntity,"type","type.id=contract.contract_type_id AND type.tenant_id=contract.tenant_id AND type.park_id=contract.park_id AND type.is_deleted=false")
   .where("contract.tenant_id=:tenantId AND contract.park_id=:parkId AND contract.is_deleted=false",scope);
  if(employeeIds!==null)query.andWhere("contract.employee_id IN (:...employeeIds)",{employeeIds});
  if(q.status)query.andWhere("contract.status=:status",{status:q.status});
  if(q.expiry_from)query.andWhere("contract.end_date>=:expiryFrom",{expiryFrom:q.expiry_from});
  if(q.expiry_to)query.andWhere("contract.end_date<=:expiryTo",{expiryTo:q.expiry_to});
  if(q.keyword)query.andWhere("(employee.full_name ILIKE :keyword OR employee.employee_code ILIKE :keyword OR contract.contract_no ILIKE :keyword)",{keyword:`%${q.keyword}%`});
  const total=await query.getCount();
  const items=await query.clone().select([
   "contract.id AS id","contract.employee_id AS employee_id","employee.employee_code AS employee_code","employee.full_name AS employee_name","contract.contract_no AS contract_no","contract.contract_type_id AS contract_type_id","type.type_name AS contract_type_name","contract.start_date AS start_date","contract.end_date AS end_date","contract.probation_end_date AS probation_end_date","contract.status AS status","contract.is_historical_import AS is_historical_import"
  ]).orderBy("contract.end_date","ASC","NULLS LAST").addOrderBy("contract.contract_no","ASC").offset((q.page-1)*q.page_size).limit(q.page_size).getRawMany<Record<string,unknown>>();
  return {items:items.map(row=>this.projectContractRaw(row)),total,page:q.page,page_size:q.page_size};
 }
 private async contractEmployeeIds(scope:TenantParkScope,actor:JwtPrincipal):Promise<string[]|null>{
  const access=resolveHrContractAccessScope(actor);
  if(access.park)return null;
  const ids:string[]=[];
  if(access.managedOrgTree)ids.push(...await this.managedEmployeeIds(scope,actor));
  if(access.self)ids.push((await this.myEmployee(scope,actor)).id);
  return [...new Set(ids)];
 }
 private projectContract(row:HrContractEntity,employee:HrEmployeeEntity,type:HrContractTypeEntity){return {id:row.id,employeeId:row.employeeId,employeeCode:employee.employeeCode,employeeName:employee.fullName,contractNo:row.contractNo,contractTypeId:row.contractTypeId,contractTypeName:type.typeName,startDate:row.startDate,endDate:row.endDate,probationEndDate:row.probationEndDate,status:row.status,isHistoricalImport:row.isHistoricalImport};}
 private projectContractChange(row:HrContractChangeEntity){return {id:row.id,sequenceNo:row.sequenceNo,changeType:row.changeType,previousStartDate:row.previousStartDate,previousEndDate:row.previousEndDate,newStartDate:row.newStartDate,newEndDate:row.newEndDate,status:row.status,isHistoricalImport:row.isHistoricalImport};}
 private projectSelfContract(row:ReturnType<HrService["projectContractRaw"]>|ReturnType<HrService["projectContract"]>){return {id:row.id,contractNo:row.contractNo,contractTypeName:row.contractTypeName,startDate:row.startDate,endDate:row.endDate,status:row.status,isHistoricalImport:row.isHistoricalImport};}
 private projectContractRaw(row:Record<string,unknown>){return {id:String(row.id),employeeId:String(row.employee_id),employeeCode:String(row.employee_code),employeeName:String(row.employee_name),contractNo:String(row.contract_no),contractTypeId:String(row.contract_type_id),contractTypeName:String(row.contract_type_name),startDate:row.start_date===null?null:String(row.start_date),endDate:row.end_date===null?null:String(row.end_date),probationEndDate:row.probation_end_date===null?null:String(row.probation_end_date),status:String(row.status),isHistoricalImport:Boolean(row.is_historical_import)};}

 async listGoalCycles(scope:TenantParkScope){return this.goalCycles.find({where:{...scope,isDeleted:false},order:{startDate:"DESC"}});}
 async createGoalCycle(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrGoalCycleDto){if(dto.endDate<dto.startDate)throw new BadRequestException("Goal cycle end date must not precede start date");if(await this.goalCycles.exists({where:{...scope,cycleCode:dto.cycleCode,isDeleted:false}}))throw new ConflictException("Goal cycle code already exists");return this.goalCycles.save(this.goalCycles.create({...scope,...dto,status:"draft",createBy:actor.sub,updateBy:actor.sub}));}
 async listGoals(scope:TenantParkScope,actor:JwtPrincipal,selfOnly=false){const employee=selfOnly?await this.myEmployee(scope,actor):null;const rows=await this.goals.find({where:{...scope,isDeleted:false,...(employee?{ownerEmployeeId:employee.id}:{})},order:{createTime:"ASC"}});return rows.map(projectHrGoal);}
 async createGoal(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrGoalDto){
  const cycle=await this.goalCycles.findOne({where:{id:dto.cycleId,...scope,isDeleted:false}});if(!cycle)throw new BadRequestException("Goal cycle is unavailable in current scope");
  if(dto.startDate<cycle.startDate||dto.dueDate>cycle.endDate||dto.dueDate<dto.startDate)throw new BadRequestException("Goal dates must stay inside the cycle");
  let parent:HrGoalEntity|null=null;if(dto.parentGoalId){parent=await this.goals.findOne({where:{id:dto.parentGoalId,...scope,isDeleted:false}});if(!parent||parent.cycleId!==dto.cycleId)throw new BadRequestException("Parent goal is unavailable in this cycle");}
  const order={group:0,department:1,employee:2};if(parent&&order[dto.goalLevel as keyof typeof order]!==order[parent.goalLevel as keyof typeof order]+1)throw new BadRequestException("Goals must cascade from group to department to employee");
  if(parent){const weightRow=await this.goals.createQueryBuilder("g").where("g.tenant_id=:tenantId AND g.park_id=:parkId AND g.parent_goal_id=:parentId AND g.is_deleted=false",{...scope,parentId:parent.id}).select("COALESCE(SUM(g.weight),0)","total").getRawOne<{total:string}>();if(Number(weightRow?.total??0)+dto.weight>1.0000001)throw new BadRequestException("Child goal weights cannot exceed 100 percent");}
  if(dto.goalLevel==="group"&&(dto.ownerOrgId||dto.ownerEmployeeId))throw new BadRequestException("Group goal must not have an organization or employee owner");
  if(dto.goalLevel==="department"){if(!dto.ownerOrgId||dto.ownerEmployeeId)throw new BadRequestException("Department goal requires an organization owner");await this.mustOrg(scope,dto.ownerOrgId);}
  if(dto.goalLevel==="employee"){if(!dto.ownerEmployeeId||dto.ownerOrgId)throw new BadRequestException("Employee goal requires an employee owner");await this.detailEmployee(scope,dto.ownerEmployeeId);}
  return this.goals.save(this.goals.create({...scope,...dto,parentGoalId:dto.parentGoalId??null,ownerOrgId:dto.ownerOrgId??null,ownerEmployeeId:dto.ownerEmployeeId??null,weight:String(dto.weight),metricName:dto.metricName??null,targetValue:dto.targetValue===undefined?null:String(dto.targetValue),currentValue:null,unit:dto.unit??null,progress:"0",status:"draft",createBy:actor.sub,updateBy:actor.sub}));
 }
 async goalCheckins(scope:TenantParkScope,actor:JwtPrincipal,id:string){const employee=await this.myEmployee(scope,actor);if(!await this.goals.exists({where:{id,...scope,ownerEmployeeId:employee.id,isDeleted:false}}))throw new NotFoundException("Goal not found");return this.goalCheckinRepo.find({where:{...scope,goalId:id,isDeleted:false},order:{createTime:"DESC"}});}
 async createGoalCheckin(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:CreateHrGoalCheckinDto){return this.dataSource.transaction(async manager=>{const goalRepo=manager.getRepository(HrGoalEntity),checkinRepo=manager.getRepository(HrGoalCheckinEntity);const goal=await goalRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!goal)throw new NotFoundException("Goal not found");if(goal.status==="completed"||goal.status==="cancelled")throw new BadRequestException("Closed goal cannot accept progress check-ins");if(goal.ownerEmployeeId){const employee=await manager.getRepository(HrEmployeeEntity).findOne({where:{id:goal.ownerEmployeeId,...scope,userId:actor.sub,isDeleted:false}});if(!employee)throw new BadRequestException("Employee goals can only be updated by their owner");}goal.progress=String(dto.progress);goal.currentValue=dto.currentValue===undefined?goal.currentValue:String(dto.currentValue);goal.status=dto.progress===1?"completed":"active";goal.updateBy=actor.sub;await goalRepo.save(goal);return checkinRepo.save(checkinRepo.create({...scope,goalId:id,progress:String(dto.progress),currentValue:dto.currentValue===undefined?null:String(dto.currentValue),summary:dto.summary,risks:dto.risks??null,evidenceFileId:dto.evidenceFileId??null,createBy:actor.sub,updateBy:actor.sub}));});}
 async myWorkReports(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);const rows=await this.reports.find({where:{...scope,employeeId:employee.id,isDeleted:false},order:{periodStart:"DESC"}});return rows.map(projectHrWorkReport);}
 async createMyWorkReport(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrWorkReportDto){
  const employee=await this.myEmployee(scope,actor);if(dto.periodEnd<dto.periodStart)throw new BadRequestException("Report end date must not precede start date");
  if(await this.reports.exists({where:{...scope,employeeId:employee.id,reportType:dto.reportType,periodStart:dto.periodStart,isDeleted:false}}))throw new ConflictException("A report already exists for this period");
  return this.dataSource.transaction(async manager=>{const repo=manager.getRepository(HrWorkReportEntity),linkRepo=manager.getRepository(HrWorkReportGoalEntity);const report=await repo.save(repo.create({...scope,employeeId:employee.id,reportType:dto.reportType,periodStart:dto.periodStart,periodEnd:dto.periodEnd,completedWork:dto.completedWork,nextPlan:dto.nextPlan??null,risks:dto.risks??null,collaborationNeeds:dto.collaborationNeeds??null,hours:dto.hours===undefined?null:String(dto.hours),status:"submitted",reviewerEmployeeId:employee.managerEmployeeId,reviewComment:null,submittedAt:new Date(),reviewedAt:null,createBy:actor.sub,updateBy:actor.sub}));for(const goalId of dto.goalIds??[]){const goal=await manager.getRepository(HrGoalEntity).findOne({where:{id:goalId,...scope,ownerEmployeeId:employee.id,isDeleted:false}});if(!goal)throw new BadRequestException("Work report can only link the employee's own goals");await linkRepo.save(linkRepo.create({...scope,reportId:report.id,goalId,progressDelta:null,createBy:actor.sub,updateBy:actor.sub}));}await this.notifications.publishWorkReportSubmitted(scope,actor,report,manager);return report;});
 }
 async teamWorkReports(scope:TenantParkScope,actor:JwtPrincipal){const ids=await this.managedEmployeeIds(scope,actor);if(!ids.length)return [];const rows=await this.reports.createQueryBuilder("r").where("r.tenant_id=:tenantId AND r.park_id=:parkId AND r.is_deleted=false",scope).andWhere("r.employee_id IN (:...ids)",{ids}).orderBy("r.period_start","DESC").getMany();return rows.map(projectHrWorkReport);}
 async reviewWorkReport(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ReviewHrWorkReportDto){const managerEmployee=await this.myEmployee(scope,actor);const report=await this.reports.findOne({where:{id,...scope,isDeleted:false}});if(!report)throw new NotFoundException("Work report not found");const managedIds=await this.managedEmployeeIds(scope,actor);if(!managedIds.includes(report.employeeId))throw new ForbiddenException("Work report is outside the manager organization scope");if(report.status!=="submitted")throw new BadRequestException("Only submitted reports can be reviewed");return this.dataSource.transaction(async manager=>{const repo=manager.getRepository(HrWorkReportEntity);report.status=dto.action;report.reviewComment=dto.comment;report.reviewerEmployeeId=managerEmployee.id;report.reviewedAt=new Date();report.updateBy=actor.sub;const saved=await repo.save(report);await this.notifications.publishWorkReportReviewed(scope,actor,saved,manager);return saved;});}

 async listPerformanceCycles(scope:TenantParkScope){return this.performanceCycles.find({where:{...scope,isDeleted:false},order:{startDate:"DESC"}});}
 async createPerformanceCycle(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPerformanceCycleDto){if(dto.endDate<dto.startDate)throw new BadRequestException("Performance cycle end date must not precede start date");if(await this.performanceCycles.exists({where:{...scope,cycleCode:dto.cycleCode,isDeleted:false}}))throw new ConflictException("Performance cycle code already exists");return this.performanceCycles.save(this.performanceCycles.create({...scope,...dto,selfReviewEnd:dto.selfReviewEnd??null,managerReviewEnd:dto.managerReviewEnd??null,calibrationEnd:dto.calibrationEnd??null,status:"active",createBy:actor.sub,updateBy:actor.sub}));}
 async createPerformancePlan(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPerformancePlanDto){const cycle=await this.performanceCycles.findOne({where:{id:dto.cycleId,...scope,isDeleted:false}});if(!cycle||cycle.status!=="active")throw new BadRequestException("Performance cycle is unavailable");const employee=await this.detailEmployee(scope,dto.employeeId);return this.dataSource.transaction(async manager=>{const planRepo=manager.getRepository(HrPerformancePlanEntity),itemRepo=manager.getRepository(HrPerformanceItemEntity);if(await planRepo.exists({where:{...scope,cycleId:dto.cycleId,employeeId:dto.employeeId,isDeleted:false}}))throw new ConflictException("Employee already has a plan in this cycle");const goals=await manager.getRepository(HrGoalEntity).createQueryBuilder("g").where("g.tenant_id=:tenantId AND g.park_id=:parkId AND g.owner_employee_id=:employeeId AND g.is_deleted=false",{...scope,employeeId:dto.employeeId}).andWhere("g.status IN ('active','completed') AND g.start_date<=:endDate AND g.due_date>=:startDate",{startDate:cycle.startDate,endDate:cycle.endDate}).orderBy("g.create_time","ASC").getMany();if(!goals.length)throw new BadRequestException("Employee has no active goals in this performance cycle");const totalWeight=goals.reduce((sum,goal)=>sum+Number(goal.weight),0);if(totalWeight>1.0000001)throw new BadRequestException("Performance goal weights cannot exceed 100 percent");const plan=await planRepo.save(planRepo.create({...scope,cycleId:dto.cycleId,employeeId:dto.employeeId,managerEmployeeId:employee.managerEmployeeId,status:"self_review",selfScore:null,managerScore:null,calibratedScore:null,finalScore:null,selfSummary:null,managerComment:null,calibrationComment:null,confirmedAt:null,createBy:actor.sub,updateBy:actor.sub}));for(const goal of goals)await itemRepo.save(itemRepo.create({...scope,planId:plan.id,goalId:goal.id,itemName:goal.goalName,weight:goal.weight,targetSnapshot:{metricName:goal.metricName,targetValue:goal.targetValue,unit:goal.unit,dueDate:goal.dueDate},selfScore:null,managerScore:null,finalScore:null,comment:null,createBy:actor.sub,updateBy:actor.sub}));return plan;});}
 async myPerformancePlans(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);const rows=await this.performancePlans.find({where:{...scope,employeeId:employee.id,isDeleted:false},order:{createTime:"DESC"}});return rows.map(row=>projectHrPerformancePlan(row,"self"));}
 async selfReviewPerformance(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ScoreHrPerformanceDto){const employee=await this.myEmployee(scope,actor);const plan=await this.performancePlans.findOne({where:{id,...scope,employeeId:employee.id,isDeleted:false}});if(!plan)throw new NotFoundException("Performance plan not found");if(plan.status!=="self_review")throw new BadRequestException("Plan is not in self review");plan.selfScore=String(dto.score);plan.selfSummary=dto.comment;plan.status="manager_review";plan.updateBy=actor.sub;return this.performancePlans.save(plan);}
 async managerPerformancePlans(scope:TenantParkScope,actor:JwtPrincipal){const ids=await this.managedEmployeeIds(scope,actor);if(!ids.length)return [];const rows=await this.performancePlans.createQueryBuilder("p").where("p.tenant_id=:tenantId AND p.park_id=:parkId AND p.is_deleted=false",scope).andWhere("p.employee_id IN (:...ids)",{ids}).orderBy("p.create_time","DESC").getMany();return rows.map(row=>projectHrPerformancePlan(row,"manager"));}
 async managerReviewPerformance(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ScoreHrPerformanceDto){const plan=await this.performancePlans.findOne({where:{id,...scope,isDeleted:false}});if(!plan)throw new NotFoundException("Performance plan not found");const managedIds=await this.managedEmployeeIds(scope,actor);if(!managedIds.includes(plan.employeeId))throw new ForbiddenException("Performance plan is outside the manager organization scope");if(plan.status!=="manager_review")throw new BadRequestException("Plan is not in manager review");plan.managerScore=String(dto.score);plan.managerComment=dto.comment;plan.status="calibrating";plan.updateBy=actor.sub;return this.performancePlans.save(plan);}
 async calibratePerformance(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:ScoreHrPerformanceDto){const plan=await this.performancePlans.findOne({where:{id,...scope,isDeleted:false}});if(!plan)throw new NotFoundException("Performance plan not found");if(plan.status!=="calibrating")throw new BadRequestException("Plan is not ready for calibration");plan.calibratedScore=String(dto.score);plan.finalScore=String(dto.score);plan.calibrationComment=dto.comment;plan.status="confirmed";plan.confirmedAt=new Date();plan.updateBy=actor.sub;return this.performancePlans.save(plan);}
 async createFeedbackCycle(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrFeedbackCycleDto){if(!await this.performanceCycles.exists({where:{id:dto.performanceCycleId,...scope,isDeleted:false}}))throw new BadRequestException("Performance cycle is unavailable");return this.feedbackCycles.save(this.feedbackCycles.create({...scope,...dto,anonymous:dto.anonymous??true,minimumAnonymousResponses:dto.minimumAnonymousResponses??3,status:"active",createBy:actor.sub,updateBy:actor.sub}));}
 async listFeedbackCycles(scope:TenantParkScope){return this.feedbackCycles.find({where:{...scope,isDeleted:false},order:{createTime:"DESC"}});}
 async createFeedbackAssignment(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrFeedbackAssignmentDto){await Promise.all([this.detailEmployee(scope,dto.subjectEmployeeId),this.detailEmployee(scope,dto.reviewerEmployeeId)]);if(dto.relationType==="self"&&dto.subjectEmployeeId!==dto.reviewerEmployeeId)throw new BadRequestException("Self feedback must be assigned to the subject");if(dto.relationType!=="self"&&dto.subjectEmployeeId===dto.reviewerEmployeeId)throw new BadRequestException("Non-self feedback requires another reviewer");if(!await this.feedbackCycles.exists({where:{id:dto.feedbackCycleId,...scope,status:"active",isDeleted:false}}))throw new BadRequestException("Feedback cycle is unavailable");if(await this.feedbackAssignments.exists({where:{...scope,feedbackCycleId:dto.feedbackCycleId,subjectEmployeeId:dto.subjectEmployeeId,reviewerEmployeeId:dto.reviewerEmployeeId,isDeleted:false}}))throw new ConflictException("Feedback assignment already exists");return this.feedbackAssignments.save(this.feedbackAssignments.create({...scope,...dto,weight:String(dto.weight),status:"pending",submittedAt:null,createBy:actor.sub,updateBy:actor.sub}));}
 async myFeedbackAssignments(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);const rows=await this.feedbackAssignments.find({where:{...scope,reviewerEmployeeId:employee.id,isDeleted:false},order:{createTime:"DESC"}});return rows.map(projectHrFeedbackAssignment);}
 async submitFeedback(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:SubmitHrFeedbackDto){const employee=await this.myEmployee(scope,actor);return this.dataSource.transaction(async manager=>{const assignmentRepo=manager.getRepository(HrFeedbackAssignmentEntity),responseRepo=manager.getRepository(HrFeedbackResponseEntity);const assignment=await assignmentRepo.findOne({where:{id,...scope,reviewerEmployeeId:employee.id,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!assignment)throw new NotFoundException("Feedback assignment not found");if(assignment.status!=="pending")throw new ConflictException("Feedback has already been submitted");const response=await responseRepo.save(responseRepo.create({...scope,assignmentId:id,score:String(dto.score),strengths:dto.strengths??null,improvements:dto.improvements??null,submittedAt:new Date(),createBy:actor.sub,updateBy:actor.sub}));assignment.status="submitted";assignment.submittedAt=new Date();assignment.updateBy=actor.sub;await assignmentRepo.save(assignment);return response;});}
 async feedbackResult(scope:TenantParkScope,subjectEmployeeId:string,feedbackCycleId:string){const cycle=await this.feedbackCycles.findOne({where:{id:feedbackCycleId,...scope,isDeleted:false}});if(!cycle)throw new NotFoundException("Feedback cycle not found");const rows=await this.feedbackResponses.createQueryBuilder("r").innerJoin(HrFeedbackAssignmentEntity,"a","a.id=r.assignment_id AND a.tenant_id=r.tenant_id AND a.park_id=r.park_id AND a.is_deleted=false").where("r.tenant_id=:tenantId AND r.park_id=:parkId AND r.is_deleted=false",scope).andWhere("a.subject_employee_id=:subjectEmployeeId",{subjectEmployeeId}).andWhere("a.feedback_cycle_id=:feedbackCycleId",{feedbackCycleId}).select("COUNT(*)","count").addSelect("AVG(r.score)","average").getRawOne<{count:string;average:string|null}>();const count=Number(rows?.count??0);if(cycle.anonymous&&count<cycle.minimumAnonymousResponses)throw new ForbiddenException("Anonymous result threshold has not been reached");return {subjectEmployeeId,feedbackCycleId,responseCount:count,averageScore:rows?.average===null?null:Number(rows?.average)};}
 async listCompensationPlans(scope:TenantParkScope){return this.compensationPlans.find({where:{...scope,isDeleted:false},order:{effectiveFrom:"DESC"}});}
 async createCompensationPlan(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrCompensationPlanDto){if(dto.effectiveTo&&dto.effectiveTo<dto.effectiveFrom)throw new BadRequestException("Compensation plan dates are invalid");if(await this.compensationPlans.exists({where:{...scope,planCode:dto.planCode,isDeleted:false}}))throw new ConflictException("Compensation plan code already exists");return this.compensationPlans.save(this.compensationPlans.create({...scope,...dto,effectiveTo:dto.effectiveTo??null,status:"active",currency:"CNY",createBy:actor.sub,updateBy:actor.sub}));}
 async assignCompensation(scope:TenantParkScope,actor:JwtPrincipal,dto:AssignHrCompensationDto){await this.detailEmployee(scope,dto.employeeId);if(!await this.compensationPlans.exists({where:{id:dto.planId,...scope,status:"active",isDeleted:false}}))throw new BadRequestException("Compensation plan is unavailable");if(dto.effectiveTo&&dto.effectiveTo<dto.effectiveFrom)throw new BadRequestException("Compensation dates are invalid");return this.employeeCompensations.save(this.employeeCompensations.create({...scope,...dto,effectiveTo:dto.effectiveTo??null,baseSalary:normalizeHrMoney(dto.baseSalary,"baseSalary"),allowanceAmount:normalizeHrMoney(dto.allowanceAmount??"0","allowanceAmount"),variableTarget:normalizeHrMoney(dto.variableTarget??"0","variableTarget"),status:"active",approvedBy:actor.sub,createBy:actor.sub,updateBy:actor.sub}));}
 async listPayrollPeriods(scope:TenantParkScope){return this.payrollPeriods.find({where:{...scope,isDeleted:false},order:{periodMonth:"DESC"}});}
 async createPayrollPeriod(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPayrollPeriodDto){const month=`${dto.periodMonth.slice(0,7)}-01`;if(dto.periodMonth!==month)throw new BadRequestException("Payroll period month must be the first day of month");if(dto.endDate<dto.startDate)throw new BadRequestException("Payroll period dates are invalid");if(await this.payrollPeriods.exists({where:{...scope,periodMonth:month,isDeleted:false}}))throw new ConflictException("Payroll period already exists");return this.payrollPeriods.save(this.payrollPeriods.create({...scope,...dto,periodMonth:month,status:"open",createBy:actor.sub,updateBy:actor.sub}));}
 async listPayrollRuns(scope:TenantParkScope,actor:JwtPrincipal){const rows=await this.payrollRuns.find({where:{...scope,isDeleted:false},order:{createTime:"DESC"}});const projected=rows.map(projectHrPayrollRun);await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.payroll_run",action:"读取工资批次",bizType:"hr_payroll_run",bizId:null,path:"/hr/payroll/runs",fieldGroups:["financial","compensation"],projection:"admin",itemCount:projected.length});return projected;}
 async payrollRunPayslips(scope:TenantParkScope,actor:JwtPrincipal,runId:string){if(!await this.payrollRuns.exists({where:{id:runId,...scope,isDeleted:false}}))throw new NotFoundException("Payroll run not found");const rows=await this.payslips.find({where:{...scope,runId,isDeleted:false},order:{createTime:"ASC"}});const projected=rows.map(row=>projectHrPayslip(row,false));await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.payslip",action:"读取工资批次明细",bizType:"hr_payroll_run",bizId:runId,path:"/hr/payroll/runs/:id/payslips",fieldGroups:["financial","compensation"],projection:"admin",itemCount:projected.length});return projected;}
 async createPayrollRun(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrPayrollRunDto){return this.dataSource.transaction(async manager=>{const periodRepo=manager.getRepository(HrPayrollPeriodEntity),runRepo=manager.getRepository(HrPayrollRunEntity),slipRepo=manager.getRepository(HrPayslipEntity);const period=await periodRepo.findOne({where:{id:dto.periodId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!period||period.status!=="open")throw new BadRequestException("Payroll period is unavailable");if(dto.correctionOfRunId){const original=await runRepo.findOne({where:{id:dto.correctionOfRunId,...scope,periodId:dto.periodId,status:"confirmed",isDeleted:false}});if(!original)throw new BadRequestException("Correction must reference a confirmed run");}else if(await runRepo.exists({where:{...scope,periodId:dto.periodId,correctionOfRunId:IsNull(),isDeleted:false}}))throw new ConflictException("Base payroll run already exists");const latest=await runRepo.findOne({where:{...scope,periodId:dto.periodId,isDeleted:false},order:{runNo:"DESC"}});const run=await runRepo.save(runRepo.create({...scope,periodId:dto.periodId,runNo:(latest?.runNo??0)+1,correctionOfRunId:dto.correctionOfRunId??null,status:"draft",employeeCount:0,grossTotal:"0",deductionTotal:"0",netTotal:"0",calculatedAt:null,reviewedAt:null,confirmedAt:null,confirmedBy:null,createBy:actor.sub,updateBy:actor.sub}));const employees=await manager.getRepository(HrEmployeeEntity).find({where:{...scope,employmentStatus:"active",isDeleted:false}});let gross=0n;for(const employee of employees){const comp=await manager.getRepository(HrEmployeeCompensationEntity).createQueryBuilder("c").where("c.tenant_id=:tenantId AND c.park_id=:parkId AND c.employee_id=:employeeId AND c.is_deleted=false AND c.status='active'",{...scope,employeeId:employee.id}).andWhere("c.effective_from<=:endDate AND (c.effective_to IS NULL OR c.effective_to>=:startDate)",{endDate:period.endDate,startDate:period.startDate}).orderBy("c.effective_from","DESC").getOne();if(!comp)continue;const amount=hrMoneyToCents(comp.baseSalary)+hrMoneyToCents(comp.allowanceAmount)+hrMoneyToCents(comp.variableTarget);gross+=amount;await slipRepo.save(slipRepo.create({...scope,runId:run.id,employeeId:employee.id,compensationSnapshot:{planId:comp.planId,effectiveFrom:comp.effectiveFrom,baseSalary:comp.baseSalary,allowanceAmount:comp.allowanceAmount,variableTarget:comp.variableTarget},grossAmount:hrCentsToMoney(amount),deductionAmount:"0.00",personalTax:"0.00",netAmount:hrCentsToMoney(amount),status:"draft",createBy:actor.sub,updateBy:actor.sub}));}run.employeeCount=await slipRepo.count({where:{...scope,runId:run.id,isDeleted:false}});run.grossTotal=hrCentsToMoney(gross);run.netTotal=hrCentsToMoney(gross);run.status="calculated";run.calculatedAt=new Date();return runRepo.save(run);});}
 async transitionPayrollRun(scope:TenantParkScope,actor:JwtPrincipal,id:string,action:"review"|"confirm"){return this.dataSource.transaction(async manager=>{const runRepo=manager.getRepository(HrPayrollRunEntity),slipRepo=manager.getRepository(HrPayslipEntity);const run=await runRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!run)throw new NotFoundException("Payroll run not found");if(action==="review"&&run.status!=="calculated")throw new ConflictException("Only calculated payroll can enter review");if(action==="confirm"&&run.status!=="reviewing")throw new ConflictException("Only reviewed payroll can be confirmed");run.status=action==="review"?"reviewing":"confirmed";if(action==="review")run.reviewedAt=new Date();else{run.confirmedAt=new Date();run.confirmedBy=actor.sub;await slipRepo.update({runId:id,...scope,isDeleted:false},{status:"confirmed",updateBy:actor.sub});}run.updateBy=actor.sub;return runRepo.save(run);});}
 async adjustPayslip(scope:TenantParkScope,actor:JwtPrincipal,runId:string,payslipId:string,dto:AdjustHrPayslipDto){return this.dataSource.transaction(async manager=>{const runRepo=manager.getRepository(HrPayrollRunEntity),slipRepo=manager.getRepository(HrPayslipEntity);const run=await runRepo.findOne({where:{id:runId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!run)throw new NotFoundException("Payroll run not found");if(!["calculated","reviewing"].includes(run.status))throw new BadRequestException("Confirmed payroll cannot be adjusted; create a correction run");const slip=await slipRepo.findOne({where:{id:payslipId,runId,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!slip)throw new NotFoundException("Payslip not found");const deduction=hrMoneyToCents(dto.deductionAmount,"deductionAmount");const tax=hrMoneyToCents(dto.personalTax,"personalTax");const net=hrMoneyToCents(slip.grossAmount)-deduction-tax;if(net<0n)throw new BadRequestException("Deductions and tax cannot exceed gross amount");slip.deductionAmount=hrCentsToMoney(deduction);slip.personalTax=hrCentsToMoney(tax);slip.netAmount=hrCentsToMoney(net);slip.remark=dto.reason;slip.updateBy=actor.sub;await slipRepo.save(slip);const totals=await slipRepo.createQueryBuilder("s").where("s.tenant_id=:tenantId AND s.park_id=:parkId AND s.run_id=:runId AND s.is_deleted=false",{...scope,runId}).select("COALESCE(SUM(s.gross_amount),0)","gross").addSelect("COALESCE(SUM(s.deduction_amount+s.personal_tax),0)","deduction").addSelect("COALESCE(SUM(s.net_amount),0)","net").getRawOne<{gross:string;deduction:string;net:string}>();run.grossTotal=normalizeHrMoney(totals?.gross??"0","grossTotal");run.deductionTotal=normalizeHrMoney(totals?.deduction??"0","deductionTotal");run.netTotal=normalizeHrMoney(totals?.net??"0","netTotal");run.updateBy=actor.sub;await runRepo.save(run);return slip;});}
 async myPayslips(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);const rows=await this.payslips.find({where:{...scope,employeeId:employee.id,status:"confirmed",isDeleted:false},order:{createTime:"DESC"}});const projected=rows.map(row=>projectHrPayslip(row,true));await recordHrSensitiveRead(this.auditService,scope,actor,{resource:"hr.payslip",action:"读取本人工资条",bizType:"hr_employee",bizId:employee.id,path:"/hr/payslips/me",fieldGroups:["financial","compensation"],projection:"self",itemCount:projected.length});return projected;}
 async myApprovals(scope:TenantParkScope,actor:JwtPrincipal){const employee=await this.myEmployee(scope,actor);const rows=await this.approvalRequests.find({where:{...scope,applicantEmployeeId:employee.id,isDeleted:false},order:{createTime:"DESC"}});return rows.map(projectHrApproval);}
 async pendingApprovals(scope:TenantParkScope){const rows=await this.approvalRequests.find({where:{...scope,status:"submitted",isDeleted:false},order:{submittedAt:"ASC"}});return rows.map(projectHrApproval);}
 async createApproval(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateHrApprovalDto){const employee=await this.myEmployee(scope,actor);return this.approvalRequests.save(this.approvalRequests.create({...scope,requestNo:`HR-${Date.now()}-${crypto.randomUUID().slice(0,8)}`,requestType:dto.requestType,applicantEmployeeId:employee.id,subjectEmployeeId:employee.id,title:dto.title,payload:dto.payload,status:"draft",currentApproverId:null,submittedAt:null,completedAt:null,createBy:actor.sub,updateBy:actor.sub}));}
 async actApproval(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HrApprovalActionDto,reviewer:boolean){return this.dataSource.transaction(async manager=>{const requestRepo=manager.getRepository(HrApprovalRequestEntity),actionRepo=manager.getRepository(HrApprovalActionEntity);const request=await requestRepo.findOne({where:{id,...scope,isDeleted:false},lock:{mode:"pessimistic_write"}});if(!request)throw new NotFoundException("HR approval request not found");const employee=reviewer?null:await manager.getRepository(HrEmployeeEntity).findOne({where:{id:request.applicantEmployeeId,...scope,userId:actor.sub,isDeleted:false}});if(!reviewer&&!employee)throw new ForbiddenException("Only the applicant can change this request");const allowed=reviewer?{approve:["submitted"],return:["submitted"]}:{submit:["draft"],resubmit:["returned"],withdraw:["submitted"]};const expected=allowed[dto.action as keyof typeof allowed];if(!expected||!expected.includes(request.status))throw new BadRequestException("Approval action is not allowed from current status");const before=request.status;const next={submit:"submitted",resubmit:"submitted",withdraw:"withdrawn",approve:"approved",return:"returned"}[dto.action]!;request.status=next;if(next==="submitted")request.submittedAt=new Date();if(["approved","withdrawn"].includes(next))request.completedAt=new Date();else request.completedAt=null;request.currentApproverId=null;request.updateBy=actor.sub;await requestRepo.save(request);await actionRepo.save(actionRepo.create({...scope,requestId:id,action:dto.action,actorUserId:actor.sub,comment:dto.comment??null,beforeStatus:before,afterStatus:next,createBy:actor.sub,updateBy:actor.sub}));return request;});}

 private async validateEmployeeReferences(scope:TenantParkScope,dto:CreateHrEmployeeDto,selfId?:string){if(dto.userId&&!await this.users.exists({where:{id:dto.userId,...scope,isDeleted:false,isEnabled:true}}))throw new BadRequestException("User is unavailable in current scope");if(dto.primaryOrgId)await this.mustOrg(scope,dto.primaryOrgId);if(dto.positionId){const p=await this.positions.findOne({where:{id:dto.positionId,...scope,isDeleted:false,status:"enabled"}});if(!p)throw new BadRequestException("Position is unavailable in current scope");if(dto.primaryOrgId&&p.orgId!==dto.primaryOrgId)throw new BadRequestException("Position does not belong to primary organization");}if(dto.managerEmployeeId){if(dto.managerEmployeeId===selfId)throw new BadRequestException("Employee cannot manage themselves");if(!await this.employees.exists({where:{id:dto.managerEmployeeId,...scope,isDeleted:false}}))throw new BadRequestException("Manager employee is unavailable in current scope");}}
 private async mustOrg(scope:TenantParkScope,id:string){if(!await this.orgs.exists({where:{id,...scope,isDeleted:false,status:"enabled"}}))throw new BadRequestException("Organization is unavailable in current scope");}
 private async managedEmployeeIds(scope:TenantParkScope,actor:JwtPrincipal):Promise<string[]>{const manager=await this.myEmployee(scope,actor);const rows=await this.dataSource.query(HR_MANAGED_EMPLOYEE_IDS_SQL,[scope.tenantId,scope.parkId,actor.sub,manager.id]) as Array<{id:string}>;return rows.map(row=>row.id);}
 private eventSnapshot(row:HrEmployeeEntity){return {employeeCode:row.employeeCode,fullName:row.fullName,userId:row.userId,primaryOrgId:row.primaryOrgId,positionId:row.positionId,managerEmployeeId:row.managerEmployeeId,employmentType:row.employmentType,employmentStatus:row.employmentStatus,hireDate:row.hireDate,departureDate:row.departureDate};}
}
