BEGIN;SET LOCAL statement_timeout='45min';SET LOCAL lock_timeout='30s';
SELECT set_config('yuzhou.run', :'run', true),set_config('yuzhou.db', :'db', true),set_config('yuzhou.tenant', :'tenant', true),set_config('yuzhou.park', :'park', true),set_config('yuzhou.mode', :'mode', true),set_config('yuzhou.expected_rows', :'expected_rows', true),set_config('yuzhou.expected_items', :'expected_items', true),set_config('yuzhou.expected_net', :'expected_net', true),set_config('yuzhou.expected_closes', :'expected_closes', true),set_config('yuzhou.period_start', :'period_start', true),set_config('yuzhou.period_end', :'period_end', true);
DO $$BEGIN IF current_database()<>current_setting('yuzhou.db') OR current_database()!~'^jinhu_hr_migration_lab_'THEN RAISE EXCEPTION'unsafe target';END IF;IF current_setting('yuzhou.mode') NOT IN('hot_history','cold_archive','full_archive')THEN RAISE EXCEPTION'unsafe T4 load mode';END IF;IF EXISTS(SELECT 1 FROM migration_batch WHERE run_id=current_setting('yuzhou.run'))THEN RAISE EXCEPTION'duplicate run';END IF;END$$;
CREATE TEMP TABLE sm(j jsonb);CREATE TEMP TABLE si(j jsonb);CREATE TEMP TABLE sf(j jsonb);CREATE TEMP TABLE st(j jsonb);CREATE TEMP TABLE sc(j jsonb);CREATE TEMP TABLE sp_all(j jsonb);COPY sm FROM :'memberships_path';COPY si FROM :'items_path';COPY sf FROM :'formulas_path';COPY st FROM :'tax_path';COPY sc FROM :'closes_path';COPY sp_all FROM :'payslips_path';
DO $$BEGIN IF(SELECT count(*)FROM sm)<>647 OR(SELECT count(*)FROM si)<>711 OR(SELECT count(*)FROM sf)<>244 OR(SELECT count(*)FROM st)<>9 OR(SELECT count(*)FROM sc)<>1431 OR(SELECT sum((j->>'sourceMultiplicity')::int)FROM sp_all)<>46092 OR(SELECT min((j->'source'->>'year')::int)FROM sp_all)<>2010 OR(SELECT max((j->'source'->>'year')::int)FROM sp_all)<>2026 THEN RAISE EXCEPTION'full source audit count drift';END IF;END$$;
CREATE TEMP TABLE sp AS SELECT j FROM sp_all WHERE make_date((j->'source'->>'year')::int,(j->'source'->>'month')::int,1)BETWEEN current_setting('yuzhou.period_start')::date AND current_setting('yuzhou.period_end')::date;
DO $$BEGIN IF(SELECT sum((j->>'sourceMultiplicity')::int)FROM sp)<>current_setting('yuzhou.expected_rows')::bigint THEN RAISE EXCEPTION'T4 selected archive window drift';END IF;END$$;
CREATE TEMP TABLE before_hash AS SELECT(SELECT encode(digest(COALESCE(string_agg(id::text||employment_status,''ORDER BY id),''),'sha256'),'hex')FROM hr_employee)employee,(SELECT encode(digest(COALESCE(string_agg(id::text||legacy_id,''ORDER BY id),''),'sha256'),'hex')FROM hr_employee_insurance_period)t3,(SELECT encode(digest(COALESCE(string_agg(id::text||status,''ORDER BY id),''),'sha256'),'hex')FROM hr_payroll_run)runs,(SELECT encode(digest(COALESCE(string_agg(id::text||status,''ORDER BY id),''),'sha256'),'hex')FROM hr_payslip)slips;
CREATE TEMP TABLE protected_before(table_name text PRIMARY KEY,relation_present boolean NOT NULL,row_count bigint NOT NULL,content_sha256 text NOT NULL);
DO $$DECLARE protected_table text;relation regclass;rows bigint;content_hash text;BEGIN
 FOREACH protected_table IN ARRAY ARRAY['hr_employee','hr_employee_compensation','hr_compensation_plan','hr_compensation_item','hr_employee_insurance_period','hr_attendance_request','hr_attendance_shift','hr_attendance_punch_event','hr_attendance_calculation_version','hr_employee_attendance_daily_result','hr_attendance_period','hr_attendance_month_summary','hr_attendance_payroll_input_batch','hr_attendance_payroll_input_item','hr_payroll_run','hr_payslip','hr_payslip_item','biz_user_message','hr_payroll_payment','hr_payroll_bank_export','hr_payroll_tax_submission','hr_payroll_outbox'] LOOP
  relation:=to_regclass('public.'||protected_table);
  IF relation IS NULL THEN INSERT INTO protected_before VALUES(protected_table,false,0,encode(digest('','sha256'),'hex'));
  ELSE EXECUTE format('SELECT count(*),encode(digest(COALESCE(string_agg(to_jsonb(row_value)::text,'''' ORDER BY to_jsonb(row_value)::text),''''),''sha256''),''hex'') FROM %s row_value',relation) INTO rows,content_hash;INSERT INTO protected_before VALUES(protected_table,true,rows,content_hash);
  END IF;
 END LOOP;
END$$;
INSERT INTO migration_batch(run_id,source_system,source_snapshot_sha256,target_database,phase,status,tool_version,started_at)VALUES(:'run','yuzhou-v10',:'snap',:'db','load','running','t4-loader-v2',now());
INSERT INTO hr_payroll_legacy_batch(tenant_id,park_id,batch_code,source_backup_hash,catalog_hash,manifest_hash,source_row_count,status,remark)VALUES(:'tenant',:'park',:'run',:'snap',:'catalog',:'mh',current_setting('yuzhou.expected_rows')::bigint,'unpublished','T4 '||current_setting('yuzhou.mode')||' run='||:'run');
INSERT INTO hr_payroll_book(tenant_id,park_id,legacy_scheme,book_name,source_hash,remark)SELECT :'tenant',:'park',n,'玉舟账套'||n,encode(digest(n::text,'sha256'),'hex'),'T4 run='||:'run' FROM generate_series(1,35)n;
INSERT INTO hr_payroll_item_definition(tenant_id,park_id,book_id,legacy_item_name,item_code,remark)SELECT :'tenant',:'park',b.id,j->'source'->>'itemname',upper(j->'source'->>'itemname'),'T4 run='||:'run'FROM si JOIN hr_payroll_book b ON b.legacy_scheme=(j->'source'->>'scheme')::int AND b.remark='T4 run='||:'run';
INSERT INTO hr_payroll_item_version(tenant_id,park_id,item_definition_id,version_no,display_name,value_type,legacy_item_type,legacy_add_or_sub,item_category,decimal_scale,sort_no,taxable,print_enabled,enabled,legacy_print_width,legacy_print_width_hash,legacy_tax_flag,legacy_no_decimal_flag,legacy_use_flag,legacy_decimal_length,legacy_decimal_length_hash,legacy_print_report,legacy_print_report_hash,legacy_item_title,legacy_long_description,suppress_decimals,legacy_metadata_review_required,source_hash,remark)SELECT :'tenant',:'park',d.id,1,j->'source'->>'description',CASE j->'source'->>'datatype'WHEN'数值'THEN'decimal'WHEN'日期'THEN'date'ELSE'text'END,j->'source'->>'itemtype',j->'source'->>'addorsub',CASE j->'source'->>'addorsub'WHEN'增加项'THEN'earning'WHEN'减少项'THEN'deduction'WHEN'自动'THEN'summary'ELSE'unclassified'END,CASE WHEN j->'declarativeMetadata'->>'decimalScale'~'^-?[0-9]{1,10}$'THEN CASE WHEN(j->'declarativeMetadata'->>'decimalScale')::numeric BETWEEN -2147483648 AND 2147483647 THEN(j->'declarativeMetadata'->>'decimalScale')::int END END,COALESCE((j->'source'->>'myorder')::int,0),CASE j->'declarativeMetadata'->>'taxable'WHEN'true'THEN true WHEN'false'THEN false END,CASE j->'declarativeMetadata'->>'printEnabled'WHEN'true'THEN true WHEN'false'THEN false END,CASE j->'declarativeMetadata'->>'enabled'WHEN'true'THEN true WHEN'false'THEN false ELSE false END,CASE WHEN j->'declarativeMetadata'->>'printWidth'~'^-?[0-9]{1,10}$'THEN CASE WHEN(j->'declarativeMetadata'->>'printWidth')::numeric BETWEEN -2147483648 AND 2147483647 THEN(j->'declarativeMetadata'->>'printWidth')::int END END,j->'declarativeMetadata'->>'printWidthSourceHash',j->'source'->>'istax',j->'source'->>'notdec',j->'source'->>'isuse',CASE WHEN j->'declarativeMetadata'->>'legacyDecimalLength'~'^-?[0-9]{1,10}$'THEN CASE WHEN(j->'declarativeMetadata'->>'legacyDecimalLength')::numeric BETWEEN -2147483648 AND 2147483647 THEN(j->'declarativeMetadata'->>'legacyDecimalLength')::int END END,j->'declarativeMetadata'->>'decimalLengthSourceHash',CASE WHEN j->'declarativeMetadata'->>'legacyPrintReport'~'^-?[0-9]{1,10}$'THEN CASE WHEN(j->'declarativeMetadata'->>'legacyPrintReport')::numeric BETWEEN -2147483648 AND 2147483647 THEN(j->'declarativeMetadata'->>'legacyPrintReport')::int END END,j->'declarativeMetadata'->>'printReportSourceHash',j->'declarativeMetadata'->>'itemTitle',j->'declarativeMetadata'->>'longDescription',CASE j->'declarativeMetadata'->>'suppressDecimals'WHEN'true'THEN true WHEN'false'THEN false END,CASE j->'declarativeMetadata'->>'legacyMetadataReviewRequired'WHEN'false'THEN false ELSE true END,j->>'sourceRowSha256','T4 run='||:'run'FROM si JOIN hr_payroll_book b ON b.legacy_scheme=(j->'source'->>'scheme')::int AND b.remark='T4 run='||:'run'JOIN hr_payroll_item_definition d ON d.book_id=b.id AND d.legacy_item_name=j->'source'->>'itemname';
INSERT INTO hr_payroll_formula_version(tenant_id,park_id,book_id,item_version_id,legacy_formula_id,version_no,raw_expression,raw_condition,expression_hash,parse_status,dependency_codes,calculation_order,remark)SELECT :'tenant',:'park',b.id,v.id,(j->'source'->>'id')::int,1,j->'source'->>'expression',NULLIF(j->'source'->>'cit',''),j->'lexicalProfile'->>'expressionSha256','manual_review','[]',COALESCE((j->'source'->>'myorder')::int,1),'T4 run='||:'run'FROM sf JOIN hr_payroll_book b ON b.legacy_scheme=(j->'source'->>'scheme')::int AND b.remark='T4 run='||:'run'LEFT JOIN hr_payroll_item_definition d ON d.book_id=b.id AND d.legacy_item_name=j->'source'->>'itemname'LEFT JOIN hr_payroll_item_version v ON v.item_definition_id=d.id;
INSERT INTO hr_payroll_book_period(tenant_id,park_id,book_id,period_month,legacy_close_state,source_hash,remark)SELECT :'tenant',:'park',b.id,make_date((j->'source'->>'year')::int,(j->'source'->>'month')::int,1),(j->'source'->>'closestate')::int,j->>'sourceRowSha256','T4 run='||:'run'FROM sc JOIN hr_payroll_book b ON b.legacy_scheme=(j->'source'->>'scheme')::int AND b.remark='T4 run='||:'run'WHERE make_date((j->'source'->>'year')::int,(j->'source'->>'month')::int,1)BETWEEN current_setting('yuzhou.period_start')::date AND current_setting('yuzhou.period_end')::date;
CREATE TEMP TABLE em AS SELECT employee_code,min(id::text)::uuid id,count(*)n FROM hr_employee WHERE tenant_id=:'tenant'AND park_id=:'park'AND NOT is_deleted GROUP BY employee_code;
INSERT INTO hr_payroll_book_membership(tenant_id,park_id,book_id,employee_id,legacy_membership_id,legacy_employee_hash,mapping_status,source_hash,remark)SELECT :'tenant',:'park',b.id,CASE WHEN em.n=1 THEN em.id END,(j->'source'->>'id')::int,encode(digest(j->'source'->>'person','sha256'),'hex'),CASE WHEN em.n=1 THEN'mapped'ELSE'employee_unmapped'END,j->>'sourceRowSha256','T4 run='||:'run'FROM sm JOIN hr_payroll_book b ON b.legacy_scheme=(j->'source'->>'scheme')::int AND b.remark='T4 run='||:'run'LEFT JOIN em ON em.employee_code=j->'source'->>'person';
INSERT INTO hr_payroll_tax_rule_version(tenant_id,park_id,legacy_tax_id,base_amount,lower_limit,upper_limit,tax_percent,offset_amount,source_hash,remark)SELECT :'tenant',:'park',(j->'source'->>'id')::int,NULLIF(j->'source'->'base'->>'decimal','')::numeric,NULLIF(j->'source'->'limit1'->>'decimal','')::numeric,NULLIF(j->'source'->'limit2'->>'decimal','')::numeric,NULLIF(j->'source'->'taxpercent'->>'decimal','')::numeric,NULLIF(j->'source'->'offset'->>'decimal','')::numeric,j->>'sourceRowSha256','T4 run='||:'run'FROM st;
CREATE TEMP TABLE cls AS SELECT sp.j,(sp.j->>'legacyScheme')::integer legacy_scheme,substring(sp.j->>'sourceContentGroupSha256',1,1) source_shard,em.id employee_id,bp.id period_id,CASE WHEN(j->>'sourceMultiplicity')::int > 1 THEN'duplicate_source'WHEN em.n IS DISTINCT FROM 1 THEN'employee_unmapped'WHEN bp.id IS NULL THEN'period_invalid'WHEN j->>'disposition'<>'candidate'THEN j->>'disposition'ELSE'loaded'END disposition FROM sp LEFT JOIN em ON em.employee_code=j->'source'->>'person'LEFT JOIN hr_payroll_book b ON b.legacy_scheme=(j->>'legacyScheme')::int AND b.remark='T4 run='||:'run'LEFT JOIN hr_payroll_book_period bp ON bp.book_id=b.id AND bp.period_month=make_date((j->'source'->>'year')::int,(j->'source'->>'month')::int,1);
CREATE INDEX cls_legacy_scheme_disposition_idx ON cls(legacy_scheme,source_shard,disposition);
INSERT INTO hr_payroll_legacy_snapshot(tenant_id,park_id,batch_id,book_period_id,employee_id,legacy_source_table,legacy_employee_hash,source_content_group_hash,source_multiplicity,mapping_status,gross_amount,deduction_amount,tax_amount,net_amount,source_hash,remark)SELECT :'tenant',:'park',lb.id,c.period_id,c.employee_id,replace(j->>'sourceTable','dbo.',''),encode(digest(j->'source'->>'person','sha256'),'hex'),j->>'sourceContentGroupSha256',(j->>'sourceMultiplicity')::int,CASE WHEN c.disposition='loaded'THEN'mapped'ELSE'employee_unmapped'END,NULLIF(g->'value'->>'decimal','')::numeric,NULLIF(d->'value'->>'decimal','')::numeric,NULLIF(t->'value'->>'decimal','')::numeric,NULLIF(n->'value'->>'decimal','')::numeric,j->>'sourceRowSha256','T4 run='||:'run'FROM cls c CROSS JOIN hr_payroll_legacy_batch lb LEFT JOIN LATERAL(SELECT x g FROM jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='gross_total')a ON true LEFT JOIN LATERAL(SELECT x d FROM jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='deduction_total')aa ON true LEFT JOIN LATERAL(SELECT x t FROM jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='tax_total')aaa ON true LEFT JOIN LATERAL(SELECT x n FROM jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='net_total')aaaa ON true WHERE lb.batch_code=:'run'AND c.disposition IN('loaded','employee_unmapped');
DO $$BEGIN IF EXISTS(SELECT 1 FROM hr_payroll_legacy_batch WHERE batch_code=current_setting('yuzhou.run') AND status<>'unpublished')THEN RAISE EXCEPTION'item load requires unpublished batch';END IF;END$$;
-- The foreign keys on legacy snapshot items remain enforced.  A full cold
-- archive exceeds the lab host's per-statement limit, so psql sends sixteen
-- deterministic content-hash shards while this surrounding transaction stays
-- open.  Any shard failure therefore rolls the entire run back.
SELECT format($t4_item$
INSERT INTO hr_payroll_legacy_snapshot_item(tenant_id,park_id,snapshot_id,item_version_id,legacy_column_name,value_type,is_source_null,raw_value,decimal_value,text_value,sort_no,source_hash,remark)
SELECT current_setting('yuzhou.tenant'),current_setting('yuzhou.park'),s.id,v.id,x->>'legacyColumn',CASE WHEN v.id IS NULL THEN'unmapped'WHEN x->'value'->>'kind'IN('decimal','zero')THEN'decimal'WHEN x->'value'->>'kind'='null'THEN v.value_type ELSE'text'END,x->'value'->>'kind'='null',CASE WHEN x->'value'->>'kind'IN('decimal','zero')THEN x->'value'->>'decimal'WHEN x->'value'->>'kind'='text'THEN x->'value'->>'value'WHEN x->'value'->>'kind'='empty'THEN''END,CASE WHEN v.id IS NOT NULL AND x->'value'->>'kind'IN('decimal','zero')THEN(x->'value'->>'decimal')::numeric END,CASE WHEN v.id IS NOT NULL AND x->'value'->>'kind'='text'THEN x->'value'->>'value'WHEN v.id IS NOT NULL AND x->'value'->>'kind'='empty'THEN''END,row_number()OVER(PARTITION BY s.id ORDER BY x->>'legacyColumn'),encode(digest(s.source_hash||(x->>'legacyColumn'),'sha256'),'hex'),'T4 run='||current_setting('yuzhou.run')
FROM cls c JOIN hr_payroll_legacy_snapshot s ON s.source_content_group_hash=c.j->>'sourceContentGroupSha256'AND s.remark='T4 run='||current_setting('yuzhou.run') CROSS JOIN LATERAL jsonb_array_elements(c.j->'values')x JOIN hr_payroll_book_period bp ON bp.id=s.book_period_id LEFT JOIN hr_payroll_item_definition d ON d.book_id=bp.book_id AND d.legacy_item_name=x->>'legacyColumn'LEFT JOIN hr_payroll_item_version v ON v.item_definition_id=d.id
WHERE c.disposition IN('loaded','employee_unmapped') AND c.source_shard=%L;
DO $t4_progress$ BEGIN RAISE NOTICE 'T4_PROGRESS_BATCH=%%/16', %s; END $t4_progress$;
$t4_item$,shard,batch_number)
FROM (VALUES('0',1),('1',2),('2',3),('3',4),('4',5),('5',6),('6',7),('7',8),('8',9),('9',10),('a',11),('b',12),('c',13),('d',14),('e',15),('f',16)) AS shards(shard,batch_number)
ORDER BY shard
\gexec
DO $$BEGIN IF EXISTS((SELECT DISTINCT tenant_id,park_id,snapshot_id FROM hr_payroll_legacy_snapshot_item WHERE remark='T4 run='||current_setting('yuzhou.run') EXCEPT SELECT tenant_id,park_id,id FROM hr_payroll_legacy_snapshot WHERE remark='T4 run='||current_setting('yuzhou.run'))) OR EXISTS((SELECT DISTINCT tenant_id,park_id,item_version_id FROM hr_payroll_legacy_snapshot_item WHERE remark='T4 run='||current_setting('yuzhou.run') AND item_version_id IS NOT NULL EXCEPT SELECT tenant_id,park_id,id FROM hr_payroll_item_version WHERE remark='T4 run='||current_setting('yuzhou.run')))THEN RAISE EXCEPTION'snapshot item owner/FK verification failed';END IF;END$$;
INSERT INTO hr_payroll_review_case(tenant_id,park_id,batch_id,case_type,subject_hash,evidence_summary,remark)
SELECT current_setting('yuzhou.tenant'),current_setting('yuzhou.park'),lb.id,'item_unmapped',encode(digest('item_unmapped:'||b.legacy_scheme::text||':'||i.legacy_column_name,'sha256'),'hex'),jsonb_build_object('legacyScheme',b.legacy_scheme,'occurrences',count(*)),'T4 run='||current_setting('yuzhou.run')
FROM hr_payroll_legacy_snapshot_item i JOIN hr_payroll_legacy_snapshot s ON s.id=i.snapshot_id JOIN hr_payroll_book_period bp ON bp.id=s.book_period_id JOIN hr_payroll_book b ON b.id=bp.book_id CROSS JOIN hr_payroll_legacy_batch lb
WHERE i.remark='T4 run='||current_setting('yuzhou.run') AND i.item_version_id IS NULL AND lb.batch_code=current_setting('yuzhou.run')
GROUP BY lb.id,b.legacy_scheme,i.legacy_column_name;
INSERT INTO hr_payroll_review_case(tenant_id,park_id,batch_id,snapshot_id,case_type,subject_hash,evidence_summary,remark)
SELECT current_setting('yuzhou.tenant'),current_setting('yuzhou.park'),lb.id,s.id,'employee_unmapped',s.source_content_group_hash,jsonb_build_object('reason','target_employee_mapping_required'),'T4 run='||current_setting('yuzhou.run')
FROM hr_payroll_legacy_snapshot s CROSS JOIN hr_payroll_legacy_batch lb
WHERE s.remark='T4 run='||current_setting('yuzhou.run') AND s.mapping_status='employee_unmapped' AND lb.batch_code=current_setting('yuzhou.run');
DO $$DECLARE archived_rows bigint; rejected_rows bigint; unmapped_employee_rows bigint; loaded_items bigint; expected_physical_items bigint; source_net numeric(20,4); loaded_source_net numeric(20,4); loaded_target_net numeric(20,4); full_source_net numeric(20,4);cold_source_net numeric(20,4);BEGIN
 SELECT COALESCE(sum((j->>'sourceMultiplicity')::int)FILTER(WHERE disposition IN('loaded','employee_unmapped')),0),COALESCE(sum((j->>'sourceMultiplicity')::int)FILTER(WHERE disposition NOT IN('loaded','employee_unmapped')),0),COALESCE(sum((j->>'sourceMultiplicity')::int)FILTER(WHERE disposition='employee_unmapped'),0) INTO archived_rows,rejected_rows,unmapped_employee_rows FROM cls;
 SELECT count(*) INTO loaded_items FROM hr_payroll_legacy_snapshot_item WHERE remark='T4 run='||current_setting('yuzhou.run');
 SELECT COALESCE(sum(jsonb_array_length(j->'values')) FILTER(WHERE disposition IN('loaded','employee_unmapped')),0) INTO expected_physical_items FROM cls;
 IF archived_rows<>current_setting('yuzhou.expected_rows')::bigint OR rejected_rows<>0 OR loaded_items<>expected_physical_items OR unmapped_employee_rows<>(SELECT COALESCE(sum(source_multiplicity),0)FROM hr_payroll_legacy_snapshot WHERE remark='T4 run='||current_setting('yuzhou.run') AND mapping_status='employee_unmapped') OR unmapped_employee_rows<>(SELECT count(*)FROM hr_payroll_review_case WHERE remark='T4 run='||current_setting('yuzhou.run') AND case_type='employee_unmapped') THEN RAISE EXCEPTION'T4 selected archive accounting drift';END IF;
 SELECT COALESCE(sum(((x->'value'->>'decimal')::numeric)*(j->>'sourceMultiplicity')::int),0) INTO source_net FROM sp CROSS JOIN LATERAL jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='net_total' AND x->'value'->>'kind' IN('decimal','zero');
 SELECT COALESCE(sum(((x->'value'->>'decimal')::numeric)*(j->>'sourceMultiplicity')::int),0) INTO loaded_source_net FROM cls CROSS JOIN LATERAL jsonb_array_elements(j->'values')x WHERE disposition IN('loaded','employee_unmapped') AND x->>'systemSummary'='net_total' AND x->'value'->>'kind' IN('decimal','zero');
 SELECT COALESCE(sum(net_amount*source_multiplicity),0) INTO loaded_target_net FROM hr_payroll_legacy_snapshot WHERE remark='T4 run='||current_setting('yuzhou.run');
 SELECT COALESCE(sum(((x->'value'->>'decimal')::numeric)*(j->>'sourceMultiplicity')::int),0)INTO full_source_net FROM sp_all CROSS JOIN LATERAL jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='net_total'AND x->'value'->>'kind'IN('decimal','zero');
 SELECT COALESCE(sum(((x->'value'->>'decimal')::numeric)*(j->>'sourceMultiplicity')::int),0)INTO cold_source_net FROM sp_all CROSS JOIN LATERAL jsonb_array_elements(j->'values')x WHERE make_date((j->'source'->>'year')::int,(j->'source'->>'month')::int,1)<DATE'2024-01-01' AND x->>'systemSummary'='net_total'AND x->'value'->>'kind'IN('decimal','zero');
 IF source_net<>current_setting('yuzhou.expected_net')::numeric OR loaded_source_net<>current_setting('yuzhou.expected_net')::numeric OR full_source_net<>102194056.8000 OR cold_source_net<>86471046.8900 OR loaded_source_net IS DISTINCT FROM loaded_target_net THEN RAISE EXCEPTION'T4 full/selected/cold net amount drift';END IF;
 UPDATE hr_payroll_legacy_batch SET source_amount_total=source_net,loaded_amount_total=loaded_target_net WHERE batch_code=current_setting('yuzhou.run');
END$$;
INSERT INTO hr_payroll_review_case(tenant_id,park_id,batch_id,formula_version_id,case_type,subject_hash,evidence_summary,remark)SELECT :'tenant',:'park',lb.id,f.id,'formula_unsafe',encode(digest(b.legacy_scheme::text||':'||f.legacy_formula_id::text,'sha256'),'hex'),'{"reason":"manual_review"}','T4 run='||:'run'FROM hr_payroll_formula_version f JOIN hr_payroll_book b ON b.id=f.book_id CROSS JOIN hr_payroll_legacy_batch lb WHERE f.remark='T4 run='||:'run'AND lb.batch_code=:'run';
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run')INSERT INTO migration_batch_item(batch_id,domain,source_object,phase,status,extracted_count,valid_count,loaded_count,rejected_count,checksum_sha256,started_at,finished_at)SELECT id,CASE WHEN current_setting('yuzhou.mode')='cold_archive' THEN'payroll_snapshot_cold_archive'ELSE'payroll_snapshot'END,'dbo.salary01..35:'||current_setting('yuzhou.period_start')||'..'||current_setting('yuzhou.period_end'),'load',CASE WHEN q > 0 THEN'quarantined'ELSE'succeeded'END,current_setting('yuzhou.expected_rows')::bigint,current_setting('yuzhou.expected_rows')::bigint-q,l,q,:'bh',now(),now()FROM b CROSS JOIN(SELECT COALESCE(sum((j->>'sourceMultiplicity')::int)FILTER(WHERE disposition IN('loaded','employee_unmapped')),0)l,COALESCE(sum((j->>'sourceMultiplicity')::int)FILTER(WHERE disposition NOT IN('loaded','employee_unmapped')),0)q FROM cls)x;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run')INSERT INTO migration_batch_item(batch_id,domain,source_object,phase,status,extracted_count,valid_count,loaded_count,rejected_count,checksum_sha256,started_at,finished_at)SELECT b.id,x.domain,x.source_object,'load','succeeded',x.n,x.n,x.n,0,:'catalog',now(),now() FROM b CROSS JOIN(VALUES('payroll_membership','dbo.schemes',647),('payroll_item','dbo.salaryitems',711),('payroll_formula','dbo.salaryequal',244),('payroll_tax_rule','dbo.tax',9),('payroll_close','dbo.salarycount:'||current_setting('yuzhou.period_start')||'..'||current_setting('yuzhou.period_end'),current_setting('yuzhou.expected_closes')::bigint))x(domain,source_object,n);
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run'),i AS(SELECT id FROM migration_batch_item WHERE batch_id=(SELECT id FROM b) AND domain=CASE WHEN current_setting('yuzhou.mode')='cold_archive' THEN'payroll_snapshot_cold_archive'ELSE'payroll_snapshot'END)INSERT INTO migration_error(batch_id,batch_item_id,category,error_code,source_identity_sha256,redacted_evidence)SELECT b.id,i.id,'validation',upper(disposition),j->>'sourceContentGroupSha256',jsonb_build_object('multiplicity',j->>'sourceMultiplicity','table',j->>'sourceTable')FROM cls,b,i WHERE disposition NOT IN('loaded','employee_unmapped');
WITH batch AS(SELECT id FROM migration_batch WHERE run_id=:'run'),maps AS(
 SELECT x.id,x.target_table,x.source_pk,x.source_hash FROM(
  SELECT id,'hr_payroll_legacy_batch'target_table,source_backup_hash||':'||catalog_hash source_pk,manifest_hash source_hash FROM hr_payroll_legacy_batch WHERE batch_code=:'run'
  UNION ALL SELECT id,'hr_payroll_book',legacy_scheme::text,source_hash FROM hr_payroll_book WHERE remark='T4 run='||:'run'
  UNION ALL SELECT d.id,'hr_payroll_item_definition',b.legacy_scheme::text||':'||d.legacy_item_name,encode(digest(b.legacy_scheme::text||':'||d.legacy_item_name,'sha256'),'hex')FROM hr_payroll_item_definition d JOIN hr_payroll_book b ON b.id=d.book_id WHERE d.remark='T4 run='||:'run'
  UNION ALL SELECT v.id,'hr_payroll_item_version',b.legacy_scheme::text||':'||d.legacy_item_name||':'||v.version_no::text,v.source_hash FROM hr_payroll_item_version v JOIN hr_payroll_item_definition d ON d.id=v.item_definition_id JOIN hr_payroll_book b ON b.id=d.book_id WHERE v.remark='T4 run='||:'run'
  UNION ALL SELECT f.id,'hr_payroll_formula_version',b.legacy_scheme::text||':'||f.legacy_formula_id::text,f.expression_hash FROM hr_payroll_formula_version f JOIN hr_payroll_book b ON b.id=f.book_id WHERE f.remark='T4 run='||:'run'
  UNION ALL SELECT p.id,'hr_payroll_book_period',b.legacy_scheme::text||':'||p.period_month::text,p.source_hash FROM hr_payroll_book_period p JOIN hr_payroll_book b ON b.id=p.book_id WHERE p.remark='T4 run='||:'run'
  UNION ALL SELECT m.id,'hr_payroll_book_membership',b.legacy_scheme::text||':'||m.legacy_membership_id::text,m.source_hash FROM hr_payroll_book_membership m JOIN hr_payroll_book b ON b.id=m.book_id WHERE m.remark='T4 run='||:'run'
  UNION ALL SELECT id,'hr_payroll_tax_rule_version',legacy_tax_id::text,source_hash FROM hr_payroll_tax_rule_version WHERE remark='T4 run='||:'run'
  UNION ALL SELECT id,'hr_payroll_legacy_snapshot',source_content_group_hash,source_hash FROM hr_payroll_legacy_snapshot WHERE remark='T4 run='||:'run'
  UNION ALL SELECT i.id,'hr_payroll_legacy_snapshot_item',s.source_content_group_hash||':'||i.legacy_column_name,i.source_hash FROM hr_payroll_legacy_snapshot_item i JOIN hr_payroll_legacy_snapshot s ON s.id=i.snapshot_id WHERE i.remark='T4 run='||:'run'
  UNION ALL SELECT c.id,'hr_payroll_review_case','item_unmapped:'||c.subject_hash,c.subject_hash FROM hr_payroll_review_case c WHERE c.remark='T4 run='||:'run'AND c.case_type='item_unmapped'
  UNION ALL SELECT c.id,'hr_payroll_review_case','employee_unmapped:'||c.subject_hash,c.subject_hash FROM hr_payroll_review_case c WHERE c.remark='T4 run='||:'run'AND c.case_type='employee_unmapped'
  UNION ALL SELECT c.id,'hr_payroll_review_case',b.legacy_scheme::text||':'||f.legacy_formula_id::text,f.expression_hash FROM hr_payroll_review_case c JOIN hr_payroll_formula_version f ON f.id=c.formula_version_id JOIN hr_payroll_book b ON b.id=f.book_id WHERE c.remark='T4 run='||:'run'
 )x
)
INSERT INTO legacy_record_map(batch_id,source_system,source_table,source_pk_canonical,source_identity_sha256,source_row_sha256,target_table,target_id,mapping_status)
SELECT batch.id,'yuzhou-v10','derived',maps.source_pk,encode(digest(maps.target_table||':'||maps.source_pk,'sha256'),'hex'),maps.source_hash,maps.target_table,maps.id,'loaded'FROM batch CROSS JOIN maps;
ANALYZE legacy_record_map;
ANALYZE hr_payroll_legacy_snapshot_item;
DO $$DECLARE current_employee text;current_t3 text;current_runs text;current_slips text;BEGIN
 SELECT encode(digest(COALESCE(string_agg(id::text||employment_status,''ORDER BY id),''),'sha256'),'hex') INTO current_employee FROM hr_employee;
 SELECT encode(digest(COALESCE(string_agg(id::text||legacy_id,''ORDER BY id),''),'sha256'),'hex') INTO current_t3 FROM hr_employee_insurance_period;
 SELECT encode(digest(COALESCE(string_agg(id::text||status,''ORDER BY id),''),'sha256'),'hex') INTO current_runs FROM hr_payroll_run;
 SELECT encode(digest(COALESCE(string_agg(id::text||status,''ORDER BY id),''),'sha256'),'hex') INTO current_slips FROM hr_payslip;
 IF EXISTS(SELECT 1 FROM before_hash WHERE employee IS DISTINCT FROM current_employee OR t3 IS DISTINCT FROM current_t3 OR runs IS DISTINCT FROM current_runs OR slips IS DISTINCT FROM current_slips)THEN RAISE EXCEPTION'T4 modified T0/T3 or online payroll state';END IF;
END$$;
UPDATE hr_payroll_legacy_batch SET loaded_row_count=(SELECT COALESCE(sum(source_multiplicity),0)FROM hr_payroll_legacy_snapshot WHERE batch_id=hr_payroll_legacy_batch.id),quarantined_row_count=current_setting('yuzhou.expected_rows')::bigint-(SELECT COALESCE(sum(source_multiplicity),0)FROM hr_payroll_legacy_snapshot WHERE batch_id=hr_payroll_legacy_batch.id),status='staged'WHERE batch_code=:'run';
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run')INSERT INTO migration_check(batch_id,check_code,expected_value,actual_value,passed,evidence_sha256)SELECT id,'T4_FULL_SOURCE_AND_SELECTED_ARCHIVE_ACCOUNTING',jsonb_build_object('mode',current_setting('yuzhou.mode'),'fullSourceRows',46092,'selectedRows',current_setting('yuzhou.expected_rows')::bigint,'selectedItems',current_setting('yuzhou.expected_items')::bigint,'selectedNet',current_setting('yuzhou.expected_net')::numeric,'fullSourceNet',102194056.8000,'coldArchiveSourceNet',86471046.8900),jsonb_build_object('mode',current_setting('yuzhou.mode'),'fullSourceRows',(SELECT sum((j->>'sourceMultiplicity')::int)FROM sp_all),'selectedRows',(SELECT sum((j->>'sourceMultiplicity')::int)FROM sp),'selectedLoaded',(SELECT loaded_row_count FROM hr_payroll_legacy_batch WHERE batch_code=:'run'),'selectedQuarantined',(SELECT quarantined_row_count FROM hr_payroll_legacy_batch WHERE batch_code=:'run'),'selectedItems',(SELECT count(*)FROM hr_payroll_legacy_snapshot_item WHERE remark='T4 run='||:'run'),'fullSourceNet',(SELECT sum(((x->'value'->>'decimal')::numeric)*(j->>'sourceMultiplicity')::int)FROM sp_all CROSS JOIN LATERAL jsonb_array_elements(j->'values')x WHERE x->>'systemSummary'='net_total'AND x->'value'->>'kind'IN('decimal','zero')),'selectedSourceNet',(SELECT source_amount_total FROM hr_payroll_legacy_batch WHERE batch_code=:'run'),'selectedLoadedNet',(SELECT loaded_amount_total FROM hr_payroll_legacy_batch WHERE batch_code=:'run'),'coldArchiveSourceNet',(SELECT sum(((x->'value'->>'decimal')::numeric)*(j->>'sourceMultiplicity')::int)FROM sp_all CROSS JOIN LATERAL jsonb_array_elements(j->'values')x WHERE make_date((j->'source'->>'year')::int,(j->'source'->>'month')::int,1)<DATE'2024-01-01' AND x->>'systemSummary'='net_total'AND x->'value'->>'kind'IN('decimal','zero'))),true,encode(digest('T4:'||current_setting('yuzhou.mode')||':'||current_setting('yuzhou.expected_rows')||':'||current_setting('yuzhou.expected_items'),'sha256'),'hex')FROM b;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run')INSERT INTO migration_rollback_point(batch_id,rollback_code,reversible_scope,cleanup_manifest,evidence_sha256,verified_at)SELECT id,'T4_PAYROLL_HISTORY',jsonb_build_object('run',:'run'),'{"procedure":"rollback_yuzhou_t4_payroll_history"}',:'bh',now()FROM b;
DO $$DECLARE a record;BEGIN SELECT * INTO a FROM before_hash;IF a.employee IS DISTINCT FROM(SELECT encode(digest(COALESCE(string_agg(id::text||employment_status,''ORDER BY id),''),'sha256'),'hex')FROM hr_employee)OR a.t3 IS DISTINCT FROM(SELECT encode(digest(COALESCE(string_agg(id::text||legacy_id,''ORDER BY id),''),'sha256'),'hex')FROM hr_employee_insurance_period)OR a.runs IS DISTINCT FROM(SELECT encode(digest(COALESCE(string_agg(id::text||status,''ORDER BY id),''),'sha256'),'hex')FROM hr_payroll_run)OR a.slips IS DISTINCT FROM(SELECT encode(digest(COALESCE(string_agg(id::text||status,''ORDER BY id),''),'sha256'),'hex')FROM hr_payslip)THEN RAISE EXCEPTION'protected T0/T3/online payroll drift';END IF;END$$;
DO $$DECLARE protected_table text;relation regclass;rows bigint;content_hash text;expected record;BEGIN
 FOR expected IN SELECT * FROM protected_before ORDER BY table_name LOOP
  protected_table:=expected.table_name;relation:=to_regclass('public.'||protected_table);
  IF relation IS NULL THEN rows:=0;content_hash:=encode(digest('','sha256'),'hex');
  ELSE EXECUTE format('SELECT count(*),encode(digest(COALESCE(string_agg(to_jsonb(row_value)::text,'''' ORDER BY to_jsonb(row_value)::text),''''),''sha256''),''hex'') FROM %s row_value',relation) INTO rows,content_hash;
  END IF;
  IF (relation IS NOT NULL) IS DISTINCT FROM expected.relation_present OR rows IS DISTINCT FROM expected.row_count OR content_hash IS DISTINCT FROM expected.content_sha256 THEN RAISE EXCEPTION'protected online payroll/compensation/attendance/message state drift: %',protected_table;END IF;
 END LOOP;
END$$;
UPDATE migration_batch SET phase='verify',status='succeeded',counts=jsonb_build_object('fullSource',46092,'loadMode',current_setting('yuzhou.mode'),'selectedSource',current_setting('yuzhou.expected_rows')::bigint,'loaded',(SELECT loaded_row_count FROM hr_payroll_legacy_batch WHERE batch_code=:'run'),'quarantined',(SELECT quarantined_row_count FROM hr_payroll_legacy_batch WHERE batch_code=:'run'),'employeeUnmappedSnapshots',(SELECT count(*)FROM hr_payroll_legacy_snapshot WHERE remark='T4 run='||:'run' AND mapping_status='employee_unmapped'),'employeeUnmappedRows',(SELECT COALESCE(sum(source_multiplicity),0)FROM hr_payroll_legacy_snapshot WHERE remark='T4 run='||:'run' AND mapping_status='employee_unmapped'),'snapshotItems',current_setting('yuzhou.expected_items')::bigint,'itemDefinitions',711,'formulas',244,'closes',current_setting('yuzhou.expected_closes')::bigint,'memberships',647,'taxRules',9),finished_at=now()WHERE run_id=:'run';COMMIT;
