import { chromium } from '/tmp/property-dialog-audit-browser/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const out=new URL('./',import.meta.url).pathname;
const unitId='11111111-1111-4111-8111-111111111111';
const user={id:'audit-user',username:'audit',real_name:'隔离审查',tenant_id:'audit-tenant',park_id:'audit-park',roles:[],permissions:['*'],is_super:true,data_scope:'tenant',enabled_modules:['asset','homestay','housing_rental','housing_cost','property','leasing','system','rbac','file','workflow'].map(module_code=>({module_code,enabled:true})),accessible_parks:[{id:'audit-park',park_id:'audit-park',park_name:'隔离园区',enabled:true}],menus:[]};
const operation={unitId,unitCode:'AUDIT-101',unitName:'隔离审查房源',buildingId:'audit-building',buildingCode:'AUDIT',buildingName:'隔离楼栋',configuredMode:'short_stay',operationStatus:'enabled',assetUnitId:null,assetUnitCode:null,assetUnitName:null,suspendReason:null,remark:null,effectiveTime:null,liveOwningAggregateCounts:{},sharedOccupancy:{activeCount:0,incompatibleCount:0},version:1,canRequestTransition:true,blockers:[],updateTime:null};
const booking={booking:{id:unitId,bookingCode:'MOCK-STAY-101',status:'confirmed',arrivalDate:'2026-09-01',departureDate:'2026-09-11',unitId,unitCode:'AUDIT-101',unitName:'隔离房源',guestCount:1},guests:[],credentials:[{id:'credential-1',status:'issued',credentialLabel:'房卡 A'}],nights:[],actions:[],ledger:[],finance_visible:false};

import assert from 'node:assert/strict';
const occupancy={id:unitId,unitId,sourceDomain:'operations',sourceType:'manual',sourceLabel:'专项人工锁房',startAt:'2026-09-10T00:00:00Z',endAt:'2026-09-11T00:00:00Z',status:'active',version:1};
const purchase={purchase:{id:unitId,purchaseCode:'采购'+('LONG-ID-'.repeat(35)),vendorName:'隔离供应商',purchaseDate:'2026-09-10',costCategory:'consumable',totalAmount:'200',approvalStatus:'approved',paymentStatus:'unpaid'},items:Array.from({length:15},(_,i)=>({id:'item-'+i,itemName:'采购明细'+i,quantity:1,unit:'个',amount:'10'}))};
const checkout={id:unitId,checkoutCode:'退租代表',contractId:unitId,contract:{id:unitId,contractCode:'合同代表'},status:'40',settlementStatus:'10',approveRecords:[],plannedCheckoutDate:'2026-09-10',checkoutType:'normal',releaseUnitStatus:'10'};

const finance={lease:{id:unitId,leaseCode:'FIN-代表',tenantDisplayName:'隔离租客'},summary:{receivable:'200',paid:'100',outstanding:'100',deposit_balance:'0'},receivables:[{id:'receivable-1',entryKind:'payment',receivableType:'rent',chargeType:'rent',balance:'100',paidAmount:'100',lastPaymentRecorderId:'actor',dueDate:'2026-10-01',status:'partial'}]};
const browser=await chromium.launch({headless:true,executablePath:'/home/jinhuit/.cache/ms-playwright/chromium-1234/chrome-linux64/chrome',args:['--no-sandbox']});const results=[];
try{for(const width of [1440,390]){
const context=await browser.newContext({viewport:{width,height:900}}),page=await context.newPage(),r={width,writes:[],errors:[]};results.push(r);
await context.addInitScript(u=>{localStorage.setItem('jinhu_access_token','audit-fixture-token');localStorage.setItem('jinhu_auth_user',JSON.stringify(u));},user);page.on('pageerror',e=>r.errors.push(e.message));
await page.route('**/api/**',async route=>{const req=route.request(),path=new URL(req.url()).pathname.replace('/api/v1','');if(req.method()!=='GET'){r.writes.push({path,body:req.postDataJSON()});return route.fulfill({status:400,json:{code:400,message:'MOCK 财务失败',data:null}});}const data=path==='/users/me'?user:path==='/housing/finance'?{items:[finance],total:1,page:1,page_size:20}:{items:[],total:0};return route.fulfill({json:{code:0,data}});});
await page.goto('http://127.0.0.1:3417/housing/finance');await page.locator('summary:visible').filter({hasText:'登记财务流水'}).first().click({timeout:60000});const form=page.locator('form:visible').filter({has:page.locator('[name=entry_type]')}).first();await form.locator('[name=entry_type]').selectOption('refund');await form.locator('[name=receivable_id]').selectOption('receivable-1');await form.locator('[name=charge_type]').fill('rent');await form.locator('[name=amount]').fill('50');await form.locator('[name=transaction_reference]').fill('原表单保留凭证');await form.getByRole('button',{name:'核对并提交审批'}).click();const d=page.locator('dialog[open]');await d.locator('textarea').fill('财务原因');await d.getByRole('button',{name:'取消',exact:true}).click();assert.equal(await form.locator('[name=amount]').inputValue(),'50');assert.equal(await form.locator('[name=transaction_reference]').inputValue(),'原表单保留凭证');r.cancelPreservedForm=true;
await form.getByRole('button',{name:'核对并提交审批'}).click();assert.equal(await d.locator('textarea').inputValue(),'');await d.locator('textarea').fill('财务原因');await d.getByRole('button',{name:'确认提交财务审批'}).click();await d.getByRole('alert').waitFor();r.alert=await d.getByRole('alert').innerText();r.layout=await d.evaluate(e=>({align:getComputedStyle(e).textAlign,buttons:[...e.querySelectorAll('footer button')].map(b=>b.getBoundingClientRect().height)}));assert(r.layout.buttons.every(h=>h>=44));await page.screenshot({path:out+`finance-${width}.png`,fullPage:true});await context.close();}
}finally{fs.writeFileSync(out+'finance-results.json',JSON.stringify(results,null,2));await browser.close();}
