"use client";
import {useEffect,useRef,useState} from "react";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrAttendanceRequest,type HrAttendanceRequestRecalculationPlan} from "../../../lib/hr-api";
import {hrLoadErrorMessage} from "../hr-errors";
import styles from "../hr-workbench.module.css";
import local from "./request-workflow.module.css";

type DayState="pending"|"running"|"success"|"failed";
type PlanState=Record<string,DayState>;

function samePlan(left:HrAttendanceRequestRecalculationPlan,right:HrAttendanceRequestRecalculationPlan){return left.requestId===right.requestId&&left.requestVersion===right.requestVersion&&left.employeeId===right.employeeId&&left.workDates.length===right.workDates.length&&left.workDates.every((date,index)=>date===right.workDates[index]);}
function validPlan(plan:HrAttendanceRequestRecalculationPlan,row:HrAttendanceRequest){return plan.requestId===row.id&&plan.requestNo===row.requestNo&&plan.requestType===row.requestType&&Number.isSafeInteger(plan.requestVersion)&&plan.requestVersion>=1&&typeof plan.employeeId==="string"&&plan.employeeId.length>0&&Array.isArray(plan.workDates)&&plan.workDates.length<=32&&plan.workDates.every((date,index)=>/^\d{4}-\d{2}-\d{2}$/.test(date)&&(index===0||plan.workDates[index-1]!<date));}

export function ApprovedRequestRecalculation({row,busy,onBusyChange,onRecalculated}:{row:HrAttendanceRequest;busy:boolean;onBusyChange:(value:boolean)=>void;onRecalculated:()=>Promise<void>}){
 const [plan,setPlan]=useState<HrAttendanceRequestRecalculationPlan|null>(null),[states,setStates]=useState<PlanState>({}),[message,setMessage]=useState(""),[refreshError,setRefreshError]=useState(""),[checking,setChecking]=useState(false),[running,setRunning]=useState(false);
 const mounted=useRef(true),runningRef=useRef(false),checkingRef=useRef(false),stopRequested=useRef(false),keys=useRef(new Map<string,string>()),completedDates=useRef(new Set<string>()),planRef=useRef<HrAttendanceRequestRecalculationPlan|null>(null),inspectionToken=useRef<string|undefined>(undefined),readGeneration=useRef(0),ownsBusy=useRef(false);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;stopRequested.current=true;readGeneration.current++;if(ownsBusy.current){ownsBusy.current=false;onBusyChange(false);}};},[onBusyChange]);
 const publishPlan=(next:HrAttendanceRequestRecalculationPlan)=>{planRef.current=next;setPlan(next);};
 const readPlan=async(token:string|undefined)=>{const next=await hrApi.attendanceRequestRecalculationPlan(row.id,token);if(!validPlan(next,row))throw new Error("重算计划返回不完整，请重新核对申请。");return next;};
 const check=async()=>{if(busy||runningRef.current||checkingRef.current)return;checkingRef.current=true;const owner=++readGeneration.current,token=getAccessToken();setChecking(true);setMessage("");setRefreshError("");try{const next=await readPlan(token);if(!mounted.current||owner!==readGeneration.current)return;const unchanged=planRef.current!==null&&samePlan(planRef.current,next)&&inspectionToken.current===token;if(!unchanged){keys.current=new Map();completedDates.current=new Set();setStates(Object.fromEntries(next.workDates.map(date=>[date,"pending"])));}inspectionToken.current=token;publishPlan(next);setMessage(next.workDates.length?"请确认员工和日期范围后再开始办理。":"该批准申请没有可自动重算的日期；请核对历史资料，系统不会猜测日期。");}catch(error){if(mounted.current&&owner===readGeneration.current)setMessage(hrLoadErrorMessage(error,"读取批准申请重算计划失败"));}finally{checkingRef.current=false;if(mounted.current&&owner===readGeneration.current)setChecking(false);}};
 const run=async()=>{if(busy||runningRef.current||!planRef.current)return;const token=getAccessToken();if(inspectionToken.current!==token){inspectionToken.current=undefined;keys.current=new Map();completedDates.current=new Set();if(mounted.current)setMessage("当前身份范围已变化，请重新核对后继续办理。");return;}const owner=++readGeneration.current;runningRef.current=true;stopRequested.current=false;ownsBusy.current=true;setRunning(true);onBusyChange(true);setMessage("");setRefreshError("");let completed=false;
  try{const current=await readPlan(token);if(!mounted.current||owner!==readGeneration.current)return;if(!samePlan(planRef.current,current)){keys.current=new Map();completedDates.current=new Set();setStates(Object.fromEntries(current.workDates.map(date=>[date,"pending"])));publishPlan(current);setMessage("申请版本、员工或日期范围已变化，原办理计划已停止；请重新核对后确认。");return;}
   for(const date of current.workDates){if(stopRequested.current)break;if(getAccessToken()!==token){if(mounted.current)setMessage("当前身份范围已变化，后续日期没有办理；请重新核对。");break;}if(completedDates.current.has(date))continue;const key=keys.current.get(date)??crypto.randomUUID();keys.current.set(date,key);if(mounted.current)setStates(previous=>({...previous,[date]:"running"}));try{await hrApi.recalculateAttendance({employeeId:current.employeeId,workDate:date,ruleVersion:"v1"},token,key);if(getAccessToken()!==token){if(mounted.current)setMessage("当前身份范围已变化，后续日期没有办理；请重新核对。");break;}completed=true;completedDates.current.add(date);if(mounted.current&&owner===readGeneration.current)setStates(previous=>({...previous,[date]:"success"}));}catch(error){if(mounted.current&&owner===readGeneration.current){setStates(previous=>({...previous,[date]:"failed"}));setMessage(`${date} 未确认完成：${hrLoadErrorMessage(error,"请继续办理")}。后续日期尚未发出。`);}break;}}
   if(mounted.current&&stopRequested.current)setMessage("已停止后续日期；正在办理的日期已正常收尾，可继续未办理日期。");
  }catch(error){if(mounted.current)setMessage(hrLoadErrorMessage(error,"重新核对批准申请失败；未发出的日期没有办理"));}
  finally{if(completed&&mounted.current&&owner===readGeneration.current&&getAccessToken()===token)try{await onRecalculated();}catch(error){if(mounted.current&&owner===readGeneration.current&&getAccessToken()===token)setRefreshError(hrLoadErrorMessage(error,"日结果或月结期间刷新失败；已成功办理的日期保持不变。"));}runningRef.current=false;if(mounted.current&&owner===readGeneration.current){setRunning(false);if(ownsBusy.current){ownsBusy.current=false;onBusyChange(false);}}}
 };
 const statesForPlan=plan?.workDates.map(date=>[date,states[date]??"pending"] as const)??[];
 return <section className={local.recalculation} aria-label={`批准申请 ${row.requestNo} 的逐日重算`}>
  <button type="button" className="ds-button" disabled={busy||checking||running} onClick={()=>void check()}>核对并重算</button>
  {plan?<div className={`ds-panel ${local.recalculationPlan}`}><strong>重算计划：{plan.employeeName}（{plan.employeeCode}） · {plan.requestNo} · 版本 {plan.requestVersion}</strong><span>日期范围：{plan.workDates.length?plan.workDates.join("、"):"无"}</span>{row.attendanceDate?null:<small>结束时间恰好为零点时，不计入当天。</small>}<div className={styles.actionRow}><button type="button" className="ds-button ds-button-primary" disabled={busy||checking||running||!plan.workDates.length} onClick={()=>void run()}>确认按日期顺序重算</button>{running?<button type="button" className="ds-button" onClick={()=>{stopRequested.current=true;}}>停止后续日期</button>:null}</div>{statesForPlan.length?<div className={local.recalculationDays}>{statesForPlan.map(([date,state])=><span key={date} className="status-pill">{date} · {{pending:"待办理",running:"办理中",success:"已成功",failed:"待继续"}[state]}</span>)}</div>:null}</div>:null}
  {message?<p role="status">{message}</p>:null}{refreshError?<p role="alert" className="form-error">{refreshError}</p>:null}
 </section>;
}
