"use client";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { useCallback,useEffect,useMemo,useState } from "react";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hrApi,type HrAttendanceCalendar,type HrAttendanceDailyResult,type HrAttendanceMonthSummary,type HrAttendancePayrollInput,type HrAttendancePayrollVersion,type HrAttendancePeriod,type HrAttendanceRequest,type HrAttendanceShift,type HrEmployee } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import { hrLoadErrorMessage } from "../hr-errors";
import styles from "../hr-workbench.module.css";

const readPermissions=[HR_PERMISSIONS.HR_ATTENDANCE_READ,HR_PERMISSIONS.HR_ATTENDANCE_TEAM_READ,HR_PERMISSIONS.HR_ATTENDANCE_SELF_READ];
const typeLabels:Record<string,string>={leave:"请假",overtime:"加班",business_trip:"出差",correction:"考勤更正"};
const statusLabels:Record<string,string>={draft:"草稿",submitted:"待审批",approved:"已批准",returned:"已退回",cancelled:"已取消"};
const emptyForm={requestType:"leave",startAt:"",endAt:"",attendanceDate:"",reason:""};
export function HrAttendanceClient(){
 const user=useAuthUser(),canRead=hasAnyPermission(user,readPermissions),canRequest=hasPermission(user,HR_PERMISSIONS.HR_ATTENDANCE_REQUEST),canApprove=hasPermission(user,HR_PERMISSIONS.HR_ATTENDANCE_APPROVE),canOperate=hasPermission(user,HR_PERMISSIONS.HR_ATTENDANCE_OPERATE),canClose=hasPermission(user,HR_PERMISSIONS.HR_ATTENDANCE_CLOSE),canCorrect=hasPermission(user,HR_PERMISSIONS.HR_ATTENDANCE_CORRECT),canPayrollInput=hasPermission(user,HR_PERMISSIONS.HR_ATTENDANCE_PAYROLL_INPUT_READ);
 const [rows,setRows]=useState<HrAttendanceCalendar[]>([]),[total,setTotal]=useState(0),[year,setYear]=useState(""),[month,setMonth]=useState(""),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false);
 const [requests,setRequests]=useState<HrAttendanceRequest[]>([]),[requestTotal,setRequestTotal]=useState(0),[requestType,setRequestType]=useState(""),[requestStatus,setRequestStatus]=useState(""),[requestLoading,setRequestLoading]=useState(true),[requestLoadingMore,setRequestLoadingMore]=useState(false);
 const [formOpen,setFormOpen]=useState(false),[form,setForm]=useState(emptyForm),[reviewing,setReviewing]=useState<HrAttendanceRequest|null>(null),[reviewComment,setReviewComment]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const [daily,setDaily]=useState<HrAttendanceDailyResult[]>([]),[dailyStatus,setDailyStatus]=useState(""),[shifts,setShifts]=useState<HrAttendanceShift[]>([]),[employees,setEmployees]=useState<HrEmployee[]>([]),[ops,setOps]=useState({employeeId:"",shiftId:"",workDate:new Date().toISOString().slice(0,10),shiftCode:"",shiftName:"",startLocal:"09:00",endLocal:"18:00",ruleVersion:"v1",eventKey:"",occurredAt:"",eventType:"clock_in"});
 const [periods,setPeriods]=useState<HrAttendancePeriod[]>([]),[selectedPeriod,setSelectedPeriod]=useState<HrAttendancePeriod|null>(null),[summaries,setSummaries]=useState<HrAttendanceMonthSummary[]>([]),[payrollInput,setPayrollInput]=useState<HrAttendancePayrollInput|null>(null),[payrollVersions,setPayrollVersions]=useState<HrAttendancePayrollVersion[]>([]),[periodMonth,setPeriodMonth]=useState(new Date().toISOString().slice(0,7)),[correctionReason,setCorrectionReason]=useState("");
 const loadCalendars=useCallback(async()=>{if(!canRead){setLoading(false);return;}setLoading(true);setMessage("");try{const result=await hrApi.attendanceCalendars(getAccessToken(),1,20,{year:year?Number(year):undefined,month:month?Number(month):undefined});setRows(result.items);setTotal(result.total);}catch(error){setRows([]);setTotal(0);setMessage(hrLoadErrorMessage(error,"加载历史考勤月历失败"));}finally{setLoading(false);}},[canRead,month,year]);
 const loadRequests=useCallback(async()=>{if(!canRead){setRequestLoading(false);return;}setRequestLoading(true);setReviewing(null);try{const result=await hrApi.attendanceRequests(getAccessToken(),1,30,{type:requestType||undefined,status:requestStatus||undefined});setRequests(result.items);setRequestTotal(result.total);}catch(error){setRequests([]);setRequestTotal(0);setMessage(hrLoadErrorMessage(error,"加载考勤申请失败"));}finally{setRequestLoading(false);}},[canRead,requestStatus,requestType]);
 useEffect(()=>{void loadCalendars();},[loadCalendars]);useEffect(()=>{void loadRequests();},[loadRequests]);
 const loadDaily=useCallback(async()=>{if(!canRead)return;try{const result=await hrApi.attendanceDaily(getAccessToken(),1,31,{status:dailyStatus||undefined});setDaily(result.items);}catch(error){setMessage(hrLoadErrorMessage(error,"加载员工日考勤失败"));}},[canRead,dailyStatus]);
 useEffect(()=>{void loadDaily();},[loadDaily]);useEffect(()=>{if(!canOperate)return;void Promise.all([hrApi.attendanceShifts(getAccessToken()),hrApi.employees(getAccessToken(),1,100,{status:"active"})]).then(([shiftRows,employeeRows])=>{setShifts(shiftRows);setEmployees(employeeRows.items);setOps(current=>({...current,employeeId:current.employeeId||employeeRows.items[0]?.id||"",shiftId:current.shiftId||shiftRows[0]?.id||""}));}).catch(error=>setMessage(hrLoadErrorMessage(error,"加载考勤运营基础数据失败")));},[canOperate]);
 const loadPeriods=useCallback(async()=>{if(!canRead)return;try{const result=await hrApi.attendancePeriods(getAccessToken());setPeriods(result.items);}catch(error){setMessage(hrLoadErrorMessage(error,"加载月度考勤期间失败"));}},[canRead]);useEffect(()=>{void loadPeriods();},[loadPeriods]);
 useEffect(()=>{if(!selectedPeriod)setPayrollVersions([]);},[selectedPeriod]);
 const openPeriod=async(period:HrAttendancePeriod)=>{setSelectedPeriod(period);setPayrollInput(null);setPayrollVersions([]);try{const result=await hrApi.attendanceMonthSummaries(period.id,getAccessToken());setSummaries(result.items);if(canPayrollInput&&period.status==="closed"){const [input,versions]=await Promise.all([hrApi.payrollAttendanceInputs(period.id,getAccessToken()),hrApi.attendancePayrollVersions(period.id,getAccessToken())]);setPayrollInput(input);setPayrollVersions(versions);}}catch(error){setSummaries([]);setMessage(hrLoadErrorMessage(error,"加载月结详情失败"));}};
 const reviewDays=useMemo(()=>rows.reduce((count,row)=>count+row.days.filter(day=>day.symbolStatus==="needs_review").length,0),[rows]);
 const loadMoreCalendars=async()=>{if(loadingMore||rows.length>=total)return;setLoadingMore(true);try{const next=await hrApi.attendanceCalendars(getAccessToken(),Math.floor(rows.length/20)+1,20,{year:year?Number(year):undefined,month:month?Number(month):undefined});setRows(current=>[...current,...next.items.filter(item=>!current.some(row=>row.id===item.id))]);}catch(error){setMessage(hrLoadErrorMessage(error,"加载更多历史月历失败"));}finally{setLoadingMore(false);}};
 const loadMoreRequests=async()=>{if(requestLoadingMore||requests.length>=requestTotal)return;setRequestLoadingMore(true);try{const next=await hrApi.attendanceRequests(getAccessToken(),Math.floor(requests.length/30)+1,30,{type:requestType||undefined,status:requestStatus||undefined});setRequests(current=>[...current,...next.items.filter(item=>!current.some(row=>row.id===item.id))]);}catch(error){setMessage(hrLoadErrorMessage(error,"加载更多考勤申请失败"));}finally{setRequestLoadingMore(false);}};
 const saveDraft=async(event:React.FormEvent)=>{event.preventDefault();if(busy)return;setBusy(true);setMessage("");try{const correction=form.requestType==="correction";await hrApi.createAttendanceRequest({requestType:form.requestType,reason:form.reason,...(correction?{attendanceDate:form.attendanceDate}:{startAt:new Date(form.startAt).toISOString(),endAt:new Date(form.endAt).toISOString()})},getAccessToken());setForm(emptyForm);setFormOpen(false);await loadRequests();setMessage("考勤申请草稿已保存。");}catch(error){setMessage(hrLoadErrorMessage(error,"保存考勤申请草稿失败"));}finally{setBusy(false);}};
 const ownAction=async(row:HrAttendanceRequest,action:"submit"|"cancel")=>{if(busy)return;setBusy(true);setMessage("");try{if(action==="submit")await hrApi.submitAttendanceRequest(row.id,getAccessToken());else await hrApi.cancelAttendanceRequest(row.id,getAccessToken());await loadRequests();setMessage(action==="submit"?"考勤申请已提交。":"考勤申请已取消。");}catch(error){setMessage(hrLoadErrorMessage(error,"办理考勤申请失败"));}finally{setBusy(false);}};
 const review=async(decision:"approve"|"reject")=>{if(busy||!reviewing)return;if(decision==="reject"&&!reviewComment.trim()){setMessage("退回申请时请填写补充要求。");return;}setBusy(true);setMessage("");try{await hrApi.reviewAttendanceRequest(reviewing.id,decision,reviewComment.trim()||undefined,getAccessToken());setReviewing(null);setReviewComment("");await loadRequests();setMessage(decision==="approve"?"考勤申请已批准。":"考勤申请已退回。");}catch(error){setMessage(hrLoadErrorMessage(error,"审批考勤申请失败"));}finally{setBusy(false);}};
 const operate=async(kind:"shift"|"schedule"|"punch"|"recalculate")=>{if(busy)return;setBusy(true);setMessage("");try{if(kind==="shift")await hrApi.createAttendanceShift({shiftCode:ops.shiftCode,shiftName:ops.shiftName,startLocal:ops.startLocal,endLocal:ops.endLocal,ruleVersion:ops.ruleVersion},getAccessToken());if(kind==="schedule")await hrApi.createAttendanceSchedule({employeeId:ops.employeeId,shiftId:ops.shiftId,workDate:ops.workDate},getAccessToken());if(kind==="punch")await hrApi.createAttendancePunch({employeeId:ops.employeeId,eventKey:ops.eventKey,occurredAt:new Date(ops.occurredAt).toISOString(),eventType:ops.eventType,source:"manual"},getAccessToken());if(kind==="recalculate")await hrApi.recalculateAttendance({employeeId:ops.employeeId,workDate:ops.workDate,ruleVersion:ops.ruleVersion},getAccessToken());setMessage("考勤运营操作已完成。");const shiftRows=await hrApi.attendanceShifts(getAccessToken());setShifts(shiftRows);await loadDaily();}catch(error){setMessage(hrLoadErrorMessage(error,"考勤运营操作失败"));}finally{setBusy(false);}};
 const periodAction=async(action:"create"|"calculate"|"close"|"correct",period?:HrAttendancePeriod)=>{if(busy)return;setBusy(true);setMessage("");try{if(action==="create")await hrApi.createAttendancePeriod(`${periodMonth}-01`,getAccessToken());else if(period){if(action==="calculate")await hrApi.calculateAttendancePeriod(period.id,getAccessToken());if(action==="close")await hrApi.closeAttendancePeriod(period.id,getAccessToken());if(action==="correct")await hrApi.correctAttendancePeriod(period.id,correctionReason,getAccessToken());}setCorrectionReason("");setSelectedPeriod(null);setSummaries([]);setPayrollInput(null);await loadPeriods();setMessage(action==="correct"?"封账后更正批次已生成，旧快照保持不变。":"月度考勤期间已更新。");}catch(error){setMessage(hrLoadErrorMessage(error,"办理月度考勤失败"));}finally{setBusy(false);}};
 const forbidden=<main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="无权访问考勤管理"/></section></main>;
 if(!canRead)return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_ATTENDANCE_PAGE} fallback={forbidden}>{forbidden}</PermissionGuard>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_ATTENDANCE_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}>
  <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">考勤运营</span><h1>考勤管理</h1><p>提交与审批请假、加班、出差和考勤更正；旧系统月历保持只读，这些日期不是员工实际出勤记录，未知符号保留待复核。</p></div></section>
  {message?<p className="form-error" role="alert">{message}</p>:null}
  {canRequest?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">员工自助</span><h2>考勤申请</h2></div><button type="button" className="ds-button ds-button-primary" onClick={()=>setFormOpen(value=>!value)}>{formOpen?"收起申请":"新建申请"}</button></div>{formOpen?<form className={styles.formGrid} onSubmit={event=>void saveDraft(event)}><label className="form-field"><span>申请类型</span><select value={form.requestType} onChange={event=>setForm({...form,requestType:event.target.value,startAt:"",endAt:"",attendanceDate:""})}>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>{form.requestType==="correction"?<label className="form-field"><span>需更正日期</span><input required type="date" value={form.attendanceDate} onChange={event=>setForm({...form,attendanceDate:event.target.value})}/></label>:<><label className="form-field"><span>开始时间</span><input required type="datetime-local" value={form.startAt} onChange={event=>setForm({...form,startAt:event.target.value})}/></label><label className="form-field"><span>结束时间</span><input required type="datetime-local" min={form.startAt||undefined} value={form.endAt} onChange={event=>setForm({...form,endAt:event.target.value})}/></label></>}<label className="form-field"><span>申请事由</span><textarea required maxLength={2000} rows={3} value={form.reason} onChange={event=>setForm({...form,reason:event.target.value})}/></label><button className="ds-button ds-button-primary" disabled={busy} type="submit">保存草稿</button></form>:null}</section>:null}
  <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">办理队列</span><h2>{canApprove?"团队与园区申请":"我的申请"}</h2></div><strong>已加载 {requests.length}/{requestTotal}</strong></div><div className={styles.filterBar}><label className="form-field"><span>类型</span><select value={requestType} onChange={event=>setRequestType(event.target.value)}><option value="">全部类型</option>{Object.entries(typeLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label className="form-field"><span>状态</span><select value={requestStatus} onChange={event=>setRequestStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><div className="ds-mobile-record-list">{requestLoading?<p className={styles.emptyState}>正在加载考勤申请…</p>:requests.length?requests.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.employeeName?`${row.employeeName} · `:""}{typeLabels[row.requestType]??row.requestType}</strong><span>{row.requestNo}{row.employeeCode?` · ${row.employeeCode}`:""}</span><span>{row.attendanceDate??`${row.startAt?new Date(row.startAt).toLocaleString("zh-CN"):""} 至 ${row.endAt?new Date(row.endAt).toLocaleString("zh-CN"):""}`}</span><span>{row.durationMinutes?`${row.durationMinutes} 分钟 · `:""}{statusLabels[row.status]??row.status}</span><span>{row.reason}</span>{row.reviewComment?<span>审批意见：{row.reviewComment}</span>:null}<div className={styles.actionRow}>{row.isSelf&&["draft","returned"].includes(row.status)?<button type="button" className="ds-button" disabled={busy} onClick={()=>void ownAction(row,"submit")}>{row.status==="returned"?"重新提交":"提交审批"}</button>:null}{row.isSelf&&["draft","submitted","returned"].includes(row.status)?<button type="button" className="ds-button" disabled={busy} onClick={()=>void ownAction(row,"cancel")}>取消申请</button>:null}{canApprove&&!row.isSelf&&row.status==="submitted"?<button type="button" className="ds-button" onClick={()=>{setReviewing(row);setReviewComment("");}}>审核</button>:null}</div></article>):<p className={styles.emptyState}>当前范围没有考勤申请。</p>}</div>{requests.length<requestTotal?<button type="button" className="ds-button" disabled={requestLoadingMore} onClick={()=>void loadMoreRequests()}>{requestLoadingMore?"加载中":"加载更多申请"}</button>:null}</section>
  {reviewing?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">审批办理</span><h2>{reviewing.employeeName} · {typeLabels[reviewing.requestType]}</h2></div><button type="button" className="ds-button" onClick={()=>setReviewing(null)}>关闭</button></div><p>{reviewing.reason}</p><label className="form-field"><span>审批意见</span><textarea rows={3} maxLength={1000} value={reviewComment} onChange={event=>setReviewComment(event.target.value)} placeholder="退回时必填，批准时可选"/></label><div className={styles.actionRow}><button type="button" className="ds-button ds-button-primary" disabled={busy} onClick={()=>void review("approve")}>批准</button><button type="button" className="ds-button" disabled={busy} onClick={()=>void review("reject")}>退回补充</button></div></section>:null}
  <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">员工事实</span><h2>{canApprove?"团队考勤异常":"我的考勤日历"}</h2></div></div><div className={`${styles.filterBar} ${styles.compactFilterBar}`}><label className="form-field"><span>结果状态</span><select aria-label="日结果状态" value={dailyStatus} onChange={event=>setDailyStatus(event.target.value)}><option value="">全部状态</option><option value="missing_punch">缺卡</option><option value="late">迟到</option><option value="early_leave">早退</option><option value="corrected">已更正</option></select></label></div><div className="ds-mobile-record-list">{daily.length?daily.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.employeeName?`${row.employeeName} · `:""}{row.workDate}</strong><span>{row.resultStatus} · 工作 {row.workedMinutes} 分钟</span><span>迟到 {row.lateMinutes} 分钟 · 早退 {row.earlyMinutes} 分钟</span><span>{row.firstInAt?new Date(row.firstInAt).toLocaleString("zh-CN"):"未打上班卡"} / {row.lastOutAt?new Date(row.lastOutAt).toLocaleString("zh-CN"):"未打下班卡"}</span>{row.anomalyCodes.length?<span>异常：{row.anomalyCodes.join("、")}</span>:null}<small>计算版本 {row.calculationVersionId}</small></article>):<p className={styles.emptyState}>当前范围暂无员工日考勤结果。</p>}</div></section>
  {canOperate?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">HR 运营</span><h2>班次、排班、打卡与重算</h2></div></div><div className={styles.operationGrid}>
   <section className={styles.operationGroup}><header><div><span className={styles.operationIndex}>01</span><h3>当日排班</h3></div><small>为员工指定业务日期与班次</small></header><div className={styles.operationFields}><label className="form-field"><span>员工</span><select value={ops.employeeId} onChange={event=>setOps({...ops,employeeId:event.target.value})}>{employees.map(employee=><option key={employee.id} value={employee.id}>{employee.fullName} · {employee.employeeCode}</option>)}</select></label><label className="form-field"><span>业务日期</span><input type="date" value={ops.workDate} onChange={event=>setOps({...ops,workDate:event.target.value})}/></label><label className="form-field"><span>班次</span><select value={ops.shiftId} onChange={event=>setOps({...ops,shiftId:event.target.value})}>{shifts.map(shift=><option key={shift.id} value={shift.id}>{shift.shiftName} {shift.startLocal}-{shift.endLocal}</option>)}</select></label></div><button type="button" className="ds-button" disabled={busy||!ops.employeeId||!ops.shiftId} onClick={()=>void operate("schedule")}>保存当日排班</button></section>
   <section className={styles.operationGroup}><header><div><span className={styles.operationIndex}>02</span><h3>班次模板</h3></div><small>维护可复用的上下班时间</small></header><div className={styles.operationFields}><label className="form-field"><span>班次编码</span><input maxLength={64} value={ops.shiftCode} onChange={event=>setOps({...ops,shiftCode:event.target.value})}/></label><label className="form-field"><span>班次名称</span><input maxLength={100} value={ops.shiftName} onChange={event=>setOps({...ops,shiftName:event.target.value})}/></label><label className="form-field"><span>开始 / 结束</span><span className={styles.timeRange}><input aria-label="班次开始时间" type="time" value={ops.startLocal} onChange={event=>setOps({...ops,startLocal:event.target.value})}/><input aria-label="班次结束时间" type="time" value={ops.endLocal} onChange={event=>setOps({...ops,endLocal:event.target.value})}/></span></label></div><button type="button" className="ds-button" disabled={busy||!ops.shiftCode||!ops.shiftName} onClick={()=>void operate("shift")}>创建班次</button></section>
   <section className={styles.operationGroup}><header><div><span className={styles.operationIndex}>03</span><h3>人工打卡</h3></div><small>补录有来源标识的考勤事件</small></header><div className={styles.operationFields}><label className="form-field"><span>事件唯一键</span><input maxLength={160} value={ops.eventKey} onChange={event=>setOps({...ops,eventKey:event.target.value})}/></label><label className="form-field"><span>打卡时间</span><input type="datetime-local" value={ops.occurredAt} onChange={event=>setOps({...ops,occurredAt:event.target.value})}/></label><label className="form-field"><span>打卡类型</span><select value={ops.eventType} onChange={event=>setOps({...ops,eventType:event.target.value})}><option value="clock_in">上班卡</option><option value="clock_out">下班卡</option><option value="unknown">未知</option></select></label></div><button type="button" className="ds-button" disabled={busy||!ops.eventKey||!ops.occurredAt} onClick={()=>void operate("punch")}>录入打卡事件</button></section>
   <section className={styles.operationGroup}><header><div><span className={styles.operationIndex}>04</span><h3>日考勤重算</h3></div><small>按当前员工与业务日期重新计算</small></header><div className={styles.operationFields}><label className="form-field"><span>规则版本</span><input maxLength={32} value={ops.ruleVersion} onChange={event=>setOps({...ops,ruleVersion:event.target.value})}/></label><div className={styles.operationContext}><span>员工</span><strong>{employees.find(employee=>employee.id===ops.employeeId)?.fullName||"未选择"}</strong><small>{ops.workDate}</small></div></div><button type="button" className="ds-button ds-button-primary" disabled={busy||!ops.employeeId} onClick={()=>void operate("recalculate")}>重算员工日考勤</button></section>
  </div></section>:null}
  <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">月度封账</span><h2>月结期间与工资输入版本</h2></div>{canOperate?<div className={styles.periodToolbar}><label className="form-field"><span>期间月份</span><input aria-label="期间月份" type="month" value={periodMonth} onChange={event=>setPeriodMonth(event.target.value)}/></label><button type="button" className="ds-button ds-button-primary" disabled={busy} onClick={()=>void periodAction("create")}>新建月结期间</button></div>:null}</div><div className="ds-mobile-record-list">{periods.map(period=><article className="ds-mobile-record" key={period.id}><strong>{period.periodMonth.slice(0,7)} · {period.status}</strong><span>当前汇总版本 V{period.activeVersion}</span>{period.failureCode?<span>失败代码：{period.failureCode}，可修复日结果后重新计算</span>:null}<div className={styles.actionRow}><button type="button" className="ds-button" onClick={()=>void openPeriod(period)}>查看汇总</button>{canOperate&&["open","failed"].includes(period.status)?<button type="button" className="ds-button" disabled={busy} onClick={()=>void periodAction("calculate",period)}>{period.status==="failed"?"恢复并重算":"开始计算"}</button>:null}{canClose&&period.status==="review"?<button type="button" className="ds-button ds-button-primary" disabled={busy} onClick={()=>void periodAction("close",period)}>确认封账</button>:null}{canCorrect&&period.status==="closed"?<button type="button" className="ds-button" onClick={()=>setSelectedPeriod(period)}>创建更正批次</button>:null}</div></article>)}</div>{selectedPeriod?<div className="ds-mobile-record"><strong>{selectedPeriod.periodMonth.slice(0,7)} 汇总明细</strong>{summaries.map(row=><span key={row.id}>{row.employeeName??"本人"} · 工作 {row.workedMinutes} 分钟 · 迟到 {row.lateMinutes} · 早退 {row.earlyMinutes} · 缺勤 {row.absenceDays} 天 · 缺卡 {row.missingPunchDays} 天</span>)}{payrollInput?<span>工资输入批次 #{payrollInput.batchNo} · {payrollInput.batchType} · 仅供工资模块读取</span>:null}{canCorrect&&selectedPeriod.status==="closed"?<><label className="form-field"><span>更正原因</span><textarea required maxLength={1000} value={correctionReason} onChange={event=>setCorrectionReason(event.target.value)}/></label><button type="button" className="ds-button" disabled={busy||!correctionReason.trim()} onClick={()=>void periodAction("correct",selectedPeriod)}>生成新更正版本</button></>:null}</div>:null}</section>
  {payrollVersions.length?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">差异审计</span><h2>工资输入版本链</h2></div></div><div className="ds-mobile-record-list">{payrollVersions.map(version=><article className="ds-mobile-record" key={version.id}><strong>批次 #{version.batchNo} · {version.batchType} · {version.status}</strong><span>汇总版本 V{version.summaryVersion} · {version.employeeCount} 名员工</span><span>相对上一批次变更 {version.changedEmployeeCount} 名员工</span><small>{new Date(version.createdAt).toLocaleString("zh-CN")}</small></article>)}</div></section>:null}
  <section className={`ds-kpi-grid ${styles.compactKpiGrid}`} aria-label="历史考勤概览"><article className="ds-kpi-card"><span>月历模板</span><strong>{total}</strong><small>当前园区历史模板</small></article><article className="ds-kpi-card"><span>已加载日期</span><strong>{rows.reduce((count,row)=>count+row.dayCount,0)}</strong><small>真实自然日</small></article><article className="ds-kpi-card"><span>待复核符号</span><strong>{reviewDays}</strong><small>不猜测旧系统含义</small></article></section>
  <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">历史兼容</span><h2>旧系统月历目录</h2></div><strong>已加载 {rows.length}/{total}</strong></div><div className={styles.filterBar}><label className="form-field"><span>年份</span><input type="number" min="1900" max="2200" value={year} onChange={event=>setYear(event.target.value)}/></label><label className="form-field"><span>月份</span><select value={month} onChange={event=>setMonth(event.target.value)}><option value="">全部月份</option>{Array.from({length:12},(_,index)=><option key={index+1} value={index+1}>{index+1} 月</option>)}</select></label></div><div className="ds-mobile-record-list">{loading?<p className={styles.emptyState}>正在加载历史月历…</p>:rows.length?rows.map(calendar=><article className="ds-mobile-record" key={calendar.id}><strong>{calendar.year} 年 {calendar.month} 月 · {calendar.calendarName??"未命名月历"}</strong><span>{calendar.dayCount} 个自然日</span><div className={styles.tagList}>{calendar.days.map(day=><span className={day.symbolStatus==="needs_review"?"status-pill status-warning":"status-pill"} key={day.date}>{Number(day.date.slice(-2))}日 {day.legacySymbol??"空"}</span>)}</div></article>):<p className={styles.emptyState}>当前筛选条件下没有历史月历。</p>}</div>{rows.length<total?<button className="ds-button" type="button" disabled={loadingMore} onClick={()=>void loadMoreCalendars()}>{loadingMore?"加载中":"加载更多月历"}</button>:null}</section>
 </main></PermissionGuard>;
}
