"use client";
import { useEffect, useRef, useState } from "react";
import { HR_PERMISSIONS, type HrPayrollInsuranceChoice, type HrPayrollInsuranceSourcePage, type HrPayrollInsuranceSourceRequest } from "@jinhu/shared";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hasPermission } from "../../../lib/permissions";
import { hrApi } from "../../../lib/hr-api";
import styles from "../hr-workbench.module.css";

export function PayrollInsuranceSourceSelection({request,disabled,onChange}:{request:HrPayrollInsuranceSourceRequest|null;disabled:boolean;onChange:(choices:HrPayrollInsuranceChoice[]|null)=>void}) {
 const user=useAuthUser();
 const allowed=[HR_PERMISSIONS.HR_PAYROLL_RECONCILIATION_CALCULATE,HR_PERMISSIONS.HR_EMPLOYEE_READ,HR_PERMISSIONS.HR_INSURANCE_READ,HR_PERMISSIONS.HR_INSURANCE_AMOUNT_READ].every(permission=>hasPermission(user,permission));
 const requestKey=JSON.stringify(request),scopeKey=JSON.stringify([user?.id,user?.tenant_id,user?.park_id,user?.permissions,user?.roles,user?.is_super,user?.data_scope,user?.data_scopes,user?.field_policies,allowed]);
 const [page,setPage]=useState(1),[data,setData]=useState<HrPayrollInsuranceSourcePage|null>(null),[choices,setChoices]=useState<Record<string,HrPayrollInsuranceChoice>>({}),[error,setError]=useState(""),[loading,setLoading]=useState(false),[refresh,setRefresh]=useState(0);
 const context=useRef("");
 useEffect(()=>{const key=requestKey+scopeKey; if(context.current!==key){context.current=key;setPage(1);setChoices({});setData(null);onChange(null);}},[requestKey,scopeKey,onChange]);
 useEffect(()=>{
  setData(null);setError("");
  if(!request||!allowed)return;
  const abort=new AbortController();setLoading(true);
  hrApi.payrollInsuranceSourceOptions(request,getAccessToken(),page,abort.signal).then(result=>{if(!abort.signal.aborted)setData(result);}).catch(e=>{if(!abort.signal.aborted)setError(e instanceof Error?e.message:"读取社保来源失败");}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});
  return()=>abort.abort();
 // Request objects are regenerated by the parent; key captures their exact values.
 },[requestKey,scopeKey,page,refresh]);
 const selectedCount=Object.keys(choices).length;
 function select(employeeId:string,index:string){
  const next={...choices};delete next[employeeId];
  const choice=data?.items.find(employee=>employee.employeeId===employeeId)?.options[Number(index)];
  if(index!==""&&choice)next[employeeId]=choice;
  setChoices(next);onChange(data&&data.total>0&&Object.keys(next).length===data.total?Object.values(next).sort((a,b)=>a.employeeId.localeCompare(b.employeeId)):null);
 }
 if(!allowed)return <p className="ds-inline-note">选择社保来源需要员工、社保及金额读取权限，请由具备权限的核算人员操作。</p>;
 return <div className="ds-panel" style={{gridColumn:"1 / -1",padding:18,display:"grid",gap:16}}>
  <h3>逐员工选择社保来源</h3>
  <p className="ds-inline-note">请选择历史期间或现代确认版本。五险与公积金按已审核公式使用；不会自动替换来源。</p>
  {!request?<p>先选择工资来源和同月考勤输入。</p>:loading?<p role="status">正在读取可用来源…</p>:error?<p role="alert">{error}</p>:data?<>
   <p>已选 {selectedCount} / {data.total} 人 · {data.periodMonth.slice(0,7)}</p>
   <div className="ds-scene-grid">{data.items.map(employee=><article className="ds-scene-card" style={{display:"grid",gridTemplateColumns:"minmax(0,1fr)",gap:12}} key={employee.employeeId}>
    <strong>{employee.fullName} · {employee.employeeCode}</strong>
    <label className="form-field"><span>{employee.fullName}的社保来源</span><select disabled={disabled} value={employee.options.findIndex(option=>option.sourceId===choices[employee.employeeId]?.sourceId)<0?"":String(employee.options.findIndex(option=>option.sourceId===choices[employee.employeeId]?.sourceId))} onChange={event=>select(employee.employeeId,event.target.value)}>
     <option value="">请选择</option>{employee.options.map((option,index)=><option key={option.sourceKind+option.sourceId} value={index}>{option.sourceKind==="historical"?"历史期间":"现代确认版本"} · 版本 {option.expectedVersion}</option>)}
    </select></label>{!employee.options.length?<p>没有可用社保来源，暂不能核算该员工。</p>:null}
   </article>)}</div>
   <div className={styles.actionRow}><button type="button" className="ds-button" disabled={disabled||page<=1} onClick={()=>setPage(page-1)}>上一页</button><span>第 {page} 页</span><button type="button" className="ds-button" disabled={disabled||page*data.page_size>=data.total} onClick={()=>setPage(page+1)}>下一页</button></div>
  </>:null}
  <button type="button" className="ds-button" disabled={!request||disabled||loading} onClick={()=>{setChoices({});onChange(null);setRefresh(refresh+1);}}>刷新来源并重新选择</button>
 </div>;
}
