import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test from "node:test";
import { LegacyPersonnelAliasBackfillPlanError, buildLegacyPersonnelAliasBackfillPlan } from "../legacy-personnel-alias-backfill-plan.mjs";

const hash = value => createHash("sha256").update(value).digest("hex");
const h = value => hash(`test:${value}`);
const uuid = n => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const contract = JSON.parse(readFileSync(new URL("../contracts/legacy-personnel-alias-backfill-v1.json", import.meta.url)));
const input = (rows = [{ id: uuid(1), employeeId: uuid(11), source: h("a"), oldaddr: "北京", edulevel: "本科", nativePlace: null, degree: null }]) => ({ contract, binding: { codeSha256: h("code"), sourceEvidenceSha256: h("observation"), sourceSnapshotSha256: h("snapshot"), targetScope: { tenantId: "10000001", parkId: "20000001" } }, employees: rows.map(row => ({ id: row.employeeId, tenantId: "10000001", parkId: "20000001", isDeleted: false, sourceIdentitySha256: h(`employee:${row.employeeId}`) })), profiles: rows.map(row => ({ id: row.id, employeeId: row.employeeId, employeeSourceIdentitySha256: h(`employee:${row.employeeId}`), tenantId: "10000001", parkId: "20000001", isDeleted: false, sourceIdentitySha256: row.source, nativePlace: row.nativePlace, degree: row.degree })), sourceRecords: rows.map(row => ({ sourceIdentitySha256: row.source, sourceRowSha256: h(`row:${row.source}`), oldaddr: row.oldaddr, edulevel: row.edulevel })) });
const rejects = (value, code) => assert.throws(() => buildLegacyPersonnelAliasBackfillPlan(value), error => error instanceof LegacyPersonnelAliasBackfillPlanError && error.code === `PERSONNEL_ALIAS_PLAN_${code}`);

test("fill-null plan remains HOLD and does not mutate input", () => { const value = input(), before = structuredClone(value), plan = buildLegacyPersonnelAliasBackfillPlan(value); assert.equal(plan.authorizationGranted, false); assert.equal(plan.productionImport, "HOLD"); assert.equal(plan.summary.countByDisposition.FILL_NULL_ONLY, 1); assert.deepEqual(plan.records[0].privatePatch.map(x => x.targetField), ["nativePlace", "degree"]); assert.deepEqual(value, before); });
test("a differing modern value is preserved while an independent null field is filled", () => { const value = input([{ id: uuid(1), employeeId: uuid(11), source: h("a"), oldaddr: "北京", edulevel: "本科", nativePlace: "", degree: null }]), plan = buildLegacyPersonnelAliasBackfillPlan(value); assert.equal(plan.records[0].disposition, "FILL_NULL_ONLY"); assert.deepEqual(plan.records[0].privatePatch.map(entry => entry.targetField), ["degree"]); assert.deepEqual(plan.records[0].preservedDifferentFields, ["nativePlace"]); assert.deepEqual(plan.records[0].alreadyEqualFields, []); });
test("null or empty source values do not fill", () => { const plan = buildLegacyPersonnelAliasBackfillPlan(input([{ id: uuid(1), employeeId: uuid(11), source: h("a"), oldaddr: "", edulevel: null, nativePlace: null, degree: null }])); assert.equal(plan.records[0].disposition, "NO_SOURCE_VALUE"); });
test("malformed source, duplicate source identity, foreign/deleted/unowned rows fail closed", () => { const invalid = input(); invalid.sourceRecords[0].oldaddr = 7; rejects(invalid, "SOURCE_VALUE_INVALID"); const duplicate = input(); duplicate.sourceRecords.push(structuredClone(duplicate.sourceRecords[0])); rejects(duplicate, "DUPLICATE_SOURCE_IDENTITY"); const foreign = input(); foreign.profiles[0].parkId = "foreign"; rejects(foreign, "FOREIGN_PROFILE_SCOPE"); const deleted = input(); deleted.employees[0].isDeleted = true; rejects(deleted, "DELETED_EMPLOYEE"); const unowned = input(); unowned.profiles[0].employeeId = uuid(99); rejects(unowned, "UNOWNED_PROFILE"); });
test("unicode code-point length is bounded without truncation", () => { const valid = input([{ id: uuid(1), employeeId: uuid(11), source: h("a"), oldaddr: "🙂".repeat(50), edulevel: "学".repeat(24), nativePlace: null, degree: null }]); assert.equal(buildLegacyPersonnelAliasBackfillPlan(valid).records[0].disposition, "FILL_NULL_ONLY"); valid.sourceRecords[0].oldaddr += "🙂"; rejects(valid, "SOURCE_VALUE_TOO_LONG"); const degree = input(); degree.sourceRecords[0].edulevel = "学".repeat(25); rejects(degree, "SOURCE_VALUE_TOO_LONG"); });
test("reject NUL and malformed surrogate text in source, target, and scope", () => { for (const bad of ["a\0b", "\ud800", "\udc00"]) { const source = input(); source.sourceRecords[0].oldaddr = bad; rejects(source, "SOURCE_VALUE_INVALID"); const target = input(); target.profiles[0].nativePlace = bad; rejects(target, "PROFILE_VALUE_INVALID"); const scope = input(); scope.binding.targetScope.parkId = bad; rejects(scope, "SCOPE_INVALID"); } });
test("target values obey the declared native place and degree column lengths", () => { const nativePlace = input(); nativePlace.profiles[0].nativePlace = "🙂".repeat(129); rejects(nativePlace, "PROFILE_VALUE_TOO_LONG"); const degree = input(); degree.profiles[0].degree = "学".repeat(65); rejects(degree, "PROFILE_VALUE_TOO_LONG"); });
test("reject duplicate profile ids and multiple profiles for one employee", () => { const duplicateId = input([{ id: uuid(1), employeeId: uuid(11), source: h("a"), oldaddr: "甲", edulevel: null, nativePlace: null, degree: null }, { id: uuid(1), employeeId: uuid(12), source: h("b"), oldaddr: "乙", edulevel: null, nativePlace: null, degree: null }]); rejects(duplicateId, "DUPLICATE_PROFILE_ID"); const duplicateEmployee = input(); const second = structuredClone(duplicateEmployee.profiles[0]); second.id = uuid(2); second.sourceIdentitySha256 = h("second-profile-source"); duplicateEmployee.profiles.push(second); duplicateEmployee.sourceRecords.push({ sourceIdentitySha256: second.sourceIdentitySha256, sourceRowSha256: h("second-source-row"), oldaddr: "乙", edulevel: null }); rejects(duplicateEmployee, "MULTIPLE_PROFILES_PER_EMPLOYEE"); });
test("returned plan and every nested private structure are immutable", () => { const plan = buildLegacyPersonnelAliasBackfillPlan(input()); assert.ok(Object.isFrozen(plan.records)); assert.ok(Object.isFrozen(plan.records[0])); assert.ok(Object.isFrozen(plan.records[0].privatePatch)); assert.ok(Object.isFrozen(plan.records[0].privatePatch[0])); assert.ok(Object.isFrozen(plan.countByDisposition)); assert.throws(() => { plan.records[0].privatePatch[0].value = "tampered"; }, TypeError); assert.throws(() => { plan.countByDisposition.FILL_NULL_ONLY = 0; }, TypeError); });
test("plan hash is order stable, conserves identities, and replay is a no-op", () => { const rows = [{ id: uuid(2), employeeId: uuid(12), source: h("b"), oldaddr: "上海", edulevel: "硕士", nativePlace: null, degree: null }, { id: uuid(1), employeeId: uuid(11), source: h("a"), oldaddr: "北京", edulevel: "本科", nativePlace: null, degree: null }], left = input(rows), right = input([...rows].reverse()); const a = buildLegacyPersonnelAliasBackfillPlan(left), b = buildLegacyPersonnelAliasBackfillPlan(right); assert.equal(a.planSha256, b.planSha256); assert.equal(a.records.length, left.profiles.length); const replayRows = rows.map(row => ({ ...row, nativePlace: row.oldaddr, degree: row.edulevel })); const replay = buildLegacyPersonnelAliasBackfillPlan(input(replayRows)); assert.equal(replay.summary.countByDisposition.FILL_NULL_ONLY, 0); assert.equal(replay.summary.countByDisposition.ALREADY_EQUAL, 2); });
