"use client";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {useCallback,useEffect,useRef,useState} from "react";
import {useAuthUser} from "../../../lib/auth-context";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrDepartureApplication,type HrDepartureOptions} from "../../../lib/hr-api";
import {hasAnyPermission,hasPermission} from "../../../lib/permissions";
import {hrLoadErrorMessage} from "../hr-errors";
import styles from "../hr-workbench.module.css";

const labels:Record<string,string>={draft:"草稿",submitted:"待审批",returned:"已退回",approved:"清场办理中",cancelled:"已取消",applied:"已离职",pending:"待办理",completed:"已完成",waived:"已豁免",settled:"已结算",open:"待归档",closed:"已归档"};
const localToday=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Shanghai",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const done=(value:string)=>["completed","waived","settled","closed"].includes(value);

export function DepartureApplicationsPanel(){
 const user=useAuthUser(),canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_DEPARTURE_READ,HR_PERMISSIONS.HR_DEPARTURE_TEAM_READ,HR_PERMISSIONS.HR_DEPARTURE_SELF_READ]),canManage=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_MANAGE),canReview=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_REVIEW),canInterview=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_INTERVIEW),canSurvey=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_SURVEY),canHandover=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_HANDOVER),canWage=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_WAGE_SETTLE),canArchive=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_ARCHIVE_CLOSE),canApply=hasPermission(user,HR_PERMISSIONS.HR_DEPARTURE_APPLY);
 const [rows,setRows]=useState<HrDepartureApplication[]>([]),[options,setOptions]=useState<HrDepartureOptions>({employees:[]}),[editing,setEditing]=useState<HrDepartureApplication|null>(null),[processing,setProcessing]=useState<HrDepartureApplication|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),abortRef=useRef<AbortController|null>(null),busyRef=useRef(false);
 const load=useCallback(async()=>{if(!canRead){setLoading(false);return;}const c=new AbortController();abortRef.current?.abort();abortRef.current=c;setLoading(true);setError("");try{const [list,refs]=await Promise.all([hrApi.departureApplications(getAccessToken(),1,50,undefined,c.signal),canManage?hrApi.departureOptions(getAccessToken(),c.signal):Promise.resolve({employees:[]})]);if(!c.signal.aborted){setRows(list.items);setOptions(refs);setProcessing(current=>current?list.items.find(row=>row.id===current.id)??null:null);}}catch(e){if((e as Error).name!=="AbortError")setError(hrLoadErrorMessage(e,"加载离职申请失败"));}finally{if(!c.signal.aborted)setLoading(false);}},[canManage,canRead]);
 useEffect(()=>{void load();return()=>abortRef.current?.abort();},[load]);
 if(!canRead)return null;
 const begin=()=>{if(busyRef.current)return false;busyRef.current=true;setBusy(true);return true;},finish=()=>{busyRef.current=false;setBusy(false);};
 const reset=()=>setEditing(null);
 const save=async(form:FormData)=>{if(!begin())return;const body={applicationName:String(form.get("applicationName")),employeeId:String(form.get("employeeId")),applicationDate:String(form.get("applicationDate")),plannedDepartureDate:String(form.get("plannedDepartureDate")),departureType:String(form.get("departureType")),reason:String(form.get("reason"))};setError("");try{if(editing)await hrApi.updateDepartureApplication(editing.id,body,getAccessToken());else await hrApi.createDepartureApplication(body,getAccessToken());reset();await load();}catch(e){setError(hrLoadErrorMessage(e,editing?"修改离职申请失败":"创建离职申请失败"));}finally{finish();}};
 const action=async(row:HrDepartureApplication,kind:"submit"|"resubmit"|"cancel"|"approve"|"return"|"apply")=>{if(!begin())return;setError("");try{if(kind==="approve"||kind==="return")await hrApi.reviewDepartureApplication(row.id,kind,kind==="return"?"请补充或修正离职资料":"",getAccessToken());else if(kind==="apply")await hrApi.applyDepartureApplication(row.id,getAccessToken());else await hrApi.departureApplicationAction(row.id,kind,getAccessToken());await load();}catch(e){setError(hrLoadErrorMessage(e,"办理离职申请失败"));}finally{finish();}};
 const clearance=async(kind:"interview"|"survey"|"handover"|"wage"|"archive",form:FormData)=>{if(!processing||!begin())return;setError("");try{const note=String(form.get("note")),waived=form.get("waived")==="on",token=getAccessToken();if(kind==="interview")await hrApi.recordDepartureInterview(processing.id,{status:waived?"waived":"completed",place:String(form.get("place"))||undefined,summary:note},token);if(kind==="survey")await hrApi.recordDepartureSurvey(processing.id,{status:waived?"waived":"completed",reasonCodes:String(form.get("reasonCodes")).split(/[，,]/).map(x=>x.trim()).filter(Boolean),summary:note},token);if(kind==="handover")await hrApi.recordDepartureHandover(processing.id,{status:waived?"waived":"completed",handoverToEmployeeId:String(form.get("handoverToEmployeeId"))||undefined,summary:note},token);if(kind==="wage")await hrApi.recordDepartureWage(processing.id,{status:waived?"waived":"settled",note},token);if(kind==="archive")await hrApi.closeDepartureArchive(processing.id,{note},token);await load();}catch(e){setError(hrLoadErrorMessage(e,"办理离职清场事项失败"));}finally{finish();}};
 return <section className="ds-panel">
  <div className={styles.sectionHeading}><div><span className="ds-eyebrow">玉舟离职闭环</span><h2>离职申请与清场</h2></div><span>{loading?"加载中":`${rows.length} 条`}</span></div>
  {error?<p className="form-error" role="alert">{error}</p>:null}
  {canManage?<form key={editing?.id??"new"} className={styles.formGrid} action={save}>
   <label className="form-field"><span>申请名称</span><input name="applicationName" maxLength={128} defaultValue={editing?.applicationName??"员工离职办理"} required/></label>
   <label className="form-field"><span>员工</span><select name="employeeId" defaultValue={editing?.employeeId??""} required><option value="">请选择</option>{options.employees.map(x=><option key={x.id} value={x.id}>{x.employeeName} · {x.employeeCode}</option>)}</select></label>
   <label className="form-field"><span>离职类型</span><select name="departureType" defaultValue={editing?.departureType??"主动离职"}><option>主动离职</option><option>协商解除</option><option>合同终止</option><option>公司解除</option><option>退休</option><option>其他</option></select></label>
   <label className="form-field"><span>申请日期</span><input name="applicationDate" type="date" defaultValue={editing?.applicationDate??localToday()} required/></label>
   <label className="form-field"><span>计划离职日期</span><input name="plannedDepartureDate" type="date" min={editing?.applicationDate??localToday()} defaultValue={editing?.plannedDepartureDate??localToday()} required/></label>
   <label className={`form-field ${styles.fullWidth}`}><span>离职原因</span><textarea name="reason" maxLength={2000} defaultValue={editing?.reason} required/></label>
   <div className={styles.actionRow}><button className="ds-button ds-button-primary" disabled={busy}>{editing?"保存修改":"保存申请草稿"}</button>{editing?<button type="button" className="ds-button" disabled={busy} onClick={reset}>放弃修改</button>:null}</div>
  </form>:null}
  <div className="ds-mobile-record-list">{rows.length?rows.map(row=><article className="ds-mobile-record" key={row.id}>
   <strong>{row.employeeName} · {labels[row.status]??row.status}</strong><span>{row.applicationNo} · {row.applicationDate} 申请 · {row.plannedDepartureDate} 计划离职</span><span>{row.orgName??"未设部门"} · {row.departureType}</span>
   {row.status==="approved"?<span>面谈 {labels[row.interviewStatus]??row.interviewStatus} · 调查 {labels[row.surveyStatus]??row.surveyStatus} · 交接 {labels[row.handoverStatus]??row.handoverStatus} · 工资 {labels[row.wageStatus]??row.wageStatus} · 档案 {labels[row.archiveStatus]??row.archiveStatus}</span>:null}
   <div className={styles.actionRow}>{canManage&&["draft","returned"].includes(row.status)?<button className="ds-button" disabled={busy} onClick={()=>setEditing(row)}>修改</button>:null}{canManage&&row.status==="draft"?<button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"submit")}>提交审批</button>:null}{canManage&&row.status==="returned"?<button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"resubmit")}>重新提交</button>:null}{canManage&&["draft","submitted","returned"].includes(row.status)?<button className="ds-button" disabled={busy} onClick={()=>void action(row,"cancel")}>取消</button>:null}{canReview&&row.status==="submitted"?<><button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"approve")}>批准</button><button className="ds-button" disabled={busy} onClick={()=>void action(row,"return")}>退回</button></>:null}{row.status==="approved"&&(canInterview||canSurvey||canHandover||canWage||canArchive)?<button className="ds-button" disabled={busy} onClick={()=>setProcessing(row)}>办理清场</button>:null}{canApply&&row.status==="approved"?<button className="ds-button ds-button-primary" disabled={busy||row.plannedDepartureDate>localToday()||![row.interviewStatus,row.surveyStatus,row.handoverStatus,row.wageStatus,row.archiveStatus].every(done)} onClick={()=>void action(row,"apply")}>确认离职生效</button>:null}</div>
  </article>):loading?<p>正在加载离职申请…</p>:<p>暂无离职申请。</p>}</div>
  {processing?<div className={styles.operationGroup}><header><div><span className="ds-eyebrow">清场办理</span><h3>{processing.employeeName} · {processing.applicationNo}</h3></div><button className="ds-button" onClick={()=>setProcessing(null)}>关闭</button></header><div className={styles.operationGrid}>
   {canInterview&&!done(processing.interviewStatus)?<form action={form=>clearance("interview",form)}><strong>离职面谈</strong><label className="form-field"><span>地点</span><input name="place" maxLength={200}/></label><label className="form-field"><span>面谈纪要</span><textarea name="note" required maxLength={2000}/></label><label><input name="waived" type="checkbox"/> 经审批豁免</label><button className="ds-button ds-button-primary" disabled={busy}>确认</button></form>:null}
   {canSurvey&&!done(processing.surveyStatus)?<form action={form=>clearance("survey",form)}><strong>离职调查</strong><label className="form-field"><span>原因代码（逗号分隔）</span><input name="reasonCodes" maxLength={500}/></label><label className="form-field"><span>调查结论</span><textarea name="note" required maxLength={2000}/></label><label><input name="waived" type="checkbox"/> 经审批豁免</label><button className="ds-button ds-button-primary" disabled={busy}>确认</button></form>:null}
   {canHandover&&!done(processing.handoverStatus)?<form action={form=>clearance("handover",form)}><strong>工作交接</strong><label className="form-field"><span>接交员工</span><select name="handoverToEmployeeId"><option value="">请选择或勾选豁免</option>{options.employees.filter(x=>x.id!==processing.employeeId).map(x=><option key={x.id} value={x.id}>{x.employeeName}</option>)}</select></label><label className="form-field"><span>交接说明</span><textarea name="note" required maxLength={2000}/></label><label><input name="waived" type="checkbox"/> 经审批豁免</label><button className="ds-button ds-button-primary" disabled={busy}>确认</button></form>:null}
   {canWage&&!done(processing.wageStatus)?<form action={form=>clearance("wage",form)}><strong>工资结算</strong><label className="form-field"><span>结算说明</span><textarea name="note" required maxLength={1000}/></label><label><input name="waived" type="checkbox"/> 经审批豁免</label><button className="ds-button ds-button-primary" disabled={busy}>确认</button></form>:null}
   {canArchive&&done(processing.interviewStatus)&&done(processing.surveyStatus)&&done(processing.handoverStatus)&&done(processing.wageStatus)&&processing.archiveStatus!=="closed"?<form action={form=>clearance("archive",form)}><strong>人事档案关闭</strong><label className="form-field"><span>归档说明</span><textarea name="note" required maxLength={1000}/></label><button className="ds-button ds-button-primary" disabled={busy}>关闭档案</button></form>:null}
  </div></div>:null}
 </section>;
}
