"use client";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {useCallback,useEffect,useRef,useState} from "react";
import {useAuthUser} from "../../../lib/auth-context";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrEmployee,type HrProbationApplication} from "../../../lib/hr-api";
import {hasPermission} from "../../../lib/permissions";
import {hrLoadErrorMessage} from "../hr-errors";
import styles from "../hr-workbench.module.css";

const statusLabels:Record<string,string>={draft:"草稿",submitted:"待审批",returned:"已退回",approved:"已批准",cancelled:"已取消",confirmed:"已转正"};

export function ProbationApplicationsPanel(){
 const user=useAuthUser(),canRead=hasPermission(user,HR_PERMISSIONS.HR_LIFECYCLE_READ),canAssign=hasPermission(user,HR_PERMISSIONS.HR_LIFECYCLE_ASSIGN),canReview=hasPermission(user,HR_PERMISSIONS.HR_LIFECYCLE_REVIEW),canConfirm=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYMENT_TRANSITION);
 const [rows,setRows]=useState<HrProbationApplication[]>([]),[employees,setEmployees]=useState<HrEmployee[]>([]),[editing,setEditing]=useState<HrProbationApplication|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(""),abortRef=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{if(!canRead){setLoading(false);return;}const controller=new AbortController();abortRef.current?.abort();abortRef.current=controller;setLoading(true);setError("");try{const [applications,options]=await Promise.all([hrApi.probationApplications(getAccessToken(),1,50,undefined,controller.signal),canAssign?hrApi.employees(getAccessToken(),1,100,{status:"probation"}):Promise.resolve({items:[],total:0,page:1,page_size:100})]);if(!controller.signal.aborted){setRows(applications.items);setEmployees(options.items);}}catch(e){if((e as Error).name!=="AbortError")setError(hrLoadErrorMessage(e,"加载转正申请失败"));}finally{if(!controller.signal.aborted)setLoading(false);}},[canAssign,canRead]);
 useEffect(()=>{void load();return()=>abortRef.current?.abort();},[load]);
 if(!canRead)return null;
 const save=async(form:FormData)=>{if(busy)return;const employeeIds=form.getAll("employeeId").map(String),participants=employeeIds.map(employeeId=>({employeeId,plannedConfirmationDate:String(form.get(`planned:${employeeId}`))}));if(!employeeIds.length){setError("请至少选择一名试用期员工");return;}if(participants.some(item=>!item.plannedConfirmationDate)){setError("请填写所有已选员工的计划转正日期");return;}const body={applicationName:String(form.get("applicationName")),applicationDate:String(form.get("applicationDate")),reason:String(form.get("reason")),participants};setBusy(true);setError("");try{if(editing)await hrApi.updateProbationApplication(editing.id,body,getAccessToken());else await hrApi.createProbationApplication(body,getAccessToken());setEditing(null);await load();}catch(e){setError(hrLoadErrorMessage(e,editing?"修改转正申请失败":"创建转正申请失败"));}finally{setBusy(false);}};
 const action=async(row:HrProbationApplication,kind:"submit"|"resubmit"|"cancel"|"approve"|"return"|"confirm")=>{if(busy)return;setBusy(true);setError("");try{if(kind==="approve"||kind==="return")await hrApi.reviewProbationApplication(row.id,kind,kind==="return"?"请补充或修正转正信息":"",getAccessToken());else if(kind==="confirm")await hrApi.confirmProbationApplication(row.id,getAccessToken());else await hrApi.probationApplicationAction(row.id,kind,getAccessToken());await load();}catch(e){setError(hrLoadErrorMessage(e,"办理转正申请失败"));}finally{setBusy(false);}};
 return <section className="ds-panel">
  <div className={styles.sectionHeading}><div><span className="ds-eyebrow">玉舟功能复现</span><h2>员工转正申请</h2></div><span>{loading?"加载中":`${rows.length} 条`}</span></div>
  {error?<p className="form-error" role="alert">{error}</p>:null}
  {canAssign?<form key={editing?.id??"new"} className={styles.formGrid} action={save}>
   <label className="form-field"><span>申请名称</span><input name="applicationName" maxLength={128} defaultValue={editing?.applicationName} required/></label>
   <label className="form-field"><span>申请日期</span><input name="applicationDate" type="date" defaultValue={editing?.applicationDate} required/></label>
   <label className={`form-field ${styles.fullWidth}`}><span>申请内容</span><textarea name="reason" maxLength={2000} defaultValue={editing?.reason} required/></label>
   <fieldset className={`${styles.fullWidth} ${styles.profileGroup}`}><legend>试用期员工与计划转正日期</legend>{employees.length?employees.map(employee=>{const participant=editing?.participants.find(item=>item.employeeId===employee.id);return <div className={styles.inlineFields} key={employee.id}><label><input type="checkbox" name="employeeId" value={employee.id} defaultChecked={Boolean(participant)}/><span>{employee.fullName} · {employee.employeeCode}</span></label><label className="form-field"><span>计划转正日期</span><input type="date" name={`planned:${employee.id}`} defaultValue={participant?.plannedConfirmationDate}/></label></div>}):<p>当前没有可申请转正的试用期员工。</p>}</fieldset>
   <div className={styles.actionRow}><button className="ds-button ds-button-primary" disabled={busy||!employees.length}>{editing?"保存修改":"保存申请草稿"}</button>{editing?<button className="ds-button" type="button" disabled={busy} onClick={()=>setEditing(null)}>放弃修改</button>:null}</div>
  </form>:null}
  <div className="ds-mobile-record-list">{rows.length?rows.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.applicationName} · {statusLabels[row.status]??row.status}</strong><span>{row.applicationNo} · {row.applicationDate}</span><span>{row.participants.map(p=>`${p.employeeName}（${p.plannedConfirmationDate}）`).join("、")}</span><div className={styles.actionRow}>{canAssign&&["draft","returned"].includes(row.status)?<button className="ds-button" disabled={busy} onClick={()=>setEditing(row)}>修改</button>:null}{canAssign&&row.status==="draft"?<button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"submit")}>提交审批</button>:null}{canAssign&&row.status==="returned"?<button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"resubmit")}>重新提交</button>:null}{canAssign&&["draft","submitted","returned"].includes(row.status)?<button className="ds-button" disabled={busy} onClick={()=>void action(row,"cancel")}>取消申请</button>:null}{canReview&&row.status==="submitted"?<><button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"approve")}>批准</button><button className="ds-button" disabled={busy} onClick={()=>void action(row,"return")}>退回</button></>:null}{canConfirm&&row.status==="approved"?<button className="ds-button ds-button-primary" disabled={busy} onClick={()=>void action(row,"confirm")}>确认转正</button>:null}</div></article>):loading?<p>正在加载转正申请…</p>:<p>暂无转正申请。</p>}</div>
 </section>;
}
