"use client";
import { useState,type FormEvent } from "react";
import type { FileRecord } from "@jinhu/shared";
import { FileUploader } from "../../components/files/FileUploader";
import { apartmentsApi } from "../../lib/apartments-api";
import { getAccessToken } from "../../lib/authz";
import styles from "./ApartmentWorkbench.module.css";
export function ApartmentHandoverAction({stayId,type,onDone,onError}:{stayId:string;type:'check-in'|'check-out';onDone:()=>Promise<void>;onError:(v:string)=>void}){
 const [files,setFiles]=useState<string[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false);
 const uploaded=(file:FileRecord)=>setFiles(v=>[...v,file.id]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!files.length){onError('现场交接至少上传一张照片');return}if(busy)return;const form=new FormData(event.currentTarget);setBusy(true);try{await apartmentsApi.mutate(`/apartments/stays/${stayId}/${type}`,{items:[{name:'房间及墙地面',condition:form.get('room_condition')},{name:'家具家电',condition:form.get('facility_condition')},{name:'卫生清洁',condition:form.get('cleaning_condition')}],keys:[{name:'入户钥匙',quantity:Number(form.get('door_key_count'))},{name:'门禁/电梯卡',quantity:Number(form.get('access_card_count'))}],water_meter_reading:form.get('water_meter_reading')||undefined,electricity_meter_reading:form.get('electricity_meter_reading')||undefined,exception_note:form.get('exception_note')||undefined,photo_file_ids:files},getAccessToken());setOpen(false);setFiles([]);await onDone()}catch(e){onError(e instanceof Error?e.message:'交接失败')}finally{setBusy(false)}};
 if(!open)return <button className="ds-button ds-button-primary" onClick={()=>setOpen(true)}>{type==='check-in'?'办理入住':'完成验收'}</button>;
 return <form className={`${styles.inlinePanel} ${styles.form}`} onSubmit={submit}><label className="form-field"><span>房间及墙地面</span><select name="room_condition" required><option value="normal">完好</option><option value="damaged">有损坏</option><option value="pending_repair">待维修</option></select></label><label className="form-field"><span>家具家电</span><select name="facility_condition" required><option value="normal">齐全完好</option><option value="damaged">有损坏</option><option value="missing">有缺失</option></select></label><label className="form-field"><span>卫生清洁</span><select name="cleaning_condition" required><option value="qualified">合格</option><option value="reclean_required">需返工</option></select></label><label className="form-field"><span>入户钥匙数</span><input name="door_key_count" type="number" min="0" max="20" defaultValue="2" onFocus={e=>e.currentTarget.select()} required/></label><label className="form-field"><span>门禁/电梯卡数</span><input name="access_card_count" type="number" min="0" max="20" defaultValue="1" onFocus={e=>e.currentTarget.select()} required/></label><label className="form-field"><span>水表读数</span><input name="water_meter_reading" type="number" min="0" max="9999999999.999" step="0.001" onFocus={e=>e.currentTarget.select()}/></label><label className="form-field"><span>电表读数</span><input name="electricity_meter_reading" type="number" min="0" max="9999999999.999" step="0.001" onFocus={e=>e.currentTarget.select()}/></label><label className={`form-field ${styles.wide}`}><span>异常与处理说明</span><textarea name="exception_note" maxLength={1000} placeholder="有损坏、缺失、读数异常时必须说明"/></label><div className={styles.wide}><FileUploader bizType={type==='check-in'?'apartment_move_in_handover':'apartment_move_out_handover'} policyKey="image" bizId={stayId} compact onUploaded={uploaded}/></div><div className={`${styles.actions} ${styles.wide}`}><button className="ds-button ds-button-primary" disabled={busy}>{busy?'提交中…':`确认交接（${files.length}张）`}</button><button className="ds-button ds-button-secondary" type="button" onClick={()=>setOpen(false)}>取消</button></div></form>;
}
