"use client";
import { useEffect,useState,type FormEvent } from "react";
import { apartmentsApi,type ApartmentRecord } from "../../lib/apartments-api";
import { getAccessToken } from "../../lib/authz";
import styles from "./ApartmentWorkbench.module.css";
export function ApartmentCreatePanel({view,onDone,onError}:{view:string;onDone:()=>Promise<void>;onError:(v:string)=>void}){
 const [options,setOptions]=useState<ApartmentRecord[]>([]),[busy,setBusy]=useState(false),[reason,setReason]=useState('');
 useEffect(()=>{if(view==='rooms')void apartmentsApi.unitCandidates(getAccessToken()).then(setOptions).catch(()=>undefined);if(view==='applications')void apartmentsApi.settings(getAccessToken()).then(x=>setReason(x.default_application_reason)).catch(()=>undefined)},[view]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{if(view==='rooms')await apartmentsApi.mutate('/apartments/rooms',{unit_id:f.get('unit_id'),room_type:f.get('room_type'),gender_policy:f.get('gender_policy'),capacity:Number(f.get('capacity')),facilities:String(f.get('facilities')||'').split('、').filter(Boolean)},getAccessToken());if(view==='applications'){const app=await apartmentsApi.mutate<ApartmentRecord>('/apartments/applications',{applicant_name:f.get('applicant_name'),applicant_type:f.get('applicant_type'),requested_room_type:f.get('requested_room_type'),requested_start_date:f.get('requested_start_date'),requested_end_date:f.get('requested_end_date')||undefined,reason:f.get('reason')},getAccessToken());await apartmentsApi.mutate(`/apartments/applications/${app.id}/submit`,undefined,getAccessToken())}e.currentTarget.reset();await onDone()}catch(err){onError(err instanceof Error?err.message:'保存失败')}finally{setBusy(false)}};
 if(view!=='rooms'&&view!=='applications')return null;
 return <section className="ds-panel"><form className={styles.form} onSubmit={submit}>{view==='rooms'?<><label className={styles.wide}>资产房号<select name="unit_id" required><option value="">请选择未占用房源</option>{options.map(x=><option value={x.id} key={x.id}>{String(x.building_name??'')} {String(x.floor_name??'')} {String(x.unit_name??x.unit_code)}</option>)}</select></label><label>公寓类型<select name="room_type"><option value="talent">人才公寓</option><option value="executive">高管宿舍</option><option value="employee">员工宿舍</option></select></label><label>入住性别<select name="gender_policy"><option value="any">不限</option><option value="male">男</option><option value="female">女</option></select></label><label>床位数<input name="capacity" type="number" min="1" max="20" defaultValue="1" required/></label><label>设施（顿号分隔）<input name="facilities" placeholder="空调、衣柜、热水器"/></label></>:<><label>入住人姓名<input name="applicant_name" maxLength={100} required/></label><label>人员类别<select name="applicant_type"><option value="internal_employee">集团员工</option><option value="subsidiary_employee">下属企业员工</option><option value="executive">高级管理人员</option><option value="external_talent">引进人才</option></select></label><label>房型<select name="requested_room_type"><option value="talent">人才公寓</option><option value="executive">高管宿舍</option><option value="employee">员工宿舍</option></select></label><label>计划入住<input name="requested_start_date" type="date" required/></label><label>计划退房<input name="requested_end_date" type="date"/></label><label className={styles.wide}>入住理由（已带出默认内容，可直接修改）<textarea name="reason" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} required/></label></>}<div className={styles.formActions}><button className="primary-button" disabled={busy}>{busy?'正在保存…':view==='rooms'?'新增公寓房源':'提交入住申请'}</button></div></form></section>;
}
