"use client";
import { useEffect,useState,type FormEvent } from "react";
import type { FileRecord } from "@jinhu/shared";
import { FileUploader } from "../../components/files/FileUploader";
import { apartmentsApi,type ApartmentHandoverMeter } from "../../lib/apartments-api";
import { getAccessToken } from "../../lib/authz";
import styles from "./ApartmentWorkbench.module.css";
export function ApartmentHandoverAction({stayId,type,onDone,onError}:{stayId:string;type:'check-in'|'check-out';onDone:()=>Promise<void>;onError:(v:string)=>void}){
 const [files,setFiles]=useState<string[]>([]),[open,setOpen]=useState(false),[busy,setBusy]=useState(false),[meters,setMeters]=useState<ApartmentHandoverMeter[]>([]),[meterValues,setMeterValues]=useState<Record<string,string>>({}),[meterLoading,setMeterLoading]=useState(false),[meterError,setMeterError]=useState('');
 useEffect(()=>{if(!open)return;let active=true;setMeterLoading(true);setMeterError('');void apartmentsApi.handoverMeters(stayId,getAccessToken()).then(items=>{if(active){setMeters(items);setMeterValues(Object.fromEntries(items.map(item=>[item.id,item.current_reading])));}}).catch((error:Error)=>{if(active)setMeterError(error.message)}).finally(()=>{if(active)setMeterLoading(false)});return()=>{active=false}},[open,stayId]);
 const uploaded=(file:FileRecord)=>setFiles(v=>[...v,file.id]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!files.length){onError('现场交接至少上传一张照片');return}if(busy||meterLoading||meterError)return;const form=new FormData(event.currentTarget);setBusy(true);try{await apartmentsApi.mutate(`/apartments/stays/${stayId}/${type}`,{items:[{name:'房间及墙地面',condition:form.get('room_condition')},{name:'家具家电',condition:form.get('facility_condition')},{name:'卫生清洁',condition:form.get('cleaning_condition')}],keys:[{name:'入户钥匙',quantity:Number(form.get('door_key_count'))},{name:'门禁/电梯卡',quantity:Number(form.get('access_card_count'))}],meter_readings:meters.map(meter=>({meter_id:meter.id,reading_value:meterValues[meter.id]})),exception_note:form.get('exception_note')||undefined,photo_file_ids:files},getAccessToken());setOpen(false);setFiles([]);await onDone()}catch(e){onError(e instanceof Error?e.message:'交接失败')}finally{setBusy(false)}};
 if(!open)return <button className="ds-button ds-button-primary" onClick={()=>setOpen(true)}>{type==='check-in'?'办理入住':'完成验收'}</button>;
 return <form className={`${styles.inlinePanel} ${styles.form}`} onSubmit={submit}><label className="form-field"><span>房间及墙地面</span><select name="room_condition" required><option value="normal">完好</option><option value="damaged">有损坏</option><option value="pending_repair">待维修</option></select></label><label className="form-field"><span>家具家电</span><select name="facility_condition" required><option value="normal">齐全完好</option><option value="damaged">有损坏</option><option value="missing">有缺失</option></select></label><label className="form-field"><span>卫生清洁</span><select name="cleaning_condition" required><option value="qualified">合格</option><option value="reclean_required">需返工</option></select></label><label className="form-field"><span>入户钥匙数</span><input name="door_key_count" type="number" min="0" max="20" defaultValue="2" onFocus={e=>e.currentTarget.select()} required/></label><label className="form-field"><span>门禁/电梯卡数</span><input name="access_card_count" type="number" min="0" max="20" defaultValue="1" onFocus={e=>e.currentTarget.select()} required/></label>{meterLoading?<p className={styles.wide}>正在加载该房号的能源表计…</p>:meterError?<p className={styles.wide}>表计加载失败：{meterError}</p>:meters.length?meters.map(meter=><label className="form-field" key={meter.id}><span>{meter.meter_type==='WATER'?'水表':'电表'} · {meter.meter_name}</span><input type="number" min={meter.current_reading} max="99999999999999.9999" step="0.0001" value={meterValues[meter.id]??''} onChange={e=>setMeterValues(values=>({...values,[meter.id]:e.target.value}))} onFocus={e=>e.currentTarget.select()} required/><small>{meter.meter_code} · 当前 {meter.current_reading} {meter.unit}</small></label>):<p className={styles.wide}>该房号尚未接入水电表，本次仅保存交接档案。</p>}<label className={`form-field ${styles.wide}`}><span>异常与处理说明</span><textarea name="exception_note" maxLength={1000} placeholder="有损坏、缺失、读数异常时必须说明"/></label><div className={styles.wide}><FileUploader bizType={type==='check-in'?'apartment_move_in_handover':'apartment_move_out_handover'} policyKey="image" bizId={stayId} compact onUploaded={uploaded}/></div><div className={`${styles.actions} ${styles.wide}`}><button className="ds-button ds-button-primary" disabled={busy||meterLoading||Boolean(meterError)}>{busy?'提交中…':`确认交接（${files.length}张）`}</button><button className="ds-button ds-button-secondary" type="button" onClick={()=>setOpen(false)}>取消</button></div></form>;
}
