"use client";
import { useEffect,useRef,useState,type FormEvent } from "react";
import { apartmentsApi,type ApartmentCandidatePage,type ApartmentRecord } from "../../lib/apartments-api";
import { getAccessToken } from "../../lib/authz";
import styles from "./ApartmentWorkbench.module.css";

const nextDate=(value:string)=>{if(!value)return undefined;const [year,month,day]=value.split("-").map(Number);return new Date(Date.UTC(year!,month!-1,day!+1)).toISOString().slice(0,10)};
const emptyCandidates:ApartmentCandidatePage={items:[],total:0,page:1,page_size:20,facets:{buildings:[],floors:[]}};
const reasonLabels:Record<string,string>={already_apartment_managed:"已纳入公寓",unit_disabled:"房号已停用",asset_parent_mapping_incomplete:"资产父级映射不完整",operating_config_disabled:"物业运营已停用",operating_mode_conflict:"已配置其他经营模式",occupied_by_other_domain:"已被其他业务占用"};

export function ApartmentCreatePanel({view,onDone,onError}:{view:string;onDone:()=>Promise<void>;onError:(v:string)=>void}){
 const [candidates,setCandidates]=useState<ApartmentCandidatePage>(emptyCandidates),[candidatePage,setCandidatePage]=useState(1),[candidateKeyword,setCandidateKeyword]=useState(''),[candidateBuilding,setCandidateBuilding]=useState(''),[candidateFloor,setCandidateFloor]=useState(''),[eligibleOnly,setEligibleOnly]=useState(false),[selectedUnitId,setSelectedUnitId]=useState(''),[candidateLoading,setCandidateLoading]=useState(false),[busy,setBusy]=useState(false),[reason,setReason]=useState(''),[startDate,setStartDate]=useState('');
 const candidateRequest=useRef(0);
 const onErrorRef=useRef(onError);onErrorRef.current=onError;
 useEffect(()=>{if(view==='rooms'){const generation=++candidateRequest.current;setCandidateLoading(true);setSelectedUnitId('');const query=new URLSearchParams({page:String(candidatePage),page_size:'20',eligible_only:String(eligibleOnly)});if(candidateKeyword.trim())query.set('keyword',candidateKeyword.trim());if(candidateBuilding)query.set('building_id',candidateBuilding);if(candidateFloor)query.set('floor_id',candidateFloor);void apartmentsApi.unitCandidates(query,getAccessToken()).then(result=>{if(generation===candidateRequest.current)setCandidates(result)}).catch((error:Error)=>{if(generation===candidateRequest.current)onErrorRef.current(error.message)}).finally(()=>{if(generation===candidateRequest.current)setCandidateLoading(false)});}if(view==='applications')void apartmentsApi.settings(getAccessToken()).then(x=>setReason(x.default_application_reason)).catch(()=>undefined)},[candidateBuilding,candidateFloor,candidateKeyword,candidatePage,eligibleOnly,view]);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{
  if(view==='rooms')await apartmentsApi.mutate('/apartments/rooms',{unit_id:f.get('unit_id'),room_type:f.get('room_type'),gender_policy:f.get('gender_policy'),capacity:Number(f.get('capacity')),facilities:String(f.get('facilities')||'').split('、').map(x=>x.trim()).filter(Boolean)},getAccessToken());
  if(view==='applications'){
   const app=await apartmentsApi.mutate<ApartmentRecord>('/apartments/applications',{applicant_name:f.get('applicant_name'),applicant_type:f.get('applicant_type'),organization_name:f.get('organization_name')||undefined,department_name:f.get('department_name')||undefined,job_title:f.get('job_title')||undefined,mobile_masked:f.get('mobile_masked')||undefined,emergency_contact_name:f.get('emergency_contact_name'),emergency_contact_mobile:f.get('emergency_contact_mobile'),household_size:Number(f.get('household_size')),accompanying_names:f.get('accompanying_names')||undefined,vehicle_plate:f.get('vehicle_plate')||undefined,accommodation_notes:f.get('accommodation_notes')||undefined,policy_accepted:f.get('policy_accepted')==='on',requested_room_type:f.get('requested_room_type'),requested_start_date:f.get('requested_start_date'),requested_end_date:f.get('requested_end_date')||undefined,reason:f.get('reason')},getAccessToken());
   await apartmentsApi.mutate(`/apartments/applications/${app.id}/submit`,undefined,getAccessToken());
  }
  e.currentTarget.reset();setStartDate('');await onDone();
 }catch(err){onError(err instanceof Error?err.message:'保存失败')}finally{setBusy(false)}};
 if(view!=='rooms'&&view!=='applications')return null;
 return <section className={`ds-panel ${styles.panel}`}>
  <header className={styles.sectionHeader}><div><h2>{view==='rooms'?'纳入公寓管理':'发起入住申请'}</h2><p>{view==='rooms'?'选择统一运营房号并配置公寓类型与床位；物理资产和空间档案无需重复创建。':'完整登记申请人、住宿需求、应急联系和安全承诺，提交后进入审批。'}</p></div></header>
  <form className={styles.form} onSubmit={submit}>{view==='rooms'?<>
   <label className="form-field"><span>搜索房号</span><input value={candidateKeyword} onChange={e=>{setCandidateKeyword(e.target.value);setCandidatePage(1)}} placeholder="房号、楼栋或楼层"/></label>
   <label className="form-field"><span>楼栋</span><select value={candidateBuilding} onChange={e=>{setCandidateBuilding(e.target.value);setCandidateFloor('');setCandidatePage(1)}}><option value="">全部楼栋</option>{candidates.facets.buildings.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
   <label className="form-field"><span>楼层</span><select value={candidateFloor} onChange={e=>{setCandidateFloor(e.target.value);setCandidatePage(1)}}><option value="">全部楼层</option>{candidates.facets.floors.filter(x=>!candidateBuilding||x.building_id===candidateBuilding).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
   <label className="form-field"><span><input type="checkbox" checked={eligibleOnly} onChange={e=>{setEligibleOnly(e.target.checked);setCandidatePage(1)}}/> 仅显示可纳入房号</span></label>
   <label className={`form-field ${styles.wide}`}><span>统一运营房号</span><select name="unit_id" value={selectedUnitId} onChange={e=>setSelectedUnitId(e.target.value)} disabled={candidateLoading} required><option value="">{candidateLoading?'正在加载房号…':'请选择房号'}</option>{candidates.items.map(x=>{const reasons=Array.isArray(x.ineligible_reasons)?x.ineligible_reasons.map(String):[];const eligible=x.eligible===true;return <option disabled={!eligible} value={x.id} key={x.id}>{String(x.building_name??'')} {String(x.floor_name??'')} {String(x.unit_name??x.unit_code)} · {x.asset_mapping_status==='mapped_complete'?'资产已关联':x.asset_mapping_status==='unmapped_external'?'外部/代管房':'资产映射待补'}{reasons.length?` · ${reasons.map(code=>reasonLabels[code]??code).join('、')}`:''}</option>})}</select><small>{candidateLoading?'正在更新候选范围':`共 ${candidates.total} 个候选，第 ${candidates.page} 页`}</small><span className={styles.formActions}><button className="ds-button ds-button-secondary" type="button" disabled={candidateLoading||candidatePage<=1} onClick={()=>setCandidatePage(page=>Math.max(1,page-1))}>上一页</button><button className="ds-button ds-button-secondary" type="button" disabled={candidateLoading||candidatePage*candidates.page_size>=candidates.total} onClick={()=>setCandidatePage(page=>page+1)}>下一页</button></span></label>
   <label className="form-field"><span>公寓类型</span><select name="room_type"><option value="talent">人才公寓</option><option value="executive">高管宿舍</option><option value="employee">员工宿舍</option></select></label>
   <label className="form-field"><span>入住性别</span><select name="gender_policy"><option value="any">不限</option><option value="male">男</option><option value="female">女</option></select></label>
   <label className="form-field"><span>床位数</span><input name="capacity" type="number" min="1" max="20" defaultValue="1" onFocus={e=>e.currentTarget.select()} required/></label>
   <label className="form-field"><span>设施（顿号分隔）</span><input name="facilities" placeholder="空调、衣柜、热水器"/></label>
  </>:<>
   <label className="form-field"><span>入住人姓名</span><input name="applicant_name" maxLength={100} required/></label><label className="form-field"><span>人员类别</span><select name="applicant_type"><option value="internal_employee">集团员工</option><option value="subsidiary_employee">下属企业员工</option><option value="executive">高级管理人员</option><option value="external_talent">引进人才</option></select></label><label className="form-field"><span>手机号（脱敏展示）</span><input name="mobile_masked" maxLength={32} placeholder="138****0000"/></label>
   <label className="form-field"><span>所属单位</span><input name="organization_name" maxLength={200}/></label><label className="form-field"><span>部门</span><input name="department_name" maxLength={200}/></label><label className="form-field"><span>岗位/职务</span><input name="job_title" maxLength={100}/></label>
   <label className="form-field"><span>紧急联系人</span><input name="emergency_contact_name" maxLength={100} required/></label><label className="form-field"><span>紧急联系人手机</span><input name="emergency_contact_mobile" type="tel" inputMode="numeric" pattern="1[0-9]{10}" placeholder="11位手机号" required/></label><label className="form-field"><span>实际入住人数</span><input name="household_size" type="number" min="1" max="10" defaultValue="1" onFocus={e=>e.currentTarget.select()} required/></label>
   <label className="form-field"><span>随住人姓名</span><input name="accompanying_names" maxLength={500} placeholder="多人用顿号分隔"/></label><label className="form-field"><span>车牌号</span><input name="vehicle_plate" maxLength={10} placeholder="苏H12345"/></label><label className="form-field"><span>申请房型</span><select name="requested_room_type"><option value="talent">人才公寓</option><option value="executive">高管宿舍</option><option value="employee">员工宿舍</option></select></label>
   <label className="form-field"><span>计划入住</span><input name="requested_start_date" type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} required/></label><label className="form-field"><span>计划退房</span><input name="requested_end_date" type="date" min={nextDate(startDate)}/></label>
   <label className={`form-field ${styles.wide}`}><span>特殊住宿需求</span><textarea name="accommodation_notes" maxLength={1000} placeholder="无障碍、医疗、作息或其他需要协调的事项"/></label><label className={`form-field ${styles.wide}`}><span>入住理由</span><textarea name="reason" maxLength={1000} value={reason} onChange={e=>setReason(e.target.value)} required/></label>
   <label className={`form-field ${styles.wide}`}><span><input name="policy_accepted" type="checkbox" required/> 本人已核对信息，并承诺遵守公寓管理、消防安全、费用结算和退房交接规定。</span></label>
  </>}<div className={styles.formActions}><button className="ds-button ds-button-primary" disabled={busy||candidateLoading||(view==='rooms'&&!selectedUnitId)}>{busy?'正在保存…':view==='rooms'?'纳入公寓管理':'提交入住申请'}</button></div></form>
 </section>;
}
