"use client";
import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
import { Building2,ClipboardCheck,FileArchive,LogOut,RefreshCw,Users } from "lucide-react";
import { PermissionGuard } from "../../components/auth/PermissionGuard";
import { getAccessToken } from "../../lib/authz";
import { apartmentsApi,type ApartmentRecord,type ApartmentSummary } from "../../lib/apartments-api";
import styles from "./ApartmentWorkbench.module.css";
import { ApartmentCreatePanel } from "./ApartmentCreatePanel";
import { ApartmentHandoverAction } from "./ApartmentHandoverAction";
const nav=[['总览','/apartments'],['房源','/apartments/rooms'],['申请','/apartments/applications'],['在住','/apartments/stays'],['退房','/apartments/checkouts'],['文书','/apartments/documents']] as const;
const labels:Record<string,string>={rooms:'房源床位',applications:'入住申请',stays:'在住管理',checkouts:'退房办理',documents:'文书档案'};
export function ApartmentWorkbench({view='dashboard'}:{view?:string}){
 const [summary,setSummary]=useState<ApartmentSummary|null>(null),[rows,setRows]=useState<ApartmentRecord[]>([]),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const load=useCallback(async()=>{setLoading(true);setMessage('');try{const token=getAccessToken();setSummary(await apartmentsApi.summary(token));if(view==='rooms')setRows(await apartmentsApi.rooms(token));else if(view==='applications')setRows(await apartmentsApi.applications(token));else if(view==='stays')setRows(await apartmentsApi.stays(token));else if(view==='checkouts')setRows(await apartmentsApi.stays(token,'checkout_pending'));else if(view==='documents')setRows(await apartmentsApi.documents(token));}catch(e){setMessage(e instanceof Error?e.message:'加载失败');}finally{setLoading(false)}},[view]);
 useEffect(()=>{void load()},[load]);
 const action=async(path:string,body?:object)=>{try{await apartmentsApi.mutate(path,body,getAccessToken());await load()}catch(e){setMessage(e instanceof Error?e.message:'操作失败')}};
 const allocate=async(row:ApartmentRecord)=>{try{const beds=await apartmentsApi.availableBeds(String(row.requested_start_date),row.requested_end_date?String(row.requested_end_date):undefined,getAccessToken());const bed=beds[0];if(!bed)throw new Error('当前日期范围没有可用床位');await apartmentsApi.mutate(`/apartments/applications/${row.id}/allocate`,{room_id:bed.room_id,bed_id:bed.id,planned_end_date:row.requested_end_date||undefined},getAccessToken());await load()}catch(e){setMessage(e instanceof Error?e.message:'分配失败')}};
 const icons=[Building2,ClipboardCheck,Users,LogOut,FileArchive];
 const forbidden=<main className="content ds-page"><section className="ds-panel"><h1>无权访问公寓管理</h1><p>当前账号缺少公寓模块或页面权限，请联系系统管理员授权。</p></section></main>;
 return <PermissionGuard module="apartment" permission={view==='dashboard'?'apartment:dashboard':`apartment:${view}`} fallback={forbidden}><main className="content ds-page">
  <section className={`ds-hero ${styles.hero}`}><div><span className={styles.muted}>集团人才公寓 · 人力资源管理</span><h1>{view==='dashboard'?'公寓管理':labels[view]}</h1><p>房源、申请、入住、退房和文书归档一条链闭环。</p></div><div className={styles.actions}><a className="secondary-button" href="/templates/apartment-import-template.xlsx" download>下载导入模板</a><button className="secondary-button" onClick={()=>void load()}><RefreshCw size={16}/>刷新</button></div></section>
  <nav className={styles.nav}>{nav.map(([n,h])=><Link href={h} key={h}>{n}</Link>)}</nav>
  {message?<p className="form-error">{message}</p>:null}
  <ApartmentCreatePanel view={view} onDone={load} onError={setMessage}/>
  {summary?<section className="ds-kpi-grid">{[['房间',summary.rooms],['床位',summary.beds],['在住',summary.occupied],['可用',summary.available],['待审批',summary.pending_applications],['待退房',summary.pending_checkouts]].map(([n,v])=><article className="ds-kpi-card" key={n}><span>{n}</span><strong>{v}</strong></article>)}</section>:null}
  {view==='dashboard'?<section className="ds-command-grid">{nav.slice(1).map(([n,h],i)=>{const Icon=icons[i]!;return <Link className="ds-command-card" href={h} key={h}><Icon size={22}/><strong>{n}</strong><span>进入办理</span></Link>})}</section>:<section className="ds-panel"><div className={styles.list}>{loading?<div className={styles.empty}>正在加载…</div>:rows.length?rows.map(row=><article className={`ds-mobile-record ${styles.record}`} key={row.id}><strong>{String(row.applicant_name??row.occupant_name??row.unit_name??row.document_type??'记录')}</strong><span>{String(row.application_code??row.stay_code??row.unit_code??'')}</span><span className={styles.muted}>{String(row.status??row.management_status??'')}</span><span className={styles.muted}>{String(row.bed_code??row.requested_start_date??'')}</span><div className={styles.actions}>{view==='applications'&&row.status==='submitted'?<><button className="primary-button" onClick={()=>void action(`/apartments/applications/${row.id}/decision`,{decision:'approve'})}>批准</button><button className="secondary-button" onClick={()=>void action(`/apartments/applications/${row.id}/decision`,{decision:'reject'})}>驳回</button></>:null}{view==='applications'&&['draft','submitted','approved'].includes(String(row.status))?<button className="secondary-button" onClick={()=>void action(`/apartments/applications/${row.id}/cancel`)}>取消</button>:null}{view==='applications'&&row.status==='approved'?<button className="primary-button" onClick={()=>void allocate(row)}>自动分配床位</button>:null}{view==='stays'&&row.status==='reserved'?<ApartmentHandoverAction stayId={row.id} type="check-in" onDone={load} onError={setMessage}/>:null}{view==='stays'&&row.status==='active'?<button className="primary-button" onClick={()=>void action(`/apartments/stays/${row.id}/request-checkout`)}>发起退房</button>:null}{view==='checkouts'?<ApartmentHandoverAction stayId={row.id} type="check-out" onDone={load} onError={setMessage}/>:null}</div></article>):<div className={styles.empty}>暂无记录。首批真实房源和人员请通过审核后的导入模板录入。</div>}</div></section>}
 </main></PermissionGuard>;
}
