"use client";

import { HR_PERMISSIONS } from "@jinhu/shared";
import { useCallback,useEffect,useMemo,useState } from "react";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hrApi,type HrContract,type HrContractDetail,type HrContractReminder,type HrContractReminderAction,type HrContractReminderStatus,type HrContractType,type HrEmployee } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import { hrLoadErrorMessage } from "../hr-errors";
import { AttachmentList } from "../../../components/files/AttachmentList";
import { FileUploader } from "../../../components/files/FileUploader";
import styles from "../hr-workbench.module.css";

const statusLabels:Record<string,string>={draft:"草稿",active:"履行中",expired:"已到期",terminated:"已终止",cancelled:"已取消",needs_review:"待复核"};
const changeLabels:Record<string,string>={renewal:"续签",amendment:"变更",termination:"终止",correction:"更正",needs_review:"待复核"};
const actionLabels:Record<string,string>={created:"创建合同",updated:"编辑合同",activated:"合同生效",cancelled:"取消合同",change_created:"创建变更",change_applied:"应用变更",change_cancelled:"取消变更"};
const reminderKindLabels:Record<string,string>={contract_expiry:"合同到期",probation_expiry:"试用期到期"};
const reminderStatusLabels:Record<string,string>={open:"待处理",read:"已读",acknowledged:"已确认",resolved:"已完成",cancelled:"已取消"};
const emptyContract={employeeId:"",contractTypeId:"",contractNo:"",startDate:"",endDate:"",probationEndDate:"",contractTermMonths:"",signatureDate:"",effectiveDate:"",positionTitle:"",workType:"",departmentNameSnapshot:"",probationMonths:"",probationSalary:"",baseSalary:"",remark:""};
const emptyChange={changeType:"renewal",newStartDate:"",newEndDate:"",remark:""};
async function loadContractEmployees(token?:string){const items:HrEmployee[]=[];for(let page=1;;page+=1){const result=await hrApi.employees(token,page,100);items.push(...result.items.filter(item=>!items.some(existing=>existing.id===item.id)));if(result.items.length===0||items.length>=result.total)break;}return items.filter(employee=>!["departed","suspended"].includes(employee.employmentStatus));}

export function HrContractsClient(){
 const user=useAuthUser();
 const canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_SELF_READ]);
 const canManage=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_MANAGE);
 const canReadSalary=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_SALARY_READ);
 const canManageSalary=canManage&&hasPermission(user,HR_PERMISSIONS.HR_COMPENSATION_MANAGE);
 const canReadDocuments=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE]);
 const canManageDocuments=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE);
 const canUpload=canManageDocuments;
 const canReadReminders=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_REMINDER_PARK_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE]);
 const canAckReminders=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK);
 const canManageReminders=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE);
 const canRunReminders=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_RUN);
 const reminderInbox=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_REMINDER_PARK_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE])?"园区收件箱":hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_TEAM_READ)?"团队收件箱":"我的收件箱";
 const selfOnly=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_SELF_READ)&&!hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ]);
 const [rows,setRows]=useState<HrContract[]>([]),[total,setTotal]=useState(0),[activeTotal,setActiveTotal]=useState(0),[expiringTotal,setExpiringTotal]=useState(0);
 const [keyword,setKeyword]=useState(""),[debouncedKeyword,setDebouncedKeyword]=useState(""),[status,setStatus]=useState("");
 const [selected,setSelected]=useState<HrContractDetail|null>(null),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[message,setMessage]=useState("");
 const [action,setAction]=useState<"contract"|"edit"|"change"|null>(null),[saving,setSaving]=useState(false),[attachmentRefresh,setAttachmentRefresh]=useState(0);
 const [employees,setEmployees]=useState<HrEmployee[]>([]),[types,setTypes]=useState<HrContractType[]>([]);
 const [contractForm,setContractForm]=useState(emptyContract),[changeForm,setChangeForm]=useState(emptyChange);
 const [reminders,setReminders]=useState<HrContractReminder[]>([]),[reminderTotal,setReminderTotal]=useState(0),[reminderLoading,setReminderLoading]=useState(false),[reminderStatus,setReminderStatus]=useState<""|HrContractReminderStatus>("open"),[reminderKind,setReminderKind]=useState(""),[reminderWindow,setReminderWindow]=useState(""),[reminderMessage,setReminderMessage]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedKeyword(keyword.trim()),300);return()=>window.clearTimeout(timer);},[keyword]);
 const load=useCallback(async()=>{if(!canRead){setLoading(false);return;}setLoading(true);setMessage("");setSelected(null);try{const token=getAccessToken();const [list,active]=await Promise.all([hrApi.contracts(token,1,50,{keyword:debouncedKeyword,status:status||undefined},selfOnly),hrApi.contracts(token,1,1,{status:"active"},selfOnly)]);setRows(list.items);setTotal(list.total);setActiveTotal(active.total);}catch(error){setRows([]);setTotal(0);setActiveTotal(0);setMessage(hrLoadErrorMessage(error,"加载劳动合同失败"));}finally{setLoading(false);}},[canRead,debouncedKeyword,selfOnly,status]);
 useEffect(()=>{void load();},[load]);
 const loadReminders=useCallback(async()=>{if(!canReadReminders){setReminders([]);setReminderTotal(0);setExpiringTotal(0);return;}setReminderLoading(true);setReminderMessage("");try{const result=await hrApi.contractReminders(getAccessToken(),1,100,reminderStatus||undefined);setReminders(result.items);setReminderTotal(result.total);setExpiringTotal(result.items.filter(item=>item.kind==="contract_expiry"&&item.windowDays===60&&!["resolved","cancelled"].includes(item.status)).length);}catch(error){setReminders([]);setReminderTotal(0);setExpiringTotal(0);setReminderMessage(hrLoadErrorMessage(error,"加载合同提醒失败"));}finally{setReminderLoading(false);}},[canReadReminders,reminderStatus]);
 useEffect(()=>{void loadReminders();},[loadReminders]);
 useEffect(()=>{if(!canManage)return;let cancelled=false;const token=getAccessToken();void Promise.all([loadContractEmployees(token),hrApi.contractTypes(token)]).then(([employeeRows,contractTypes])=>{if(!cancelled){setEmployees(employeeRows);setTypes(contractTypes);}}).catch(error=>{if(!cancelled)setMessage(hrLoadErrorMessage(error,"加载合同办理基础数据失败"));});return()=>{cancelled=true;};},[canManage]);
 const loadMore=async()=>{if(loadingMore||rows.length>=total)return;setLoadingMore(true);try{const next=await hrApi.contracts(getAccessToken(),Math.floor(rows.length/50)+1,50,{keyword:debouncedKeyword,status:status||undefined},selfOnly);setRows(current=>[...current,...next.items.filter(item=>!current.some(existing=>existing.id===item.id))]);}catch(error){setMessage(hrLoadErrorMessage(error,"加载更多合同失败"));}finally{setLoadingMore(false);}};
 const pick=async(row:HrContract)=>{setMessage("");setAction(null);try{setSelected(await hrApi.contract(row.id,getAccessToken()));}catch(error){setSelected(null);setMessage(hrLoadErrorMessage(error,"加载合同详情失败"));}};
 const contractPayload=()=>({...contractForm,endDate:contractForm.endDate||undefined,probationEndDate:contractForm.probationEndDate||undefined,contractTermMonths:contractForm.contractTermMonths===""?undefined:Number(contractForm.contractTermMonths),signatureDate:contractForm.signatureDate||undefined,effectiveDate:contractForm.effectiveDate||undefined,positionTitle:contractForm.positionTitle||undefined,workType:contractForm.workType||undefined,departmentNameSnapshot:contractForm.departmentNameSnapshot||undefined,probationMonths:contractForm.probationMonths===""?undefined:Number(contractForm.probationMonths),probationSalary:canManageSalary&&contractForm.probationSalary?contractForm.probationSalary:undefined,baseSalary:canManageSalary&&contractForm.baseSalary?contractForm.baseSalary:undefined,remark:contractForm.remark||undefined});
 const saveContract=async(event:React.FormEvent)=>{event.preventDefault();if(saving)return;setSaving(true);setMessage("");try{const editedId=action==="edit"&&selected?selected.id:null;if(editedId){await hrApi.updateContract(editedId,contractPayload(),getAccessToken());}else await hrApi.createContract(contractPayload(),getAccessToken());setContractForm(emptyContract);setAction(null);await load();if(editedId)setSelected(await hrApi.contract(editedId,getAccessToken()));setMessage(editedId?"劳动合同草稿已更新。":"劳动合同草稿已创建。");}catch(error){setMessage(hrLoadErrorMessage(error,action==="edit"?"更新劳动合同草稿失败":"创建劳动合同草稿失败"));}finally{setSaving(false);}};
 const beginEdit=()=>{if(!selected)return;setContractForm({employeeId:selected.employeeId??"",contractTypeId:selected.contractTypeId??"",contractNo:selected.contractNo,startDate:selected.startDate??"",endDate:selected.endDate??"",probationEndDate:selected.probationEndDate??"",contractTermMonths:selected.contractTermMonths===null||selected.contractTermMonths===undefined?"":String(selected.contractTermMonths),signatureDate:selected.signatureDate??"",effectiveDate:selected.effectiveDate??"",positionTitle:selected.positionTitle??"",workType:selected.workType??"",departmentNameSnapshot:selected.departmentNameSnapshot??"",probationMonths:selected.probationMonths===null||selected.probationMonths===undefined?"":String(selected.probationMonths),probationSalary:selected.probationSalary??"",baseSalary:selected.baseSalary??"",remark:selected.remark??""});setAction("edit");};
 const saveChange=async(event:React.FormEvent)=>{event.preventDefault();if(saving||!selected)return;setSaving(true);setMessage("");try{await hrApi.createContractChange(selected.id,{...changeForm,newEndDate:changeForm.newEndDate||undefined,remark:changeForm.remark||undefined},getAccessToken());setChangeForm(emptyChange);setAction(null);setMessage("合同变更草稿已创建。");setSelected(await hrApi.contract(selected.id,getAccessToken()));}catch(error){setMessage(hrLoadErrorMessage(error,"创建合同变更草稿失败"));}finally{setSaving(false);}};
 const actContract=async(next:"activate"|"cancel")=>{if(saving||!selected||!window.confirm(next==="activate"?"确认该劳动合同正式生效？":"确认取消该劳动合同草稿？"))return;setSaving(true);setMessage("");try{const id=selected.id;await hrApi.contractAction(id,next,getAccessToken());await load();setSelected(await hrApi.contract(id,getAccessToken()));setMessage(next==="activate"?"合同已生效。":"合同草稿已取消。");}catch(error){setMessage(hrLoadErrorMessage(error,"办理合同状态失败"));}finally{setSaving(false);}};
 const actChange=async(changeId:string,next:"apply"|"cancel")=>{if(saving||!selected||!window.confirm(next==="apply"?"确认应用该合同变更？应用后将更新当前合同期限或状态。":"确认取消该合同变更草稿？"))return;setSaving(true);setMessage("");try{const id=selected.id;await hrApi.contractChangeAction(id,changeId,next,getAccessToken());await load();setSelected(await hrApi.contract(id,getAccessToken()));setMessage(next==="apply"?"合同变更已生效。":"合同变更草稿已取消。");}catch(error){setMessage(hrLoadErrorMessage(error,"办理合同变更状态失败"));}finally{setSaving(false);}};
 const runReminders=async()=>{if(!canRunReminders||reminderLoading)return;setReminderLoading(true);setReminderMessage("");try{const result=await hrApi.runContractReminders(getAccessToken());await loadReminders();setReminderMessage(result.created?`已生成 ${result.created} 条提醒。`:"提醒已是最新状态。");}catch(error){setReminderMessage(hrLoadErrorMessage(error,"运行合同提醒失败"));}finally{setReminderLoading(false);}};
 const actReminder=async(id:string,next:HrContractReminderAction)=>{if(reminderLoading)return;setReminderLoading(true);setReminderMessage("");try{await hrApi.actContractReminder(id,next,getAccessToken());await loadReminders();}catch(error){setReminderMessage(hrLoadErrorMessage(error,"办理合同提醒失败"));}finally{setReminderLoading(false);}};
 const visibleReminders=useMemo(()=>reminders.filter(item=>(!reminderKind||item.kind===reminderKind)&&(!reminderWindow||item.windowDays===Number(reminderWindow))),[reminderKind,reminderWindow,reminders]);
 const visible=useMemo(()=>rows,[rows]);
 const forbidden=<main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="无权访问劳动合同"/></section></main>;
 if(!canRead)return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_CONTRACTS_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="当前账号拥有劳动合同页面入口，但没有可用的合同读取权限。"/></section></main></PermissionGuard>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_CONTRACTS_PAGE} fallback={forbidden}>
  <main className={`content ds-page ${styles.page}`}>
   <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">员工生命周期</span><h1>{selfOnly?"我的劳动合同":"劳动合同"}</h1></div></section>
   {canManage?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">合同办理</span><h2>{action==="edit"?"编辑合同草稿":"在线合同业务"}</h2></div><button type="button" className="ds-button" onClick={()=>{setContractForm(emptyContract);setAction(current=>current==="contract"?null:"contract");}}>{action==="contract"?"收起新建":"新建合同"}</button></div>
    {action==="contract"||action==="edit"?<form className={styles.formGrid} onSubmit={event=>void saveContract(event)}>
     <label className="form-field"><span>员工</span><select required value={contractForm.employeeId} onChange={event=>setContractForm({...contractForm,employeeId:event.target.value})}><option value="">请选择员工</option>{employees.map(employee=><option value={employee.id} key={employee.id}>{employee.fullName} · {employee.employeeCode}</option>)}</select></label>
     <label className="form-field"><span>合同类型</span><select required value={contractForm.contractTypeId} onChange={event=>setContractForm({...contractForm,contractTypeId:event.target.value})}><option value="">请选择合同类型</option>{types.map(type=><option value={type.id} key={type.id}>{type.typeName}</option>)}</select></label>
     <label className="form-field"><span>合同编号</span><input required maxLength={64} value={contractForm.contractNo} onChange={event=>setContractForm({...contractForm,contractNo:event.target.value})}/></label>
     <label className="form-field"><span>开始日期</span><input required type="date" value={contractForm.startDate} onChange={event=>setContractForm({...contractForm,startDate:event.target.value})}/></label>
     <label className="form-field"><span>结束日期</span><input type="date" min={contractForm.startDate||undefined} value={contractForm.endDate} onChange={event=>setContractForm({...contractForm,endDate:event.target.value})}/></label>
     <label className="form-field"><span>合同期限（月）</span><input type="number" min={0} max={1200} step={1} value={contractForm.contractTermMonths} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,contractTermMonths:event.target.value})}/></label>
     <label className="form-field"><span>签订日期</span><input type="date" value={contractForm.signatureDate} onChange={event=>setContractForm({...contractForm,signatureDate:event.target.value})}/></label>
     <label className="form-field"><span>生效日期</span><input type="date" max={contractForm.endDate||undefined} value={contractForm.effectiveDate} onChange={event=>setContractForm({...contractForm,effectiveDate:event.target.value})}/></label>
     <label className="form-field"><span>试用期截止</span><input type="date" min={contractForm.startDate||undefined} max={contractForm.endDate||undefined} value={contractForm.probationEndDate} onChange={event=>setContractForm({...contractForm,probationEndDate:event.target.value})}/></label>
     <label className="form-field"><span>试用期（月）</span><input type="number" min={0} max={120} step={1} value={contractForm.probationMonths} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,probationMonths:event.target.value})}/></label>
     <label className="form-field"><span>合同岗位</span><input maxLength={100} value={contractForm.positionTitle} onChange={event=>setContractForm({...contractForm,positionTitle:event.target.value})}/></label>
     <label className="form-field"><span>合同工种</span><input maxLength={100} value={contractForm.workType} onChange={event=>setContractForm({...contractForm,workType:event.target.value})}/></label>
     <label className="form-field"><span>部门快照</span><input maxLength={200} value={contractForm.departmentNameSnapshot} onChange={event=>setContractForm({...contractForm,departmentNameSnapshot:event.target.value})}/></label>
     {canManageSalary?<><label className="form-field"><span>试用期工资</span><input type="number" min={0} step="0.01" value={contractForm.probationSalary} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,probationSalary:event.target.value})}/></label><label className="form-field"><span>转正工资</span><input type="number" min={0} step="0.01" value={contractForm.baseSalary} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,baseSalary:event.target.value})}/></label></>:null}
     <label className="form-field"><span>办理备注</span><input maxLength={500} value={contractForm.remark} onChange={event=>setContractForm({...contractForm,remark:event.target.value})}/></label>
     <button className="ds-button" disabled={saving} type="submit">{saving?"保存中":action==="edit"?"保存合同修改":"保存合同草稿"}</button>
    </form>:null}
   </section>:null}
   <section className={`ds-kpi-grid ${styles.compactKpiGrid}`} aria-label="劳动合同概览"><article className="ds-kpi-card"><span>全部合同</span><strong>{total}</strong><small>当前权限范围</small></article><article className="ds-kpi-card"><span>履行中</span><strong>{activeTotal}</strong><small>有效劳动关系</small></article><article className="ds-kpi-card"><span>60 日提醒</span><strong>{canReadReminders?expiringTotal:"—"}</strong><small>未关闭合同提醒</small></article></section>
   {canReadReminders?<section className="ds-panel" aria-label="合同提醒工作区"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">{reminderInbox}</span><h2>合同提醒</h2></div>{canRunReminders?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void runReminders()}>运行提醒</button>:null}</div><div className={styles.filterBar}><label className="form-field"><span>提醒类型</span><select value={reminderKind} onChange={event=>setReminderKind(event.target.value)}><option value="">全部类型</option><option value="contract_expiry">合同到期</option><option value="probation_expiry">试用期到期</option></select></label><label className="form-field"><span>提醒窗口</span><select value={reminderWindow} onChange={event=>setReminderWindow(event.target.value)}><option value="">全部窗口</option>{[30,60,90].map(days=><option key={days} value={days}>{days} 天</option>)}</select></label><label className="form-field"><span>状态</span><select value={reminderStatus} onChange={event=>setReminderStatus(event.target.value as ""|HrContractReminderStatus)}><option value="">全部状态</option>{Object.entries(reminderStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{reminderMessage?<p className="form-error" role="alert">{reminderMessage}</p>:null}<div className="ds-mobile-record-list">{reminderLoading&&!reminders.length?<p className={styles.emptyState}>正在加载合同提醒…</p>:visibleReminders.length?visibleReminders.map(item=><article className="ds-mobile-record" key={item.id}><strong>{reminderKindLabels[item.kind]??item.kind} · {item.windowDays} 天</strong><span>收件人：{reminderInbox}</span><span>截止日期：{item.dueDate}</span><span>状态：{reminderStatusLabels[item.status]??item.status}</span><div className={styles.actionRow}>{canAckReminders&&item.status==="open"?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"read")}>标记已读</button>:null}{canAckReminders&&["open","read"].includes(item.status)?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"acknowledge")}>确认收到</button>:null}{canManageReminders&&item.status==="acknowledged"?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"resolve")}>完成提醒</button>:null}{canManageReminders&&["open","read"].includes(item.status)?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"cancel")}>取消提醒</button>:null}</div></article>):<p className={styles.emptyState}>当前筛选条件下没有合同提醒。</p>}</div>{reminderTotal>reminders.length?<small>当前显示前 {reminders.length} 条，共 {reminderTotal} 条。</small>:null}</section>:null}
   <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">合同台账</span><h2>合同目录</h2></div><strong>已加载 {rows.length}/{total}</strong></div><div className={styles.filterBar}><label className="form-field"><span>搜索</span><input type="search" value={keyword} onChange={event=>setKeyword(event.target.value)} placeholder="姓名、员工编号或合同编号"/></label><label className="form-field"><span>合同状态</span><select value={status} onChange={event=>setStatus(event.target.value)}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
    {message?<p className="form-error" role="alert">{message}</p>:null}
    <div className="ds-mobile-record-list">{loading?<p className={styles.emptyState}>正在加载劳动合同…</p>:visible.length?visible.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.employeeName?`${row.employeeName} · `:""}{row.contractTypeName}</strong><span>{row.employeeCode?`${row.employeeCode} · `:""}{row.contractNo}</span><span>{row.startDate??"未登记"} 至 {row.endDate??"无固定期限"}</span><span>{statusLabels[row.status]??row.status}{row.isHistoricalImport?" · 旧系统历史":""}</span><button type="button" className="ds-button" onClick={()=>void pick(row)}>查看合同</button></article>):<p className={styles.emptyState}>当前筛选条件下没有可查看的劳动合同。</p>}</div>
    {rows.length<total?<button type="button" className="ds-button" disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?"加载中":"加载更多"}</button>:null}
   </section>
   {selected?<section className="ds-panel">
    <div className={styles.sectionHeading}><div><span className="ds-eyebrow">合同详情</span><h2>{selected.employeeName?`${selected.employeeName} · `:""}{selected.contractNo}</h2></div><strong>{statusLabels[selected.status]??selected.status}</strong></div>
    <div className="ds-mobile-record-list"><article className="ds-mobile-record"><strong>{selected.contractTypeName}</strong>{selected.employeeName?<span>员工：{selected.employeeCode} · {selected.employeeName}</span>:null}<span>期限：{selected.startDate??"未登记"} 至 {selected.endDate??"无固定期限"}{selected.contractTermMonths!==null&&selected.contractTermMonths!==undefined?` · ${selected.contractTermMonths} 个月`:""}</span><span>签订/生效：{selected.signatureDate??"未登记"} / {selected.effectiveDate??"未登记"}</span><span>试用期：{selected.probationMonths??"未登记"} 个月 · 截止 {selected.probationEndDate??"未登记"}</span><span>岗位/工种：{selected.positionTitle??"未登记"} / {selected.workType??"未登记"}</span><span>部门快照：{selected.departmentNameSnapshot??"未登记"}</span>{canReadSalary&&(selected.probationSalary!==undefined||selected.baseSalary!==undefined)?<span>试用/转正工资：{selected.probationSalary??"未登记"} / {selected.baseSalary??"未登记"}</span>:null}{selected.remark?<span>备注：{selected.remark}</span>:null}</article></div>
    {canManage&&!selected.isHistoricalImport&&selected.status==="draft"?<div className={styles.actionRow}><button type="button" className="ds-button" disabled={saving} onClick={beginEdit}>编辑草稿</button><button type="button" className="ds-button" disabled={saving} onClick={()=>void actContract("activate")}>确认生效</button><button type="button" className="ds-button" disabled={saving} onClick={()=>void actContract("cancel")}>取消草稿</button></div>:null}
    {canManage&&!selected.isHistoricalImport&&selected.status==="active"?<button type="button" className="ds-button" onClick={()=>setAction(current=>current==="change"?null:"change")}>{action==="change"?"收起办理":"办理续签/变更"}</button>:null}
    {action==="change"?<form className={styles.formGrid} onSubmit={event=>void saveChange(event)}><label className="form-field"><span>办理类型</span><select value={changeForm.changeType} onChange={event=>setChangeForm({...changeForm,changeType:event.target.value})}><option value="renewal">续签</option><option value="amendment">变更</option><option value="termination">终止</option><option value="correction">更正</option></select></label><label className="form-field"><span>新开始日期/生效日期</span><input required type="date" value={changeForm.newStartDate} onChange={event=>setChangeForm({...changeForm,newStartDate:event.target.value})}/></label><label className="form-field"><span>新结束日期</span><input type="date" min={changeForm.newStartDate||undefined} value={changeForm.newEndDate} onChange={event=>setChangeForm({...changeForm,newEndDate:event.target.value})}/></label><label className="form-field"><span>办理备注</span><input maxLength={500} value={changeForm.remark} onChange={event=>setChangeForm({...changeForm,remark:event.target.value})}/></label><button className="ds-button" disabled={saving} type="submit">{saving?"保存中":"保存变更草稿"}</button></form>:null}
    {canReadDocuments?<><h3>合同附件</h3>{canUpload&&!selected.isHistoricalImport?<FileUploader compact bizType="hr_contract_document" bizId={selected.id} policyKey="contract" label="上传合同附件" onUploaded={()=>setAttachmentRefresh(value=>value+1)}/>:null}<AttachmentList compact label="合同附件" emptyLabel="暂无合同附件" bizType="hr_contract_document" bizId={selected.id} refreshKey={attachmentRefresh} readPermissions={[HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE]} downloadPermissions={[HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE]} mutationDisabled={!canManageDocuments||selected.isHistoricalImport} mutationPermission={HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE}/></>:<p className={styles.emptyState}>无附件查看权限</p>}
    <h3>续签与变更历史</h3><div className="ds-mobile-record-list">{selected.changes.length?selected.changes.map(change=><article className="ds-mobile-record" key={change.id}><strong>第 {change.sequenceNo} 次 · {changeLabels[change.changeType]??change.changeType}</strong><span>{change.previousStartDate??"未登记"} 至 {change.previousEndDate??"无固定期限"} → {change.newStartDate} 至 {change.newEndDate??"无固定期限"}</span><span>{change.isHistoricalImport?"旧系统历史记录":change.status==="draft"?"新系统草稿":change.status==="cancelled"?"已取消":"新系统记录"}</span>{canManage&&!change.isHistoricalImport&&change.status==="draft"?<div className={styles.actionRow}><button type="button" className="ds-button" disabled={saving} onClick={()=>void actChange(change.id,"apply")}>确认变更</button><button type="button" className="ds-button" disabled={saving} onClick={()=>void actChange(change.id,"cancel")}>取消变更</button></div>:null}</article>):<p className={styles.emptyState}>暂无续签或变更记录。</p>}</div>
    <h3>办理轨迹</h3><div className="ds-mobile-record-list">{selected.actions?.length?selected.actions.map(item=><article className="ds-mobile-record" key={item.id}><strong>第 {item.sequenceNo} 步 · {actionLabels[item.action]??item.action}</strong><span>{item.fromStatus?`${statusLabels[item.fromStatus]??item.fromStatus} → `:""}{statusLabels[item.toStatus]??item.toStatus}</span><span>{new Date(item.occurredAt).toLocaleString("zh-CN")}</span></article>):<p className={styles.emptyState}>旧系统历史合同暂无新平台办理轨迹。</p>}</div>
   </section>:null}
  </main>
 </PermissionGuard>;
}
