"use client";

import { HR_PERMISSIONS } from "@jinhu/shared";
import { useCallback,useEffect,useMemo,useRef,useState,useSyncExternalStore } from "react";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hrApi,type HrContract,type HrContractDetail,type HrContractReminder,type HrContractReminderAction,type HrContractReminderStatus,type HrContractType,type HrEmployee } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import { hrLoadErrorMessage } from "../hr-errors";
import { AttachmentList } from "../../../components/files/AttachmentList";
import { FileUploader } from "../../../components/files/FileUploader";
import styles from "../hr-workbench.module.css";
import { createContractLedger,contractPageCount,runContractContextAction } from "./contract-ledger";
import contractStyles from "./contracts.module.css";

const statusLabels:Record<string,string>={draft:"草稿",active:"履行中",expired:"已到期",terminated:"已终止",cancelled:"已取消",needs_review:"待复核"};
const changeLabels:Record<string,string>={renewal:"续签",amendment:"变更",termination:"终止",correction:"更正",needs_review:"待复核"};
const actionLabels:Record<string,string>={created:"创建合同",updated:"编辑合同",activated:"合同生效",cancelled:"取消合同",change_created:"创建变更",change_applied:"应用变更",change_cancelled:"取消变更"};
const reminderKindLabels:Record<string,string>={contract_expiry:"合同到期",probation_expiry:"试用期到期"};
const reminderStatusLabels:Record<string,string>={open:"待处理",read:"已读",acknowledged:"已确认",resolved:"已完成",cancelled:"已取消"};
const emptyContract={employeeId:"",contractTypeId:"",contractNo:"",startDate:"",endDate:"",probationEndDate:"",contractTermMonths:"",signatureDate:"",effectiveDate:"",positionTitle:"",workType:"",departmentNameSnapshot:"",probationMonths:"",probationSalary:"",baseSalary:"",remark:""};
const emptyChange={changeType:"renewal",newStartDate:"",newEndDate:"",remark:""};
async function loadContractEmployees(token?:string){const items:HrEmployee[]=[];for(let page=1;;page+=1){const result=await hrApi.employees(token,page,100);items.push(...result.items.filter(item=>!items.some(existing=>existing.id===item.id)));if(result.items.length===0||items.length>=result.total)break;}return items.filter(employee=>!["departed","suspended"].includes(employee.employmentStatus));}

export function HrContractsClient(){
 const user=useAuthUser();
 const canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_SELF_READ]);
 const canManage=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_MANAGE);
 const canReadSalary=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_SALARY_READ);
 const canManageSalary=canManage&&hasPermission(user,HR_PERMISSIONS.HR_COMPENSATION_MANAGE);
 const canReadDocuments=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE]);
 const canManageDocuments=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE);
 const canUpload=canManageDocuments;
 const canReadReminders=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_REMINDER_PARK_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE]);
 const canAckReminders=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_ACK);
 const canManageReminders=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE);
 const canRunReminders=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_RUN);
 const reminderInbox=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_REMINDER_PARK_READ,HR_PERMISSIONS.HR_CONTRACT_REMINDER_MANAGE])?"园区收件箱":hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_REMINDER_TEAM_READ)?"团队收件箱":"我的收件箱";
 const selfOnly=hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_SELF_READ)&&!hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ]);
 const [expiringTotalState,setExpiringTotal]=useState(0);
 const [keyword,setKeyword]=useState(""),[debouncedKeyword,setDebouncedKeyword]=useState(""),[status,setStatus]=useState("");
 const [actionState,setAction]=useState<"contract"|"edit"|"change"|null>(null),[attachmentRefresh,setAttachmentRefresh]=useState(0);
 const contextKey=JSON.stringify([user?.id,user?.tenant_id,user?.park_id,user?.is_super,user?.permissions,user?.roles,user?.data_scope,user?.data_scopes,user?.field_policies]);
 const contextRef=useRef(contextKey);contextRef.current=contextKey;
 const ledgerRef=useRef<ReturnType<typeof createContractLedger<HrContract,HrContractDetail>>|null>(null);
 if(!ledgerRef.current)ledgerRef.current=createContractLedger<HrContract,HrContractDetail>({
  list:(query,page,size)=>hrApi.contracts(getAccessToken(),page,size,{keyword:query.keyword,status:query.status||undefined},query.selfOnly),
  activeTotal:async query=>(await hrApi.contracts(getAccessToken(),1,1,{status:"active"},query.selfOnly)).total,
  detail:id=>hrApi.contract(id,getAccessToken()),error:hrLoadErrorMessage
 });
 const ledger=ledgerRef.current,snapshot=useSyncExternalStore(ledger.subscribe,ledger.getSnapshot,ledger.getSnapshot),contextMatches=snapshot.contextKey===contextKey;
 const rows=contextMatches?snapshot.rows:[],total=contextMatches?snapshot.total:0,activeTotal=contextMatches?snapshot.activeTotal:0,selected=contextMatches?snapshot.selected:null,loading=!contextMatches||snapshot.loading,detailLoading=contextMatches&&snapshot.detailLoading,saving=contextMatches&&snapshot.saving,message=contextMatches?snapshot.message:"",page=contextMatches?snapshot.page:1,action=contextMatches?actionState:null;
 const setMessage=ledger.setMessage;
 const [employees,setEmployees]=useState<HrEmployee[]>([]),[types,setTypes]=useState<HrContractType[]>([]);
 const [contractForm,setContractForm]=useState(emptyContract),[changeForm,setChangeForm]=useState(emptyChange);
 const [remindersState,setReminders]=useState<HrContractReminder[]>([]),[reminderTotalState,setReminderTotal]=useState(0),[reminderLoadingState,setReminderLoading]=useState(false),[reminderStatus,setReminderStatus]=useState<""|HrContractReminderStatus>("open"),[reminderKind,setReminderKind]=useState(""),[reminderWindow,setReminderWindow]=useState(""),[reminderMessageState,setReminderMessage]=useState(""),[reminderContextKey,setReminderContextKey]=useState("");
 const reminderContextMatches=reminderContextKey===contextKey,reminders=reminderContextMatches?remindersState:[],reminderTotal=reminderContextMatches?reminderTotalState:0,expiringTotal=reminderContextMatches?expiringTotalState:0,reminderLoading=reminderContextMatches&&reminderLoadingState,reminderMessage=reminderContextMatches?reminderMessageState:"";
 const reminderGeneration=useRef(0),reminderAbort=useRef<AbortController|null>(null);
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedKeyword(keyword.trim()),300);return()=>window.clearTimeout(timer);},[keyword]);
 useEffect(()=>{ledger.configure({contextKey,canRead,canManage,selfOnly,keyword:keyword.trim(),status});setAction(null);if(keyword.trim()===debouncedKeyword)void ledger.load();return()=>ledger.cancel();},[ledger,contextKey,canRead,canManage,selfOnly,keyword,debouncedKeyword,status]);
 useEffect(()=>{setContractForm(emptyContract);setChangeForm(emptyChange);setEmployees([]);setTypes([]);setAttachmentRefresh(0);setReminders([]);setReminderTotal(0);setExpiringTotal(0);setReminderMessage("");setReminderLoading(false);setReminderContextKey(contextKey);},[contextKey]);
 const loadReminders=useCallback(async()=>{if(!canReadReminders){reminderAbort.current?.abort();reminderGeneration.current+=1;setReminders([]);setReminderTotal(0);setExpiringTotal(0);return;}reminderAbort.current?.abort();const current=++reminderGeneration.current,controller=new AbortController();reminderAbort.current=controller;setReminderLoading(true);setReminderMessage("");try{const result=await hrApi.contractReminders(getAccessToken(),1,100,reminderStatus||undefined,controller.signal);if(current!==reminderGeneration.current||contextRef.current!==contextKey)return;setReminders(result.items);setReminderTotal(result.total);setExpiringTotal(result.items.filter(item=>item.kind==="contract_expiry"&&item.windowDays===60&&!["resolved","cancelled"].includes(item.status)).length);}catch(error){if(current===reminderGeneration.current&&contextRef.current===contextKey&&!controller.signal.aborted){setReminders([]);setReminderTotal(0);setExpiringTotal(0);setReminderMessage(hrLoadErrorMessage(error,"加载合同提醒失败"));}}finally{if(current===reminderGeneration.current&&contextRef.current===contextKey)setReminderLoading(false);}},[canReadReminders,reminderStatus,contextKey]);
 useEffect(()=>{void loadReminders();return()=>{reminderAbort.current?.abort();reminderGeneration.current+=1;};},[loadReminders]);
 useEffect(()=>{if(!canManage)return;let cancelled=false;const token=getAccessToken();void Promise.all([loadContractEmployees(token),hrApi.contractTypes(token)]).then(([employeeRows,contractTypes])=>{if(!cancelled&&contextRef.current===contextKey){setEmployees(employeeRows);setTypes(contractTypes);}}).catch(error=>{if(!cancelled&&contextRef.current===contextKey)setMessage(hrLoadErrorMessage(error,"加载合同办理基础数据失败"));});return()=>{cancelled=true;};},[canManage,contextKey,setMessage]);
 const pick=(row:HrContract)=>{setAction(null);return ledger.pick(row);};
 const contractPayload=()=>({...contractForm,endDate:contractForm.endDate||undefined,probationEndDate:contractForm.probationEndDate||undefined,contractTermMonths:contractForm.contractTermMonths===""?undefined:Number(contractForm.contractTermMonths),signatureDate:contractForm.signatureDate||undefined,effectiveDate:contractForm.effectiveDate||undefined,positionTitle:contractForm.positionTitle||undefined,workType:contractForm.workType||undefined,departmentNameSnapshot:contractForm.departmentNameSnapshot||undefined,probationMonths:contractForm.probationMonths===""?undefined:Number(contractForm.probationMonths),probationSalary:canManageSalary&&contractForm.probationSalary?contractForm.probationSalary:undefined,baseSalary:canManageSalary&&contractForm.baseSalary?contractForm.baseSalary:undefined,remark:contractForm.remark||undefined});
 const saveContract=async(event:React.FormEvent)=>{event.preventDefault();const editedId=action==="edit"&&selected?selected.id:undefined,payload=contractPayload();await ledger.mutate(()=>editedId?hrApi.updateContract(editedId,payload,getAccessToken()):hrApi.createContract(payload,getAccessToken()),{selectedId:editedId,refreshList:true,success:editedId?"劳动合同草稿已更新。":"劳动合同草稿已创建。",failure:editedId?"更新劳动合同草稿失败":"创建劳动合同草稿失败",onSuccess:()=>{setContractForm(emptyContract);setAction(null);}});};
 const beginEdit=()=>{if(!selected)return;setContractForm({employeeId:selected.employeeId??"",contractTypeId:selected.contractTypeId??"",contractNo:selected.contractNo,startDate:selected.startDate??"",endDate:selected.endDate??"",probationEndDate:selected.probationEndDate??"",contractTermMonths:selected.contractTermMonths===null||selected.contractTermMonths===undefined?"":String(selected.contractTermMonths),signatureDate:selected.signatureDate??"",effectiveDate:selected.effectiveDate??"",positionTitle:selected.positionTitle??"",workType:selected.workType??"",departmentNameSnapshot:selected.departmentNameSnapshot??"",probationMonths:selected.probationMonths===null||selected.probationMonths===undefined?"":String(selected.probationMonths),probationSalary:selected.probationSalary??"",baseSalary:selected.baseSalary??"",remark:selected.remark??""});setAction("edit");};
 const saveChange=async(event:React.FormEvent)=>{event.preventDefault();if(!selected||selected.isHistoricalImport)return;const id=selected.id,payload={...changeForm,newEndDate:changeForm.newEndDate||undefined,remark:changeForm.remark||undefined};await ledger.mutate(()=>hrApi.createContractChange(id,payload,getAccessToken()),{selectedId:id,refreshList:false,success:"合同变更草稿已创建。",failure:"创建合同变更草稿失败",onSuccess:()=>{setChangeForm(emptyChange);setAction(null);}});};
 const actContract=async(next:"activate"|"cancel")=>{if(saving||!selected||selected.isHistoricalImport||!window.confirm(next==="activate"?"确认该劳动合同正式生效？":"确认取消该劳动合同草稿？"))return;const id=selected.id;await ledger.mutate(()=>hrApi.contractAction(id,next,getAccessToken()),{selectedId:id,refreshList:true,success:next==="activate"?"合同已生效。":"合同草稿已取消。",failure:"办理合同状态失败"});};
 const actChange=async(changeId:string,next:"apply"|"cancel")=>{if(saving||!selected||selected.isHistoricalImport||!window.confirm(next==="apply"?"确认应用该合同变更？应用后将更新当前合同期限或状态。":"确认取消该合同变更草稿？"))return;const id=selected.id;await ledger.mutate(()=>hrApi.contractChangeAction(id,changeId,next,getAccessToken()),{selectedId:id,refreshList:true,success:next==="apply"?"合同变更已生效。":"合同变更草稿已取消。",failure:"办理合同变更状态失败"});};
 const runReminders=async()=>{if(!canRunReminders||reminderLoading||!reminderContextMatches)return;setReminderLoading(true);setReminderMessage("");await runContractContextAction({isCurrent:()=>contextRef.current===contextKey,work:()=>hrApi.runContractReminders(getAccessToken()),refresh:loadReminders,success:result=>setReminderMessage(result.created?`已生成 ${result.created} 条提醒。`:"提醒已是最新状态。"),error:error=>setReminderMessage(hrLoadErrorMessage(error,"运行合同提醒失败")),settled:()=>setReminderLoading(false)});};
 const actReminder=async(id:string,next:HrContractReminderAction)=>{if(reminderLoading||!reminderContextMatches)return;setReminderLoading(true);setReminderMessage("");await runContractContextAction({isCurrent:()=>contextRef.current===contextKey,work:()=>hrApi.actContractReminder(id,next,getAccessToken()),refresh:loadReminders,success:()=>{},error:error=>setReminderMessage(hrLoadErrorMessage(error,"办理合同提醒失败")),settled:()=>setReminderLoading(false)});};
 const visibleReminders=useMemo(()=>reminders.filter(item=>(!reminderKind||item.kind===reminderKind)&&(!reminderWindow||item.windowDays===Number(reminderWindow))),[reminderKind,reminderWindow,reminders]);
 const visible=useMemo(()=>rows,[rows]);
 const forbidden=<main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="无权访问劳动合同"/></section></main>;
 if(!canRead)return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_CONTRACTS_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="当前账号拥有劳动合同页面入口，但没有可用的合同读取权限。"/></section></main></PermissionGuard>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_CONTRACTS_PAGE} fallback={forbidden}>
  <main className={`content ds-page ${styles.page}`}>
   <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">员工生命周期</span><h1>{selfOnly?"我的劳动合同":"劳动合同"}</h1></div></section>
   {canManage?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">合同办理</span><h2>{action==="edit"?"编辑合同草稿":"在线合同业务"}</h2></div><button type="button" className="ds-button" onClick={()=>{setContractForm(emptyContract);setAction(current=>current==="contract"?null:"contract");}}>{action==="contract"?"收起新建":"新建合同"}</button></div>
    {action==="contract"||action==="edit"?<form className={styles.formGrid} onSubmit={event=>void saveContract(event)}>
     <label className="form-field"><span>员工</span><select required value={contractForm.employeeId} onChange={event=>setContractForm({...contractForm,employeeId:event.target.value})}><option value="">请选择员工</option>{employees.map(employee=><option value={employee.id} key={employee.id}>{employee.fullName} · {employee.employeeCode}</option>)}</select></label>
     <label className="form-field"><span>合同类型</span><select required value={contractForm.contractTypeId} onChange={event=>setContractForm({...contractForm,contractTypeId:event.target.value})}><option value="">请选择合同类型</option>{types.map(type=><option value={type.id} key={type.id}>{type.typeName}</option>)}</select></label>
     <label className="form-field"><span>合同编号</span><input required maxLength={64} value={contractForm.contractNo} onChange={event=>setContractForm({...contractForm,contractNo:event.target.value})}/></label>
     <label className="form-field"><span>开始日期</span><input required type="date" value={contractForm.startDate} onChange={event=>setContractForm({...contractForm,startDate:event.target.value})}/></label>
     <label className="form-field"><span>结束日期</span><input type="date" min={contractForm.startDate||undefined} value={contractForm.endDate} onChange={event=>setContractForm({...contractForm,endDate:event.target.value})}/></label>
     <label className="form-field"><span>合同期限（月）</span><input type="number" min={0} max={1200} step={1} value={contractForm.contractTermMonths} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,contractTermMonths:event.target.value})}/></label>
     <label className="form-field"><span>签订日期</span><input type="date" value={contractForm.signatureDate} onChange={event=>setContractForm({...contractForm,signatureDate:event.target.value})}/></label>
     <label className="form-field"><span>生效日期</span><input type="date" max={contractForm.endDate||undefined} value={contractForm.effectiveDate} onChange={event=>setContractForm({...contractForm,effectiveDate:event.target.value})}/></label>
     <label className="form-field"><span>试用期截止</span><input type="date" min={contractForm.startDate||undefined} max={contractForm.endDate||undefined} value={contractForm.probationEndDate} onChange={event=>setContractForm({...contractForm,probationEndDate:event.target.value})}/></label>
     <label className="form-field"><span>试用期（月）</span><input type="number" min={0} max={120} step={1} value={contractForm.probationMonths} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,probationMonths:event.target.value})}/></label>
     <label className="form-field"><span>合同岗位</span><input maxLength={100} value={contractForm.positionTitle} onChange={event=>setContractForm({...contractForm,positionTitle:event.target.value})}/></label>
     <label className="form-field"><span>合同工种</span><input maxLength={100} value={contractForm.workType} onChange={event=>setContractForm({...contractForm,workType:event.target.value})}/></label>
     <label className="form-field"><span>部门快照</span><input maxLength={200} value={contractForm.departmentNameSnapshot} onChange={event=>setContractForm({...contractForm,departmentNameSnapshot:event.target.value})}/></label>
     {canManageSalary?<><label className="form-field"><span>试用期工资</span><input type="number" min={0} step="0.01" value={contractForm.probationSalary} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,probationSalary:event.target.value})}/></label><label className="form-field"><span>转正工资</span><input type="number" min={0} step="0.01" value={contractForm.baseSalary} onFocus={event=>event.currentTarget.select()} onChange={event=>setContractForm({...contractForm,baseSalary:event.target.value})}/></label></>:null}
     <label className="form-field"><span>办理备注</span><input maxLength={500} value={contractForm.remark} onChange={event=>setContractForm({...contractForm,remark:event.target.value})}/></label>
     <button className="ds-button" disabled={saving} type="submit">{saving?"保存中":action==="edit"?"保存合同修改":"保存合同草稿"}</button>
    </form>:null}
   </section>:null}
   <section className={`ds-kpi-grid ${styles.compactKpiGrid}`} aria-label="劳动合同概览"><article className="ds-kpi-card"><span>筛选合同</span><strong>{total}</strong><small>当前筛选与权限范围</small></article><article className="ds-kpi-card"><span>履行中</span><strong>{activeTotal}</strong><small>有效劳动关系</small></article><article className="ds-kpi-card"><span>60 日提醒</span><strong>{canReadReminders?expiringTotal:"—"}</strong><small>未关闭合同提醒</small></article></section>
   {canReadReminders?<section className="ds-panel" aria-label="合同提醒工作区"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">{reminderInbox}</span><h2>合同提醒</h2></div>{canRunReminders?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void runReminders()}>运行提醒</button>:null}</div><div className={styles.filterBar}><label className="form-field"><span>提醒类型</span><select value={reminderKind} onChange={event=>setReminderKind(event.target.value)}><option value="">全部类型</option><option value="contract_expiry">合同到期</option><option value="probation_expiry">试用期到期</option></select></label><label className="form-field"><span>提醒窗口</span><select value={reminderWindow} onChange={event=>setReminderWindow(event.target.value)}><option value="">全部窗口</option>{[30,60,90].map(days=><option key={days} value={days}>{days} 天</option>)}</select></label><label className="form-field"><span>状态</span><select value={reminderStatus} onChange={event=>setReminderStatus(event.target.value as ""|HrContractReminderStatus)}><option value="">全部状态</option>{Object.entries(reminderStatusLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{reminderMessage?<p className="form-error" role="alert">{reminderMessage}</p>:null}<div className={`ds-mobile-record-list ${contractStyles.recordList}`}>{reminderLoading&&!reminders.length?<p className={styles.emptyState}>正在加载合同提醒…</p>:visibleReminders.length?visibleReminders.map(item=><article className="ds-mobile-record" key={item.id}><strong>{reminderKindLabels[item.kind]??item.kind} · {item.windowDays} 天</strong><span>收件人：{reminderInbox}</span><span>截止日期：{item.dueDate}</span><span>状态：{reminderStatusLabels[item.status]??item.status}</span><div className={styles.actionRow}>{canAckReminders&&item.status==="open"?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"read")}>标记已读</button>:null}{canAckReminders&&["open","read"].includes(item.status)?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"acknowledge")}>确认收到</button>:null}{canManageReminders&&item.status==="acknowledged"?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"resolve")}>完成提醒</button>:null}{canManageReminders&&["open","read"].includes(item.status)?<button type="button" className="ds-button" disabled={reminderLoading} onClick={()=>void actReminder(item.id,"cancel")}>取消提醒</button>:null}</div></article>):<p className={styles.emptyState}>当前筛选条件下没有合同提醒。</p>}</div>{reminderTotal>reminders.length?<small>当前显示前 {reminders.length} 条，共 {reminderTotal} 条。</small>:null}</section>:null}
   <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">合同台账</span><h2>合同目录</h2></div><strong>本页 {rows.length} 条 · 共 {total} 条</strong></div><div className={styles.filterBar}><label className="form-field"><span>搜索</span><input type="search" value={keyword} onChange={event=>{ledger.invalidate();setAction(null);setKeyword(event.target.value);}} placeholder="姓名、员工编号或合同编号"/></label><label className="form-field"><span>合同状态</span><select value={status} onChange={event=>{ledger.invalidate();setAction(null);setStatus(event.target.value);}}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label></div>
    {message?<p className="form-error" role="alert">{message}</p>:null}
    <div className={`ds-mobile-record-list ${contractStyles.recordList}`}>{loading?<p className={styles.emptyState}>正在加载劳动合同…</p>:visible.length?visible.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.employeeName?`${row.employeeName} · `:""}{row.contractTypeName}</strong><span>{row.employeeCode?`${row.employeeCode} · `:""}{row.contractNo}</span><span>{row.startDate??"未登记"} 至 {row.endDate??"无固定期限"}</span><span>{statusLabels[row.status]??row.status}{row.isHistoricalImport?" · 旧系统历史":""}</span><button type="button" className="ds-button" onClick={()=>void pick(row)}>查看合同</button></article>):<p className={styles.emptyState}>当前筛选条件下没有可查看的劳动合同。</p>}</div>
    <nav aria-label="劳动合同分页" className={styles.filterBar}><button type="button" className="ds-button" disabled={loading||page<=1} onClick={()=>{setAction(null);void ledger.load(page-1);}}>上一页</button><span role="status" aria-live="polite">第 {page} / {contractPageCount(total)} 页 · 共 {total} 条 · 每页 50 条</span><button type="button" className="ds-button" disabled={loading||page>=contractPageCount(total)} onClick={()=>{setAction(null);void ledger.load(page+1);}}>下一页</button><button type="button" className="ds-button" disabled={loading} onClick={()=>{setAction(null);void ledger.load(page);}}>刷新本页</button></nav>{detailLoading?<p role="status">正在加载合同详情…</p>:null}
   </section>
   {selected?<section className="ds-panel">
    <div className={styles.sectionHeading}><div><span className="ds-eyebrow">合同详情</span><h2>{selected.employeeName?`${selected.employeeName} · `:""}{selected.contractNo}</h2></div><strong>{statusLabels[selected.status]??selected.status}</strong></div>
    <div className={`ds-mobile-record-list ${contractStyles.recordList}`}><article className="ds-mobile-record"><strong>{selected.contractTypeName}</strong>{selected.employeeName&&selected.employeeCode?<span>员工：{selected.employeeCode} · {selected.employeeName}</span>:null}<span>期限：{selected.startDate??"未登记"} 至 {selected.endDate??"无固定期限"}{selected.contractTermMonths!==null&&selected.contractTermMonths!==undefined?` · ${selected.contractTermMonths} 个月`:""}</span>{selected.signatureDate!==undefined||selected.effectiveDate!==undefined?<span>签订/生效：{selected.signatureDate??"未登记"} / {selected.effectiveDate??"未登记"}</span>:null}{selected.probationEndDate!==undefined?<span>试用期：{selected.probationMonths??"未登记"} 个月 · 截止 {selected.probationEndDate??"未登记"}</span>:null}{selected.positionTitle!==undefined||selected.workType!==undefined?<span>岗位/工种：{selected.positionTitle??"未登记"} / {selected.workType??"未登记"}</span>:null}{selected.departmentNameSnapshot!==undefined?<span>部门快照：{selected.departmentNameSnapshot??"未登记"}</span>:null}{canReadSalary&&(selected.probationSalary!==undefined||selected.baseSalary!==undefined)?<span>试用/转正工资：{selected.probationSalary??"未登记"} / {selected.baseSalary??"未登记"}</span>:null}{selected.remark?<span>备注：{selected.remark}</span>:null}</article></div>
    {canManage&&!selected.isHistoricalImport&&selected.status==="draft"?<div className={styles.actionRow}><button type="button" className="ds-button" disabled={saving} onClick={beginEdit}>编辑草稿</button><button type="button" className="ds-button" disabled={saving} onClick={()=>void actContract("activate")}>确认生效</button><button type="button" className="ds-button" disabled={saving} onClick={()=>void actContract("cancel")}>取消草稿</button></div>:null}
    {canManage&&!selected.isHistoricalImport&&selected.status==="active"?<button type="button" className="ds-button" onClick={()=>setAction(current=>current==="change"?null:"change")}>{action==="change"?"收起办理":"办理续签/变更"}</button>:null}
    {action==="change"?<form className={styles.formGrid} onSubmit={event=>void saveChange(event)}><label className="form-field"><span>办理类型</span><select value={changeForm.changeType} onChange={event=>setChangeForm({...changeForm,changeType:event.target.value})}><option value="renewal">续签</option><option value="amendment">变更</option><option value="termination">终止</option><option value="correction">更正</option></select></label><label className="form-field"><span>新开始日期/生效日期</span><input required type="date" value={changeForm.newStartDate} onChange={event=>setChangeForm({...changeForm,newStartDate:event.target.value})}/></label><label className="form-field"><span>新结束日期</span><input type="date" min={changeForm.newStartDate||undefined} value={changeForm.newEndDate} onChange={event=>setChangeForm({...changeForm,newEndDate:event.target.value})}/></label><label className="form-field"><span>办理备注</span><input maxLength={500} value={changeForm.remark} onChange={event=>setChangeForm({...changeForm,remark:event.target.value})}/></label><button className="ds-button" disabled={saving} type="submit">{saving?"保存中":"保存变更草稿"}</button></form>:null}
    {canReadDocuments?<><h3>合同附件</h3>{canUpload&&!selected.isHistoricalImport?<FileUploader compact bizType="hr_contract_document" bizId={selected.id} policyKey="contract" label="上传合同附件" onUploaded={()=>setAttachmentRefresh(value=>value+1)}/>:null}<AttachmentList compact label="合同附件" emptyLabel="暂无合同附件" bizType="hr_contract_document" bizId={selected.id} refreshKey={attachmentRefresh} readPermissions={[HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE]} downloadPermissions={[HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE]} mutationDisabled={!canManageDocuments||selected.isHistoricalImport} mutationPermission={HR_PERMISSIONS.HR_CONTRACT_DOCUMENT_MANAGE}/></>:<p className={styles.emptyState}>无附件查看权限</p>}
    <h3>续签与变更历史</h3><div className={`ds-mobile-record-list ${contractStyles.recordList}`}>{selected.changes.length?selected.changes.map(change=><article className="ds-mobile-record" key={change.id}><strong>第 {change.sequenceNo} 次 · {changeLabels[change.changeType]??change.changeType}</strong><span>{change.previousStartDate??"未登记"} 至 {change.previousEndDate??"无固定期限"} → {change.newStartDate} 至 {change.newEndDate??"无固定期限"}</span><span>{change.isHistoricalImport?"旧系统历史记录":change.status==="draft"?"新系统草稿":change.status==="cancelled"?"已取消":"新系统记录"}</span>{canManage&&!change.isHistoricalImport&&change.status==="draft"?<div className={styles.actionRow}><button type="button" className="ds-button" disabled={saving} onClick={()=>void actChange(change.id,"apply")}>确认变更</button><button type="button" className="ds-button" disabled={saving} onClick={()=>void actChange(change.id,"cancel")}>取消变更</button></div>:null}</article>):<p className={styles.emptyState}>暂无续签或变更记录。</p>}</div>
    <h3>办理轨迹</h3><div className={`ds-mobile-record-list ${contractStyles.recordList}`}>{selected.actions?.length?selected.actions.map(item=><article className="ds-mobile-record" key={item.id}><strong>第 {item.sequenceNo} 步 · {actionLabels[item.action]??item.action}</strong><span>{item.fromStatus?`${statusLabels[item.fromStatus]??item.fromStatus} → `:""}{statusLabels[item.toStatus]??item.toStatus}</span><span>{new Date(item.occurredAt).toLocaleString("zh-CN")}</span></article>):<p className={styles.emptyState}>旧系统历史合同暂无新平台办理轨迹。</p>}</div>
   </section>:null}
  </main>
 </PermissionGuard>;
}
