"use client";
import {useCallback,useState} from "react";
import {hrApi,type HrGoalChangeContext,type HrGoalChangeDetail} from "../../../lib/hr-api";
import {getAccessToken} from "../../../lib/authz";
import {requireGoalChangeDetail} from "./goals-workflow";
import {useResource} from "./goal-resource";
import styles from "../hr-workbench.module.css";
import local from "./goals.module.css";
const fields:Record<string,string>={goalName:"目标名称",goalLevel:"目标层级",weight:"权重",metricType:"指标类型",metricName:"指标名称",targetValue:"目标值",unit:"单位",metricDefinition:"统计口径",startDate:"开始日期",dueDate:"截止日期",status:"状态"};
const labels:Record<string,string>={group:"集团",department:"部门",employee:"员工",numeric:"数值",percentage:"百分比",milestone:"里程碑",count:"数量",currency:"金额",draft:"草稿",active:"进行中",completed:"已完成",cancelled:"已取消"};
type Props={id:string;context:HrGoalChangeContext;busy:boolean;error:string;close:()=>void;submit:(body:object)=>void};
export function GoalDefinitionEditor(props:Props){
 const read=useCallback((signal:AbortSignal)=>hrApi.goalChangeDetail(props.id,getAccessToken(),signal).then(value=>{const detail=requireGoalChangeDetail(value);if(detail.goal.id!==props.id)throw new Error("目标详情与当前选择不一致，请重新读取。");return detail;}),[props.id]);
 const detail=useResource<HrGoalChangeDetail>(true,read);
 return <section className="ds-panel" aria-label="目标定义编辑与版本"><div className={styles.sectionHeading}><h2>目标定义编辑与版本</h2><button className="ds-button" disabled={props.busy} onClick={props.close}>收起定义</button></div>{detail.loading?<p>正在读取当前定义及版本…</p>:null}{detail.error?<><p role="alert">{detail.error}</p><button className="ds-button" disabled={props.busy||detail.loading} onClick={()=>void detail.load()}>重新读取定义</button></>:null}{detail.data?<DefinitionForm key={`${detail.data.goal.id}-${detail.data.goal.currentVersionNo}`} {...props} detail={detail.data}/>:null}</section>;
}
function DefinitionForm({detail,context,busy,error,submit}:Props&{detail:HrGoalChangeDetail}){
 const g=detail.goal,[level,setLevel]=useState(g.goalLevel),[cycleId,setCycleId]=useState(g.cycleId),[parentId,setParentId]=useState(g.parentGoalId??""),[start,setStart]=useState(g.startDate);
 const closed=["completed","cancelled"].includes(g.status),cycle=context.cycles.find(c=>c.id===cycleId),parents=context.parents.filter(p=>p.id!==g.id&&p.cycleId===cycleId);
 const collaborators=[...context.employees.map(e=>({id:e.id,name:e.fullName})),...detail.collaborators.filter(c=>!context.employees.some(e=>e.id===c.employeeId)).map(c=>({id:c.employeeId,name:c.employeeName??"原协作者（当前不可选）"}))];
 const send=(form:FormData)=>{if(busy||closed)return;submit({cycleId,parentGoalId:level==="group"?undefined:parentId||undefined,goalLevel:level,ownerOrgId:level!=="group"?String(form.get("ownerOrgId"))||undefined:undefined,ownerEmployeeId:level==="employee"?String(form.get("ownerEmployeeId"))||undefined:undefined,goalName:String(form.get("goalName")).trim(),weight:Number(form.get("weight")),metricType:String(form.get("metricType")),metricName:String(form.get("metricName")).trim(),targetValue:String(form.get("targetValue"))===""?null:Number(form.get("targetValue")),unit:String(form.get("unit")).trim(),metricDefinition:String(form.get("metricDefinition")),startDate:start,dueDate:String(form.get("dueDate")),collaboratorEmployeeIds:form.getAll("collaboratorEmployeeIds").map(String),expectedVersionNo:g.currentVersionNo,changeReason:String(form.get("changeReason")).trim()});};
 return <><p>{g.goalName} · 当前定义版本 {g.currentVersionNo} · 执行进度 {Number(g.progress)*100}%</p>{closed?<p>该目标已结束，可查看定义和历史版本。</p>:null}<form className={styles.formGrid} aria-label="目标定义变更" onSubmit={event=>{event.preventDefault();send(new FormData(event.currentTarget));}}><fieldset disabled={busy||closed} style={{display:"contents"}}>
 <label className="form-field"><span>目标名称</span><input name="goalName" maxLength={200} defaultValue={g.goalName} required autoFocus/></label>
 <label className="form-field"><span>目标周期</span><select value={cycleId} onChange={e=>{setCycleId(e.target.value);setParentId("");}} required>{!context.cycles.some(c=>c.id===g.cycleId)?<option value={g.cycleId}>原目标周期（当前不可选）</option>:null}{context.cycles.map(c=><option key={c.id} value={c.id}>{c.cycleName}{c.status==="closed"?"（已关闭）":""}</option>)}</select></label>
 <label className="form-field"><span>目标层级</span><select value={level} onChange={e=>{setLevel(e.target.value);setParentId("");}}>{context.canCreateGroup||g.goalLevel==="group"?<option value="group">集团</option>:null}<option value="department">部门</option><option value="employee">员工</option></select></label>
 {level!=="group"?<label className="form-field"><span>上级目标</span><select value={parentId} onChange={e=>setParentId(e.target.value)} required><option value="">请选择上级</option>{parentId&&!parents.some(p=>p.id===parentId)?<option value={parentId}>原上级目标（当前不可选）</option>:null}{parents.map(p=><option key={p.id} value={p.id}>{p.goalName}</option>)}</select></label>:null}
 {level!=="group"?<label className="form-field"><span>部门归属</span><select name="ownerOrgId" defaultValue={g.ownerOrgId??""} required={level==="department"}><option value="">请选择部门</option>{g.ownerOrgId&&!context.orgs.some(o=>o.id===g.ownerOrgId)?<option value={g.ownerOrgId}>{g.ownerName??"原所属部门（当前不可选）"}</option>:null}{context.orgs.map(o=><option key={o.id} value={o.id}>{o.orgName}</option>)}</select></label>:null}
 {level==="employee"?<label className="form-field"><span>员工归属</span><select name="ownerEmployeeId" defaultValue={g.ownerEmployeeId??""} required><option value="">请选择员工</option>{g.ownerEmployeeId&&!context.employees.some(e=>e.id===g.ownerEmployeeId)?<option value={g.ownerEmployeeId}>{g.ownerName??"原所属员工（当前不可选）"}</option>:null}{context.employees.map(e=><option key={e.id} value={e.id}>{e.fullName}</option>)}</select></label>:null}
 <label className="form-field"><span>指标类型</span><select name="metricType" defaultValue={g.metricType}>{["numeric","percentage","milestone","count","currency"].map(v=><option key={v} value={v}>{labels[v]}</option>)}</select></label>
 <label className="form-field"><span>指标名称</span><input name="metricName" maxLength={100} defaultValue={g.metricName??""} required/></label>
 <label className="form-field"><span>目标值</span><input name="targetValue" type="number" step="0.0001" defaultValue={g.targetValue??""} onFocus={e=>e.currentTarget.select()}/></label>
 <label className="form-field"><span>单位</span><input name="unit" maxLength={32} defaultValue={g.unit??""} required/></label>
 <label className="form-field"><span>权重</span><input name="weight" type="number" min="0.0001" max="1" step="0.0001" defaultValue={g.weight} required onFocus={e=>e.currentTarget.select()}/></label>
 <label className="form-field"><span>统计口径</span><textarea name="metricDefinition" maxLength={1000} defaultValue={g.metricDefinition??""}/></label>
 <label className="form-field"><span>开始日期</span><input type="date" value={start} min={cycle?.startDate} max={cycle?.endDate} onChange={e=>setStart(e.target.value)} required/></label>
 <label className="form-field"><span>截止日期</span><input name="dueDate" type="date" min={start||cycle?.startDate} max={cycle?.endDate} defaultValue={g.dueDate} required/></label>
 <label className="form-field"><span>协作者（可多选）</span><select name="collaboratorEmployeeIds" multiple defaultValue={detail.collaborators.map(c=>c.employeeId)}>{collaborators.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
 <label className="form-field"><span>变更原因</span><textarea name="changeReason" maxLength={1000} required/></label>
 {!closed?<div className={styles.formActions}><button className="ds-button ds-button-primary">保存定义并留存版本</button></div>:null}</fieldset>{error?<p className="form-error" role="alert">{error}</p>:null}</form>
 <h3>历史定义版本</h3><div className={`ds-mobile-record-list ${local.records}`}>{detail.versions.length?detail.versions.map(v=><article className="ds-mobile-record" key={v.versionNo}><strong>版本 {v.versionNo} · {v.createdAt}</strong><span>变更原因：{v.changeReason}</span>{Object.entries(fields).filter(([k])=>Object.hasOwn(v.snapshot,k)).map(([k,label])=><span key={k}>{label}：{v.snapshot[k]==null?"未填写":labels[String(v.snapshot[k])]??String(v.snapshot[k])}</span>)}{Object.hasOwn(v.snapshot,"cycleId")?<span>目标周期：{context.cycles.find(c=>c.id===v.snapshot.cycleId)?.cycleName??"历史周期（当前名称不可用）"}</span>:null}{Object.hasOwn(v.snapshot,"parentGoalId")?<span>上级目标：{v.snapshot.parentGoalId?context.parents.find(p=>p.id===v.snapshot.parentGoalId)?.goalName??"历史上级（当前名称不可用）":"无"}</span>:null}{Object.hasOwn(v.snapshot,"ownerOrgId")?<span>所属部门：{v.snapshot.ownerOrgId?context.orgs.find(o=>o.id===v.snapshot.ownerOrgId)?.orgName??"历史部门（当前名称不可用）":"无"}</span>:null}{Object.hasOwn(v.snapshot,"ownerEmployeeId")?<span>所属员工：{v.snapshot.ownerEmployeeId?context.employees.find(e=>e.id===v.snapshot.ownerEmployeeId)?.fullName??"历史员工（当前名称不可用）":"无"}</span>:null}{Array.isArray(v.snapshot.collaboratorEmployeeIds)?<span>版本协作者：{v.snapshot.collaboratorEmployeeIds.length} 人</span>:null}</article>):<p>暂无历史版本。</p>}</div></>;
}
