"use client";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {PermissionGuard} from "../../../components/auth/PermissionGuard";
import {useAuthUser} from "../../../lib/auth-context";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrGoal,type HrWorkReport} from "../../../lib/hr-api";
import {hasPermission} from "../../../lib/permissions";
import styles from "../hr-workbench.module.css";
import {hrLoadErrorMessage} from "../hr-errors";
import {isForbiddenError} from "../../../lib/api-client";
const label:Record<string,string>={daily:"日报",weekly:"周报",monthly:"月报",draft:"草稿",submitted:"待审核",resubmitted:"重新待审",confirmed:"已确认",returned:"已退回"};
export function HrWorkReportsClient(){
 const user=useAuthUser(),canDraft=hasPermission(user,HR_PERMISSIONS.HR_WORK_REPORT_DRAFT),canSubmit=hasPermission(user,HR_PERMISSIONS.HR_WORK_REPORT_SUBMIT),canReview=hasPermission(user,HR_PERMISSIONS.HR_WORK_REPORT_REVIEW),canTeamRead=hasPermission(user,HR_PERMISSIONS.HR_WORK_REPORT_TEAM_READ)||canReview;
 const [mine,setMine]=useState<HrWorkReport[]>([]),[team,setTeam]=useState<HrWorkReport[]>([]),[goals,setGoals]=useState<HrGoal[]>([]),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[forbidden,setForbidden]=useState(false),[editing,setEditing]=useState<HrWorkReport|null|"new">(null);
 const requestRef=useRef(0),controllerRef=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{controllerRef.current?.abort();const request=++requestRef.current,controller=new AbortController();controllerRef.current=controller;setLoading(true);setForbidden(false);setMine([]);setTeam([]);setGoals([]);setEditing(null);try{const token=getAccessToken();const [myRows,myGoals,teamRows]=await Promise.all([hrApi.myWorkReports(token,controller.signal),hrApi.goals(true,token,{},controller.signal),canTeamRead?hrApi.teamWorkReports(token,controller.signal):Promise.resolve([])]);if(request!==requestRef.current)return;setMine(myRows);setGoals(myGoals);setTeam(teamRows);setMessage("");}catch(error){if(request!==requestRef.current||controller.signal.aborted)return;setForbidden(isForbiddenError(error));setMessage(hrLoadErrorMessage(error,"加载汇报失败"));}finally{if(request===requestRef.current)setLoading(false);}},[canTeamRead]);
 useEffect(()=>{void load();return()=>{requestRef.current+=1;controllerRef.current?.abort();};},[load]);const pending=useMemo(()=>team.filter(item=>["submitted","resubmitted"].includes(item.status)).length,[team]);
 const saveDraft=async(form:FormData)=>{const goalId=String(form.get("goalId")??""),proposed=String(form.get("proposedProgress")??"");const body={reportType:String(form.get("reportType")),periodStart:String(form.get("periodStart")),periodEnd:String(form.get("periodEnd")),completedWork:String(form.get("completedWork"))||undefined,nextPlan:String(form.get("nextPlan"))||undefined,risks:String(form.get("risks"))||undefined,collaborationNeeds:String(form.get("collaborationNeeds"))||undefined,hours:String(form.get("hours"))?Number(form.get("hours")):undefined,goalSuggestions:goalId?[{goalId,proposedProgress:proposed?Number(proposed)/100:undefined,suggestionSummary:String(form.get("suggestionSummary"))||undefined}]:[]};try{if(editing!=="new"&&editing)await hrApi.updateWorkReport(editing.id,body,getAccessToken());else await hrApi.createWorkReport(body,getAccessToken());setEditing(null);await load();}catch(error){setMessage(error instanceof Error?error.message:"保存草稿失败");}};
 const submit=async(id:string)=>{try{await hrApi.submitWorkReport(id,getAccessToken());await load();}catch(error){setMessage(error instanceof Error?error.message:"提交失败");}};
 const review=async(form:FormData)=>{try{await hrApi.reviewWorkReport(String(form.get("reportId")),{action:String(form.get("action")),comment:String(form.get("comment"))||undefined},getAccessToken());await load();}catch(error){setMessage(error instanceof Error?error.message:"审核失败");}};
 const edit=editing==="new"?null:editing;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_WORK_REPORTS_PAGE}><main className={`content ds-page ${styles.page}`}>
 <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">日常执行</span><h1>工作汇报</h1><p>保存草稿，确认无误后再提交主管。</p></div>{canDraft?<button type="button" className="ds-button ds-button-primary" onClick={()=>setEditing(editing?null:"new")}>{editing?"收起":"写汇报"}</button>:null}</section>
 <section className="ds-kpi-grid" aria-label="汇报概览"><article className="ds-kpi-card"><span>我的记录</span><strong>{mine.length}</strong><small>日报、周报、月报</small></article><article className="ds-kpi-card"><span>待我补充</span><strong>{mine.filter(x=>x.status==="returned").length}</strong><small>修改后重新提交</small></article>{canTeamRead?<article className="ds-kpi-card"><span>团队待审</span><strong>{pending}</strong><small>主管当前待办</small></article>:null}</section>
 {editing?<form key={edit?.id??"new"} className={`ds-panel ${styles.formGrid}`} action={saveDraft}><div className={styles.sectionHeading}><div><span className="ds-eyebrow">{edit?"补充":"新建"}</span><h2>工作汇报草稿</h2></div></div><label className="form-field"><span>类型</span><select name="reportType" defaultValue={edit?.reportType??"daily"}><option value="daily">日报</option><option value="weekly">周报</option><option value="monthly">月报</option></select></label><label className="form-field"><span>开始日期</span><input name="periodStart" type="date" defaultValue={edit?.periodStart} required/></label><label className="form-field"><span>结束日期</span><input name="periodEnd" type="date" defaultValue={edit?.periodEnd} required/></label><label className="form-field"><span>工时</span><input name="hours" type="number" min="0" max="744" step="0.25" defaultValue={edit?.hours??""}/></label><label className="form-field"><span>完成工作</span><textarea name="completedWork" maxLength={10000} defaultValue={edit?.completedWork}/></label><label className="form-field"><span>下一步</span><textarea name="nextPlan" maxLength={10000} defaultValue={edit?.nextPlan??""}/></label><label className="form-field"><span>风险</span><textarea name="risks" maxLength={5000} defaultValue={edit?.risks??""}/></label><label className="form-field"><span>协同需求</span><textarea name="collaborationNeeds" maxLength={5000} defaultValue={edit?.collaborationNeeds??""}/></label><label className="form-field"><span>目标进度建议</span><select name="goalId" defaultValue={edit?.goalSuggestions[0]?.goalId??""}><option value="">不关联</option>{goals.filter(g=>!["completed","cancelled"].includes(g.status)).map(g=><option key={g.id} value={g.id}>{g.goalName}</option>)}</select></label><label className="form-field"><span>建议进度（%）</span><input name="proposedProgress" type="number" min="0" max="100" step="0.01" defaultValue={edit?.goalSuggestions[0]?.proposedProgress?Number(edit.goalSuggestions[0].proposedProgress)*100:""}/></label><label className="form-field"><span>建议说明</span><input name="suggestionSummary" maxLength={2000} defaultValue={edit?.goalSuggestions[0]?.suggestionSummary??""}/></label><div className={styles.formActions}><button className="ds-button ds-button-primary">保存草稿</button><button type="button" className="ds-button" onClick={()=>setEditing(null)}>取消</button></div></form>:null}
 {message?<div className="form-error" role="alert"><p>{forbidden?"当前角色无权读取该汇报范围。":message}</p><button type="button" className="ds-button" onClick={()=>void load()}>重试</button></div>:null}{loading?<section className="ds-panel"><p>正在加载…</p></section>:null}
 {canTeamRead&&!loading?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">主管待办</span><h2>团队审核</h2></div><strong>{pending} 项</strong></div><div className="ds-mobile-record-list">{team.length===0?<p className={styles.emptyState}>当前没有团队汇报。</p>:team.map(item=><article className="ds-mobile-record" key={item.id}><strong>{item.employeeName??"员工"} · {label[item.reportType]} · {item.periodStart}</strong><span>{label[item.status]??item.status} · 第 {item.submissionNo} 次提交</span><span>{item.completedWork}</span>{["submitted","resubmitted"].includes(item.status)&&canReview?<details className={styles.actionDisclosure}><summary>审核</summary><form className={styles.formGrid} action={review}><input type="hidden" name="reportId" value={item.id}/><label className="form-field"><span>结果</span><select name="action"><option value="confirmed">确认</option><option value="returned">退回</option></select></label><label className="form-field"><span>意见（退回必填）</span><input name="comment" maxLength={1000}/></label><button className="ds-button ds-button-primary">提交审核</button></form></details>:null}</article>)}</div></section>:null}
 {!loading?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">个人记录</span><h2>我的汇报</h2></div></div><div className="ds-mobile-record-list">{mine.length===0?<p className={styles.emptyState}>暂无汇报。</p>:mine.map(item=><article className="ds-mobile-record" key={item.id}><strong>{label[item.reportType]} · {item.periodStart}</strong><span>{label[item.status]??item.status}{item.submissionNo?` · 第 ${item.submissionNo} 次提交`:""}</span><span>{item.completedWork||"草稿尚未填写完成工作"}</span>{item.reviewComment?<span>主管意见：{item.reviewComment}</span>:null}<div className={styles.recordActions}>{canDraft&&["draft","returned"].includes(item.status)?<button type="button" className="ds-button" onClick={()=>setEditing(item)}>编辑</button>:null}{canSubmit&&["draft","returned"].includes(item.status)?<button type="button" className="ds-button ds-button-primary" onClick={()=>void submit(item.id)}>{item.status==="returned"?"重新提交":"提交审核"}</button>:null}</div></article>)}</div></section>:null}
 </main></PermissionGuard>;
}
