import type {HrFeedback360Task,HrFeedback360Cycle,HrFeedback360Nomination,HrFeedback360Options,HrFeedback360Result} from "../../../lib/hr-api";
const text=(v:unknown)=>typeof v==="string";
const rows=<T>(v:T[],valid:(r:T)=>boolean):T[]=>{if(!Array.isArray(v)||v.some(r=>!r||!valid(r)))throw Error("360办理响应不完整，请重新读取。");return v;};
export const feedbackTasks=(v:HrFeedback360Task[])=>rows(v,r=>[r.id,r.cycleName,r.subjectName,r.relationType,r.status,r.responseEnd].every(text)&&!!r.questionnaire&&Array.isArray(r.questionnaire.questions)&&r.questionnaire.questions.length>0&&r.questionnaire.questions.length<=100&&new Set(r.questionnaire.questions.map(q=>q.code)).size===r.questionnaire.questions.length&&r.questionnaire.questions.every(q=>q&&[q.code,q.text,q.dimensionCode].every(text)&&["rating","text"].includes(q.type)&&typeof q.required==="boolean"));
export const feedbackCycles=(v:HrFeedback360Cycle[])=>rows(v,r=>[r.id,r.cycleCode,r.cycleName,r.nominationEnd,r.responseEnd,r.status].every(text)&&Number.isSafeInteger(r.subjectCount)&&r.subjectCount>=0&&Number.isSafeInteger(r.minimumAnonymousResponses)&&r.minimumAnonymousResponses>=3&&r.minimumAnonymousResponses<=20);
export const feedbackNominations=(v:HrFeedback360Nomination[])=>rows(v,r=>[r.id,r.subjectId,r.cycleName,r.subjectName,r.nomineeName,r.relationType,r.status].every(text)&&typeof r.canDecide==="boolean");
export const feedbackResults=(v:HrFeedback360Result[])=>rows(v,r=>[r.cycleName,r.subjectName,r.publishedAt].every(text)&&Array.isArray(r.dimensions)&&r.dimensions.every(d=>d&&text(d.dimensionCode)&&text(d.averageScore)&&Number.isFinite(Number(d.averageScore))));
export function feedbackOptions(v:HrFeedback360Options){if(!v)throw Error("360办理响应不完整，请重新读取。");rows(v.employees,r=>[r.id,r.fullName,r.employeeCode].every(text));rows(v.models,r=>[r.id,r.modelName,r.versionName].every(text));rows(v.questionnaires,r=>[r.id,r.questionnaireName,r.versionName,r.modelVersionId].every(text));rows(v.subjects,r=>[r.id,r.cycleName,r.subjectName,r.status].every(text));return v;}
export function feedbackAnswers(task:HrFeedback360Task,form:FormData){return task.questionnaire.questions.flatMap<{questionCode:string;score?:number;text?:string}>(q=>{const value=String(form.get(q.code)??"").trim();if(!value){if(q.required)throw Error(`请填写${q.text}`);return[];}if(q.type==="rating"){const score=Number(value);if(!Number.isFinite(score)||score<0||score>100||Math.abs(score*100-Math.round(score*100))>1e-8)throw Error(`${q.text}须为0到100的数值，最多两位小数`);return[{questionCode:q.code,score}];}return[{questionCode:q.code,text:value}];});}
