"use client";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {useEffect,useRef,useState} from "react";
import {FeedbackConfiguration} from "./FeedbackConfiguration";
import {PermissionGuard} from "../../../components/auth/PermissionGuard";
import {ApiError} from "../../../lib/api-client";
import {useAuthUser} from "../../../lib/auth-context";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrFeedback360Task,type HrFeedback360Options} from "../../../lib/hr-api";
import {hasPermission} from "../../../lib/permissions";
import {hrLoadErrorMessage} from "../hr-errors";
import {useHrResource} from "../use-hr-resource";
import {feedbackTasks,feedbackCycles,feedbackOptions,feedbackNominations,feedbackResults,feedbackAnswers} from "./feedback-operation-data";
import styles from "../hr-workbench.module.css";
import local from "./feedback-operation.module.css";
const relations:Record<string,string>={self:"本人",manager:"上级",peer:"同级",subordinate:"下属",collaborator:"协作方"};
const states:Record<string,string>={draft:"草稿",nominating:"提名中",responding:"评价中",closed:"待发布",published:"已发布",pending:"待处理",submitted:"已提交",cancelled:"已取消"};
const reads={tasks:(s:AbortSignal)=>hrApi.myFeedback360Assignments(getAccessToken(),s).then(feedbackTasks),cycles:(s:AbortSignal)=>hrApi.feedback360Cycles(getAccessToken(),s).then(feedbackCycles),cycleContext:(s:AbortSignal)=>hrApi.feedback360CycleContext(getAccessToken(),s).then(feedbackCycles),options:(s:AbortSignal)=>hrApi.feedback360Options(getAccessToken(),s).then(feedbackOptions),pending:(s:AbortSignal)=>hrApi.feedback360PendingNominations(getAccessToken(),s).then(feedbackNominations),results:(s:AbortSignal)=>hrApi.feedback360Results(getAccessToken(),s).then(feedbackResults)};
type Target={kind:"activate"|"approve"|"reject"|"close"|"publish";id:string;name:string};
type Panel="cycle"|"nominate"|"answer"|"action"|null;
export function HrFeedbackClient(){const user=useAuthUser();return <FeedbackWorkspace key={JSON.stringify(user)}/>;}
function FeedbackWorkspace(){
 const user=useAuthUser(),cycleManage=hasPermission(user,H.HR_FEEDBACK_CYCLE_MANAGE),nominate=hasPermission(user,H.HR_FEEDBACK_NOMINATE),review=hasPermission(user,H.HR_FEEDBACK_NOMINATION_REVIEW),respond=hasPermission(user,H.HR_FEEDBACK_RESPOND),publish=hasPermission(user,H.HR_FEEDBACK_RESULT_PUBLISH),canRead=[H.HR_FEEDBACK_READ,H.HR_FEEDBACK_TEAM_READ,H.HR_FEEDBACK_SELF_READ].some(p=>hasPermission(user,p)),canResults=[H.HR_FEEDBACK_RESULT_READ,H.HR_FEEDBACK_TEAM_READ,H.HR_FEEDBACK_SELF_READ].some(p=>hasPermission(user,p));
 const tasks=useHrResource(respond,reads.tasks),cycles=useHrResource(canRead||cycleManage,cycleManage?reads.cycleContext:reads.cycles),options=useHrResource(cycleManage||nominate||review||publish,reads.options),pending=useHrResource(review,reads.pending),results=useHrResource(canResults,reads.results);
 const [panel,setPanel]=useState<Panel>(null),[answerId,setAnswerId]=useState<string|null>(null),[target,setTarget]=useState<Target|null>(null),[busy,setBusy]=useState(false),[writeError,setWriteError]=useState(""),[message,setMessage]=useState("");
 const writing=useRef(false),alive=useRef(true),key=useRef(crypto.randomUUID()),fingerprint=useRef<string|null>(null);useEffect(()=>{alive.current=true;return()=>{alive.current=false;}},[]);
 const refresh=async()=>{const loaded=await Promise.all([tasks.load(),cycles.load(),options.load(),pending.load(),results.load()]);return loaded.every(Boolean);};
 const close=()=>{if(writing.current)return;setPanel(null);setTarget(null);setAnswerId(null);setWriteError("");};
 const open=(next:Panel,id?:string,t?:Target)=>{if(writing.current)return;key.current=crypto.randomUUID();fingerprint.current=null;setWriteError("");setPanel(next);setAnswerId(id??null);setTarget(t??null);};
 const mutate=async(job:(operationKey:string)=>Promise<unknown>,success:string,payload:unknown)=>{if(writing.current||!alive.current)return;const nextFingerprint=JSON.stringify(payload);if(fingerprint.current!==null&&fingerprint.current!==nextFingerprint){setWriteError("上次提交结果尚未确认，请保持原内容重试，或刷新核对后重新办理。");return;}fingerprint.current=nextFingerprint;writing.current=true;setBusy(true);setWriteError("");setMessage("");try{await job(key.current);if(!alive.current)return;setPanel(null);setAnswerId(null);setTarget(null);setMessage(success);if(!await refresh()&&alive.current)setMessage(success+" 后续读取未完成，请刷新查看，勿重复提交。");}catch(e){if(alive.current){if(e instanceof ApiError&&[400,403,404,422].includes(e.status)){key.current=crypto.randomUUID();fingerprint.current=null;}setWriteError(hrLoadErrorMessage(e,"360办理失败"));}}finally{writing.current=false;if(alive.current)setBusy(false);}};
 const createCycle=(form:FormData)=>{if(!options.data)return;const modelVersionId=String(form.get("modelVersionId")),questionnaireVersionId=String(form.get("questionnaireVersionId")),employeeIds=form.getAll("employeeIds").map(String);if(!options.data.models.some(m=>m.id===modelVersionId)||!options.data.questionnaires.some(q=>q.id===questionnaireVersionId&&q.modelVersionId===modelVersionId)||!employeeIds.length||employeeIds.some(id=>!options.data!.employees.some(e=>e.id===id))){setWriteError("请从当前可用选项选择模型、匹配问卷及评价对象。");return;}void mutate(k=>hrApi.createFeedback360Cycle({cycleCode:String(form.get("cycleCode")),cycleName:String(form.get("cycleName")),modelVersionId,questionnaireVersionId,nominationEnd:String(form.get("nominationEnd")),responseEnd:String(form.get("responseEnd")),minimumAnonymousResponses:Number(form.get("minimumAnonymousResponses")),employeeIds},getAccessToken(),k),"360周期已创建，请核对后启动提名。",Array.from(form.entries()));};
 const nominateReviewer=(form:FormData)=>{if(!options.data)return;const subjectId=String(form.get("subjectId")),nomineeEmployeeId=String(form.get("nomineeEmployeeId"));if(!options.data.subjects.some(s=>s.id===subjectId&&["nominating","responding"].includes(s.status))||!options.data.employees.some(e=>e.id===nomineeEmployeeId)){setWriteError("提名对象已变化，请重新读取并选择。");return;}void mutate(k=>hrApi.nominateFeedback360({subjectId,nomineeEmployeeId,relationType:String(form.get("relationType"))},getAccessToken(),k),"评价人提名已提交。",Array.from(form.entries()));};
 const task=tasks.data?.find(t=>t.id===answerId&&t.status==="pending");
 const submitAnswer=(form:FormData)=>{if(!task)return;try{const answers=feedbackAnswers(task,form);if(!answers.length)throw Error("请至少回答一道题。");void mutate(k=>hrApi.submitFeedback360(task.id,{answers},getAccessToken(),k),"360评价已提交，内容不可修改。",{id:task.id,answers});}catch(e){setWriteError(hrLoadErrorMessage(e,"请核对答卷"));}};
 const submitTarget=(form:FormData)=>{if(!target)return;const t=target,valid=t.kind==="activate"?cycles.data?.some(c=>c.id===t.id&&c.status==="draft"):t.kind==="approve"||t.kind==="reject"?pending.data?.some(n=>n.id===t.id&&n.canDecide):options.data?.subjects.some(s=>s.id===t.id&&s.status===(t.kind==="close"?"responding":"closed"));if(!valid){setWriteError("办理对象已变化，请刷新后重新选择。");return;}const reason=String(form.get("reason")??"").trim();if(t.kind==="reject"&&!reason){setWriteError("请填写拒绝原因。");return;}void mutate(k=>t.kind==="activate"?hrApi.activateFeedback360Cycle(t.id,getAccessToken(),k):t.kind==="approve"||t.kind==="reject"?hrApi.decideFeedback360Nomination(t.id,{decision:t.kind,reason:t.kind==="reject"?reason:undefined},getAccessToken(),k):t.kind==="close"?hrApi.closeFeedback360Subject(t.id,getAccessToken(),k):hrApi.publishFeedback360Result(t.id,getAccessToken(),k),{activate:"周期已启动提名。",approve:"提名已批准并生成任务。",reject:"提名已拒绝。",close:"评价收集已关闭。",publish:"匿名结果已发布。"}[t.kind],{...t,reason});};
 const selectAction=(t:Target)=>open("action",undefined,t);
 const configurationPublished=async()=>{if(panel){setMessage("配置已发布，当前办理完成后可刷新选项。");return;}if(!await options.load())throw Error("配置已发布，周期选项刷新失败");};
 return <PermissionGuard module="hr" permission={H.HR_FEEDBACK_360_PAGE}><main className={`content ds-page ${styles.page} ${local.workspace}`}>
 <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">人才反馈</span><h1>360评价</h1><p>完成评价任务，管理提名审批，查看达到匿名门槛的维度结果。</p></div><div className={styles.heroActions}>{cycleManage?<button className="ds-button ds-button-primary" disabled={busy||!options.data} onClick={()=>open(panel==="cycle"?null:"cycle")}>新建周期</button>:null}<button className="ds-button" disabled={busy} onClick={()=>{if(writing.current)return;close();void refresh();}}>刷新评价工作台</button></div></section>
 <section className={`ds-kpi-grid ${styles.compactKpiGrid}`}><article className="ds-kpi-card"><span>待我评价</span><strong>{tasks.loading?"…":tasks.error?"待重试":tasks.data?.filter(t=>t.status==="pending").length??0}</strong></article><article className="ds-kpi-card"><span>待审批提名</span><strong>{pending.loading?"…":pending.error?"待重试":pending.data?.length??0}</strong></article><article className="ds-kpi-card"><span>已发布结果</span><strong>{results.loading?"…":results.error?"待重试":results.data?.length??0}</strong></article></section>
 {message?<p role="status" className="form-success">{message}</p>:null}
 {options.error||options.loading?<ResourceState label="业务选项" resource={options} busy={busy}/>:null}
 {panel==="cycle"&&options.data?<CycleForm key="cycle" options={options.data} busy={busy} error={writeError} submit={createCycle} close={close}/>:null}
 {panel==="nominate"&&options.data?<NominationForm key="nominate" options={options.data} busy={busy} error={writeError} submit={nominateReviewer} close={close}/>:null}
 {panel==="answer"&&task?<AnswerForm key={task.id} task={task} busy={busy} error={writeError} submit={submitAnswer} close={close}/>:null}
 {panel==="action"&&target?<form className={`ds-panel ${styles.formGrid}`} aria-label="360状态办理" onSubmit={e=>{e.preventDefault();submitTarget(new FormData(e.currentTarget));}}><fieldset disabled={busy} className={local.fields}><h2>{target.name} · {{activate:"启动提名",approve:"批准提名",reject:"拒绝提名",close:"关闭收集",publish:"发布结果"}[target.kind]}</h2>{target.kind==="reject"?<label className="form-field"><span>拒绝原因</span><textarea name="reason" maxLength={1000} required autoFocus/></label>:<p>{target.kind==="publish"?"仅达到既有匿名门槛的聚合结果可以发布。":"请核对当前对象后确认办理。"}</p>}<div className={styles.formActions}><button className="ds-button ds-button-primary">确认办理</button><button type="button" className="ds-button" onClick={close}>取消</button></div></fieldset>{writeError?<p role="alert" className="form-error">{writeError}</p>:null}</form>:null}
 {nominate?<section className="ds-panel"><h2>评价人提名</h2><button className="ds-button" disabled={busy||!options.data} onClick={()=>open(panel==="nominate"?null:"nominate")}>{panel==="nominate"?"收起提名":"发起提名"}</button></section>:null}
 {respond?<section className="ds-panel" aria-label="本人评价任务"><h2>待我评价</h2><ResourceState label="本人评价任务" resource={tasks} busy={busy}/>{tasks.data?<div className={`ds-mobile-record-list ${local.records}`}>{tasks.data.length?tasks.data.map(t=><article className="ds-mobile-record" key={t.id}><strong>{t.subjectName} · {relations[t.relationType]??t.relationType}</strong><span>{t.cycleName} · 截止 {t.responseEnd}</span><span>{states[t.status]??t.status}</span>{t.status==="pending"?<button className="ds-button" disabled={busy} onClick={()=>open("answer",t.id)}>开始评价</button>:null}</article>):<p>当前没有评价任务。</p>}</div>:null}</section>:null}
 {review?<section className="ds-panel" aria-label="提名审批"><h2>待审批提名</h2><ResourceState label="提名审批" resource={pending} busy={busy}/>{pending.data?<div className={`ds-mobile-record-list ${local.records}`}>{pending.data.length?pending.data.map(n=><article className="ds-mobile-record" key={n.id}><strong>{n.subjectName} · {relations[n.relationType]??n.relationType}</strong><span>{n.cycleName} · 提名 {n.nomineeName}</span>{n.canDecide?<div className={styles.recordActions}><button className="ds-button ds-button-primary" disabled={busy} onClick={()=>selectAction({kind:"approve",id:n.id,name:n.nomineeName})}>批准</button><button className="ds-button" disabled={busy} onClick={()=>selectAction({kind:"reject",id:n.id,name:n.nomineeName})}>拒绝</button></div>:<span>需由另一位审批人处理</span>}</article>):<p>没有待审批提名。</p>}</div>:null}</section>:null}
 {canRead||cycleManage?<section className="ds-panel" aria-label="周期运营"><h2>周期运营</h2><ResourceState label="周期运营" resource={cycles} busy={busy}/>{cycles.data?<div className={`ds-mobile-record-list ${local.records}`}>{cycles.data.length?cycles.data.map(c=><article className="ds-mobile-record" key={c.id}><strong>{c.cycleName} · {c.cycleCode}</strong><span>{states[c.status]??c.status} · {c.subjectCount} 人 · 评价截止 {c.responseEnd}</span>{cycleManage&&c.status==="draft"?<button className="ds-button" disabled={busy} onClick={()=>selectAction({kind:"activate",id:c.id,name:c.cycleName})}>启动提名</button>:null}</article>):<p>暂无评价周期。</p>}</div>:null}</section>:null}
 {publish?<section className="ds-panel" aria-label="结果发布"><h2>结果发布</h2>{options.data?<div className={`ds-mobile-record-list ${local.records}`}>{options.data.subjects.filter(s=>["responding","closed"].includes(s.status)).map(s=><article className="ds-mobile-record" key={s.id}><strong>{s.cycleName} · {s.subjectName}</strong><span>{states[s.status]}</span><button className="ds-button" disabled={busy} onClick={()=>selectAction({kind:s.status==="responding"?"close":"publish",id:s.id,name:s.subjectName})}>{s.status==="responding"?"关闭收集":"发布匿名结果"}</button></article>)}</div>:null}</section>:null}
 {canResults?<section className="ds-panel" aria-label="匿名聚合结果"><h2>匿名聚合结果</h2><ResourceState label="匿名结果" resource={results} busy={busy}/>{results.data?<div className={`ds-mobile-record-list ${local.records}`}>{results.data.length?results.data.map((r,i)=><article className="ds-mobile-record" key={`${r.publishedAt}-${i}`}><strong>{r.subjectName} · {r.cycleName}</strong>{r.dimensions.map(d=><span key={d.dimensionCode}>{d.dimensionCode}：{d.averageScore}</span>)}</article>):<p>尚无达到匿名门槛并发布的结果。</p>}</div>:null}</section>:null}
 <FeedbackConfiguration onPublished={configurationPublished}/>
 </main></PermissionGuard>;
}
function ResourceState({label,resource,busy}:{label:string;resource:{loading:boolean;error:string;load:()=>Promise<boolean>};busy:boolean}){return <>{resource.loading?<p>正在读取{label}…</p>:null}{resource.error?<div role="alert"><p>{label}：{resource.error}</p><button className="ds-button" disabled={busy||resource.loading} onClick={()=>void resource.load()}>重新读取{label}</button></div>:null}</>;}
type FormProps={busy:boolean;error:string;submit:(form:FormData)=>void;close:()=>void};
function FormActions({close}:{close:()=>void}){return <div className={styles.formActions}><button className="ds-button ds-button-primary">保存周期</button><button type="button" className="ds-button" onClick={close}>取消</button></div>;}
function CycleForm({options,busy,error,submit,close}:FormProps&{options:HrFeedback360Options}){
 const [model,setModel]=useState(""),[questionnaire,setQuestionnaire]=useState(""),[nominationEnd,setNominationEnd]=useState("");
 return <form className={`ds-panel ${styles.formGrid}`} aria-label="创建360周期" onSubmit={e=>{e.preventDefault();submit(new FormData(e.currentTarget));}}><fieldset className={local.fields} disabled={busy}><h2>创建360周期</h2><label className="form-field"><span>周期编码</span><input name="cycleCode" pattern="[A-Z][A-Z0-9_-]{1,31}" maxLength={32} required autoFocus/></label><label className="form-field"><span>周期名称</span><input name="cycleName" minLength={2} maxLength={120} required/></label><label className="form-field"><span>胜任力版本</span><select name="modelVersionId" value={model} onChange={e=>{setModel(e.target.value);setQuestionnaire("");}} required><option value="">请选择</option>{options.models.map(m=><option key={m.id} value={m.id}>{m.modelName} · {m.versionName}</option>)}</select></label><label className="form-field"><span>问卷版本</span><select name="questionnaireVersionId" value={questionnaire} onChange={e=>setQuestionnaire(e.target.value)} required><option value="">请选择匹配问卷</option>{options.questionnaires.filter(q=>q.modelVersionId===model).map(q=><option key={q.id} value={q.id}>{q.questionnaireName} · {q.versionName}</option>)}</select></label><label className="form-field"><span>提名截止</span><input name="nominationEnd" type="date" value={nominationEnd} onChange={e=>setNominationEnd(e.target.value)} required/></label><label className="form-field"><span>评价截止</span><input name="responseEnd" type="date" min={nominationEnd} required/></label><label className="form-field"><span>匿名最小样本</span><input name="minimumAnonymousResponses" type="number" min="3" max="20" step="1" defaultValue="3" required onFocus={e=>e.currentTarget.select()}/></label><label className="form-field"><span>评价对象（可多选）</span><select name="employeeIds" multiple size={5} required>{options.employees.map(e=><option key={e.id} value={e.id}>{e.fullName} · {e.employeeCode}</option>)}</select></label><FormActions close={close}/></fieldset>{error?<p role="alert" className="form-error">{error}</p>:null}</form>;
}
function NominationForm({options,busy,error,submit,close}:FormProps&{options:HrFeedback360Options}){return <form className={`ds-panel ${styles.formGrid}`} aria-label="评价人提名" onSubmit={e=>{e.preventDefault();submit(new FormData(e.currentTarget));}}><fieldset className={local.fields} disabled={busy}><h2>评价人提名</h2><label className="form-field"><span>评价对象</span><select name="subjectId" required autoFocus><option value="">请选择</option>{options.subjects.filter(s=>["nominating","responding"].includes(s.status)).map(s=><option key={s.id} value={s.id}>{s.cycleName} · {s.subjectName}</option>)}</select></label><label className="form-field"><span>评价人</span><select name="nomineeEmployeeId" required><option value="">请选择</option>{options.employees.map(e=><option key={e.id} value={e.id}>{e.fullName} · {e.employeeCode}</option>)}</select></label><label className="form-field"><span>关系</span><select name="relationType">{Object.entries(relations).filter(([value])=>value!=="collaborator").map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><div className={styles.formActions}><button className="ds-button ds-button-primary">提交提名</button><button type="button" className="ds-button" onClick={close}>取消</button></div></fieldset>{error?<p role="alert" className="form-error">{error}</p>:null}</form>;}
function AnswerForm({task,busy,error,submit,close}:FormProps&{task:HrFeedback360Task}){return <form className={`ds-panel ${styles.formGrid}`} aria-label="本人360答卷" onSubmit={e=>{e.preventDefault();submit(new FormData(e.currentTarget));}}><fieldset className={local.fields} disabled={busy}><h2>{task.subjectName} · {task.cycleName}</h2>{task.questionnaire.questions.map(q=><label className="form-field" key={q.code}><span>{q.text}{q.required?"":"（选填）"}</span>{q.type==="rating"?<input name={q.code} type="number" min="0" max="100" step="0.01" required={q.required} onFocus={e=>e.currentTarget.select()}/>:<textarea name={q.code} maxLength={2000} required={q.required}/>}</label>)}<div className={styles.formActions}><button className="ds-button ds-button-primary">确认提交</button><button type="button" className="ds-button" onClick={close}>取消</button></div></fieldset>{error?<p role="alert" className="form-error">{error}</p>:null}</form>;}
