"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {createIdempotencyKey} from "../../../lib/api-client";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrCandidateProfile,type HrCandidateProfileHistory,type HrCandidateProfileRequisitionOption,type SaveHrCandidateProfileInput} from "../../../lib/hr-api";
import {hrLoadErrorMessage} from "../hr-errors";
import styles from "./recruitment.module.css";
const fields=[['candidateNo','候选人编号'],['fullName','姓名'],['source','来源'],['expectedOnboardDate','预计入职'],['mobile','手机号'],['email','邮箱'],['identityNumber','证件号码']] as const;
type Field=typeof fields[number][0];
type Draft=Record<Field,string>;
const protectedFields=['mobile','email','identityNumber'] as const;
const nullable=['source','expectedOnboardDate',...protectedFields];
const record=(v:unknown):v is Record<string,unknown>=>typeof v==='object'&&v!==null&&!Array.isArray(v);
const validTime=(v:unknown)=>typeof v==='string'&&/T.*(?:Z|[+-]\d\d:\d\d)$/.test(v)&&Number.isFinite(Date.parse(v));
const validDate=(v:unknown)=>typeof v==='string'&&/^\d{4}-\d\d-\d\d$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
export function projectCandidateProfile(v:unknown,id:string):HrCandidateProfile{
 if(!record(v)||v.id!==id||!Number.isSafeInteger(v.version)||Number(v.version)<1||typeof v.sensitiveAvailable!=='boolean'||!validTime(v.updatedAt))throw Error('资料响应与候选人不一致');
 for(const k of ['candidateNo','fullName','requisitionId','requisitionTitle'])if(typeof v[k]!=='string'||!v[k])throw Error('资料响应缺少业务字段');
 if(!['talent_pool','screening','interview','offer','hired','rejected','withdrawn'].includes(String(v.stage)))throw Error('候选人状态无效');
 for(const k of ['source','latestEvaluation','convertedEmployeeId','mobileMasked','emailMasked','identityMasked'])if(v[k]!==null&&typeof v[k]!=='string')throw Error('资料响应字段无效');
 if(v.expectedOnboardDate!==null&&!validDate(v.expectedOnboardDate))throw Error('预计入职日期无效');
 for(const k of protectedFields){if(v.sensitiveAvailable){if(v[k]!==null&&typeof v[k]!=='string')throw Error('完整资料响应无效');}else if(Object.hasOwn(v,k))throw Error('受限资料响应无效');}
 // Build a projection explicitly: never forward unknown server fields to the parent or draft.
 return {id,version:Number(v.version),updatedAt:v.updatedAt as string,sensitiveAvailable:v.sensitiveAvailable,candidateNo:v.candidateNo as string,fullName:v.fullName as string,requisitionId:v.requisitionId as string,requisitionTitle:v.requisitionTitle as string,stage:v.stage as string,source:v.source as string|null,expectedOnboardDate:v.expectedOnboardDate as string|null,latestEvaluation:v.latestEvaluation as string|null,convertedEmployeeId:v.convertedEmployeeId as string|null,mobileMasked:v.mobileMasked as string|null,emailMasked:v.emailMasked as string|null,identityMasked:v.identityMasked as string|null,...(v.sensitiveAvailable?{mobile:v.mobile as string|null,email:v.email as string|null,identityNumber:v.identityNumber as string|null}:{})};
}
const asDraft=(v:HrCandidateProfile):Draft=>Object.fromEntries(fields.map(([k])=>[k,v[k]??''])) as Draft;
const canonical=(k:Field,v:string)=>{const t=v.trim();return nullable.includes(k)&&!t?null:k==='email'?t.toLowerCase():k==='mobile'||k==='identityNumber'?t.replace(/\s+/g,'').toUpperCase():t;};
function changes(base:HrCandidateProfile,draft:Draft,req:string,reason:string):SaveHrCandidateProfileInput{
 const out:SaveHrCandidateProfileInput={expectedVersion:base.version,changeReason:reason.trim()};
 for(const [k] of fields){if(protectedFields.some(p=>p===k)&&!base.sensitiveAvailable)continue;const v=canonical(k,draft[k]);if(v!==canonical(k,base[k]??''))Object.assign(out,{[k]:v});}
 if(req!==base.requisitionId)out.requisitionId=req;
 return out;
}
function assertPage(v:unknown,page:number):asserts v is {items:unknown[];total:number;page:number;page_size:number}{
 if(!record(v)||!Array.isArray(v.items)||!Number.isSafeInteger(v.total)||Number(v.total)<0||v.page!==page||v.page_size!==10||v.items.length>10||v.items.length>Number(v.total))throw Error('资料分页响应无效');
}
const stageLabels:Record<string,string>={talent_pool:'人才库',screening:'筛选',interview:'面试',offer:'待录用',hired:'已录用',rejected:'未通过',withdrawn:'已退出'};
function snapshotText(v:HrCandidateProfile){return [...fields.filter(([k])=>v.sensitiveAvailable||!protectedFields.some(p=>p===k)).map(([k,label])=>`${label}：${v[k]??'未登记'}`),`招聘需求：${v.requisitionTitle}`,`阶段：${stageLabels[v.stage]??v.stage}`,`电话摘要：${v.mobileMasked??'未登记'}`,`邮箱摘要：${v.emailMasked??'未登记'}`,`证件摘要：${v.identityMasked??'未登记'}`].join('；');}
export function CandidateProfile({candidateId,canManage,disabled,onBusyChange,onSaved}:{candidateId:string;canManage:boolean;disabled:boolean;onBusyChange:(busy:boolean)=>void;onSaved:(row:HrCandidateProfile)=>void}){
 const [open,setOpen]=useState(false),[base,setBase]=useState<HrCandidateProfile|null>(null),[draft,setDraft]=useState<Draft|null>(null),[req,setReq]=useState(''),[reason,setReason]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[conflict,setConflict]=useState<HrCandidateProfile|null>(null),[conflictPending,setConflictPending]=useState(false);
 const [history,setHistory]=useState<HrCandidateProfileHistory[]>([]),[historyPage,setHistoryPage]=useState(1),[historyTotal,setHistoryTotal]=useState(0),[historyError,setHistoryError]=useState('');
 const [optionsOpen,setOptionsOpen]=useState(false),[keyword,setKeyword]=useState(''),[optionPage,setOptionPage]=useState(1),[options,setOptions]=useState<HrCandidateProfileRequisitionOption[]>([]),[optionTotal,setOptionTotal]=useState(0),[optionError,setOptionError]=useState(''),[optionLoading,setOptionLoading]=useState(false),[chosen,setChosen]=useState<HrCandidateProfileRequisitionOption|null>(null);
 const alive=useRef(true),identity=useRef(candidateId),savingRef=useRef(false),requests=useRef<Record<string,AbortController>>({}),attempt=useRef<{signature:string;key:string}|null>(null);
 identity.current=candidateId;
 const beginRead=useCallback((kind:string)=>{requests.current[kind]?.abort();const c=new AbortController();requests.current[kind]=c;return c;},[]);
 const current=(kind:string,c:AbortController,id:string)=>alive.current&&identity.current===id&&!c.signal.aborted&&requests.current[kind]===c;
 useEffect(()=>{alive.current=true;setOpen(false);setBase(null);setDraft(null);setConflict(null);setConflictPending(false);setHistory([]);setOptions([]);setChosen(null);setOptionsOpen(false);setReason('');setError('');setMessage('');attempt.current=null;return()=>{alive.current=false;Object.values(requests.current).forEach(c=>c.abort());};},[candidateId,canManage]);
 const readCurrent=async()=>{const c=beginRead('current');setLoading(true);setError('');setBase(null);try{const row=projectCandidateProfile(await hrApi.recruitmentCandidateProfile(candidateId,getAccessToken(),c.signal),candidateId);if(!current('current',c,candidateId))return;setBase(row);setDraft(asDraft(row));setReq(row.requisitionId);setReason('');setConflict(null);setConflictPending(false);attempt.current=null;}catch(e){if(current('current',c,candidateId))setError(hrLoadErrorMessage(e,'读取候选人资料失败'));}finally{if(current('current',c,candidateId))setLoading(false);}};
 const readHistory=useCallback(async(page:number)=>{const c=beginRead('history');setHistoryError('');try{const result=await hrApi.recruitmentCandidateProfileHistory(candidateId,getAccessToken(),page,10,c.signal);if(!current('history',c,candidateId))return;assertPage(result,page);const rows=result.items.map(value=>{if(!record(value)||typeof value.id!=='string'||!value.id||typeof value.changeReason!=='string'||typeof value.actorDisplayName!=='string'||!validTime(value.occurredAt))throw Error('资料历史响应无效');const before=projectCandidateProfile(value.before,candidateId),after=projectCandidateProfile(value.after,candidateId);if(after.version!==before.version+1)throw Error('资料历史版本无效');return {id:value.id,before,after,changeReason:value.changeReason,actorDisplayName:value.actorDisplayName,occurredAt:value.occurredAt as string};});setHistory(rows);setHistoryTotal(result.total);setHistoryPage(page);}catch(e){if(current('history',c,candidateId))setHistoryError(hrLoadErrorMessage(e,'读取资料更正历史失败'));}},[candidateId,beginRead]);
 const readOptions=async(page:number)=>{const c=beginRead('options');setOptionLoading(true);setOptionError('');setOptions([]);try{const result=await hrApi.recruitmentCandidateProfileRequisitionOptions(candidateId,getAccessToken(),page,10,keyword.trim(),c.signal);if(!current('options',c,candidateId))return;assertPage(result,page);const rows=result.items.map(v=>{if(!record(v)||!['id','requisitionCode','title','orgName'].every(k=>typeof v[k]==='string')||!['draft','open'].includes(String(v.status)))throw Error('招聘需求选项无效');return v as unknown as HrCandidateProfileRequisitionOption;});setOptions(rows);setOptionTotal(result.total);setOptionPage(page);}catch(e){if(current('options',c,candidateId))setOptionError(hrLoadErrorMessage(e,'读取可选招聘需求失败'));}finally{if(current('options',c,candidateId))setOptionLoading(false);}};
 const readConflict=async()=>{const id=candidateId,c=beginRead('conflict');setConflict(null);try{const row=projectCandidateProfile(await hrApi.recruitmentCandidateProfile(id,getAccessToken(),c.signal),id);if(current('conflict',c,id)){setConflict(row);if(!row.sensitiveAvailable){requests.current.history?.abort();requests.current.current?.abort();setHistory([]);setDraft(d=>d?{...d,mobile:'',email:'',identityNumber:''}:d);setBase(b=>b?{...b,sensitiveAvailable:false,mobile:undefined,email:undefined,identityNumber:undefined}:b);}}}catch(e){if(current('conflict',c,id))setError(hrLoadErrorMessage(e,'读取最新资料失败，请保留草稿并重新核对。'));}};
 const save=async()=>{
  if(savingRef.current||disabled||!canManage||!base||!draft||conflictPending)return;
  const body=changes(base,draft,req,reason);
  if(!body.changeReason||!draft.candidateNo.trim()||!draft.fullName.trim()){setError('请填写编号、姓名及更正原因。');return;}
  if(Object.keys(body).length===2){setError('请先修改需要更正的资料。');return;}
  if((base.stage==='hired'||base.convertedEmployeeId)&&body.requisitionId){setError('已录用或已转员工，请保留当前招聘需求。');return;}
  const signature=JSON.stringify(body);if(attempt.current?.signature!==signature)attempt.current={signature,key:createIdempotencyKey('hr-candidate-profile')};const key=attempt.current.key,id=candidateId;
  savingRef.current=true;setSaving(true);onBusyChange(true);setError('');setMessage('');
  try{const row=projectCandidateProfile(await hrApi.saveRecruitmentCandidateProfile(id,body,getAccessToken(),key),id);if(!alive.current||identity.current!==id)return;
   if(row.version!==base.version+1||row.sensitiveAvailable!==base.sensitiveAvailable||row.stage!==base.stage||row.convertedEmployeeId!==base.convertedEmployeeId)throw Error('保存回执版本或状态不一致');
   for(const [k] of fields){if(protectedFields.some(p=>p===k)&&!base.sensitiveAvailable)continue;const expected=Object.hasOwn(body,k)?body[k]:base[k];if(row[k]!==expected)throw Error('保存回执资料不一致');}
   if(row.latestEvaluation!==base.latestEvaluation)throw Error('保存回执阶段评价不一致');for(const [field,mask] of [['mobile','mobileMasked'],['email','emailMasked'],['identityNumber','identityMasked']] as const){if(!Object.hasOwn(body,field)&&row[mask]!==base[mask])throw Error('保存回执联系方式摘要不一致');}if(row.requisitionId!==(body.requisitionId??base.requisitionId))throw Error('保存回执招聘需求不一致');
   onSaved(row);setBase(row);setDraft(asDraft(row));setReason('');attempt.current=null;setMessage(`资料已保存，版本 ${row.version}。`);void readHistory(1);
  }catch(e){if(!alive.current||identity.current!==id)return;setError(hrLoadErrorMessage(e,'资料保存失败或回执无效，请保留草稿后重试。'));
   if(record(e)&&(e.status===409||e.statusCode===409)&&e.message==='Candidate changed; reload before saving'){setConflictPending(true);await readConflict();}

  }finally{savingRef.current=false;if(alive.current&&identity.current===id){setSaving(false);onBusyChange(false);}}
 };
 const locked=disabled||saving;
 const acknowledge=()=>{if(!conflict||!draft||!base||locked)return;const merged=asDraft(conflict);for(const [k] of fields){if(protectedFields.some(p=>p===k)&&(!base.sensitiveAvailable||!conflict.sensitiveAvailable))continue;if(canonical(k,draft[k])!==canonical(k,base[k]??''))merged[k]=draft[k];}if(req===base.requisitionId){setReq(conflict.requisitionId);setChosen(null);}setDraft(merged);setBase(conflict);setConflict(null);setConflictPending(false);attempt.current=null;setError('');setOptionsOpen(false);requests.current.options?.abort();};
 return <section className={styles.profile} aria-label="候选人资料维护"><button type="button" className="ds-button" disabled={locked} onClick={()=>{if(open){setOpen(false);return;}setOpen(true);void readCurrent();void readHistory(1);}}>{open?'收起资料':canManage?'维护候选人资料':'资料更正历史'}</button>{open?<>
  {loading?<p role="status">正在读取资料…</p>:null}{error?<p role="alert" className="form-error">{error}</p>:null}{!base&&!loading?<button type="button" className="ds-button" disabled={locked} onClick={()=>void readCurrent()}>重新读取资料</button>:null}{message?<p role="status">{message}</p>:null}
  {base&&draft?<><p>招聘需求：{chosen?.id===req?chosen.title:base.requisitionTitle} · 资料版本 {base.version}</p>{!base.sensitiveAvailable?<p>电话：{base.mobileMasked??'未登记'}；邮箱：{base.emailMasked??'未登记'}；证件：{base.identityMasked??'未登记'}</p>:null}
  {canManage?<form aria-label="更正候选人资料" className={styles.profileForm} onSubmit={e=>{e.preventDefault();void save();}}>
   {fields.filter(([k])=>base.sensitiveAvailable||!protectedFields.some(p=>p===k)).map(([k,label])=><label className="form-field" key={k}><span>{label}</span><input type={k==='expectedOnboardDate'?'date':k==='email'?'email':k==='mobile'?'tel':'text'} required={k==='candidateNo'||k==='fullName'} maxLength={k==='candidateNo'||k==='source'||k==='identityNumber'?64:k==='fullName'?100:k==='mobile'?24:k==='email'?160:undefined} pattern={k==='mobile'?'\\+?[0-9 -]{6,24}':undefined} disabled={locked} value={draft[k]} onChange={e=>{attempt.current=null;setDraft({...draft,[k]:e.target.value});}}/></label>)}
   <label className="form-field"><span>更正原因</span><textarea required maxLength={1000} disabled={locked} value={reason} onChange={e=>{attempt.current=null;setReason(e.target.value);}}/></label>
   <div className={styles.profileActions}>{base.stage!=='hired'&&!base.convertedEmployeeId?<button type="button" className="ds-button" disabled={locked||conflictPending} onClick={()=>{setOptionsOpen(true);void readOptions(1);}}>更换招聘需求</button>:<span>已录用或已转员工，保留招聘需求。</span>}<button type="button" className="ds-button" disabled={locked} onClick={()=>{setReq(base.requisitionId);setChosen(null);attempt.current=null;}}>保留原招聘需求</button><button className="ds-button ds-button-primary" disabled={locked||conflictPending}>保存资料更正</button></div>
  </form>:<p>{snapshotText(base)}</p>}
  {optionsOpen&&canManage&&base.stage!=='hired'&&!base.convertedEmployeeId?<div aria-label="可选招聘需求" className={styles.profileOptions}><form onSubmit={e=>{e.preventDefault();void readOptions(1);}}><label className="form-field"><span>搜索招聘需求</span><input value={keyword} disabled={locked} onChange={e=>setKeyword(e.target.value)}/></label><button className="ds-button" disabled={locked||optionLoading}>搜索需求</button></form>{optionError?<p role="alert">{optionError}<button type="button" className="ds-button" disabled={locked||optionLoading} onClick={()=>void readOptions(optionPage)}>重读招聘需求</button></p>:null}{optionLoading?<p>读取中…</p>:options.map(o=><button type="button" className="ds-command-card" key={o.id} disabled={locked||conflictPending} aria-pressed={req===o.id} onClick={()=>{setReq(o.id);setChosen(o);attempt.current=null;}}>{o.requisitionCode} · {o.title} · {o.orgName}</button>)}<nav className={styles.profileActions} aria-label="招聘需求选项分页"><button type="button" className="ds-button" disabled={locked||optionLoading||optionPage<=1} onClick={()=>void readOptions(optionPage-1)}>需求选项上一页</button><span>第 {optionPage} / {Math.max(1,Math.ceil(optionTotal/10))} 页</span><button type="button" className="ds-button" disabled={locked||optionLoading||optionPage*10>=optionTotal} onClick={()=>void readOptions(optionPage+1)}>需求选项下一页</button></nav></div>:null}
  </>:null}
  {conflictPending?<div role="region" aria-label="资料冲突比较"><p>资料已有更新，请核对后继续。草稿保留在表单中。</p>{conflict?<><p>服务器版本 {conflict.version}：{snapshotText(conflict)}</p><p>草稿招聘需求：{chosen?.id===req?chosen.title:base?.requisitionTitle}（{req}）</p><p>草稿：{draft?fields.filter(([k])=>conflict.sensitiveAvailable||!protectedFields.some(p=>p===k)).map(([k,l])=>`${l}：${draft[k]||'未登记'}`).join('；'):''}</p><button type="button" className="ds-button" disabled={locked} onClick={acknowledge}>确认以草稿更新</button></>:<button type="button" className="ds-button" disabled={locked} onClick={()=>void readConflict()}>重新核对最新资料</button>}</div>:null}
  <div className={`ds-mobile-record-list ${styles.historyRecords}`}><h3>资料更正记录</h3>{historyError?<p role="alert">{historyError}<button type="button" className="ds-button" disabled={locked} onClick={()=>void readHistory(historyPage)}>重读资料历史</button></p>:null}{history.map(h=><article className="ds-mobile-record" key={h.id}><strong>版本 {h.before.version} → {h.after.version}</strong><span>{h.actorDisplayName} · {new Date(h.occurredAt).toLocaleString('zh-CN')}</span><p>更正前：{snapshotText(h.before)}</p><p>更正后：{snapshotText(h.after)}</p><p>原因：{h.changeReason}</p></article>)}{!history.length&&!historyError?<p>尚无资料更正记录。</p>:null}<nav className={styles.profileActions} aria-label="资料历史分页"><button type="button" className="ds-button" disabled={locked||historyPage<=1} onClick={()=>void readHistory(historyPage-1)}>资料历史上一页</button><span>第 {historyPage} / {Math.max(1,Math.ceil(historyTotal/10))} 页</span><button type="button" className="ds-button" disabled={locked||historyPage*10>=historyTotal} onClick={()=>void readHistory(historyPage+1)}>资料历史下一页</button></nav></div>
 </>:null}</section>;
}
