"use client";
import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import Link from "next/link";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { FileUploader } from "../../../components/files/FileUploader";
import { AttachmentList } from "../../../components/files/AttachmentList";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { isForbiddenError } from "../../../lib/api-client";
import { hrApi,type HrContract,type HrDirectoryOrgOption,type HrDirectoryUserOption,type HrEmployee,type HrEmployeeProfile,type HrEmployeeRecords,type HrEmploymentEvent } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import styles from "../hr-workbench.module.css";

const statusLabels:Record<string,string>={preboarding:"待入职",probation:"试用期",active:"在职",suspended:"停职",departed:"已离职"};
const typeLabels:Record<string,string>={full_time:"全职",part_time:"兼职",intern:"实习",contractor:"合同制"};
const employeeDocumentReadPermissions=[HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_READ,HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_TEAM_READ,HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_SELF_READ,HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_MANAGE];
const ProfileField=({name,label,value,type="text",maxLength,min,max,step}:{name:string;label:string;value?:string|null;type?:string;maxLength?:number;min?:number;max?:number;step?:string})=><label className="form-field"><span>{label}</span><input name={name} type={type} defaultValue={value??""} maxLength={maxLength} min={min} max={max} step={step}/></label>;
function YuzhouBasicProfileFields({profile}:{profile:HrEmployeeProfile|null}){return <div className={styles.profileFields} key={profile?.id??"new-profile"}>
 <fieldset className={styles.profileGroup}><legend>身份与个人信息</legend><ProfileField name="englishName" label="英文姓名" value={profile?.englishName} maxLength={100}/><label className="form-field"><span>性别</span><select name="gender" defaultValue={profile?.gender??""}><option value="">未登记</option><option value="男">男</option><option value="女">女</option><option value="其他">其他</option></select></label><ProfileField name="dateOfBirth" label="出生日期" value={profile?.dateOfBirth} type="date"/><ProfileField name="ethnicity" label="民族" value={profile?.ethnicity} maxLength={64}/><ProfileField name="nativePlace" label="籍贯" value={profile?.nativePlace} maxLength={128}/><ProfileField name="politicalStatus" label="政治面貌" value={profile?.politicalStatus} maxLength={64}/><ProfileField name="partyJoinDate" label="参加党派时间" value={profile?.partyJoinDate} type="date"/><ProfileField name="heightCm" label="身高（厘米）" value={profile?.heightCm} type="number" min={30} max={300} step="0.01"/><ProfileField name="weightKg" label="体重（公斤）" value={profile?.weightKg} type="number" min={1} max={500} step="0.01"/><ProfileField name="maritalStatus" label="婚姻状况" value={profile?.maritalStatus} maxLength={32}/><ProfileField name="healthStatus" label="健康状况" value={profile?.healthStatus} maxLength={64}/><ProfileField name="householdRegistration" label="户口所在地" value={profile?.householdRegistration} maxLength={256}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>教育与语言</legend><ProfileField name="highestEducation" label="最高学历" value={profile?.highestEducation} maxLength={64}/><ProfileField name="major" label="主修专业" value={profile?.major} maxLength={128}/><ProfileField name="degree" label="学位" value={profile?.degree} maxLength={64}/><ProfileField name="foreignLanguage" label="外语" value={profile?.foreignLanguage} maxLength={64}/><ProfileField name="languageLevel" label="外语水平" value={profile?.languageLevel} maxLength={64}/><ProfileField name="graduationDate" label="毕业日期" value={profile?.graduationDate} type="date"/><ProfileField name="graduationSchool" label="毕业学校" value={profile?.graduationSchool} maxLength={160}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>职务与专业资格</legend><ProfileField name="jobTitle" label="职务" value={profile?.jobTitle} maxLength={100}/><ProfileField name="jobGrade" label="职务级别" value={profile?.jobGrade} maxLength={64}/><ProfileField name="employeeCategory" label="员工类别" value={profile?.employeeCategory} maxLength={64}/><ProfileField name="technicalTitle" label="技术职称" value={profile?.technicalTitle} maxLength={100}/><ProfileField name="technicalGrade" label="职称级别" value={profile?.technicalGrade} maxLength={64}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>证件与联系方式</legend><label className="form-field"><span>证件类型</span><select name="idType" defaultValue={profile?.idType??""}><option value="">未登记</option><option value="resident_id">居民身份证</option><option value="passport">护照</option><option value="other">其他</option></select></label><ProfileField name="idNumber" label="证件号（加密保存）" value={profile?.idNumber} maxLength={64}/><ProfileField name="personalMobile" label="个人手机" value={profile?.personalMobile} maxLength={32}/><ProfileField name="homePhone" label="家庭电话" value={profile?.homePhone} maxLength={32}/><ProfileField name="personalEmail" label="个人邮箱" value={profile?.personalEmail} type="email" maxLength={128}/><ProfileField name="address" label="联系地址" value={profile?.address} maxLength={500}/><ProfileField name="emergencyContactName" label="紧急联系人" value={profile?.emergencyContactName} maxLength={100}/><ProfileField name="emergencyContactMobile" label="紧急联系电话" value={profile?.emergencyContactMobile} maxLength={32}/></fieldset>
 </div>}
function EmployeeProfileSummary({profile}:{profile:HrEmployeeProfile}){return <div className={`ds-mobile-record-list ${styles.employeeRecordList}`}>
 <article className="ds-mobile-record"><strong>{profile.masked?"受保护档案（已脱敏）":"完整敏感档案"}</strong><span>证件：{profile.idNumberMasked||"未登记"}</span><span>个人手机：{profile.personalMobile||"未登记"}</span><span>个人邮箱：{profile.personalEmail||"未登记"}</span><span>紧急联系人：{profile.emergencyContactName||"未登记"} · {profile.emergencyContactMobile||"未登记"}</span><span>职务/职级：{profile.jobTitle||"未登记"} · {profile.jobGrade||"未登记"}</span></article>
 </div>}
export function HrEmployeesClient(){
 const user=useAuthUser(),canManage=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_MANAGE),canReadAll=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_READ),canReadTeam=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_TEAM_READ),canReadSelf=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_SELF_READ),canReadDirectory=canReadAll||canReadTeam||canReadSelf;
 const canReadProfileAll=hasAnyPermission(user,[HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_READ,HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE]),canReadProfileTeam=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_TEAM_READ),canReadProfileSelf=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_SELF_READ),canManageProfile=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_PROFILE_MANAGE),canReadEvents=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYMENT_EVENT_READ);
 const canReadContracts=hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ,HR_PERMISSIONS.HR_CONTRACT_SELF_READ]),contractsSelfOnly=!hasAnyPermission(user,[HR_PERMISSIONS.HR_CONTRACT_READ,HR_PERMISSIONS.HR_CONTRACT_TEAM_READ])&&hasPermission(user,HR_PERMISSIONS.HR_CONTRACT_SELF_READ),canReadInsurance=hasAnyPermission(user,[HR_PERMISSIONS.HR_INSURANCE_READ,HR_PERMISSIONS.HR_INSURANCE_TEAM_READ,HR_PERMISSIONS.HR_INSURANCE_SELF_READ]);
 const canReadEmployeeDocuments=hasAnyPermission(user,employeeDocumentReadPermissions),canManageEmployeeDocuments=hasPermission(user,HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_MANAGE);
 const [rows,setRows]=useState<HrEmployee[]>([]),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[message,setMessage]=useState(""),[apiForbidden,setApiForbidden]=useState(false);
 const [orgs,setOrgs]=useState<HrDirectoryOrgOption[]>([]),[users,setUsers]=useState<HrDirectoryUserOption[]>([]),[positions,setPositions]=useState<Awaited<ReturnType<typeof hrApi.positions>>>([]);
 const [selected,setSelected]=useState<HrEmployee|null>(null),[events,setEvents]=useState<HrEmploymentEvent[]>([]),[busy,setBusy]=useState(false);
 const [profile,setProfile]=useState<HrEmployeeProfile|null>(null);
 const [records,setRecords]=useState<HrEmployeeRecords|null>(null);
 const [employeeContracts,setEmployeeContracts]=useState<HrContract[]>([]);
 const [attachmentRefresh,setAttachmentRefresh]=useState(0);
 const [query,setQuery]=useState(""),[statusFilter,setStatusFilter]=useState(""),[createOpen,setCreateOpen]=useState(false);
 const detailAbort=useRef<AbortController|null>(null);
 const visibleRows=useMemo(()=>{const keyword=query.trim().toLowerCase();return rows.filter(row=>(!statusFilter||row.employmentStatus===statusFilter)&&(!keyword||row.fullName.toLowerCase().includes(keyword)||row.employeeCode.toLowerCase().includes(keyword)))},[query,rows,statusFilter]);
 const load=useCallback(async()=>{setLoading(true);setMessage("");setApiForbidden(false);try{const token=getAccessToken();if(canReadAll||canReadTeam){const result=await hrApi.employees(token,1,100,{keyword:query.trim(),status:statusFilter});setRows(result.items);setTotal(result.total)}else if(canReadSelf){setRows([await hrApi.me(token)]);setTotal(1)}else{setApiForbidden(true);setRows([]);setTotal(0)}}catch(e){if(isForbiddenError(e))setApiForbidden(true);else setMessage(e instanceof Error?e.message:"加载员工档案失败");setRows([]);setTotal(0);setSelected(null);setEvents([]);setProfile(null);setRecords(null);setEmployeeContracts([])}finally{setLoading(false)}},[canReadAll,canReadSelf,canReadTeam,query,statusFilter]);
 const loadMore=async()=>{if(loadingMore||rows.length>=total)return;setLoadingMore(true);setMessage("");try{const result=await hrApi.employees(getAccessToken(),Math.floor(rows.length/100)+1,100,{keyword:query.trim(),status:statusFilter});setRows(current=>[...current,...result.items.filter(item=>!current.some(existing=>existing.id===item.id))]);setTotal(result.total)}catch(e){setMessage(e instanceof Error?e.message:"加载更多员工档案失败")}finally{setLoadingMore(false)}};
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),300);return()=>window.clearTimeout(timer)},[load]);
 useEffect(()=>{if(selected&&!rows.some(row=>row.id===selected.id)){detailAbort.current?.abort();setSelected(null);setEvents([]);setProfile(null);setRecords(null);setEmployeeContracts([])}},[rows,selected]);
 useEffect(()=>()=>detailAbort.current?.abort(),[]);
 useEffect(()=>{if(!canManage)return;const token=getAccessToken();void Promise.all([hrApi.directoryOptions(token),hrApi.positions(token)]).then(([refs,p])=>{setOrgs(refs.orgs);setUsers(refs.users);setPositions(p)}).catch(e=>setMessage(e instanceof Error?e.message:"加载组织选项失败"))},[canManage]);
 const pick=async(row:HrEmployee)=>{detailAbort.current?.abort();const controller=new AbortController();detailAbort.current=controller;setSelected(row);setEvents([]);setProfile(null);setRecords(null);setEmployeeContracts([]);setMessage("");try{
  const token=getAccessToken(),canReadRecords=hasAnyPermission(user,[HR_PERMISSIONS.HR_EMPLOYEE_RECORD_READ,HR_PERMISSIONS.HR_EMPLOYEE_RECORD_TEAM_READ,HR_PERMISSIONS.HR_EMPLOYEE_RECORD_SELF_READ]);
  const detail=await hrApi.employee(row.id,token,controller.signal);
  const isSelf=detail.userId===user?.id;
  const [historyResult,profileResult,contractsResult,recordsResult]=await Promise.allSettled([
   canReadEvents?hrApi.events(row.id,token,controller.signal):Promise.resolve([]),
   canReadProfileAll||canReadProfileTeam?hrApi.profile(row.id,token,controller.signal):canReadProfileSelf&&isSelf?hrApi.myProfile(token,controller.signal):Promise.resolve(null),
   canReadContracts?hrApi.contracts(token,1,100,{keyword:row.employeeCode},contractsSelfOnly,controller.signal):Promise.resolve({items:[],total:0,page:1,page_size:100}),
   canReadRecords?hrApi.employeeRecords(row.id,token,controller.signal):Promise.resolve(null)
  ]);
  if(controller.signal.aborted||detailAbort.current!==controller)return;
  setSelected(detail);
  setEvents(historyResult.status==="fulfilled"?historyResult.value:[]);
  setProfile(profileResult.status==="fulfilled"?profileResult.value:null);
  setRecords(recordsResult.status==="fulfilled"?recordsResult.value:null);
  const contracts=contractsResult.status==="fulfilled"?contractsResult.value.items:[];
  setEmployeeContracts(contractsSelfOnly?contracts:contracts.filter(contract=>contract.employeeId===row.id));
  const failures=[historyResult,profileResult,contractsResult,recordsResult].filter(result=>result.status==="rejected"&&!isForbiddenError(result.reason)&&result.reason?.name!=="AbortError");
  if(failures.length)setMessage(`员工基本档案已加载，另有 ${failures.length} 个详情分区暂时不可用。`);
 }catch(e){if((e as Error).name==="AbortError"||detailAbort.current!==controller)return;if(isForbiddenError(e)){setSelected(null);setRecords(null);setMessage("当前员工详情不在您的数据权限范围内。")}else setMessage(e instanceof Error?e.message:"加载员工详情失败")}};
 const create=async(form:FormData)=>{try{setBusy(true);await hrApi.createEmployee({employeeCode:String(form.get("employeeCode")??""),fullName:String(form.get("fullName")??""),userId:String(form.get("userId")??"")||undefined,primaryOrgId:String(form.get("primaryOrgId")??"")||undefined,positionId:String(form.get("positionId")??"")||undefined,employmentType:String(form.get("employmentType")??"full_time"),employmentStatus:"preboarding",hireDate:String(form.get("hireDate")??"")||undefined,workLocation:String(form.get("workLocation")??"")||undefined},getAccessToken());await load();}catch(e){setMessage(e instanceof Error?e.message:"创建员工档案失败")}finally{setBusy(false)}};
 const transition=async(form:FormData)=>{if(!selected)return;try{setBusy(true);const updated=await hrApi.transition(selected.id,{action:String(form.get("action")),effectiveDate:String(form.get("effectiveDate")),reason:String(form.get("reason")),primaryOrgId:String(form.get("primaryOrgId")??"")||undefined,positionId:String(form.get("positionId")??"")||undefined,managerEmployeeId:String(form.get("managerEmployeeId")??"")||undefined},getAccessToken());setSelected(updated);await Promise.all([load(),pick(updated)])}catch(e){setMessage(e instanceof Error?e.message:"办理任职变动失败")}finally{setBusy(false)}};
 const saveProfile=async(form:FormData)=>{if(!selected)return;const value=(name:string)=>String(form.get(name)??"")||undefined,numberValue=(name:string)=>{const raw=value(name);return raw===undefined?undefined:Number(raw)};try{setBusy(true);const token=getAccessToken();await hrApi.updateProfile(selected.id,{idType:value("idType"),idNumber:value("idNumber"),englishName:value("englishName"),gender:value("gender"),dateOfBirth:value("dateOfBirth"),ethnicity:value("ethnicity"),nativePlace:value("nativePlace"),politicalStatus:value("politicalStatus"),partyJoinDate:value("partyJoinDate"),heightCm:numberValue("heightCm"),weightKg:numberValue("weightKg"),maritalStatus:value("maritalStatus"),healthStatus:value("healthStatus"),householdRegistration:value("householdRegistration"),highestEducation:value("highestEducation"),major:value("major"),degree:value("degree"),foreignLanguage:value("foreignLanguage"),languageLevel:value("languageLevel"),graduationDate:value("graduationDate"),graduationSchool:value("graduationSchool"),homePhone:value("homePhone"),jobTitle:value("jobTitle"),jobGrade:value("jobGrade"),employeeCategory:value("employeeCategory"),technicalTitle:value("technicalTitle"),technicalGrade:value("technicalGrade"),personalMobile:value("personalMobile"),personalEmail:value("personalEmail"),address:value("address"),emergencyContactName:value("emergencyContactName"),emergencyContactMobile:value("emergencyContactMobile")},token);setProfile(await hrApi.profile(selected.id,token));setMessage("敏感档案已保存")}catch(e){setMessage(e instanceof Error?e.message:"保存敏感档案失败")}finally{setBusy(false)}};
 const forbidden=<main className={`content ds-page ${styles.page}`}><section className="ds-panel"><h1>无权访问员工档案</h1><p>请联系管理员配置员工自助或人事档案权限。</p></section></main>;
 if(apiForbidden)return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_EMPLOYEES_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="当前账号拥有员工档案页面入口，但没有可用的员工目录或本人档案读取权限。"/></section></main></PermissionGuard>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_EMPLOYEES_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}>
  <section className={styles.workbenchHeader}><div><span className="ds-eyebrow">人力资源管理</span><h1>{canReadAll?"员工档案":canReadTeam?"团队员工档案":"我的档案"}</h1><p>{canReadAll?`共 ${total} 份可见员工档案，当前已加载 ${rows.length} 份。`:canReadTeam?`本人负责组织及子树内共 ${total} 份员工档案。`:"当前登录账号关联的任职档案。"}</p></div>{canManage?<button className="ds-button ds-button-primary" type="button" onClick={()=>setCreateOpen(value=>!value)}>{createOpen?"收起新增":"新增员工"}</button>:null}</section>
  {canManage&&createOpen?<form className={`ds-panel ${styles.formGrid}`} action={create}><label className="form-field"><span>员工编号</span><input name="employeeCode" maxLength={64} required/></label><label className="form-field"><span>姓名</span><input name="fullName" maxLength={100} required/></label><label className="form-field"><span>系统账号</span><select name="userId"><option value="">待入职，暂不关联</option>{users.map(x=><option key={x.id} value={x.id}>{x.realName||x.displayName||x.username}</option>)}</select></label><label className="form-field"><span>所属组织</span><select name="primaryOrgId"><option value="">暂未分配</option>{orgs.map(x=><option key={x.id} value={x.id}>{x.orgName}</option>)}</select></label><label className="form-field"><span>岗位</span><select name="positionId"><option value="">暂未分配</option>{positions.map(x=><option key={x.id} value={x.id}>{x.positionName}</option>)}</select></label><label className="form-field"><span>用工类型</span><select name="employmentType"><option value="full_time">全职</option><option value="part_time">兼职</option><option value="intern">实习</option><option value="contractor">合同制</option></select></label><label className="form-field"><span>预计入职日期</span><input name="hireDate" type="date"/></label><label className="form-field"><span>工作地点</span><input name="workLocation" maxLength={128}/></label><button className="ds-button ds-button-primary" type="submit" disabled={busy}>保存待入职员工</button></form>:null}
  {message?<p className="form-error" role="alert">{message}</p>:null}
  {selected&&canReadEmployeeDocuments?<><section className="ds-panel"><h2>{selected.fullName} · 人员照片</h2>{canManageEmployeeDocuments?<FileUploader compact bizType="hr_employee_photo" bizId={selected.id} policyKey="image" label="上传员工照片" safeErrorMessage="员工照片上传失败" onUploaded={()=>setAttachmentRefresh(value=>value+1)}/>:null}<AttachmentList compact label="员工照片" emptyLabel="暂无员工照片" bizType="hr_employee_photo" bizId={selected.id} refreshKey={attachmentRefresh} readPermissions={employeeDocumentReadPermissions} downloadPermissions={employeeDocumentReadPermissions} mutationDisabled={!canManageEmployeeDocuments} mutationPermission={HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_MANAGE}/></section><section className="ds-panel"><h2>{selected.fullName} · 档案附件</h2>{canManageEmployeeDocuments?<FileUploader compact bizType="hr_employee_document" bizId={selected.id} policyKey="general" label="上传员工档案附件" safeErrorMessage="员工档案附件上传失败" onUploaded={()=>setAttachmentRefresh(value=>value+1)}/>:null}<AttachmentList compact label="档案附件" emptyLabel="暂无档案附件" bizType="hr_employee_document" bizId={selected.id} refreshKey={attachmentRefresh} readPermissions={employeeDocumentReadPermissions} downloadPermissions={employeeDocumentReadPermissions} mutationDisabled={!canManageEmployeeDocuments} mutationPermission={HR_PERMISSIONS.HR_EMPLOYEE_DOCUMENT_MANAGE}/></section></>:selected?<section className="ds-panel"><h2>{selected.fullName} · 档案附件</h2><p>无附件查看权限</p></section>:null}
  <section className="ds-panel"><div className={styles.directoryToolbar}><label className="form-field"><span>搜索员工</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="姓名或员工编号"/></label><label className="form-field"><span>任职状态</span><select value={statusFilter} onChange={event=>setStatusFilter(event.target.value)}><option value="">全部状态</option>{Object.entries(statusLabels).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label><span className="status-pill">已加载 {rows.length}/{total} · 筛选 {visibleRows.length} 条</span></div><div className={`ds-mobile-record-list ${styles.employeeRecordList}`}>{loading?<p>正在加载…</p>:visibleRows.length?visibleRows.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.fullName}</strong><span>{row.employeeCode}</span><span>{typeLabels[row.employmentType]??row.employmentType} · {statusLabels[row.employmentStatus]??row.employmentStatus}</span><span>{row.workLocation||"未设置工作地点"}</span><span>{row.userId?"已关联系统账号":"尚未关联系统账号"}</span>{canReadDirectory?<button className="ds-button" type="button" onClick={()=>void pick(row)}>{canManage||hasPermission(user,HR_PERMISSIONS.HR_EMPLOYMENT_TRANSITION)?"查看与办理":"查看档案"}</button>:null}</article>):<p>{rows.length?"没有符合筛选条件的员工。":"暂无可查看的员工档案。"}</p>}</div>{(canReadAll||canReadTeam)&&rows.length<total?<button className="ds-button ds-button-secondary" type="button" disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?"加载中…":"加载更多员工"}</button>:null}</section>
  {selected?<section className="ds-panel"><h2>{selected.fullName} · 员工详情</h2><p>{selected.employeeCode} · 当前状态：{statusLabels[selected.employmentStatus]??selected.employmentStatus}</p>{hasPermission(user,HR_PERMISSIONS.HR_EMPLOYMENT_TRANSITION)&&selected.employmentStatus!=="departed"?<form className={styles.formGrid} action={transition}><label className="form-field"><span>办理事项</span><select name="action" required>{selected.employmentStatus==="preboarding"?<><option value="start_probation">办理入职（进入试用）</option><option value="confirm_employment">办理入职（直接转正）</option></>:null}{selected.employmentStatus==="probation"?<option value="confirm_employment">试用转正</option>:null}{selected.employmentStatus==="active"?<><option value="transfer">调岗/调部门</option><option value="suspend">停职</option></>:null}{selected.employmentStatus==="suspended"?<option value="resume">恢复任职</option>:null}</select></label><label className="form-field"><span>生效日期</span><input name="effectiveDate" type="date" required/></label><label className="form-field"><span>调入组织（仅调岗）</span><select name="primaryOrgId"><option value="">请选择</option>{orgs.map(x=><option key={x.id} value={x.id}>{x.orgName}</option>)}</select></label><label className="form-field"><span>新岗位（仅调岗）</span><select name="positionId"><option value="">暂不分配</option>{positions.map(x=><option key={x.id} value={x.id}>{x.positionName}</option>)}</select></label><label className="form-field"><span>新直属上级（仅调岗）</span><select name="managerEmployeeId"><option value="">暂不设置</option>{rows.filter(x=>x.id!==selected.id&&x.employmentStatus!=="departed").map(x=><option key={x.id} value={x.id}>{x.fullName}</option>)}</select></label><label className="form-field"><span>办理原因</span><input name="reason" maxLength={500} required/></label><button className="ds-button ds-button-primary" disabled={busy}>确认办理并留痕</button></form>:null}{profile?<><h3>{profile.masked?"脱敏敏感档案":"敏感档案"}</h3><EmployeeProfileSummary profile={profile}/></>:null}{canManageProfile?<><h3>维护敏感档案</h3><p>玉舟基础档案字段按现代隐私规则保存；证件号加密、指纹去重，读取和修改均保留审计。</p><form className={styles.formGrid} action={saveProfile}><YuzhouBasicProfileFields profile={profile}/><button className="ds-button ds-button-primary" disabled={busy}>保存敏感档案</button></form></>:null}{canReadEvents?<><h3>任职历史</h3><div className={`ds-mobile-record-list ${styles.employeeRecordList}`}>{events.length?events.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.eventType}</strong><span>{x.effectiveDate}</span><span>{x.reason||"无备注"}</span></article>):<p>暂无任职变动记录。</p>}</div></>:null}</section>:null}
  {selected&&canReadContracts?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">员工生命周期</span><h2>{selected.fullName} · 劳动合同</h2></div><Link className="ds-button" href="/hr/contracts">进入合同台账</Link></div><div className={`ds-mobile-record-list ${styles.employeeRecordList}`}>{employeeContracts.length?employeeContracts.map(contract=><article className="ds-mobile-record" key={contract.id}><strong>{contract.contractTypeName}</strong><span>{contract.contractNo}</span><span>{contract.startDate??"未登记"} 至 {contract.endDate??"无固定期限"}</span><span>{contract.isHistoricalImport?"旧系统历史合同":contract.status}</span></article>):<p>当前员工暂无可见劳动合同。</p>}</div></section>:null}
  {selected&&records?<section className="ds-panel"><h2>{selected.fullName} · 扩展档案</h2><div className={`ds-mobile-record-list ${styles.employeeRecordList}`}>{records.experiences.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.organizationName}</strong><span>{x.type==="education"?"教育经历":"工作经历"} · {x.title||"未登记职务"}</span><span>{x.startDate} 至 {x.endDate||"至今"}</span></article>)}{records.skills.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.skillName}</strong><span>{x.proficiency||"未评级"}</span></article>)}{records.credentials.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.credentialName}</strong><span>{x.numberMasked||"未登记编号"} · {x.validTo?`有效至 ${x.validTo}`:"长期有效"}</span></article>)}{records.family.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.relationship}</strong><span>{x.fullNameMasked} · {x.contactMasked||"未登记联系方式"}</span></article>)}{!records.experiences.length&&!records.skills.length&&!records.credentials.length&&!records.family.length?<p>暂无可见扩展档案。</p>:null}</div></section>:null}
  {selected&&canReadInsurance?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">员工生命周期</span><h2>{selected.fullName} · 五险一金</h2></div><Link className="ds-button" href="/hr/insurance">进入社保台账</Link></div><p>按权限查看该员工历史月度参保与缴费信息；旧系统原始快照不会在页面出站。</p></section>:null}
 </main></PermissionGuard>;
}
