import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import test from "node:test";
const root=join(__dirname,"../..");
const read=(path:string)=>readFileSync(join(root,path),"utf8");
test("lifecycle workbench uses shared permission gates and mobile records",()=>{const page=read("app/hr/lifecycle/HrLifecycleClient.tsx"),api=read("lib/hr-api.ts"),menu=read("lib/menu.ts");assert.match(page,/HR_LIFECYCLE_PAGE/);assert.match(page,/ds-mobile-record-list/);assert.match(page,/listAbort\.current\?\.abort/);assert.match(page,/eventAbort\.current\?\.abort/);assert.match(page,/clearDetail/);assert.match(page,/i\.responsibleUserId === user\?\.id/);assert.match(page,/\["pending", "returned"\]\.includes\(i\.status\) && canReview/);assert.match(page,/当前没有可见任务/);assert.match(page,/重试/);assert.doesNotMatch(page,/tenantId|parkId|输入 UUID/);assert.match(api,/lifecycleChecklists/);assert.match(menu,/"\/hr\/lifecycle"/);});
test("employment event statistics use the atomic permission and isolated error state",()=>{const page=read("app/hr/lifecycle/HrLifecycleClient.tsx"),api=read("lib/hr-api.ts");assert.match(page,/HR_EMPLOYMENT_EVENT_READ/);assert.match(page,/statisticsAbort\.current\?\.abort/);assert.match(page,/statisticsError/);assert.match(page,/人事异动统计/);assert.match(page,/ds-kpi-grid/);assert.match(page,/type="date"/);assert.match(api,/employmentEventStatistics/);assert.match(api,/\/hr\/employment-events\/statistics/);});
test("employee extended record surface renders only server projections and cancels stale detail",()=>{const page=read("app/hr/employees/HrEmployeesClient.tsx"),family=read("app/hr/employees/components/HrFamilyRecords.tsx");assert.match(page,/employeeRecords/);assert.match(page,/detailAbort\.current\?\.abort/);assert.match(page,/controller\.signal\.aborted/);assert.match(page,/<HrFamilyRecords records=\{records\} canReadFull=\{hasPermission\(user,HR_PERMISSIONS\.HR_EMPLOYEE_FAMILY_READ\)\}/);assert.match(family,/fullNameMasked/);assert.match(family,/records\.fieldAccess\.family !== true/);assert.match(page,/numberMasked/);assert.doesNotMatch(page+family,/identityEncrypted|numberEncrypted|contactEncrypted/);});
