"use client";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { useCallback,useEffect,useState } from "react";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hrApi,type HrInsurancePeriod } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import { hrLoadErrorMessage } from "../hr-errors";
import styles from "../hr-workbench.module.css";

const kindLabels:Record<string,string>={pension:"养老保险",medical:"医疗保险",unemployment:"失业保险",injury:"工伤保险",maternity:"生育保险",housing_fund:"住房公积金"};
export function HrInsuranceClient(){
 const user=useAuthUser(),canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_INSURANCE_READ,HR_PERMISSIONS.HR_INSURANCE_TEAM_READ,HR_PERMISSIONS.HR_INSURANCE_SELF_READ]),full=hasPermission(user,HR_PERMISSIONS.HR_INSURANCE_READ),selfOnly=hasPermission(user,HR_PERMISSIONS.HR_INSURANCE_SELF_READ)&&!hasAnyPermission(user,[HR_PERMISSIONS.HR_INSURANCE_READ,HR_PERMISSIONS.HR_INSURANCE_TEAM_READ]);
 const [rows,setRows]=useState<HrInsurancePeriod[]>([]),[total,setTotal]=useState(0),[keyword,setKeyword]=useState(""),[debouncedKeyword,setDebouncedKeyword]=useState(""),[year,setYear]=useState(""),[month,setMonth]=useState(""),[reviewOnly,setReviewOnly]=useState(false),[selected,setSelected]=useState<HrInsurancePeriod|null>(null),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedKeyword(keyword.trim()),300);return()=>window.clearTimeout(timer);},[keyword]);
 const filters={keyword:debouncedKeyword||undefined,year:year?Number(year):undefined,month:month?Number(month):undefined,needsReview:reviewOnly?true:undefined};
 const load=useCallback(async()=>{if(!canRead){setLoading(false);return;}setLoading(true);setSelected(null);setMessage("");try{const result=await hrApi.insurancePeriods(getAccessToken(),1,30,filters,selfOnly);setRows(result.items);setTotal(result.total);}catch(error){setRows([]);setTotal(0);setMessage(hrLoadErrorMessage(error,"加载社保台账失败"));}finally{setLoading(false);}},[canRead,debouncedKeyword,month,reviewOnly,selfOnly,year]);
 useEffect(()=>{void load();},[load]);
 const loadMore=async()=>{if(loadingMore||rows.length>=total)return;setLoadingMore(true);try{const next=await hrApi.insurancePeriods(getAccessToken(),Math.floor(rows.length/30)+1,30,filters,selfOnly);setRows(current=>[...current,...next.items.filter(item=>!current.some(row=>row.id===item.id))]);}catch(error){setMessage(hrLoadErrorMessage(error,"加载更多社保记录失败"));}finally{setLoadingMore(false);}};
 const pick=async(row:HrInsurancePeriod)=>{setMessage("");try{setSelected(await hrApi.insurancePeriod(row.id,getAccessToken()));}catch(error){setSelected(null);setMessage(hrLoadErrorMessage(error,"加载社保明细失败"));}};
 const forbidden=<main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="无权访问五险一金"/></section></main>;
 if(!canRead)return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_INSURANCE_PAGE} fallback={forbidden}>{forbidden}</PermissionGuard>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_INSURANCE_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}>
  <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">员工保障</span><h1>{selfOnly?"我的五险一金":"五险一金台账"}</h1><p>{full?"按月核对个人与单位缴费、异常基数和待复核记录。":"查看权限范围内的个人缴费与参保状态，单位成本仅向 HR 授权岗位开放。"}</p></div></section>
  <section className={`ds-kpi-grid ${styles.compactKpiGrid}`} aria-label="社保台账概览"><article className="ds-kpi-card"><span>期间记录</span><strong>{total}</strong><small>当前筛选范围</small></article><article className="ds-kpi-card"><span>已加载个人缴费</span><strong>¥ {rows.reduce((sum,row)=>sum+Number(row.employeeAmount),0).toFixed(2)}</strong><small>精确到分</small></article><article className="ds-kpi-card"><span>待复核</span><strong>{rows.filter(row=>row.needsReview).length}</strong><small>当前已加载记录</small></article></section>
  <section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">历史台账</span><h2>员工月度明细</h2></div><strong>已加载 {rows.length}/{total}</strong></div><div className={styles.filterBar}>{!selfOnly?<label className="form-field"><span>员工</span><input type="search" placeholder="姓名或员工编号" value={keyword} onChange={event=>setKeyword(event.target.value)}/></label>:null}<label className="form-field"><span>年份</span><input type="number" min="1900" max="2200" value={year} onChange={event=>setYear(event.target.value)}/></label><label className="form-field"><span>月份</span><select value={month} onChange={event=>setMonth(event.target.value)}><option value="">全部月份</option>{Array.from({length:12},(_,index)=><option key={index+1} value={index+1}>{index+1} 月</option>)}</select></label><label className="form-field"><span>复核状态</span><select value={reviewOnly?"review":"all"} onChange={event=>setReviewOnly(event.target.value==="review")}><option value="all">全部记录</option><option value="review">仅待复核</option></select></label></div>{message?<p className="form-error" role="alert">{message}</p>:null}<div className="ds-mobile-record-list">{loading?<p className={styles.emptyState}>正在加载社保台账…</p>:rows.length?rows.map(row=><article className="ds-mobile-record" key={row.id}><strong>{row.employeeName?`${row.employeeName} · `:""}{row.periodYear} 年 {row.periodMonth} 月</strong>{row.employeeCode?<span>{row.employeeCode}</span>:null}<span>个人缴费 ¥ {row.employeeAmount} · 补充缴费 ¥ {row.supplementAmount}</span>{full?<span>单位缴费 ¥ {row.employerAmount} · 合计 ¥ {row.totalAmount}</span>:null}<span>{row.itemCount} 个险种{row.needsReview?" · 待复核":" · 已入账"}</span>{full||selfOnly?<button type="button" className="ds-button" onClick={()=>void pick(row)}>查看分项</button>:null}</article>):<p className={styles.emptyState}>当前筛选条件下没有社保记录。</p>}</div>{rows.length<total?<button className="ds-button" type="button" disabled={loadingMore} onClick={()=>void loadMore()}>{loadingMore?"加载中":"加载更多"}</button>:null}</section>
  {selected?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">期间明细</span><h2>{selected.employeeName?`${selected.employeeName} · `:""}{selected.periodYear} 年 {selected.periodMonth} 月</h2></div><strong>{selected.needsReview?"待复核":"已入账"}</strong></div><div className="ds-mobile-record-list">{selected.items?.map(item=><article className="ds-mobile-record" key={item.insuranceKind}><strong>{kindLabels[item.insuranceKind]??item.insuranceKind}</strong><span>缴费基数 {item.contributionBase??"未记录"}</span><span>个人 ¥ {item.employeeAmount??"0.00"} · 补充 ¥ {item.supplementAmount??"0.00"}</span>{full?<span>单位 ¥ {item.employerAmount??"0.00"} · 合计 ¥ {item.totalAmount??"0.00"}</span>:null}{item.legacyBaseNegative?<span className="status-pill status-warning">旧系统负基数，需复核</span>:null}</article>)}</div></section>:null}
 </main></PermissionGuard>;
}
