"use client";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {useCallback,useEffect,useMemo,useRef,useState} from "react";
import {PermissionGuard} from "../../../components/auth/PermissionGuard";
import {useAuthUser} from "../../../lib/auth-context";
import {getAccessToken} from "../../../lib/authz";
import {hrApi,type HrPerformanceCycleV2,type HrPerformanceReviewPage,type HrPerformanceReviewV2} from "../../../lib/hr-api";
import {hasAnyPermission,hasPermission} from "../../../lib/permissions";
import {hrLoadErrorMessage} from "../hr-errors";
import styles from "../hr-workbench.module.css";
import templateStyles from "./performance-template.module.css";
import {PerformanceRewardEvidence} from "./PerformanceRewardEvidence";
import {PerformanceTemplates} from "./PerformanceTemplates";
import {HrPerformanceLegacyPanel} from "./HrPerformanceLegacyPanel";
import {HrPerformanceLegacyRelationsPanel} from "./HrPerformanceLegacyRelationsPanel";
import {HrPerformanceLegacyAssessmentMasterPanel} from "./HrPerformanceLegacyAssessmentMasterPanel";
import {HrPerformanceLegacyAssessmentValuePanel} from "./HrPerformanceLegacyAssessmentValuePanel";
import {HrPerformanceLegacyAssessmentValueOfPersonPanel} from "./HrPerformanceLegacyAssessmentValueOfPersonPanel";
import {HrPerformanceLegacyPersonSummaryPanel} from "./HrPerformanceLegacyPersonSummaryPanel";
import {HrPerformanceLegacyWebAssQueryPanel} from "./HrPerformanceLegacyWebAssQueryPanel";

type Options={orgs:Array<{id:string;orgName:string}>;templates:Array<{id:string;templateName:string;versionName:string}>};
type Batch={id:string;cycleId:string;batchName:string;meetingAt:string;status:string;canAct:boolean};
type Editor={kind:"self"|"manager"|"calibrate"|"appeal"|"resolve";review:HrPerformanceReviewV2}|null;
const labels:Record<string,string>={planning:"规划中",self_review:"员工自评",manager_review:"主管评价",calibration:"校准中",employee_acknowledged:"待员工签收",appealed:"申诉处理中",confirmed:"已确认"};

export function HrPerformanceClient(){const user=useAuthUser();return <PerformanceWorkspace key={JSON.stringify(user)}/>;}
function PerformanceWorkspace(){
 const user=useAuthUser(),manage=hasPermission(user,HR_PERMISSIONS.HR_PERFORMANCE_MANAGE),templateManage=hasPermission(user,HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_MANAGE),canCalibrate=hasPermission(user,HR_PERMISSIONS.HR_PERFORMANCE_CALIBRATE);
 const canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_PERFORMANCE_READ,HR_PERMISSIONS.HR_PERFORMANCE_TEAM_READ,HR_PERMISSIONS.HR_PERFORMANCE_SELF_READ]),canTemplateRead=templateManage||hasPermission(user,HR_PERMISSIONS.HR_PERFORMANCE_TEMPLATE_READ);
 const [cycles,setCycles]=useState<HrPerformanceCycleV2[]>([]),[reviews,setReviews]=useState<HrPerformanceReviewV2[]>([]),[options,setOptions]=useState<Options>({orgs:[],templates:[]}),[calibrationUsers,setCalibrationUsers]=useState<Array<{id:string;displayName:string}>>([]),[batches,setBatches]=useState<Batch[]>([]),[mode,setMode]=useState<"cycle"|"batch"|null>(null),[editor,setEditor]=useState<Editor>(null),[state,setState]=useState<"loading"|"ready"|"forbidden"|"error">("loading"),[message,setMessage]=useState(""),[formError,setFormError]=useState(""),[loadError,setLoadError]=useState(""),[busy,setBusy]=useState(false),[decision,setDecision]=useState<"rejected"|"upheld">("rejected");
 const [evidenceReview,setEvidenceReview]=useState<HrPerformanceReviewV2|null>(null);
 const [reviewPage,setReviewPage]=useState(1),[cycleFilter,setCycleFilter]=useState(""),[statusFilter,setStatusFilter]=useState("");
 const [reviewCounts,setReviewCounts]=useState({total:0,pending:0,confirmed:0});
 const alive=useRef(true),writeLock=useRef(false);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;};},[]);
 const generation=useRef(0),request=useRef<AbortController|null>(null);
 const load=useCallback(async()=>{if(!alive.current)return;const current=++generation.current;request.current?.abort();const controller=new AbortController();request.current=controller;setState("loading");setLoadError("");setReviews([]);setEvidenceReview(null);setReviewCounts({total:0,pending:0,confirmed:0});setBatches([]);setEditor(null);try{const token=getAccessToken(),tasks:Promise<unknown>[]=[canRead?hrApi.performanceCyclesV2(token,controller.signal):Promise.resolve([]),canRead?hrApi.performanceReviewPageV2({page:reviewPage,pageSize:30,cycleId:cycleFilter,status:statusFilter},token,controller.signal):Promise.resolve({items:[],total:0,pending:0,confirmed:0,page:1,pageSize:30})];const slots:{options?:number;calibration?:number;batches?:number}={};if(manage){slots.options=tasks.length;tasks.push(hrApi.performanceOptionsV2(token,controller.signal));}if(canCalibrate){slots.calibration=tasks.length;tasks.push(hrApi.performanceCalibrationOptionsV2(token,controller.signal));slots.batches=tasks.length;tasks.push(hrApi.performanceCalibrationBatchesV2(token,controller.signal));}const result=await Promise.all(tasks);if(current!==generation.current)return;setCycles(result[0] as HrPerformanceCycleV2[]);const pageResult=result[1] as HrPerformanceReviewPage;if(!Array.isArray(pageResult.items)||![pageResult.total,pageResult.pending,pageResult.confirmed].every(n=>Number.isInteger(n)&&n>=0)||pageResult.pending+pageResult.confirmed!==pageResult.total||pageResult.items.length>30)throw new Error("绩效评价分页结果无效");setReviews(pageResult.items);setReviewCounts({total:pageResult.total,pending:pageResult.pending,confirmed:pageResult.confirmed});if(slots.options!==undefined)setOptions(result[slots.options] as Options);if(slots.calibration!==undefined)setCalibrationUsers((result[slots.calibration] as {users:Array<{id:string;displayName:string}>}).users);if(slots.batches!==undefined)setBatches(result[slots.batches] as Batch[]);setState("ready");}catch(e){if(current!==generation.current||controller.signal.aborted)return;const text=hrLoadErrorMessage(e,"加载绩效工作台失败");setLoadError(text);setState(text.includes("权限")?"forbidden":"error");}},[canCalibrate,manage,canRead,reviewPage,cycleFilter,statusFilter]);
 useEffect(()=>{void load();return()=>{generation.current++;request.current?.abort();};},[load]);
 const pending=reviewCounts.pending,activeBatchByCycle=useMemo(()=>new Map(batches.filter(x=>x.status==="active"&&x.canAct).map(x=>[x.cycleId,x])),[batches]);
 const run=async(action:()=>Promise<unknown>,success:string)=>{if(writeLock.current||!alive.current)return;writeLock.current=true;setBusy(true);setFormError("");setMessage("");try{await action();if(!alive.current)return;setMode(null);setEditor(null);setMessage(success);await load();}catch(e){if(alive.current)setFormError(hrLoadErrorMessage(e,"操作失败"));}finally{writeLock.current=false;if(alive.current)setBusy(false);}};
 const scores=(review:HrPerformanceReviewV2,f:FormData)=>Object.fromEntries(review.dimensions.map(d=>[d.code,Number(f.get(`score-${d.code}`))]));
 const comments=(review:HrPerformanceReviewV2,f:FormData)=>Object.fromEntries(review.dimensions.map(d=>[d.code,String(f.get(`comment-${d.code}`)??"")]).filter(([,v])=>v));
 const submitEditor=async(f:FormData)=>{if(!editor||writeLock.current||!alive.current)return;
 if(editor.kind!=="appeal"&&(editor.kind!=="resolve"||String(f.get("decision"))==="upheld")){for(const d of editor.review.dimensions){const raw=String(f.get(`score-${d.code}`)??"").trim(),value=Number(raw);if(!/^-?\d+(?:\.\d{1,2})?$/.test(raw)||!Number.isFinite(value)||value<Number(d.scoreMin)||value>Number(d.scoreMax)){setFormError(`${d.name}请填写${d.scoreMin}至${d.scoreMax}之间的分数，最多两位小数。`);return;}}}
 const token=getAccessToken(),review=editor.review;if(editor.kind==="self")return run(()=>hrApi.submitPerformanceSelfReviewV2(review.id,{dimensionScores:scores(review,f),dimensionComments:comments(review,f)},token),"自评已提交");if(editor.kind==="manager")return run(()=>hrApi.submitPerformanceManagerReviewV2(review.id,{dimensionScores:scores(review,f),dimensionComments:comments(review,f)},token),"主管评价已提交");if(editor.kind==="calibrate"){const batch=activeBatchByCycle.get(review.cycleId);if(!batch){setFormError("请先为本周期创建校准会");return;}return run(()=>hrApi.addPerformanceCalibrationEntryV2(batch.id,{cycleEmployeeId:review.id,dimensionScores:scores(review,f),reason:String(f.get("reason"))},token),"校准调整已记录");}if(editor.kind==="appeal")return run(()=>hrApi.appealPerformanceReviewV2(review.id,String(f.get("reason")),token),"申诉已提交");const decision=String(f.get("decision")) as "upheld"|"rejected";return run(()=>hrApi.resolvePerformanceAppealV2(review.appeal!.id,{decision,reason:String(f.get("reason")),...(decision==="upheld"?{dimensionScores:scores(review,f)}:{})},token),"申诉处理已完成");};

 const createCycle=async(f:FormData)=>run(()=>hrApi.createPerformanceCycleV2({cycleCode:String(f.get("code")),cycleName:String(f.get("name")),startDate:String(f.get("startDate")),endDate:String(f.get("endDate")),templateVersionId:String(f.get("templateVersionId")),applicableOrgIds:f.getAll("orgIds").map(String)},getAccessToken()),"绩效周期已创建");
 const createBatch=async(f:FormData)=>run(()=>hrApi.createPerformanceCalibrationBatchV2({cycleId:String(f.get("cycleId")),batchName:String(f.get("batchName")),meetingAt:String(f.get("meetingAt")),participantUserIds:f.getAll("participantUserIds").map(String)},getAccessToken()),"校准会已创建");
 const changeReviewQuery=(next:{page?:number;cycleId?:string;status?:string})=>{if(writeLock.current)return;generation.current++;request.current?.abort();setReviews([]);setEvidenceReview(null);setReviewCounts({total:0,pending:0,confirmed:0});setEditor(null);setFormError("");setState("loading");setReviewPage(next.page??1);if(next.cycleId!==undefined)setCycleFilter(next.cycleId);if(next.status!==undefined)setStatusFilter(next.status);};
 const open=(kind:NonNullable<Editor>["kind"],review:HrPerformanceReviewV2)=>{if(writeLock.current)return;setMode(null);setDecision("rejected");setEditor({kind,review});setFormError("");};

 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_PERFORMANCE_PAGE}><main className={`content ds-page ${styles.page} ${templateStyles.reviewWorkbench}`}>
  <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">绩效管理</span><h1>绩效工作台</h1><p>处理评价待办、校准与结果签收。</p></div><div className={styles.heroActions}>{canTemplateRead?<a className="ds-button" href="#performance-templates">评价模板</a>:null}{manage?<button disabled={busy} className="ds-button" type="button" onClick={()=>{setEditor(null);setMode(mode==="cycle"?null:"cycle");}}> 新建周期</button>:null}{canCalibrate?<button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>{setEditor(null);setMode(mode==="batch"?null:"batch");}}> 创建校准会</button>:null}</div></section>
  {canRead?<section className="ds-kpi-grid"><article className="ds-kpi-card"><span>可见周期</span><strong>{cycles.length}</strong><small>当前角色范围</small></article><article className="ds-kpi-card"><span>待办评价</span><strong>{pending}</strong><small>当前筛选范围 · 需要继续办理</small></article><article className="ds-kpi-card"><span>已确认</span><strong>{reviewCounts.confirmed}</strong><small>当前筛选范围 · 结果已封存</small></article></section>:null}

  {mode==="cycle"?<form onSubmit={event=>{event.preventDefault();void createCycle(new FormData(event.currentTarget));}} className={`ds-panel ${styles.formGrid}`}><h2>新建绩效周期</h2><label className="form-field"><span>周期编码</span><input disabled={busy} name="code" required/></label><label className="form-field"><span>周期名称</span><input disabled={busy} name="name" required/></label><label className="form-field"><span>开始日期</span><input disabled={busy} name="startDate" type="date" required/></label><label className="form-field"><span>结束日期</span><input disabled={busy} name="endDate" type="date" required/></label><label className="form-field"><span>评价模板</span><select disabled={busy} name="templateVersionId" required><option value="">请选择</option>{options.templates.map(x=><option value={x.id} key={x.id}>{x.templateName} · {x.versionName}</option>)}</select></label><fieldset className={styles.formGrid}><legend>适用组织</legend>{options.orgs.map(x=><label key={x.id}><input disabled={busy} type="checkbox" name="orgIds" value={x.id}/> {x.orgName}</label>)}</fieldset><div className={styles.formActions}><button disabled={busy} className="ds-button ds-button-primary">保存周期</button><button disabled={busy} type="button" className="ds-button" onClick={()=>setMode(null)}>取消</button></div></form>:null}
  {mode==="batch"?<form onSubmit={event=>{event.preventDefault();void createBatch(new FormData(event.currentTarget));}} className={`ds-panel ${styles.formGrid}`}><h2>创建校准会</h2><label className="form-field"><span>绩效周期</span><select disabled={busy} name="cycleId" required><option value="">请选择</option>{cycles.filter(x=>x.status==="calibration"&&!activeBatchByCycle.has(x.id)).map(x=><option key={x.id} value={x.id}>{x.cycleName}</option>)}</select></label><label className="form-field"><span>会议名称</span><input disabled={busy} name="batchName" required maxLength={120}/></label><label className="form-field"><span>会议时间</span><input disabled={busy} name="meetingAt" type="datetime-local" required/></label><fieldset className={styles.formGrid}><legend>参会人员</legend>{calibrationUsers.map(x=><label key={x.id}><input disabled={busy} type="checkbox" name="participantUserIds" value={x.id}/> {x.displayName}</label>)}</fieldset><div className={styles.formActions}><button disabled={busy} className="ds-button ds-button-primary">创建校准会</button><button disabled={busy} type="button" className="ds-button" onClick={()=>setMode(null)}>取消</button></div></form>:null}
  {message?<p className="status-pill status-success" role="status">{message}</p>:null}{formError&&!editor?<p className="form-error" role="alert">{formError}</p>:null}
  {canRead?<section className="ds-panel" aria-label="评价筛选"><div className={styles.filterBar}><label className="form-field"><span>评价周期</span><select disabled={busy} value={cycleFilter} onChange={e=>changeReviewQuery({cycleId:e.target.value})}><option value="">全部周期</option>{cycles.map(c=><option value={c.id} key={c.id}>{c.cycleName}</option>)}</select></label><label className="form-field"><span>评价状态</span><select disabled={busy} value={statusFilter} onChange={e=>changeReviewQuery({status:e.target.value})}><option value="">全部状态</option>{Object.entries(labels).filter(([key])=>key!=="planning").map(([key,label])=><option value={key} key={key}>{label}</option>)}</select></label></div></section>:null}
  {state==="loading"?<section className="ds-panel" aria-busy="true">正在加载绩效数据…</section>:state==="forbidden"?<section className="ds-panel"><h2>暂无访问权限</h2><p role="alert">{loadError}</p></section>:state==="error"?<section className="ds-panel"><p role="alert">{loadError}{message?"；操作已成功，请重新加载查看，勿重复提交。":""}</p><button disabled={busy} className="ds-button" type="button" onClick={()=>void load()}>重新加载</button></section>:<>
  {canRead?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">我的工作</span><h2>评价与结果</h2></div></div><div className={`ds-mobile-record-list ${templateStyles.records}`}>{reviews.length?reviews.map(review=><article className="ds-mobile-record" key={review.id}><div><strong>{review.employee.name??review.employee.code??"员工"}</strong><span>{review.cycleName} · {labels[review.status]??review.status}</span>{review.result?<small>{review.result.levelName} · {review.result.score} 分</small>:null}</div><div className={styles.formActions}><button disabled={busy} className="ds-button" type="button" onClick={()=>{if(writeLock.current)return;setEvidenceReview(review);}}>查看奖惩依据</button>{review.actions.selfReview?<button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>open("self",review)}>填写自评</button>:null}{review.actions.managerReview?<button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>open("manager",review)}>主管评价</button>:null}{canCalibrate&&review.status==="calibration"&&activeBatchByCycle.has(review.cycleId)?<button disabled={busy} className="ds-button" type="button" onClick={()=>open("calibrate",review)}>记录校准</button>:null}{review.actions.acknowledge?<button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>void run(()=>hrApi.acknowledgePerformanceReviewV2(review.id,getAccessToken()),"绩效结果已签收")}>签收</button>:null}{review.actions.appeal?<button disabled={busy} className="ds-button" type="button" onClick={()=>open("appeal",review)}>申诉</button>:null}{review.actions.resolveAppeal&&review.appeal?<button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>open("resolve",review)}>处理申诉</button>:null}</div></article>):<p className={styles.emptyState}>当前没有可办理的绩效评价。</p>}</div></section>:null}
   {canRead?<nav className={styles.filterBar} aria-label="绩效评价分页"><button type="button" className="ds-button" disabled={busy||reviewPage<=1} onClick={()=>changeReviewQuery({page:reviewPage-1})}>上一页</button><span role="status">第 {reviewPage} / {Math.max(1,Math.ceil(reviewCounts.total/30))} 页 · 共 {reviewCounts.total} 条 · 本页 {reviews.length} 条</span><button type="button" className="ds-button" disabled={busy||reviewPage>=Math.max(1,Math.ceil(reviewCounts.total/30))} onClick={()=>changeReviewQuery({page:reviewPage+1})}>下一页</button><button type="button" className="ds-button" disabled={busy} onClick={()=>void load()}>刷新评价</button></nav>:null}
   {canCalibrate?batches.filter(x=>x.status==="active"&&x.canAct).map(batch=><section className="ds-panel" key={batch.id}><div className={styles.sectionHeading}><div><span className="ds-eyebrow">校准进行中</span><h2>{batch.batchName}</h2></div><button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>void run(()=>hrApi.completePerformanceCalibrationBatchV2(batch.id,getAccessToken()),"校准结果已提交员工签收")}>完成校准</button></div></section>):null}
   {manage?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">周期管理</span><h2>绩效周期</h2></div></div><div className={`ds-mobile-record-list ${templateStyles.records}`}>{cycles.length?cycles.map(x=><article className="ds-mobile-record" key={x.id}><div><strong>{x.cycleName}</strong><span>{x.startDate} 至 {x.endDate} · {labels[x.status]??x.status}</span></div>{x.status==="planning"?<button disabled={busy} className="ds-button ds-button-primary" type="button" onClick={()=>void run(()=>hrApi.publishPerformanceCycleV2(x.id,getAccessToken()),"绩效周期已发布")}>发布周期</button>:null}</article>):<p className={styles.emptyState}>当前没有绩效周期。</p>}</div></section>:null}

  </>}
  {canRead&&evidenceReview?<PerformanceRewardEvidence key={evidenceReview.id} id={evidenceReview.id} employeeName={evidenceReview.employee.name??evidenceReview.employee.code??"员工"} cycleName={evidenceReview.cycleName} onClose={()=>setEvidenceReview(null)}/>:null}
  {editor?<section className="ds-panel"><form key={`${editor.kind}:${editor.review.id}`} onSubmit={event=>{event.preventDefault();void submitEditor(new FormData(event.currentTarget));}} className={`${styles.formGrid} ${templateStyles.operationForm}`}><div className={styles.sectionHeading}><div><span className="ds-eyebrow">{editor.review.employee.name}</span><h2>{{self:"员工自评",manager:"主管评价",calibrate:"校准调整",appeal:"绩效申诉",resolve:"申诉处理"}[editor.kind]}</h2></div><button disabled={busy} className="ds-button" type="button" onClick={()=>setEditor(null)}>关闭</button></div>{editor.kind!=="appeal"&&(editor.kind!=="resolve"||decision==="upheld")?editor.review.dimensions.map(d=><div className={templateStyles.reviewDimension} key={d.code}><label className="form-field"><span>{d.name}（{Number(d.weight)*100}%）</span><input disabled={busy} name={`score-${d.code}`} type="number" min={d.scoreMin} max={d.scoreMax} step="0.01" onFocus={event=>event.target.select()} defaultValue={(editor.kind==="self"?editor.review.selfSubmission?.scores[d.code]:editor.kind==="manager"?editor.review.managerSubmission?.scores[d.code]:editor.review.calibration?.scores[d.code]??editor.review.managerSubmission?.scores[d.code]??editor.review.selfSubmission?.scores[d.code])??""} required/></label>{editor.kind!=="calibrate"&&editor.kind!=="resolve"?<label className="form-field"><span>评价说明</span><textarea disabled={busy} name={`comment-${d.code}`} maxLength={1000} defaultValue={(editor.kind==="self"?editor.review.selfSubmission:editor.review.managerSubmission)?.comments[d.code]??""}/></label>:null}</div>):null}{editor.kind==="resolve"?<label className="form-field"><span>处理决定</span><select disabled={busy} name="decision" value={decision} onChange={event=>setDecision(event.target.value as "rejected"|"upheld")} required><option value="rejected">维持原结果</option><option value="upheld">采纳并调整</option></select></label>:null}{["calibrate","appeal","resolve"].includes(editor.kind)?<label className="form-field"><span>{editor.kind==="appeal"?"申诉理由":"处理理由"}</span><textarea disabled={busy} name="reason" minLength={2} maxLength={2000} required/></label>:null}<div className={styles.formActions}><button disabled={busy} className="ds-button ds-button-primary">提交</button><button disabled={busy} className="ds-button" type="button" onClick={()=>setEditor(null)}>取消</button></div>{formError?<p className="form-error" role="alert">{formError}</p>:null}</form></section>:null}
  {canTemplateRead?<PerformanceTemplates/>:null}
  <HrPerformanceLegacyPanel/>
  <HrPerformanceLegacyRelationsPanel/>
  <HrPerformanceLegacyPersonSummaryPanel/>
  <HrPerformanceLegacyAssessmentMasterPanel/>
  <HrPerformanceLegacyAssessmentValuePanel/>
  <HrPerformanceLegacyAssessmentValueOfPersonPanel/>
  <HrPerformanceLegacyWebAssQueryPanel/>
 </main></PermissionGuard>;
}
