"use client";
import type { HrEmployeeProfile } from "../../../../lib/hr-api";
import styles from "../../hr-workbench.module.css";
export type ProfileSaveBody={expectedVersion:number}&Record<string,unknown>;
const ProfileField=({name,label,value,type="text",maxLength,min,max,step}:{name:string;label:string;value?:string|null;type?:string;maxLength?:number;min?:number;max?:number;step?:string})=><label className="form-field"><span>{label}</span><input name={name} type={type} defaultValue={value??""} maxLength={maxLength} min={min} max={max} step={step}/></label>;
export function YuzhouBasicProfileFields({profile}:{profile:HrEmployeeProfile|null}){return <div className={styles.profileFields} key={profile?.id??"new-profile"}>
 <fieldset className={styles.profileGroup}><legend>身份与个人信息</legend><ProfileField name="englishName" label="英文姓名" value={profile?.englishName} maxLength={100}/><label className="form-field"><span>性别</span><select name="gender" defaultValue={profile?.gender??""}><option value="">未登记</option>{profile?.gender&&!["男","女","其他"].includes(profile.gender)?<option value={profile.gender}>{profile.gender}</option>:null}<option value="男">男</option><option value="女">女</option><option value="其他">其他</option></select></label><ProfileField name="dateOfBirth" label="出生日期" value={profile?.dateOfBirth} type="date"/><ProfileField name="ethnicity" label="民族" value={profile?.ethnicity} maxLength={64}/><ProfileField name="nativePlace" label="籍贯" value={profile?.nativePlace} maxLength={128}/><ProfileField name="politicalStatus" label="政治面貌" value={profile?.politicalStatus} maxLength={64}/><ProfileField name="partyJoinDate" label="参加党派时间" value={profile?.partyJoinDate} type="date"/><ProfileField name="heightCm" label="身高（厘米）" value={profile?.heightCm} type="number" min={30} max={300} step="0.01"/><ProfileField name="weightKg" label="体重（公斤）" value={profile?.weightKg} type="number" min={1} max={500} step="0.01"/><ProfileField name="maritalStatus" label="婚姻状况" value={profile?.maritalStatus} maxLength={32}/><ProfileField name="healthStatus" label="健康状况" value={profile?.healthStatus} maxLength={64}/><ProfileField name="householdRegistration" label="户口所在地" value={profile?.householdRegistration} maxLength={256}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>教育与语言</legend><ProfileField name="highestEducation" label="最高学历" value={profile?.highestEducation} maxLength={64}/><ProfileField name="major" label="主修专业" value={profile?.major} maxLength={128}/><ProfileField name="degree" label="学位" value={profile?.degree} maxLength={64}/><ProfileField name="foreignLanguage" label="外语" value={profile?.foreignLanguage} maxLength={64}/><ProfileField name="languageLevel" label="外语水平" value={profile?.languageLevel} maxLength={64}/><ProfileField name="graduationDate" label="毕业日期" value={profile?.graduationDate} type="date"/><ProfileField name="graduationSchool" label="毕业学校" value={profile?.graduationSchool} maxLength={160}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>职务与专业资格</legend><ProfileField name="jobTitle" label="职务" value={profile?.jobTitle} maxLength={100}/><ProfileField name="jobGrade" label="职务级别" value={profile?.jobGrade} maxLength={64}/><ProfileField name="employeeCategory" label="员工类别" value={profile?.employeeCategory} maxLength={64}/><ProfileField name="technicalTitle" label="技术职称" value={profile?.technicalTitle} maxLength={100}/><ProfileField name="technicalGrade" label="职称级别" value={profile?.technicalGrade} maxLength={64}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>证件与联系方式</legend><label className="form-field"><span>证件类型</span><select name="idType" defaultValue={profile?.idType??""}><option value="">未登记</option><option value="resident_id">居民身份证</option><option value="passport">护照</option><option value="other">其他</option></select></label><ProfileField name="idNumber" label="证件号（加密保存）" value={profile?.idNumber} maxLength={64}/><ProfileField name="personalMobile" label="个人手机" value={profile?.personalMobile} maxLength={32}/><ProfileField name="homePhone" label="家庭电话" value={profile?.homePhone} maxLength={32}/><ProfileField name="personalEmail" label="个人邮箱" value={profile?.personalEmail} type="email" maxLength={128}/><ProfileField name="address" label="联系地址" value={profile?.address} maxLength={500}/><ProfileField name="emergencyContactName" label="紧急联系人" value={profile?.emergencyContactName} maxLength={100}/><ProfileField name="emergencyContactMobile" label="紧急联系电话" value={profile?.emergencyContactMobile} maxLength={32}/></fieldset>
 <fieldset className={styles.profileGroup}><legend>档案备注</legend><label className="form-field"><span>档案备注</span><textarea name="remark" defaultValue={profile?.remark??""} maxLength={500} rows={3}/></label></fieldset>
 </div>}

export function buildProfileSaveBody(form:FormData,expectedVersion:number):ProfileSaveBody{const value=(name:string)=>String(form.get(name)??"")||undefined,numberValue=(name:string)=>{const raw=value(name);return raw===undefined?undefined:Number(raw)};const body:ProfileSaveBody={expectedVersion,idType:value("idType"),idNumber:String(form.get("idNumber")??""),englishName:value("englishName"),gender:value("gender"),dateOfBirth:value("dateOfBirth"),ethnicity:value("ethnicity"),nativePlace:value("nativePlace"),politicalStatus:value("politicalStatus"),partyJoinDate:value("partyJoinDate"),heightCm:numberValue("heightCm"),weightKg:numberValue("weightKg"),maritalStatus:value("maritalStatus"),healthStatus:value("healthStatus"),householdRegistration:value("householdRegistration"),highestEducation:value("highestEducation"),major:value("major"),degree:value("degree"),foreignLanguage:value("foreignLanguage"),languageLevel:value("languageLevel"),graduationDate:value("graduationDate"),graduationSchool:value("graduationSchool"),homePhone:value("homePhone"),jobTitle:value("jobTitle"),jobGrade:value("jobGrade"),employeeCategory:value("employeeCategory"),technicalTitle:value("technicalTitle"),technicalGrade:value("technicalGrade"),personalMobile:value("personalMobile"),personalEmail:value("personalEmail"),address:value("address"),emergencyContactName:value("emergencyContactName"),emergencyContactMobile:value("emergencyContactMobile"),remark:value("remark")};return body;}
