ALTER TABLE sys_code_rule
  DROP CONSTRAINT IF EXISTS ck_sys_code_rule_entity_type;

ALTER TABLE sys_code_rule
  ADD CONSTRAINT ck_sys_code_rule_entity_type CHECK (
    entity_type IN (
      'park',
      'building',
      'floor',
      'room',
      'unit',
      'zone',
      'asset',
      'device',
      'camera',
      'iot_point',
      'iot_gateway',
      'iot_device',
      'iot_metric',
      'iot_alert',
      'iot_alert_rule',
      'robot',
      'cleaning_robot',
      'inspection_robot',
      'workorder',
      'workorder_log',
      'safety_inspect_point',
      'safety_inspect_template',
      'safety_inspect_plan',
      'safety_inspect_task',
      'safety_hazard',
      'safety_hazard_log',
      'safety_emergency_contact',
      'safety_emergency_plan',
      'safety_emergency_event',
      'safety_emergency_log',
      'safety_work_permit',
      'safety_work_permit_log',
      'leasing_lead',
      'contract',
      'contract_change',
      'renewal_contract',
      'checkout',
      'refund',
      'bill',
      'receivable',
      'payment',
      'invoice',
      'waiver'
    )
  );
