WITH field_policies(entity, field_key, field_name, policy_type, mask_rule, remark) AS (
  VALUES
    ('emergency_contact', 'email', '应急联系人邮箱', 'masked', 'email', 'S5-B emergency contact email field policy'),
    ('emergencyContact', 'email', '应急联系人邮箱', 'masked', 'email', 'S5-B emergencyContact email field policy'),
    ('biz_safety_emergency_contact', 'email', '应急联系人邮箱', 'masked', 'email', 'S5-B biz emergency contact email field policy'),
    ('emergency_event', 'gps_lng', '应急事件经度', 'masked', 'custom', 'S5-B emergency event gps lng field policy'),
    ('emergency_event', 'gps_lat', '应急事件纬度', 'masked', 'custom', 'S5-B emergency event gps lat field policy'),
    ('emergency_event', 'conclusion', '应急事件复盘结论', 'visible', NULL, 'S5-B emergency event conclusion field policy'),
    ('emergency_event', 'review_file_id', '应急事件复盘附件', 'visible', NULL, 'S5-B emergency event review file field policy'),
    ('emergencyEvent', 'gpsLng', '应急事件经度', 'masked', 'custom', 'S5-B emergencyEvent gps lng field policy'),
    ('emergencyEvent', 'gpsLat', '应急事件纬度', 'masked', 'custom', 'S5-B emergencyEvent gps lat field policy'),
    ('emergencyEvent', 'conclusion', '应急事件复盘结论', 'visible', NULL, 'S5-B emergencyEvent conclusion field policy'),
    ('emergencyEvent', 'reviewFileId', '应急事件复盘附件', 'visible', NULL, 'S5-B emergencyEvent review file field policy'),
    ('biz_safety_emergency_event', 'gps_lng', '应急事件经度', 'masked', 'custom', 'S5-B biz emergency event gps lng field policy'),
    ('biz_safety_emergency_event', 'gps_lat', '应急事件纬度', 'masked', 'custom', 'S5-B biz emergency event gps lat field policy'),
    ('biz_safety_emergency_event', 'conclusion', '应急事件复盘结论', 'visible', NULL, 'S5-B biz emergency event conclusion field policy'),
    ('biz_safety_emergency_event', 'review_file_id', '应急事件复盘附件', 'visible', NULL, 'S5-B biz emergency event review file field policy'),
    ('work_permit', 'start_check_photo_file_ids', '开工检查照片', 'visible', NULL, 'S5-B work permit start photo field policy'),
    ('work_permit', 'end_check_photo_file_ids', '完工检查照片', 'visible', NULL, 'S5-B work permit end photo field policy'),
    ('workPermit', 'startCheckPhotoFileIds', '开工检查照片', 'visible', NULL, 'S5-B workPermit start photo field policy'),
    ('workPermit', 'endCheckPhotoFileIds', '完工检查照片', 'visible', NULL, 'S5-B workPermit end photo field policy'),
    ('biz_safety_work_permit', 'start_check_photo_file_ids', '开工检查照片', 'visible', NULL, 'S5-B biz work permit start photo field policy'),
    ('biz_safety_work_permit', 'end_check_photo_file_ids', '完工检查照片', 'visible', NULL, 'S5-B biz work permit end photo field policy'),
    ('work_permit_check', 'violation_desc', '作业许可巡查违规说明', 'visible', NULL, 'S5-B work permit check violation field policy'),
    ('work_permit_check', 'photo_file_ids', '作业许可巡查照片', 'visible', NULL, 'S5-B work permit check photo field policy'),
    ('workPermitCheck', 'violationDesc', '作业许可巡查违规说明', 'visible', NULL, 'S5-B workPermitCheck violation field policy'),
    ('workPermitCheck', 'photoFileIds', '作业许可巡查照片', 'visible', NULL, 'S5-B workPermitCheck photo field policy'),
    ('biz_safety_work_permit_check', 'violation_desc', '作业许可巡查违规说明', 'visible', NULL, 'S5-B biz work permit check violation field policy'),
    ('biz_safety_work_permit_check', 'photo_file_ids', '作业许可巡查照片', 'visible', NULL, 'S5-B biz work permit check photo field policy')
)
INSERT INTO sys_field_policy (
  id,
  tenant_id,
  park_id,
  module,
  entity,
  field_key,
  field_name,
  policy_type,
  mask_rule,
  status,
  create_time,
  update_time,
  is_deleted,
  version,
  remark
)
SELECT
  uuid_generate_v4(),
  '10000001',
  '20000001',
  'safety',
  field_policies.entity,
  field_policies.field_key,
  field_policies.field_name,
  field_policies.policy_type,
  field_policies.mask_rule,
  'enabled',
  now(),
  now(),
  false,
  1,
  field_policies.remark
FROM field_policies
ON CONFLICT (tenant_id, module, entity, field_key) WHERE is_deleted = false DO UPDATE SET
  field_name = EXCLUDED.field_name,
  policy_type = EXCLUDED.policy_type,
  mask_rule = EXCLUDED.mask_rule,
  status = EXCLUDED.status,
  update_time = now(),
  remark = EXCLUDED.remark;
