BEGIN;
CREATE TABLE IF NOT EXISTS hr_position (
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,org_id uuid NOT NULL REFERENCES sys_org(id),position_code varchar(64) NOT NULL,position_name varchar(100) NOT NULL,job_family varchar(64),job_level varchar(32),headcount_limit integer,status varchar(32) NOT NULL DEFAULT 'enabled',create_by uuid,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,remark varchar(500));
CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_position_scope_code ON hr_position(tenant_id,park_id,position_code) WHERE is_deleted=false;
CREATE INDEX IF NOT EXISTS idx_hr_position_org ON hr_position(tenant_id,park_id,org_id) WHERE is_deleted=false;
CREATE TABLE IF NOT EXISTS hr_employee (
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,employee_code varchar(64) NOT NULL,full_name varchar(100) NOT NULL,user_id uuid REFERENCES sys_user(id),primary_org_id uuid REFERENCES sys_org(id),position_id uuid REFERENCES hr_position(id),manager_employee_id uuid,employment_type varchar(32) NOT NULL DEFAULT 'full_time',employment_status varchar(32) NOT NULL DEFAULT 'preboarding',hire_date date,probation_end_date date,departure_date date,work_location varchar(128),work_mobile varchar(32),work_email varchar(128),create_by uuid,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,remark varchar(500),CONSTRAINT fk_hr_employee_manager FOREIGN KEY(manager_employee_id) REFERENCES hr_employee(id),CONSTRAINT ck_hr_employee_status CHECK(employment_status IN ('preboarding','probation','active','suspended','departed')),CONSTRAINT ck_hr_employee_type CHECK(employment_type IN ('full_time','part_time','intern','contractor')),CONSTRAINT ck_hr_employee_dates CHECK(departure_date IS NULL OR hire_date IS NULL OR departure_date>=hire_date));
CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_employee_scope_code ON hr_employee(tenant_id,park_id,employee_code) WHERE is_deleted=false;
CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_employee_scope_user ON hr_employee(tenant_id,park_id,user_id) WHERE is_deleted=false AND user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_hr_employee_org ON hr_employee(tenant_id,park_id,primary_org_id) WHERE is_deleted=false;
CREATE INDEX IF NOT EXISTS idx_hr_employee_manager ON hr_employee(tenant_id,park_id,manager_employee_id) WHERE is_deleted=false;
CREATE TABLE IF NOT EXISTS hr_employee_profile (
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,employee_id uuid NOT NULL REFERENCES hr_employee(id),id_type varchar(32),id_number_masked varchar(64),personal_mobile varchar(32),personal_email varchar(128),address varchar(500),emergency_contact_name varchar(100),emergency_contact_mobile varchar(32),create_by uuid,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,remark varchar(500));
CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_employee_profile_employee ON hr_employee_profile(tenant_id,park_id,employee_id) WHERE is_deleted=false;
CREATE TABLE IF NOT EXISTS hr_employment_event (
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,employee_id uuid NOT NULL REFERENCES hr_employee(id),event_type varchar(32) NOT NULL,effective_date date NOT NULL,before_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,after_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,reason varchar(500),status varchar(32) NOT NULL DEFAULT 'effective',create_by uuid,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,remark varchar(500));
CREATE INDEX IF NOT EXISTS idx_hr_employment_event_employee ON hr_employment_event(tenant_id,park_id,employee_id,effective_date DESC) WHERE is_deleted=false;
CREATE TABLE IF NOT EXISTS hr_employee_document (
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,employee_id uuid NOT NULL REFERENCES hr_employee(id),document_type varchar(64) NOT NULL,file_id uuid NOT NULL REFERENCES sys_file(id),document_name varchar(255) NOT NULL,valid_from date,valid_to date,status varchar(32) NOT NULL DEFAULT 'active',create_by uuid,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,remark varchar(500),CONSTRAINT ck_hr_employee_document_dates CHECK(valid_to IS NULL OR valid_from IS NULL OR valid_to>=valid_from));
CREATE INDEX IF NOT EXISTS idx_hr_employee_document_employee ON hr_employee_document(tenant_id,park_id,employee_id) WHERE is_deleted=false;
COMMIT;
