BEGIN;
CREATE UNIQUE INDEX IF NOT EXISTS uq_hr_employee_scope_id ON hr_employee(tenant_id,park_id,id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sys_user_scope_id ON sys_user(tenant_id,park_id,id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_sys_file_scope_id ON sys_file(tenant_id,park_id,id);

CREATE TABLE hr_reward_discipline_category(
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,category_code varchar(64) NOT NULL,current_version_no integer NOT NULL DEFAULT 1,status varchar(16) NOT NULL DEFAULT 'enabled',create_by uuid NOT NULL,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid NOT NULL,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,
 CONSTRAINT ck_hr_reward_category_version CHECK(current_version_no>0),CONSTRAINT ck_hr_reward_category_status CHECK(status IN('enabled','disabled')),CONSTRAINT fk_hr_reward_category_creator FOREIGN KEY(tenant_id,park_id,create_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_category_updater FOREIGN KEY(tenant_id,park_id,update_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_category_scope_id UNIQUE(tenant_id,park_id,id));
CREATE UNIQUE INDEX uq_hr_reward_category_code ON hr_reward_discipline_category(tenant_id,park_id,category_code) WHERE is_deleted=false;
CREATE INDEX ix_hr_reward_category_creator ON hr_reward_discipline_category(tenant_id,park_id,create_by);CREATE INDEX ix_hr_reward_category_updater ON hr_reward_discipline_category(tenant_id,park_id,update_by);
CREATE TABLE hr_reward_discipline_category_version(
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,category_id uuid NOT NULL,version_no integer NOT NULL,kind varchar(16) NOT NULL,name varchar(120) NOT NULL,impact_level varchar(16) NOT NULL,description varchar(1000),create_by uuid NOT NULL,create_time timestamptz NOT NULL DEFAULT now(),
 CONSTRAINT ck_hr_reward_category_kind CHECK(kind IN('reward','discipline')),CONSTRAINT ck_hr_reward_category_impact CHECK(impact_level IN('minor','normal','major','critical')),CONSTRAINT fk_hr_reward_category_version_category FOREIGN KEY(tenant_id,park_id,category_id) REFERENCES hr_reward_discipline_category(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_category_version_creator FOREIGN KEY(tenant_id,park_id,create_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_category_version_scope_id UNIQUE(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_category_version_identity UNIQUE(tenant_id,park_id,category_id,id),CONSTRAINT uq_hr_reward_category_version_no UNIQUE(tenant_id,park_id,category_id,version_no));
CREATE INDEX ix_hr_reward_category_version_category ON hr_reward_discipline_category_version(tenant_id,park_id,category_id);CREATE INDEX ix_hr_reward_category_version_creator ON hr_reward_discipline_category_version(tenant_id,park_id,create_by);

CREATE TABLE hr_reward_discipline_case(
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,case_code varchar(64) NOT NULL,employee_id uuid NOT NULL,category_id uuid NOT NULL,category_version_id uuid NOT NULL,status varchar(16) NOT NULL DEFAULT 'draft',occurred_on date NOT NULL,fact_summary varchar(300) NOT NULL,detailed_reason varchar(3000),impact_level varchar(16) NOT NULL,amount_suggestion numeric(20,4),currency varchar(3),evidence_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,category_snapshot jsonb,submitted_at timestamptz,approved_at timestamptz,returned_at timestamptz,withdrawn_at timestamptz,reviewer_user_id uuid,create_by uuid NOT NULL,create_time timestamptz NOT NULL DEFAULT now(),update_by uuid NOT NULL,update_time timestamptz NOT NULL DEFAULT now(),is_deleted boolean NOT NULL DEFAULT false,version integer NOT NULL DEFAULT 1,
 CONSTRAINT ck_hr_reward_case_status CHECK(status IN('draft','submitted','approved','returned','withdrawn')),CONSTRAINT ck_hr_reward_case_impact CHECK(impact_level IN('minor','normal','major','critical')),CONSTRAINT ck_hr_reward_case_amount CHECK(amount_suggestion IS NULL OR amount_suggestion>=0),CONSTRAINT ck_hr_reward_case_currency CHECK((amount_suggestion IS NULL AND currency IS NULL) OR (amount_suggestion IS NOT NULL AND currency~'^[A-Z]{3}$')),CONSTRAINT ck_hr_reward_case_snapshot CHECK((status='draft' AND category_snapshot IS NULL AND submitted_at IS NULL) OR (status<>'draft' AND category_snapshot IS NOT NULL AND submitted_at IS NOT NULL)),
 CONSTRAINT fk_hr_reward_case_employee FOREIGN KEY(tenant_id,park_id,employee_id) REFERENCES hr_employee(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_case_category FOREIGN KEY(tenant_id,park_id,category_id) REFERENCES hr_reward_discipline_category(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_case_category_version FOREIGN KEY(tenant_id,park_id,category_id,category_version_id) REFERENCES hr_reward_discipline_category_version(tenant_id,park_id,category_id,id),CONSTRAINT fk_hr_reward_case_reviewer FOREIGN KEY(tenant_id,park_id,reviewer_user_id) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_case_creator FOREIGN KEY(tenant_id,park_id,create_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_case_updater FOREIGN KEY(tenant_id,park_id,update_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_case_scope_id UNIQUE(tenant_id,park_id,id));
CREATE UNIQUE INDEX uq_hr_reward_case_code ON hr_reward_discipline_case(tenant_id,park_id,case_code) WHERE is_deleted=false;CREATE INDEX ix_hr_reward_case_employee ON hr_reward_discipline_case(tenant_id,park_id,employee_id);CREATE INDEX ix_hr_reward_case_category ON hr_reward_discipline_case(tenant_id,park_id,category_id,category_version_id);CREATE INDEX ix_hr_reward_case_reviewer ON hr_reward_discipline_case(tenant_id,park_id,reviewer_user_id);CREATE INDEX ix_hr_reward_case_creator ON hr_reward_discipline_case(tenant_id,park_id,create_by);CREATE INDEX ix_hr_reward_case_updater ON hr_reward_discipline_case(tenant_id,park_id,update_by);CREATE INDEX ix_hr_reward_case_status ON hr_reward_discipline_case(tenant_id,park_id,status,occurred_on) WHERE is_deleted=false;

CREATE TABLE hr_reward_discipline_action(
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,case_id uuid NOT NULL,action varchar(24) NOT NULL,from_status varchar(16),to_status varchar(16),note varchar(1000),actor_user_id uuid NOT NULL,create_time timestamptz NOT NULL DEFAULT now(),CONSTRAINT ck_hr_reward_action_type CHECK(action IN('submit','approve','return','resubmit','withdraw','correct','appeal')),CONSTRAINT fk_hr_reward_action_case FOREIGN KEY(tenant_id,park_id,case_id) REFERENCES hr_reward_discipline_case(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_action_actor FOREIGN KEY(tenant_id,park_id,actor_user_id) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_action_scope_id UNIQUE(tenant_id,park_id,id));
CREATE INDEX ix_hr_reward_action_case ON hr_reward_discipline_action(tenant_id,park_id,case_id);CREATE INDEX ix_hr_reward_action_actor ON hr_reward_discipline_action(tenant_id,park_id,actor_user_id);
CREATE TABLE hr_reward_discipline_correction(
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,case_id uuid NOT NULL,sequence_no integer NOT NULL,correction_type varchar(16) NOT NULL,summary varchar(300) NOT NULL,reason varchar(1000) NOT NULL,create_by uuid NOT NULL,create_time timestamptz NOT NULL DEFAULT now(),CONSTRAINT ck_hr_reward_correction_seq CHECK(sequence_no>0),CONSTRAINT ck_hr_reward_correction_type CHECK(correction_type IN('correction','appeal')),CONSTRAINT fk_hr_reward_correction_case FOREIGN KEY(tenant_id,park_id,case_id) REFERENCES hr_reward_discipline_case(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_correction_creator FOREIGN KEY(tenant_id,park_id,create_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_correction_scope_id UNIQUE(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_correction_seq UNIQUE(tenant_id,park_id,case_id,sequence_no));
CREATE INDEX ix_hr_reward_correction_case ON hr_reward_discipline_correction(tenant_id,park_id,case_id);CREATE INDEX ix_hr_reward_correction_creator ON hr_reward_discipline_correction(tenant_id,park_id,create_by);
CREATE TABLE hr_reward_discipline_link(
 id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),tenant_id varchar(64) NOT NULL,park_id varchar(64) NOT NULL,case_id uuid NOT NULL,target_type varchar(32) NOT NULL,target_id uuid NOT NULL,target_version integer NOT NULL,status varchar(16) NOT NULL DEFAULT 'linked',create_by uuid NOT NULL,create_time timestamptz NOT NULL DEFAULT now(),CONSTRAINT ck_hr_reward_link_type CHECK(target_type IN('payroll_input','performance_reference')),CONSTRAINT ck_hr_reward_link_status CHECK(status IN('pending','linked','failed','void')),CONSTRAINT ck_hr_reward_link_version CHECK(target_version>0),CONSTRAINT fk_hr_reward_link_case FOREIGN KEY(tenant_id,park_id,case_id) REFERENCES hr_reward_discipline_case(tenant_id,park_id,id),CONSTRAINT fk_hr_reward_link_creator FOREIGN KEY(tenant_id,park_id,create_by) REFERENCES sys_user(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_link_scope_id UNIQUE(tenant_id,park_id,id),CONSTRAINT uq_hr_reward_link_target UNIQUE(tenant_id,park_id,case_id,target_type));
CREATE INDEX ix_hr_reward_link_case ON hr_reward_discipline_link(tenant_id,park_id,case_id);CREATE INDEX ix_hr_reward_link_creator ON hr_reward_discipline_link(tenant_id,park_id,create_by);CREATE INDEX ix_hr_reward_link_target ON hr_reward_discipline_link(tenant_id,park_id,target_type,target_id);

CREATE OR REPLACE FUNCTION fn_hr_reward_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION '% is append-only',TG_TABLE_NAME; END $$;
CREATE TRIGGER tr_hr_reward_category_version_immutable BEFORE UPDATE OR DELETE ON hr_reward_discipline_category_version FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_append_only();CREATE TRIGGER tr_hr_reward_action_immutable BEFORE UPDATE OR DELETE ON hr_reward_discipline_action FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_append_only();CREATE TRIGGER tr_hr_reward_correction_immutable BEFORE UPDATE OR DELETE ON hr_reward_discipline_correction FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_append_only();CREATE TRIGGER tr_hr_reward_link_immutable BEFORE UPDATE OR DELETE ON hr_reward_discipline_link FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_append_only();
CREATE OR REPLACE FUNCTION fn_hr_reward_category_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'reward category is immutable'; END IF;
 IF (NEW.tenant_id,NEW.park_id,NEW.category_code,NEW.create_by,NEW.create_time,NEW.is_deleted) IS DISTINCT FROM (OLD.tenant_id,OLD.park_id,OLD.category_code,OLD.create_by,OLD.create_time,OLD.is_deleted) THEN RAISE EXCEPTION 'reward category identity is immutable'; END IF;
 IF NEW.current_version_no IS DISTINCT FROM OLD.current_version_no THEN
  IF NEW.current_version_no<>OLD.current_version_no+1 OR NOT EXISTS(SELECT 1 FROM hr_reward_discipline_category_version v WHERE v.tenant_id=NEW.tenant_id AND v.park_id=NEW.park_id AND v.category_id=NEW.id AND v.version_no=NEW.current_version_no FOR SHARE) THEN RAISE EXCEPTION 'invalid reward category version pointer'; END IF;
 END IF;
 RETURN NEW; END $$;
CREATE TRIGGER tr_hr_reward_category_guard BEFORE UPDATE OR DELETE ON hr_reward_discipline_category FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_category_guard();
CREATE OR REPLACE FUNCTION fn_hr_reward_case_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'reward case is immutable'; END IF;
 IF (NEW.tenant_id,NEW.park_id,NEW.employee_id,NEW.category_id,NEW.category_version_id,NEW.create_by,NEW.create_time,NEW.is_deleted) IS DISTINCT FROM (OLD.tenant_id,OLD.park_id,OLD.employee_id,OLD.category_id,OLD.category_version_id,OLD.create_by,OLD.create_time,OLD.is_deleted) THEN RAISE EXCEPTION 'reward case ownership is immutable'; END IF;
 IF NEW.status IS DISTINCT FROM OLD.status AND NOT ((OLD.status='draft' AND NEW.status='submitted') OR (OLD.status='returned' AND NEW.status='submitted') OR (OLD.status='submitted' AND NEW.status IN('approved','returned','withdrawn'))) THEN RAISE EXCEPTION 'invalid reward case transition'; END IF;
 IF OLD.status='submitted' AND (NEW.occurred_on,NEW.fact_summary,NEW.detailed_reason,NEW.impact_level,NEW.amount_suggestion,NEW.currency,NEW.evidence_snapshot,NEW.category_snapshot) IS DISTINCT FROM (OLD.occurred_on,OLD.fact_summary,OLD.detailed_reason,OLD.impact_level,OLD.amount_suggestion,OLD.currency,OLD.evidence_snapshot,OLD.category_snapshot) THEN RAISE EXCEPTION 'submitted reward facts are immutable'; END IF;
 IF OLD.status IN('approved','withdrawn') AND NEW IS DISTINCT FROM OLD THEN RAISE EXCEPTION 'terminal reward case is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER tr_hr_reward_case_guard BEFORE UPDATE OR DELETE ON hr_reward_discipline_case FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_case_guard();
CREATE OR REPLACE FUNCTION fn_hr_reward_file_guard() RETURNS trigger LANGUAGE plpgsql AS $$ DECLARE file_id uuid; BEGIN FOR file_id IN SELECT jsonb_array_elements_text(NEW.evidence_snapshot)::uuid LOOP IF NOT EXISTS(SELECT 1 FROM sys_file f WHERE f.tenant_id=NEW.tenant_id AND f.park_id=NEW.park_id AND f.id=file_id AND f.biz_type='hr_reward_evidence' AND f.biz_id=NEW.id AND f.status=1 AND f.is_deleted=false FOR SHARE) THEN RAISE EXCEPTION 'reward evidence file owner mismatch'; END IF; END LOOP; RETURN NEW; END $$;
CREATE TRIGGER tr_hr_reward_file_owner BEFORE INSERT OR UPDATE OF evidence_snapshot ON hr_reward_discipline_case FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_file_guard();
CREATE OR REPLACE FUNCTION fn_hr_reward_file_inverse_guard() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF EXISTS(SELECT 1 FROM hr_reward_discipline_case c WHERE c.tenant_id=OLD.tenant_id AND c.park_id=OLD.park_id AND c.id=OLD.biz_id AND OLD.biz_type='hr_reward_evidence' AND c.evidence_snapshot ? OLD.id::text AND c.is_deleted=false FOR SHARE) THEN
  IF TG_OP='DELETE' OR (NEW.tenant_id,NEW.park_id,NEW.biz_type,NEW.biz_id,NEW.status,NEW.is_deleted) IS DISTINCT FROM (OLD.tenant_id,OLD.park_id,OLD.biz_type,OLD.biz_id,OLD.status,OLD.is_deleted) THEN RAISE EXCEPTION 'referenced reward evidence is immutable'; END IF;
 END IF;
 RETURN COALESCE(NEW,OLD); END $$;
CREATE TRIGGER tr_hr_reward_file_inverse_guard BEFORE UPDATE OF tenant_id,park_id,biz_type,biz_id,status,is_deleted OR DELETE ON sys_file FOR EACH ROW EXECUTE FUNCTION fn_hr_reward_file_inverse_guard();
COMMIT;
