import { BadRequestException, ConflictException, Injectable, NotFoundException } from "@nestjs/common";
import { createHash, randomUUID } from "node:crypto";
import { DataSource, type EntityManager } from "typeorm";
import type { TenantParkScope } from "@jinhu/shared";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import type { AllocateApartmentDto, ArchiveDocumentDto, CreateApartmentApplicationDto, CreateApartmentRoomDto, CreateTemplateDto, DecisionDto, HandoverDto, ListApartmentDto, UpdateApartmentRoomDto } from "./dto/apartment.dto";

@Injectable()
export class ApartmentsService {
  constructor(private readonly dataSource: DataSource) {}
  private scope(scope: TenantParkScope) { return [scope.tenantId, scope.parkId]; }

  async summary(scope: TenantParkScope) {
    const [row] = await this.dataSource.query(`SELECT
      (SELECT count(*)::int FROM biz_apartment_room r WHERE r.tenant_id=$1 AND r.park_id=$2 AND r.is_deleted=false AND r.management_status='enabled') AS rooms,
      (SELECT COALESCE(sum(r.capacity),0)::int FROM biz_apartment_room r WHERE r.tenant_id=$1 AND r.park_id=$2 AND r.is_deleted=false AND r.management_status='enabled') AS beds,
      (SELECT count(*)::int FROM biz_apartment_stay s WHERE s.tenant_id=$1 AND s.park_id=$2 AND s.is_deleted=false AND s.status='active') AS occupied,
      (SELECT count(*)::int FROM biz_apartment_application a WHERE a.tenant_id=$1 AND a.park_id=$2 AND a.is_deleted=false AND a.status='submitted') AS pending_applications,
      (SELECT count(*)::int FROM biz_apartment_stay s WHERE s.tenant_id=$1 AND s.park_id=$2 AND s.is_deleted=false AND s.status='checkout_pending') AS pending_checkouts`, this.scope(scope));
    return { ...row, available: Math.max(0, Number(row.beds)-Number(row.occupied)) };
  }

  listRooms(scope: TenantParkScope, query: ListApartmentDto) {
    return this.dataSource.query(`SELECT r.*,u.unit_code,u.unit_name,b.name AS building_name,f.floor_name,
      count(bed.id)::int AS bed_count,count(s.id) FILTER (WHERE s.status IN ('reserved','active','checkout_pending'))::int AS occupied_count
      FROM biz_apartment_room r JOIN biz_unit u ON u.id=r.unit_id
      LEFT JOIN biz_building b ON b.id=u.building_id LEFT JOIN biz_floor f ON f.id=u.floor_id
      LEFT JOIN biz_apartment_bed bed ON bed.room_id=r.id AND bed.is_deleted=false
      LEFT JOIN biz_apartment_stay s ON s.bed_id=bed.id AND s.is_deleted=false AND s.status IN ('reserved','active','checkout_pending')
      WHERE r.tenant_id=$1 AND r.park_id=$2 AND r.is_deleted=false
      AND ($3::text IS NULL OR r.management_status=$3)
      AND ($4::text IS NULL OR u.unit_name ILIKE '%'||$4||'%' OR u.unit_code ILIKE '%'||$4||'%')
      GROUP BY r.id,u.id,b.id,f.id ORDER BY u.unit_code`, [...this.scope(scope), query.status ?? null, query.keyword?.trim() || null]);
  }
  unitCandidates(scope:TenantParkScope){return this.dataSource.query(`SELECT u.id,u.unit_code,u.unit_name,b.name AS building_name,f.floor_name FROM biz_unit u LEFT JOIN biz_building b ON b.id=u.building_id LEFT JOIN biz_floor f ON f.id=u.floor_id WHERE u.tenant_id=$1 AND u.park_id=$2 AND u.is_deleted=false AND NOT EXISTS(SELECT 1 FROM biz_apartment_room r WHERE r.unit_id=u.id AND r.is_deleted=false) AND NOT EXISTS(SELECT 1 FROM biz_property_occupancy o WHERE o.unit_id=u.id AND o.is_deleted=false AND o.status IN ('held','active') AND o.end_at>now()) ORDER BY u.unit_code LIMIT 500`,this.scope(scope));}
  availableBeds(scope:TenantParkScope,start:string,end?:string){return this.dataSource.query(`SELECT b.id,b.bed_code,b.room_id,u.unit_code,u.unit_name,r.room_type,r.gender_policy FROM biz_apartment_bed b JOIN biz_apartment_room r ON r.id=b.room_id JOIN biz_unit u ON u.id=r.unit_id WHERE b.tenant_id=$1 AND b.park_id=$2 AND b.is_deleted=false AND b.status='enabled' AND r.is_deleted=false AND r.management_status='enabled' AND NOT EXISTS(SELECT 1 FROM biz_apartment_stay s WHERE s.bed_id=b.id AND s.is_deleted=false AND s.status IN ('reserved','active','checkout_pending') AND daterange(s.planned_start_date,COALESCE(s.planned_end_date,'infinity'::date),'[)') && daterange($3::date,COALESCE($4::date,'infinity'::date),'[)')) ORDER BY u.unit_code,b.bed_code`,[...this.scope(scope),start,end??null]);}

  async createRoom(scope: TenantParkScope, actor: JwtPrincipal, dto: CreateApartmentRoomDto) {
    return this.dataSource.transaction(async manager => {
      const unit = await manager.query(`SELECT id FROM biz_unit WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`, [dto.unit_id, ...this.scope(scope)]);
      if (!unit.length) throw new NotFoundException("房源不存在或不在当前园区");
      const [room] = await manager.query(`INSERT INTO biz_apartment_room(tenant_id,park_id,unit_id,room_type,gender_policy,capacity,facilities,effective_from,management_status,create_by,update_by)
        VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,'enabled',$9,$9) RETURNING *`, [...this.scope(scope), dto.unit_id,dto.room_type,dto.gender_policy??"any",dto.capacity,JSON.stringify(dto.facilities??[]),dto.effective_from??new Date().toISOString().slice(0,10),actor.sub]);
      const [occupancy] = await manager.query(`INSERT INTO biz_property_occupancy(tenant_id,park_id,unit_id,source_domain,source_type,source_id,start_at,end_at,status,create_by,update_by)
        VALUES($1,$2,$3,'apartment','apartment_room',$4,$5::date,'9999-12-31','active',$6,$6) RETURNING id`, [...this.scope(scope),dto.unit_id,room.id,dto.effective_from??new Date().toISOString().slice(0,10),actor.sub]);
      await manager.query(`UPDATE biz_apartment_room SET occupancy_id=$1 WHERE id=$2`, [occupancy.id,room.id]);
      for (let i=1;i<=dto.capacity;i++) await manager.query(`INSERT INTO biz_apartment_bed(tenant_id,park_id,room_id,bed_code,status,create_by,update_by) VALUES($1,$2,$3,$4,'enabled',$5,$5)`, [...this.scope(scope),room.id,String(i).padStart(2,"0"),actor.sub]);
      return { ...room, occupancy_id: occupancy.id };
    }).catch(this.translateConflict);
  }

  async updateRoom(scope: TenantParkScope, actor: JwtPrincipal, id: string, dto: UpdateApartmentRoomDto) {
    return this.dataSource.transaction(async manager => {
      const [room] = await manager.query(`SELECT * FROM biz_apartment_room WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`, [id,...this.scope(scope)]);
      if (!room) throw new NotFoundException("公寓房间不存在");
      const [{ count }] = await manager.query(`SELECT count(*)::int count FROM biz_apartment_stay WHERE room_id=$1 AND status IN ('reserved','active','checkout_pending') AND is_deleted=false`,[id]);
      if (dto.capacity !== undefined && dto.capacity < count) throw new ConflictException("新容量不能小于当前占用数");
      await manager.query(`UPDATE biz_apartment_room SET room_type=COALESCE($1,room_type),gender_policy=COALESCE($2,gender_policy),capacity=COALESCE($3,capacity),facilities=COALESCE($4::jsonb,facilities),management_status=COALESCE($5,management_status),update_by=$6,update_time=now() WHERE id=$7`,[dto.room_type??null,dto.gender_policy??null,dto.capacity??null,dto.facilities?JSON.stringify(dto.facilities):null,dto.management_status??null,actor.sub,id]);
      if (dto.capacity && dto.capacity > room.capacity) for(let i=room.capacity+1;i<=dto.capacity;i++) await manager.query(`INSERT INTO biz_apartment_bed(tenant_id,park_id,room_id,bed_code,status,create_by,update_by) VALUES($1,$2,$3,$4,'enabled',$5,$5) ON CONFLICT DO NOTHING`,[...this.scope(scope),id,String(i).padStart(2,"0"),actor.sub]);
      return (await manager.query(`SELECT * FROM biz_apartment_room WHERE id=$1`,[id]))[0];
    });
  }

  listApplications(scope: TenantParkScope, query: ListApartmentDto) { return this.dataSource.query(`SELECT a.*,u.real_name AS applicant_user_name FROM biz_apartment_application a LEFT JOIN sys_user u ON u.id=a.applicant_user_id WHERE a.tenant_id=$1 AND a.park_id=$2 AND a.is_deleted=false AND ($3::text IS NULL OR a.status=$3) AND ($4::text IS NULL OR a.applicant_name ILIKE '%'||$4||'%' OR a.application_code ILIKE '%'||$4||'%') ORDER BY a.create_time DESC`,[...this.scope(scope),query.status??null,query.keyword?.trim()||null]); }
  async createApplication(scope: TenantParkScope, actor: JwtPrincipal, dto: CreateApartmentApplicationDto) {
    if (!dto.applicant_party_id && !dto.applicant_user_id) dto.applicant_user_id=actor.sub;
    if (dto.requested_end_date && dto.requested_start_date>=dto.requested_end_date) throw new BadRequestException("结束日期必须晚于开始日期");
    const code=`APT-${new Date().toISOString().slice(0,10).replaceAll("-","")}-${randomUUID().slice(0,8).toUpperCase()}`;
    const [row]=await this.dataSource.query(`INSERT INTO biz_apartment_application(tenant_id,park_id,application_code,applicant_party_id,applicant_user_id,applicant_name,applicant_type,organization_name,department_name,job_title,mobile_masked,identity_number_masked,requested_room_type,requested_start_date,requested_end_date,reason,status,create_by,update_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,'draft',$17,$17) RETURNING *`,[...this.scope(scope),code,dto.applicant_party_id??null,dto.applicant_user_id??null,dto.applicant_name,dto.applicant_type,dto.organization_name??null,dto.department_name??null,dto.job_title??null,dto.mobile_masked??null,dto.identity_number_masked??null,dto.requested_room_type,dto.requested_start_date,dto.requested_end_date??null,dto.reason,actor.sub]); return row;
  }
  async submit(scope:TenantParkScope,actor:JwtPrincipal,id:string){return this.transition(scope,actor,id,"draft","submitted",`submitted_at=now()`);}
  async cancel(scope:TenantParkScope,actor:JwtPrincipal,id:string){const [r]=await this.dataSource.query(`UPDATE biz_apartment_application SET status='cancelled',update_by=$1,update_time=now(),version=version+1 WHERE id=$2 AND tenant_id=$3 AND park_id=$4 AND status IN ('draft','submitted','approved') AND is_deleted=false RETURNING *`,[actor.sub,id,...this.scope(scope)]);if(!r)throw new ConflictException("当前状态不可取消申请");return r;}
  async decide(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:DecisionDto){return this.dataSource.transaction(async manager=>{const [app]=await this.lockApplication(manager,scope,id);if(app.status!=="submitted")throw new ConflictException("仅已提交申请可审批");await manager.query(`INSERT INTO biz_apartment_approval(tenant_id,park_id,application_id,application_version,decision,decided_by,opinion,create_by,update_by) VALUES($1,$2,$3,$4,$5,$6,$7,$6,$6)`,[...this.scope(scope),id,app.version,dto.decision,actor.sub,dto.opinion??null]);const status=dto.decision==="approve"?"approved":"rejected";return (await manager.query(`UPDATE biz_apartment_application SET status=$1,decided_at=now(),update_by=$2,update_time=now(),version=version+1 WHERE id=$3 RETURNING *`,[status,actor.sub,id]))[0];});}
  async allocate(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:AllocateApartmentDto){return this.dataSource.transaction(async manager=>{const [app]=await this.lockApplication(manager,scope,id);if(app.status!=="approved")throw new ConflictException("仅已批准申请可分配床位");const [bed]=await manager.query(`SELECT b.id,b.room_id,r.room_type,r.gender_policy,r.management_status FROM biz_apartment_bed b JOIN biz_apartment_room r ON r.id=b.room_id WHERE b.id=$1 AND b.room_id=$2 AND b.tenant_id=$3 AND b.park_id=$4 AND b.status='enabled' AND b.is_deleted=false AND r.is_deleted=false FOR UPDATE`,[dto.bed_id,dto.room_id,...this.scope(scope)]);if(!bed||bed.management_status!=="enabled")throw new ConflictException("床位当前不可分配");const code=`STAY-${Date.now()}-${randomUUID().slice(0,6).toUpperCase()}`;const [stay]=await manager.query(`INSERT INTO biz_apartment_stay(tenant_id,park_id,stay_code,application_id,room_id,bed_id,occupant_party_id,occupant_user_id,occupant_name,planned_start_date,planned_end_date,status,create_by,update_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'reserved',$12,$12) RETURNING *`,[...this.scope(scope),code,id,dto.room_id,dto.bed_id,app.applicant_party_id,app.applicant_user_id,app.applicant_name,app.requested_start_date,dto.planned_end_date??app.requested_end_date,actor.sub]);await manager.query(`UPDATE biz_apartment_application SET status='allocated',update_by=$1,update_time=now(),version=version+1 WHERE id=$2`,[actor.sub,id]);return stay;}).catch(this.translateConflict);}
  listStays(scope:TenantParkScope,query:ListApartmentDto){return this.dataSource.query(`SELECT s.*,a.application_code,u.unit_name,u.unit_code,b.bed_code FROM biz_apartment_stay s JOIN biz_apartment_application a ON a.id=s.application_id JOIN biz_apartment_room r ON r.id=s.room_id JOIN biz_unit u ON u.id=r.unit_id JOIN biz_apartment_bed b ON b.id=s.bed_id WHERE s.tenant_id=$1 AND s.park_id=$2 AND s.is_deleted=false AND ($3::text IS NULL OR s.status=$3) AND ($4::text IS NULL OR s.occupant_name ILIKE '%'||$4||'%' OR s.stay_code ILIKE '%'||$4||'%') ORDER BY s.create_time DESC`,[...this.scope(scope),query.status??null,query.keyword?.trim()||null]);}
  async checkIn(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HandoverDto){return this.handover(scope,actor,id,"move_in",dto,"reserved","active");}
  async requestCheckout(scope:TenantParkScope,actor:JwtPrincipal,id:string){return this.dataSource.transaction(async manager=>{const [stay]=await manager.query(`SELECT * FROM biz_apartment_stay WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`,[id,...this.scope(scope)]);if(!stay||stay.status!=="active")throw new ConflictException("仅在住记录可发起退房");await manager.query(`UPDATE biz_apartment_stay SET status='checkout_pending',checkout_requested_at=now(),update_by=$1,update_time=now() WHERE id=$2`,[actor.sub,id]);await manager.query(`UPDATE biz_apartment_application SET status='checkout_pending',update_by=$1,update_time=now() WHERE id=$2`,[actor.sub,stay.application_id]);return {id,status:"checkout_pending"};});}
  async checkOut(scope:TenantParkScope,actor:JwtPrincipal,id:string,dto:HandoverDto){return this.handover(scope,actor,id,"move_out",dto,"checkout_pending","completed");}
  listTemplates(scope:TenantParkScope){return this.dataSource.query(`SELECT * FROM biz_apartment_document_template WHERE tenant_id=$1 AND park_id=$2 AND is_deleted=false ORDER BY document_type,version_no DESC`,this.scope(scope));}
  async createTemplate(scope:TenantParkScope,actor:JwtPrincipal,dto:CreateTemplateDto){const [r]=await this.dataSource.query(`INSERT INTO biz_apartment_document_template(tenant_id,park_id,document_type,version_no,status,template_file_id,variable_schema,create_by,update_by) VALUES($1,$2,$3,$4,'draft',$5,$6::jsonb,$7,$7) RETURNING *`,[...this.scope(scope),dto.document_type,dto.version_no,dto.template_file_id??null,JSON.stringify(dto.variable_schema??{}),actor.sub]);return r;}
  async publishTemplate(scope:TenantParkScope,actor:JwtPrincipal,id:string){const [r]=await this.dataSource.query(`UPDATE biz_apartment_document_template SET status='published',published_at=now(),update_by=$1,update_time=now() WHERE id=$2 AND tenant_id=$3 AND park_id=$4 AND status='draft' AND is_deleted=false RETURNING *`,[actor.sub,id,...this.scope(scope)]);if(!r)throw new ConflictException("仅草稿模板可发布");return r;}
  listDocuments(scope:TenantParkScope){return this.dataSource.query(`SELECT d.*,t.document_type AS template_type FROM biz_apartment_document d JOIN biz_apartment_document_template t ON t.id=d.template_id WHERE d.tenant_id=$1 AND d.park_id=$2 AND d.is_deleted=false ORDER BY d.create_time DESC`,this.scope(scope));}
  async archiveDocument(scope:TenantParkScope,actor:JwtPrincipal,dto:ArchiveDocumentDto){if(!dto.stay_id&&!dto.application_id)throw new BadRequestException("必须关联申请或入住记录");const [t]=await this.dataSource.query(`SELECT * FROM biz_apartment_document_template WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND status='published' AND is_deleted=false`,[dto.template_id,...this.scope(scope)]);if(!t)throw new NotFoundException("已发布模板不存在");const hash=dto.signed_file_id?(dto.signed_sha256??createHash("sha256").update(dto.signed_file_id).digest("hex")):null;const [r]=await this.dataSource.query(`INSERT INTO biz_apartment_document(tenant_id,park_id,stay_id,application_id,template_id,document_type,template_version,variable_snapshot,generated_file_id,signed_file_id,signed_sha256,signed_at,create_by,update_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,CASE WHEN $10::uuid IS NULL THEN NULL ELSE now() END,$12,$12) RETURNING *`,[...this.scope(scope),dto.stay_id??null,dto.application_id??null,t.id,t.document_type,t.version_no,JSON.stringify(dto.variables??{}),dto.generated_file_id??null,dto.signed_file_id??null,hash,actor.sub]);return r;}

  private async transition(scope:TenantParkScope,actor:JwtPrincipal,id:string,from:string,to:string,extra:string){const [r]=await this.dataSource.query(`UPDATE biz_apartment_application SET status=$1,${extra},update_by=$2,update_time=now(),version=version+1 WHERE id=$3 AND tenant_id=$4 AND park_id=$5 AND status=$6 AND is_deleted=false RETURNING *`,[to,actor.sub,id,...this.scope(scope),from]);if(!r)throw new ConflictException(`当前状态不可执行此操作`);return r;}
  private lockApplication(manager:EntityManager,scope:TenantParkScope,id:string){return manager.query(`SELECT * FROM biz_apartment_application WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`,[id,...this.scope(scope)]);}
  private async handover(scope:TenantParkScope,actor:JwtPrincipal,id:string,type:"move_in"|"move_out",dto:HandoverDto,from:string,to:string){return this.dataSource.transaction(async manager=>{const [stay]=await manager.query(`SELECT * FROM biz_apartment_stay WHERE id=$1 AND tenant_id=$2 AND park_id=$3 AND is_deleted=false FOR UPDATE`,[id,...this.scope(scope)]);if(!stay||stay.status!==from)throw new ConflictException("当前入住状态不可办理交接");const [handover]=await manager.query(`INSERT INTO biz_apartment_handover(tenant_id,park_id,stay_id,handover_type,status,item_snapshot,key_snapshot,photo_file_ids,exception_note,confirmed_at,create_by,update_by) VALUES($1,$2,$3,$4,'confirmed',$5::jsonb,$6::jsonb,$7::jsonb,$8,now(),$9,$9) ON CONFLICT (tenant_id,park_id,stay_id,handover_type) WHERE is_deleted=false DO UPDATE SET item_snapshot=EXCLUDED.item_snapshot,key_snapshot=EXCLUDED.key_snapshot,photo_file_ids=EXCLUDED.photo_file_ids,exception_note=EXCLUDED.exception_note,status='confirmed',confirmed_at=now(),update_by=EXCLUDED.update_by,update_time=now() RETURNING *`,[...this.scope(scope),id,type,JSON.stringify(dto.items??[]),JSON.stringify(dto.keys??[]),JSON.stringify(dto.photo_file_ids??[]),dto.exception_note??null,actor.sub]);await manager.query(`UPDATE biz_apartment_stay SET status=$1,actual_check_in_at=CASE WHEN $1='active' THEN now() ELSE actual_check_in_at END,actual_check_out_at=CASE WHEN $1='completed' THEN now() ELSE actual_check_out_at END,update_by=$2,update_time=now() WHERE id=$3`,[to,actor.sub,id]);await manager.query(`UPDATE biz_apartment_application SET status=$1,update_by=$2,update_time=now() WHERE id=$3`,[to==="active"?"checked_in":"completed",actor.sub,stay.application_id]);return handover;});}
  private translateConflict(error: unknown): never { if (typeof error === "object"&&error&&"code" in error&&(["23P01","23505"].includes(String((error as {code:unknown}).code)))) throw new ConflictException("房源或床位已被占用，请刷新后重试"); throw error; }
}
