import { Body, Controller, Get, Param, ParseUUIDPipe, Post, Put, Query, UseInterceptors } from "@nestjs/common";
import { APARTMENT_PERMISSIONS, type TenantParkScope } from "@jinhu/shared";
import { CurrentScope } from "../../shared/decorators/current-scope.decorator";
import { CurrentUser } from "../../shared/decorators/current-user.decorator";
import { RequireModule } from "../../shared/decorators/modules.decorator";
import { RequirePermissions } from "../../shared/decorators/permissions.decorator";
import { IdempotencyInterceptor } from "../../shared/interceptors/idempotency.interceptor";
import type { JwtPrincipal } from "../../shared/types/jwt-principal";
import { AuditLog } from "../audit/decorators/audit-log.decorator";
import { ApartmentsService } from "./apartments.service";
import { AllocateApartmentDto, ApartmentUnitCandidateQueryDto, ArchiveDocumentDto, CreateApartmentApplicationDto, CreateApartmentRoomDto, CreateTemplateDto, DecisionDto, GenerateApartmentDocumentDto, HandoverDto, ListApartmentDto, OnlineSignApartmentDocumentDto, PaperSignApartmentDocumentDto, UpdateApartmentRoomDto, UpdateApartmentSettingsDto, VoidApartmentDocumentDto } from "./dto/apartment.dto";

@Controller("apartments")
@RequireModule("apartment")
export class ApartmentsController {
  constructor(private readonly service: ApartmentsService) {}
  @Get("summary") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) summary(@CurrentScope() s:TenantParkScope){return this.service.summary(s);}
  @Get("rooms") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) rooms(@CurrentScope() s:TenantParkScope,@Query() q:ListApartmentDto){return this.service.listRooms(s,q);}
  @Get("unit-candidates") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_ROOM_MANAGE) unitCandidates(@CurrentScope()s:TenantParkScope,@Query()q:ApartmentUnitCandidateQueryDto){return this.service.unitCandidates(s,q);}
  @Get("available-beds") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_ALLOCATE) availableBeds(@CurrentScope()s:TenantParkScope,@Query("start")start:string,@Query("end")end?:string){return this.service.availableBeds(s,start,end);}
  @Post("rooms") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_ROOM_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_room",action:"新增公寓房源",bizType:"biz_apartment_room"}) createRoom(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateApartmentRoomDto){return this.service.createRoom(s,u,d);}
  @Put("rooms/:id") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_ROOM_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_room",action:"更新公寓房源",bizType:"biz_apartment_room"}) updateRoom(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:UpdateApartmentRoomDto){return this.service.updateRoom(s,u,id,d);}
  @Get("applications") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) applications(@CurrentScope()s:TenantParkScope,@Query()q:ListApartmentDto){return this.service.listApplications(s,q);}
  @Post("applications") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_APPLY) @AuditLog({module:"公寓管理",resource:"biz.apartment_application",action:"创建入住申请",bizType:"biz_apartment_application",captureBody:false}) createApplication(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateApartmentApplicationDto){return this.service.createApplication(s,u,d);}
  @Post("applications/:id/submit") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_APPLY) @AuditLog({module:"公寓管理",resource:"biz.apartment_application",action:"提交入住申请",bizType:"biz_apartment_application"}) submit(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.submit(s,u,id);}
  @Post("applications/:id/cancel") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_APPLICATION_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_application",action:"取消入住申请",bizType:"biz_apartment_application"}) cancel(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.cancel(s,u,id);}
  @Post("applications/:id/decision") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_APPROVE) @AuditLog({module:"公寓管理",resource:"biz.apartment_approval",action:"审批入住申请",bizType:"biz_apartment_application"}) decide(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:DecisionDto){return this.service.decide(s,u,id,d);}
  @Post("applications/:id/allocate") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_ALLOCATE) @AuditLog({module:"公寓管理",resource:"biz.apartment_stay",action:"分配公寓床位",bizType:"biz_apartment_stay"}) allocate(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:AllocateApartmentDto){return this.service.allocate(s,u,id,d);}
  @Get("stays") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) stays(@CurrentScope()s:TenantParkScope,@Query()q:ListApartmentDto){return this.service.listStays(s,q);}
  @Post("stays/:id/check-in") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_CHECK_IN) @AuditLog({module:"公寓管理",resource:"biz.apartment_handover",action:"办理入住交接",bizType:"biz_apartment_stay"}) checkIn(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HandoverDto){return this.service.checkIn(s,u,id,d);}
  @Post("stays/:id/request-checkout") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_CHECK_OUT) @AuditLog({module:"公寓管理",resource:"biz.apartment_stay",action:"发起退房",bizType:"biz_apartment_stay"}) requestCheckout(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.requestCheckout(s,u,id);}
  @Post("stays/:id/check-out") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_CHECK_OUT) @AuditLog({module:"公寓管理",resource:"biz.apartment_handover",action:"完成退房验收",bizType:"biz_apartment_stay"}) checkOut(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:HandoverDto){return this.service.checkOut(s,u,id,d);}
  @Get("settings") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) settings(@CurrentScope()s:TenantParkScope){return this.service.getSettings(s);}
  @Put("settings") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_setting",action:"更新公寓默认设置",bizType:"biz_apartment_setting"}) updateSettings(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:UpdateApartmentSettingsDto){return this.service.updateSettings(s,u,d);}
  @Get("templates") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) templates(@CurrentScope()s:TenantParkScope){return this.service.listTemplates(s);}
  @Post("templates") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) createTemplate(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:CreateTemplateDto){return this.service.createTemplate(s,u,d);}
  @Post("templates/:id/publish") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) publishTemplate(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string){return this.service.publishTemplate(s,u,id);}
  @Get("documents") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) documents(@CurrentScope()s:TenantParkScope){return this.service.listDocuments(s);}
  @Get("documents/:id") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) documentDetail(@CurrentScope()s:TenantParkScope,@Param("id",new ParseUUIDPipe())id:string){return this.service.getDocument(s,id);}
  @Get("documents/:id/render") @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_READ) renderDocument(@CurrentScope()s:TenantParkScope,@Param("id",new ParseUUIDPipe())id:string){return this.service.renderDocument(s,id);}
  @Post("documents/generate") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_document",action:"生成公寓正式文书",bizType:"biz_apartment_document",captureBody:false}) generateDocument(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:GenerateApartmentDocumentDto){return this.service.generateDocument(s,u,d);}
  @Post("documents/:id/sign-online") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_document",action:"线上签署公寓文书",bizType:"biz_apartment_document",captureBody:false}) onlineSign(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:OnlineSignApartmentDocumentDto){return this.service.onlineSign(s,u,id,d);}
  @Post("documents/:id/sign-paper") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_document",action:"归档纸质签字文书",bizType:"biz_apartment_document",captureBody:false}) paperSign(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:PaperSignApartmentDocumentDto){return this.service.paperSign(s,u,id,d);}
  @Post("documents/:id/void") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_document",action:"作废公寓文书",bizType:"biz_apartment_document"}) voidDocument(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Param("id",new ParseUUIDPipe())id:string,@Body()d:VoidApartmentDocumentDto){return this.service.voidDocument(s,u,id,d);}
  @Post("documents") @UseInterceptors(new IdempotencyInterceptor()) @RequirePermissions(APARTMENT_PERMISSIONS.APARTMENT_DOCUMENT_MANAGE) @AuditLog({module:"公寓管理",resource:"biz.apartment_document",action:"兼容归档公寓文书",bizType:"biz_apartment_document",captureBody:false}) document(@CurrentScope()s:TenantParkScope,@CurrentUser()u:JwtPrincipal,@Body()d:ArchiveDocumentDto){return this.service.archiveDocument(s,u,d);}
}
