import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrApprovalsClient} from "../../app/hr/approvals/HrApprovalsClient";
import {ApiError} from "../../lib/api-client";
import {hrApi,type HrApproval} from "../../lib/hr-api";
import type * as ApiClientModule from "../../lib/api-client";
const auth=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>auth.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"token"}));
vi.mock("../../lib/api-client",async original=>({...await original<typeof ApiClientModule>(),createIdempotencyKey:()=>"revision-key"}));
vi.mock("../../lib/hr-api",()=>({hrApi:{myApprovals:vi.fn(),pendingApprovals:vi.fn(),createApproval:vi.fn(),approvalAction:vi.fn(),reviewApproval:vi.fn(),approvalHistory:vi.fn(),reviseApproval:vi.fn()}}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
const row=(version=3,title="退回的申请"):HrApproval=>({id:"approval",requestNo:"HR-UNCHANGED",requestType:"profile_change",applicantEmployeeId:"employee",subjectEmployeeId:"employee",title,payload:{description:version===3?"原说明":"修改说明"},version,status:"returned",submittedAt:null,completedAt:null});
beforeEach(()=>{vi.resetAllMocks();auth.user={id:"actor",park_id:"park",permissions:[H.HR_APPROVALS_PAGE,H.HR_APPROVAL_SELF_MANAGE]};vi.mocked(hrApi.myApprovals).mockResolvedValue([row()]);vi.mocked(hrApi.pendingApprovals).mockResolvedValue([]);vi.mocked(hrApi.approvalHistory).mockResolvedValue({request:row(),actions:[]});});
async function edit(){fireEvent.click(await screen.findByRole("button",{name:"查看办理记录"}));fireEvent.click(await screen.findByRole("button",{name:"修改申请内容"}));fireEvent.change(screen.getByLabelText("申请标题"),{target:{value:"修改标题"}});fireEvent.change(screen.getByLabelText("申请说明"),{target:{value:"修改说明"}});fireEvent.change(screen.getByLabelText("修改原因"),{target:{value:"补充退回意见"}});}
it("retains revision fields on conflict and locks sibling actions while editing",async()=>{vi.mocked(hrApi.reviseApproval).mockRejectedValueOnce(new ApiError("版本冲突",409));render(<HrApprovalsClient/>);await edit();expect(screen.getByRole("button",{name:"发起申请"})).toBeDisabled();expect(screen.getByRole("button",{name:"重新提交审核"})).toBeDisabled();expect(screen.getByRole("button",{name:/^刷新$/})).toBeDisabled();fireEvent.submit(screen.getByRole("button",{name:"保存修改"}).closest("form")!);await screen.findByText("版本冲突");expect(screen.getByLabelText("申请标题")).toHaveValue("修改标题");expect(screen.getByLabelText("修改原因")).toHaveValue("补充退回意见");expect(screen.queryByRole("button",{name:"按原请求重试"})).toBeNull();fireEvent.click(screen.getByRole("button",{name:"取消修改"}));expect(screen.getByRole("button",{name:"重新提交审核"})).toBeEnabled();});
it("retries the frozen revision and retains its new version through stale same-status reads before resubmit",async()=>{const revised=row(4,"修改标题");vi.mocked(hrApi.reviseApproval).mockRejectedValueOnce(new Error("响应中断")).mockResolvedValueOnce(revised);vi.mocked(hrApi.approvalAction).mockResolvedValueOnce({...revised,version:5,status:"submitted"});render(<HrApprovalsClient/>);await edit();const form=screen.getByRole("button",{name:"保存修改"}).closest("form")!;fireEvent.submit(form);fireEvent.submit(form);await screen.findByRole("button",{name:"按原请求重试"});expect(hrApi.reviseApproval).toHaveBeenCalledTimes(1);expect(screen.getByLabelText("申请标题")).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"按原请求重试"}));await screen.findByText("申请内容已修改，请核对后重新提交。");expect(vi.mocked(hrApi.reviseApproval).mock.calls[0]).toEqual(vi.mocked(hrApi.reviseApproval).mock.calls[1]);await waitFor(()=>expect(hrApi.myApprovals).toHaveBeenCalledTimes(2));expect(screen.getByText("修改标题")).toBeVisible();expect(screen.queryByText("退回的申请")).toBeNull();expect(screen.getByText("HR-UNCHANGED")).toBeVisible();fireEvent.click(screen.getByRole("button",{name:"重新提交审核"}));await screen.findByText("提交申请已保存。");expect(hrApi.approvalAction).toHaveBeenCalledWith("approval",{action:"resubmit"},"token","revision-key");expect(screen.getByText("修改标题")).toBeVisible();});
