import {act,fireEvent,render,screen,waitFor,within} from '@testing-library/react';
import {beforeEach,expect,it,vi} from 'vitest';
import {CandidateProfile,projectCandidateProfile} from '../../app/hr/recruitment/CandidateProfile';
import {hrApi,type HrCandidateProfile} from '../../lib/hr-api';
vi.mock('../../lib/authz',()=>({getAccessToken:()=> 'synthetic-token'}));
vi.mock('../../lib/hr-api',()=>({hrApi:{recruitmentCandidateProfile:vi.fn(),recruitmentCandidateProfileHistory:vi.fn(),recruitmentCandidateProfileRequisitionOptions:vi.fn(),saveRecruitmentCandidateProfile:vi.fn()}}));
const row=(extra:Partial<HrCandidateProfile>={}):HrCandidateProfile=>({id:'candidate-a',version:4,candidateNo:'C1',fullName:'合成候选人',requisitionId:'req-a',requisitionTitle:'合成需求',stage:'interview',source:'渠道',expectedOnboardDate:'2026-10-15',latestEvaluation:null,convertedEmployeeId:null,mobileMasked:'138****0000',emailMasked:null,identityMasked:null,sensitiveAvailable:false,updatedAt:'2026-10-11T01:00:00Z',...extra});
const props={candidateId:'candidate-a',canManage:true,disabled:false,onBusyChange:vi.fn(),onSaved:vi.fn()};
const page=(items:unknown[]=[],n=1,total=items.length)=>({items,total,page:n,page_size:10});
beforeEach(()=>{vi.resetAllMocks();vi.mocked(hrApi.recruitmentCandidateProfile).mockResolvedValue(row());vi.mocked(hrApi.recruitmentCandidateProfileHistory).mockImplementation(async(_id,_token,n=1)=>page([],n) as never);vi.mocked(hrApi.recruitmentCandidateProfileRequisitionOptions).mockResolvedValue(page() as never);});
async function open(){fireEvent.click(screen.getByRole('button',{name:'维护候选人资料'}));await screen.findByLabelText('更正原因');}
const change=(label:string,value:string)=>fireEvent.change(screen.getByLabelText(label),{target:{value}});
const save=()=>fireEvent.submit(screen.getByRole('form',{name:'更正候选人资料'}));
it('loads lazily and allows basic corrections with protected fields omitted',async()=>{vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockResolvedValue(row({version:5,fullName:'更新姓名',source:null,expectedOnboardDate:null}));render(<CandidateProfile {...props}/>);expect(hrApi.recruitmentCandidateProfile).not.toHaveBeenCalled();await open();expect(screen.queryByLabelText('手机号')).not.toBeInTheDocument();change('姓名','更新姓名');change('来源','');change('预计入职','');change('更正原因','更正登记');save();await screen.findByText('资料已保存，版本 5。');expect(hrApi.saveRecruitmentCandidateProfile).toHaveBeenCalledWith('candidate-a',{expectedVersion:4,changeReason:'更正登记',fullName:'更新姓名',source:null,expectedOnboardDate:null},'synthetic-token',expect.any(String));expect(props.onSaved).toHaveBeenCalledWith(row({version:5,fullName:'更新姓名',source:null,expectedOnboardDate:null}));});
it('shows history without mutable controls for read-only users',async()=>{render(<CandidateProfile {...props} canManage={false}/>);fireEvent.click(screen.getByRole('button',{name:'资料更正历史'}));await screen.findByText(/招聘需求：合成需求 · 资料版本 4/);expect(screen.queryByRole('form')).not.toBeInTheDocument();expect(screen.queryByRole('button',{name:'更换招聘需求'})).not.toBeInTheDocument();});
it('reuses exact uncertain request and rejects wrong save association',async()=>{vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockResolvedValueOnce(row({id:'other',version:5,fullName:'我的姓名'})).mockResolvedValueOnce(row({version:5,fullName:'我的姓名'}));render(<CandidateProfile {...props}/>);await open();change('姓名','我的姓名');change('更正原因','更正');save();await screen.findByRole('alert');expect(props.onSaved).not.toHaveBeenCalled();expect(screen.getByLabelText('姓名')).toHaveValue('我的姓名');save();await screen.findByText('资料已保存，版本 5。');const calls=vi.mocked(hrApi.saveRecruitmentCandidateProfile).mock.calls;expect(calls).toHaveLength(2);expect(calls[0]).toEqual(calls[1]);});
it('requires explicit conflict acknowledgment and respects current hired relationship',async()=>{vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockRejectedValueOnce({status:409,message:'Candidate changed; reload before saving'}).mockResolvedValueOnce(row({version:7,fullName:'草稿姓名',stage:'hired',convertedEmployeeId:'employee-a'}));vi.mocked(hrApi.recruitmentCandidateProfile).mockResolvedValueOnce(row()).mockResolvedValueOnce(row({version:6,fullName:'他人姓名',stage:'hired',convertedEmployeeId:'employee-a'}));render(<CandidateProfile {...props}/>);await open();change('姓名','草稿姓名');change('更正原因','核对后更正');save();const region=await screen.findByRole('region',{name:'资料冲突比较'});await within(region).findByText(/服务器版本 6/);expect(screen.getByRole('button',{name:'保存资料更正'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'确认以草稿更新'}));expect(screen.queryByRole('button',{name:'更换招聘需求'})).not.toBeInTheDocument();save();await screen.findByText('资料已保存，版本 7。');expect(vi.mocked(hrApi.saveRecruitmentCandidateProfile).mock.calls[1]![1]).toMatchObject({expectedVersion:6,fullName:'草稿姓名'});});
it('blocks synchronous duplicates and parent actions',async()=>{let resolve!:(v:HrCandidateProfile)=>void;vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockReturnValue(new Promise(r=>{resolve=r;}));render(<CandidateProfile {...props}/>);await open();change('姓名','更新姓名');change('更正原因','更正');act(()=>{save();save();});expect(hrApi.saveRecruitmentCandidateProfile).toHaveBeenCalledTimes(1);expect(props.onBusyChange).toHaveBeenCalledWith(true);expect(screen.getByLabelText('姓名')).toBeDisabled();await act(async()=>resolve(row({version:5,fullName:'更新姓名'})));expect(props.onBusyChange).toHaveBeenLastCalledWith(false);});
it('normalizes protected corrections and omits unchanged historical requirement',async()=>{vi.mocked(hrApi.recruitmentCandidateProfile).mockResolvedValue(row({sensitiveAvailable:true,mobile:null,email:null,identityNumber:null}));vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockResolvedValue(row({version:5,sensitiveAvailable:true,mobile:'13800000000',email:'user@example.test',identityNumber:'ABC123'}));render(<CandidateProfile {...props}/>);await open();change('手机号','138 0000 0000');change('邮箱','USER@example.test');change('证件号码','abc 123');change('更正原因','补充联系方式');save();await screen.findByText('资料已保存，版本 5。');expect(vi.mocked(hrApi.saveRecruitmentCandidateProfile).mock.calls[0]![1]).toEqual({expectedVersion:4,changeReason:'补充联系方式',mobile:'13800000000',email:'user@example.test',identityNumber:'ABC123'});});
it('supports independent history recovery and gapped global versions',async()=>{vi.mocked(hrApi.recruitmentCandidateProfileHistory).mockRejectedValueOnce(Error('offline')).mockImplementation(async(_id,_token,n=1)=>page([{id:`history-${n}`,before:row({version:n*3}),after:row({version:n*3+1,fullName:'历史姓名'}),changeReason:'补正',actorDisplayName:'合成办理人',occurredAt:'2026-10-11T01:00:00Z'}],n,11) as never);render(<CandidateProfile {...props}/>);await open();fireEvent.click(await screen.findByRole('button',{name:'重读资料历史'}));await screen.findByText('版本 3 → 4');fireEvent.click(screen.getByRole('button',{name:'资料历史下一页'}));await screen.findByText('版本 6 → 7');fireEvent.click(screen.getByRole('button',{name:'资料历史上一页'}));await screen.findByText('版本 3 → 4');expect(screen.getByLabelText('姓名')).toBeEnabled();});
it('rejects partial projections and never renders protected inputs on failed read',async()=>{vi.mocked(hrApi.recruitmentCandidateProfile).mockResolvedValueOnce({...row(),mobile:null});render(<CandidateProfile {...props}/>);fireEvent.click(screen.getByRole('button',{name:'维护候选人资料'}));await screen.findByRole('alert');expect(screen.queryByRole('form',{name:'更正候选人资料'})).not.toBeInTheDocument();fireEvent.click(screen.getByRole('button',{name:'重新读取资料'}));await screen.findByLabelText('姓名');expect(()=>projectCandidateProfile({...row(),expectedOnboardDate:'2026-02-30'},'candidate-a')).toThrow();});
it('ignores late reads after candidate switch',async()=>{let resolve!:(v:HrCandidateProfile)=>void;vi.mocked(hrApi.recruitmentCandidateProfile).mockReturnValueOnce(new Promise(r=>{resolve=r;})).mockResolvedValue(row({id:'candidate-b',fullName:'第二候选人'}));const view=render(<CandidateProfile {...props}/>);fireEvent.click(screen.getByRole('button',{name:'维护候选人资料'}));view.rerender(<CandidateProfile {...props} candidateId='candidate-b'/>);await waitFor(()=>expect(screen.getByRole('button',{name:'维护候选人资料'})).toBeEnabled());await open();await act(async()=>resolve(row()));expect(screen.getByLabelText('姓名')).toHaveValue('第二候选人');});

it('retains exact uncertain intent for an idempotency in-progress conflict',async()=>{vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockRejectedValueOnce(Object.assign(Error('Request is still processing'),{status:409})).mockResolvedValueOnce(row({version:5,fullName:'更新姓名'}));render(<CandidateProfile {...props}/>);await open();change('姓名','更新姓名');change('更正原因','更正');save();await screen.findByRole('alert');expect(screen.queryByRole('region',{name:'资料冲突比较'})).not.toBeInTheDocument();save();await screen.findByText('资料已保存，版本 5。');const calls=vi.mocked(hrApi.saveRecruitmentCandidateProfile).mock.calls;expect(calls[0]).toEqual(calls[1]);});

it('rebases only explicit draft intent, preserving another operator untouched fields',async()=>{vi.mocked(hrApi.recruitmentCandidateProfile).mockResolvedValueOnce(row()).mockResolvedValueOnce(row({version:6,source:'他人渠道',requisitionId:'req-b',requisitionTitle:'他人需求'}));vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockRejectedValueOnce({status:409,message:'Candidate changed; reload before saving'}).mockResolvedValueOnce(row({version:7,fullName:'草稿姓名',source:'他人渠道',requisitionId:'req-b',requisitionTitle:'他人需求'}));render(<CandidateProfile {...props}/>);await open();change('姓名','草稿姓名');change('更正原因','更正');save();await screen.findByText(/服务器版本 6/);fireEvent.click(screen.getByRole('button',{name:'确认以草稿更新'}));expect(screen.getByLabelText('来源')).toHaveValue('他人渠道');save();await screen.findByText('资料已保存，版本 7。');expect(vi.mocked(hrApi.saveRecruitmentCandidateProfile).mock.calls[1]![1]).toEqual({expectedVersion:6,changeReason:'更正',fullName:'草稿姓名'});});
it('keeps a chosen requirement off-page and submits only explicit relationship change',async()=>{
 vi.mocked(hrApi.recruitmentCandidateProfileRequisitionOptions).mockImplementation(async(_id,_token,n=1)=>page([{id:n===1?'req-b':'req-c',requisitionCode:`R${n}`,title:n===1?'选中岗位':'其他岗位',orgName:'合成部门',status:'open'}],n,11) as never);vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockResolvedValue(row({version:5,requisitionId:'req-b',requisitionTitle:'选中岗位'}));
 render(<CandidateProfile {...props}/>);await open();fireEvent.click(screen.getByRole('button',{name:'更换招聘需求'}));fireEvent.click(await screen.findByRole('button',{name:'R1 · 选中岗位 · 合成部门'}));fireEvent.click(screen.getByRole('button',{name:'需求选项下一页'}));await screen.findByRole('button',{name:'R2 · 其他岗位 · 合成部门'});expect(screen.getByText(/招聘需求：选中岗位 · 资料版本/)).toBeInTheDocument();change('更正原因','调整报名岗位');save();await screen.findByText('资料已保存，版本 5。');expect(vi.mocked(hrApi.saveRecruitmentCandidateProfile).mock.calls[0]![1]).toEqual({expectedVersion:4,changeReason:'调整报名岗位',requisitionId:'req-b'});
});
it('does not publish stale full history after exact current projection loses sensitive access',async()=>{
 let resolve!:(v:unknown)=>void;const full=row({sensitiveAvailable:true,mobile:'13800000000',email:null,identityNumber:null});vi.mocked(hrApi.recruitmentCandidateProfile).mockResolvedValueOnce(full).mockResolvedValueOnce(row({version:6}));vi.mocked(hrApi.recruitmentCandidateProfileHistory).mockReturnValueOnce(new Promise(r=>{resolve=r;}) as never);vi.mocked(hrApi.saveRecruitmentCandidateProfile).mockRejectedValueOnce({status:409,message:'Candidate changed; reload before saving'});render(<CandidateProfile {...props}/>);await open();change('姓名','草稿姓名');change('更正原因','更正');save();await screen.findByText(/服务器版本 6/);await act(async()=>resolve(page([{id:'old-full-history',before:full,after:{...full,version:5},changeReason:'旧完整记录',actorDisplayName:'合成人',occurredAt:'2026-10-11T01:00:00Z'}])));expect(screen.queryByText(/13800000000/)).not.toBeInTheDocument();expect(screen.queryByLabelText('手机号')).not.toBeInTheDocument();
});
