import {fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,it,expect,vi} from "vitest";
import {HrContractsClient} from "../../app/hr/contracts/HrContractsClient";
import {hrApi,type HrContractDetail,type HrEmployee} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",permissions:["hr:contract:read","hr:contract:manage"]}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
vi.mock("../../lib/hr-api",()=>({hrApi:{contracts:vi.fn(),contract:vi.fn(),employees:vi.fn(),contractTypes:vi.fn(),reviewContractInformation:vi.fn(),updateContract:vi.fn(),contractAction:vi.fn()}}));
const basic:HrContractDetail={id:"contract",version:7,employeeId:"employee",contractTypeId:"type",contractNo:"SYN-REVIEW",contractTypeName:"合成合同",startDate:"2090-01-01",endDate:null,status:"needs_review",isHistoricalImport:true,changes:[],actions:[]};
beforeEach(()=>{vi.clearAllMocks();state.user={id:"actor",permissions:["hr:contract:read","hr:contract:manage"]};vi.mocked(hrApi.contracts).mockResolvedValue({items:[basic],total:1,page:1,page_size:50});vi.mocked(hrApi.contract).mockResolvedValue(basic);vi.mocked(hrApi.employees).mockResolvedValue({items:[{id:"employee",employeeCode:"SYN",fullName:"Synthetic",employmentStatus:"active"} as HrEmployee],total:1,page:1,page_size:100});vi.mocked(hrApi.contractTypes).mockResolvedValue([{id:"type",typeCode:"SYN",typeName:"合成合同",isHistoricalImport:false}]);vi.mocked(hrApi.reviewContractInformation).mockResolvedValue({...basic,status:"draft",version:8});});
async function open(){fireEvent.click(await screen.findByRole("button",{name:"查看合同"}));await screen.findByRole("heading",{name:"SYN-REVIEW"});}
it("completes the same contract using the opened version without activating or leaking salary",async()=>{render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));fireEvent.click(screen.getByRole("button",{name:"补全并保存草稿"}));await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(1));expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]).toEqual(["contract",expect.objectContaining({expectedVersion:7,employeeId:"employee",contractNo:"SYN-REVIEW"}),"synthetic-token"]);expect(JSON.stringify(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]?.[1])).not.toContain('"baseSalary"');expect(hrApi.updateContract).not.toHaveBeenCalled();expect(hrApi.contractAction).not.toHaveBeenCalled();await screen.findByText("合同信息已补全并保存为草稿，请核对后确认生效。");});
it("retains the form and frozen version on conflict",async()=>{vi.mocked(hrApi.reviewContractInformation).mockRejectedValue(new Error("版本冲突"));render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));fireEvent.click(screen.getByRole("button",{name:"补全并保存草稿"}));await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(1));expect(await screen.findByRole("button",{name:"补全并保存草稿"})).toBeVisible();expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]?.[1]).toMatchObject({expectedVersion:7});});
it("requires a returned version rather than inventing one",async()=>{vi.mocked(hrApi.contract).mockResolvedValue({...basic,version:undefined});render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));await screen.findByText("请刷新合同详情后再补全信息。");expect(screen.queryByRole("button",{name:"补全并保存草稿"})).toBeNull();expect(hrApi.reviewContractInformation).not.toHaveBeenCalled();});
it("hides review for read-only users",async()=>{state.user={id:"actor",permissions:["hr:contract:read"]};render(<HrContractsClient/>);await open();expect(screen.queryByRole("button",{name:"补全合同信息"})).toBeNull();});
