import {act,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {CandidateInterviews} from "../../app/hr/recruitment/CandidateInterviews";
import {hrApi,type HrCandidateInterview} from "../../lib/hr-api";
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../lib/hr-api",()=>({hrApi:{recruitmentCandidateInterviews:vi.fn(),recruitmentCandidateInterview:vi.fn(),recruitmentCandidateInterviewHistory:vi.fn(),createRecruitmentCandidateInterview:vi.fn(),updateRecruitmentCandidateInterview:vi.fn()}}));
const row=(extra:Partial<HrCandidateInterview>={}):HrCandidateInterview=>({id:"interview-a",candidateId:"candidate-a",version:1,roundLabel:"初试",startsAt:"2026-10-12T01:00:00Z",endsAt:"2026-10-12T02:00:00Z",location:"会议室",interviewerName:"合成面试人",status:"scheduled",outcome:"pending",resultNotes:null,cancellationReason:null,updatedAt:"2026-10-11T01:00:00Z",...extra});
const page=<T,>(n=1,items:T[]=[],total=items.length)=>({items,total,page:n,page_size:10});
const props={candidateId:"candidate-a",canManage:true,disabled:false,onBusyChange:vi.fn()};
beforeEach(()=>{vi.resetAllMocks();vi.mocked(hrApi.recruitmentCandidateInterviews).mockResolvedValue(page(1,[row()]) as never);vi.mocked(hrApi.recruitmentCandidateInterviewHistory).mockImplementation(async(_a,_b,_t,n=1)=>page(n) as never);});
async function edit(){await waitFor(()=>expect(screen.getByRole("button",{name:"办理/更正"})).toBeEnabled());fireEvent.click(screen.getByRole("button",{name:"办理/更正"}));}
function change(label:string,value:string){fireEvent.change(screen.getByLabelText(label),{target:{value}});}
const save=()=>fireEvent.click(screen.getByRole("button",{name:"保存更正"}));
it("shows scoped records without write entries for read-only users",async()=>{render(<CandidateInterviews {...props} canManage={false}/>);await screen.findByText(/初试 · 已安排/);expect(screen.queryByRole("button",{name:"新建面试"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"办理\/更正"})).not.toBeInTheDocument();});
it("gates writes on invalid list receipts and restores independently",async()=>{vi.mocked(hrApi.recruitmentCandidateInterviews).mockResolvedValueOnce({items:[row({candidateId:"other"})],total:1,page:1,page_size:10} as never);render(<CandidateInterviews {...props}/>);await screen.findByRole("alert");expect(screen.getByRole("button",{name:"新建面试"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"重读面试列表"}));await edit();});
it("preserves an uncertain update's original key body and version across manual reread",async()=>{vi.mocked(hrApi.updateRecruitmentCandidateInterview).mockRejectedValueOnce(Error("lost receipt")).mockResolvedValueOnce(row({version:2,location:"新会议室"}));render(<CandidateInterviews {...props}/>);await edit();change("地点","新会议室");save();await screen.findByText(/面试保存失败或回执无效/);expect(screen.getByLabelText("地点")).toHaveValue("新会议室");save();await screen.findByText("面试已保存，版本 2。");const calls=vi.mocked(hrApi.updateRecruitmentCandidateInterview).mock.calls;expect(calls).toHaveLength(2);expect(calls[0]).toEqual(calls[1]);expect(calls[0]![2]).toMatchObject({expectedVersion:1,startsAt:"2026-10-12T09:00:00+08:00"});});
it("accepts minute-precision browser input as Beijing time on new scheduling",async()=>{vi.mocked(hrApi.createRecruitmentCandidateInterview).mockImplementation(async(_id,body)=>row({...body,id:"new-a",candidateId:"candidate-a",version:1,updatedAt:"2026-10-11T01:00:00Z"}) as never);render(<CandidateInterviews {...props}/>);await waitFor(()=>expect(screen.getByRole("button",{name:"新建面试"})).toBeEnabled());fireEvent.click(screen.getByRole("button",{name:"新建面试"}));change("轮次名称","复试");change("开始时间（北京时间）","2026-10-13T09:00");change("结束时间（北京时间）","2026-10-13T10:00");change("地点","视频会议");change("面试人姓名","合成负责人");fireEvent.submit(screen.getByRole("form",{name:"安排面试"}));await screen.findByText("面试已保存，版本 1。");expect(vi.mocked(hrApi.createRecruitmentCandidateInterview).mock.calls[0]![1]).toMatchObject({expectedVersion:0,startsAt:"2026-10-13T09:00:00+08:00",status:"scheduled",outcome:"pending",resultNotes:null,cancellationReason:null});});
it("blocks synchronous duplicate writes and parent operations while saving",async()=>{let resolve!:(v:HrCandidateInterview)=>void;vi.mocked(hrApi.updateRecruitmentCandidateInterview).mockReturnValue(new Promise(r=>{resolve=r;}));render(<CandidateInterviews {...props}/>);await edit();const button=screen.getByRole("button",{name:"保存更正"});act(()=>{fireEvent.click(button);fireEvent.click(button);});expect(hrApi.updateRecruitmentCandidateInterview).toHaveBeenCalledTimes(1);expect(props.onBusyChange).toHaveBeenCalledWith(true);expect(screen.getByLabelText("地点")).toBeDisabled();expect(screen.getByRole("button",{name:"取消编辑"})).toBeDisabled();await act(async()=>resolve(row({version:2})));expect(props.onBusyChange).toHaveBeenLastCalledWith(false);});
it("retains draft and rejects a wrong-record save receipt",async()=>{vi.mocked(hrApi.updateRecruitmentCandidateInterview).mockResolvedValue(row({id:"unrelated",version:2}));render(<CandidateInterviews {...props}/>);await edit();save();await screen.findByText(/面试保存失败或回执无效/);expect(screen.getByLabelText("轮次名称")).toHaveValue("初试");expect(screen.queryByText("面试已保存，版本 2。")).not.toBeInTheDocument();});
it("reads exact conflict record off-page and rebases only after explicit comparison acknowledgement",async()=>{vi.mocked(hrApi.updateRecruitmentCandidateInterview).mockRejectedValueOnce({status:409}).mockResolvedValueOnce(row({version:3,location:"我的草稿"}));vi.mocked(hrApi.recruitmentCandidateInterview).mockResolvedValue(row({version:2,location:"其他办理人会议室"}));render(<CandidateInterviews {...props}/>);await edit();change("地点","我的草稿");save();const region=await screen.findByRole("region",{name:"面试冲突比较"});await within(region).findByText("地点：其他办理人会议室");expect(screen.getByRole("button",{name:"保存更正"})).toBeDisabled();expect(screen.getByLabelText("地点")).toHaveValue("我的草稿");fireEvent.click(screen.getByRole("button",{name:"确认以草稿更新"}));save();await screen.findByText("面试已保存，版本 3。");const calls=vi.mocked(hrApi.updateRecruitmentCandidateInterview).mock.calls;expect(calls[1]![2]).toMatchObject({expectedVersion:2,location:"我的草稿"});expect(calls[1]![4]).not.toEqual(calls[0]![4]);expect(hrApi.recruitmentCandidateInterview).toHaveBeenCalledWith("candidate-a","interview-a","synthetic-token",expect.any(AbortSignal));});
it("renders actual history shape and pagination with all result fields and independent retries",async()=>{const {updatedAt:_unused,...snapshot}=row({status:"completed",outcome:"pass",resultNotes:"完整评估记录"});void _unused;vi.mocked(hrApi.recruitmentCandidateInterviewHistory).mockRejectedValueOnce(Error("offline")).mockImplementation(async(_a,_b,_t,n=1)=>page(n,[{...snapshot,id:`history-${n}`,interviewId:"interview-a",version:n,actorDisplayName:"合成办理人",occurredAt:"2026-10-11T01:00:00Z"}],11) as never);render(<CandidateInterviews {...props}/>);await edit();await screen.findByRole("button",{name:"重读面试历史"});expect(screen.getByLabelText("地点")).toBeEnabled();fireEvent.click(screen.getByRole("button",{name:"重读面试历史"}));await screen.findByText("面试记录：完整评估记录");fireEvent.click(screen.getByRole("button",{name:"下一页历史"}));await screen.findByText(/初试 · 已完成 · 版本 2/);fireEvent.click(screen.getByRole("button",{name:"上一页历史"}));await screen.findByText(/初试 · 已完成 · 版本 1/);expect(hrApi.recruitmentCandidateInterviewHistory).toHaveBeenLastCalledWith("candidate-a","interview-a","synthetic-token",1,10,expect.any(AbortSignal));});
it("requires complete result or cancellation reason and restricts terminal corrections",async()=>{render(<CandidateInterviews {...props}/>);await edit();change("面试状态","completed");fireEvent.submit(screen.getByRole("form",{name:"更正面试"}));await screen.findByText("完成面试须填写结论和非空记录。");expect(hrApi.updateRecruitmentCandidateInterview).not.toHaveBeenCalled();change("面试状态","cancelled");fireEvent.submit(screen.getByRole("form",{name:"更正面试"}));await screen.findByText("取消面试须填写非空原因。");});
it("ignores an earlier candidate's late list response",async()=>{let resolve!:(v:Awaited<ReturnType<typeof hrApi.recruitmentCandidateInterviews>>)=>void;vi.mocked(hrApi.recruitmentCandidateInterviews).mockImplementation(async id=>id==="candidate-a"?new Promise(r=>{resolve=r;}):page(1,[row({candidateId:"candidate-b",roundLabel:"新候选人复试"})]) as never);const view=render(<CandidateInterviews {...props}/>);view.rerender(<CandidateInterviews {...props} candidateId="candidate-b"/>);await screen.findByText(/新候选人复试/);await act(async()=>resolve(page(1,[row()])));expect(screen.queryByText(/初试 ·/)).not.toBeInTheDocument();});
