import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,it,expect,vi} from "vitest";
import {HrContractsClient} from "../../app/hr/contracts/HrContractsClient";
import {hrApi,type HrContractDetail,type HrEmployee} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",permissions:["hr:contract:read","hr:contract:manage"]}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
vi.mock("../../lib/hr-api",()=>({hrApi:{contracts:vi.fn(),contract:vi.fn(),employees:vi.fn(),contractTypes:vi.fn(),reviewContractInformation:vi.fn(),updateContract:vi.fn(),contractAction:vi.fn()}}));
const basic:HrContractDetail={id:"contract",version:7,employeeId:"employee",contractTypeId:"type",contractNo:"SYN-REVIEW",contractTypeName:"合成合同",startDate:"2090-01-01",endDate:null,status:"needs_review",isHistoricalImport:true,changes:[],actions:[]};
beforeEach(()=>{vi.clearAllMocks();state.user={id:"actor",permissions:["hr:contract:read","hr:contract:manage"]};vi.mocked(hrApi.contracts).mockResolvedValue({items:[basic],total:1,page:1,page_size:50});vi.mocked(hrApi.contract).mockResolvedValue(basic);vi.mocked(hrApi.employees).mockResolvedValue({items:[{id:"employee",employeeCode:"SYN",fullName:"Synthetic",employmentStatus:"active"} as HrEmployee],total:1,page:1,page_size:100});vi.mocked(hrApi.contractTypes).mockResolvedValue([{id:"type",typeCode:"SYN",typeName:"合成合同",isHistoricalImport:false}]);vi.mocked(hrApi.reviewContractInformation).mockResolvedValue({...basic,status:"draft",version:8});});
async function open(){fireEvent.click(await screen.findByRole("button",{name:"查看合同"}));await screen.findByRole("heading",{name:"SYN-REVIEW"});}
it("completes the same contract using the opened version without activating or leaking salary",async()=>{render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));fireEvent.click(screen.getByRole("button",{name:"补全并保存草稿"}));await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(1));expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]).toEqual(["contract",expect.objectContaining({expectedVersion:7,employeeId:"employee",contractNo:"SYN-REVIEW"}),"synthetic-token",expect.any(String)]);expect(JSON.stringify(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]?.[1])).not.toContain('"baseSalary"');expect(hrApi.updateContract).not.toHaveBeenCalled();expect(hrApi.contractAction).not.toHaveBeenCalled();await screen.findByText("合同信息已补全并保存为草稿，请核对后确认生效。");});
it("retains the form and frozen version on conflict",async()=>{vi.mocked(hrApi.reviewContractInformation).mockRejectedValue(new Error("版本冲突"));render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));fireEvent.click(screen.getByRole("button",{name:"补全并保存草稿"}));await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(1));expect(await screen.findByRole("button",{name:"补全并保存草稿"})).toBeVisible();expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]?.[1]).toMatchObject({expectedVersion:7});});
it("requires a returned version rather than inventing one",async()=>{vi.mocked(hrApi.contract).mockResolvedValue({...basic,version:undefined});render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));await screen.findByText("请刷新合同详情后再补全信息。");expect(screen.queryByRole("button",{name:"补全并保存草稿"})).toBeNull();expect(hrApi.reviewContractInformation).not.toHaveBeenCalled();});
it("hides review for read-only users",async()=>{state.user={id:"actor",permissions:["hr:contract:read"]};render(<HrContractsClient/>);await open();expect(screen.queryByRole("button",{name:"补全合同信息"})).toBeNull();});

async function reviewForm(){await open();fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));}
const submitReview=()=>fireEvent.click(screen.getByRole("button",{name:"补全并保存草稿"}));
it("retries an unknown write with the original body/key, but edits and completed reopened operations use new keys",async()=>{
 vi.mocked(hrApi.reviewContractInformation).mockRejectedValue(new Error("connection lost"));render(<HrContractsClient/>);await reviewForm();submitReview();await screen.findByText("connection lost");submitReview();await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(2));
 const first=vi.mocked(hrApi.reviewContractInformation).mock.calls[0]!;expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[1]).toEqual(first);
 fireEvent.change(screen.getByLabelText("办理备注"),{target:{value:"更正说明"}});submitReview();await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(3));const edited=vi.mocked(hrApi.reviewContractInformation).mock.calls[2]!;expect(edited[3]).not.toBe(first[3]);expect(edited[1]).toMatchObject({remark:"更正说明"});
 fireEvent.change(screen.getByLabelText("办理备注"),{target:{value:""}});vi.mocked(hrApi.reviewContractInformation).mockResolvedValue({...basic,status:"draft",version:8});submitReview();await screen.findByText("合同信息已补全并保存为草稿，请核对后确认生效。");const completed=vi.mocked(hrApi.reviewContractInformation).mock.calls[3]!;expect(completed[3]).not.toBe(first[3]);
 fireEvent.click(screen.getByRole("button",{name:"补全合同信息"}));submitReview();await waitFor(()=>expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(5));expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[4]![3]).not.toBe(completed[3]);
});
it("retains the actual receipt when post-save list refresh fails and retries only reading",async()=>{
 render(<HrContractsClient/>);await reviewForm();vi.mocked(hrApi.contracts).mockRejectedValue(new Error("read offline"));submitReview();await screen.findByText("合同 SYN-REVIEW · 草稿");await screen.findByText(/保存已成功，列表或详情未刷新/);expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(1);
 vi.mocked(hrApi.contracts).mockResolvedValue({items:[basic],total:1,page:1,page_size:50});fireEvent.click(screen.getByRole("button",{name:"刷新本页"}));await screen.findByRole("button",{name:"查看合同"});expect(screen.getByText("合同 SYN-REVIEW · 草稿")).toBeVisible();expect(hrApi.reviewContractInformation).toHaveBeenCalledTimes(1);
});
it.each(["account","unmount"])("freezes controls during write and suppresses old receipts after %s",async mode=>{
 let resolve!:(value:HrContractDetail)=>void;vi.mocked(hrApi.reviewContractInformation).mockReturnValue(new Promise(done=>{resolve=done;}));const view=render(<HrContractsClient/>);await reviewForm();submitReview();expect(screen.getByLabelText("合同编号")).toBeDisabled();expect(screen.getByLabelText("办理备注")).toBeDisabled();expect(screen.getByRole("button",{name:"新建合同"})).toBeDisabled();
 const reads=vi.mocked(hrApi.contracts).mock.calls.length;if(mode==="account"){state.user={...state.user,id:"other"};view.rerender(<HrContractsClient/>);await waitFor(()=>expect(hrApi.contracts).toHaveBeenCalledTimes(reads+2));}else view.unmount();
 const before=vi.mocked(hrApi.contracts).mock.calls.length;await act(async()=>{resolve({...basic,contractNo:"OLD-RECEIPT",status:"draft",version:8});});expect(screen.queryByText(/OLD-RECEIPT/)).toBeNull();expect(hrApi.contracts).toHaveBeenCalledTimes(before);
});

it("isolates contract action retries by action and selected record",async()=>{
 const confirm=vi.spyOn(window,"confirm").mockReturnValue(true),draft={...basic,status:"draft"};vi.mocked(hrApi.contracts).mockResolvedValue({items:[draft],total:1,page:1,page_size:50});vi.mocked(hrApi.contract).mockResolvedValue(draft);vi.mocked(hrApi.contractAction).mockRejectedValue(new Error("action offline"));
 try{render(<HrContractsClient/>);await open();fireEvent.click(screen.getByRole("button",{name:"确认生效"}));await screen.findByText("action offline");fireEvent.click(screen.getByRole("button",{name:"确认生效"}));await waitFor(()=>expect(hrApi.contractAction).toHaveBeenCalledTimes(2));const first=vi.mocked(hrApi.contractAction).mock.calls[0]!;expect(vi.mocked(hrApi.contractAction).mock.calls[1]).toEqual(first);
 fireEvent.click(screen.getByRole("button",{name:"取消草稿"}));await waitFor(()=>expect(hrApi.contractAction).toHaveBeenCalledTimes(3));expect(vi.mocked(hrApi.contractAction).mock.calls[2]![3]).not.toBe(first[3]);
 const other={...draft,id:"other-contract",contractNo:"SYN-OTHER"};vi.mocked(hrApi.contracts).mockResolvedValue({items:[other],total:1,page:1,page_size:50});vi.mocked(hrApi.contract).mockResolvedValue(other);fireEvent.click(screen.getByRole("button",{name:"刷新本页"}));fireEvent.click(await screen.findByRole("button",{name:"查看合同"}));await screen.findByRole("heading",{name:"SYN-OTHER"});fireEvent.click(screen.getByRole("button",{name:"确认生效"}));await waitFor(()=>expect(hrApi.contractAction).toHaveBeenCalledTimes(4));expect(vi.mocked(hrApi.contractAction).mock.calls[3]![0]).toBe("other-contract");expect(vi.mocked(hrApi.contractAction).mock.calls[3]![3]).not.toBe(first[3]);
 }finally{confirm.mockRestore();}
});

it("rejects a receipt for a different contract and retains the exact original retry",async()=>{
 vi.mocked(hrApi.reviewContractInformation).mockResolvedValueOnce({...basic,id:"wrong-contract",contractNo:"WRONG-RECEIPT",status:"draft"}).mockResolvedValue({...basic,status:"draft",version:8});render(<HrContractsClient/>);await reviewForm();submitReview();await screen.findByText("办理回执与当前请求不一致，请使用原请求重试。");expect(screen.queryByText(/WRONG-RECEIPT/)).toBeNull();expect(screen.queryByRole("heading",{name:"已提交回执"})).toBeNull();submitReview();await screen.findByText("合同 SYN-REVIEW · 草稿");expect(vi.mocked(hrApi.reviewContractInformation).mock.calls[1]).toEqual(vi.mocked(hrApi.reviewContractInformation).mock.calls[0]);
});
