import {beforeEach,expect,it,vi} from "vitest";
import {apiRequest,createIdempotencyKey} from "../../lib/api-client";
vi.mock("../../lib/api-client",()=>({apiRequest:vi.fn(),createIdempotencyKey:vi.fn()}));
import {hrApi} from "../../lib/hr-api";
beforeEach(()=>{vi.clearAllMocks();vi.mocked(apiRequest).mockResolvedValue({data:{}} as Awaited<ReturnType<typeof apiRequest>>);vi.mocked(createIdempotencyKey).mockReturnValue("generated-key");});
it("every departure operation forwards the original supplied request key",async()=>{
 const body={note:"Synthetic evidence"};
 await hrApi.createDepartureApplication(body,"token","original-key");await hrApi.updateDepartureApplication("a",body,"token","original-key");await hrApi.departureApplicationAction("a","resubmit","token","original-key");await hrApi.reviewDepartureApplication("a","return","Actual opinion","token","original-key");await hrApi.recordDepartureInterview("a",body,"token","original-key");await hrApi.recordDepartureSurvey("a",body,"token","original-key");await hrApi.recordDepartureHandover("a",body,"token","original-key");await hrApi.recordDepartureWage("a",body,"token","original-key");await hrApi.closeDepartureArchive("a",body,"token","original-key");await hrApi.applyDepartureApplication("a","token","original-key");
 expect(apiRequest).toHaveBeenCalledTimes(10);for(const call of vi.mocked(apiRequest).mock.calls)expect(call[1]).toEqual(expect.objectContaining({token:"token",idempotencyKey:"original-key"}));expect(vi.mocked(apiRequest).mock.calls.map(call=>call[0])).toEqual(["/hr/departure-applications","/hr/departure-applications/a","/hr/departure-applications/a/actions","/hr/departure-applications/a/review","/hr/departure-applications/a/interview","/hr/departure-applications/a/survey","/hr/departure-applications/a/handover","/hr/departure-applications/a/wage-settlement","/hr/departure-applications/a/archive","/hr/departure-applications/a/apply"]);expect(apiRequest).toHaveBeenNthCalledWith(4,"/hr/departure-applications/a/review",expect.objectContaining({body:{action:"return",comment:"Actual opinion"}}));expect(createIdempotencyKey).not.toHaveBeenCalled();
});
it("legacy callers retain generated keys",async()=>{await hrApi.createDepartureApplication({},"token");await hrApi.updateDepartureApplication("a",{},"token");await hrApi.departureApplicationAction("a","submit","token");await hrApi.reviewDepartureApplication("a","approve","","token");await hrApi.recordDepartureInterview("a",{},"token");await hrApi.recordDepartureSurvey("a",{},"token");await hrApi.recordDepartureHandover("a",{},"token");await hrApi.recordDepartureWage("a",{},"token");await hrApi.closeDepartureArchive("a",{},"token");await hrApi.applyDepartureApplication("a","token");expect(vi.mocked(createIdempotencyKey).mock.calls.map(call=>call[0])).toEqual(["hr-departure-create","hr-departure-update","hr-departure-submit","hr-departure-approve","hr-departure-interview","hr-departure-survey","hr-departure-handover","hr-departure-wage","hr-departure-archive","hr-departure-apply"]);for(const call of vi.mocked(apiRequest).mock.calls)expect(call[1]).toEqual(expect.objectContaining({idempotencyKey:"generated-key"}));});
