import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrEmployeesClient} from "../../app/hr/employees/HrEmployeesClient";
import {hrApi,type HrEmployee} from "../../lib/hr-api";
const auth=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>auth.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../lib/hr-api",()=>({hrApi:{employees:vi.fn(),employee:vi.fn(),transition:vi.fn(),createEmployee:vi.fn(),directoryOptions:vi.fn(),positions:vi.fn()}}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
const employee=(id="employee-1",status="probation"):HrEmployee=>({id,employeeCode:"SYN-"+id,fullName:"合成员工"+id,userId:null,primaryOrgId:"org",positionId:null,managerEmployeeId:"manager",employmentType:"full_time",employmentStatus:status,legacyJobstateCode:null,legacyJobstateName:null,hireDate:"2020-01-01",departureDate:null,workLocation:null,workMobile:null,workEmail:null});
let current:HrEmployee;
beforeEach(()=>{vi.resetAllMocks();current=employee();auth.user={id:"actor",park_id:"park",permissions:[H.HR_EMPLOYEES_PAGE,H.HR_EMPLOYEE_READ,H.HR_EMPLOYMENT_TRANSITION]};vi.mocked(hrApi.employees).mockImplementation(async(_t,p=1,size=50,filters)=>({items:Object.hasOwn(filters??{},"status")?[current]:[employee("manager","active")],total:1,page:p,page_size:size}));vi.mocked(hrApi.employee).mockImplementation(async()=>current);vi.mocked(hrApi.transition).mockImplementation(async()=>{current={...current,employmentStatus:"active"};return current});vi.mocked(hrApi.directoryOptions).mockResolvedValue({orgs:[{id:"org",orgCode:"SYN",orgName:"合成部门",status:"active"}],users:[]});vi.mocked(hrApi.positions).mockResolvedValue([]);vi.mocked(hrApi.createEmployee).mockResolvedValue(employee("created","preboarding"));});
async function openTransition(){const view=render(<HrEmployeesClient/>);fireEvent.click(await screen.findByRole("button",{name:"查看与办理"}));await screen.findByRole("heading",{name:"合成员工employee-1 · 员工详情"});return view;}
const transitionForm=()=>screen.getByRole("button",{name:"确认办理并留痕"}).closest("form")!;
const change=(label:string,value:string)=>fireEvent.change(screen.getByLabelText(label),{target:{value}});
function fillTransition(){change("生效日期","2026-10-09");change("办理原因","合成业务办理原因");}
async function openCreate(){auth.user.permissions.push(H.HR_EMPLOYEE_MANAGE);const view=render(<HrEmployeesClient/>);await screen.findByRole("button",{name:"查看与办理"});fireEvent.click(screen.getByRole("button",{name:"新增员工"}));change("员工编号","SYN-NEW");change("姓名","合成新员工");change("预计入职日期","2026-10-10");change("工作地点","合成办公地");return view;}
const createForm=()=>screen.getByRole("button",{name:"保存待入职员工"}).closest("form")!;
it("failed employee creation retains all entered fields and success closes it only after retry",async()=>{vi.mocked(hrApi.createEmployee).mockRejectedValueOnce(new Error("合成创建失败"));await openCreate();const form=createForm();fireEvent.submit(form);await screen.findByText("合成创建失败");expect(screen.getByLabelText("员工编号")).toHaveValue("SYN-NEW");expect(screen.getByLabelText("姓名")).toHaveValue("合成新员工");expect(screen.getByLabelText("预计入职日期")).toHaveValue("2026-10-10");fireEvent.submit(form);await screen.findByText("待入职员工已创建，可继续办理入职。");expect(screen.queryByRole("button",{name:"保存待入职员工"})).toBeNull();expect(hrApi.createEmployee).toHaveBeenCalledTimes(2);expect(hrApi.createEmployee).toHaveBeenLastCalledWith(expect.objectContaining({employeeCode:"SYN-NEW",fullName:"合成新员工",hireDate:"2026-10-10",employmentStatus:"preboarding"}),"synthetic-token");});
it("employee creation commits before failed list refresh and cannot repeat from an old form",async()=>{await openCreate();vi.mocked(hrApi.employees).mockRejectedValueOnce(new Error("合成读取失败"));fireEvent.submit(createForm());await screen.findByText("待入职员工已创建，可继续办理入职。");await screen.findByText(/加载员工档案失败/);expect(screen.queryByRole("button",{name:"保存待入职员工"})).toBeNull();expect(hrApi.createEmployee).toHaveBeenCalledTimes(1);});
it("creation has one synchronous writer and locks its fields and directory until saved",async()=>{let done!:(value:HrEmployee)=>void;vi.mocked(hrApi.createEmployee).mockImplementationOnce(()=>new Promise(resolve=>{done=resolve}));await openCreate();const form=createForm();fireEvent.submit(form);fireEvent.submit(form);expect(hrApi.createEmployee).toHaveBeenCalledTimes(1);expect(screen.getByLabelText("姓名")).toBeDisabled();expect(screen.getByLabelText("搜索员工")).toBeDisabled();expect(screen.getByRole("button",{name:"收起新增"})).toBeDisabled();await act(async()=>done(employee("created","preboarding")));await screen.findByText("待入职员工已创建，可继续办理入职。");});
it("failed transition retains date and reason then retries exact employee and action",async()=>{vi.mocked(hrApi.transition).mockRejectedValueOnce(new Error("合成任职失败"));await openTransition();fillTransition();const form=transitionForm();fireEvent.submit(form);await screen.findByText("合成任职失败");expect(screen.getByLabelText("生效日期")).toHaveValue("2026-10-09");expect(screen.getByLabelText("办理原因")).toHaveValue("合成业务办理原因");fireEvent.submit(form);await screen.findByText("任职变动已保存并留痕。");expect(hrApi.transition).toHaveBeenCalledTimes(2);expect(hrApi.transition).toHaveBeenLastCalledWith("employee-1",{action:"confirm_employment",effectiveDate:"2026-10-09",reason:"合成业务办理原因"},"synthetic-token");});
it("pending transfer locks manager search and selection with one exact write",async()=>{current=employee("employee-1","active");let done!:(value:HrEmployee)=>void;vi.mocked(hrApi.transition).mockImplementationOnce(()=>new Promise(resolve=>{done=resolve}));await openTransition();await waitFor(()=>expect(screen.getByRole("button",{name:"确认办理并留痕"})).toBeEnabled());fillTransition();const form=transitionForm();fireEvent.submit(form);fireEvent.submit(form);expect(hrApi.transition).toHaveBeenCalledTimes(1);expect(screen.getByRole("searchbox",{name:"搜索上级候选"})).toBeDisabled();expect(screen.getByRole("combobox",{name:"新直属上级"})).toBeDisabled();expect(screen.getByLabelText("生效日期")).toBeDisabled();expect(screen.getByRole("button",{name:"刷新本页"})).toBeDisabled();expect(screen.getByRole("button",{name:"查看与办理"})).toBeDisabled();expect(vi.mocked(hrApi.transition).mock.calls[0]![1]).toEqual({action:"transfer",effectiveDate:"2026-10-09",reason:"合成业务办理原因",primaryOrgId:undefined,positionId:undefined,managerEmployeeId:undefined});await act(async()=>done(current));await screen.findByText("任职变动已保存并留痕。");});
it("a committed transition remains successful when list refresh fails",async()=>{await openTransition();fillTransition();vi.mocked(hrApi.employees).mockRejectedValueOnce(new Error("合成刷新失败"));fireEvent.submit(transitionForm());await screen.findByText("任职变动已保存并留痕。");await screen.findByText(/加载员工档案失败/);expect(screen.queryByRole("button",{name:"确认办理并留痕"})).toBeNull();expect(hrApi.transition).toHaveBeenCalledTimes(1);});
it("direct employee navigation preserves committed status when detail refresh fails",async()=>{render(<HrEmployeesClient employeeId="employee-1"/>);await screen.findByRole("heading",{name:"合成员工employee-1 · 员工详情"});fillTransition();vi.mocked(hrApi.employee).mockRejectedValueOnce(new Error("合成详情失败"));fireEvent.submit(transitionForm());await screen.findByText("任职变动已保存并留痕。");await screen.findByText(/加载员工详情失败/);expect(screen.queryByRole("button",{name:"确认办理并留痕"})).toBeNull();expect(hrApi.employees).not.toHaveBeenCalled();});
it("identity replacement drops pending drafts and prevents old transition reload",async()=>{let done!:(value:HrEmployee)=>void;vi.mocked(hrApi.transition).mockImplementationOnce(()=>new Promise(resolve=>{done=resolve}));const view=await openTransition();fillTransition();fireEvent.submit(transitionForm());auth.user={...auth.user,park_id:"other"};view.rerender(<HrEmployeesClient/>);await screen.findByRole("button",{name:"查看与办理"});const reads=vi.mocked(hrApi.employees).mock.calls.length;await act(async()=>done(employee()));expect(hrApi.employees).toHaveBeenCalledTimes(reads);expect(screen.queryByText("任职变动已保存并留痕。")).toBeNull();expect(screen.queryByRole("button",{name:"确认办理并留痕"})).toBeNull();});
it("unmounted employee creation does not reload the departed scope",async()=>{let done!:(value:HrEmployee)=>void;vi.mocked(hrApi.createEmployee).mockImplementationOnce(()=>new Promise(resolve=>{done=resolve}));const view=await openCreate();fireEvent.submit(createForm());const reads=vi.mocked(hrApi.employees).mock.calls.length;view.unmount();await act(async()=>done(employee("created","preboarding")));expect(hrApi.employees).toHaveBeenCalledTimes(reads);});
