import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,it,expect,vi} from "vitest";
import {EmployeeDirectoryExport} from "../../app/hr/employees/EmployeeDirectoryExport";
import type * as ExportModule from "../../app/hr/employees/employee-directory-export";
import {collectEmployeeDirectory,employeeDirectoryCsv,downloadEmployeeDirectory} from "../../app/hr/employees/employee-directory-export";
import {hrApi,type HrEmployee} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",permissions:["hr:employee:read"]}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../lib/hr-api",()=>({hrApi:{employees:vi.fn()}}));
vi.mock("../../app/hr/employees/employee-directory-export",async importOriginal=>({...await importOriginal<typeof ExportModule>(),downloadEmployeeDirectory:vi.fn()}));
const employee=(i:number)=>({id:`synthetic-${i}`,employeeCode:`SYN-${i}`,fullName:`合成员工${i}`,employmentType:"full_time",employmentStatus:"active",workLocation:"合成园区",hireDate:null,departureDate:null,userId:null} as HrEmployee);
const all=Array.from({length:120},(_,i)=>employee(i));
function page(n:number,rows=all){return {items:rows.slice((n-1)*50,n*50),total:rows.length,page:n,page_size:50};}
beforeEach(()=>{vi.clearAllMocks();state.user={id:"actor",permissions:["hr:employee:read"]};vi.mocked(hrApi.employees).mockImplementation(async(_token,n)=>page(n??1));});
it("collects every matched page and rechecks the first page",async()=>{const fetched:number[]=[];const result=await collectEmployeeDirectory(async n=>{fetched.push(n);return page(n)},()=>true);expect(result).toHaveLength(120);expect(fetched).toEqual([1,2,3,1]);});
it("exports an empty match as headers and rejects partial, repeated or changing pages",async()=>{
 expect(await collectEmployeeDirectory(async n=>page(n,[]),()=>true)).toEqual([]);
 for(const bad of [{...page(2),total:119},{...page(2),items:page(2).items.slice(1)},{...page(2),items:[employee(0),...page(2).items.slice(1)]},{...page(2),page_size:100}])await expect(collectEmployeeDirectory(async n=>n===1?page(1):bad,()=>true)).rejects.toThrow();
 let count=0;await expect(collectEmployeeDirectory(async n=>++count===4?{...page(1),items:[{...employee(0),fullName:"变化"},...page(1).items.slice(1)]}:page(n),()=>true)).rejects.toThrow("发生变化");
 await expect(collectEmployeeDirectory(async()=>({...page(1),total:5001}),()=>true)).rejects.toThrow("5000");
});
it("does not turn late responses or failed later pages into a partial file",async()=>{expect(await collectEmployeeDirectory(async n=>page(n),()=>false)).toBeNull();await expect(collectEmployeeDirectory(async n=>{if(n===2)throw new Error("synthetic failure");return page(n)},()=>true)).rejects.toThrow("synthetic failure");});
it("CSV keeps source text, protects formulas and includes only directory columns",()=>{const csv=employeeDirectoryCsv([{...employee(0),fullName:'=HYPERLINK("synthetic")',workLocation:"逗号,换行\n位置",employmentType:"自定义用工",workMobile:"SHOULD-NOT-EXPORT"}]);expect(csv.startsWith("\uFEFF")).toBe(true);expect(csv).toContain('"\'=HYPERLINK(""synthetic"")"');expect(csv).toContain('"逗号,换行\n位置"');expect(csv).toContain("自定义用工");expect(csv).not.toContain("SHOULD-NOT-EXPORT");expect(csv).not.toContain("synthetic-0");});
it("reuses current filters and signal, prevents duplicate clicks, downloads only complete results",async()=>{render(<EmployeeDirectoryExport keyword="合成" status="active" orgId="org-1"/>);const button=screen.getByRole("button",{name:"导出筛选员工"});fireEvent.click(button);fireEvent.click(button);await screen.findByText("已导出 120 条匹配员工记录。");expect(hrApi.employees).toHaveBeenCalledTimes(4);for(const call of vi.mocked(hrApi.employees).mock.calls){expect(call.slice(0,1)).toEqual(["synthetic-token"]);expect(call[2]).toBe(50);expect(call[3]).toEqual({keyword:"合成",status:"active",orgId:"org-1"});expect(call[4]).toBeInstanceOf(AbortSignal);}expect(downloadEmployeeDirectory).toHaveBeenCalledTimes(1);});
it("filter, organization and account changes cancel pending requests and suppress late download",async()=>{let resolve:(value:ReturnType<typeof page>)=>void=()=>{};vi.mocked(hrApi.employees).mockImplementation(()=>new Promise(done=>{resolve=done}));const {rerender}=render(<EmployeeDirectoryExport keyword="旧" status="active" orgId="org-old"/>);fireEvent.click(screen.getByRole("button",{name:"导出筛选员工"}));const signal=vi.mocked(hrApi.employees).mock.calls[0]?.[4];rerender(<EmployeeDirectoryExport keyword="新" status="active" orgId="org-old"/>);expect(signal?.aborted).toBe(true);await act(async()=>resolve(page(1)));expect(downloadEmployeeDirectory).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"导出筛选员工"}));const second=vi.mocked(hrApi.employees).mock.calls[1]?.[4];rerender(<EmployeeDirectoryExport keyword="新" status="active" orgId="org-new"/>);expect(second?.aborted).toBe(true);await act(async()=>resolve(page(1)));expect(downloadEmployeeDirectory).not.toHaveBeenCalled();fireEvent.click(screen.getByRole("button",{name:"导出筛选员工"}));const third=vi.mocked(hrApi.employees).mock.calls[2]?.[4];state.user={id:"other",permissions:["hr:employee:read"]};rerender(<EmployeeDirectoryExport keyword="新" status="active" orgId="org-new"/>);expect(third?.aborted).toBe(true);await act(async()=>resolve(page(1)));expect(downloadEmployeeDirectory).not.toHaveBeenCalled();});
it("hides export for a self-only account and reports failures without downloading",async()=>{state.user={id:"actor",permissions:["hr:employee:self_read"]};const {rerender}=render(<EmployeeDirectoryExport keyword="" status=""/>);expect(screen.queryByRole("button",{name:"导出筛选员工"})).toBeNull();state.user={id:"actor",permissions:["hr:employee:team_read"]};vi.mocked(hrApi.employees).mockRejectedValue(new Error("范围拒绝"));rerender(<EmployeeDirectoryExport keyword="" status=""/>);fireEvent.click(screen.getByRole("button",{name:"导出筛选员工"}));await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("范围拒绝"));expect(downloadEmployeeDirectory).not.toHaveBeenCalled();});
