import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {useState} from 'react';
import {expect,it,vi} from 'vitest';
import {FeedbackReferencePicker,type FeedbackPageReader} from '../../app/hr/feedback-360/FeedbackReferencePicker';
const row={id:'first',name:'合成一'},next={id:'next',name:'合成后续'},valid=(r:typeof row)=>typeof r.name==='string';
const page=(items:typeof row[],p=1,total=items.length)=>({items,page:p,page_size:20,total});
function Harness({read,initial=[]}:{read:FeedbackPageReader<typeof row>;initial?:typeof row[]}){const [selected,setSelected]=useState(initial),[ready,setReady]=useState(false);return <><FeedbackReferencePicker label="对象" references={{read,valid,label:r=>r.name}} selected={selected} onChange={setSelected} onReady={setReady} multiple/><button disabled={!ready||!selected.length}>保存</button></>;}
it('malformed candidate page disables only the picker and retries without clearing retained choices',async()=>{const read=vi.fn().mockResolvedValueOnce(page([row])).mockResolvedValueOnce({...page([next]),page_size:100}).mockResolvedValue(page([next]));render(<Harness read={read}/>);fireEvent.click(await screen.findByRole('checkbox',{name:'合成一'}));fireEvent.change(screen.getByRole('searchbox'),{target:{value:'后续'}});fireEvent.click(screen.getByRole('button',{name:'搜索对象'}));await screen.findByText('对象：360候选分页响应无效，请重试。');expect(screen.getByRole('button',{name:'保存'})).toBeDisabled();expect(screen.getByLabelText('已选对象')).toHaveTextContent('合成一');expect(screen.queryByRole('checkbox')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'重试对象'}));await screen.findByRole('checkbox',{name:'合成后续'});await waitFor(()=>expect(screen.getByRole('button',{name:'保存'})).toBeEnabled());});
it('slower superseded search cannot restore old candidates',async()=>{let finish:(v:ReturnType<typeof page>)=>void=()=>{};let oldSignal:AbortSignal|undefined;const read=vi.fn().mockResolvedValueOnce(page([row])).mockImplementationOnce((_p,_k,s)=>{oldSignal=s;return new Promise(resolve=>{finish=resolve;});}).mockResolvedValue(page([next]));render(<Harness read={read}/>);await screen.findByRole('checkbox',{name:'合成一'});fireEvent.change(screen.getByRole('searchbox'),{target:{value:'旧查询'}});fireEvent.click(screen.getByRole('button',{name:'搜索对象'}));await waitFor(()=>expect(read).toHaveBeenCalledTimes(2));fireEvent.change(screen.getByRole('searchbox'),{target:{value:'新查询'}});fireEvent.click(screen.getByRole('button',{name:'搜索对象'}));await screen.findByRole('checkbox',{name:'合成后续'});expect(oldSignal?.aborted).toBe(true);await act(async()=>finish(page([row])));expect(screen.queryByRole('checkbox',{name:'合成一'})).toBeNull();expect(screen.getByRole('checkbox',{name:'合成后续'})).toBeInTheDocument();});
it('duplicate identities fail closed and a cycle never accepts selection number501',async()=>{const read=vi.fn().mockResolvedValueOnce(page([row,row])).mockResolvedValue(page([next]));const selected=Array.from({length:500},(_,i)=>({id:`e${i}`,name:`合成${i}`}));render(<Harness read={read} initial={selected}/>);await screen.findByText('对象：360候选分页响应无效，请重试。');fireEvent.click(screen.getByRole('button',{name:'重试对象'}));fireEvent.click(await screen.findByRole('checkbox',{name:'合成后续'}));await screen.findByText('每个周期最多选择500名评价对象，请先移除已选对象。');expect(screen.getByRole('checkbox',{name:'合成后续'})).not.toBeChecked();});
