import {beforeEach,expect,it,vi} from "vitest";
import {hrApi} from "../../lib/hr-api";
import {apiRequest,createIdempotencyKey} from "../../lib/api-client";
vi.mock("../../lib/api-client",()=>({apiRequest:vi.fn(),createIdempotencyKey:vi.fn()}));
beforeEach(()=>{vi.clearAllMocks();vi.mocked(apiRequest).mockResolvedValue({data:{}} as Awaited<ReturnType<typeof apiRequest>>);vi.mocked(createIdempotencyKey).mockReturnValue('generated-key');});
it('cycle operation read carries cancellation and no write key',async()=>{const signal=new AbortController().signal;await hrApi.feedback360CycleContext('synthetic-token',signal);expect(apiRequest).toHaveBeenCalledWith('/hr/feedback360-v2/cycles/operation-context',{token:'synthetic-token',signal});expect(createIdempotencyKey).not.toHaveBeenCalled();});
it('all seven operation adapters preserve caller retry keys and exact bodies',async()=>{const body={synthetic:true};await hrApi.createFeedback360Cycle(body,'synthetic-token','cycle-key');await hrApi.activateFeedback360Cycle('cycle','synthetic-token','activate-key');await hrApi.nominateFeedback360(body,'synthetic-token','nominate-key');await hrApi.decideFeedback360Nomination('nomination',body,'synthetic-token','decision-key');await hrApi.submitFeedback360('task',body,'synthetic-token','answer-key');await hrApi.closeFeedback360Subject('subject','synthetic-token','close-key');await hrApi.publishFeedback360Result('subject','synthetic-token','publish-key');const calls=[['cycles','cycle-key',body],['cycles/cycle/activate','activate-key',undefined],['nominations','nominate-key',body],['nominations/nomination/decision','decision-key',body],['assignments/task/submit','answer-key',body],['subjects/subject/close','close-key',undefined],['subjects/subject/publish','publish-key',undefined]] as const;calls.forEach(([path,key,body],i)=>expect(apiRequest).toHaveBeenNthCalledWith(i+1,`/hr/feedback360-v2/${path}`,{method:'POST',token:'synthetic-token',idempotencyKey:key,...(body?{body}:{})}));expect(createIdempotencyKey).not.toHaveBeenCalled();});
it('existing callers without a key still receive a generated key',async()=>{await hrApi.submitFeedback360('task',{answers:[]},'synthetic-token');expect(createIdempotencyKey).toHaveBeenCalledWith('hr-feedback360-submit');expect(apiRequest).toHaveBeenCalledWith('/hr/feedback360-v2/assignments/task/submit',expect.objectContaining({idempotencyKey:'generated-key'}));});
it('operation candidates use bounded exact-purpose queries with encoded literal search and cancellation',async()=>{const signal=new AbortController().signal;await hrApi.feedback360CycleOptions('synthetic-token',signal);await hrApi.feedback360EmployeeOptions(31,' A_%\\ ','synthetic-token',signal);await hrApi.feedback360SubjectOptions('publish',2,' 周期 & 601 ','synthetic-token',signal);expect(apiRequest).toHaveBeenNthCalledWith(1,'/hr/feedback360-v2/cycle-options',{token:'synthetic-token',signal});expect(apiRequest).toHaveBeenNthCalledWith(2,'/hr/feedback360-v2/employee-options?page=31&page_size=20&keyword=A_%25%5C',{token:'synthetic-token',signal});expect(apiRequest).toHaveBeenNthCalledWith(3,'/hr/feedback360-v2/subject-options?purpose=publish&page=2&page_size=20&keyword=%E5%91%A8%E6%9C%9F+%26+601',{token:'synthetic-token',signal});expect(createIdempotencyKey).not.toHaveBeenCalled();});
