import {act,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrFeedbackClient} from "../../app/hr/feedback-360/HrFeedbackClient";
const state=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]},api:{myFeedback360Assignments:vi.fn(),feedback360Cycles:vi.fn(),feedback360CycleContext:vi.fn(),feedback360Options:vi.fn(),feedback360CycleOptions:vi.fn(),feedback360EmployeeOptions:vi.fn(),feedback360SubjectOptions:vi.fn(),feedback360PendingNominations:vi.fn(),feedback360Results:vi.fn(),createFeedback360Cycle:vi.fn(),activateFeedback360Cycle:vi.fn(),nominateFeedback360:vi.fn(),decideFeedback360Nomination:vi.fn(),submitFeedback360:vi.fn(),closeFeedback360Subject:vi.fn(),publishFeedback360Result:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));
vi.mock("../../app/hr/feedback-360/FeedbackConfiguration",()=>({FeedbackConfiguration:()=>null}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=><>{children}</>}));
const task={id:"task",cycleName:"合成周期",subjectName:"合成对象",relationType:"peer",status:"pending",responseEnd:"2026-10-31",questionnaire:{questions:[{code:"rating",text:"合成评分",type:"rating",required:true,dimensionCode:"d"},{code:"optional",text:"合成选填",type:"text",required:false,dimensionCode:"d"}]}};
const cycle={id:"cycle",cycleCode:"SYN",cycleName:"合成周期",nominationEnd:"2026-10-20",responseEnd:"2026-10-31",status:"draft",subjectCount:1,minimumAnonymousResponses:3};
const options={employees:[{id:"employee",fullName:"合成员工",employeeCode:"SYN"}],models:[{id:"model",modelName:"合成模型",versionName:"v1"}],questionnaires:[{id:"questionnaire",questionnaireName:"合成问卷",versionName:"v1",modelVersionId:"model"},{id:"other",questionnaireName:"不匹配问卷",versionName:"v1",modelVersionId:"other-model"}],subjects:[{id:"subject",cycleCode:"SYN",employeeCode:"SYN",cycleName:"合成周期",subjectName:"合成对象",status:"nominating"}]};
function change(f:HTMLElement,name:string,value:string){fireEvent.change(f.querySelector(`[name="${name}"]`)!,{target:{value}});}
beforeEach(()=>{Object.values(state.api).forEach(m=>m.mockReset());state.user={id:"actor",park_id:"park",permissions:[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_RESPOND]};state.api.myFeedback360Assignments.mockResolvedValue([task]);state.api.feedback360Cycles.mockResolvedValue([cycle]);state.api.feedback360CycleContext.mockResolvedValue([cycle]);state.api.feedback360Options.mockResolvedValue(options);state.api.feedback360CycleOptions.mockResolvedValue({models:options.models,questionnaires:options.questionnaires});state.api.feedback360EmployeeOptions.mockResolvedValue({items:options.employees,total:1,page:1,page_size:20});state.api.feedback360SubjectOptions.mockResolvedValue({items:options.subjects,total:1,page:1,page_size:20});state.api.feedback360PendingNominations.mockResolvedValue([{id:"nomination",subjectId:"subject",cycleName:"合成周期",subjectName:"合成对象",nomineeName:"合成评价人",relationType:"peer",status:"pending",canDecide:true}]);state.api.feedback360Results.mockResolvedValue([]);for(const k of ['createFeedback360Cycle','activateFeedback360Cycle','nominateFeedback360','decideFeedback360Nomination','submitFeedback360','closeFeedback360Subject','publishFeedback360Result'] as const)state.api[k].mockResolvedValue({});});
it("respond-only uses own task route and preserves zero, optional blank and unknown retry key",async()=>{state.api.submitFeedback360.mockRejectedValueOnce(new Error("合成网络中断"));render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'开始评价'}));const f=screen.getByRole('form',{name:'本人360答卷'});change(f,'rating','0');fireEvent.submit(f);await screen.findByText('合成网络中断');expect(f.querySelector('[name="rating"]')).toHaveValue(0);const key=state.api.submitFeedback360.mock.calls[0]![3];fireEvent.submit(f);await screen.findByText('360评价已提交，内容不可修改。');expect(state.api.submitFeedback360).toHaveBeenLastCalledWith('task',{answers:[{questionCode:'rating',score:0}]},'synthetic-token',key);expect(screen.queryByRole('form',{name:'本人360答卷'})).toBeNull();expect(state.api.feedback360Options).not.toHaveBeenCalled();expect(state.api.feedback360Cycles).not.toHaveBeenCalled();});
it("an independent options failure does not block own task",async()=>{state.user.permissions.push(H.HR_FEEDBACK_CYCLE_MANAGE);state.api.feedback360CycleOptions.mockRejectedValue(new Error('合成选项拒绝'));render(<HrFeedbackClient/>);await screen.findByText('业务选项：合成选项拒绝');fireEvent.click(await screen.findByRole('button',{name:'开始评价'}));expect(screen.getByRole('form',{name:'本人360答卷'})).toBeInTheDocument();expect(screen.getByRole('button',{name:'新建周期'})).toBeDisabled();expect(screen.getByRole('button',{name:'启动提名'})).toBeEnabled();});
it("cycle-only manager uses operation context without ordinary read and activates",async()=>{state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_CYCLE_MANAGE];render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'启动提名'}));fireEvent.submit(screen.getByRole('form',{name:'360状态办理'}));await screen.findByText('周期已启动提名。');expect(state.api.activateFeedback360Cycle).toHaveBeenCalledWith('cycle','synthetic-token',expect.any(String));expect(state.api.feedback360Cycles).not.toHaveBeenCalled();expect(state.api.myFeedback360Assignments).not.toHaveBeenCalled();});
it("failed cycle creation retains matching versions and all draft values",async()=>{state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_CYCLE_MANAGE];state.api.createFeedback360Cycle.mockRejectedValueOnce(new Error('合成创建失败'));render(<HrFeedbackClient/>);await waitFor(()=>expect(screen.getByRole('button',{name:'新建周期'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'新建周期'}));const f=screen.getByRole('form',{name:'创建360周期'});for(const [k,v] of Object.entries({cycleCode:'SYN-NEW',cycleName:'合成新周期',modelVersionId:'model',questionnaireVersionId:'questionnaire',nominationEnd:'2026-10-20',responseEnd:'2026-10-31'}))change(f,k,v);expect(f.querySelector('option[value="other"]')).toBeNull();fireEvent.click(await screen.findByRole("checkbox",{name:"合成员工 · SYN"}));fireEvent.submit(f);await screen.findByText('合成创建失败');expect(f.querySelector('[name="cycleName"]')).toHaveValue('合成新周期');expect(f.querySelector('[name="questionnaireVersionId"]')).toHaveValue('questionnaire');const key=state.api.createFeedback360Cycle.mock.calls[0]![2];fireEvent.submit(f);await screen.findByText('360周期已创建，请核对后启动提名。');expect(state.api.createFeedback360Cycle).toHaveBeenLastCalledWith(expect.objectContaining({employeeIds:['employee'],minimumAnonymousResponses:3,modelVersionId:'model',questionnaireVersionId:'questionnaire'}),'synthetic-token',key);});
it("failed nomination preserves reviewer and relationship",async()=>{state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_NOMINATE];state.api.nominateFeedback360.mockRejectedValueOnce(new Error('合成提名失败'));render(<HrFeedbackClient/>);await waitFor(()=>expect(screen.getByRole('button',{name:'发起提名'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'发起提名'}));const f=screen.getByRole('form',{name:'评价人提名'});fireEvent.click(await screen.findByRole("checkbox",{name:"合成周期 · SYN · 合成对象 · SYN"}));fireEvent.click(await screen.findByRole("checkbox",{name:"合成员工 · SYN"}));expect(f.querySelector('option[value="collaborator"]')).toBeNull();change(f,'relationType','peer');fireEvent.submit(f);await screen.findByText('合成提名失败');expect(screen.getByRole("checkbox",{name:"合成员工 · SYN"})).toBeChecked();const key=state.api.nominateFeedback360.mock.calls[0]![2];fireEvent.submit(f);await screen.findByText('评价人提名已提交。');expect(state.api.nominateFeedback360).toHaveBeenLastCalledWith({subjectId:'subject',nomineeEmployeeId:'employee',relationType:'peer'},'synthetic-token',key);});
it("real rejection reason survives failure instead of using fixed text",async()=>{state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_NOMINATION_REVIEW];state.api.decideFeedback360Nomination.mockRejectedValueOnce(new Error('合成拒绝失败'));render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'拒绝'}));const f=screen.getByRole('form',{name:'360状态办理'});change(f,'reason','业务关系不符合本次评价范围');fireEvent.submit(f);await screen.findByText('合成拒绝失败');expect(f.querySelector('[name="reason"]')).toHaveValue('业务关系不符合本次评价范围');fireEvent.submit(f);await screen.findByText('提名已拒绝。');expect(state.api.decideFeedback360Nomination).toHaveBeenLastCalledWith('nomination',{decision:'reject',reason:'业务关系不符合本次评价范围'},'synthetic-token',expect.any(String));});
it("successful answer followed by read failure closes committed draft and warns",async()=>{render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'开始评价'}));const f=screen.getByRole('form',{name:'本人360答卷'});change(f,'rating','20');state.api.myFeedback360Assignments.mockRejectedValue(new Error('合成刷新失败'));fireEvent.submit(f);await screen.findByText('本人评价任务：合成刷新失败');expect(screen.getByRole('status')).toHaveTextContent('勿重复提交');expect(screen.queryByRole('form',{name:'本人360答卷'})).toBeNull();expect(state.api.submitFeedback360).toHaveBeenCalledTimes(1);});
it("synchronous write lock blocks duplicate submit and switches until settled",async()=>{let finish=()=>{};state.api.submitFeedback360.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({})}));render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'开始评价'}));const f=screen.getByRole('form',{name:'本人360答卷'});change(f,'rating','10');fireEvent.submit(f);fireEvent.submit(f);expect(state.api.submitFeedback360).toHaveBeenCalledTimes(1);expect(f.querySelector('[name="rating"]')).toBeDisabled();expect(screen.getByRole('button',{name:'刷新评价工作台'})).toBeDisabled();await act(async()=>finish());});
it("identity replacement ignores stale write completion",async()=>{let finish=()=>{};state.api.submitFeedback360.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({})}));const {rerender}=render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'开始评价'}));const f=screen.getByRole('form',{name:'本人360答卷'});change(f,'rating','10');fireEvent.submit(f);state.user={...state.user,park_id:'other'};state.api.myFeedback360Assignments.mockResolvedValue([]);rerender(<HrFeedbackClient/>);await screen.findByText('当前没有评价任务。');await act(async()=>finish());expect(screen.queryByText('360评价已提交，内容不可修改。')).toBeNull();});
it("malformed task only disables that resource while cycle management remains usable",async()=>{state.user.permissions.push(H.HR_FEEDBACK_CYCLE_MANAGE);state.api.myFeedback360Assignments.mockResolvedValue([{id:'broken'}]);render(<HrFeedbackClient/>);await screen.findByText('本人评价任务：360办理响应不完整，请重新读取。');expect(screen.queryByRole('button',{name:'开始评价'})).toBeNull();expect(screen.getByRole('button',{name:'启动提名'})).toBeEnabled();});
it("unknown-result retry cannot silently change its original payload",async()=>{state.api.submitFeedback360.mockRejectedValueOnce(new Error('合成结果未知'));render(<HrFeedbackClient/>);fireEvent.click(await screen.findByRole('button',{name:'开始评价'}));const f=screen.getByRole('form',{name:'本人360答卷'});change(f,'rating','10');fireEvent.submit(f);await screen.findByText('合成结果未知');change(f,'rating','20');fireEvent.submit(f);await screen.findByText('上次提交结果尚未确认，请保持原内容重试，或刷新核对后重新办理。');expect(state.api.submitFeedback360).toHaveBeenCalledTimes(1);change(f,'rating','10');fireEvent.submit(f);await screen.findByText('360评价已提交，内容不可修改。');expect(state.api.submitFeedback360.mock.calls[1]![3]).toBe(state.api.submitFeedback360.mock.calls[0]![3]);});
it("submitted tasks expose no answer action and invalid precision never writes",async()=>{state.api.myFeedback360Assignments.mockResolvedValue([task,{...task,id:'submitted',status:'submitted',subjectName:'合成已提交对象'}]);render(<HrFeedbackClient/>);await screen.findByText('合成已提交对象 · 同级');expect(screen.getAllByRole('button',{name:'开始评价'})).toHaveLength(1);fireEvent.click(screen.getByRole('button',{name:'开始评价'}));const f=screen.getByRole('form',{name:'本人360答卷'});change(f,'rating','1.111');fireEvent.submit(f);await screen.findByText('合成评分须为0到100的数值，最多两位小数');expect(state.api.submitFeedback360).not.toHaveBeenCalled();});

it("cycle selections survive pagination/search beyond 500 and enter the submitted payload",async()=>{
 state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_CYCLE_MANAGE];
 state.api.feedback360EmployeeOptions.mockImplementation((page:number,keyword:string)=>Promise.resolve({items:keyword?[{id:"e601",fullName:"后续员工",employeeCode:"E601"}]:page===1?options.employees:[{id:"e21",fullName:"跨页员工",employeeCode:"E021"}],total:keyword?1:606,page:keyword?1:page,page_size:20}));
 render(<HrFeedbackClient/>);await waitFor(()=>expect(screen.getByRole('button',{name:'新建周期'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'新建周期'}));
 const f=screen.getByRole('form',{name:'创建360周期'});for(const [k,v] of Object.entries({cycleCode:'SYN-NEW',cycleName:'合成新周期',modelVersionId:'model',questionnaireVersionId:'questionnaire',nominationEnd:'2026-10-20',responseEnd:'2026-10-31'}))change(f,k,v);
 fireEvent.click(await screen.findByRole('checkbox',{name:'合成员工 · SYN'}));fireEvent.click(screen.getByRole('button',{name:'评价对象下一页'}));fireEvent.click(await screen.findByRole('checkbox',{name:'跨页员工 · E021'}));
 fireEvent.change(screen.getByRole('searchbox',{name:'搜索评价对象'}),{target:{value:'E601'}});fireEvent.click(screen.getByRole('button',{name:'搜索评价对象'}));fireEvent.click(await screen.findByRole('checkbox',{name:'后续员工 · E601'}));
 expect(within(screen.getByLabelText('已选评价对象')).getAllByRole('button')).toHaveLength(3);fireEvent.submit(f);await screen.findByText('360周期已创建，请核对后启动提名。');expect(state.api.createFeedback360Cycle).toHaveBeenCalledWith(expect.objectContaining({employeeIds:['employee','e21','e601']}),'synthetic-token',expect.any(String));expect(state.api.feedback360Options).not.toHaveBeenCalled();
});
it("nomination candidate failure retains the independent reviewer and blocks writing until retry",async()=>{
 state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_NOMINATE];state.api.feedback360SubjectOptions.mockRejectedValueOnce(new Error('对象读取失败'));
 render(<HrFeedbackClient/>);fireEvent.click(screen.getByRole('button',{name:'发起提名'}));fireEvent.click(await screen.findByRole('checkbox',{name:'合成员工 · SYN'}));await screen.findByText('提名对象：对象读取失败');const f=screen.getByRole('form',{name:'评价人提名'});fireEvent.submit(f);expect(state.api.nominateFeedback360).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole('button',{name:'重试提名对象'}));fireEvent.click(await screen.findByRole('checkbox',{name:'合成周期 · SYN · 合成对象 · SYN'}));expect(screen.getByRole('checkbox',{name:'合成员工 · SYN'})).toBeChecked();fireEvent.submit(f);await screen.findByText('评价人提名已提交。');expect(state.api.feedback360CycleOptions).not.toHaveBeenCalled();expect(state.api.feedback360Options).not.toHaveBeenCalled();
});
it("publication searches an operational subject beyond 500 and separates a committed write from refresh failure",async()=>{
 state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_RESULT_PUBLISH];state.api.feedback360SubjectOptions.mockImplementation((purpose:string,page:number,keyword:string)=>Promise.resolve({items:keyword?[{...options.subjects[0],id:'s601',status:'closed',subjectName:'后续对象'}]:[],total:keyword?1:602,page,page_size:20}));
 render(<HrFeedbackClient/>);await waitFor(()=>expect(state.api.feedback360SubjectOptions).toHaveBeenCalled());fireEvent.change(screen.getByRole('searchbox',{name:'搜索发布对象'}),{target:{value:'E601'}});fireEvent.click(screen.getByRole('button',{name:'搜索发布对象'}));fireEvent.click(await screen.findByRole('button',{name:'发布匿名结果'}));state.api.feedback360SubjectOptions.mockRejectedValue(new Error('发布列表刷新失败'));fireEvent.submit(screen.getByRole('form',{name:'360状态办理'}));await screen.findByText('发布对象：发布列表刷新失败');expect(screen.getByRole('status')).toHaveTextContent('匿名结果已发布。');expect(screen.getByRole('status')).toHaveTextContent('勿重复提交');expect(state.api.publishFeedback360Result).toHaveBeenCalledWith('s601','synthetic-token',expect.any(String));expect(state.api.feedback360EmployeeOptions).not.toHaveBeenCalled();expect(state.api.feedback360CycleOptions).not.toHaveBeenCalled();
});
it("review-only never reads employee, subject or cycle configuration candidates",async()=>{state.user.permissions=[H.HR_FEEDBACK_360_PAGE,H.HR_FEEDBACK_NOMINATION_REVIEW];render(<HrFeedbackClient/>);await screen.findByRole('button',{name:'批准'});expect(state.api.feedback360Options).not.toHaveBeenCalled();expect(state.api.feedback360EmployeeOptions).not.toHaveBeenCalled();expect(state.api.feedback360SubjectOptions).not.toHaveBeenCalled();expect(state.api.feedback360CycleOptions).not.toHaveBeenCalled();});
