import {act,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrGoalsClient} from "../../app/hr/goals/HrGoalsClient";
import type {HrGoal,HrGoalCycle} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]},api:{goalCycles:vi.fn(),goalManagementContext:vi.fn(),goalOptions:vi.fn(),goalCheckinContext:vi.fn(),goals:vi.fn(),goalCheckins:vi.fn(),createGoalCycle:vi.fn(),createGoal:vi.fn(),createGoalCheckin:vi.fn(),goalCycleAction:vi.fn(),goalAction:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=><>{children}</>}));
const goal=(id="goal",status="draft"):HrGoal=>({id,cycleId:"cycle",parentGoalId:null,goalLevel:"department",goalName:`合成${id}`,ownerOrgId:"org",ownerEmployeeId:null,ownerName:"合成部门",weight:"1",metricType:"numeric",metricName:"合成指标",targetValue:"0",currentValue:"0",unit:"项",progress:"0",startDate:"2026-10-01",dueDate:"2026-10-31",status,currentVersionNo:1});
const cycle=(status="active"):HrGoalCycle=>({id:"cycle",cycleCode:"SYN",cycleName:"合成周期",startDate:"2026-10-01",endDate:"2026-10-31",status});
const targetForm=()=>screen.getByRole("form",{name:"目标状态办理"});
function change(form:HTMLElement,name:string,value:string){fireEvent.change(form.querySelector(`[name="${name}"]`)!,{target:{value}});}
beforeEach(()=>{Object.values(state.api).forEach(m=>m.mockReset());state.user={id:"actor",park_id:"park",permissions:[H.HR_GOALS_PAGE,H.HR_GOAL_MANAGE,H.HR_GOAL_CYCLE_MANAGE]};state.api.goalCycles.mockResolvedValue([cycle()]);state.api.goalManagementContext.mockResolvedValue({items:[goal()],parents:[]});state.api.goalOptions.mockResolvedValue({canCreateGroup:false,orgs:[{id:"org",orgName:"合成部门"}],employees:[{id:"employee",fullName:"合成员工"}]});state.api.goalCheckinContext.mockResolvedValue([{...goal("own","active"),goalLevel:"employee",ownerEmployeeId:"employee"}]);state.api.goals.mockResolvedValue([goal("read","active")]);state.api.goalCheckins.mockResolvedValue([]);for(const k of ['createGoalCycle','createGoal','createGoalCheckin','goalCycleAction','goalAction'] as const)state.api[k].mockResolvedValue({});});
it("manager-only sees actionable drafts without ordinary goal or employee reads",async()=>{state.user.permissions=[H.HR_GOALS_PAGE,H.HR_GOAL_MANAGE];render(<HrGoalsClient/>);await screen.findByText("合成goal");expect(state.api.goals).not.toHaveBeenCalled();expect(state.api.goalCheckinContext).not.toHaveBeenCalled();expect(screen.getByRole('button',{name:'激活目标'})).toBeEnabled();expect(screen.queryByRole('button',{name:'启用周期'})).toBeNull();});
it("cycle-only manager can create and activate cycles without goal authority",async()=>{state.user.permissions=[H.HR_GOALS_PAGE,H.HR_GOAL_CYCLE_MANAGE];state.api.goalCycles.mockResolvedValue([cycle("draft")]);render(<HrGoalsClient/>);await screen.findByRole('button',{name:'启用周期'});expect(state.api.goalManagementContext).not.toHaveBeenCalled();expect(state.api.goalOptions).not.toHaveBeenCalled();expect(state.api.goals).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'启用周期'}));fireEvent.submit(targetForm());await screen.findByText('目标周期状态已更新。');expect(state.api.goalCycleAction).toHaveBeenCalledWith('cycle','activate','synthetic-token',expect.any(String));});
it("cycle close conflict remains visible and can retry exact action",async()=>{state.api.goalCycleAction.mockRejectedValueOnce(new Error('合成未结目标阻止关期'));render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'关闭周期'}));fireEvent.submit(targetForm());await screen.findByText('合成未结目标阻止关期');expect(targetForm()).toBeInTheDocument();fireEvent.submit(targetForm());await screen.findByText('目标周期状态已更新。');expect(state.api.goalCycleAction).toHaveBeenLastCalledWith('cycle','close','synthetic-token',expect.any(String));});
it("goal action rejects retain reason and do not close target or repeat while pending",async()=>{state.api.goalAction.mockRejectedValueOnce(new Error('合成激活失败'));render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'激活目标'}));const f=targetForm();change(f,'reason','确认目标权重与口径');fireEvent.submit(f);await screen.findByText('合成激活失败');expect(f.querySelector('[name="reason"]')).toHaveValue('确认目标权重与口径');fireEvent.submit(f);await screen.findByText('目标状态已更新。');expect(state.api.goalAction).toHaveBeenLastCalledWith('goal',{action:'activate',reason:'确认目标权重与口径'},'synthetic-token',expect.any(String));expect(screen.queryByRole('form',{name:'目标状态办理'})).toBeNull();});
it("active goal offers complete/cancel, terminal goal has neither transition",async()=>{state.api.goalManagementContext.mockResolvedValue({items:[goal('active','active'),goal('terminal','completed')],parents:[]});render(<HrGoalsClient/>);await screen.findByText('合成terminal');const terminal=screen.getByText('合成terminal').closest('article')!;expect(within(terminal).queryByRole('button',{name:'完成目标'})).toBeNull();fireEvent.click(screen.getByRole('button',{name:'取消目标'}));const f=targetForm();change(f,'reason','合成取消原因');fireEvent.submit(f);await screen.findByText('目标状态已更新。');expect(state.api.goalAction).toHaveBeenCalledWith('active',{action:'cancel',reason:'合成取消原因'},'synthetic-token',expect.any(String));});
it("checkin-only actor updates own progress and preserves explicit zero without extra reads",async()=>{state.user.permissions=[H.HR_GOALS_PAGE,H.HR_GOAL_CHECKIN];state.api.createGoalCheckin.mockRejectedValueOnce(new Error('合成进度保存失败'));render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'更新进度'}));const f=screen.getByRole('form',{name:'本人进度办理'});change(f,'summary','合成阶段进展');change(f,'currentValue','0');fireEvent.submit(f);await screen.findByText('合成进度保存失败');expect(f.querySelector('[name="summary"]')).toHaveValue('合成阶段进展');fireEvent.submit(f);await screen.findByText('目标进度已保存。');expect(state.api.createGoalCheckin).toHaveBeenLastCalledWith('own',expect.objectContaining({progress:0,currentValue:0,summary:'合成阶段进展'}),'synthetic-token',expect.any(String));expect(state.api.goalCycles).not.toHaveBeenCalled();expect(state.api.goals).not.toHaveBeenCalled();expect(state.api.goalManagementContext).not.toHaveBeenCalled();});
it("successful transition remains committed when followup context refresh fails",async()=>{render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'激活目标'}));const f=targetForm();change(f,'reason','合成开始执行');state.api.goalManagementContext.mockRejectedValue(new Error('合成管理刷新失败'));fireEvent.submit(f);await screen.findByText('管理目标：合成管理刷新失败');expect(screen.getByRole('status')).toHaveTextContent('目标状态已更新。 后续读取未完成');expect(screen.queryByRole('form',{name:'目标状态办理'})).toBeNull();expect(screen.queryByRole('button',{name:'激活目标'})).toBeNull();});
it("one synchronous writer locks target, create and refresh controls",async()=>{let finish=()=>{};state.api.goalAction.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({})}));render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'激活目标'}));const f=targetForm();change(f,'reason','合成互锁');fireEvent.submit(f);fireEvent.submit(f);expect(state.api.goalAction).toHaveBeenCalledTimes(1);expect(f.querySelector('[name="reason"]')).toBeDisabled();expect(screen.getByRole('button',{name:'分解目标'})).toBeDisabled();expect(screen.getByRole('button',{name:'刷新目标工作台'})).toBeDisabled();await act(async()=>finish());});
it("cycle creation failure retains all draft fields and allows retry",async()=>{state.api.createGoalCycle.mockRejectedValueOnce(new Error('合成周期保存失败'));render(<HrGoalsClient/>);fireEvent.click(screen.getByRole('button',{name:'目标周期'}));const f=screen.getByRole('button',{name:'保存周期'}).closest('form')!;for(const [name,value] of Object.entries({cycleCode:'SYN-NEW',cycleName:'合成新周期',startDate:'2026-10-01',endDate:'2026-10-31'}))change(f,name,value);fireEvent.submit(f);await screen.findByText('合成周期保存失败');expect(f.querySelector('[name="cycleName"]')).toHaveValue('合成新周期');fireEvent.submit(f);await screen.findByText('目标周期已保存，请在周期台账启用。');expect(state.api.createGoalCycle).toHaveBeenLastCalledWith({cycleCode:'SYN-NEW',cycleName:'合成新周期',startDate:'2026-10-01',endDate:'2026-10-31'},'synthetic-token',expect.any(String));});
it("create goal keeps scoped references and zero target after failed save",async()=>{state.api.goalManagementContext.mockResolvedValue({items:[goal()],parents:[{id:'parent',cycleId:'cycle',goalName:'合成集团上级',goalLevel:'group',status:'active',startDate:'2026-10-01',dueDate:'2026-10-31'}]});state.api.createGoal.mockRejectedValueOnce(new Error('合成分解失败'));render(<HrGoalsClient/>);await waitFor(()=>expect(screen.getByRole('button',{name:'分解目标'})).toBeEnabled());fireEvent.click(screen.getByRole('button',{name:'分解目标'}));const f=screen.getByRole('button',{name:'创建目标'}).closest('form')!;for(const [name,value] of Object.entries({parentGoalId:'parent',ownerOrgId:'org',goalName:'合成部门任务',metricName:'合成产出',targetValue:'0',unit:'项',weight:'0.5',startDate:'2026-10-01',dueDate:'2026-10-31'}))change(f,name,value);fireEvent.submit(f);await screen.findByText('合成分解失败');expect(f.querySelector('[name="targetValue"]')).toHaveValue(0);expect(f.querySelector('[name="parentGoalId"]')).toHaveValue('parent');fireEvent.submit(f);await screen.findByText('目标草稿已保存，请核对后激活。');expect(state.api.createGoal).toHaveBeenLastCalledWith(expect.objectContaining({cycleId:'cycle',parentGoalId:'parent',ownerOrgId:'org',targetValue:0,goalLevel:'department',weight:0.5}),'synthetic-token',expect.any(String));});
it("read-only team chooses scoped team request and can inspect checkin history",async()=>{state.user.permissions=[H.HR_GOALS_PAGE,H.HR_GOAL_TEAM_READ];state.api.goalCheckins.mockResolvedValue([{id:'entry',goalId:'read',progress:'0',currentValue:'0',summary:'合成进展摘要',risks:'合成风险',confidence:'high',nextAction:'合成下一步',createTime:'2026-10-09'}]);render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'进展记录'}));await screen.findByText('合成进展摘要');expect(state.api.goals).toHaveBeenCalledWith(false,'synthetic-token',{},expect.any(AbortSignal));expect(state.api.goalCheckins).toHaveBeenCalledWith('read','synthetic-token',expect.any(AbortSignal));expect(state.api.goalManagementContext).not.toHaveBeenCalled();expect(screen.queryByRole('button',{name:'激活目标'})).toBeNull();});
it("management failure does not hide independently readable authorized goals or cycles",async()=>{state.user.permissions.push(H.HR_GOAL_TEAM_READ);state.api.goalManagementContext.mockRejectedValue(new Error('合成管理读失败'));render(<HrGoalsClient/>);await screen.findByText('合成read');expect(screen.getByText('合成周期 · SYN')).toBeInTheDocument();expect(screen.getByText('管理目标：合成管理读失败')).toBeInTheDocument();expect(screen.queryByRole('button',{name:'激活目标'})).toBeNull();});
it("malformed operation context exposes error and never enables a write",async()=>{state.api.goalManagementContext.mockResolvedValue({items:[{id:'bad',status:'draft'}],parents:[]});render(<HrGoalsClient/>);await screen.findByText('管理目标：目标办理信息无效，请重新读取。');expect(screen.queryByRole('button',{name:'激活目标'})).toBeNull();expect(screen.getByRole('button',{name:'分解目标'})).toBeDisabled();});
it("identity replacement clears prior target and ignores old write completion",async()=>{let finish=()=>{};state.api.goalAction.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({})}));const {rerender}=render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'激活目标'}));change(targetForm(),'reason','合成旧上下文');fireEvent.submit(targetForm());state.user={...state.user,park_id:'other'};state.api.goalManagementContext.mockResolvedValue({items:[],parents:[]});rerender(<HrGoalsClient/>);expect(screen.queryByRole('form',{name:'目标状态办理'})).toBeNull();await waitFor(()=>expect(state.api.goalManagementContext).toHaveBeenCalledTimes(2));await act(async()=>finish());expect(state.api.goalManagementContext).toHaveBeenCalledTimes(2);expect(screen.queryByRole('status')).toBeNull();});

it("team manager draft has no history read shortcut beyond ordinary read scope",async()=>{state.user.permissions.push(H.HR_GOAL_TEAM_READ);render(<HrGoalsClient/>);await screen.findByText('合成goal');expect(screen.queryByRole('button',{name:'进展记录'})).toBeNull();expect(screen.getByRole('button',{name:'激活目标'})).toBeEnabled();});

it("unknown create/checkin transport failure reuses operation key on identical retry",async()=>{state.user.permissions=[H.HR_GOALS_PAGE,H.HR_GOAL_CHECKIN];state.api.createGoalCheckin.mockRejectedValueOnce(new Error('合成连接中断'));render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole('button',{name:'更新进度'}));const f=screen.getByRole('form',{name:'本人进度办理'});change(f,'summary','合成重试同一次进度');fireEvent.submit(f);await screen.findByText('合成连接中断');const first=state.api.createGoalCheckin.mock.calls[0];fireEvent.submit(f);await screen.findByText('目标进度已保存。');expect(state.api.createGoalCheckin.mock.calls[1]).toEqual(first);});
