import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrGoalsClient} from "../../app/hr/goals/HrGoalsClient";
const state=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]},api:{goalChangeContext:vi.fn(),goalChangeDetail:vi.fn(),changeGoal:vi.fn(),goalCycles:vi.fn(),goalManagementContext:vi.fn(),goalOptions:vi.fn(),goalCheckinContext:vi.fn(),goals:vi.fn(),goalCheckins:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=><>{children}</>}));
const goal={id:"goal",cycleId:"cycle",parentGoalId:"parent",goalLevel:"department",goalName:"合成部门目标",ownerOrgId:"org",ownerEmployeeId:null,ownerName:"合成部门",weight:"0.5",metricType:"numeric",metricName:"合成指标",targetValue:"0",currentValue:"4",unit:"项",progress:"0.4",startDate:"2026-10-01",dueDate:"2026-10-31",status:"active",currentVersionNo:2};
const context=()=>({items:[goal],parents:[{...goal,id:"parent",goalLevel:"group",goalName:"合成集团目标"}],cycles:[{id:"cycle",cycleCode:"SYN",cycleName:"合成周期",startDate:"2026-10-01",endDate:"2026-10-31",status:"active"}],canCreateGroup:false,orgs:[{id:"org",orgName:"合成部门"}],employees:[{id:"employee",fullName:"合成协作者"}]});
const detail=()=>({goal:{...goal,metricDefinition:"合成原统计口径"},collaborators:[{employeeId:"employee",employeeName:"合成协作者"}],versions:[{versionNo:2,snapshot:{goalName:"合成部门目标",targetValue:"0",metricDefinition:"合成原统计口径"},changeReason:"合成版本变更",createdAt:"2026-10-09"},{versionNo:1,snapshot:{goalName:"原名称"},changeReason:"合成初始定义",createdAt:"2026-10-01"}]});
const form=()=>screen.getByRole("form",{name:"目标定义变更"});
const open=async()=>{fireEvent.click(await screen.findByRole("button",{name:"编辑定义与查看版本"}));await screen.findByDisplayValue("合成原统计口径");};
beforeEach(()=>{Object.values(state.api).forEach(m=>m.mockReset());state.user={id:"actor",park_id:"park",permissions:[H.HR_GOALS_PAGE,H.HR_GOAL_CHANGE]};state.api.goalChangeContext.mockResolvedValue(context());state.api.goalChangeDetail.mockResolvedValue(detail());state.api.changeGoal.mockResolvedValue(goal);});
it("CHANGE-only user gets exact operation resources and complete current definition/history",async()=>{render(<HrGoalsClient/>);await open();expect(state.api.goals).not.toHaveBeenCalled();expect(state.api.goalManagementContext).not.toHaveBeenCalled();expect(state.api.goalOptions).not.toHaveBeenCalled();expect(state.api.goalCycles).not.toHaveBeenCalled();expect(screen.getByText("合成初始定义",{exact:false})).toBeInTheDocument();expect(form().querySelector('[name="targetValue"]')).toHaveValue(0);expect(form().querySelector('[name="collaboratorEmployeeIds"]')).toHaveValue(["employee"]);});
it("failed edit retains zero, reason and collaborators; identical retry uses same version/key",async()=>{state.api.changeGoal.mockRejectedValueOnce(Error("合成连接中断"));render(<HrGoalsClient/>);await open();fireEvent.change(screen.getByLabelText("变更原因"),{target:{value:"合成业务调整"}});fireEvent.submit(form());await screen.findByText("合成连接中断");expect(screen.getByLabelText("变更原因")).toHaveValue("合成业务调整");expect(form().querySelector('[name="targetValue"]')).toHaveValue(0);expect(state.api.changeGoal.mock.calls[0]![1]).toEqual(expect.objectContaining({targetValue:0,collaboratorEmployeeIds:["employee"],expectedVersionNo:2,metricDefinition:"合成原统计口径"}));const first=state.api.changeGoal.mock.calls[0];fireEvent.submit(form());await screen.findByText("目标定义已更新，历史版本已保留。");expect(state.api.changeGoal.mock.calls[1]).toEqual(first);expect(screen.queryByRole("form",{name:"目标定义变更"})).toBeNull();});
it("nullable target remains null and unchanged unavailable collaborator binding survives",async()=>{const d=detail();d.goal.targetValue=null as unknown as string;d.collaborators=[{employeeId:"historic",employeeName:"原协作者"}];state.api.goalChangeDetail.mockResolvedValue(d);render(<HrGoalsClient/>);await open();fireEvent.change(screen.getByLabelText("变更原因"),{target:{value:"合成空值延续"}});fireEvent.submit(form());await screen.findByText("目标定义已更新，历史版本已保留。");expect(state.api.changeGoal).toHaveBeenCalledWith("goal",expect.objectContaining({targetValue:null,collaboratorEmployeeIds:["historic"]}),"synthetic-token",expect.any(String));});
it("writer lock prevents duplicate submission and target changes",async()=>{let finish=()=>{};state.api.changeGoal.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve(goal);}));render(<HrGoalsClient/>);await open();fireEvent.change(screen.getByLabelText("变更原因"),{target:{value:"合成锁验证"}});fireEvent.submit(form());fireEvent.submit(form());expect(state.api.changeGoal).toHaveBeenCalledTimes(1);expect(screen.getByRole("button",{name:"收起定义"})).toBeDisabled();expect(screen.getByRole("button",{name:"编辑定义与查看版本"})).toBeDisabled();await act(async()=>finish());});
it("committed edit remains success when later context refresh fails",async()=>{state.api.goalChangeContext.mockResolvedValueOnce(context()).mockRejectedValue(Error("合成刷新失败"));render(<HrGoalsClient/>);await open();fireEvent.change(screen.getByLabelText("变更原因"),{target:{value:"合成保存"}});fireEvent.submit(form());await screen.findByText("目标定义已更新，历史版本已保留。 后续读取未完成，请刷新查看，勿重复办理。");expect(screen.queryByRole("form",{name:"目标定义变更"})).toBeNull();expect(state.api.changeGoal).toHaveBeenCalledTimes(1);});
it("closed goal exposes immutable definition/history with no save",async()=>{const c=context(),d=detail();c.items=[{...goal,status:"completed"}];d.goal.status="completed";state.api.goalChangeContext.mockResolvedValue(c);state.api.goalChangeDetail.mockResolvedValue(d);render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole("button",{name:"查看定义版本"}));await screen.findByDisplayValue("合成原统计口径");expect(screen.queryByRole("button",{name:"保存定义并留存版本"})).toBeNull();expect(screen.getByLabelText("目标名称")).toBeDisabled();});
it("malformed or mismatched detail disables editing with an explicit retry",async()=>{state.api.goalChangeDetail.mockResolvedValue({...detail(),goal:{...detail().goal,id:"other"}});render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole("button",{name:"编辑定义与查看版本"}));await screen.findByText("目标详情与当前选择不一致，请重新读取。");expect(screen.queryByRole("form",{name:"目标定义变更"})).toBeNull();expect(screen.getByRole("button",{name:"重新读取定义"})).toBeEnabled();});
it("identity replacement clears draft and ignores late detail",async()=>{let finish=(value:unknown)=>{};state.api.goalChangeDetail.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));const {rerender}=render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole("button",{name:"编辑定义与查看版本"}));state.user={...state.user,park_id:"other"};state.api.goalChangeContext.mockResolvedValue({...context(),items:[]});rerender(<HrGoalsClient/>);await screen.findByText("当前权限范围暂无可变更目标。");await act(async()=>finish(detail()));expect(screen.queryByRole("form",{name:"目标定义变更"})).toBeNull();expect(screen.queryByRole("region",{name:"目标定义编辑与版本"})).toBeNull();});
it("read permission alone never fetches a change context",async()=>{state.user.permissions=[H.HR_GOALS_PAGE,H.HR_GOAL_TEAM_READ];state.api.goals.mockResolvedValue([]);state.api.goalCycles.mockResolvedValue([]);render(<HrGoalsClient/>);await waitFor(()=>expect(state.api.goals).toHaveBeenCalled());expect(state.api.goalChangeContext).not.toHaveBeenCalled();expect(screen.queryByRole("region",{name:"目标定义与版本"})).toBeNull();});

it("missing definition projection cannot become an empty replacement",async()=>{const d=detail();delete (d.goal as Partial<typeof d.goal>).metricDefinition;state.api.goalChangeDetail.mockResolvedValue(d);render(<HrGoalsClient/>);fireEvent.click(await screen.findByRole("button",{name:"编辑定义与查看版本"}));await screen.findByText("目标版本详情无效，请重新读取。");expect(screen.queryByRole("form",{name:"目标定义变更"})).toBeNull();expect(state.api.changeGoal).not.toHaveBeenCalled();});

it("history translates enums without rewriting literal business names",async()=>{const d=detail();d.versions[0]!.snapshot.goalName="count";state.api.goalChangeDetail.mockResolvedValue(d);render(<HrGoalsClient/>);await open();expect(screen.getByText("目标名称：count")).toBeInTheDocument();expect(screen.queryByText("目标名称：数量")).toBeNull();});
