import {act,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {StrictMode} from "react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS} from "@jinhu/shared";
import {LifecycleTemplateEditor} from "../../app/hr/lifecycle/LifecycleTemplateEditor";
import {LifecycleTemplateManager} from "../../app/hr/lifecycle/LifecycleTemplateManager";
import {HrLifecycleClient} from "../../app/hr/lifecycle/HrLifecycleClient";
import type {HrLifecycleTemplateDetail,HrLifecycleTemplateItem} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",tenant_id:"tenant",park_id:"park",permissions:[] as string[]},api:{createLifecycleTemplate:vi.fn(),publishLifecycleTemplateVersion:vi.fn(),lifecycleTemplates:vi.fn(),lifecycleTemplateOptions:vi.fn(),lifecycleTemplateDetail:vi.fn(),directoryOptions:vi.fn(),lifecycleChecklists:vi.fn(),events:vi.fn(),createLifecycleChecklist:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
vi.mock("../../app/hr/lifecycle/ProbationApplicationsPanel",()=>({ProbationApplicationsPanel:()=>null}));vi.mock("../../app/hr/lifecycle/JobChangeApplicationsPanel",()=>({JobChangeApplicationsPanel:()=>null}));vi.mock("../../app/hr/lifecycle/DepartureApplicationsPanel",()=>({DepartureApplicationsPanel:()=>null}));vi.mock("../../app/hr/lifecycle/RehireApplicationsPanel",()=>({RehireApplicationsPanel:()=>null}));
vi.mock("../../app/hr/components/HrEmployeeSelection",()=>({HrEmployeeSelection:({selectedId,onChange}:{selectedId:string;onChange:(value:string)=>void})=><label>员工<select value={selectedId} onChange={event=>onChange(event.target.value)}><option value=""/><option value="employee">合成员工</option></select></label>}));
const item=(index=1):HrLifecycleTemplateItem=>({code:`TASK-${index}`,name:`合成任务${index}`,category:"documents",defaultDueDays:index,required:true});
const template:HrLifecycleTemplateDetail={id:"template",code:"SYN",name:"合成模板",type:"onboarding",versionId:"version-1",versionNo:1,itemCount:2,items:[item(1),item(2)]};
beforeEach(()=>{Object.values(state.api).forEach(mock=>mock.mockReset());state.user={id:"actor",tenant_id:"tenant",park_id:"park",permissions:[HR_PERMISSIONS.HR_LIFECYCLE_PAGE,HR_PERMISSIONS.HR_LIFECYCLE_TEMPLATE_MANAGE]};state.api.lifecycleTemplates.mockResolvedValue([template]);state.api.lifecycleTemplateDetail.mockResolvedValue(template);state.api.lifecycleTemplateOptions.mockResolvedValue([template]);state.api.directoryOptions.mockResolvedValue({users:[],orgs:[]});state.api.lifecycleChecklists.mockResolvedValue({items:[],total:0});state.api.events.mockResolvedValue([]);});
const group=(index:number)=>within(screen.getByRole("group",{name:`任务${index}`}));
const fill=(index:number,code:string,name:string)=>{fireEvent.change(group(index).getByLabelText("任务编号"),{target:{value:code}});fireEvent.change(group(index).getByLabelText("任务名称"),{target:{value:name}});};
it("submits ordered full task fields, removes a task and retains failed creation drafts",async()=>{
 state.api.createLifecycleTemplate.mockRejectedValue(new Error("合成模板失败"));const saved=vi.fn();render(<LifecycleTemplateEditor onSaved={saved}/>);fireEvent.change(screen.getByLabelText("模板编号"),{target:{value:"SYN"}});fireEvent.change(screen.getByLabelText("模板名称"),{target:{value:"草稿模板"}});fill(1,"ACCOUNT","开通账号");fireEvent.change(group(1).getByLabelText("相对截止天数"),{target:{value:"-365"}});fireEvent.click(screen.getByRole("button",{name:"添加任务"}));fill(2,"DOC","提交资料");fireEvent.change(group(2).getByLabelText("相对截止天数"),{target:{value:"0"}});fireEvent.click(group(2).getByRole("checkbox",{name:"必须办理"}));fireEvent.click(screen.getByRole("button",{name:"添加任务"}));fill(3,"REMOVE","移除任务");fireEvent.click(screen.getByRole("button",{name:"下移任务1"}));fireEvent.click(screen.getByRole("button",{name:"删除任务3"}));fireEvent.submit(screen.getByRole("button",{name:"发布模板"}).closest("form")!);await screen.findByText("合成模板失败");expect(state.api.createLifecycleTemplate).toHaveBeenCalledWith({code:"SYN",name:"草稿模板",type:"onboarding",items:[{code:"DOC",name:"提交资料",category:"documents",defaultDueDays:0,required:false},{code:"ACCOUNT",name:"开通账号",category:"documents",defaultDueDays:-365,required:true}]},"synthetic-token");expect(screen.getByLabelText("模板名称")).toHaveValue("草稿模板");expect(group(1).getByLabelText("任务名称")).toHaveValue("提交资料");expect(saved).not.toHaveBeenCalled();
});
it("enforces one and50 item limits with touch ordering controls",()=>{
 const {unmount}=render(<LifecycleTemplateEditor onSaved={vi.fn()}/>);expect(screen.getByRole("button",{name:"删除任务1"})).toBeDisabled();unmount();render(<LifecycleTemplateEditor template={{...template,itemCount:50,items:Array.from({length:50},(_,i)=>item(i))}} onSaved={vi.fn()}/>);expect(screen.getByRole("button",{name:"添加任务"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"删除任务50"}));expect(screen.getByRole("button",{name:"添加任务"})).toBeEnabled();fireEvent.click(screen.getByRole("button",{name:"添加任务"}));expect(screen.getAllByRole("group")).toHaveLength(50);expect(screen.getByRole("button",{name:"添加任务"})).toBeDisabled();
});
it("blocks duplicate, blank and out-of-bound task fields before publishing",async()=>{
 render(<LifecycleTemplateEditor template={{...template,items:[item(),item()]}} onSaved={vi.fn()}/>);const form=screen.getByRole("button",{name:"发布新版本"}).closest("form")!;fireEvent.submit(form);expect(screen.getByRole("alert")).toHaveTextContent("重复");fill(2,"OTHER"," ");fireEvent.submit(form);expect(screen.getByRole("alert")).toHaveTextContent("不能为空");fill(2,"OTHER","另一个任务");fireEvent.change(group(2).getByLabelText("相对截止天数"),{target:{value:"366"}});fireEvent.submit(form);expect(screen.getByRole("alert")).toHaveTextContent("-365至365");expect(state.api.publishLifecycleTemplateVersion).not.toHaveBeenCalled();
});
it("publishes current-version edits with a synchronous double-submit guard and success feedback",async()=>{
 let resolve!:(value:{versionNo:number;itemCount:number})=>void;state.api.publishLifecycleTemplateVersion.mockImplementation(()=>new Promise(finish=>{resolve=finish;}));render(<LifecycleTemplateEditor template={template} onSaved={vi.fn()}/>);fireEvent.change(group(1).getByLabelText("任务名称"),{target:{value:"修改账号任务"}});const form=screen.getByRole("button",{name:"发布新版本"}).closest("form")!;fireEvent.submit(form);fireEvent.submit(form);expect(state.api.publishLifecycleTemplateVersion).toHaveBeenCalledTimes(1);expect(state.api.publishLifecycleTemplateVersion).toHaveBeenCalledWith("template",{items:[{...item(1),name:"修改账号任务"},item(2)]},"synthetic-token");await act(async()=>resolve({versionNo:2,itemCount:2}));expect(await screen.findByText("已发布模板V2，共2项任务。")).toBeVisible();
});
it("manager reads current items, retains failed version edits and ignores detail after close",async()=>{
 state.api.publishLifecycleTemplateVersion.mockRejectedValue(new Error("新版本失败"));render(<LifecycleTemplateManager onSaved={vi.fn()}/>);fireEvent.click(await screen.findByRole("button",{name:"编辑合成模板新版本"}));await screen.findByText(/当前V1/);const editors=screen.getAllByRole("group",{name:"任务1"});const versionGroup=within(editors[1]!);fireEvent.change(versionGroup.getByLabelText("任务名称"),{target:{value:"保留新稿"}});fireEvent.submit(screen.getByRole("button",{name:"发布新版本"}).closest("form")!);await screen.findByText("新版本失败");expect(versionGroup.getByLabelText("任务名称")).toHaveValue("保留新稿");fireEvent.click(screen.getByRole("button",{name:"关闭模板编辑"}));let finish!:(value:HrLifecycleTemplateDetail)=>void;state.api.lifecycleTemplateDetail.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));fireEvent.click(screen.getByRole("button",{name:"编辑合成模板新版本"}));const signal=state.api.lifecycleTemplateDetail.mock.calls.at(-1)![2] as AbortSignal;fireEvent.click(screen.getByRole("button",{name:"关闭模板编辑"}));expect(signal.aborted).toBe(true);await act(async()=>finish(template));expect(screen.queryByRole("button",{name:"发布新版本"})).toBeNull();
});
it("assign-only reads minimal candidates, cannot edit and failed checklist retains selection and due date",async()=>{
 state.user.permissions=[HR_PERMISSIONS.HR_LIFECYCLE_PAGE,HR_PERMISSIONS.HR_LIFECYCLE_ASSIGN];state.api.createLifecycleChecklist.mockRejectedValue(new Error("清单失败"));render(<HrLifecycleClient/>);await screen.findByRole("option",{name:"入职 · 合成模板（V1）"});expect(state.api.lifecycleTemplates).not.toHaveBeenCalled();expect(state.api.lifecycleChecklists).not.toHaveBeenCalled();expect(screen.queryByRole("button",{name:"发布模板"})).toBeNull();fireEvent.change(screen.getByLabelText("员工"),{target:{value:"employee"}});fireEvent.change(screen.getByLabelText("模板版本"),{target:{value:"version-1"}});fireEvent.change(screen.getByLabelText("截止日期"),{target:{value:"2026-10-08"}});fireEvent.submit(screen.getByRole("button",{name:"创建清单"}).closest("form")!);await screen.findByText("清单失败");expect(screen.getByLabelText("模板版本")).toHaveValue("version-1");expect(screen.getByLabelText("截止日期")).toHaveValue("2026-10-08");expect(screen.getByLabelText("员工")).toHaveValue("employee");
});
it("full context switch clears template drafts and cancels late detail response",async()=>{
 let finish!:(value:HrLifecycleTemplateDetail)=>void;state.api.lifecycleTemplateDetail.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve;}));const view=render(<HrLifecycleClient/>);fireEvent.change(screen.getByLabelText("模板名称"),{target:{value:"旧身份草稿"}});fireEvent.click(await screen.findByRole("button",{name:"编辑合成模板新版本"}));const signal=state.api.lifecycleTemplateDetail.mock.calls[0]![2] as AbortSignal;state.user={...state.user,park_id:"other"};view.rerender(<HrLifecycleClient/>);expect(signal.aborted).toBe(true);expect(screen.getByLabelText("模板名称")).toHaveValue("");await act(async()=>finish(template));expect(screen.queryByRole("button",{name:"发布新版本"})).toBeNull();
});
it.each([{id:"wrong-template"},{items:[null,null]},{itemCount:51},{items:[{...item(1),required:"false"},item(2)]}])("rejects malformed or mismatched detail before mounting the editor: %j",async invalid=>{
 state.api.lifecycleTemplateDetail.mockResolvedValue({...template,...invalid});render(<LifecycleTemplateManager onSaved={vi.fn()}/>);
 fireEvent.click(await screen.findByRole("button",{name:"编辑合成模板新版本"}));expect(await screen.findByRole("alert")).toHaveTextContent("清单模板数据无效");expect(screen.queryByRole("button",{name:"发布新版本"})).toBeNull();
 state.api.lifecycleTemplateDetail.mockResolvedValue(template);fireEvent.click(screen.getByRole("button",{name:"重试模板版本"}));expect(await screen.findByRole("button",{name:"发布新版本"})).toBeVisible();
});
it("a publication refresh cannot replace a reopened draft for the same template",async()=>{
 let finishRefresh!:()=>void;const refreshed=vi.fn(()=>new Promise<void>(resolve=>{finishRefresh=resolve;}));state.api.publishLifecycleTemplateVersion.mockResolvedValue({versionNo:2,itemCount:2});
 render(<LifecycleTemplateManager onSaved={refreshed}/>);fireEvent.click(await screen.findByRole("button",{name:"编辑合成模板新版本"}));fireEvent.submit((await screen.findByRole("button",{name:"发布新版本"})).closest("form")!);await waitFor(()=>expect(refreshed).toHaveBeenCalledTimes(1));
 fireEvent.click(screen.getByRole("button",{name:"关闭模板编辑"}));fireEvent.click(screen.getByRole("button",{name:"编辑合成模板新版本"}));await screen.findByRole("button",{name:"发布新版本"});
 const field=within(screen.getAllByRole("group",{name:"任务1"})[1]!).getByLabelText("任务名称");fireEvent.change(field,{target:{value:"重新打开后的新草稿"}});
 await act(async()=>finishRefresh());expect(field).toHaveValue("重新打开后的新草稿");expect(state.api.lifecycleTemplateDetail).toHaveBeenCalledTimes(2);
});
it("StrictMode publication keeps success distinct from a failed optional refresh",async()=>{
 state.api.publishLifecycleTemplateVersion.mockResolvedValue({versionNo:2,itemCount:2});render(<StrictMode><LifecycleTemplateEditor template={template} onSaved={async()=>{throw new Error("候选刷新中断");}}/></StrictMode>);
 fireEvent.submit(screen.getByRole("button",{name:"发布新版本"}).closest("form")!);
 expect(await screen.findByText("已发布模板V2，共2项任务。")).toBeVisible();expect(screen.getByRole("alert")).toHaveTextContent("模板已发布，刷新失败：候选刷新中断");expect(state.api.publishLifecycleTemplateVersion).toHaveBeenCalledTimes(1);
});
it("malformed assignment options do not mount unsafe select values",async()=>{
 state.user.permissions=[HR_PERMISSIONS.HR_LIFECYCLE_PAGE,HR_PERMISSIONS.HR_LIFECYCLE_ASSIGN];state.api.lifecycleTemplateOptions.mockResolvedValue([{...template,name:{private:"invalid"}}]);render(<HrLifecycleClient/>);
 expect(await screen.findByRole("alert")).toHaveTextContent("清单模板数据无效");expect(screen.queryByRole("option",{name:/合成模板/})).toBeNull();
});
