import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrPerformanceClient} from "../../app/hr/performance/HrPerformanceClient";
import type {HrPerformanceReviewV2} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]},api:{performanceCyclesV2:vi.fn(),performanceReviewsV2:vi.fn(),submitPerformanceSelfReviewV2:vi.fn(),submitPerformanceManagerReviewV2:vi.fn(),resolvePerformanceAppealV2:vi.fn(),acknowledgePerformanceReviewV2:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
vi.mock("../../app/hr/performance/PerformanceTemplates",()=>({PerformanceTemplates:()=>null}));
vi.mock("../../app/hr/performance/HrPerformanceLegacyPanel", () => ({ HrPerformanceLegacyPanel: () => null }));
vi.mock("../../app/hr/performance/HrPerformanceLegacyRelationsPanel", () => ({ HrPerformanceLegacyRelationsPanel: () => null }));
vi.mock("../../app/hr/performance/HrPerformanceLegacyAssessmentMasterPanel", () => ({ HrPerformanceLegacyAssessmentMasterPanel: () => null }));
vi.mock("../../app/hr/performance/HrPerformanceLegacyAssessmentValuePanel", () => ({ HrPerformanceLegacyAssessmentValuePanel: () => null }));
vi.mock("../../app/hr/performance/HrPerformanceLegacyAssessmentValueOfPersonPanel", () => ({ HrPerformanceLegacyAssessmentValueOfPersonPanel: () => null }));
vi.mock("../../app/hr/performance/HrPerformanceLegacyPersonSummaryPanel", () => ({ HrPerformanceLegacyPersonSummaryPanel: () => null }));
vi.mock("../../app/hr/performance/HrPerformanceLegacyWebAssQueryPanel", () => ({ HrPerformanceLegacyWebAssQueryPanel: () => null }));

const review=(id="review-1"):HrPerformanceReviewV2=>({id,cycleId:"cycle-1",cycleName:"合成评分期",status:"self_review",employee:{id:"employee-"+id,code:"SYN-"+id,name:"合成员工"+id},dimensions:[{code:"work",name:"工作质量",weight:"1",scoreMin:"0",scoreMax:"5"}],selfSubmission:null,managerSubmission:null,calibration:null,result:null,appeal:null,actions:{selfReview:true,managerReview:false,acknowledge:false,appeal:false,resolveAppeal:false}});
beforeEach(()=>{vi.resetAllMocks();state.user={id:"actor",park_id:"park",permissions:[H.HR_PERFORMANCE_PAGE,H.HR_PERFORMANCE_SELF_READ]};state.api.performanceCyclesV2.mockResolvedValue([]);state.api.performanceReviewsV2.mockResolvedValue([review(),review("review-2")]);state.api.submitPerformanceSelfReviewV2.mockResolvedValue({});state.api.submitPerformanceManagerReviewV2.mockResolvedValue({});state.api.resolvePerformanceAppealV2.mockResolvedValue({});});
async function selfForm(){render(<HrPerformanceClient/>);fireEvent.click((await screen.findAllByRole("button",{name:"填写自评"}))[0]!);return screen.getByRole("button",{name:"提交"}).closest("form")!;}
const score=()=>screen.getByLabelText("工作质量（100%）");
const change=(label:string,value:string)=>fireEvent.change(screen.getByLabelText(label),{target:{value}});
it("supports configured five-point ranges without invented80 and sends exact configured score/comments",async()=>{const form=await selfForm();expect(score()).toHaveValue(null);expect(score()).toHaveAttribute("max","5");fireEvent.submit(form);expect(state.api.submitPerformanceSelfReviewV2).not.toHaveBeenCalled();await screen.findByText("工作质量请填写0至5之间的分数，最多两位小数。");change("工作质量（100%）","3.25");change("评价说明","合成自评说明");fireEvent.submit(form);await waitFor(()=>expect(state.api.submitPerformanceSelfReviewV2).toHaveBeenCalledWith("review-1",{dimensionScores:{work:3.25},dimensionComments:{work:"合成自评说明"}},"synthetic-token"));});
it.each(["6","-1","1.234"])("rejects invalid score%s before domain write",async value=>{const form=await selfForm();change("工作质量（100%）",value);fireEvent.submit(form);await screen.findByRole("alert");expect(state.api.submitPerformanceSelfReviewV2).not.toHaveBeenCalled();});
it("recovers actor's zero and existing comments, and switches records without carrying a draft",async()=>{state.api.performanceReviewsV2.mockResolvedValue([{...review(),selfSubmission:{scores:{work:0},comments:{work:"已有说明"},score:"0"}},review("review-2")]);await selfForm();expect(score()).toHaveValue(0);expect(screen.getByLabelText("评价说明")).toHaveValue("已有说明");change("工作质量（100%）","4");fireEvent.click(screen.getAllByRole("button",{name:"填写自评"})[1]!);expect(score()).toHaveValue(null);expect(screen.getByLabelText("评价说明")).toHaveValue("");});
it("preserves failed drafts then retries the same business record",async()=>{state.api.submitPerformanceSelfReviewV2.mockRejectedValueOnce(new Error("合成提交失败"));const form=await selfForm();change("工作质量（100%）","0");change("评价说明","保留说明");fireEvent.submit(form);await screen.findByText("合成提交失败");expect(score()).toHaveValue(0);expect(screen.getByLabelText("评价说明")).toHaveValue("保留说明");fireEvent.submit(form);await screen.findByText("自评已提交");expect(state.api.submitPerformanceSelfReviewV2).toHaveBeenCalledTimes(2);});
it("single synchronous writer locks fields and close/switch until completion",async()=>{let done!:()=>void;state.api.submitPerformanceSelfReviewV2.mockImplementationOnce(()=>new Promise<void>(resolve=>{done=resolve}));const form=await selfForm();change("工作质量（100%）","4");fireEvent.submit(form);fireEvent.submit(form);expect(state.api.submitPerformanceSelfReviewV2).toHaveBeenCalledTimes(1);expect(score()).toBeDisabled();expect(screen.getByRole("button",{name:"关闭"})).toBeDisabled();expect(screen.getAllByRole("button",{name:"填写自评"}).every(x=>x.hasAttribute("disabled"))).toBe(true);await act(async()=>done());await screen.findByText("自评已提交");});
it("committed action plus refresh failure shows success and read warning with no repeat editor",async()=>{const form=await selfForm();state.api.performanceReviewsV2.mockRejectedValueOnce(new Error("合成刷新失败"));change("工作质量（100%）","4");fireEvent.submit(form);await screen.findByText("自评已提交");await screen.findByText(/合成刷新失败.*操作已成功/);expect(screen.queryByRole("button",{name:"提交"})).toBeNull();expect(state.api.submitPerformanceSelfReviewV2).toHaveBeenCalledTimes(1);});
it("appeal rejection needs a reason without replacement scores; upheld requires valid scores",async()=>{state.api.performanceReviewsV2.mockResolvedValue([{...review(),status:"appealed",appeal:{id:"appeal-1",status:"pending"},actions:{...review().actions,selfReview:false,resolveAppeal:true}}]);render(<HrPerformanceClient/>);fireEvent.click(await screen.findByRole("button",{name:"处理申诉"}));expect(screen.queryByLabelText("工作质量（100%）")).toBeNull();change("处理理由","维持原结果的合成说明");fireEvent.submit(screen.getByRole("button",{name:"提交"}).closest("form")!);await waitFor(()=>expect(state.api.resolvePerformanceAppealV2).toHaveBeenCalledWith("appeal-1",{decision:"rejected",reason:"维持原结果的合成说明"},"synthetic-token"));await screen.findByText("申诉处理已完成");fireEvent.click(screen.getByRole("button",{name:"处理申诉"}));change("处理决定","upheld");change("工作质量（100%）","3.33");change("处理理由","采纳调整的合成说明");fireEvent.submit(screen.getByRole("button",{name:"提交"}).closest("form")!);await waitFor(()=>expect(state.api.resolvePerformanceAppealV2).toHaveBeenLastCalledWith("appeal-1",{decision:"upheld",reason:"采纳调整的合成说明",dimensionScores:{work:3.33}},"synthetic-token"));});
it("unmounted write cannot start old-scope reload",async()=>{let done!:()=>void;state.api.submitPerformanceSelfReviewV2.mockImplementationOnce(()=>new Promise<void>(resolve=>{done=resolve}));const view=render(<HrPerformanceClient/>);fireEvent.click((await screen.findAllByRole("button",{name:"填写自评"}))[0]!);change("工作质量（100%）","4");fireEvent.submit(screen.getByRole("button",{name:"提交"}).closest("form")!);const reads=state.api.performanceReviewsV2.mock.calls.length;view.unmount();await act(async()=>done());expect(state.api.performanceReviewsV2).toHaveBeenCalledTimes(reads);});

it("honors a hundred-point configuration without pre-filling a judgment",async()=>{state.api.performanceReviewsV2.mockResolvedValue([{...review(),dimensions:[{...review().dimensions[0]!,scoreMax:"100"}]}]);const form=await selfForm();expect(score()).toHaveValue(null);expect(score()).toHaveAttribute("max","100");change("工作质量（100%）","80");fireEvent.submit(form);await waitFor(()=>expect(state.api.submitPerformanceSelfReviewV2).toHaveBeenCalledWith("review-1",{dimensionScores:{work:80},dimensionComments:{}},"synthetic-token"));});
it("manager recovers its own zero and comment instead of copying self judgment",async()=>{state.api.performanceReviewsV2.mockResolvedValue([{...review(),selfSubmission:{scores:{work:5},comments:{work:"员工自评"},score:"5"},managerSubmission:{scores:{work:0},comments:{work:"主管说明"},score:"0"},actions:{...review().actions,selfReview:false,managerReview:true}}]);render(<HrPerformanceClient/>);fireEvent.click(await screen.findByRole("button",{name:"主管评价"}));expect(score()).toHaveValue(0);expect(screen.getByLabelText("评价说明")).toHaveValue("主管说明");fireEvent.submit(screen.getByRole("button",{name:"提交"}).closest("form")!);await waitFor(()=>expect(state.api.submitPerformanceManagerReviewV2).toHaveBeenCalledWith("review-1",{dimensionScores:{work:0},dimensionComments:{work:"主管说明"}},"synthetic-token"));});
it("quick action failure is visible even without an open form",async()=>{state.api.performanceReviewsV2.mockResolvedValue([{...review(),actions:{...review().actions,selfReview:false,acknowledge:true}}]);state.api.acknowledgePerformanceReviewV2.mockRejectedValue(new Error("合成签收失败"));render(<HrPerformanceClient/>);fireEvent.click(await screen.findByRole("button",{name:"签收"}));await screen.findByText("合成签收失败");expect(screen.queryByRole("button",{name:"提交"})).toBeNull();});
it("identity replacement clears drafts and ignores an old committed action",async()=>{let done!:()=>void;state.api.submitPerformanceSelfReviewV2.mockImplementationOnce(()=>new Promise<void>(resolve=>{done=resolve}));const view=render(<HrPerformanceClient/>);fireEvent.click((await screen.findAllByRole("button",{name:"填写自评"}))[0]!);change("工作质量（100%）","4");fireEvent.submit(screen.getByRole("button",{name:"提交"}).closest("form")!);state.user={...state.user,park_id:"other"};view.rerender(<HrPerformanceClient/>);await screen.findAllByRole("button",{name:"填写自评"});expect(screen.queryByRole("button",{name:"提交"})).toBeNull();const reads=state.api.performanceReviewsV2.mock.calls.length;await act(async()=>done());expect(state.api.performanceReviewsV2).toHaveBeenCalledTimes(reads);expect(screen.queryByText("自评已提交")).toBeNull();fireEvent.click(screen.getAllByRole("button",{name:"填写自评"})[0]!);expect(score()).toHaveValue(null);});
