import { act, fireEvent, render, screen } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { PayrollInputOperations } from "../../app/hr/payroll/PayrollInputOperations";
const state=vi.hoisted(()=>({user:{id:"reviewer",tenant_id:"tenant",park_id:"park",permissions:[] as string[]},api:{payrollPeriods:vi.fn(),payrollInputs:vi.fn(),payrollInput:vi.fn(),updatePayrollInput:vi.fn(),confirmPayrollInput:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));
const employees=Array.from({length:101},(_,index)=>({employeeId:`employee-${index}`,expectedEmployeeVersion:index+1,employeeCode:`SYN-${index}`,fullName:`员工${index}`,directItems:{收入:"123.4500",税:"0.0000"}}));
const detail={id:"input",periodId:"period",ruleSetId:"rules",ruleVersionId:"approved",revisionNo:3,version:4,status:"draft",reason:"核对当期输入",employees,total:101,page:1,page_size:20,canEdit:true,canConfirm:true};
beforeEach(()=>{vi.resetAllMocks();state.user={id:"reviewer",tenant_id:"tenant",park_id:"park",permissions:[HR_PERMISSIONS.HR_PAYROLL_READ,HR_PERMISSIONS.HR_PAYROLL_DETAIL_READ,HR_PERMISSIONS.HR_EMPLOYEE_READ,HR_PERMISSIONS.HR_PAYROLL_MANAGE,HR_PERMISSIONS.HR_PAYROLL_REVIEW]};state.api.payrollPeriods.mockResolvedValue([{id:"period",periodMonth:"2026-10-01",startDate:"2026-10-01",endDate:"2026-10-31",status:"open"}]);state.api.payrollInputs.mockResolvedValue({items:[{...detail,displayName:"当期工资规则",employeeCount:101}],total:21,page:1,page_size:20});state.api.payrollInput.mockImplementation(async(_id,query)=>({...detail,page:query.page,page_size:query.pageSize,employees:employees.slice((query.page-1)*query.pageSize,query.page*query.pageSize)}));state.api.updatePayrollInput.mockResolvedValue({...detail,version:5});state.api.confirmPayrollInput.mockResolvedValue({...detail,version:5,status:"confirmed"});});
async function open(){render(<PayrollInputOperations/>);await screen.findByRole("option",{name:"2026-10"});fireEvent.change(screen.getByLabelText("查看输入期间"),{target:{value:"period"}});fireEvent.click(await screen.findByRole("button",{name:"查看输入明细"}));await screen.findByRole("region",{name:"工资输入明细"});}
it("metadata-only operators never fetch employee amounts or detail",async()=>{state.user.permissions=[HR_PERMISSIONS.HR_PAYROLL_READ];render(<PayrollInputOperations/>);await screen.findByRole("option",{name:"2026-10"});fireEvent.change(screen.getByLabelText("查看输入期间"),{target:{value:"period"}});await screen.findByText("当前权限可查看批次概要。");expect(state.api.payrollInput).not.toHaveBeenCalled();});
it("edits load all pages and retain every employee beyond the visible page",async()=>{await open();fireEvent.click(screen.getByRole("button",{name:"修改整批草稿"}));await screen.findByLabelText("员工0 · 收入");expect(state.api.payrollInput).toHaveBeenCalledWith("input",{page:2,pageSize:100},"synthetic-token",expect.any(AbortSignal));fireEvent.change(screen.getByLabelText("员工0 · 收入"),{target:{value:"999.9900"}});fireEvent.click(screen.getByRole("button",{name:"保存整批修改"}));await screen.findByText("整批输入草稿已更新。");const payload=state.api.updatePayrollInput.mock.calls[0]![1];expect(payload.employees).toHaveLength(101);expect(payload.expectedVersion).toBe(4);expect(payload.employees[0]).toEqual({employeeId:"employee-0",expectedEmployeeVersion:1,directItems:{收入:"999.9900",税:"0.0000"}});expect(payload.employees[100]).toEqual({employeeId:"employee-100",expectedEmployeeVersion:101,directItems:{收入:"123.4500",税:"0.0000"}});expect(JSON.stringify(payload)).not.toContain("fullName");});
it("version drift while loading the roster cannot open a partial editor",async()=>{await open();state.api.payrollInput.mockImplementation(async(_id,query)=>({...detail,version:query.page===2?5:4,page:query.page,page_size:query.pageSize,employees:employees.slice((query.page-1)*query.pageSize,query.page*query.pageSize)}));fireEvent.click(screen.getByRole("button",{name:"修改整批草稿"}));await screen.findByText("读取期间输入已变化，请刷新后重新编辑。");expect(screen.queryByLabelText("员工0 · 收入")).toBeNull();expect(state.api.updatePayrollInput).not.toHaveBeenCalled();});
it("failed save retains the full roster and reason with stable retry identity",async()=>{state.api.updatePayrollInput.mockRejectedValueOnce(new Error("合成修改失败"));await open();fireEvent.click(screen.getByRole("button",{name:"修改整批草稿"}));await screen.findByLabelText("修改准备说明");fireEvent.change(screen.getByLabelText("修改准备说明"),{target:{value:"重新核对所有员工"}});fireEvent.click(screen.getByRole("button",{name:"保存整批修改"}));await screen.findByText("合成修改失败");expect(screen.getByLabelText("修改准备说明")).toHaveValue("重新核对所有员工");fireEvent.click(screen.getByRole("button",{name:"保存整批修改"}));await screen.findByText("整批输入草稿已更新。");expect(state.api.updatePayrollInput.mock.calls[0]).toEqual(state.api.updatePayrollInput.mock.calls[1]);});
it("confirmation is single flight and a committed refresh failure blocks repeats",async()=>{let complete!:(value:unknown)=>void;state.api.confirmPayrollInput.mockImplementation(()=>new Promise(resolve=>{complete=resolve;}));await open();fireEvent.click(screen.getByRole("button",{name:"确认整批工资输入"}));fireEvent.click(screen.getByRole("button",{name:"确认整批工资输入"}));expect(state.api.confirmPayrollInput).toHaveBeenCalledTimes(1);expect(screen.getByLabelText("查看输入期间")).toBeDisabled();state.api.payrollInput.mockRejectedValue(new Error("合成刷新失败"));await act(async()=>complete({...detail,status:"confirmed",version:5}));await screen.findByText("操作已提交，刷新失败；请刷新最新状态，勿重复提交。");expect(screen.queryByRole("button",{name:"确认整批工资输入"})).toBeNull();expect(state.api.confirmPayrollInput.mock.calls[0]![1]).toEqual({expectedVersion:4});});
it("server action eligibility hides self-confirmation and terminal edits",async()=>{state.api.payrollInput.mockImplementation(async()=>({...detail,status:"confirmed",canEdit:false,canConfirm:false,employees:employees.slice(0,20)}));await open();expect(screen.queryByRole("button",{name:"修改整批草稿"})).toBeNull();expect(screen.queryByRole("button",{name:"确认整批工资输入"})).toBeNull();});
