import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { PayrollRunCreation } from "../../app/hr/payroll/PayrollRunCreation";
const state=vi.hoisted(()=>({user:{id:"author",tenant_id:"tenant",park_id:"park",permissions:[] as string[]},api:{payrollPeriods:vi.fn(),payrollInputs:vi.fn(),formalPayrollRunOptions:vi.fn(),createFormalPayrollRun:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));
const employee={employeeId:"employee",employeeCode:"SYN",fullName:"合成员工",insuranceSource:null};
const options={inputId:"input",inputVersion:7,periodId:"period",month:"2026-10",employeeCount:1,requires:{compensation:false,attendance:false,insurance:false},canCreateBase:true,overlappingEmployeeCount:0,attendanceBatches:[],correctionRuns:[],items:[employee],total:1,page:1,page_size:20};
const result={id:"run",runNo:1,employeeCount:1,grossAmount:"100.00",deductionAmount:"25.00",personalTax:"0.00",netAmount:"75.00"};
beforeEach(()=>{vi.resetAllMocks();state.user={id:"author",tenant_id:"tenant",park_id:"park",permissions:[HR_PERMISSIONS.HR_PAYROLL_READ,HR_PERMISSIONS.HR_PAYROLL_MANAGE,HR_PERMISSIONS.HR_PAYROLL_DETAIL_READ,HR_PERMISSIONS.HR_EMPLOYEE_READ]};state.api.payrollPeriods.mockResolvedValue([{id:"period",periodMonth:"2026-10-01",status:"open"}]);state.api.payrollInputs.mockResolvedValue({items:[{id:"input",revisionNo:3,version:7,status:"confirmed",displayName:"当期工资规则",employeeCount:1},{id:"draft",revisionNo:4,version:1,status:"draft",displayName:"待确认规则",employeeCount:1}],total:2,page:1,page_size:20});state.api.formalPayrollRunOptions.mockResolvedValue(options);state.api.createFormalPayrollRun.mockResolvedValue(result);});
async function open(onCreated?:()=>void){render(<PayrollRunCreation onCreated={onCreated}/>);await screen.findByRole("option",{name:"2026-10"});fireEvent.change(screen.getByLabelText("核算期间"),{target:{value:"period"}});fireEvent.click(await screen.findByRole("button",{name:"选择此确认输入"}));await screen.findByRole("button",{name:"生成正式工资批次"});}
it("missing employee financial capability never probes generation candidates",()=>{state.user.permissions=[HR_PERMISSIONS.HR_PAYROLL_MANAGE];render(<PayrollRunCreation/>);expect(state.api.payrollPeriods).not.toHaveBeenCalled();expect(state.api.formalPayrollRunOptions).not.toHaveBeenCalled();});
it("only confirmed inputs can generate and unused source fields are omitted",async()=>{const created=vi.fn();await open(created);expect(screen.getByRole("button",{name:"草稿待确认"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText(/第 1 批已生成/);expect(state.api.createFormalPayrollRun.mock.calls[0]![0]).toEqual({inputId:"input",expectedInputVersion:7});expect(created).toHaveBeenCalledTimes(1);expect(screen.getByRole("button",{name:"生成正式工资批次"})).toBeDisabled();});
it("compensation-only roster exposes page-two gap counts and blocks create before a request",async()=>{const rows=Array.from({length:23},(_,index)=>({employeeId:`employee-${index+1}`,employeeCode:`SYN-${String(index+1).padStart(3,"0")}`,fullName:`合成员工${index+1}`,insuranceSource:null,compensationCoverage:{status:index===20?"missing_or_incomplete":"covered",sourceCount:index===21?2:1}}));state.api.formalPayrollRunOptions.mockImplementation(async query=>({...options,employeeCount:23,total:23,requires:{compensation:true,attendance:false,insurance:false},compensationCoverage:{coveredCount:22,missingOrIncompleteCount:1,overlapCount:0,incompatiblePolicyCount:0,invalidMetadataCount:0,unsupportedCurrencyCount:0},page:query.page,page_size:query.pageSize,items:rows.slice((query.page-1)*query.pageSize,query.page*query.pageSize)}));await open();await screen.findByText(/缺失\/不完整 1/);fireEvent.click(screen.getByRole("button",{name:"来源名单下一页"}));await screen.findByText("薪酬区间缺失或不完整");expect(screen.getByText("合成员工21 · SYN-021")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText(/薪酬有效区间或来源资料待处理/);expect(state.api.createFormalPayrollRun).not.toHaveBeenCalled();});
it("unchecked compensation stays unknown and unused-source generation still retains its old request",async()=>{state.api.formalPayrollRunOptions.mockResolvedValue({...options,requires:{compensation:true,attendance:false,insurance:false},compensationCoverage:null,items:[{...employee,compensationCoverage:null}]});await open();await screen.findByText("薪酬来源尚未核对；生成时会按批准规则重新核对并冻结来源。");expect(screen.getByText("薪酬来源未检查")).toBeInTheDocument();expect(screen.queryByText(/缺失\/不完整 0/)).toBeNull();fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText(/第 1 批已生成/);expect(state.api.createFormalPayrollRun.mock.calls[0]![0]).toEqual({inputId:"input",expectedInputVersion:7});});
it("incomplete attendance remains inspectable, binds the selected response and cannot create",async()=>{state.api.formalPayrollRunOptions.mockImplementation(async query=>{const selectedAttendanceBatchId=query.attendanceInputBatchId??null;return {...options,requires:{...options.requires,attendance:true},selectedAttendanceBatchId,attendanceBatches:[{id:"incomplete",batchNo:1,batchType:"close",missingEmployeeCount:1},{id:"closed",batchNo:2,batchType:"correction",missingEmployeeCount:0}],items:[{...employee,attendanceCovered:selectedAttendanceBatchId==="incomplete"?false:selectedAttendanceBatchId==="closed"?true:null}]};});await open();expect(screen.getByRole("option",{name:/缺 1 位员工/})).not.toBeDisabled();fireEvent.change(screen.getByLabelText("当期封账考勤"),{target:{value:"incomplete"}});await screen.findByText("考勤缺失");expect(state.api.formalPayrollRunOptions).toHaveBeenLastCalledWith({inputId:"input",expectedInputVersion:7,attendanceInputBatchId:"incomplete",page:1,pageSize:20},"synthetic-token",expect.any(AbortSignal));expect(screen.getByText("当前批次尚未覆盖全部员工，仅供核对，不能生成正式工资。")).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText("请选择覆盖全部员工的当期封账考勤。");expect(state.api.createFormalPayrollRun).not.toHaveBeenCalled();fireEvent.change(screen.getByLabelText("当期封账考勤"),{target:{value:"closed"}});await screen.findByText("考勤已覆盖");fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText(/第 1 批已生成/);expect(state.api.createFormalPayrollRun.mock.calls[0]![0]).toEqual({inputId:"input",expectedInputVersion:7,attendanceInputBatchId:"closed"});});
it("insurance confirmation reads every page and posts all selected exact versions",async()=>{const rows=Array.from({length:101},(_,index)=>({...employee,employeeId:`employee-${index}`,insuranceSource:{employeeId:`employee-${index}`,sourceKind:"modern_confirmed",sourceId:`insurance-${index}`,expectedVersion:2,expectedHash:"a".repeat(64)}}));state.api.formalPayrollRunOptions.mockImplementation(async(q)=>({...options,employeeCount:101,total:101,requires:{...options.requires,insurance:true},page:q.page,page_size:q.pageSize,items:rows.slice((q.page-1)*q.pageSize,q.page*q.pageSize)}));await open();fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText("请读取完整名单并确认采用当期保险版本。");fireEvent.click(screen.getByRole("button",{name:"读取完整当期保险来源"}));const accept=await screen.findByLabelText("使用全部 101 人的当期确认保险版本");await waitFor(()=>expect(accept).not.toBeDisabled());expect(state.api.formalPayrollRunOptions).toHaveBeenCalledWith({inputId:"input",expectedInputVersion:7,page:2,pageSize:100},"synthetic-token",expect.any(AbortSignal));expect(screen.queryByText("a".repeat(64))).toBeNull();fireEvent.click(accept);fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText(/第 1 批已生成/);expect(state.api.createFormalPayrollRun.mock.calls[0]![0].insuranceSources).toHaveLength(101);expect(state.api.createFormalPayrollRun.mock.calls[0]![0].insuranceSources[100]).toEqual(rows[100]!.insuranceSource);});
it("missing insurance never produces a partial selection or a payroll request",async()=>{state.api.formalPayrollRunOptions.mockImplementation(async(q)=>({...options,requires:{...options.requires,insurance:true},page:q.page,page_size:q.pageSize}));await open();fireEvent.click(screen.getByRole("button",{name:"读取完整当期保险来源"}));await screen.findByText("1 位员工缺少当期确认保险，请在保险工作区补齐后刷新。");expect(screen.getByLabelText("使用全部 1 人的当期确认保险版本")).toBeDisabled();expect(state.api.createFormalPayrollRun).not.toHaveBeenCalled();});
it("overlapping employees require an eligible original run and a correction reason",async()=>{state.api.formalPayrollRunOptions.mockResolvedValue({...options,canCreateBase:false,overlappingEmployeeCount:1,correctionRuns:[{id:"original",runNo:4,employeeCount:1}]});render(<PayrollRunCreation/>);await screen.findByRole("option",{name:"2026-10"});fireEvent.change(screen.getByLabelText("核算期间"),{target:{value:"period"}});fireEvent.click(await screen.findByRole("button",{name:"选择此确认输入"}));fireEvent.click(await screen.findByRole("button",{name:"生成更正批次"}));await screen.findByText("请选择可更正的原批次并填写更正原因。");fireEvent.change(screen.getByLabelText("更正原批次"),{target:{value:"original"}});fireEvent.change(screen.getByLabelText("更正原因"),{target:{value:"核对来源后补算"}});fireEvent.click(screen.getByRole("button",{name:"生成更正批次"}));await screen.findByText(/第 1 批已生成/);expect(state.api.createFormalPayrollRun.mock.calls[0]![0]).toEqual({inputId:"input",expectedInputVersion:7,correctionOfRunId:"original",correctionReason:"核对来源后补算"});});
it("failed generation retains selection and retry identity with one active write",async()=>{state.api.createFormalPayrollRun.mockRejectedValueOnce(new Error("合成核算失败"));await open();fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));await screen.findByText("合成核算失败");let complete!:(value:unknown)=>void;state.api.createFormalPayrollRun.mockImplementationOnce(()=>new Promise(resolve=>{complete=resolve;}));fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));fireEvent.click(screen.getByRole("button",{name:"生成正式工资批次"}));expect(state.api.createFormalPayrollRun).toHaveBeenCalledTimes(2);expect(state.api.createFormalPayrollRun.mock.calls[0]).toEqual(state.api.createFormalPayrollRun.mock.calls[1]);expect(screen.getByLabelText("核算期间")).toBeDisabled();await act(async()=>complete(result));await screen.findByText(/第 1 批已生成/);});

it("closed-period correction binds input filter and original run without ordinary period probes",async()=>{
  const correction={periodId:"period",month:"2026-10",windowId:"window",ruleSetId:"rules",ruleName:"正式规则",originalRunId:"original",originalRunNo:4};
  state.api.formalPayrollRunOptions.mockResolvedValue({...options,canCreateBase:false,correctionRuns:[{id:"original",runNo:4,employeeCount:1}]});
  render(<PayrollRunCreation correction={correction}/>);
  fireEvent.click(await screen.findByRole("button",{name:"选择此确认输入"}));
  const reason=await screen.findByLabelText("更正原因");
  expect(state.api.payrollPeriods).not.toHaveBeenCalled();
  expect(state.api.payrollInputs).toHaveBeenCalledWith({periodId:"period",page:1,pageSize:20,correctionWindowId:"window"},"synthetic-token",expect.any(AbortSignal));
  expect(screen.getByLabelText("核算期间")).toBeDisabled();expect(screen.getByLabelText("更正原批次")).toHaveValue("original");expect(screen.getByLabelText("更正原批次")).toBeDisabled();
  fireEvent.change(reason,{target:{value:"关闭期间继续更正"}});fireEvent.click(screen.getByRole("button",{name:"生成更正批次"}));
  await screen.findByText(/第 1 批已生成/);
  expect(state.api.createFormalPayrollRun.mock.calls[0]![0]).toEqual({inputId:"input",expectedInputVersion:7,correctionOfRunId:"original",correctionReason:"关闭期间继续更正"});
});
