import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, expect, it, vi } from "vitest";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { HrPayrollClient } from "../../app/hr/payroll/HrPayrollClient";
import { PayrollFormulaReview } from "../../app/hr/payroll/PayrollFormulaReview";
const state=vi.hoisted(()=>({user:{id:"actor",tenant_id:"tenant",park_id:"park",permissions:[] as string[]},api:{payrollRules:vi.fn(),payrollHistoryFormulas:vi.fn(),payrollHistoryBooks:vi.fn(),payrollHistoryFormula:vi.fn(),reviewPayrollFormula:vi.fn(),payrollHistoryCatalogItems:vi.fn(),payrollHistoryTaxRules:vi.fn(),payrollHistoryReviewCases:vi.fn()}}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=>children}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));
const detail={id:"formula",bookId:"book",bookName:"Actual book",legacyScheme:"scheme",itemName:"Actual net",versionNo:1,rawExpression:"[基本项目]+1.2500",rawCondition:null,parserVersion:"parser",parseStatus:"manual_review",dependencyCodes:["payroll:基本项目"],calculationOrder:1,reviewedAt:null,reviewReason:null,syntax:{status:"parsed",parserVersion:"parser",dependencies:["payroll:基本项目"],reason:null},approvalEligibility:"syntax_ready"};
beforeEach(()=>{vi.resetAllMocks();state.api.payrollRules.mockResolvedValue({items:[],total:0,page:1,page_size:20});state.user={id:"actor",tenant_id:"tenant",park_id:"park",permissions:[HR_PERMISSIONS.HR_PAYROLL_RULE_READ,HR_PERMISSIONS.HR_PAYROLL_FORMULA_REVIEW]};state.api.payrollHistoryFormulas.mockResolvedValue({items:[detail],total:21,page:1,page_size:20});state.api.payrollHistoryBooks.mockResolvedValue({items:[{id:"book",bookName:"Actual book"}],total:21,page:1,page_size:20});state.api.payrollHistoryFormula.mockResolvedValue(detail);state.api.reviewPayrollFormula.mockResolvedValue({id:"new-version"});});
async function open(){await screen.findByRole("button",{name:"查看公式"});fireEvent.click(screen.getByRole("button",{name:"查看公式"}));await screen.findByText(detail.rawExpression);}
it("read-only role sees real formula details, no approval and complete status/book pagination",async()=>{state.user.permissions=[HR_PERMISSIONS.HR_PAYROLL_RULE_READ];render(<PayrollFormulaReview/>);await open();expect(screen.getByText("Actual book · Actual net · V1")).toBeInTheDocument();expect(screen.queryByRole("button",{name:"批准用于模拟核对"})).toBeNull();fireEvent.change(screen.getByLabelText("公式状态"),{target:{value:"approved_for_simulation"}});await waitFor(()=>expect(state.api.payrollHistoryFormulas).toHaveBeenLastCalledWith("synthetic-token",1,20,{parseStatus:"approved_for_simulation"},expect.any(AbortSignal)));expect(screen.queryByText(detail.rawExpression)).toBeNull();fireEvent.click(screen.getByRole("button",{name:"公式下一页"}));await waitFor(()=>expect(state.api.payrollHistoryFormulas).toHaveBeenLastCalledWith("synthetic-token",2,20,{parseStatus:"approved_for_simulation"},expect.any(AbortSignal)));fireEvent.change(screen.getByLabelText("公式账套"),{target:{value:"book"}});await waitFor(()=>expect(state.api.payrollHistoryFormulas).toHaveBeenLastCalledWith("synthetic-token",1,20,{bookId:"book",parseStatus:"approved_for_simulation"},expect.any(AbortSignal)));});
it("review requires explicit reason, preserves failed input and retries via existing endpoint",async()=>{state.api.reviewPayrollFormula.mockRejectedValueOnce(new Error("synthetic failure"));render(<PayrollFormulaReview/>);await open();expect(screen.getByRole("button",{name:"批准用于模拟核对"})).toBeDisabled();fireEvent.change(screen.getByLabelText("公式复核理由"),{target:{value:"Reviewed actual expression"}});fireEvent.click(screen.getByRole("button",{name:"批准用于模拟核对"}));await screen.findByText(/synthetic failure/);expect(screen.getByLabelText("公式复核理由")).toHaveValue("Reviewed actual expression");fireEvent.click(screen.getByRole("button",{name:"批准用于模拟核对"}));await screen.findByText(/已批准用于模拟核对/);expect(state.api.reviewPayrollFormula).toHaveBeenLastCalledWith("formula",{decision:"approve_for_simulation",reason:"Reviewed actual expression"},"synthetic-token");expect(state.api.reviewPayrollFormula).toHaveBeenCalledTimes(2);expect(screen.getByRole("button",{name:"拒绝公式"})).toBeDisabled();});
it("synchronous duplicate writes own one flight and committed success survives refresh failure",async()=>{let finish!:(value:object)=>void;state.api.reviewPayrollFormula.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));render(<PayrollFormulaReview/>);await open();fireEvent.change(screen.getByLabelText("公式复核理由"),{target:{value:"Actual review"}});const button=screen.getByRole("button",{name:"批准用于模拟核对"});fireEvent.click(button);fireEvent.click(button);expect(state.api.reviewPayrollFormula).toHaveBeenCalledTimes(1);state.api.payrollHistoryFormulas.mockRejectedValue(new Error("refresh failure"));await act(async()=>finish({id:"new"}));await screen.findByText(/复核已提交，列表刷新失败/);expect(screen.getByRole("button",{name:"批准用于模拟核对"})).toBeDisabled();});
it("blocked syntax permits rejection and terminal versions have no decision controls",async()=>{state.api.payrollHistoryFormula.mockResolvedValue({...detail,rawCondition:"independent legacy condition",approvalEligibility:"blocked"});const view=render(<PayrollFormulaReview/>);await open();expect(screen.getByText("independent legacy condition")).toBeInTheDocument();fireEvent.change(screen.getByLabelText("公式复核理由"),{target:{value:"Condition needs conversion"}});expect(screen.getByRole("button",{name:"批准用于模拟核对"})).toBeDisabled();fireEvent.click(screen.getByRole("button",{name:"拒绝公式"}));await waitFor(()=>expect(state.api.reviewPayrollFormula).toHaveBeenCalledWith("formula",{decision:"reject",reason:"Condition needs conversion"},"synthetic-token"));view.unmount();state.api.payrollHistoryFormula.mockResolvedValue({...detail,parseStatus:"approved_for_simulation",approvalEligibility:"terminal",reviewReason:"Actual prior approval"});render(<PayrollFormulaReview/>);await open();expect(screen.getByText(/Actual prior approval/)).toBeInTheDocument();expect(screen.queryByLabelText("公式复核理由")).toBeNull();});
it("context changes abort old reads and discard selected detail/review reason",async()=>{const view=render(<PayrollFormulaReview/>);await open();const signal=state.api.payrollHistoryFormula.mock.calls[0]![2] as AbortSignal;fireEvent.change(screen.getByLabelText("公式复核理由"),{target:{value:"Old park review"}});state.user={...state.user,park_id:"other"};view.rerender(<PayrollFormulaReview/>);expect(signal.aborted).toBe(true);expect(screen.queryByText(detail.rawExpression)).toBeNull();expect(screen.queryByLabelText("公式复核理由")).toBeNull();});
it("non-rule readers do not probe formulas or books",()=>{state.user.permissions=[HR_PERMISSIONS.HR_PAYROLL_FORMULA_REVIEW];render(<PayrollFormulaReview/>);expect(state.api.payrollHistoryFormulas).not.toHaveBeenCalled();expect(state.api.payrollHistoryBooks).not.toHaveBeenCalled();});

it("pending review keeps filters stable and old detail responses cannot cross contexts",async()=>{let finish!:(value:object)=>void;state.api.reviewPayrollFormula.mockImplementation(()=>new Promise(resolve=>{finish=resolve;}));const view=render(<PayrollFormulaReview/>);await open();fireEvent.change(screen.getByLabelText("公式复核理由"),{target:{value:"Actual review"}});fireEvent.click(screen.getByRole("button",{name:"批准用于模拟核对"}));fireEvent.change(screen.getByLabelText("公式状态"),{target:{value:"rejected"}});expect(screen.getByLabelText("公式状态")).toHaveValue("");state.user={...state.user,park_id:"other"};view.rerender(<PayrollFormulaReview/>);await act(async()=>finish({id:"new"}));expect(screen.queryByText(/已批准用于模拟核对；/)).toBeNull();expect(screen.queryByText(detail.rawExpression)).toBeNull();});

it("actual payroll rules page mounts one complete formula work area independently of history summaries",async()=>{state.user.permissions.push(HR_PERMISSIONS.HR_PAYROLL_PAGE);for(const fn of [state.api.payrollHistoryCatalogItems,state.api.payrollHistoryTaxRules,state.api.payrollHistoryReviewCases])fn.mockResolvedValue({items:[],total:0,page:1,page_size:20});render(<HrPayrollClient/>);await open();expect(screen.getByRole("heading",{name:"工资公式复核"})).toBeInTheDocument();expect(state.api.payrollHistoryFormulas).toHaveBeenCalledTimes(1);expect(state.api.payrollHistoryFormulas).toHaveBeenCalledWith("synthetic-token",1,20,{},expect.any(AbortSignal));});
