import {act,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {useState} from 'react';
import {beforeEach,expect,it,vi} from 'vitest';
import {RewardCategoryVersions} from '../../app/hr/rewards/RewardCategoryVersions';
const state=vi.hoisted(()=>({api:{rewardCategoryVersions:vi.fn(),publishRewardCategoryVersion:vi.fn()}}));
vi.mock('../../lib/hr-api',()=>({hrApi:state.api}));
vi.mock('../../lib/authz',()=>({getAccessToken:()=> 'synthetic-token'}));
const category={id:'category',code:'SYN',name:'合成制度',kind:'reward' as const,impactLevel:'normal',status:'enabled',versionNo:23},version={id:'v23',name:'合成现行定义',kind:'reward' as const,impactLevel:'normal' as const,versionNo:23,description:'原制度完整说明',createdAt:'2026-10-09'};
const page=(p=1)=>({category:{id:'category',code:'SYN',status:'enabled',currentVersionNo:23},items:[{...version,id:`v${p===1?23:3}`,versionNo:p===1?23:3}],total:23,page:p,page_size:20});
function Harness({refreshFailure=false}:{refreshFailure?:boolean}){const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');return <><RewardCategoryVersions categories={[category]} busy={busy} publish={async job=>{setBusy(true);try{await job();setNotice(refreshFailure?'发布已成功，刷新失败勿重复提交':'发布已成功');return true;}catch{return false;}finally{setBusy(false);}}}/><p role="status">{notice}</p></>;}
beforeEach(()=>{vi.resetAllMocks();state.api.rewardCategoryVersions.mockImplementation((_id:string,p:number)=>Promise.resolve(page(p)));state.api.publishRewardCategoryVersion.mockResolvedValue({...version,id:'v24',versionNo:24});});
async function open(){fireEvent.click(screen.getByRole('button',{name:'维护版本 合成制度'}));await screen.findByDisplayValue('原制度完整说明');return screen.getByRole('form',{name:'发布奖惩类别版本'});}
it('loads complete current definition and retains it through history pages then publishes exact expected version',async()=>{render(<Harness/>);expect(state.api.rewardCategoryVersions).not.toHaveBeenCalled();const f=await open();fireEvent.change(screen.getByLabelText('版本名称'),{target:{value:'合成更新制度'}});fireEvent.click(screen.getByRole('button',{name:'版本下一页'}));await screen.findByText('版本 3 · 合成现行定义');expect(screen.getByLabelText('版本名称')).toHaveValue('合成更新制度');expect(screen.getByLabelText('制度说明')).toHaveValue('原制度完整说明');fireEvent.submit(f);await screen.findByText('发布已成功');expect(state.api.publishRewardCategoryVersion).toHaveBeenCalledWith('category',{expectedVersionNo:23,kind:'reward',name:'合成更新制度',impactLevel:'normal',description:'原制度完整说明'},'synthetic-token',expect.any(String));expect(screen.queryByRole('form')).toBeNull();});
it('unknown publication failure retains the draft and exact retry key, blocking changed payload',async()=>{state.api.publishRewardCategoryVersion.mockRejectedValueOnce(Error('合成结果未知'));render(<Harness/>);const f=await open();fireEvent.submit(f);await screen.findByText('合成结果未知');const key=state.api.publishRewardCategoryVersion.mock.calls[0]![3];expect(screen.getByLabelText('制度说明')).toHaveValue('原制度完整说明');fireEvent.change(screen.getByLabelText('版本名称'),{target:{value:'不同内容'}});fireEvent.submit(f);await screen.findByText('上次发布结果尚未确认，请保持原内容重试，或刷新核对后重新办理。');expect(state.api.publishRewardCategoryVersion).toHaveBeenCalledTimes(1);fireEvent.change(screen.getByLabelText('版本名称'),{target:{value:'合成现行定义'}});fireEvent.submit(f);await screen.findByText('发布已成功');expect(state.api.publishRewardCategoryVersion.mock.calls[1]![3]).toBe(key);});
it('synchronous write locking prevents duplicate publication and closes before refresh failure',async()=>{let finish=()=>{};state.api.publishRewardCategoryVersion.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({...version,versionNo:24});}));render(<Harness refreshFailure/>);const f=await open();fireEvent.submit(f);fireEvent.submit(f);expect(state.api.publishRewardCategoryVersion).toHaveBeenCalledTimes(1);expect(screen.getByLabelText('制度说明')).toBeDisabled();expect(screen.getByRole('button',{name:'关闭版本维护'})).toBeDisabled();await act(async()=>finish());await screen.findByText('发布已成功，刷新失败勿重复提交');expect(screen.queryByRole('form')).toBeNull();});
it('history failure preserves draft and recovers locally without publishing',async()=>{render(<Harness/>);await open();fireEvent.change(screen.getByLabelText('制度说明'),{target:{value:'已编辑说明'}});state.api.rewardCategoryVersions.mockRejectedValueOnce(Error('历史读取失败'));fireEvent.click(screen.getByRole('button',{name:'版本下一页'}));await screen.findByText('历史读取失败');expect(screen.getByLabelText('制度说明')).toHaveValue('已编辑说明');expect(screen.getByRole('button',{name:'发布类别新版本'})).toBeDisabled();fireEvent.click(screen.getByRole('button',{name:'重试类别历史'}));await screen.findByText('版本 3 · 合成现行定义');await waitFor(()=>expect(screen.getByRole('button',{name:'发布类别新版本'})).toBeEnabled());expect(state.api.publishRewardCategoryVersion).not.toHaveBeenCalled();});
it('a changed current version retains the old draft and requires explicit reload',async()=>{render(<Harness/>);await open();fireEvent.change(screen.getByLabelText('制度说明'),{target:{value:'保留旧稿'}});state.api.rewardCategoryVersions.mockResolvedValueOnce({...page(2),category:{...page(2).category,currentVersionNo:24}});fireEvent.click(screen.getByRole('button',{name:'版本下一页'}));await screen.findByText('现行类别已更新，请保留需要的草稿内容，再重载现行定义。');expect(screen.getByLabelText('制度说明')).toHaveValue('保留旧稿');expect(screen.getByRole('button',{name:'发布类别新版本'})).toBeDisabled();state.api.rewardCategoryVersions.mockResolvedValueOnce({...page(),category:{...page().category,currentVersionNo:24},items:[{...version,id:'v24',versionNo:24,description:'最新说明'}],total:24});fireEvent.click(screen.getByRole('button',{name:'放弃草稿并重载现行定义'}));await screen.findByDisplayValue('最新说明');expect(screen.getByRole('button',{name:'发布类别新版本'})).toBeEnabled();});
it('closed target ignores late history and never populates a stale editor',async()=>{let finish:(v:ReturnType<typeof page>)=>void=()=>{};let signal:AbortSignal|undefined;state.api.rewardCategoryVersions.mockImplementation((_id,_page,_token,s)=>{signal=s;return new Promise(resolve=>{finish=resolve;});});render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:'维护版本 合成制度'}));await waitFor(()=>expect(state.api.rewardCategoryVersions).toHaveBeenCalledTimes(1));fireEvent.click(screen.getByRole('button',{name:'关闭版本维护'}));expect(signal?.aborted).toBe(true);await act(async()=>finish(page()));expect(screen.queryByRole('form')).toBeNull();});
it('malformed or duplicate version metadata fails closed',async()=>{state.api.rewardCategoryVersions.mockResolvedValueOnce({...page(),items:[version,version]});render(<Harness/>);fireEvent.click(screen.getByRole('button',{name:'维护版本 合成制度'}));await screen.findByText('奖惩类别版本响应无效，请重试。');expect(screen.queryByRole('form')).toBeNull();expect(state.api.publishRewardCategoryVersion).not.toHaveBeenCalled();});
