import {act,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrTrainingClient} from "../../app/hr/training/HrTrainingClient";
import type {HrTrainingPlan,HrTrainingPlanDetail} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]},api:{trainingPlans:vi.fn(),trainingCourses:vi.fn(),trainingCourseOptions:vi.fn(),trainingRequirementOptions:vi.fn(),trainingPositionRequirements:vi.fn(),trainingPositionRequirementGaps:vi.fn(),trainingEmployeeOptions:vi.fn(),trainingPlan:vi.fn(),createTrainingCourse:vi.fn(),createTrainingPlan:vi.fn(),createTrainingPositionRequirement:vi.fn(),reviseTrainingPlanFacts:vi.fn(),correctTraining:vi.fn(),trainingPlanAction:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));
vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));
vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));
vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=><>{children}</>}));
const plan:HrTrainingPlan={id:"plan",code:"SYN-P",name:"合成培训计划",courseTitle:"合成课程",status:"completed",mandatory:true,startDate:"2026-10-01",endDate:"2026-10-08",factRevision:3,participantCount:1,completedCount:1};
const detail:HrTrainingPlanDetail={...plan,snapshot:{},participants:[{id:"participant",employeeName:"合成学员",status:"completed",checkedInAt:null,completedHours:"8",score:"80",correctionVersion:2,canAct:true}]};
const form=(name:string)=>screen.getByRole("button",{name}).closest("form")!;
const change=(target:HTMLFormElement,name:string,value:string)=>fireEvent.change(target.querySelector(`[name="${name}"]`)!,{target:{value}});
beforeEach(()=>{Object.values(state.api).forEach(m=>m.mockReset());state.user={id:"actor",park_id:"park",permissions:[H.HR_TRAINING_PAGE,H.HR_TRAINING_READ,H.HR_TRAINING_COURSE_MANAGE,H.HR_TRAINING_PLAN_MANAGE,H.HR_TRAINING_PROGRESS_MANAGE]};state.api.trainingPlans.mockResolvedValue({items:[plan],total:21});state.api.trainingCourses.mockResolvedValue([]);state.api.trainingCourseOptions.mockResolvedValue({courses:[{id:"course",title:"合成课程",hours:"8"}]});state.api.trainingRequirementOptions.mockResolvedValue({courses:[],positions:[{id:"position",positionName:"合成岗位",positionCode:"SYN-J"}]});state.api.trainingPositionRequirements.mockResolvedValue([]);state.api.trainingPositionRequirementGaps.mockResolvedValue([]);state.api.trainingEmployeeOptions.mockResolvedValue({items:[],total:0,page:1,page_size:20});state.api.trainingPlan.mockResolvedValue(detail);state.api.correctTraining.mockResolvedValue({});state.api.reviseTrainingPlanFacts.mockResolvedValue({});state.api.createTrainingCourse.mockResolvedValue({});state.api.createTrainingPlan.mockResolvedValue({});state.api.createTrainingPositionRequirement.mockResolvedValue({});});
async function open(){render(<HrTrainingClient/>);await screen.findByText("合成培训计划");fireEvent.click(screen.getByRole("button",{name:"查看"}));await screen.findByRole("button",{name:"保存培训结果更正"});}
it("retains rejected requirement selections and retries their exact target",async()=>{state.api.createTrainingPositionRequirement.mockRejectedValueOnce(new Error("合成必修失败")).mockResolvedValue({});render(<HrTrainingClient/>);await screen.findByRole("option",{name:"合成岗位 · SYN-J"});const f=form("设置必修");change(f,"position","position");change(f,"requiredCourse","course");fireEvent.submit(f);await screen.findByText("合成必修失败");expect(f.elements.namedItem("position")).toHaveValue("position");expect(f.elements.namedItem("requiredCourse")).toHaveValue("course");fireEvent.submit(f);await waitFor(()=>expect(f.elements.namedItem("position")).toHaveValue(""));expect(state.api.createTrainingPositionRequirement).toHaveBeenNthCalledWith(2,{positionId:"position",courseId:"course"},"synthetic-token");});
it("retains rejected plan fact reason and revised dates",async()=>{state.api.reviseTrainingPlanFacts.mockRejectedValue(new Error("合成日期失败"));await open();const f=form("保存课程及日期");change(f,"courseName","合成新课程");change(f,"startDate","2026-10-02");change(f,"reason","合成修订原因");fireEvent.submit(f);await screen.findByText("合成日期失败");expect(f.elements.namedItem("reason")).toHaveValue("合成修订原因");expect(f.elements.namedItem("startDate")).toHaveValue("2026-10-02");expect(state.api.reviseTrainingPlanFacts).toHaveBeenCalledWith("plan",{courseName:"合成新课程",startDate:"2026-10-02",expectedRevision:3,reason:"合成修订原因"},"synthetic-token");});
it("preserves rejected result draft and exact zero correction payload",async()=>{state.api.correctTraining.mockRejectedValueOnce(new Error("合成结果失败")).mockResolvedValue({});await open();const f=form("保存培训结果更正");change(f,"scoreAction","write");change(f,"score","0");change(f,"reason","合成成绩依据");fireEvent.submit(f);await screen.findByText("合成结果失败");expect(f.elements.namedItem("reason")).toHaveValue("合成成绩依据");expect(f.elements.namedItem("score")).toHaveValue(0);fireEvent.submit(f);await screen.findByText("培训操作已保存。");expect(state.api.correctTraining).toHaveBeenNthCalledWith(2,"participant",{correctedScore:"0",expectedRevision:2,reason:"合成成绩依据"},"synthetic-token");});
it("committed result keeps success, clears stale form and reads target only once when detail refresh fails",async()=>{await open();state.api.trainingPlan.mockRejectedValueOnce(new Error("合成详情失败"));const f=form("保存培训结果更正");change(f,"reason","合成依据");change(f,"scoreAction","write");change(f,"score","81");fireEvent.submit(f);await screen.findByText("合成详情失败");expect(screen.getByText(/培训操作已保存/)).toHaveTextContent("培训操作已保存");expect(screen.queryByRole("button",{name:"保存培训结果更正"})).toBeNull();expect(state.api.correctTraining).toHaveBeenCalledTimes(1);expect(state.api.trainingPlan).toHaveBeenCalledTimes(2);expect(state.api.trainingPlans).toHaveBeenCalledTimes(2);});
it("list refresh failure does not erase saved status when target detail succeeds",async()=>{await open();state.api.trainingPlans.mockRejectedValueOnce(new Error("合成列表失败"));change(form("保存培训结果更正"),"reason","合成依据");change(form("保存培训结果更正"),"scoreAction","write");change(form("保存培训结果更正"),"score","81");fireEvent.submit(form("保存培训结果更正"));await screen.findByText("合成列表失败");expect(screen.getByText(/培训操作已保存/)).toHaveTextContent("培训操作已保存");expect(state.api.trainingPlan).toHaveBeenCalledTimes(2);});
it("locks double submit, fields, target navigation, close and page through pending write",async()=>{let finish=()=>{};state.api.correctTraining.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({});}));await open();const f=form("保存培训结果更正");change(f,"reason","合成依据");change(f,"scoreAction","write");change(f,"score","81");fireEvent.submit(f);fireEvent.submit(f);expect(state.api.correctTraining).toHaveBeenCalledTimes(1);for(const name of ["查看","关闭","刷新","下一页"])expect(screen.getByRole("button",{name})).toBeDisabled();expect(f.elements.namedItem("reason")).toBeDisabled();expect(form("保存课程").elements.namedItem("title")).toBeDisabled();await act(async()=>finish());await screen.findByText("培训操作已保存。");});
it("course commit is not reported as failed or left as a retry draft when options reload fails",async()=>{render(<HrTrainingClient/>);await screen.findByText("合成培训计划");const f=form("保存课程");for(const [n,v] of Object.entries({code:"SYN-C",title:"合成新课程",category:"合成类别",hours:"8"}))change(f,n,v);state.api.trainingCourseOptions.mockRejectedValueOnce(new Error("合成选项失败"));fireEvent.submit(f);await screen.findByText("合成选项失败");expect(screen.getByText(/培训操作已保存/)).toHaveTextContent("培训操作已保存");await waitFor(()=>expect(f.elements.namedItem("title")).toHaveValue(""));expect(state.api.createTrainingCourse).toHaveBeenCalledTimes(1);});
it("identity replacement ignores old committed result and performs no stale reload",async()=>{let finish=()=>{};state.api.correctTraining.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({});}));const {rerender}=render(<HrTrainingClient/>);await screen.findByText("合成培训计划");fireEvent.click(screen.getByRole("button",{name:"查看"}));await screen.findByRole("button",{name:"保存培训结果更正"});change(form("保存培训结果更正"),"reason","旧上下文依据");change(form("保存培训结果更正"),"scoreAction","write");change(form("保存培训结果更正"),"score","81");fireEvent.submit(form("保存培训结果更正"));expect(state.api.correctTraining).toHaveBeenCalledTimes(1);state.user={...state.user,park_id:"other"};rerender(<HrTrainingClient/>);await waitFor(()=>expect(state.api.trainingPlans).toHaveBeenCalledTimes(2));await act(async()=>finish());expect(state.api.trainingPlans).toHaveBeenCalledTimes(2);expect(state.api.trainingPlan).toHaveBeenCalledTimes(1);expect(screen.queryByText(/培训操作已保存/)).toBeNull();});

it("committed plan clears submitted participants even if subsequent options fail",async()=>{state.api.trainingEmployeeOptions.mockResolvedValue({items:[{id:"employee",fullName:"合成参训人",employeeCode:"SYN-E"}],total:1,page:1,page_size:20});render(<HrTrainingClient/>);fireEvent.click(await screen.findByRole("checkbox",{name:"合成参训人 · SYN-E"}));const f=form("创建计划");for(const [n,v] of Object.entries({code:"SYN-NEW",name:"合成新计划",course:"course",startDate:"2026-10-10",endDate:"2026-10-11"}))change(f,n,v);state.api.trainingCourseOptions.mockRejectedValueOnce(new Error("合成计划选项失败"));fireEvent.submit(f);await screen.findByText("合成计划选项失败");await waitFor(()=>expect(f.elements.namedItem("name")).toHaveValue(""));expect(new FormData(f).getAll("employees")).toEqual([]);expect(state.api.createTrainingPlan).toHaveBeenCalledTimes(1);expect(state.api.createTrainingPlan).toHaveBeenCalledWith(expect.objectContaining({name:"合成新计划",employeeIds:["employee"]}),"synthetic-token");});
