import {act,fireEvent,render,screen,waitFor,within} from "@testing-library/react";
import {beforeEach,expect,it,vi} from "vitest";
import {HR_PERMISSIONS as H} from "@jinhu/shared";
import {HrWorkReportsClient} from "../../app/hr/work-reports/HrWorkReportsClient";
import type {HrWorkReport,HrWorkReportPage} from "../../lib/hr-api";
const state=vi.hoisted(()=>({user:{id:"actor",park_id:"park",permissions:[] as string[]},api:{workReportsPage:vi.fn(),goals:vi.fn(),createWorkReport:vi.fn(),updateWorkReport:vi.fn(),submitWorkReport:vi.fn(),cancelWorkReport:vi.fn(),reviewWorkReport:vi.fn()}}));
vi.mock("../../lib/auth-context",()=>({useAuthUser:()=>state.user}));vi.mock("../../lib/authz",()=>({getAccessToken:()=>"synthetic-token"}));vi.mock("../../lib/hr-api",()=>({hrApi:state.api}));vi.mock("../../components/auth/PermissionGuard",()=>({PermissionGuard:({children}:{children:React.ReactNode})=><>{children}</>}));
function report(n:number,team=false):HrWorkReport{return{id:`${team?"team":"mine"}-${n}`,employeeName:team?"合成员工":null,reportType:"daily",periodStart:"2026-10-01",periodEnd:"2026-10-01",title:`${team?"团队":"本人"}${n}`,completedWork:"合成工作",nextPlan:null,risks:null,questionsAndSuggestions:null,collaborationNeeds:null,hours:"0",status:team?"submitted":"draft",submissionNo:1,reviewComment:null,submittedAt:null,reviewedAt:null,goalSuggestions:[]};}
function page(team=false,p=1,total=43):HrWorkReportPage{return{items:Array.from({length:Math.max(0,Math.min(20,total-(p-1)*20))},(_,i)=>report((p-1)*20+i+1,team)),total,page:p,page_size:20,summary:{pending:team?Math.min(35,total):0,returned:Math.min(5,total)}};}
const nav=(name="我的汇报")=>within(screen.getByRole("navigation",{name:`${name}分页`}));
const draftForm=()=>screen.getByRole("button",{name:"保存草稿"}).closest("form")!;
function change(form:HTMLFormElement,name:string,value:string){fireEvent.change(form.querySelector(`[name="${name}"]`)!,{target:{value}});}
async function reviewForm(){const row=(await screen.findByText("合成员工 · 团队1 · 2026-10-01")).closest("article")!;fireEvent.click(within(row).getByText("审核",{exact:true}));return within(row).getByRole("button",{name:"提交审核"}).closest("form")!;}
beforeEach(()=>{Object.values(state.api).forEach(m=>m.mockReset());state.user={id:"actor",park_id:"park",permissions:[H.HR_WORK_REPORTS_PAGE,H.HR_WORK_REPORT_SELF_READ,H.HR_WORK_REPORT_DRAFT,H.HR_WORK_REPORT_SUBMIT]};state.api.workReportsPage.mockImplementation(async(team:boolean,p=1)=>page(team,p));state.api.goals.mockResolvedValue([]);for(const name of ["createWorkReport","updateWorkReport","submitWorkReport","cancelWorkReport","reviewWorkReport"] as const)state.api[name].mockResolvedValue({});});
it("review-only actor reads and pages team totals without own or goal queries",async()=>{state.user.permissions=[H.HR_WORK_REPORTS_PAGE,H.HR_WORK_REPORT_REVIEW];render(<HrWorkReportsClient/>);await screen.findByText("合成员工 · 团队1 · 2026-10-01");expect(screen.queryByRole("region",{name:"我的汇报"})).toBeNull();expect(state.api.goals).not.toHaveBeenCalled();expect(state.api.workReportsPage.mock.calls.every(c=>c[0]===true)).toBe(true);expect(screen.getByText("35")).toBeInTheDocument();fireEvent.click(nav("团队汇报").getByRole("button",{name:"下一页"}));await screen.findByText("合成员工 · 团队21 · 2026-10-01");expect(state.api.workReportsPage).toHaveBeenLastCalledWith(true,2,{},"synthetic-token",expect.any(AbortSignal));});
it("own paging and filters reset page while preserving separate complete totals",async()=>{render(<HrWorkReportsClient/>);await screen.findByText("本人1 · 2026-10-01");fireEvent.click(nav().getByRole("button",{name:"下一页"}));await screen.findByText("本人21 · 2026-10-01");fireEvent.change(screen.getByRole("combobox",{name:"我的汇报状态"}),{target:{value:"returned"}});await waitFor(()=>expect(state.api.workReportsPage).toHaveBeenLastCalledWith(false,1,{status:"returned"},"synthetic-token",expect.any(AbortSignal)));expect(screen.getByText("43")).toBeInTheDocument();expect(state.api.goals).not.toHaveBeenCalled();});
it("own and optional goal failures do not hide authorized team work",async()=>{state.user.permissions.push(H.HR_WORK_REPORT_REVIEW,H.HR_GOAL_SELF_READ);state.api.goals.mockRejectedValue(new Error("合成目标不可用"));state.api.workReportsPage.mockImplementation(async(team:boolean,p:number)=>{if(!team)throw new Error("合成本人读取失败");return page(true,p)});render(<HrWorkReportsClient/>);await screen.findByText("合成员工 · 团队1 · 2026-10-01");await screen.findByText("合成本人读取失败");await screen.findByText("合成目标不可用");expect(screen.getByRole("button",{name:"写汇报"})).toBeEnabled();});
it("stale response after changed filter is aborted and ignored",async()=>{let finish=(p:HrWorkReportPage)=>{};state.api.workReportsPage.mockImplementationOnce(()=>new Promise(resolve=>{finish=resolve}));render(<HrWorkReportsClient/>);await waitFor(()=>expect(state.api.workReportsPage).toHaveBeenCalledTimes(1));const signal=state.api.workReportsPage.mock.calls[0]![4] as AbortSignal;fireEvent.change(screen.getByRole("combobox",{name:"我的汇报类型"}),{target:{value:"weekly"}});await screen.findByText("本人1 · 2026-10-01");expect(signal.aborted).toBe(true);const old=page();old.items[0]={...old.items[0]!,title:"迟到旧数据"};await act(async()=>finish(old));expect(screen.queryByText(/迟到旧数据/)).toBeNull();});
it("malformed page fails visibly and retries; shrinking total clamps to a real page",async()=>{state.api.workReportsPage.mockResolvedValueOnce({...page(),items:[]});render(<HrWorkReportsClient/>);await screen.findByText("工作汇报分页响应无效，请重新读取。");fireEvent.click(nav().getByRole("button",{name:"刷新我的汇报"}));await screen.findByText("本人1 · 2026-10-01");state.api.workReportsPage.mockImplementation(async(t:boolean,p:number)=>page(t,p,1));fireEvent.click(nav().getByRole("button",{name:"下一页"}));await waitFor(()=>expect(state.api.workReportsPage).toHaveBeenLastCalledWith(false,1,{},"synthetic-token",expect.any(AbortSignal)));await screen.findByText("本人1 · 2026-10-01");expect(nav().getByRole("button",{name:"下一页"})).toBeDisabled();});
it("draft rejection retains actual fields and retry sends explicit zero hours",async()=>{state.api.createWorkReport.mockRejectedValueOnce(new Error("合成草稿失败")).mockResolvedValue({});render(<HrWorkReportsClient/>);fireEvent.click(screen.getByRole("button",{name:"写汇报"}));const f=draftForm();for(const [n,v] of Object.entries({title:"合成草稿标题",periodStart:"2026-10-09",periodEnd:"2026-10-09",completedWork:"合成完成工作",hours:"0"}))change(f,n,v);fireEvent.submit(f);await screen.findByText("合成草稿失败");expect(f.elements.namedItem("title")).toHaveValue("合成草稿标题");expect(f.elements.namedItem("completedWork")).toHaveValue("合成完成工作");fireEvent.submit(f);await screen.findByText("工作汇报草稿已保存。");expect(screen.queryByRole("button",{name:"保存草稿"})).toBeNull();expect(state.api.createWorkReport).toHaveBeenNthCalledWith(2,expect.objectContaining({title:"合成草稿标题",hours:0,goalSuggestions:[]}),"synthetic-token");});
it("failed review preserves return decision and comment for retry",async()=>{state.user.permissions=[H.HR_WORK_REPORTS_PAGE,H.HR_WORK_REPORT_REVIEW];state.api.reviewWorkReport.mockRejectedValue(new Error("合成审核失败"));render(<HrWorkReportsClient/>);const f=await reviewForm();change(f,"action","returned");change(f,"comment","合成退回意见");fireEvent.submit(f);await screen.findByText("审核未保存，意见已保留，请核对错误提示后重试。");expect(f.elements.namedItem("comment")).toHaveValue("合成退回意见");expect(f.elements.namedItem("action")).toHaveValue("returned");expect(state.api.reviewWorkReport).toHaveBeenCalledWith("team-1",{action:"returned",comment:"合成退回意见"},"synthetic-token");});
it("one review writer locks navigation and keeps success after subsequent read fails",async()=>{state.user.permissions=[H.HR_WORK_REPORTS_PAGE,H.HR_WORK_REPORT_REVIEW,H.HR_WORK_REPORT_DRAFT];let finish=()=>{};state.api.reviewWorkReport.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({})}));render(<HrWorkReportsClient/>);const f=await reviewForm();change(f,"comment","合成确认依据");fireEvent.submit(f);fireEvent.submit(f);expect(state.api.reviewWorkReport).toHaveBeenCalledTimes(1);expect(f.elements.namedItem("comment")).toBeDisabled();expect(nav("团队汇报").getByRole("button",{name:"下一页"})).toBeDisabled();expect(screen.getByRole("button",{name:"写汇报"})).toBeDisabled();state.api.workReportsPage.mockRejectedValue(new Error("合成刷新失败"));await act(async()=>finish());await screen.findByText("合成刷新失败");expect(screen.getByRole("status")).toHaveTextContent("工作汇报审核已保存");expect(screen.queryByRole("button",{name:"提交审核"})).toBeNull();});
it("draft-only actor can create without acquiring read or goal permission",async()=>{state.user.permissions=[H.HR_WORK_REPORTS_PAGE,H.HR_WORK_REPORT_DRAFT];render(<HrWorkReportsClient/>);fireEvent.click(screen.getByRole("button",{name:"写汇报"}));const f=draftForm();change(f,"title","合成仅草稿");change(f,"periodStart","2026-10-09");change(f,"periodEnd","2026-10-09");fireEvent.submit(f);await screen.findByText("工作汇报草稿已保存。");expect(state.api.workReportsPage).not.toHaveBeenCalled();expect(state.api.goals).not.toHaveBeenCalled();});
it("context replacement removes old rows and ignores old write completion",async()=>{let finish=()=>{};state.api.submitWorkReport.mockImplementation(()=>new Promise(resolve=>{finish=()=>resolve({})}));const {rerender}=render(<HrWorkReportsClient/>);const row=(await screen.findByText("本人1 · 2026-10-01")).closest("article")!;fireEvent.click(within(row).getByRole("button",{name:"提交审核"}));state.user={...state.user,park_id:"other"};state.api.workReportsPage.mockResolvedValue(page(false,1,0));rerender(<HrWorkReportsClient/>);expect(screen.queryByText("本人1 · 2026-10-01")).toBeNull();await waitFor(()=>expect(state.api.workReportsPage).toHaveBeenCalledTimes(2));await act(async()=>finish());expect(state.api.workReportsPage).toHaveBeenCalledTimes(2);expect(screen.queryByText(/工作汇报已提交审核/)).toBeNull();});
it("editing retains zero first progress and additional saved suggestions without goal read permission",async()=>{const data=page(false,1,1);data.items[0]!.goalSuggestions=[{goalId:"goal-a",goalName:"已关联A",proposedProgress:"0",proposedCurrentValue:"3",suggestionSummary:"首项"},{goalId:"goal-b",goalName:"已关联B",proposedProgress:"0.5",proposedCurrentValue:null,suggestionSummary:"次项"}];state.api.workReportsPage.mockResolvedValue(data);render(<HrWorkReportsClient/>);await screen.findByText("本人1 · 2026-10-01");fireEvent.click(screen.getByRole("button",{name:"编辑"}));const f=draftForm();expect(f.elements.namedItem("proposedProgress")).toHaveValue(0);fireEvent.submit(f);await screen.findByText("工作汇报草稿已保存。");expect(state.api.updateWorkReport).toHaveBeenCalledWith("mine-1",expect.objectContaining({goalSuggestions:[{goalId:"goal-a",proposedProgress:0,proposedCurrentValue:3,suggestionSummary:"首项"},{goalId:"goal-b",proposedProgress:0.5,suggestionSummary:"次项"}]}),"synthetic-token");expect(state.api.goals).not.toHaveBeenCalled();});
