BEGIN;
DO $$BEGIN IF(SELECT count(*) FROM sys_role WHERE tenant_id='10000001' AND park_id='20000001' AND code IN('HR_MANAGER','DEPARTMENT_MANAGER','EMPLOYEE_SELF_SERVICE') AND is_deleted=false AND is_enabled=true AND status='enabled')<>3 THEN RAISE EXCEPTION 'Expected exact active HR talent role baseline';END IF;END$$;
CREATE TEMP TABLE hr_talent_permissions(code varchar(128)PRIMARY KEY,name varchar(128),resource varchar(64),action varchar(64),sort_no integer)ON COMMIT DROP;
INSERT INTO hr_talent_permissions VALUES
 ('hr:talent','人才发展','hr.talent','page',882),('hr:talent:read','读取园区人才数据','hr.talent','read',883),('hr:talent:team_read','读取组织树人才数据','hr.talent','team_read',884),('hr:talent:self_read','读取本人人才发展','hr.talent','self_read',885),
 ('hr:talent:profile_create','冻结人才画像','hr.talent','profile_create',886),('hr:talent:review','执行人才盘点','hr.talent','review',887),('hr:succession:read','读取继任规划','hr.succession','read',888),('hr:succession:manage','管理继任规划','hr.succession','manage',889),
 ('hr:development:manage','管理发展计划','hr.development','manage',890),('hr:development:self_action','完成本人发展行动','hr.development','self_action',891);
INSERT INTO sys_permission(id,tenant_id,park_id,code,name,parent_id,resource,action,permission_path,perm_path,permission_level,level,sort_no,permission_type,perm_type,frontend_route,is_system,is_builtin,is_tenant_custom,visible,keep_alive,always_show,is_enabled,status,create_time,update_time,is_deleted,version,remark)
SELECT uuid_generate_v4(),'10000001','20000001',x.code,x.name,p.id,x.resource,x.action,'hr/'||x.code,'hr/'||x.code,3,3,x.sort_no,CASE WHEN x.action='page' THEN 'page' ELSE 'api' END,CASE WHEN x.action='page' THEN 20 ELSE 30 END,CASE WHEN x.action='page' THEN '/hr/talent' ELSE NULL END,true,true,false,x.action='page',true,false,true,'enabled',now(),now(),false,1,'HR T6 talent least privilege atom' FROM hr_talent_permissions x CROSS JOIN LATERAL(SELECT id FROM sys_permission WHERE tenant_id='10000001' AND code='hr' AND is_deleted=false LIMIT 1)p
ON CONFLICT(tenant_id,code)WHERE is_deleted=false DO UPDATE SET name=EXCLUDED.name,park_id=EXCLUDED.park_id,parent_id=EXCLUDED.parent_id,resource=EXCLUDED.resource,action=EXCLUDED.action,sort_no=EXCLUDED.sort_no,permission_type=EXCLUDED.permission_type,perm_type=EXCLUDED.perm_type,frontend_route=EXCLUDED.frontend_route,visible=EXCLUDED.visible,is_enabled=true,status='enabled',is_deleted=false,update_time=now(),remark=EXCLUDED.remark;
CREATE TEMP TABLE hr_talent_grants(role_code varchar(64),permission_code varchar(128),PRIMARY KEY(role_code,permission_code))ON COMMIT DROP;
INSERT INTO hr_talent_grants VALUES
 ('HR_MANAGER','hr:talent'),('HR_MANAGER','hr:talent:read'),('HR_MANAGER','hr:talent:profile_create'),('HR_MANAGER','hr:talent:review'),('HR_MANAGER','hr:succession:read'),('HR_MANAGER','hr:succession:manage'),('HR_MANAGER','hr:development:manage'),
 ('DEPARTMENT_MANAGER','hr:talent'),('DEPARTMENT_MANAGER','hr:talent:team_read'),('DEPARTMENT_MANAGER','hr:development:manage'),('DEPARTMENT_MANAGER','hr:development:self_action'),
 ('EMPLOYEE_SELF_SERVICE','hr:talent'),('EMPLOYEE_SELF_SERVICE','hr:talent:self_read'),('EMPLOYEE_SELF_SERVICE','hr:development:self_action');
INSERT INTO rel_role_perm(tenant_id,park_id,role_id,permission_id,create_time,update_time,is_deleted,version,remark)
SELECT '10000001','20000001',r.id,p.id,now(),now(),false,1,'HR T6 talent least privilege' FROM hr_talent_grants g JOIN sys_role r ON r.tenant_id='10000001' AND r.park_id='20000001' AND r.code=g.role_code AND r.is_deleted=false AND r.is_enabled=true AND r.status='enabled' JOIN sys_permission p ON p.tenant_id='10000001' AND p.park_id='20000001' AND p.code=g.permission_code AND p.is_deleted=false
ON CONFLICT(tenant_id,park_id,role_id,permission_id)WHERE is_deleted=false DO UPDATE SET is_deleted=false,update_time=now(),remark=EXCLUDED.remark;
DO $$BEGIN
 IF(SELECT count(*) FROM sys_permission WHERE tenant_id='10000001' AND park_id='20000001' AND code IN(SELECT code FROM hr_talent_permissions) AND is_deleted=false AND is_enabled=true)<>10 THEN RAISE EXCEPTION 'HR talent permissions incomplete';END IF;
 IF EXISTS(SELECT 1 FROM rel_role_perm rp JOIN sys_role r ON(r.id,r.tenant_id,r.park_id)=(rp.role_id,rp.tenant_id,rp.park_id) JOIN sys_permission p ON(p.id,p.tenant_id,p.park_id)=(rp.permission_id,rp.tenant_id,rp.park_id) WHERE rp.tenant_id='10000001' AND rp.park_id='20000001' AND rp.is_deleted=false AND ((r.code='DEPARTMENT_MANAGER' AND p.code IN('hr:talent:read','hr:talent:profile_create','hr:talent:review','hr:succession:read','hr:succession:manage')) OR (r.code='EMPLOYEE_SELF_SERVICE' AND p.code IN('hr:talent:read','hr:talent:team_read','hr:talent:profile_create','hr:talent:review','hr:succession:read','hr:succession:manage','hr:development:manage')))) THEN RAISE EXCEPTION 'HR talent broad permission leaked';END IF;
END$$;
COMMIT;
