#!/usr/bin/env sh
set -eu
ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
RUN_ID="${YUZHOU_MIGRATION_RUN_ID:-}"
DATABASE="${YUZHOU_SQLSERVER_DATABASE:-YuzhouHR_Lab_20260820_intake01}"
CONTAINER="${YUZHOU_SQLSERVER_CONTAINER:-jinhu_yuzhou_migration_lab-sqlserver-1}"
CREDENTIAL_FILE="${YUZHOU_ETL_CREDENTIAL_FILE:-$ROOT_DIR/database/import-reports/yuzhou-hr/20260820_intake01-etl.env}"
OUTPUT_ROOT="${YUZHOU_STAGING_ROOT:-$ROOT_DIR/database/import-reports/yuzhou-hr}"
fail(){ printf 'ERROR: %s\n' "$1" >&2; exit 1; }
[ "${ALLOW_YUZHOU_MIGRATION:-no}" = yes ] || fail "set ALLOW_YUZHOU_MIGRATION=yes"
printf %s "$RUN_ID" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$' || fail "invalid run id"
[ -f "$CREDENTIAL_FILE" ] || fail "read-only ETL credential file is missing"
. "$CREDENTIAL_FILE"
[ "$YUZHOU_SQLSERVER_ETL_LOGIN" != sa ] || fail "sa is forbidden for extraction"
[ "$YUZHOU_SQLSERVER_DATABASE" = "$DATABASE" ] || fail "credential database mismatch"
[ "$(docker inspect --format '{{ index .Config.Labels "com.docker.compose.project" }}' "$CONTAINER" 2>/dev/null || true)" = jinhu_yuzhou_migration_lab ] || fail "container is not the migration lab"
ro="$(docker exec -e ETL_PASSWORD="$YUZHOU_SQLSERVER_ETL_PASSWORD" "$CONTAINER" bash -lc '/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U "$1" -P "$ETL_PASSWORD" -d "$2" -h -1 -W -Q "SET NOCOUNT ON; SELECT CONVERT(int,is_read_only) FROM sys.databases WHERE name=DB_NAME();"' q "$YUZHOU_SQLSERVER_ETL_LOGIN" "$DATABASE" | tr -d '[:space:]')"
[ "$ro" = 1 ] || fail "source database is not read-only"
OUT="$OUTPUT_ROOT/staging-$RUN_ID"; [ ! -e "$OUT" ] || fail "staging run already exists"; mkdir -p "$OUT"; chmod 700 "$OUT"
query(){ name="$1"; sql="$2"; docker exec -e ETL_PASSWORD="$YUZHOU_SQLSERVER_ETL_PASSWORD" "$CONTAINER" bash -lc '/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U "$1" -P "$ETL_PASSWORD" -d "$2" -y 0 -w 65535 -Q "$3"' q "$YUZHOU_SQLSERVER_ETL_LOGIN" "$DATABASE" "$sql" | tr -d '\r\n' >"$OUT/$name"; node -e 'JSON.parse(require("fs").readFileSync(process.argv[1],"utf8"))' "$OUT/$name"; chmod 600 "$OUT/$name"; }
DATES=""; i=1; while [ "$i" -le 31 ]; do DATES="$DATES,date$i"; i=$((i+1)); done
query attendance.raw.json "SET NOCOUNT ON; SELECT id,tablename,year,month$DATES FROM dbo.timekeeptable ORDER BY id FOR JSON PATH,INCLUDE_NULL_VALUES;"
query policies.raw.json "SET NOCOUNT ON; SELECT id,des,rightscope,CONVERT(varchar(40),oldage) oldage,CONVERT(varchar(40),oldage_e) oldage_e,CONVERT(varchar(40),oldage_p) oldage_p,CONVERT(varchar(40),oldage_pc) oldage_pc,CONVERT(varchar(40),remedy) remedy,CONVERT(varchar(40),remedy_e) remedy_e,CONVERT(varchar(40),remedy_p) remedy_p,CONVERT(varchar(40),remedy_pc) remedy_pc,CONVERT(varchar(40),losework) losework,CONVERT(varchar(40),losework_e) losework_e,CONVERT(varchar(40),losework_p) losework_p,CONVERT(varchar(40),losework_pc) losework_pc,CONVERT(varchar(40),fund) fund,CONVERT(varchar(40),fund_e) fund_e,CONVERT(varchar(40),fund_p) fund_p,CONVERT(varchar(40),fund_pc) fund_pc,CONVERT(varchar(40),wound) wound,CONVERT(varchar(40),wound_e) wound_e,CONVERT(varchar(40),wound_p) wound_p,CONVERT(varchar(40),wound_pc) wound_pc,CONVERT(varchar(40),bear) bear,CONVERT(varchar(40),bear_e) bear_e,CONVERT(varchar(40),bear_p) bear_p,CONVERT(varchar(40),bear_pc) bear_pc,CONVERT(varchar(40),oldage2) oldage2,CONVERT(varchar(40),oldage_e2) oldage_e2,CONVERT(varchar(40),oldage_p2) oldage_p2,CONVERT(varchar(40),oldage_pc2) oldage_pc2,CONVERT(varchar(40),remedy2) remedy2,CONVERT(varchar(40),remedy_e2) remedy_e2,CONVERT(varchar(40),remedy_p2) remedy_p2,CONVERT(varchar(40),remedy_pc2) remedy_pc2,CONVERT(varchar(40),losework2) losework2,CONVERT(varchar(40),losework_e2) losework_e2,CONVERT(varchar(40),losework_p2) losework_p2,CONVERT(varchar(40),losework_pc2) losework_pc2,CONVERT(varchar(40),fund2) fund2,CONVERT(varchar(40),fund_e2) fund_e2,CONVERT(varchar(40),fund_p2) fund_p2,CONVERT(varchar(40),fund_pc2) fund_pc2,CONVERT(varchar(40),wound2) wound2,CONVERT(varchar(40),wound_e2) wound_e2,CONVERT(varchar(40),wound_p2) wound_p2,CONVERT(varchar(40),wound_pc2) wound_pc2,CONVERT(varchar(40),bear2) bear2,CONVERT(varchar(40),bear_e2) bear_e2,CONVERT(varchar(40),bear_p2) bear_p2,CONVERT(varchar(40),bear_pc2) bear_pc2 FROM dbo.insure_method ORDER BY id FOR JSON PATH,INCLUDE_NULL_VALUES;"
query insurance.raw.json "SET NOCOUNT ON; SELECT id,recyear,recmonth,person,CONVERT(varchar(40),base) base,CONVERT(varchar(40),base_oldage) base_oldage,CONVERT(varchar(40),oldage) oldage,CONVERT(varchar(40),oldage_e) oldage_e,CONVERT(varchar(40),oldage_p) oldage_p,CONVERT(varchar(40),oldage_pc) oldage_pc,CONVERT(varchar(40),base_remedy) base_remedy,CONVERT(varchar(40),remedy) remedy,CONVERT(varchar(40),remedy_e) remedy_e,CONVERT(varchar(40),remedy_p) remedy_p,CONVERT(varchar(40),remedy_pc) remedy_pc,CONVERT(varchar(40),base_losework) base_losework,CONVERT(varchar(40),losework) losework,CONVERT(varchar(40),losework_e) losework_e,CONVERT(varchar(40),losework_p) losework_p,CONVERT(varchar(40),losework_pc) losework_pc,CONVERT(varchar(40),base_fund) base_fund,CONVERT(varchar(40),fund) fund,CONVERT(varchar(40),fund_e) fund_e,CONVERT(varchar(40),fund_p) fund_p,CONVERT(varchar(40),fund_pc) fund_pc,CONVERT(varchar(40),base_bear) base_bear,CONVERT(varchar(40),bear) bear,CONVERT(varchar(40),bear_e) bear_e,CONVERT(varchar(40),bear_p) bear_p,CONVERT(varchar(40),bear_pc) bear_pc,CONVERT(varchar(40),base_wound) base_wound,CONVERT(varchar(40),wound) wound,CONVERT(varchar(40),wound_e) wound_e,CONVERT(varchar(40),wound_p) wound_p,CONVERT(varchar(40),wound_pc) wound_pc,fundflag,oldageflag,woundflag,remedyflag,loseworkflag,bearflag FROM dbo.person_insure ORDER BY id FOR JSON PATH,INCLUDE_NULL_VALUES;"
node "$ROOT_DIR/scripts/transform-yuzhou-t3-attendance-insurance.mjs" "$OUT"
printf 'YUZHOU_T3_EXTRACT_OK run_id=%s output=%s\n' "$RUN_ID" "$OUT"
