#!/usr/bin/env sh
set -eu
umask 077
ROOT="$(CDPATH= cd -- "$(dirname -- "$0")/.."&&pwd)"; RUN="${YUZHOU_MIGRATION_RUN_ID:-}"; DB="${YUZHOU_TARGET_DATABASE:-}"; PG="${YUZHOU_POSTGRES_CONTAINER:-jinhu-smart-park-postgres}"; EXPECTED_PROJECT="${YUZHOU_EXPECTED_POSTGRES_COMPOSE_PROJECT:-jinhu_hr_migration_lab}"; STAGE="${YUZHOU_STAGING_DIR:-$ROOT/database/import-reports/yuzhou-hr/staging-t4-$RUN}"; HASH="${YUZHOU_T4_BUSINESS_SHA256:-}"; TENANT="${YUZHOU_TARGET_TENANT_ID:-10000001}"; PARK="${YUZHOU_TARGET_PARK_ID:-20000001}"; MODE="${YUZHOU_T4_LOAD_MODE:-hot_history}"
fail(){ echo "ERROR: $1" >&2;exit 1;}; [ "${ALLOW_YUZHOU_MIGRATION:-no}" = yes ]||fail "set ALLOW_YUZHOU_MIGRATION=yes"; printf %s "$RUN"|grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$'||fail "invalid run"; printf %s "$DB"|grep -Eq '^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$'||fail "unsafe database"; printf %s "$HASH"|grep -Eq '^[0-9a-f]{64}$'||fail "pin business hash"; case "$MODE" in hot_history) PERIOD_START=2024-01-01; PERIOD_END=2026-12-31; EXPECTED_ROWS=8342; EXPECTED_ITEMS=190880; EXPECTED_NET=15723009.9100; EXPECTED_CLOSES=266;; cold_archive) PERIOD_START=2010-01-01; PERIOD_END=2023-12-31; EXPECTED_ROWS=37750; EXPECTED_ITEMS=887140; EXPECTED_NET=86471046.8900; EXPECTED_CLOSES=1165;; *) fail "YUZHOU_T4_LOAD_MODE must be hot_history or cold_archive";; esac; [ "${YUZHOU_T4_PERIOD_START:-$PERIOD_START}" = "$PERIOD_START" ]&&[ "${YUZHOU_T4_PERIOD_END:-$PERIOD_END}" = "$PERIOD_END" ]||fail "T4 mode period override rejected"; [ "$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$PG" 2>/dev/null||true)" = "$EXPECTED_PROJECT" ]||fail "wrong compose project"
E="$ROOT/.trellis/tasks/08-24-yuzhou-hr-t4-payroll-history/research/source-evidence-manifest.json"; node - "$STAGE" "$E" "$HASH" <<'NODE'
const fs=require('fs'),c=require('crypto'),[d,e,h]=process.argv.slice(2),m=JSON.parse(fs.readFileSync(d+'/manifest.json')),x=JSON.parse(fs.readFileSync(e));if(m.businessContentSha256!==h||m.sourceBackupSha256!==x.sourceBackupSha256||m.actualSourceRows!=='46092')throw Error('manifest mismatch');for(const[n,v]of Object.entries(m.outputFiles))if(c.createHash('sha256').update(fs.readFileSync(d+'/'+n)).digest('hex')!==v.fileSha256)throw Error(n+' hash mismatch');
NODE
TMP="/tmp/yuzhou-t4-$RUN"; trap 'docker exec "$PG" rm -rf "$TMP" >/dev/null 2>&1||true' EXIT; docker exec "$PG" mkdir -p "$TMP"; for f in scheme-memberships items formulas tax-rules closes payslips;do docker cp "$STAGE/$f.jsonl" "$PG:$TMP/$f.jsonl" >/dev/null;done; docker cp "$ROOT/scripts/sql/load-yuzhou-t4-payroll-history.sql" "$PG:$TMP/load.sql" >/dev/null; docker exec "$PG" chown -R postgres:postgres "$TMP"; docker exec "$PG" chmod -R go-rwx "$TMP"
SNAP="$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1])).sourceBackupSha256)' "$E")"; CAT="$(node -e 'process.stdout.write(JSON.parse(require("fs").readFileSync(process.argv[1])).catalogAggregateSha256)' "$STAGE/manifest.json")"; MH="$(shasum -a256 "$STAGE/manifest.json"|awk '{print $1}')"
docker exec "$PG" psql -X -v ON_ERROR_STOP=1 -U jinhu -d "$DB" -v run="$RUN" -v db="$DB" -v tenant="$TENANT" -v park="$PARK" -v mode="$MODE" -v expected_rows="$EXPECTED_ROWS" -v expected_items="$EXPECTED_ITEMS" -v expected_net="$EXPECTED_NET" -v expected_closes="$EXPECTED_CLOSES" -v period_start="$PERIOD_START" -v period_end="$PERIOD_END" -v snap="$SNAP" -v catalog="$CAT" -v bh="$HASH" -v mh="$MH" -v memberships_path="$TMP/scheme-memberships.jsonl" -v items_path="$TMP/items.jsonl" -v formulas_path="$TMP/formulas.jsonl" -v tax_path="$TMP/tax-rules.jsonl" -v closes_path="$TMP/closes.jsonl" -v payslips_path="$TMP/payslips.jsonl" -f "$TMP/load.sql"
docker exec "$PG" psql -X -At -F '|' -U jinhu -d "$DB" -c "SELECT run_id,status,counts FROM migration_batch WHERE run_id='$RUN'"
