#!/usr/bin/env sh
set -eu
umask 077
ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
fail(){ printf 'ERROR: %s\n' "$1" >&2; exit 1; }
RUN_ID="${YUZHOU_TRAINING_REWARD_HISTORY_RUN_ID:-}"; DB="${YUZHOU_TARGET_DATABASE:-}"; STAGE="${YUZHOU_TRAINING_REWARD_HISTORY_STAGING_DIR:-}"; ACTOR="${YUZHOU_MATERIALIZATION_ACTOR_USER_ID:-}"; PG="${YUZHOU_POSTGRES_CONTAINER:-jinhu-smart-park-postgres}"; PROJECT="${YUZHOU_EXPECTED_POSTGRES_COMPOSE_PROJECT:-jinhu_hr_migration_lab}"; TENANT="${YUZHOU_TARGET_TENANT_ID:-10000001}"; PARK="${YUZHOU_TARGET_PARK_ID:-20000001}"; SNAPSHOT="${YUZHOU_BACKUP_SHA256:-}"
[ "${ALLOW_YUZHOU_MIGRATION:-no}" = yes ] || fail "set ALLOW_YUZHOU_MIGRATION=yes"
printf %s "$RUN_ID"|grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$'||fail "invalid run id"
printf %s "$DB"|grep -Eq '^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$'||fail "unsafe target database"
printf %s "$ACTOR"|grep -Eq '^[0-9a-fA-F-]{36}$'||fail "materialization actor is required"
printf %s "$SNAPSHOT"|grep -Eq '^[0-9a-f]{64}$'||fail "backup hash is required"
[ -d "$STAGE" ]&&[ "$(stat -f '%Lp' "$STAGE" 2>/dev/null||stat -c '%a' "$STAGE")" = 700 ]||fail "controlled staging directory required"
[ -f "$STAGE/manifest.json" ]&&[ "$(stat -f '%Lp' "$STAGE/manifest.json" 2>/dev/null||stat -c '%a' "$STAGE/manifest.json")" = 600 ]||fail "controlled staging manifest required"
[ "$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$PG" 2>/dev/null||true)" = "$PROJECT" ]||fail "wrong PostgreSQL compose project"
stage_meta="$(node - "$STAGE" <<'NODE'
const {createHash}=require("crypto"),{readFileSync,statSync}=require("fs"),{join}=require("path");const stage=process.argv[2],manifest=JSON.parse(readFileSync(join(stage,"manifest.json"),"utf8"));const rows=name=>readFileSync(join(stage,name),"utf8").trim().split("\n").filter(Boolean).map(line=>JSON.parse(line.replaceAll("\\\\","\\")));const training=rows("training-history.jsonl"),reward=rows("reward-category.jsonl"),sha=p=>createHash("sha256").update(readFileSync(p)).digest("hex");if(manifest.productionImport!=="HOLD"||manifest.sourceReadOnly!==true||statSync(join(stage,"training-history.jsonl")).mode&0o777!==0o600||statSync(join(stage,"reward-category.jsonl")).mode&0o777!==0o600)throw Error("unsafe staging");if(training.length!==manifest.domains.trainingHistory.sourceRows||reward.length!==manifest.domains.rewardCategories.sourceRows||sha(join(stage,"training-history.jsonl"))!==manifest.domains.trainingHistory.fileSha256||sha(join(stage,"reward-category.jsonl"))!==manifest.domains.rewardCategories.fileSha256)throw Error("staging hash drift");const sourceRows=training.length+reward.length,loadedRows=training.filter(x=>x.status==="eligible").length+reward.filter(x=>x.status==="eligible").length,quarantinedRows=sourceRows-loadedRows;if(training.filter(x=>x.status==="eligible").length!==manifest.domains.trainingHistory.eligibleRows||reward.filter(x=>x.status==="eligible").length!==manifest.domains.rewardCategories.eligibleRows||quarantinedRows!==manifest.domains.trainingHistory.quarantinedRows+manifest.domains.rewardCategories.quarantinedRows)throw Error("staging accounting drift");process.stdout.write(JSON.stringify({sourceRows,loadedRows,quarantinedRows}));
NODE
)" || fail "training reward staging validation failed"
SOURCE_ROWS="$(node -e 'console.log(JSON.parse(process.argv[1]).sourceRows)' "$stage_meta")"; LOADED_ROWS="$(node -e 'console.log(JSON.parse(process.argv[1]).loadedRows)' "$stage_meta")"; QUARANTINED_ROWS="$(node -e 'console.log(JSON.parse(process.argv[1]).quarantinedRows)' "$stage_meta")"
combined="$(mktemp "${TMPDIR:-/tmp}/yuzhou-training-reward.XXXXXX")"; chmod 600 "$combined"; trap 'rm -f "$combined"; docker exec "$PG" rm -rf "/tmp/$RUN_ID" >/dev/null 2>&1||true' EXIT HUP INT TERM
cat "$STAGE/training-history.jsonl" "$STAGE/reward-category.jsonl" >"$combined"; remote="/tmp/$RUN_ID"; docker exec "$PG" mkdir -p "$remote"; docker cp "$combined" "$PG:$remote/input.jsonl"; docker exec "$PG" chown -R postgres:postgres "$remote"; docker exec "$PG" chmod -R go-rwx "$remote"
docker exec -i "$PG" psql -X -v ON_ERROR_STOP=1 -U jinhu -d "$DB" -v run="$RUN_ID" -v db="$DB" -v tenant="$TENANT" -v park="$PARK" -v actor="$ACTOR" -v snapshot="$SNAPSHOT" -v source_rows="$SOURCE_ROWS" -v loaded_rows="$LOADED_ROWS" -v quarantined_rows="$QUARANTINED_ROWS" -v path="$remote/input.jsonl" <<'SQL'
BEGIN; SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='5min'; SELECT set_config('yuzhou.training_reward_db',:'db',true); SELECT set_config('yuzhou.training_reward_run',:'run',true); SELECT set_config('yuzhou.training_reward_tenant',:'tenant',true); SELECT set_config('yuzhou.training_reward_park',:'park',true); SELECT set_config('yuzhou.training_reward_actor',:'actor',true);
DO $$BEGIN IF current_database()<>current_setting('yuzhou.training_reward_db') OR current_database()!~'^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$' THEN RAISE EXCEPTION'unsafe target'; END IF; END$$;
CREATE TEMP TABLE source_rows(payload jsonb); COPY source_rows FROM :'path';
DO $$BEGIN
 IF (SELECT count(*) FROM source_rows)<>:'source_rows'::bigint OR EXISTS(SELECT 1 FROM source_rows GROUP BY payload->>'sourceTable',payload->>'sourceIdentitySha256' HAVING count(*)<>1) THEN RAISE EXCEPTION 'source staging drift'; END IF;
 IF EXISTS(SELECT 1 FROM migration_batch WHERE run_id=current_setting('yuzhou.training_reward_run')) THEN RAISE EXCEPTION 'duplicate migration run'; END IF;
 IF NOT EXISTS(SELECT 1 FROM sys_user WHERE tenant_id=current_setting('yuzhou.training_reward_tenant') AND park_id=current_setting('yuzhou.training_reward_park') AND id=current_setting('yuzhou.training_reward_actor')::uuid AND status='enabled' AND is_deleted=false) THEN RAISE EXCEPTION 'materialization actor is unavailable'; END IF;
END$$;
INSERT INTO migration_batch(run_id,source_system,source_snapshot_sha256,target_database,phase,status,tool_version,started_at,counts) VALUES(:'run','yuzhou-v10',:'snapshot',:'db','load','running','training-reward-history-v1',now(),jsonb_build_object('sourceRows',:'source_rows'::bigint));
CREATE TEMP TABLE eligible_training AS SELECT payload,('YZ-TH-'||substr(payload->>'sourceIdentitySha256',1,16)) code FROM source_rows WHERE payload->>'domain'='training_history' AND payload->>'status'='eligible';
INSERT INTO hr_training_course(tenant_id,park_id,course_code,create_by,update_by) SELECT :'tenant',:'park',code,:'actor'::uuid,:'actor'::uuid FROM eligible_training;
INSERT INTO hr_training_course_version(tenant_id,park_id,course_id,version_no,title,category,hours,create_by) SELECT :'tenant',:'park',c.id,1,t.payload->'source'->>'courseName','legacy',(t.payload->'source'->>'hours')::numeric,:'actor'::uuid FROM eligible_training t JOIN hr_training_course c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.course_code=t.code;
INSERT INTO hr_training_plan(tenant_id,park_id,plan_code,plan_name,course_id,course_version_id,start_date,end_date,create_by,update_by) SELECT :'tenant',:'park',replace(t.code,'YZ-TH-','YZ-TP-'),t.payload->'source'->>'courseName',c.id,v.id,(t.payload->'source'->>'startDate')::date,(t.payload->'source'->>'endDate')::date,:'actor'::uuid,:'actor'::uuid FROM eligible_training t JOIN hr_training_course c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.course_code=t.code JOIN hr_training_course_version v ON v.tenant_id=c.tenant_id AND v.park_id=c.park_id AND v.course_id=c.id AND v.version_no=1;
INSERT INTO hr_training_participant(tenant_id,park_id,plan_id,employee_id) SELECT :'tenant',:'park',p.id,e.id FROM eligible_training t JOIN hr_training_plan p ON p.tenant_id=:'tenant' AND p.park_id=:'park' AND p.plan_code=replace(t.code,'YZ-TH-','YZ-TP-') JOIN legacy_record_map m ON m.source_system='yuzhou-v10' AND m.source_table='dbo.person' AND m.source_pk_canonical='person='||(t.payload->>'employeeCode') AND m.target_table='hr_employee' AND m.mapping_status IN('loaded','verified') AND m.is_active JOIN hr_employee e ON e.id=m.target_id AND e.tenant_id=:'tenant' AND e.park_id=:'park' AND NOT e.is_deleted;
UPDATE hr_training_plan p SET status='published',published_at=now(),snapshot=jsonb_build_object('courseTitle',v.title,'category',v.category,'provider',v.provider,'hours',v.hours::text,'participantCount',1),update_by=:'actor'::uuid,update_time=now() FROM hr_training_course_version v WHERE p.tenant_id=:'tenant' AND p.park_id=:'park' AND p.course_version_id=v.id AND p.plan_code LIKE 'YZ-TP-%';
UPDATE hr_training_plan SET status='in_progress',started_at=now(),update_by=:'actor'::uuid,update_time=now() WHERE tenant_id=:'tenant' AND park_id=:'park' AND plan_code LIKE 'YZ-TP-%';
UPDATE hr_training_participant tp SET status='completed',completed_at=(p.end_date::timestamp AT TIME ZONE 'Asia/Shanghai'),completed_hours=v.hours,update_time=now() FROM hr_training_plan p JOIN hr_training_course_version v ON v.id=p.course_version_id WHERE tp.plan_id=p.id AND tp.tenant_id=:'tenant' AND tp.park_id=:'park' AND p.plan_code LIKE 'YZ-TP-%';
UPDATE hr_training_plan SET status='completed',completed_at=now(),update_by=:'actor'::uuid,update_time=now() WHERE tenant_id=:'tenant' AND park_id=:'park' AND plan_code LIKE 'YZ-TP-%';
CREATE TEMP TABLE eligible_reward AS SELECT payload,('YZ-RC-'||(payload->'source'->>'code')) code FROM source_rows WHERE payload->>'domain'='reward_category' AND payload->>'status'='eligible';
INSERT INTO hr_reward_discipline_category(tenant_id,park_id,category_code,create_by,update_by) SELECT :'tenant',:'park',code,:'actor'::uuid,:'actor'::uuid FROM eligible_reward;
INSERT INTO hr_reward_discipline_category_version(tenant_id,park_id,category_id,version_no,kind,name,impact_level,create_by) SELECT :'tenant',:'park',c.id,1,r.payload->'source'->>'kind',r.payload->'source'->>'name','normal',:'actor'::uuid FROM eligible_reward r JOIN hr_reward_discipline_category c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.category_code=r.code;
INSERT INTO hr_legacy_training_reward_projection(tenant_id,park_id,migration_batch_id,source_table,source_identity_sha256,source_row_sha256,projection_kind,training_course_id,training_course_version_id,training_plan_id,training_participant_id) SELECT :'tenant',:'park',b.id,t.payload->>'sourceTable',t.payload->>'sourceIdentitySha256',t.payload->>'sourceRowSha256','training_history',c.id,v.id,p.id,tp.id FROM eligible_training t CROSS JOIN migration_batch b JOIN hr_training_course c ON c.course_code=t.code AND c.tenant_id=:'tenant' AND c.park_id=:'park' JOIN hr_training_course_version v ON v.course_id=c.id AND v.tenant_id=c.tenant_id AND v.park_id=c.park_id JOIN hr_training_plan p ON p.course_id=c.id AND p.tenant_id=c.tenant_id AND p.park_id=c.park_id JOIN hr_training_participant tp ON tp.plan_id=p.id AND tp.tenant_id=p.tenant_id AND tp.park_id=p.park_id WHERE b.run_id=:'run';
INSERT INTO hr_legacy_training_reward_projection(tenant_id,park_id,migration_batch_id,source_table,source_identity_sha256,source_row_sha256,projection_kind,reward_category_id,reward_category_version_id) SELECT :'tenant',:'park',b.id,r.payload->>'sourceTable',r.payload->>'sourceIdentitySha256',r.payload->>'sourceRowSha256','reward_category',c.id,v.id FROM eligible_reward r CROSS JOIN migration_batch b JOIN hr_reward_discipline_category c ON c.category_code=r.code AND c.tenant_id=:'tenant' AND c.park_id=:'park' JOIN hr_reward_discipline_category_version v ON v.category_id=c.id AND v.tenant_id=c.tenant_id AND v.park_id=c.park_id WHERE b.run_id=:'run';
INSERT INTO legacy_record_map(batch_id,source_system,source_table,source_pk_canonical,source_identity_sha256,source_row_sha256,target_table,target_id,mapping_status) SELECT b.id,'yuzhou-v10',p.source_table,'id='||p.source_identity_sha256,p.source_identity_sha256,p.source_row_sha256,CASE p.projection_kind WHEN'training_history'THEN'hr_training_plan' ELSE'hr_reward_discipline_category'END,COALESCE(p.training_plan_id,p.reward_category_id),'loaded' FROM hr_legacy_training_reward_projection p JOIN migration_batch b ON b.id=p.migration_batch_id WHERE b.run_id=:'run';
INSERT INTO migration_error(batch_id,category,error_code,source_identity_sha256,redacted_evidence,evidence_redacted,retryable) SELECT b.id,'mapping',payload->>'quarantineCode',payload->>'sourceIdentitySha256',jsonb_build_object('rule',payload->>'quarantineCode'),true,false FROM source_rows CROSS JOIN migration_batch b WHERE b.run_id=:'run' AND payload->>'status'='quarantined';
UPDATE migration_batch SET phase='verify',status='succeeded',finished_at=now(),counts=jsonb_build_object('sourceRows',:'source_rows'::bigint,'loadedRows',:'loaded_rows'::bigint,'quarantinedRows',:'quarantined_rows'::bigint) WHERE run_id=:'run';
COMMIT;
SQL
docker exec "$PG" psql -X -A -t -U jinhu -d "$DB" -c "SELECT json_build_object('status','PASS','trainingPlans',(SELECT count(*) FROM hr_legacy_training_reward_projection p JOIN migration_batch b ON b.id=p.migration_batch_id WHERE b.run_id='$RUN_ID' AND p.projection_kind='training_history'),'rewardCategories',(SELECT count(*) FROM hr_legacy_training_reward_projection p JOIN migration_batch b ON b.id=p.migration_batch_id WHERE b.run_id='$RUN_ID' AND p.projection_kind='reward_category'),'quarantined',(SELECT count(*) FROM migration_error e JOIN migration_batch b ON b.id=e.batch_id WHERE b.run_id='$RUN_ID'),'productionImport','HOLD');"
