#!/usr/bin/env sh
set -eu
ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.."&&pwd)";RUN_ID="${YUZHOU_MIGRATION_RUN_ID:-}";DB="${YUZHOU_TARGET_DATABASE:-}";TENANT="${YUZHOU_TARGET_TENANT_ID:-10000001}";PARK="${YUZHOU_TARGET_PARK_ID:-20000001}";STAGE="${YUZHOU_STAGING_DIR:-$ROOT_DIR/database/import-reports/yuzhou-hr/staging-$RUN_ID}";PG="${YUZHOU_POSTGRES_CONTAINER:-jinhu-smart-park-postgres}";EXPECTED_PROJECT="${YUZHOU_EXPECTED_POSTGRES_COMPOSE_PROJECT:-jinhu_hr_migration_lab}";SNAP="${YUZHOU_BACKUP_SHA256:-3ed50b9a2ba420c0fb7a9c2628f9a2d62a05e7a14ba574929bc145ac47a9036e}";TH="${YUZHOU_T2_TYPES_SHA256:-2382d80666b4c287d3ff0ae0d86194de8a80a445f80ca2a399f0e956208c1ab4}";CH="${YUZHOU_T2_CONTRACTS_SHA256:-939f78c96457f2856b28105ba8b89c8953fa6ebc839c591317db28fdfcfd7efc}";VH="${YUZHOU_T2_CHANGES_SHA256:-156436dd8895cb4c4102f7e38a85c90587d8eb28a24a069d59c6948b477b1d0e}"
TYPE_DICTIONARY_SHA256="${YUZHOU_T2_CONTRACT_TYPE_DICTIONARY_SHA256:-}"
STATE_DICTIONARY_SHA256="${YUZHOU_T2_CONTRACT_STATE_DICTIONARY_SHA256:-}"
fail(){ echo "ERROR: $1" >&2;exit 1;};[ "${ALLOW_YUZHOU_MIGRATION:-no}" = yes ]||fail "set mutation flag";printf %s "$RUN_ID"|grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$'||fail "invalid run id";printf %s "$DB"|grep -Eq '^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$'||fail "invalid isolated target database";for f in contract-types contracts contract-changes;do [ -f "$STAGE/$f.jsonl" ]||fail "staging file missing";done
for dictionary_sha in "$TYPE_DICTIONARY_SHA256" "$STATE_DICTIONARY_SHA256";do printf %s "$dictionary_sha"|grep -Eq '^[0-9a-f]{64}$'||fail "approved contract dictionary SHA-256 is required";done
[ "$(shasum -a 256 "$STAGE/contract-types.jsonl"|awk '{print $1}')" = "$TH" ]||fail "types staging SHA-256 mismatch";[ "$(shasum -a 256 "$STAGE/contracts.jsonl"|awk '{print $1}')" = "$CH" ]||fail "contracts staging SHA-256 mismatch";[ "$(shasum -a 256 "$STAGE/contract-changes.jsonl"|awk '{print $1}')" = "$VH" ]||fail "changes staging SHA-256 mismatch";[ "$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$PG")" = "$EXPECTED_PROJECT" ]||fail "wrong postgres project"
TMP="/tmp/yuzhou-t2-$RUN_ID";cleanup(){ docker exec "$PG" rm -rf "$TMP" >/dev/null 2>&1||true;};trap cleanup EXIT HUP INT TERM;docker exec "$PG" mkdir -p "$TMP";for f in contract-types contracts contract-changes;do docker cp "$STAGE/$f.jsonl" "$PG:$TMP/$f.jsonl";done;docker exec "$PG" chown -R postgres:postgres "$TMP";docker exec "$PG" chmod -R go-rwx "$TMP"
docker exec -i "$PG" psql -X -v ON_ERROR_STOP=1 -U jinhu -d "$DB" -v run="$RUN_ID" -v db="$DB" -v tenant="$TENANT" -v park="$PARK" -v snap="$SNAP" -v th="$TH" -v ch="$CH" -v vh="$VH" -v type_dictionary_sha="$TYPE_DICTIONARY_SHA256" -v state_dictionary_sha="$STATE_DICTIONARY_SHA256" -v tpath="$TMP/contract-types.jsonl" -v cpath="$TMP/contracts.jsonl" -v vpath="$TMP/contract-changes.jsonl" <<'SQL'
BEGIN;SET LOCAL lock_timeout='10s';SET LOCAL statement_timeout='5min';SELECT set_config('yz.run',:'run',true);SELECT set_config('yz.db',:'db',true);DO $$BEGIN IF current_database()<>current_setting('yz.db') OR current_database()!~'^jinhu_hr_migration_lab_' THEN RAISE EXCEPTION 'unsafe target';END IF;IF EXISTS(SELECT 1 FROM migration_batch WHERE run_id=current_setting('yz.run'))THEN RAISE EXCEPTION 'migration run already exists';END IF;END$$;
CREATE TEMP TABLE st(payload jsonb);CREATE TEMP TABLE sc(payload jsonb);CREATE TEMP TABLE sv(payload jsonb);COPY st FROM :'tpath';COPY sc FROM :'cpath';COPY sv FROM :'vpath';DO $$BEGIN IF(SELECT count(*)FROM st)<>4 OR(SELECT count(*)FROM sc)<>802 OR(SELECT count(*)FROM sv)<>357 THEN RAISE EXCEPTION 'T2 count drift';END IF;END$$;
CREATE TEMP TABLE st_contract_type_decision AS SELECT s.payload,d.* FROM st s CROSS JOIN LATERAL hr_resolve_legacy_dictionary(:'tenant',:'park','contract_type',:'type_dictionary_sha',s.payload->'source'->>'typeCode',s.payload->'source'->>'typeName',NULL) d;
CREATE TEMP TABLE st_contract_state_decision AS SELECT s.payload,d.* FROM sc s CROSS JOIN LATERAL hr_resolve_legacy_dictionary(:'tenant',:'park','contract_state',:'state_dictionary_sha',NULL,NULL,s.payload->'source'->>'legacyState') d;
DO $$BEGIN
 IF EXISTS(SELECT 1 FROM st_contract_type_decision WHERE decision<>'map' OR target_domain<>'contract_type_code' OR target_value!~'^[A-Za-z0-9][A-Za-z0-9._-]{0,63}$')THEN RAISE EXCEPTION 'T2 contract type dictionary contains unresolved values';END IF;
 IF EXISTS(SELECT 1 FROM st_contract_state_decision WHERE decision<>'map' OR target_domain<>'contract_status' OR target_value NOT IN('draft','active','expired','terminated','cancelled'))THEN RAISE EXCEPTION 'T2 contract state dictionary contains unresolved values';END IF;
END$$;
CREATE TEMP TABLE employee_before AS SELECT encode(digest(string_agg(concat_ws('|',id,employment_status,COALESCE(primary_org_id::text,''),COALESCE(position_id::text,'')),';'ORDER BY id),'sha256'),'hex')h FROM hr_employee WHERE tenant_id=:'tenant' AND park_id=:'park' AND NOT is_deleted;
INSERT INTO migration_batch(run_id,source_system,source_snapshot_sha256,target_database,phase,status,tool_version,started_at)VALUES(:'run','yuzhou-v10',:'snap',:'db','load','running','t2-contract-loader-v1',now());
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run'),contract_counts AS(SELECT count(*) n FROM st_contract_state_decision s JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=s.payload->'source'->>'employeeCode' AND NOT e.is_deleted),change_counts AS(SELECT count(*) n FROM sv s JOIN sc parent ON parent.payload->'source'->>'contractNo'=s.payload->'source'->>'contractNo' JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=parent.payload->'source'->>'employeeCode' AND NOT e.is_deleted)INSERT INTO migration_batch_item(batch_id,domain,source_object,phase,status,extracted_count,valid_count,rejected_count,checksum_sha256,started_at)SELECT id,'contract_type','dbo.compacttypecode','load','running',4,4,0,:'th',now()FROM b UNION ALL SELECT id,'contract','dbo.compact','load','running',802,contract_counts.n,802-contract_counts.n,:'ch',now()FROM b CROSS JOIN contract_counts UNION ALL SELECT id,'contract_change','dbo.compact_c','load','running',357,change_counts.n,357-change_counts.n,:'vh',now()FROM b CROSS JOIN change_counts;
INSERT INTO hr_contract_type(tenant_id,park_id,type_code,type_name,status,is_historical_import,remark)SELECT :'tenant',:'park',target_value,payload->'source'->>'typeName','enabled',true,'Yuzhou run='||:'run' FROM st_contract_type_decision;
INSERT INTO hr_contract(tenant_id,park_id,employee_id,contract_type_id,contract_no,start_date,end_date,probation_end_date,contract_term_months,signature_date,first_signature_date,last_signature_date,cumulative_term_months,renewal_count,status,probation_months,probation_salary,base_salary,confidentiality_agreement,non_compete_agreement,training_service_agreement,legacy_file_reference,legacy_text_present,is_historical_import,legacy_source_identity_sha256,legacy_source_row_sha256,source_snapshot,remark)
SELECT :'tenant',:'park',e.id,t.id,s.payload->'source'->>'contractNo',NULLIF(s.payload->'source'->>'startDate','')::date,NULLIF(s.payload->'source'->>'endDate','')::date,NULLIF(s.payload->'source'->>'probationEndDate','')::date,NULLIF(s.payload->'source'->>'derivedContractTermMonths','')::int,NULLIF(s.payload->'source'->>'signedDate','')::date,NULLIF(s.payload->'source'->>'signedDate','')::date,NULLIF(s.payload->'source'->>'signedDate','')::date,NULL,COALESCE(NULLIF(s.payload->'source'->>'legacyRenewalCount','')::int,0),s.target_value,NULLIF(s.payload->'source'->>'probationMonths','')::int,NULLIF(s.payload->'source'->>'probationSalary','')::numeric,NULLIF(s.payload->'source'->>'baseSalary','')::numeric,s.payload->'source'->>'confidentialityFlag'='1',s.payload->'source'->>'nonCompeteFlag'='1',s.payload->'source'->>'trainingServiceFlag'='1',NULL,(s.payload->'source'->>'legacyTextPresent')::int=1,true,s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256',jsonb_build_object('legacyState',s.payload->'source'->>'legacyState','unconfirmedTerm',s.payload->'source'->>'contractMonths','unconfirmedTotalTerm',s.payload->'source'->>'totalContractMonths','unconfirmedRenewalYears',s.payload->'source'->>'continueyears','contractTermDecision',s.payload->'source'->>'contractTermDecision','signatureDateDecision',s.payload->'source'->>'signatureDateDecision','renewalCountDecision',s.payload->'source'->>'renewalCountDecision'),'Yuzhou run='||:'run' FROM st_contract_state_decision s JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=s.payload->'source'->>'employeeCode' AND NOT e.is_deleted JOIN hr_contract_type t ON t.tenant_id=:'tenant' AND t.park_id=:'park' AND t.type_name=s.payload->'source'->>'typeName' AND NOT t.is_deleted;
INSERT INTO hr_contract_legacy_evidence(tenant_id,park_id,contract_id,evidence_kind,content_sha256,size_bytes,migration_status,source_identity_sha256)
SELECT :'tenant',:'park',c.id,'controlled_text',s.payload->'source'->>'legacyTextSha256',NULLIF(s.payload->'source'->>'legacyTextBytes','')::bigint,'hashed_only',encode(digest((s.payload->>'sourceIdentitySha256')||'|controlled_text','sha256'),'hex') FROM sc s JOIN hr_contract c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.legacy_source_identity_sha256=s.payload->>'sourceIdentitySha256' WHERE (s.payload->'source'->>'legacyTextPresent')::int=1;
INSERT INTO hr_contract_legacy_evidence(tenant_id,park_id,contract_id,evidence_kind,locator_sha256,migration_status,missing_reason,source_identity_sha256)
SELECT :'tenant',:'park',c.id,'file_manifest',s.payload->'source'->>'legacyFileLocatorSha256','not_extracted','SOURCE_FILE_NOT_EXTRACTED',encode(digest((s.payload->>'sourceIdentitySha256')||'|file_manifest','sha256'),'hex') FROM sc s JOIN hr_contract c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.legacy_source_identity_sha256=s.payload->>'sourceIdentitySha256' WHERE (s.payload->'source'->>'legacyFilePresent')::int=1;
INSERT INTO hr_contract_change(tenant_id,park_id,contract_id,sequence_no,change_type,previous_start_date,previous_end_date,new_start_date,new_end_date,signed_at,is_historical_import,legacy_source_identity_sha256,legacy_source_row_sha256,source_snapshot,remark)SELECT :'tenant',:'park',c.id,(s.payload->'source'->>'sequenceNo')::int,'renewal',NULL,NULL,(s.payload->'source'->>'startDate')::timestamp::date,NULLIF(s.payload->'source'->>'endDate','')::timestamp::date,NULLIF(s.payload->'source'->>'signedAt','')::timestamp,true,s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256',jsonb_build_object('legacySourceKey',s.payload->>'sourceKey','sequenceDerivation','ordered_source_tuple'),'Yuzhou run='||:'run' FROM sv s JOIN hr_contract c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.contract_no=s.payload->'source'->>'contractNo' AND NOT c.is_deleted;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run')INSERT INTO legacy_record_map(batch_id,source_system,source_table,source_pk_canonical,source_identity_sha256,source_row_sha256,target_table,target_id,mapping_status)SELECT b.id,'yuzhou-v10','dbo.compacttypecode','type='||(s.payload->>'sourceKey'),s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256','hr_contract_type',t.id,'loaded' FROM st_contract_type_decision s CROSS JOIN b JOIN hr_contract_type t ON t.type_code=s.target_value AND t.tenant_id=:'tenant' AND t.park_id=:'park' UNION ALL SELECT b.id,'yuzhou-v10','dbo.compact','contract='||(s.payload->>'sourceKey'),s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256','hr_contract',c.id,'loaded' FROM sc s CROSS JOIN b JOIN hr_contract c ON c.contract_no=s.payload->'source'->>'contractNo' AND c.tenant_id=:'tenant' AND c.park_id=:'park' UNION ALL SELECT b.id,'yuzhou-v10','dbo.compact_c','change='||(s.payload->>'sourceKey'),s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256','hr_contract_change',v.id,'loaded' FROM sv s CROSS JOIN b JOIN hr_contract c ON c.contract_no=s.payload->'source'->>'contractNo' AND c.tenant_id=:'tenant' AND c.park_id=:'park' JOIN hr_contract_change v ON v.contract_id=c.id AND v.sequence_no=(s.payload->'source'->>'sequenceNo')::int;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run'),i AS(SELECT id,batch_id,domain FROM migration_batch_item WHERE batch_id=(SELECT id FROM b))INSERT INTO migration_error(batch_id,batch_item_id,category,error_code,source_identity_sha256,redacted_evidence,evidence_redacted,retryable)SELECT b.id,i.id,'mapping','CONTRACT_EMPLOYEE_NOT_MAPPED',s.payload->>'sourceIdentitySha256',jsonb_build_object('rule','employee_mapping_missing'),true,false FROM sc s CROSS JOIN b JOIN i ON i.batch_id=b.id AND i.domain='contract' LEFT JOIN hr_employee e ON e.employee_code=s.payload->'source'->>'employeeCode' AND e.tenant_id=:'tenant' AND e.park_id=:'park' AND NOT e.is_deleted WHERE e.id IS NULL UNION ALL SELECT b.id,i.id,'mapping','CONTRACT_CHANGE_MASTER_NOT_FOUND',s.payload->>'sourceIdentitySha256',jsonb_build_object('rule','master_contract_missing'),true,false FROM sv s CROSS JOIN b JOIN i ON i.batch_id=b.id AND i.domain='contract_change' LEFT JOIN hr_contract c ON c.contract_no=s.payload->'source'->>'contractNo' AND c.tenant_id=:'tenant' AND c.park_id=:'park' WHERE c.id IS NULL;
UPDATE migration_batch_item i SET loaded_count=(SELECT count(*)FROM legacy_record_map m WHERE m.batch_id=i.batch_id AND m.target_table=CASE i.domain WHEN'contract_type'THEN'hr_contract_type'WHEN'contract'THEN'hr_contract'ELSE'hr_contract_change'END),status=CASE WHEN rejected_count>0 THEN'quarantined'ELSE'succeeded'END,finished_at=now()WHERE batch_id=(SELECT id FROM migration_batch WHERE run_id=:'run');
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run'),a AS(SELECT encode(digest(string_agg(concat_ws('|',id,employment_status,COALESCE(primary_org_id::text,''),COALESCE(position_id::text,'')),';'ORDER BY id),'sha256'),'hex')h FROM hr_employee WHERE tenant_id=:'tenant' AND park_id=:'park' AND NOT is_deleted)INSERT INTO migration_check(batch_id,check_code,expected_value,actual_value,tolerance,passed,evidence_sha256)SELECT b.id,'T2_CONTRACT_ACCOUNTING',to_jsonb(802),to_jsonb((SELECT count(*)FROM hr_contract WHERE remark='Yuzhou run='||:'run')+(SELECT count(*)FROM migration_error WHERE batch_id=b.id AND error_code='CONTRACT_EMPLOYEE_NOT_MAPPED')),'{}'::jsonb,(SELECT count(*)FROM hr_contract WHERE remark='Yuzhou run='||:'run')+(SELECT count(*)FROM migration_error WHERE batch_id=b.id AND error_code='CONTRACT_EMPLOYEE_NOT_MAPPED')=802,encode(digest('802','sha256'),'hex')FROM b UNION ALL SELECT b.id,'T2_CHANGE_ACCOUNTING',to_jsonb(357),to_jsonb((SELECT count(*)FROM hr_contract_change WHERE remark='Yuzhou run='||:'run')+(SELECT count(*)FROM migration_error WHERE batch_id=b.id AND error_code='CONTRACT_CHANGE_MASTER_NOT_FOUND')),'{}'::jsonb,(SELECT count(*)FROM hr_contract_change WHERE remark='Yuzhou run='||:'run')+(SELECT count(*)FROM migration_error WHERE batch_id=b.id AND error_code='CONTRACT_CHANGE_MASTER_NOT_FOUND')=357,encode(digest('357','sha256'),'hex')FROM b UNION ALL SELECT b.id,'T2_EMPLOYEE_UNCHANGED',to_jsonb(x.h),to_jsonb(a.h),'{}'::jsonb,x.h=a.h,encode(digest(x.h,'sha256'),'hex')FROM b CROSS JOIN employee_before x CROSS JOIN a;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run')INSERT INTO migration_rollback_point(batch_id,rollback_code,reversible_scope,cleanup_manifest,evidence_sha256,verified_at)SELECT id,'T2_CONTRACTS',jsonb_build_object('runId',:'run'),jsonb_build_object('tables',ARRAY['hr_contract_reminder_outbox','hr_contract_reminder_action','hr_contract_reminder','hr_contract_legacy_evidence','hr_contract_change','hr_contract','hr_contract_type']),encode(digest(:'run','sha256'),'hex'),now()FROM b;UPDATE migration_batch SET phase='verify',status=CASE WHEN EXISTS(SELECT 1 FROM migration_check WHERE batch_id=migration_batch.id AND NOT passed)THEN'failed'ELSE'succeeded'END,counts=jsonb_build_object('types',4,'contractsLoaded',(SELECT count(*)FROM legacy_record_map WHERE batch_id=migration_batch.id AND target_table='hr_contract'),'contractsQuarantined',(SELECT count(*)FROM migration_error WHERE batch_id=migration_batch.id AND error_code='CONTRACT_EMPLOYEE_NOT_MAPPED'),'changesLoaded',(SELECT count(*)FROM legacy_record_map WHERE batch_id=migration_batch.id AND target_table='hr_contract_change'),'changesQuarantined',(SELECT count(*)FROM migration_error WHERE batch_id=migration_batch.id AND error_code='CONTRACT_CHANGE_MASTER_NOT_FOUND')),finished_at=now()WHERE run_id=:'run';DO $$BEGIN IF EXISTS(SELECT 1 FROM migration_check c JOIN migration_batch b ON b.id=c.batch_id WHERE b.run_id=current_setting('yz.run') AND NOT c.passed)THEN RAISE EXCEPTION 'T2 verification failed';END IF;END$$;COMMIT;
SQL
docker exec "$PG" psql -X -A -t -F '|' -U jinhu -d "$DB" -c "SELECT run_id,status,counts FROM migration_batch WHERE run_id='$RUN_ID'"
