#!/usr/bin/env sh
set -eu
ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"; RUN_ID="${YUZHOU_MIGRATION_RUN_ID:-}"; DB="${YUZHOU_TARGET_DATABASE:-}"; TENANT="${YUZHOU_TARGET_TENANT_ID:-10000001}"; PARK="${YUZHOU_TARGET_PARK_ID:-20000001}"; STAGE="${YUZHOU_STAGING_DIR:-$ROOT_DIR/database/import-reports/yuzhou-hr/staging-$RUN_ID}"; PG="${YUZHOU_POSTGRES_CONTAINER:-jinhu-smart-park-postgres}"; EXPECTED_PROJECT="${YUZHOU_EXPECTED_POSTGRES_COMPOSE_PROJECT:-jinhu_hr_migration_lab}"
AH="${YUZHOU_T3_ATTENDANCE_SHA256:-9060321bf7a7d7f935f6c5dfbae7aba2774d28fd254d4e0d2b5a0957ad251c62}"; PH="${YUZHOU_T3_POLICIES_SHA256:-dadab284fb59d6bbf3c3baa5d52b356b6c18f8e9e11fdab5a62c4669f566dbdb}"; IH="${YUZHOU_T3_INSURANCE_SHA256:-fc76166540dea2056cd7c012a545de26435ae362abb26af7efd7802dc7c6d033}"; SNAP="${YUZHOU_BACKUP_SHA256:-3ed50b9a2ba420c0fb7a9c2628f9a2d62a05e7a14ba574929bc145ac47a9036e}"
RECEIPT="${YUZHOU_SOURCE_RESTORE_RECEIPT_SHA256:-}"; CATALOG="${YUZHOU_SOURCE_CATALOG_SHA256:-}"; BUSINESS="${YUZHOU_SOURCE_BUSINESS_SHA256:-}"; MAPPING="${YUZHOU_MAPPING_CONTRACT_SHA256:-}"
fail(){ printf 'ERROR: %s\n' "$1" >&2; exit 1; }
[ "${ALLOW_YUZHOU_MIGRATION:-no}" = yes ] || fail "set mutation flag"; printf %s "$RUN_ID"|grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$'||fail "invalid run id"; printf %s "$DB"|grep -Eq '^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$'||fail "invalid isolated target database"
for value in "$RECEIPT" "$CATALOG" "$BUSINESS" "$MAPPING"; do printf %s "$value"|grep -Eq '^[0-9a-f]{64}$'||fail "T3 current source binding is required"; done
for f in attendance policies insurance; do [ -f "$STAGE/$f.jsonl" ]||fail "staging file missing"; done
[ -f "$STAGE/manifest.json" ] || fail "staging manifest missing"
[ "$(stat -f '%Lp' "$STAGE/manifest.json" 2>/dev/null || stat -c '%a' "$STAGE/manifest.json")" = 600 ] || fail "staging manifest must be mode 0600"
[ "$(shasum -a 256 "$STAGE/attendance.jsonl"|awk '{print $1}')" = "$AH" ]||fail "attendance staging SHA-256 mismatch"; [ "$(shasum -a 256 "$STAGE/policies.jsonl"|awk '{print $1}')" = "$PH" ]||fail "policies staging SHA-256 mismatch"; [ "$(shasum -a 256 "$STAGE/insurance.jsonl"|awk '{print $1}')" = "$IH" ]||fail "insurance staging SHA-256 mismatch"
node - "$STAGE/manifest.json" "$SNAP" "$AH" "$PH" "$IH" "$RECEIPT" "$CATALOG" "$BUSINESS" "$MAPPING" <<'NODE' || fail "T3 staging manifest binding mismatch"
const fs=require('fs'),[path,snapshot,attendance,policies,insurance,receipt,catalog,business,mapping]=process.argv.slice(2),m=JSON.parse(fs.readFileSync(path,'utf8'));
if(m.formatVersion!==1||m.artifactKind!=='yuzhou_t3_attendance_insurance_stage'||m.sourceReadOnly!==true||m.sourceSnapshotSha256!==snapshot||m.sourceRestoreReceiptSha256!==receipt||m.sourceCatalogSha256!==catalog||m.sourceBusinessSha256!==business||m.mappingContractSha256!==mapping||m.productionImport!=='HOLD')throw Error('source binding');
for(const [domain,hash] of Object.entries({attendance,policies,insurance}))if(m.domains?.[domain]?.file!==`${domain}.jsonl`||m.domains[domain].fileSha256!==hash)throw Error(domain);
NODE
[ "$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$PG")" = "$EXPECTED_PROJECT" ]||fail "wrong postgres project"
TMP="/tmp/yuzhou-t3-$RUN_ID"; cleanup(){ docker exec "$PG" rm -rf "$TMP" >/dev/null 2>&1||true; }; trap cleanup EXIT HUP INT TERM; docker exec "$PG" mkdir -p "$TMP"; for f in attendance policies insurance; do docker cp "$STAGE/$f.jsonl" "$PG:$TMP/$f.jsonl"; done; docker exec "$PG" chown -R postgres:postgres "$TMP"; docker exec "$PG" chmod -R go-rwx "$TMP"
docker exec -i "$PG" psql -X -v ON_ERROR_STOP=1 -U jinhu -d "$DB" -v run="$RUN_ID" -v db="$DB" -v tenant="$TENANT" -v park="$PARK" -v snap="$SNAP" -v ah="$AH" -v ph="$PH" -v ih="$IH" -v apath="$TMP/attendance.jsonl" -v ppath="$TMP/policies.jsonl" -v ipath="$TMP/insurance.jsonl" <<'SQL'
BEGIN; SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='10min'; SELECT set_config('yz.run',:'run',true); SELECT set_config('yz.db',:'db',true);
DO $$BEGIN IF current_database()<>current_setting('yz.db') OR current_database()!~'^jinhu_hr_migration_lab_' THEN RAISE EXCEPTION 'unsafe target'; END IF; IF EXISTS(SELECT 1 FROM migration_batch WHERE run_id=current_setting('yz.run')) THEN RAISE EXCEPTION 'migration run already exists'; END IF; END$$;
CREATE TEMP TABLE sa(payload jsonb); CREATE TEMP TABLE sp(payload jsonb); CREATE TEMP TABLE si(payload jsonb,period_year integer,period_month integer); COPY sa FROM :'apath'; COPY sp FROM :'ppath'; COPY si FROM :'ipath';
UPDATE si SET period_year=CASE WHEN payload->'source'->>'year'~'^[0-9]{1,4}$' THEN(payload->'source'->>'year')::int END,period_month=CASE WHEN payload->'source'->>'month'~'^[0-9]{1,2}$' THEN(payload->'source'->>'month')::int END;
DO $$BEGIN IF(SELECT count(*)FROM sa)<>144 OR(SELECT count(*)FROM sp)<>12 OR(SELECT count(*)FROM si)<>35008 THEN RAISE EXCEPTION 'T3 count drift'; END IF; END$$;
CREATE TEMP TABLE employee_before AS SELECT encode(digest(string_agg(concat_ws('|',id,employment_status,COALESCE(primary_org_id::text,''),COALESCE(position_id::text,'')),';'ORDER BY id),'sha256'),'hex') h FROM hr_employee WHERE tenant_id=:'tenant' AND park_id=:'park' AND NOT is_deleted;
INSERT INTO migration_batch(run_id,source_system,source_snapshot_sha256,target_database,phase,status,tool_version,started_at) VALUES(:'run','yuzhou-v10',:'snap',:'db','load','running','t3-attendance-insurance-loader-v1',now());
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run'),v AS(SELECT count(*) n FROM si s JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=s.payload->'source'->>'employeeCode' AND NOT e.is_deleted WHERE s.period_year BETWEEN 1900 AND 2100 AND s.period_month BETWEEN 1 AND 12) INSERT INTO migration_batch_item(batch_id,domain,source_object,phase,status,extracted_count,valid_count,rejected_count,checksum_sha256,started_at) SELECT id,'attendance_calendar','dbo.timekeeptable','load','running',144,144,0,:'ah',now() FROM b UNION ALL SELECT id,'insurance_policy','dbo.insure_method','load','running',12,12,0,:'ph',now() FROM b UNION ALL SELECT id,'employee_insurance','dbo.person_insure','load','running',35008,v.n,35008-v.n,:'ih',now() FROM b CROSS JOIN v;
INSERT INTO hr_attendance_import_batch(tenant_id,park_id,batch_code,source_system,source_checksum,status,remark) VALUES(:'tenant',:'park',:'run','yuzhou-v10',:'ah','imported','Yuzhou T3 historical import');
INSERT INTO hr_attendance_symbol_rule(tenant_id,park_id,rule_version,legacy_symbol,normalized_kind,status,remark) VALUES(:'tenant',:'park','yuzhou-v1','普通班次','standard_shift','enabled','Yuzhou T3 rule'),(:'tenant',:'park','yuzhou-v1','晚上班','night_shift','enabled','Yuzhou T3 rule');
INSERT INTO hr_attendance_calendar_source(tenant_id,park_id,import_batch_id,legacy_id,calendar_name,calendar_year,calendar_month,source_snapshot,remark) SELECT :'tenant',:'park',b.id,(s.payload->'source'->>'id')::int,s.payload->'source'->>'calendarName',(s.payload->'source'->>'year')::int,(s.payload->'source'->>'month')::int,jsonb_build_object('sourceRowSha256',s.payload->>'sourceRowSha256'),'Yuzhou run='||:'run' FROM sa s CROSS JOIN hr_attendance_import_batch b WHERE b.tenant_id=:'tenant' AND b.park_id=:'park' AND b.batch_code=:'run';
INSERT INTO hr_attendance_day(tenant_id,park_id,calendar_source_id,attendance_date,legacy_symbol,symbol_status,normalized_kind,remark) SELECT :'tenant',:'park',c.id,make_date(c.calendar_year,c.calendar_month,(d->>'day')::int),NULLIF(d->>'legacySymbol',''),CASE WHEN NULLIF(d->>'legacySymbol','') IS NULL THEN'blank' WHEN r.id IS NULL THEN'needs_review' ELSE'mapped' END,r.normalized_kind,'Yuzhou run='||:'run' FROM sa s JOIN hr_attendance_calendar_source c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.legacy_id=(s.payload->'source'->>'id')::int CROSS JOIN LATERAL jsonb_array_elements(s.payload->'days') d LEFT JOIN hr_attendance_symbol_rule r ON r.tenant_id=:'tenant' AND r.park_id=:'park' AND r.rule_version='yuzhou-v1' AND r.legacy_symbol=d->>'legacySymbol' AND NOT r.is_deleted;
INSERT INTO hr_insurance_policy(tenant_id,park_id,policy_code,policy_name,scope_description,remark) SELECT :'tenant',:'park','YUZHOU-'||(s.payload->'source'->>'id'),s.payload->'source'->>'name',s.payload->'source'->>'scope','Yuzhou run='||:'run' FROM sp s;
INSERT INTO hr_insurance_policy_item(tenant_id,park_id,policy_id,insurance_kind,variant_no,base_rate,employer_rate,employee_rate,supplement_rate,source_snapshot,remark) SELECT :'tenant',:'park',p.id,i->>'kind',(i->>'variant')::int,NULLIF(i->>'baseRate','')::numeric,NULLIF(i->>'employerRate','')::numeric,NULLIF(i->>'employeeRate','')::numeric,NULLIF(i->>'supplementRate','')::numeric,'{}','Yuzhou run='||:'run' FROM sp s JOIN hr_insurance_policy p ON p.tenant_id=:'tenant' AND p.park_id=:'park' AND p.policy_code='YUZHOU-'||(s.payload->'source'->>'id') CROSS JOIN LATERAL jsonb_array_elements(s.payload->'items') i;
INSERT INTO hr_employee_insurance_period(tenant_id,park_id,employee_id,period_year,period_month,legacy_id,needs_review,source_snapshot,remark) SELECT :'tenant',:'park',e.id,s.period_year,s.period_month,(s.payload->'source'->>'id')::int,EXISTS(SELECT 1 FROM jsonb_array_elements(s.payload->'items') i WHERE(i->>'legacyBaseNegative')::boolean),jsonb_build_object('sourceRowSha256',s.payload->>'sourceRowSha256'),'Yuzhou run='||:'run' FROM si s JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=s.payload->'source'->>'employeeCode' AND NOT e.is_deleted WHERE s.period_year BETWEEN 1900 AND 2100 AND s.period_month BETWEEN 1 AND 12;
INSERT INTO hr_employee_insurance_item(tenant_id,park_id,period_id,insurance_kind,contribution_base,total_amount,employer_amount,employee_amount,supplement_amount,legacy_base_negative,remark) SELECT :'tenant',:'park',p.id,i->>'kind',NULLIF(i->>'contributionBase','')::numeric,NULLIF(i->>'totalAmount','')::numeric,NULLIF(i->>'employerAmount','')::numeric,NULLIF(i->>'employeeAmount','')::numeric,NULLIF(i->>'supplementAmount','')::numeric,(i->>'legacyBaseNegative')::boolean,'Yuzhou run='||:'run' FROM si s JOIN hr_employee_insurance_period p ON p.tenant_id=:'tenant' AND p.park_id=:'park' AND p.legacy_id=(s.payload->'source'->>'id')::int CROSS JOIN LATERAL jsonb_array_elements(s.payload->'items') i;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run') INSERT INTO legacy_record_map(batch_id,source_system,source_table,source_pk_canonical,source_identity_sha256,source_row_sha256,target_table,target_id,mapping_status) SELECT b.id,'yuzhou-v10','dbo.timekeeptable','id='||(s.payload->>'sourceKey'),s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256','hr_attendance_calendar_source',c.id,'loaded' FROM sa s CROSS JOIN b JOIN hr_attendance_calendar_source c ON c.tenant_id=:'tenant' AND c.park_id=:'park' AND c.legacy_id=(s.payload->'source'->>'id')::int UNION ALL SELECT b.id,'yuzhou-v10','dbo.insure_method','id='||(s.payload->>'sourceKey'),s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256','hr_insurance_policy',p.id,'loaded' FROM sp s CROSS JOIN b JOIN hr_insurance_policy p ON p.tenant_id=:'tenant' AND p.park_id=:'park' AND p.policy_code='YUZHOU-'||(s.payload->'source'->>'id') UNION ALL SELECT b.id,'yuzhou-v10','dbo.person_insure','id='||(s.payload->>'sourceKey'),s.payload->>'sourceIdentitySha256',s.payload->>'sourceRowSha256','hr_employee_insurance_period',p.id,'loaded' FROM si s CROSS JOIN b JOIN hr_employee_insurance_period p ON p.tenant_id=:'tenant' AND p.park_id=:'park' AND p.legacy_id=(s.payload->'source'->>'id')::int;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run'),i AS(SELECT id,batch_id FROM migration_batch_item WHERE domain='employee_insurance' AND batch_id=(SELECT id FROM b)) INSERT INTO migration_error(batch_id,batch_item_id,category,error_code,source_identity_sha256,redacted_evidence,evidence_redacted,retryable) SELECT b.id,i.id,'validation','INSURANCE_PERIOD_INVALID',s.payload->>'sourceIdentitySha256',jsonb_build_object('rule','invalid_or_missing_period'),true,false FROM si s CROSS JOIN b CROSS JOIN i WHERE s.period_year IS NULL OR s.period_year NOT BETWEEN 1900 AND 2100 OR s.period_month IS NULL OR s.period_month NOT BETWEEN 1 AND 12 UNION ALL SELECT b.id,i.id,'mapping','INSURANCE_EMPLOYEE_NOT_MAPPED',s.payload->>'sourceIdentitySha256',jsonb_build_object('rule','employee_mapping_missing'),true,false FROM si s CROSS JOIN b CROSS JOIN i LEFT JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=s.payload->'source'->>'employeeCode' AND NOT e.is_deleted WHERE e.id IS NULL AND s.period_year BETWEEN 1900 AND 2100 AND s.period_month BETWEEN 1 AND 12;
UPDATE migration_batch_item i SET loaded_count=CASE domain WHEN'attendance_calendar'THEN(SELECT count(*)FROM hr_attendance_calendar_source WHERE remark='Yuzhou run='||:'run') WHEN'insurance_policy'THEN(SELECT count(*)FROM hr_insurance_policy WHERE remark='Yuzhou run='||:'run') ELSE(SELECT count(*)FROM hr_employee_insurance_period WHERE remark='Yuzhou run='||:'run') END,status=CASE WHEN rejected_count>0 THEN'quarantined'ELSE'succeeded'END,finished_at=now() WHERE batch_id=(SELECT id FROM migration_batch WHERE run_id=:'run');
CREATE TEMP TABLE source_sums AS SELECT i->>'kind' kind,sum(COALESCE(NULLIF(i->>'totalAmount','')::numeric,0)) total_amount,sum(COALESCE(NULLIF(i->>'employerAmount','')::numeric,0)) employer_amount,sum(COALESCE(NULLIF(i->>'employeeAmount','')::numeric,0)) employee_amount,sum(COALESCE(NULLIF(i->>'supplementAmount','')::numeric,0)) supplement_amount FROM si s JOIN hr_employee e ON e.tenant_id=:'tenant' AND e.park_id=:'park' AND e.employee_code=s.payload->'source'->>'employeeCode' AND NOT e.is_deleted CROSS JOIN LATERAL jsonb_array_elements(s.payload->'items') i WHERE s.period_year BETWEEN 1900 AND 2100 AND s.period_month BETWEEN 1 AND 12 GROUP BY i->>'kind';
CREATE TEMP TABLE target_sums AS SELECT i.insurance_kind kind,sum(COALESCE(i.total_amount,0)) total_amount,sum(COALESCE(i.employer_amount,0)) employer_amount,sum(COALESCE(i.employee_amount,0)) employee_amount,sum(COALESCE(i.supplement_amount,0)) supplement_amount FROM hr_employee_insurance_item i WHERE i.remark='Yuzhou run='||:'run' GROUP BY i.insurance_kind;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run') INSERT INTO migration_check(batch_id,check_code,expected_value,actual_value,tolerance,passed,evidence_sha256) SELECT b.id,'T3_ATTENDANCE_DAYS',to_jsonb(4383),to_jsonb((SELECT count(*)FROM hr_attendance_day WHERE remark='Yuzhou run='||:'run')),'{}'::jsonb,4383=(SELECT count(*)FROM hr_attendance_day WHERE remark='Yuzhou run='||:'run'),encode(digest('4383','sha256'),'hex') FROM b UNION ALL SELECT b.id,'T3_INSURANCE_ACCOUNTING',to_jsonb(35008),to_jsonb((SELECT count(*)FROM hr_employee_insurance_period WHERE remark='Yuzhou run='||:'run')+(SELECT count(*)FROM migration_error WHERE batch_id=b.id AND error_code IN('INSURANCE_EMPLOYEE_NOT_MAPPED','INSURANCE_PERIOD_INVALID'))),'{}'::jsonb,35008=(SELECT count(*)FROM hr_employee_insurance_period WHERE remark='Yuzhou run='||:'run')+(SELECT count(*)FROM migration_error WHERE batch_id=b.id AND error_code IN('INSURANCE_EMPLOYEE_NOT_MAPPED','INSURANCE_PERIOD_INVALID')),encode(digest('35008','sha256'),'hex') FROM b UNION ALL SELECT b.id,'T3_EMPLOYEE_UNCHANGED',to_jsonb(x.h),to_jsonb(a.h),'{}'::jsonb,x.h=a.h,encode(digest(x.h,'sha256'),'hex') FROM b CROSS JOIN employee_before x CROSS JOIN(SELECT encode(digest(string_agg(concat_ws('|',id,employment_status,COALESCE(primary_org_id::text,''),COALESCE(position_id::text,'')),';'ORDER BY id),'sha256'),'hex')h FROM hr_employee WHERE tenant_id=:'tenant' AND park_id=:'park' AND NOT is_deleted)a;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run') INSERT INTO migration_check(batch_id,check_code,expected_value,actual_value,tolerance,passed,evidence_sha256) SELECT b.id,'T3_INSURANCE_SUM_'||upper(s.kind),to_jsonb(s.*)-'kind',to_jsonb(t.*)-'kind','{}'::jsonb,s.total_amount=t.total_amount AND s.employer_amount=t.employer_amount AND s.employee_amount=t.employee_amount AND s.supplement_amount=t.supplement_amount,encode(digest(concat_ws('|',s.kind,s.total_amount,s.employer_amount,s.employee_amount,s.supplement_amount),'sha256'),'hex') FROM source_sums s JOIN target_sums t USING(kind) CROSS JOIN b;
WITH b AS(SELECT id FROM migration_batch WHERE run_id=:'run') INSERT INTO migration_rollback_point(batch_id,rollback_code,reversible_scope,cleanup_manifest,evidence_sha256,verified_at) SELECT id,'T3_ATTENDANCE_INSURANCE',jsonb_build_object('runId',:'run'),jsonb_build_object('tables',ARRAY['hr_employee_insurance_item','hr_employee_insurance_period','hr_insurance_policy_item','hr_insurance_policy','hr_attendance_day','hr_attendance_calendar_source','hr_attendance_symbol_rule','hr_attendance_import_batch']),encode(digest(:'run','sha256'),'hex'),now() FROM b;
UPDATE hr_attendance_import_batch SET status='verified' WHERE batch_code=:'run' AND tenant_id=:'tenant' AND park_id=:'park'; UPDATE migration_batch SET phase='verify',status=CASE WHEN EXISTS(SELECT 1 FROM migration_check WHERE batch_id=migration_batch.id AND NOT passed)THEN'failed'ELSE'succeeded'END,counts=jsonb_build_object('calendars',144,'days',4383,'policies',12,'policyItems',144,'insurancePeriods',(SELECT count(*)FROM hr_employee_insurance_period WHERE remark='Yuzhou run='||:'run'),'insuranceItems',(SELECT count(*)FROM hr_employee_insurance_item WHERE remark='Yuzhou run='||:'run'),'quarantined',(SELECT count(*)FROM migration_error WHERE batch_id=migration_batch.id)),finished_at=now() WHERE run_id=:'run';
DO $$BEGIN IF EXISTS(SELECT 1 FROM migration_check c JOIN migration_batch b ON b.id=c.batch_id WHERE b.run_id=current_setting('yz.run') AND NOT c.passed) THEN RAISE EXCEPTION 'T3 verification failed'; END IF; END$$; COMMIT;
SQL
docker exec "$PG" psql -X -A -t -F '|' -U jinhu -d "$DB" -c "SELECT run_id,status,counts FROM migration_batch WHERE run_id='$RUN_ID'"
