#!/usr/bin/env sh
set -eu
RUN_ID="${YUZHOU_T5_FILE_RUN_ID:-${YUZHOU_MIGRATION_RUN_ID:-}}"; DB="${YUZHOU_TARGET_DATABASE:-}"; PG="${YUZHOU_POSTGRES_CONTAINER:-}"; PROJECT="${YUZHOU_EXPECTED_POSTGRES_COMPOSE_PROJECT:-}"
fail(){ printf 'ERROR: %s\n' "$1" >&2; exit 1; }
[ "${ALLOW_YUZHOU_MIGRATION:-no}" = yes ] && [ "${ALLOW_YUZHOU_ROLLBACK:-no}" = yes ] || fail "set both migration and rollback approvals"
[ "${YUZHOU_T5_FILE_MODE:-}" = isolated_rehearsal ] || fail "T5_FILE only permits isolated_rehearsal"
printf %s "$RUN_ID" | grep -Eq '^[A-Za-z0-9][A-Za-z0-9._-]{5,63}$' || fail "invalid run id"; printf %s "$DB" | grep -Eq '^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$' || fail "unsafe target database"; printf %s "$PROJECT" | grep -Eq '^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$' || fail "unsafe compose project"; [ "$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$PG" 2>/dev/null || true)" = "$PROJECT" ] || fail "wrong PostgreSQL compose project"
docker exec -i "$PG" psql -X -q -v ON_ERROR_STOP=1 -U jinhu -d "$DB" -v run="$RUN_ID" -v db="$DB" >/dev/null <<'SQL'
BEGIN; SET LOCAL lock_timeout='10s'; SET LOCAL statement_timeout='10min'; SELECT set_config('yuzhou.t5_rollback',:'run',true),set_config('yuzhou.t5_db',:'db',true);
DO $$DECLARE b uuid;BEGIN IF current_database()<>current_setting('yuzhou.t5_db') OR current_database()!~'^jinhu_hr_migration_lab_[A-Za-z0-9_]{6,64}$' THEN RAISE EXCEPTION 'unsafe target'; END IF; SELECT id INTO b FROM migration_batch WHERE run_id=current_setting('yuzhou.t5_rollback') AND status='succeeded' FOR UPDATE; IF b IS NULL OR NOT EXISTS(SELECT 1 FROM hr_legacy_t5_import_batch WHERE migration_batch_id=b AND status='staged' FOR UPDATE) OR NOT EXISTS(SELECT 1 FROM migration_rollback_point WHERE batch_id=b AND rollback_code='T5_LEGACY_HISTORY' AND verified_at IS NOT NULL) THEN RAISE EXCEPTION 'staged T5_FILE batch not found'; END IF; IF EXISTS(SELECT 1 FROM legacy_record_map WHERE batch_id=b AND is_active AND (target_table NOT IN('hr_legacy_t5_file_evidence','hr_legacy_t5_quarantine') OR (target_table='hr_legacy_t5_quarantine' AND(target_id IS NOT NULL OR mapping_status<>'quarantined')))) THEN RAISE EXCEPTION 'unexpected T5_FILE rollback target'; END IF; END$$;
DELETE FROM hr_legacy_t5_file_evidence x USING legacy_record_map m,migration_batch b WHERE m.batch_id=b.id AND b.run_id=:'run' AND m.target_table='hr_legacy_t5_file_evidence' AND m.target_id=x.id AND m.is_active;
DO $$BEGIN IF EXISTS(SELECT 1 FROM hr_legacy_t5_file_evidence x JOIN legacy_record_map m ON m.target_id=x.id WHERE m.batch_id=(SELECT id FROM migration_batch WHERE run_id=current_setting('yuzhou.t5_rollback')) AND m.is_active) THEN RAISE EXCEPTION 'T5_FILE evidence rollback residual'; END IF; END$$;
UPDATE legacy_record_map SET mapping_status='rolled_back',is_active=false,update_time=now() WHERE batch_id=(SELECT id FROM migration_batch WHERE run_id=:'run') AND is_active; UPDATE hr_legacy_t5_import_batch SET status='rolled_back',update_time=now() WHERE migration_batch_id=(SELECT id FROM migration_batch WHERE run_id=:'run'); UPDATE migration_batch SET status='rolled_back',phase='rollback',finished_at=now(),update_time=now() WHERE run_id=:'run'; COMMIT;
SQL
docker exec "$PG" psql -X -q -A -t -F '|' -U jinhu -d "$DB" -c "SELECT status FROM migration_batch WHERE run_id='$RUN_ID'"
