import { Controller, Get } from "@nestjs/common";
import { SYSTEM_PERMISSIONS } from "@jinhu/shared";
import type { TenantParkScope } from "@jinhu/shared";
import { CurrentScope } from "../../shared/decorators/current-scope.decorator";
import { RequireAnyPermissions } from "../../shared/decorators/permissions.decorator";
import { ReferenceDataService } from "./reference-data.service";

@Controller("reference-data")
export class ReferenceDataController {
  constructor(private readonly referenceDataService: ReferenceDataService) {}

  @Get("form-options")
  @RequireAnyPermissions(
    "ENGINEERING_PROJECT_VIEW",
    "ENGINEERING_PROJECT_CREATE",
    "ENGINEERING_PROJECT_UPDATE",
    "ENGINEERING_PLAN_VIEW",
    "ENGINEERING_PLAN_CREATE",
    "ENGINEERING_PLAN_UPDATE",
    "ENGINEERING_DAILY_REPORT_VIEW",
    "ENGINEERING_DAILY_REPORT_CREATE",
    "ENGINEERING_DAILY_REPORT_UPDATE",
    "ENGINEERING_INSPECTION_VIEW",
    "ENGINEERING_INSPECTION_CREATE",
    "ENGINEERING_INSPECTION_UPDATE",
    "ENGINEERING_RECTIFICATION_VIEW",
    "ENGINEERING_RECTIFICATION_ASSIGN",
    "ENGINEERING_RECTIFICATION_UPDATE",
    "ENGINEERING_ACCEPTANCE_VIEW",
    "ENGINEERING_ACCEPTANCE_CREATE",
    "ENGINEERING_ACCEPTANCE_UPDATE",
    SYSTEM_PERMISSIONS.ASSET_READ,
    SYSTEM_PERMISSIONS.ASSET_BUILDING_LIST,
    SYSTEM_PERMISSIONS.ASSET_FLOOR_LIST,
    SYSTEM_PERMISSIONS.ASSET_UNIT_LIST,
    SYSTEM_PERMISSIONS.SAFETY_HAZARD_READ,
    SYSTEM_PERMISSIONS.SAFETY_HAZARD_CREATE,
    SYSTEM_PERMISSIONS.SAFETY_HAZARD_UPDATE,
    SYSTEM_PERMISSIONS.SAFETY_HAZARD_OVERDUE,
    SYSTEM_PERMISSIONS.SAFETY_WORK_PERMIT_READ,
    SYSTEM_PERMISSIONS.SAFETY_WORK_PERMIT_CREATE,
    SYSTEM_PERMISSIONS.SAFETY_WORK_PERMIT_UPDATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_POINT_READ,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_POINT_CREATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_POINT_UPDATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_PLAN_READ,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_PLAN_CREATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_PLAN_UPDATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_READ,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_CREATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_GENERATE,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_MY,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_START,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_CHECK_IN,
    SYSTEM_PERMISSIONS.SAFETY_INSPECT_TASK_SUBMIT_RESULTS,
    SYSTEM_PERMISSIONS.SAFETY_EMERGENCY_READ,
    SYSTEM_PERMISSIONS.SAFETY_EMERGENCY_CREATE,
    SYSTEM_PERMISSIONS.SAFETY_EMERGENCY_UPDATE,
    SYSTEM_PERMISSIONS.SAFETY_STATISTICS_READ,
    SYSTEM_PERMISSIONS.SAFETY_EMERGENCY_STATISTICS_READ,
    SYSTEM_PERMISSIONS.SAFETY_WORK_PERMIT_STATISTICS_READ,
    SYSTEM_PERMISSIONS.WORKORDER_READ,
    SYSTEM_PERMISSIONS.WORKORDER_CREATE,
    SYSTEM_PERMISSIONS.WORKORDER_UPDATE,
    SYSTEM_PERMISSIONS.WORKORDER_OVERDUE,
    SYSTEM_PERMISSIONS.WORKORDER_STATS,
    SYSTEM_PERMISSIONS.IOT_DEVICE_READ,
    SYSTEM_PERMISSIONS.IOT_DEVICE_CREATE,
    SYSTEM_PERMISSIONS.IOT_DEVICE_UPDATE,
    SYSTEM_PERMISSIONS.IOT_ALERT_READ,
    SYSTEM_PERMISSIONS.IOT_DASHBOARD_READ,
    SYSTEM_PERMISSIONS.ENERGY_METER_READ,
    SYSTEM_PERMISSIONS.ENERGY_METER_CREATE,
    SYSTEM_PERMISSIONS.ENERGY_METER_UPDATE,
    SYSTEM_PERMISSIONS.ENERGY_BILLING_ITEM_VIEW,
    SYSTEM_PERMISSIONS.LEASING_CONTRACT_READ,
    SYSTEM_PERMISSIONS.LEASING_CONTRACT_CREATE,
    SYSTEM_PERMISSIONS.LEASING_CONTRACT_UPDATE,
    SYSTEM_PERMISSIONS.LEASING_LEAD_READ,
    SYSTEM_PERMISSIONS.LEASING_LEAD_CREATE,
    SYSTEM_PERMISSIONS.LEASING_LEAD_UPDATE,
    SYSTEM_PERMISSIONS.LEASING_CHECKOUT_READ,
    SYSTEM_PERMISSIONS.LEASING_CHECKOUT_CREATE,
    SYSTEM_PERMISSIONS.LEASING_CHECKOUT_UPDATE,
    SYSTEM_PERMISSIONS.LEASING_RECEIVABLE_READ,
    SYSTEM_PERMISSIONS.LEASING_PAYMENT_READ,
    SYSTEM_PERMISSIONS.PARK_TENANT_READ,
    SYSTEM_PERMISSIONS.VIDEO_CAMERA_READ,
    SYSTEM_PERMISSIONS.VIDEO_CAMERA_CREATE,
    SYSTEM_PERMISSIONS.VIDEO_CAMERA_UPDATE,
    SYSTEM_PERMISSIONS.VIDEO_SECURITY_DASHBOARD_READ
  )
  listFormOptions(@CurrentScope() scope: TenantParkScope) {
    return this.referenceDataService.getFormOptions(scope);
  }
}
