"use client";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { useCallback,useEffect,useRef,useState } from "react";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hrApi,type HrEmployee,type HrTrainingCourse,type HrTrainingPlan,type HrTrainingPlanDetail } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import { hrLoadErrorMessage } from "../hr-errors";
import styles from "../hr-workbench.module.css";
const statusLabel:Record<string,string>={draft:"草稿",published:"待开始",in_progress:"进行中",completed:"已完成",cancelled:"已取消",assigned:"待签到",checked_in:"已签到"};
export function HrTrainingClient(){
 const user=useAuthUser(),canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_TRAINING_READ,HR_PERMISSIONS.HR_TRAINING_TEAM_READ,HR_PERMISSIONS.HR_TRAINING_SELF_READ]),canCourse=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE),canPlan=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE),canCost=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_COST_READ);
 const [plans,setPlans]=useState<HrTrainingPlan[]>([]),[courses,setCourses]=useState<Array<Pick<HrTrainingCourse,"id"|"title"|"hours">>>([]),[employees,setEmployees]=useState<Array<Pick<HrEmployee,"id"|"employeeCode"|"fullName">>>([]),[detail,setDetail]=useState<HrTrainingPlanDetail|null>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const generation=useRef(0),listAbort=useRef<AbortController|null>(null),detailAbort=useRef<AbortController|null>(null),pageSize=20;
 const clearDetail=()=>{detailAbort.current?.abort();detailAbort.current=null;setDetail(null);};
 const load=useCallback(async()=>{if(!canRead){setLoading(false);return;}const g=++generation.current,c=new AbortController();listAbort.current?.abort();listAbort.current=c;setLoading(true);setError("");clearDetail();try{const token=getAccessToken(),[p,options]=await Promise.all([hrApi.trainingPlans(token,page,pageSize,undefined,c.signal),canPlan?hrApi.trainingPlanOptions(token,c.signal):hrApi.trainingCourses(token,c.signal).then(courses=>({courses,employees:[]}))]);if(g!==generation.current)return;setPlans(p.items);setTotal(p.total);setCourses(options.courses);setEmployees(options.employees);}catch(e){if((e as Error).name!=="AbortError"&&g===generation.current){setPlans([]);setCourses([]);setEmployees([]);setTotal(0);setError(hrLoadErrorMessage(e,"加载培训任务失败"));}}finally{if(g===generation.current)setLoading(false);}},[canPlan,canRead,page]);
 useEffect(()=>{void load();return()=>{generation.current++;listAbort.current?.abort();detailAbort.current?.abort();};},[load]);
 const open=async(id:string)=>{clearDetail();const c=new AbortController();detailAbort.current=c;setDetailLoading(true);setError("");try{const x=await hrApi.trainingPlan(id,getAccessToken(),c.signal);if(!c.signal.aborted&&detailAbort.current===c)setDetail(x);}catch(e){if((e as Error).name!=="AbortError"&&detailAbort.current===c)setError(hrLoadErrorMessage(e,"加载培训详情失败"));}finally{if(detailAbort.current===c)setDetailLoading(false);}};
 const mutate=async(job:()=>Promise<unknown>,message:string,refreshId?:string)=>{if(busy)return;setBusy(true);setError("");try{await job();if(refreshId)setDetail(await hrApi.trainingPlan(refreshId,getAccessToken()));await load();if(refreshId)await open(refreshId);}catch(e){setError(hrLoadErrorMessage(e,message));}finally{setBusy(false);}};
 const createCourse=async(form:FormData)=>mutate(()=>hrApi.createTrainingCourse({code:String(form.get("code")),title:String(form.get("title")),category:String(form.get("category")),provider:String(form.get("provider"))||undefined,hours:String(form.get("hours")),description:String(form.get("description"))||undefined},getAccessToken()),"创建课程失败");
 const createPlan=async(form:FormData)=>mutate(()=>hrApi.createTrainingPlan({code:String(form.get("code")),name:String(form.get("name")),courseId:String(form.get("course")),mandatory:form.get("mandatory")==="on",startDate:String(form.get("startDate")),endDate:String(form.get("endDate")),budgetAmount:String(form.get("budgetAmount")||"0"),costCurrency:"CNY",employeeIds:form.getAll("employees").map(String)},getAccessToken()),"创建培训计划失败");
 const complete=async(participantId:string,planId:string,form:FormData)=>mutate(()=>hrApi.completeTraining(participantId,{completedHours:String(form.get("hours")),score:String(form.get("score"))||undefined,evaluation:String(form.get("evaluation"))||undefined,...(canCost&&form.get("actualCost")?{actualCost:String(form.get("actualCost"))}:{})},getAccessToken()),"记录培训结果失败",planId);
 const forbidden=<main className={`content ds-page ${styles.page}`}><section className="ds-panel"><ForbiddenState message="无权访问培训管理"/></section></main>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_TRAINING_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page}`}>
  <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">人事运营 · 人才发展</span><h1>培训管理</h1><p>统一课程、培训计划、员工任务与结果记录，形成可追溯的人才培养档案。</p></div><div className={styles.heroActions}><button className="ds-button" disabled={loading} onClick={()=>void load()}>{loading?"刷新中":"刷新"}</button></div></section>
  {error?<section className="ds-panel"><p className="form-error" role="alert">{error}</p><button className="ds-button" onClick={()=>void load()}>重试</button></section>:null}
  {canCourse?<section className="ds-panel"><h2>新增课程</h2><form className={styles.formGrid} action={createCourse}><label className="form-field"><span>课程编号</span><input name="code" required maxLength={64}/></label><label className="form-field"><span>课程名称</span><input name="title" required maxLength={160}/></label><label className="form-field"><span>分类</span><input name="category" required maxLength={64}/></label><label className="form-field"><span>培训机构</span><input name="provider" maxLength={160}/></label><label className="form-field"><span>标准学时</span><input name="hours" required type="number" min="0.01" max="999999.99" step="0.01"/></label><label className="form-field"><span>课程摘要</span><input name="description" maxLength={2000}/></label><button className="ds-button ds-button-primary" disabled={busy}>保存课程</button></form></section>:null}
  {canPlan?<section className="ds-panel"><h2>创建培训计划</h2><form className={styles.formGrid} action={createPlan}><label className="form-field"><span>计划编号</span><input name="code" required maxLength={64}/></label><label className="form-field"><span>计划名称</span><input name="name" required maxLength={160}/></label><label className="form-field"><span>课程</span><select name="course" required><option value="">请选择</option>{courses.map(x=><option key={x.id} value={x.id}>{x.title} · {x.hours} 学时</option>)}</select></label><label className="form-field"><span>开始日期</span><input name="startDate" type="date" required/></label><label className="form-field"><span>结束日期</span><input name="endDate" type="date" required/></label><label className={`form-field ${styles.desktopSensitive}`}><span>预算</span><input name="budgetAmount" type="number" min="0" step="0.0001" defaultValue="0" required/></label><label className="form-field"><span>参训员工</span><select name="employees" multiple required size={5}>{employees.map(x=><option key={x.id} value={x.id}>{x.fullName} · {x.employeeCode}</option>)}</select></label><label className="form-field"><span><input name="mandatory" type="checkbox"/> 必修培训</span></label><button className="ds-button ds-button-primary" disabled={busy}>创建计划</button></form></section>:null}
  <section className="ds-panel"><h2>培训任务</h2><div className="ds-mobile-record-list">{loading?<p>正在加载…</p>:plans.length?plans.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.name}</strong><span>{statusLabel[x.status]??x.status} · {x.completedCount}/{x.participantCount} 人完成</span><span>{x.startDate} 至 {x.endDate}{x.mandatory?" · 必修":""}</span>{canCost&&x.budgetAmount!==undefined?<span className={styles.desktopSensitive}>预算 {x.budgetAmount} {x.costCurrency} · 已发生 {x.actualCost}</span>:null}<div className={styles.recordActions}><button className="ds-button" onClick={()=>void open(x.id)}>查看</button>{canPlan&&x.status==="draft"?<button className="ds-button" disabled={busy} onClick={()=>void mutate(()=>hrApi.trainingPlanAction(x.id,"publish",getAccessToken()),"发布计划失败")}>发布</button>:null}{canPlan&&x.status==="published"?<button className="ds-button" disabled={busy} onClick={()=>void mutate(()=>hrApi.trainingPlanAction(x.id,"start",getAccessToken()),"开始计划失败")}>开始</button>:null}{canPlan&&x.status==="in_progress"&&x.completedCount===x.participantCount?<button className="ds-button" disabled={busy} onClick={()=>void mutate(()=>hrApi.trainingPlanAction(x.id,"complete",getAccessToken()),"完成计划失败")}>完成计划</button>:null}</div></article>):<p>当前没有可见培训任务。</p>}</div>{total>pageSize?<div className={styles.recordActions}><button className="ds-button" disabled={page===1||loading} onClick={()=>setPage(x=>Math.max(1,x-1))}>上一页</button><span>第 {page} 页</span><button className="ds-button" disabled={page*pageSize>=total||loading} onClick={()=>setPage(x=>x+1)}>下一页</button></div>:null}</section>
  {detailLoading?<section className="ds-panel"><p>正在加载培训详情…</p></section>:detail?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">培训结果</span><h2>{detail.name}</h2></div><button className="ds-button" onClick={clearDetail}>关闭</button></div><div className="ds-mobile-record-list">{detail.participants.map((x,index)=><article className="ds-mobile-record" key={x.id??`${x.employeeName}-${x.status}-${index}`}><strong>{x.employeeName}</strong><span>{statusLabel[x.status]??x.status}{x.completedHours?` · ${x.completedHours} 学时`:""}{x.score?` · ${x.score} 分`:""}</span>{canCost&&x.actualCost?<span className={styles.desktopSensitive}>费用 {x.actualCost}</span>:null}{x.id&&x.canAct&&x.status==="assigned"?<button className="ds-button" disabled={busy} onClick={()=>void mutate(()=>hrApi.trainingCheckIn(x.id!,getAccessToken()),"签到失败",detail.id)}>签到</button>:null}{x.id&&x.canAct&&["assigned","checked_in"].includes(x.status)?<form className={styles.formGrid} action={form=>complete(x.id!,detail.id,form)}><label className="form-field"><span>完成学时</span><input name="hours" type="number" min="0" step="0.01" required/></label><label className="form-field"><span>成绩</span><input name="score" type="number" min="0" max="100" step="0.01"/></label><label className="form-field"><span>评价</span><input name="evaluation" maxLength={1000}/></label>{canCost?<label className={`form-field ${styles.desktopSensitive}`}><span>实际费用</span><input name="actualCost" type="number" min="0" step="0.0001"/></label>:null}<button className="ds-button ds-button-primary" disabled={busy}>记录完成</button></form>:null}</article>)}</div></section>:null}
 </main></PermissionGuard>;
}
