"use client";
import { HR_PERMISSIONS } from "@jinhu/shared";
import { useCallback,useEffect,useRef,useState } from "react";
import { ForbiddenState } from "../../../components/auth/ForbiddenState";
import { PermissionGuard } from "../../../components/auth/PermissionGuard";
import { useAuthUser } from "../../../lib/auth-context";
import { getAccessToken } from "../../../lib/authz";
import { hrApi,type HrTrainingCourse,type HrTrainingPlan,type HrTrainingPlanDetail,type HrTrainingPositionRequirement,type HrTrainingPositionRequirementGap } from "../../../lib/hr-api";
import { hasAnyPermission,hasPermission } from "../../../lib/permissions";
import { hrLoadErrorMessage } from "../hr-errors";
import styles from "../hr-workbench.module.css";
import operations from "./training-operation.module.css";
import { TrainingResultForm, TrainingCertificateRecords } from "./TrainingResultForm";
import type { TrainingResultPayload } from "./training-result-form";
import { TrainingPlanFactsForm,trainingPlanFactsPayload } from "./TrainingPlanFactsForm";
import { TrainingEmployeePicker,type TrainingEmployeeOption } from "./TrainingEmployeePicker";
const statusLabel:Record<string,string>={draft:"草稿",published:"待开始",in_progress:"进行中",completed:"已完成",cancelled:"已取消",assigned:"待签到",checked_in:"已签到"};
export function HrTrainingClient(){
 const user=useAuthUser();
 return <HrTrainingWorkspace key={JSON.stringify(user)}/>;
}
function HrTrainingWorkspace(){
 const user=useAuthUser(),canRead=hasAnyPermission(user,[HR_PERMISSIONS.HR_TRAINING_READ,HR_PERMISSIONS.HR_TRAINING_TEAM_READ,HR_PERMISSIONS.HR_TRAINING_SELF_READ]),canCourse=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_COURSE_MANAGE),canPlan=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_PLAN_MANAGE),canCost=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_COST_READ),canProgress=hasPermission(user,HR_PERMISSIONS.HR_TRAINING_PROGRESS_MANAGE);
 const [plans,setPlans]=useState<HrTrainingPlan[]>([]),[courses,setCourses]=useState<Array<Pick<HrTrainingCourse,"id"|"title"> & Partial<Pick<HrTrainingCourse,"hours">>>>([]),[selectedEmployees,setSelectedEmployees]=useState<TrainingEmployeeOption[]>([]),[requirements,setRequirements]=useState<HrTrainingPositionRequirement[]>([]),[requirementPositions,setRequirementPositions]=useState<Array<{id:string;positionCode:string;positionName:string}>>([]),[gaps,setGaps]=useState<HrTrainingPositionRequirementGap[]>([]),[detail,setDetail]=useState<HrTrainingPlanDetail|null>(null),[page,setPage]=useState(1),[total,setTotal]=useState(0),[loading,setLoading]=useState(true),[detailLoading,setDetailLoading]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const mounted=useRef(true),mutationFlight=useRef(false),generation=useRef(0),listAbort=useRef<AbortController|null>(null),detailAbort=useRef<AbortController|null>(null),pageSize=20;
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
 const clearDetail=()=>{detailAbort.current?.abort();detailAbort.current=null;setDetail(null);setDetailLoading(false);};
 const load=useCallback(async(allowDuringWrite=false)=>{if(!mounted.current||(mutationFlight.current&&!allowDuringWrite))return;if(!allowDuringWrite)setSuccess("");if(!canRead&&!canPlan&&!canCourse){setLoading(false);return;}const g=++generation.current,c=new AbortController();listAbort.current?.abort();listAbort.current=c;setLoading(true);setError("");clearDetail();try{const token=getAccessToken(),[p,options,requirementOptions,requirementRows,gapRows]=await Promise.allSettled([canRead?hrApi.trainingPlans(token,page,pageSize,undefined,c.signal):Promise.resolve({items:[],total:0}),canPlan?hrApi.trainingCourseOptions(token,c.signal):canRead?hrApi.trainingCourses(token,c.signal).then(courses=>({courses})):Promise.resolve({courses:[]}),canCourse?hrApi.trainingRequirementOptions(token,c.signal):Promise.resolve({courses:[],positions:[]}),canCourse?hrApi.trainingPositionRequirements(token,c.signal):Promise.resolve([]),canPlan?hrApi.trainingPositionRequirementGaps(token,c.signal):Promise.resolve([])]);if(!mounted.current||g!==generation.current)return;const failures:string[]=[];
 if(p.status==="fulfilled"){setPlans(p.value.items);setTotal(p.value.total);}else failures.push(hrLoadErrorMessage(p.reason,"加载培训任务失败"));
 if(options.status==="fulfilled")setCourses(options.value.courses);else failures.push(hrLoadErrorMessage(options.reason,"加载培训课程失败"));
 if(requirementOptions.status==="fulfilled"){setRequirementPositions(requirementOptions.value.positions);if(!canPlan&&canCourse)setCourses(requirementOptions.value.courses);}else failures.push(hrLoadErrorMessage(requirementOptions.reason,"加载岗位候选失败"));
 if(requirementRows.status==="fulfilled")setRequirements(requirementRows.value);else failures.push(hrLoadErrorMessage(requirementRows.reason,"加载岗位必修课程失败"));
 if(gapRows.status==="fulfilled")setGaps(gapRows.value);else failures.push(hrLoadErrorMessage(gapRows.reason,"加载岗位必修完成情况失败"));
 if(failures.length)setError(failures.join("；"));}catch(e){if((e as Error).name!=="AbortError"&&mounted.current&&g===generation.current){setPlans([]);setCourses([]);setRequirements([]);setRequirementPositions([]);setGaps([]);setTotal(0);setError(hrLoadErrorMessage(e,"加载培训任务失败"));}}finally{if(mounted.current&&g===generation.current)setLoading(false);}},[canCourse,canPlan,canRead,page]);
 useEffect(()=>{void load();return()=>{generation.current++;listAbort.current?.abort();detailAbort.current?.abort();};},[load]);
 const open=async(id:string,allowDuringWrite=false)=>{if(!mounted.current||(mutationFlight.current&&!allowDuringWrite))return;if(!allowDuringWrite)setSuccess("");clearDetail();const c=new AbortController();detailAbort.current=c;setDetailLoading(true);if(!allowDuringWrite)setError("");try{const x=await hrApi.trainingPlan(id,getAccessToken(),c.signal);if(x.id!==id)throw new Error("培训详情响应不属于当前计划");if(mounted.current&&!c.signal.aborted&&detailAbort.current===c)setDetail(x);}catch(e){if(mounted.current&&(e as Error).name!=="AbortError"&&detailAbort.current===c)setError(previous=>[previous,hrLoadErrorMessage(e,"加载培训详情失败")].filter(Boolean).join("；"));}finally{if(mounted.current&&detailAbort.current===c)setDetailLoading(false);}};
 const mutate=async(job:()=>Promise<unknown>,message:string,refreshId?:string)=>{if(!mounted.current||mutationFlight.current||detailLoading)return false;mutationFlight.current=true;setBusy(true);setError("");setSuccess("");let committed=false;try{await job();committed=true;if(!mounted.current)return false;clearDetail();setPlans([]);setRequirements([]);setGaps([]);setSuccess("培训操作已保存。");await load(true);if(refreshId&&mounted.current)await open(refreshId,true);return mounted.current;}catch(e){if(mounted.current)setError(hrLoadErrorMessage(e,committed?"业务已保存，刷新失败，请重新读取，勿重复提交。":message));return committed&&mounted.current;}finally{mutationFlight.current=false;if(mounted.current)setBusy(false);}};
 const createCourse=async(form:FormData)=>mutate(()=>hrApi.createTrainingCourse({code:String(form.get("code")),title:String(form.get("title")),category:String(form.get("category")),provider:String(form.get("provider"))||undefined,hours:String(form.get("hours")),description:String(form.get("description"))||undefined},getAccessToken()),"创建课程失败");
 const createPlan=async(form:FormData)=>mutate(()=>hrApi.createTrainingPlan({code:String(form.get("code")),name:String(form.get("name")),courseId:String(form.get("course")),mandatory:form.get("mandatory")==="on",startDate:String(form.get("startDate")),endDate:String(form.get("endDate")),budgetAmount:canCost?String(form.get("budgetAmount")||"0"):"0",costCurrency:"CNY",employeeIds:[...new Set(form.getAll("employees").map(String))]},getAccessToken()),"创建培训计划失败");
 const createRequirement=async(form:FormData)=>mutate(()=>hrApi.createTrainingPositionRequirement({positionId:String(form.get("position")),courseId:String(form.get("requiredCourse"))},getAccessToken()),"设置岗位必修课程失败");
 const complete=async(participantId:string,planId:string,payload:TrainingResultPayload)=>mutate(()=>hrApi.completeTraining(participantId,payload,getAccessToken()),"记录培训结果失败",planId);
 const revisePlanFacts=async(current:HrTrainingPlanDetail,form:FormData)=>{const payload=trainingPlanFactsPayload(form,current,canCourse);if(!payload.courseName&&!payload.startDate&&!payload.endDate){setError("请先修改课程名称或日期");return;}return mutate(()=>hrApi.reviseTrainingPlanFacts(current.id,payload,getAccessToken()),"更新培训课程及日期失败",current.id);};
 const correctResult=async(participantId:string,planId:string,payload:TrainingResultPayload)=>mutate(()=>hrApi.correctTraining(participantId,payload,getAccessToken()),"更新培训结果失败",planId);
 const forbidden=<main className={`content ds-page ${styles.page} ${operations.workspace}`}><section className="ds-panel"><ForbiddenState message="无权访问培训管理"/></section></main>;
 return <PermissionGuard module="hr" permission={HR_PERMISSIONS.HR_TRAINING_PAGE} fallback={forbidden}><main className={`content ds-page ${styles.page} ${operations.workspace}`}>
  <section className="ds-hero"><div className="ds-hero-copy"><span className="ds-eyebrow">人事运营 · 人才发展</span><h1>培训管理</h1><p>统一课程、培训计划、员工任务与结果记录，形成可追溯的人才培养档案。</p></div><div className={styles.heroActions}><button className="ds-button" disabled={busy||loading} onClick={()=>void load()}>{loading?"刷新中":"刷新"}</button></div></section>
  {success?<section className="ds-panel"><p role="status">{success}{error?" 后续读取未完成，请刷新查看，勿重复提交。":""}</p></section>:null}
  {error?<section className="ds-panel"><p className="form-error" role="alert">{error}</p><button className="ds-button" disabled={busy||loading} onClick={()=>void load()}>重试</button></section>:null}
  {canCourse?<section className="ds-panel"><h2>新增课程</h2><form className={styles.formGrid} onSubmit={event=>{event.preventDefault();const form=event.currentTarget;if(busy)return;void createCourse(new FormData(form)).then(success=>{if(success)form.reset();});}}><fieldset disabled={busy||detailLoading} style={{display:"contents"}}><label className="form-field"><span>课程编号</span><input name="code" required maxLength={64}/></label><label className="form-field"><span>课程名称</span><input name="title" required maxLength={160}/></label><label className="form-field"><span>分类</span><input name="category" required maxLength={64}/></label><label className="form-field"><span>培训机构</span><input name="provider" maxLength={160}/></label><label className="form-field"><span>标准学时</span><input name="hours" required type="number" min="0.01" max="999999.99" step="0.01"/></label><label className="form-field"><span>课程摘要</span><input name="description" maxLength={2000}/></label><button className="ds-button ds-button-primary" disabled={busy||detailLoading}>保存课程</button></fieldset></form></section>:null}
  {canCourse?<section className="ds-panel"><h2>岗位必修课程</h2><p>为岗位建立必修课程矩阵；停用规则会保留历史证据，重新启用请建立新的规则。</p><form className={styles.formGrid} onSubmit={event=>{event.preventDefault();const form=event.currentTarget;void createRequirement(new FormData(form)).then(saved=>{if(saved)form.reset();});}}><fieldset disabled={busy||detailLoading} style={{display:"contents"}}><label className="form-field"><span>岗位</span><select name="position" required><option value="">请选择</option>{requirementPositions.map(x=><option key={x.id} value={x.id}>{x.positionName} · {x.positionCode}</option>)}</select></label><label className="form-field"><span>必修课程</span><select name="requiredCourse" required><option value="">请选择</option>{courses.map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><button className="ds-button ds-button-primary" disabled={busy||detailLoading}>设置必修</button></fieldset></form><div className={`ds-mobile-record-list ${styles.trainingRecords}`}>{requirements.length?requirements.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.positionName} · {x.courseTitle}</strong><span>{x.positionCode} · {x.courseCode} · {x.hours} 学时</span><span>{x.status==="enabled"?"生效中":"已停用"}</span>{x.status==="enabled"?<button className="ds-button" disabled={busy||detailLoading} onClick={()=>void mutate(()=>hrApi.disableTrainingPositionRequirement(x.id,getAccessToken()),"停用岗位必修课程失败")}>停用</button>:null}</article>):<p>尚未设置岗位必修课程。</p>}</div></section>:null}
  {canPlan?<section className="ds-panel"><h2>岗位必修完成情况</h2><div className={`ds-mobile-record-list ${styles.trainingRecords}`}>{gaps.length?gaps.map(x=><article className="ds-mobile-record" key={`${x.requirementId}-${x.employeeId}`}><strong>{x.employeeName} · {x.courseTitle}</strong><span>{x.positionName} · {x.employeeCode} · {x.courseCode}</span><span>{x.completed?"已完成":"待安排"}</span></article>):<p>当前没有在职员工的岗位必修课程记录。</p>}</div></section>:null}
  {canPlan?<section className="ds-panel"><h2>创建培训计划</h2><form className={styles.formGrid} onSubmit={event=>{event.preventDefault();const form=event.currentTarget;if(busy)return;if(!selectedEmployees.length){setError("请选择至少一名参训员工");return;}void createPlan(new FormData(form)).then(success=>{if(success){form.reset();setSelectedEmployees([]);}});}}><fieldset disabled={busy||detailLoading} style={{display:"contents"}}><label className="form-field"><span>计划编号</span><input name="code" required maxLength={64}/></label><label className="form-field"><span>计划名称</span><input name="name" required maxLength={160}/></label><label className="form-field"><span>课程</span><select name="course" required><option value="">请选择</option>{courses.map(x=><option key={x.id} value={x.id}>{x.title} · {x.hours} 学时</option>)}</select></label><label className="form-field"><span>开始日期</span><input name="startDate" type="date" required/></label><label className="form-field"><span>结束日期</span><input name="endDate" type="date" required/></label>{canCost?<label className={`form-field ${styles.desktopSensitive}`}><span>预算</span><input name="budgetAmount" type="number" min="0" step="0.0001" defaultValue="0" required/></label>:null}<TrainingEmployeePicker selected={selectedEmployees} onChange={setSelectedEmployees} disabled={busy||detailLoading}/><label className="checkbox-row"><input name="mandatory" type="checkbox"/><span>必修培训</span></label><button className="ds-button ds-button-primary" disabled={busy||detailLoading}>创建计划</button></fieldset></form></section>:null}
  <section className="ds-panel"><h2>培训任务</h2><div className={`ds-mobile-record-list ${styles.trainingRecords}`}>{loading?<p>正在加载…</p>:plans.length?plans.map(x=><article className="ds-mobile-record" key={x.id}><strong>{x.name}</strong><span>课程：{x.courseTitle??"未登记"}</span><span>{statusLabel[x.status]??x.status} · {x.completedCount}/{x.participantCount} 人完成</span><span>{x.startDate} 至 {x.endDate}{x.mandatory?" · 必修":""}</span>{canCost&&x.budgetAmount!==undefined?<span className={styles.desktopSensitive}>预算 {x.budgetAmount} {x.costCurrency} · 已发生 {x.actualCost}</span>:null}<div className={styles.recordActions}><button className="ds-button" disabled={busy||loading||detailLoading} onClick={()=>void open(x.id)}>查看</button>{canPlan&&x.status==="draft"?<button className="ds-button" disabled={busy||detailLoading} onClick={()=>void mutate(()=>hrApi.trainingPlanAction(x.id,"publish",getAccessToken()),"发布计划失败")}>发布</button>:null}{canPlan&&x.status==="published"?<button className="ds-button" disabled={busy||detailLoading} onClick={()=>void mutate(()=>hrApi.trainingPlanAction(x.id,"start",getAccessToken()),"开始计划失败")}>开始</button>:null}{canPlan&&x.status==="in_progress"&&x.completedCount===x.participantCount?<button className="ds-button" disabled={busy||detailLoading} onClick={()=>void mutate(()=>hrApi.trainingPlanAction(x.id,"complete",getAccessToken()),"完成计划失败")}>完成计划</button>:null}</div></article>):<p>当前没有可见培训任务。</p>}</div>{total>pageSize?<div className={styles.recordActions}><button className="ds-button" disabled={busy||page===1||loading} onClick={()=>setPage(x=>Math.max(1,x-1))}>上一页</button><span>第 {page} 页</span><button className="ds-button" disabled={busy||page*pageSize>=total||loading} onClick={()=>setPage(x=>x+1)}>下一页</button></div>:null}</section>
  {detailLoading?<section className="ds-panel"><p>正在加载培训详情…</p></section>:detail?<section className="ds-panel"><div className={styles.sectionHeading}><div><span className="ds-eyebrow">培训结果</span><h2>{detail.name}</h2></div><button className="ds-button" disabled={busy||detailLoading} onClick={()=>{if(!mutationFlight.current)clearDetail();}}>关闭</button></div><p>课程：{detail.courseTitle??"未登记"} · {detail.startDate} 至 {detail.endDate}</p>{canPlan&&["published","in_progress","completed"].includes(detail.status)?<TrainingPlanFactsForm key={`${detail.id}-${detail.factRevision}`} current={detail} canCourse={canCourse} busy={busy} className={styles.formGrid} onSubmit={form=>revisePlanFacts(detail,form)}/>:null}<div className={`ds-mobile-record-list ${styles.trainingRecords}`}>{detail.participants.map((x,index)=><article className="ds-mobile-record" key={x.id??`${x.employeeName}-${x.status}-${index}`}><strong>{x.employeeName}</strong><span>{statusLabel[x.status]??x.status}{x.completedHours?` · ${x.completedHours} 学时`:""}{x.score?` · ${x.score} 分`:""}</span>{Object.hasOwn(x,"memo")&&(x.memo===null||typeof x.memo==="string")?<span>培训备注：{x.memo===null?"未登记":x.memo===""?"无备注文本":x.memo}</span>:null}{canCost&&x.actualCost?<span className={styles.desktopSensitive}>费用 {x.actualCost}</span>:null}{x.id&&x.canAct&&x.status==="assigned"?<button className="ds-button" disabled={busy||detailLoading} onClick={()=>void mutate(()=>hrApi.trainingCheckIn(x.id!,getAccessToken()),"签到失败",detail.id)}>签到</button>:null}{x.id&&x.canAct&&["assigned","checked_in"].includes(x.status)?<TrainingResultForm key={`${x.id}-${x.status}`} participant={{...x,id:x.id}} mode="complete" busy={busy} onSubmit={payload=>complete(x.id!,detail.id,payload)}/>:null}{x.id&&canProgress&&x.status==="completed"?<TrainingResultForm key={`${x.id}-${x.correctionVersion}`} participant={{...x,id:x.id}} mode="correct" busy={busy} onSubmit={payload=>correctResult(x.id!,detail.id,payload)}/>:null}{x.evaluation!==undefined?<span>评价：{x.evaluation===null?"未登记":x.evaluation===""?"空文本":x.evaluation}</span>:null}{x.id&&!(x.canAct&&["assigned","checked_in"].includes(x.status))&&!(canProgress&&x.status==="completed")?<TrainingCertificateRecords participantId={x.id}/>:null}</article>)}</div></section>:null}
 </main></PermissionGuard>;
}
