import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { mkdtempSync, readdirSync, statSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { V7_ENV_KEYS, assertSnapshotV7, directPgRegressionCandidateV7, runV7 } from "../track-b2c-000197-v11-v6-direct-pg-regression-v7.mjs";
import { directBaselinePlanV6 } from "../track-b2c-000197-v11-v6-direct-pg-regression-v6.mjs";

const target = Object.freeze({ runId: "b2c197_v11v6_direct_v7_attempt07", container: "jinhu-b2c197-v11v6-direct-v7-attempt07", containerId: "a".repeat(64), database: "jinhu_b2c197_v11v6_direct_v7_db07", volume: "b".repeat(64), imageId: "c".repeat(64) });
const history = directBaselinePlanV6().filter(({ filename }) => Number(filename.slice(0, 6)) >= 185).map(({ filename, raw_sha256 }) => ({ filename, raw_sha256, status: "succeeded" }));
const snapshot = Object.freeze({ primary_history: history, mirror_history: history, forbidden_primary: 0, forbidden_mirror: 0, approval_rows: 0, keys: ["tenant_id", "park_id", "action_id", "source_type", "source_id", "source_expected_version"], indexdef: "89d630118eeeab3655fffe97cde034d82567c1e253c543f9a33a7a8420768584", predicate: "d47740fefda3dc305edc9f845c359dfae15d6d9fa1c28a096870870129563a37", build_residue: false });

test("v7 is static until all four sealed authority inputs exist", () => { const candidate = directPgRegressionCandidateV7(); assert.equal(candidate.execution_authorized, false); assert.deepEqual(candidate.fixed_physical_targets, []); assert.equal(candidate.docker_or_database_command_executed, false); assert.equal(V7_ENV_KEYS.length, 6); assert.doesNotThrow(() => assertSnapshotV7(snapshot)); for (const bad of [{ ...snapshot, forbidden_primary: 1 }, { ...snapshot, build_residue: true }, { ...snapshot, keys: [] }, { ...snapshot, primary_history: [] }]) assert.throws(() => assertSnapshotV7(bad), /snapshot-drift/u); });
test("v7 fake execution accepts Buffer spawn output, verbose P0001 and exact four rollback snapshots", () => { const calls = []; const fake = (_command, args, options) => { calls.push({ args, input: options.input }); assert.ok(args.includes("VERBOSITY=verbose") || args[0] === "inspect"); if (args[0] === "inspect") return { status: 0, stdout: Buffer.from(`${target.containerId}\n/${target.container}\ntrue\n${target.imageId}\n{}\n[{"Type":"volume","Name":"${target.volume}","RW":true,"Destination":"/var/lib/postgresql/data"}]\n`), stderr: Buffer.alloc(0) }; if (options.input === "SHOW server_version_num;") return { status: 0, stdout: Buffer.from("160014\n"), stderr: Buffer.alloc(0) }; if (options.input.startsWith("SELECT json_build_object")) return { status: 0, stdout: Buffer.from(JSON.stringify(snapshot)), stderr: Buffer.alloc(0) }; if (options.input.includes("DO $fault$")) return { status: 3, stdout: Buffer.alloc(0), stderr: Buffer.from(`ERROR:  P0001: ${options.input.match(/v11-injected-[a-z-]+/u)[0]}\n`) }; return { status: 0, stdout: Buffer.alloc(0), stderr: Buffer.alloc(0) }; }; const evidenceRoot = resolve(mkdtempSync("/tmp/b2c-v7-fake-"), "evidence"); const result = runV7({ authority: { target }, evidenceRoot, runCommand: fake }); assert.equal(result.result.fault_count, 4); assert.equal(result.result.final_snapshot_exact, true); assert.equal(calls.filter(({ input }) => input.includes("DO $fault$")).length, 4); assert.equal(calls.some(({ input }) => input.includes("PostgreSQL database dump")), false); assert.ok(readdirSync(evidenceRoot).every((name) => (statSync(resolve(evidenceRoot, name)).mode & 0o777) === 0o444)); });
