import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmodSync, copyFileSync, cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath, pathToFileURL, URL } from "node:url";

const sourceRoot = resolve(fileURLToPath(new URL("../../../../", import.meta.url)));
const runnerRelative = "scripts/e2e/property-remediation/track-b2c-000197-v11-v6-direct-pg-regression-v13.mjs";
const specRelative = "scripts/e2e/property-remediation/tests/b2c-000197-v11-v6-direct-pg-regression-v13.spec.mjs";
const researchRelative = ".trellis/tasks/07-30-pr192-b-domain-integrations/research";
const prefix = "b2c-000197-v11-v6-direct-pg-regression-v13";
const sha = (value) => createHash("sha256").update(value).digest("hex");
const ids = Object.freeze({ run: "b2c197_v11v6_direct_v13_attempt13", container: "jinhu-b2c197-v11v6-direct-v13-attempt13", database: "jinhu_b2c197_v11v6_direct_v13_db13", containerId: "a".repeat(64), volumeId: "b".repeat(64), imageId: "c".repeat(64) });
const names = Object.freeze({
  candidate: `${prefix}-candidate-authority-20260803.json`, manifest: `${prefix}-candidate-manifest-20260803.json`, registry: `${prefix}-resource-registry-20260803.json`, staticRecord: `${prefix}-static-test-record-20260803.json`, node22Tap: `${prefix}-node22.tap`, node24Tap: `${prefix}-node24.tap`, databaseReview: `${prefix}-independent-database-review-20260803.json`, qaReview: `${prefix}-independent-qa-review-20260803.json`, securityReview: `${prefix}-independent-security-review-20260803.json`, drainReview: `${prefix}-independent-old-writer-drain-review-20260803.json`, provisionAuthority: `${prefix}-provision-authority-20260803.json`, observation: `${prefix}-resource-observation-20260803.json`, executionAuthority: `${prefix}-execution-authority-20260803.json`,
});
const reviewChain = ["candidate", "database", "qa", "security", "drain", "provision_authority", "resource_observation", "execution_authority"];

function json(value) { return `${JSON.stringify(value, null, 2)}\n`; }
function seal(path, value) { mkdirSync(dirname(path), { recursive: true }); if (existsSync(path) && !lstatSync(path).isSymbolicLink()) chmodSync(path, 0o644); writeFileSync(path, typeof value === "string" ? value : json(value)); chmodSync(path, 0o444); return sha(readFileSync(path)); }
function edit(path, mutate) { const value = JSON.parse(readFileSync(path, "utf8")); return seal(path, mutate(value)); }
function pathOf(fixture, key) { return resolve(fixture.research, names[key]); }
function canonicalPaths() { const result = {}; for (const [key, name] of Object.entries(names)) result[key] = `${researchRelative}/${name}`; return result; }

async function fixture({ migrations = false } = {}) {
  const root = mkdtempSync("/tmp/b2c-v13-fixture-"); const research = resolve(root, researchRelative); mkdirSync(resolve(root, dirname(runnerRelative)), { recursive: true }); mkdirSync(resolve(root, dirname(specRelative)), { recursive: true }); mkdirSync(research, { recursive: true });
  copyFileSync(resolve(sourceRoot, runnerRelative), resolve(root, runnerRelative)); copyFileSync(resolve(sourceRoot, specRelative), resolve(root, specRelative)); chmodSync(resolve(root, runnerRelative), 0o444); chmodSync(resolve(root, specRelative), 0o444); if (migrations) cpSync(resolve(sourceRoot, "database"), resolve(root, "database"), { recursive: true });
  const tap22 = seal(pathOf({ research }, "node22Tap"), "TAP version 13\n1..1\nok 1 - v13 static Node 22\n"); const tap24 = seal(pathOf({ research }, "node24Tap"), "TAP version 13\n1..1\nok 1 - v13 static Node 24\n");
  const runnerSha = sha(readFileSync(resolve(root, runnerRelative))), specSha = sha(readFileSync(resolve(root, specRelative)));
  const resources = ["A", "B", "C", "D", "E", "F", "G", "H", "v4"].map((label, index) => ({ label, run_id: `past-run-${index}`, container: `past-container-${index}`, container_id: `${index}`.repeat(64), database: `past-database-${index}`, volume: `past-volume-${index}` }));
  const registrySha = seal(pathOf({ research }, "registry"), { schema_version: "b2c-v13-resource-registry-v1", resources });
  const recordSha = seal(pathOf({ research }, "staticRecord"), { schema_version: "b2c-v13-static-test-record-v1", runner_raw_sha256: runnerSha, test_raw_sha256: specSha, node22: { binary: "/fixture/node22", result: "pass", raw_tap_sha256: tap22 }, node24: { binary: "/fixture/node24", result: "pass", raw_tap_sha256: tap24 }, docker_or_database_command_executed: false, coverage: ["fixed-paths", "two-phase-authority", "exact-contracts", "fake-full-path"] });
  const candidateSha = seal(pathOf({ research }, "candidate"), { schema_version: "b2c-v13-candidate-authority-v1", status: "PENDING_REVIEW", execution_authorized: false, container_create_authorized: false, container_execute_authorized: false, formal_go: false, docker_or_database_command_executed: false, runner_raw_sha256: runnerSha, runner_spec_raw_sha256: specSha, registry_raw_sha256: registrySha, static_test_record_raw_sha256: recordSha, node22_tap_raw_sha256: tap22, node24_tap_raw_sha256: tap24 });
  const manifestSha = seal(pathOf({ research }, "manifest"), { schema_version: "b2c-v13-candidate-manifest-v1", status: "PENDING_REVIEW", candidate_flags: { container_create_authorized: false, container_execute_authorized: false, execution_authorized: false, formal_go: false }, candidate_authority_raw_sha256: candidateSha, runner_raw_sha256: runnerSha, runner_spec_raw_sha256: specSha, registry_raw_sha256: registrySha, static_test_record_raw_sha256: recordSha, node22_tap_raw_sha256: tap22, node24_tap_raw_sha256: tap24, review_chain: reviewChain, canonical_paths: canonicalPaths(), trust_root: "repository-fixed-path-procedural-root-v1" });
  const common = { candidate_authority_raw_sha256: candidateSha, candidate_manifest_raw_sha256: manifestSha, registry_raw_sha256: registrySha, static_test_record_raw_sha256: recordSha, node22_tap_raw_sha256: tap22, node24_tap_raw_sha256: tap24 };
  const databaseSha = seal(pathOf({ research }, "databaseReview"), { schema_version: "b2c-v13-independent-database-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common });
  const qaSha = seal(pathOf({ research }, "qaReview"), { schema_version: "b2c-v13-independent-qa-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common, database_review_raw_sha256: databaseSha });
  const securitySha = seal(pathOf({ research }, "securityReview"), { schema_version: "b2c-v13-independent-security-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common, database_review_raw_sha256: databaseSha, qa_review_raw_sha256: qaSha });
  const drainSha = seal(pathOf({ research }, "drainReview"), { schema_version: "b2c-v13-independent-old-writer-drain-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common, database_review_raw_sha256: databaseSha, qa_review_raw_sha256: qaSha, security_review_raw_sha256: securitySha });
  const provisionSha = seal(pathOf({ research }, "provisionAuthority"), { schema_version: "b2c-v13-provision-authority-v1", status: "AUTHORIZED", container_create_authorized: true, container_execute_authorized: false, execution_authorized: false, formal_go: false, candidate_authority_raw_sha256: candidateSha, candidate_manifest_raw_sha256: manifestSha, database_review_raw_sha256: databaseSha, qa_review_raw_sha256: qaSha, security_review_raw_sha256: securitySha, drain_review_raw_sha256: drainSha, run_id: ids.run, container: ids.container, database: ids.database, image_reference: "postgres:16-alpine", host_port_bindings: 0, anonymous_volume: true, mount_type: "volume", mount_rw: true, mount_destination: "/var/lib/postgresql/data" });
  const module = await import(`${pathToFileURL(resolve(root, runnerRelative)).href}?fixture=${encodeURIComponent(root)}`);
  return { root, research, module, hashes: { candidateSha, manifestSha, databaseSha, qaSha, securitySha, drainSha, provisionSha } };
}

function inspectOutput(fixture) { return `${ids.containerId}\ntrue\n${ids.imageId}\n{}\n${JSON.stringify([{ Type: "volume", Name: ids.volumeId, RW: true, Destination: "/var/lib/postgresql/data" }])}\n${JSON.stringify({ "jinhu.b2c.run_id": ids.run, "jinhu.b2c.provision_authority_sha256": fixture.hashes.provisionSha })}\n`; }
function provisionFake(fixture, failInspect = false) { return (command, argv) => { assert.equal(command, "/usr/bin/docker"); if (argv[0] === "run") return { status: 0, stdout: `${ids.containerId}\n`, stderr: "" }; if (argv[0] === "inspect") return failInspect ? { status: 1, stdout: "", stderr: "inspect failed" } : { status: 0, stdout: inspectOutput(fixture), stderr: "" }; throw new Error(`unexpected provision command:${argv.join(" ")}`); }; }
function completeExecutionAuthority(fixture) {
  const observationPath = pathOf(fixture, "observation"), observationSha = sha(readFileSync(observationPath));
  seal(pathOf(fixture, "executionAuthority"), { schema_version: "b2c-v13-execution-authority-v1", status: "AUTHORIZED", container_create_authorized: false, container_execute_authorized: true, execution_authorized: true, formal_go: false, candidate_authority_raw_sha256: fixture.hashes.candidateSha, candidate_manifest_raw_sha256: fixture.hashes.manifestSha, database_review_raw_sha256: fixture.hashes.databaseSha, qa_review_raw_sha256: fixture.hashes.qaSha, security_review_raw_sha256: fixture.hashes.securitySha, drain_review_raw_sha256: fixture.hashes.drainSha, provision_authority_raw_sha256: fixture.hashes.provisionSha, resource_observation_raw_sha256: observationSha, run_id: ids.run, container: ids.container, container_id: ids.containerId, database: ids.database, volume_id: ids.volumeId, image_id: ids.imageId });
}
const lateNames = ["000185_property_b_identity_schema_expand.sql", "000186_property_b_approval_runtime_schema.sql", "000187_property_b_event_notification_schema.sql", "000188_property_b_task_runtime_schema.sql", "000189_property_b_module_rbac_definitions.sql", "000190_property_b_migration_compatibility_control.sql", "000193_property_b_runtime_integrity_forward_fix.sql", "000194_property_task_projection_contract_correction.sql", "000195_property_mutation_receipt_contract_v2.sql"];
function exactSnapshot(fixture) { const history = lateNames.map((filename) => ({ filename, raw_sha256: sha(readFileSync(resolve(fixture.root, "database/migrations", filename))), status: "succeeded" })); return { primary_history: history, mirror_history: history, forbidden_primary: 0, forbidden_mirror: 0, approval_rows: 0, keys: ["tenant_id", "park_id", "action_id", "source_type", "source_id", "source_expected_version"], indexdef: "89d630118eeeab3655fffe97cde034d82567c1e253c543f9a33a7a8420768584", predicate: "d47740fefda3dc305edc9f845c359dfae15d6d9fa1c28a096870870129563a37", catalog: { index_exists: true, build_residue: false } }; }
function executionFake(fixture) { const snapshot = JSON.stringify(exactSnapshot(fixture)); return (command, argv, options) => { assert.equal(command, "/usr/bin/docker"); if (argv[0] === "inspect") return { status: 0, stdout: inspectOutput(fixture), stderr: "" }; const input = String(options.input ?? ""); if (input === "SHOW server_version_num;") return { status: 0, stdout: "160010\n", stderr: "" }; const marker = input.match(/v13-injected-(before-create|after-create|after-drop|before-rename)/u)?.[0]; if (marker) return { status: 1, stdout: "", stderr: `ERROR:  P0001: ${marker}\n` }; if (input.includes("SELECT json_build_object('primary_history'")) return { status: 0, stdout: `${snapshot}\n`, stderr: "" }; return { status: 0, stdout: "", stderr: "" }; }; }
function assertNoCommands(fn) { let calls = 0; assert.throws(() => fn(() => { calls += 1; return { status: 0, stdout: "", stderr: "" }; })); assert.equal(calls, 0); }

test("v13 exposes only sealed two-phase resource APIs and permanently pending candidate flags", async () => { const value = await fixture(); assert.deepEqual(value.module.candidateV13(), { status: "PENDING_REVIEW", execution_authorized: false, container_create_authorized: false, container_execute_authorized: false, formal_go: false, docker_or_database_command_executed: false, trust_root: "repository-fixed-path-procedural-root-v1", review_chain: reviewChain }); assert.deepEqual(Object.keys(value.module).sort(), ["assertFaultMarkerV13", "assertSnapshotV13", "candidateV13", "executeV13", "provisionV13"]); });

test("v13 positive fake-command path provisions exact intent then executes inspect, full baseline, four real DDL boundaries, and provenance terminal", async () => {
  const value = await fixture({ migrations: true }); let provisionCalls = 0; value.module.provisionV13({ runCommand: (...args) => { provisionCalls += 1; return provisionFake(value)(...args); } }); assert.equal(provisionCalls, 2); const observation = JSON.parse(readFileSync(pathOf(value, "observation"), "utf8")); assert.equal(observation.container_id, ids.containerId); assert.deepEqual(observation.labels, { run_id: ids.run, provision_authority_sha256: value.hashes.provisionSha }); assert.equal(lstatSync(pathOf(value, "observation")).mode & 0o777, 0o444);
  completeExecutionAuthority(value); let executionCalls = 0; const result = value.module.executeV13({ runCommand: (...args) => { executionCalls += 1; return executionFake(value)(...args); } }); assert.deepEqual(result.faults.map(({ boundary }) => boundary), ["before-create", "after-create", "after-drop", "before-rename"]); assert.ok(executionCalls > 200); const terminal = JSON.parse(readFileSync(resolve(value.research, `${prefix}-evidence-20260803/success-${ids.run}.json`), "utf8")); assert.deepEqual(Object.keys(terminal.authority_provenance).sort(), ["execution_authority_raw_sha256", "resource_observation_raw_sha256"]); const manifest = JSON.parse(readFileSync(resolve(value.research, `${prefix}-evidence-20260803/success-${ids.run}.manifest.json`), "utf8")); assert.equal(manifest.status, "SUCCESS"); assert.ok(manifest.files.every((entry) => entry.mode === "0444" && /^[0-9a-f]{64}$/u.test(entry.raw_sha256)));
});

test("v13 rejects every canonical intake path when missing, mutable, or symlinked before creation", async () => {
  for (const key of ["candidate", "manifest", "registry", "staticRecord", "node22Tap", "node24Tap", "databaseReview", "qaReview", "securityReview", "drainReview", "provisionAuthority"]) {
    for (const condition of ["missing", "mutable", "symlink"]) { const value = await fixture(); const path = pathOf(value, key); if (condition === "missing") renameSync(path, `${path}.elsewhere`); else if (condition === "mutable") chmodSync(path, 0o644); else { renameSync(path, `${path}.target`); symlinkSync(`${path}.target`, path); } assertNoCommands((runCommand) => value.module.provisionV13({ runCommand })); }
  }
});

test("v13 rejects exact schema, field, decision, numeric-zero, hash, registry, resource, and live-byte drift before creation", async () => {
  const cases = [
    ["candidate", (v) => ({ ...v, extra: true })], ["candidate", (v) => { delete v.status; return v; }], ["candidate", (v) => ({ ...v, formal_go: "false" })], ["manifest", (v) => ({ ...v, review_chain: [...v.review_chain].reverse() })], ["databaseReview", (v) => ({ ...v, decision: "NO-GO" })], ["qaReview", (v) => ({ ...v, open_p0: "0" })], ["securityReview", (v) => ({ ...v, review_approved: false })], ["drainReview", (v) => ({ ...v, candidate_authority_raw_sha256: "0".repeat(64) })], ["provisionAuthority", (v) => ({ ...v, anonymous_volume: false })], ["provisionAuthority", (v) => ({ ...v, container_execute_authorized: true })], ["provisionAuthority", (v) => ({ ...v, image_reference: "postgres:latest" })], ["registry", (v) => ({ ...v, extra: true })], ["registry", (v) => ({ ...v, resources: v.resources.slice(1) })], ["registry", (v) => ({ ...v, resources: v.resources.map((entry, index) => index ? entry : { ...entry, run_id: ids.run }) })],
  ];
  for (const [key, mutate] of cases) { const value = await fixture(); edit(pathOf(value, key), mutate); assertNoCommands((runCommand) => value.module.provisionV13({ runCommand })); }
  { const value = await fixture(); const path = pathOf(value, "provisionAuthority"); const raw = readFileSync(path, "utf8").replace('"host_port_bindings": 0', '"host_port_bindings": -0'); seal(path, raw); assertNoCommands((runCommand) => value.module.provisionV13({ runCommand })); }
  for (const live of [runnerRelative, specRelative]) { const value = await fixture(); const path = resolve(value.root, live); chmodSync(path, 0o644); writeFileSync(path, `${readFileSync(path, "utf8")}\n`); chmodSync(path, 0o444); assertNoCommands((runCommand) => value.module.provisionV13({ runCommand })); }
});

test("v13 seals an immutable non-reusable failure receipt when post-create inspection fails", async () => { const value = await fixture(); assert.throws(() => value.module.provisionV13({ runCommand: provisionFake(value, true) })); const receipt = JSON.parse(readFileSync(pathOf(value, "observation"), "utf8")); assert.equal(receipt.status, "PROVISION_FAILED"); assert.equal(receipt.run_id_reusable, false); assert.equal(receipt.cleanup_attempted, false); assert.equal(lstatSync(pathOf(value, "observation")).mode & 0o777, 0o444); });

test("v13 execute rejects observation/execution authority schemas, bindings, modes, symlinks, and migration drift with zero child commands", async () => {
  const mutations = [["observation", (v) => ({ ...v, extra: true })], ["observation", (v) => ({ ...v, container_id: "d".repeat(64) })], ["observation", (v) => ({ ...v, host_port_bindings: "0" })], ["executionAuthority", (v) => ({ ...v, container_create_authorized: true })], ["executionAuthority", (v) => ({ ...v, formal_go: true })], ["executionAuthority", (v) => ({ ...v, resource_observation_raw_sha256: "0".repeat(64) })]];
  for (const [key, mutate] of mutations) { const value = await fixture({ migrations: true }); value.module.provisionV13({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); edit(pathOf(value, key), mutate); assertNoCommands((runCommand) => value.module.executeV13({ runCommand })); }
  for (const key of ["observation", "executionAuthority"]) for (const condition of ["mutable", "symlink"]) { const value = await fixture({ migrations: true }); value.module.provisionV13({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); const path = pathOf(value, key); if (condition === "mutable") chmodSync(path, 0o644); else { renameSync(path, `${path}.target`); symlinkSync(`${path}.target`, path); } assertNoCommands((runCommand) => value.module.executeV13({ runCommand })); }
  const drift = await fixture({ migrations: true }); drift.module.provisionV13({ runCommand: provisionFake(drift) }); completeExecutionAuthority(drift); const migration = resolve(drift.root, "database/migrations/000185_property_b_identity_schema_expand.sql"); writeFileSync(migration, `${readFileSync(migration, "utf8")}\n`); assertNoCommands((runCommand) => drift.module.executeV13({ runCommand }));
});

test("v13 snapshot and full P0001 marker contracts reject missing/extra/coerced values and substring matches", async () => { const value = await fixture({ migrations: true }); const snapshot = exactSnapshot(value); assert.doesNotThrow(() => value.module.assertSnapshotV13(snapshot)); for (const changed of [{ ...snapshot, extra: true }, { ...snapshot, forbidden_primary: "0" }, { ...snapshot, approval_rows: -0 }, { ...snapshot, catalog: { ...snapshot.catalog, extra: false } }, { ...snapshot, primary_history: snapshot.primary_history.map((entry, index) => index ? entry : { ...entry, extra: true }) }]) assert.throws(() => value.module.assertSnapshotV13(changed)); assert.doesNotThrow(() => value.module.assertFaultMarkerV13("ERROR:  P0001: v13-injected-after-drop\n", "v13-injected-after-drop")); for (const output of ["ERROR: P0001: prefix-v13-injected-after-drop\n", "ERROR: P0001: v13-injected-after-drop-suffix\n", "ERROR: P0001: v13-injected-after-drop\nERROR: P0001: other\n"]) assert.throws(() => value.module.assertFaultMarkerV13(output, "v13-injected-after-drop")); });
