import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { chmodSync, copyFileSync, cpSync, existsSync, lstatSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, symlinkSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import test from "node:test";
import { fileURLToPath, pathToFileURL, URL } from "node:url";

const sourceRoot = resolve(fileURLToPath(new URL("../../../../", import.meta.url)));
const runnerRelative = "scripts/e2e/property-remediation/track-b2c-000197-v11-v6-direct-pg-regression-v18.mjs";
const specRelative = "scripts/e2e/property-remediation/tests/b2c-000197-v11-v6-direct-pg-regression-v18.spec.mjs";
const researchRelative = ".trellis/tasks/07-30-pr192-b-domain-integrations/research";
const prefix = "b2c-000197-v11-v6-direct-pg-regression-v18";
const sha = (value) => createHash("sha256").update(value).digest("hex");
const ids = Object.freeze({ run: "b2c197_v11v6_direct_v18_attempt16", container: "jinhu-b2c197-v11v6-direct-v18-attempt16", database: "jinhu_b2c197_v11v6_direct_v18_db16", containerId: "a".repeat(64), volumeId: "b".repeat(64), imageId: "c".repeat(64) });
const failedV15 = Object.freeze({ label: "v15", run_id: "b2c197_v11v6_direct_v15_20260803a", container: "jinhu-b2c197-v11v6-direct-v15-20260803a", container_id: "366d42084ff57b7ddb16bdf0ca30e39cb9a06a16d4eb9d6f9b139f70b2cdae99", database: "jinhu_b2c197_v11v6_direct_v15_20260803a", volume: "acea395306dcd510508dd5b9c97a89f3ce891b5e7b99b4984eba47d181a7b72a" });
const failedV17 = Object.freeze({ label: "v17", run_id: "b2c197_v11v6_direct_v17_20260803a", container: "jinhu-b2c197-v11v6-direct-v17-20260803a", container_id: "1ae79773a7a3133fe8fa5f99a3c06094f733b2b1f71b910225123b17640f9e63", database: "jinhu_b2c197_v11v6_direct_v17_20260803a", volume: "771024a7b887becf7af2fc05bcd0b9d32f54ef657fc5cab112437d44af4d3a87" });
const names = Object.freeze({
  candidate: `${prefix}-candidate-authority-20260803.json`, manifest: `${prefix}-candidate-manifest-20260803.json`, registry: `${prefix}-resource-registry-20260803.json`, staticRecord: `${prefix}-static-test-record-20260803.json`, node22Tap: `${prefix}-node22.tap`, node24Tap: `${prefix}-node24.tap`, databaseReview: `${prefix}-independent-database-review-20260803.json`, qaReview: `${prefix}-independent-qa-review-20260803.json`, securityReview: `${prefix}-independent-security-review-20260803.json`, drainReview: `${prefix}-independent-old-writer-drain-review-20260803.json`, provisionAuthority: `${prefix}-provision-authority-20260803.json`, observation: `${prefix}-resource-observation-20260803.json`, executionAuthority: `${prefix}-execution-authority-20260803.json`,
});
const reviewChain = ["candidate", "database", "qa", "security", "drain", "provision_authority", "resource_observation", "execution_authority"];

function json(value) { return `${JSON.stringify(value, null, 2)}\n`; }
function seal(path, value) { mkdirSync(dirname(path), { recursive: true }); if (existsSync(path) && !lstatSync(path).isSymbolicLink()) chmodSync(path, 0o644); writeFileSync(path, typeof value === "string" ? value : json(value)); chmodSync(path, 0o444); return sha(readFileSync(path)); }
function edit(path, mutate) { const value = JSON.parse(readFileSync(path, "utf8")); return seal(path, mutate(value)); }
function pathOf(fixture, key) { return resolve(fixture.research, names[key]); }
function canonicalPaths() { const result = {}; for (const [key, name] of Object.entries(names)) result[key] = `${researchRelative}/${name}`; return result; }

async function fixture({ migrations = false, registryMutator = (resources) => resources } = {}) {
  const root = mkdtempSync("/tmp/b2c-v18-test-"); const research = resolve(root, researchRelative); mkdirSync(resolve(root, dirname(runnerRelative)), { recursive: true }); mkdirSync(resolve(root, dirname(specRelative)), { recursive: true }); mkdirSync(research, { recursive: true });
  copyFileSync(resolve(sourceRoot, runnerRelative), resolve(root, runnerRelative)); copyFileSync(resolve(sourceRoot, specRelative), resolve(root, specRelative)); chmodSync(resolve(root, runnerRelative), 0o444); chmodSync(resolve(root, specRelative), 0o444); if (migrations) cpSync(resolve(sourceRoot, "database"), resolve(root, "database"), { recursive: true });
  const tap22 = seal(pathOf({ research }, "node22Tap"), "TAP version 13\n1..1\nok 1 - v18 static Node 22\n"); const tap24 = seal(pathOf({ research }, "node24Tap"), "TAP version 13\n1..1\nok 1 - v18 static Node 24\n");
  const runnerSha = sha(readFileSync(resolve(root, runnerRelative))), specSha = sha(readFileSync(resolve(root, specRelative)));
  const historicalRuns = ["b2c197_r0_20260802a", "b2c197_r0_20260802a", "b2c197_prelim_20260802b", "b2c197_prelim_20260802b", "b2c197_prelim_20260802f", "b2c197_prelim_20260802f", "b2c197_prelim_20260802g", "b2c197_prelim_20260802g", "b2c197_v11v6_isolated_20260802a"];
  const resources = registryMutator([...(["A", "B", "C", "D", "E", "F", "G", "H", "v4"].map((label, index) => ({ label, run_id: historicalRuns[index], container: `past-container-${index}`, container_id: `${index}`.repeat(64), database: `past-database-${index}`, volume: `past-volume-${index}` }))), { ...failedV15 }, { ...failedV17 }]);
  const registrySha = seal(pathOf({ research }, "registry"), { schema_version: "b2c-v18-resource-registry-v1", resources });
  const recordSha = seal(pathOf({ research }, "staticRecord"), { schema_version: "b2c-v18-static-test-record-v1", runner_raw_sha256: runnerSha, test_raw_sha256: specSha, node22: { binary: "/fixture/node22", result: "pass", raw_tap_sha256: tap22 }, node24: { binary: "/fixture/node24", result: "pass", raw_tap_sha256: tap24 }, docker_or_database_command_executed: false, coverage: ["fixed-paths", "two-phase-authority", "exact-contracts", "fake-full-path"] });
  const candidateSha = seal(pathOf({ research }, "candidate"), { schema_version: "b2c-v18-candidate-authority-v1", status: "PENDING_REVIEW", execution_authorized: false, container_create_authorized: false, container_execute_authorized: false, formal_go: false, docker_or_database_command_executed: false, runner_raw_sha256: runnerSha, runner_spec_raw_sha256: specSha, registry_raw_sha256: registrySha, static_test_record_raw_sha256: recordSha, node22_tap_raw_sha256: tap22, node24_tap_raw_sha256: tap24 });
  const manifestSha = seal(pathOf({ research }, "manifest"), { schema_version: "b2c-v18-candidate-manifest-v1", status: "PENDING_REVIEW", candidate_flags: { container_create_authorized: false, container_execute_authorized: false, execution_authorized: false, formal_go: false }, candidate_authority_raw_sha256: candidateSha, runner_raw_sha256: runnerSha, runner_spec_raw_sha256: specSha, registry_raw_sha256: registrySha, static_test_record_raw_sha256: recordSha, node22_tap_raw_sha256: tap22, node24_tap_raw_sha256: tap24, review_chain: reviewChain, canonical_paths: canonicalPaths(), trust_root: "repository-fixed-path-procedural-root-v1" });
  const common = { candidate_authority_raw_sha256: candidateSha, candidate_manifest_raw_sha256: manifestSha, registry_raw_sha256: registrySha, static_test_record_raw_sha256: recordSha, node22_tap_raw_sha256: tap22, node24_tap_raw_sha256: tap24 };
  const databaseSha = seal(pathOf({ research }, "databaseReview"), { schema_version: "b2c-v18-independent-database-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common });
  const qaSha = seal(pathOf({ research }, "qaReview"), { schema_version: "b2c-v18-independent-qa-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common, database_review_raw_sha256: databaseSha });
  const securitySha = seal(pathOf({ research }, "securityReview"), { schema_version: "b2c-v18-independent-security-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common, database_review_raw_sha256: databaseSha, qa_review_raw_sha256: qaSha });
  const drainSha = seal(pathOf({ research }, "drainReview"), { schema_version: "b2c-v18-independent-old-writer-drain-review-v1", decision: "GO", review_approved: true, open_p0: 0, open_p1: 0, ...common, database_review_raw_sha256: databaseSha, qa_review_raw_sha256: qaSha, security_review_raw_sha256: securitySha });
  const provisionSha = seal(pathOf({ research }, "provisionAuthority"), { schema_version: "b2c-v18-provision-authority-v1", status: "AUTHORIZED", container_create_authorized: true, container_execute_authorized: false, execution_authorized: false, formal_go: false, candidate_authority_raw_sha256: candidateSha, candidate_manifest_raw_sha256: manifestSha, database_review_raw_sha256: databaseSha, qa_review_raw_sha256: qaSha, security_review_raw_sha256: securitySha, drain_review_raw_sha256: drainSha, run_id: ids.run, container: ids.container, database: ids.database, image_reference: "postgres:16-alpine", host_port_bindings: 0, anonymous_volume: true, mount_type: "volume", mount_rw: true, mount_destination: "/var/lib/postgresql/data" });
  const rawModule = await import(`${pathToFileURL(resolve(root, runnerRelative)).href}?fixture=${encodeURIComponent(root)}`);
  const module = { ...rawModule, provisionV18: ({ runCommand }) => rawModule.createIsolatedV18TestHarness(runCommand).provision(), executeV18: ({ runCommand }) => rawModule.createIsolatedV18TestHarness(runCommand).execute() };
  return { root, research, module, rawModule, hashes: { candidateSha, manifestSha, databaseSha, qaSha, securitySha, drainSha, provisionSha } };
}

function inspectOutput(fixture, extraLabels = {}, image = `sha256:${ids.imageId}`) { return `${ids.containerId}\ntrue\n${image}\n{}\n${JSON.stringify([{ Type: "volume", Name: ids.volumeId, RW: true, Destination: "/var/lib/postgresql/data" }])}\n${JSON.stringify({ "jinhu.b2c.run_id": ids.run, "jinhu.b2c.provision_authority_sha256": fixture.hashes.provisionSha, "desktop.docker.io/wsl-distro": "Ubuntu-26.04", ...extraLabels })}\n`; }
function assertRealInspectFormat(argv) { assert.equal(argv[2].includes("\\n"), false); assert.equal((argv[2].match(/\n/gu) ?? []).length, 5); }
function provisionFake(fixture, { failInspect = false, extraLabels = {}, secret = "", image = `sha256:${ids.imageId}` } = {}) { return (command, argv) => { assert.equal(command, "/usr/bin/docker"); if (argv[0] === "run") return { status: 0, stdout: `${ids.containerId}\n`, stderr: "" }; if (argv[0] === "inspect") { assertRealInspectFormat(argv); return failInspect ? { status: null, stdout: "", stderr: "", error: new Error(secret || "inspect failed") } : { status: 0, stdout: inspectOutput(fixture, extraLabels, image), stderr: "" }; } throw new Error(`unexpected provision command:${argv.join(" ")}`); }; }
function completeExecutionAuthority(fixture) {
  const observationPath = pathOf(fixture, "observation"), observationSha = sha(readFileSync(observationPath));
  seal(pathOf(fixture, "executionAuthority"), { schema_version: "b2c-v18-execution-authority-v1", status: "AUTHORIZED", container_create_authorized: false, container_execute_authorized: true, execution_authorized: true, formal_go: false, candidate_authority_raw_sha256: fixture.hashes.candidateSha, candidate_manifest_raw_sha256: fixture.hashes.manifestSha, database_review_raw_sha256: fixture.hashes.databaseSha, qa_review_raw_sha256: fixture.hashes.qaSha, security_review_raw_sha256: fixture.hashes.securitySha, drain_review_raw_sha256: fixture.hashes.drainSha, provision_authority_raw_sha256: fixture.hashes.provisionSha, resource_observation_raw_sha256: observationSha, run_id: ids.run, container: ids.container, container_id: ids.containerId, database: ids.database, volume_id: ids.volumeId, image_id: ids.imageId });
}
const lateNames = ["000185_property_b_identity_schema_expand.sql", "000186_property_b_approval_runtime_schema.sql", "000187_property_b_event_notification_schema.sql", "000188_property_b_task_runtime_schema.sql", "000189_property_b_module_rbac_definitions.sql", "000200_property_b_migration_compatibility_control.sql", "000193_property_b_runtime_integrity_forward_fix.sql", "000194_property_task_projection_contract_correction.sql", "000195_property_mutation_receipt_contract_v2.sql"];
function exactSnapshot(fixture) { const history = lateNames.map((filename) => ({ filename, raw_sha256: sha(readFileSync(resolve(fixture.root, "database/migrations", filename))), status: "succeeded" })); return { primary_history: history, mirror_history: history, forbidden_primary: 0, forbidden_mirror: 0, approval_rows: 0, keys: ["tenant_id", "park_id", "action_id", "source_type", "source_id", "source_expected_version"], indexdef: "89d630118eeeab3655fffe97cde034d82567c1e253c543f9a33a7a8420768584", predicate: "d47740fefda3dc305edc9f845c359dfae15d6d9fa1c28a096870870129563a37", catalog: { index_exists: true, build_residue: false } }; }
function executionFake(fixture, { extraLabels = {} } = {}) { const snapshot = JSON.stringify(exactSnapshot(fixture)); return (command, argv, options) => { assert.equal(command, "/usr/bin/docker"); if (argv[0] === "inspect") { assertRealInspectFormat(argv); return { status: 0, stdout: inspectOutput(fixture, extraLabels), stderr: "" }; } const input = String(options.input ?? ""); if (input === "SHOW server_version_num;") return { status: 0, stdout: "160010\n", stderr: "" }; const marker = input.match(/v18-injected-(before-create|after-create|after-drop|before-rename)/u)?.[0]; if (marker) return { status: 1, stdout: "", stderr: `ERROR:  P0001: ${marker}\n` }; if (input.includes("SELECT json_build_object('primary_history'")) return { status: 0, stdout: `${snapshot}\n`, stderr: "" }; return { status: 0, stdout: "", stderr: "" }; }; }
function assertNoCommands(fn) { let calls = 0; assert.throws(() => fn(() => { calls += 1; return { status: 0, stdout: "", stderr: "" }; })); assert.equal(calls, 0); }

test("v18 exposes zero-argument formal APIs with no caller command injection and a /tmp-only harness", async () => { const value = await fixture(); assert.deepEqual(value.module.candidateV18(), { status: "PENDING_REVIEW", execution_authorized: false, container_create_authorized: false, container_execute_authorized: false, formal_go: false, docker_or_database_command_executed: false, trust_root: "repository-fixed-path-procedural-root-v1", review_chain: reviewChain }); assert.equal(value.rawModule.provisionV18.length, 0); assert.equal(value.rawModule.executeV18.length, 0); assert.match(String(value.rawModule.provisionV18), /provisionWithV18\(spawnSync\)/u); assert.match(String(value.rawModule.executeV18), /executeWithV18\(spawnSync\)/u); let injected = 0; chmodSync(pathOf(value, "candidate"), 0o644); assert.throws(() => value.rawModule.provisionV18({ runCommand: () => { injected += 1; } })); assert.throws(() => value.rawModule.executeV18({ runCommand: () => { injected += 1; } })); assert.equal(injected, 0); const live = await import(`${pathToFileURL(resolve(sourceRoot, runnerRelative)).href}?live-harness-rejection`); assert.throws(() => live.createIsolatedV18TestHarness(() => {}), /b2c-v18-test-harness-root/u); });

test("v18 accepts the real registry pattern with shared historical run IDs while rejecting reuse of every target identity", async () => {
  const shared = await fixture(); const registry = JSON.parse(readFileSync(pathOf(shared, "registry"), "utf8")); assert.deepEqual(registry.resources.find(({ label }) => label === "v15"), failedV15); assert.deepEqual(registry.resources.find(({ label }) => label === "v17"), failedV17); let acceptedCalls = 0; shared.module.provisionV18({ runCommand: (...args) => { acceptedCalls += 1; return provisionFake(shared)(...args); } }); assert.equal(acceptedCalls, 2);
  for (const [field, target] of [["run_id", ids.run], ["container", ids.container], ["database", ids.database], ["volume", "postgres:16-alpine"]]) { const value = await fixture({ registryMutator: (resources) => resources.map((entry, index) => index ? entry : { ...entry, [field]: target }) }); assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
  for (const [field, target] of [["container_id", ids.containerId], ["volume", ids.volumeId], ["volume", ids.imageId]]) { const value = await fixture({ migrations: true, registryMutator: (resources) => resources.map((entry, index) => index ? entry : { ...entry, [field]: target }) }); value.module.provisionV18({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); assertNoCommands((runCommand) => value.module.executeV18({ runCommand })); }
  for (const [field, target] of [["run_id", ids.run], ["container", ids.container], ["container_id", ids.containerId], ["database", ids.database], ["volume", ids.volumeId]]) { const requiresExecution = ["container_id", "volume"].includes(field); const value = await fixture({ migrations: requiresExecution, registryMutator: (resources) => resources.map((entry) => entry.label === "v15" ? { ...entry, [field]: target } : entry) }); if (requiresExecution) { value.module.provisionV18({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); assertNoCommands((runCommand) => value.module.executeV18({ runCommand })); } else assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
  for (const [field, target] of [["run_id", ids.run], ["container", ids.container], ["container_id", ids.containerId], ["database", ids.database], ["volume", ids.volumeId]]) { const requiresExecution = ["container_id", "volume"].includes(field); const value = await fixture({ migrations: requiresExecution, registryMutator: (resources) => resources.map((entry) => entry.label === "v17" ? { ...entry, [field]: target } : entry) }); if (requiresExecution) { value.module.provisionV18({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); assertNoCommands((runCommand) => value.module.executeV18({ runCommand })); } else assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
  for (const mutate of [(resources) => resources.map((entry, index) => index ? entry : { ...entry, container: "   " }), (resources) => resources.map((entry, index) => index ? entry : { ...entry, label: "Z" })]) { const value = await fixture({ registryMutator: mutate }); assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
});

test("v18 positive fake-command path proves four ordered injection points across three explicit catalog states", async () => {
  const value = await fixture({ migrations: true }); let provisionCalls = 0; value.module.provisionV18({ runCommand: (...args) => { provisionCalls += 1; return provisionFake(value)(...args); } }); assert.equal(provisionCalls, 2); const observation = JSON.parse(readFileSync(pathOf(value, "observation"), "utf8")); assert.equal(observation.container_id, ids.containerId); assert.equal(observation.image_id, ids.imageId); assert.deepEqual(observation.labels, { run_id: ids.run, provision_authority_sha256: value.hashes.provisionSha }); assert.deepEqual(observation.inherited_labels, { "desktop.docker.io/wsl-distro": "Ubuntu-26.04" }); assert.equal(lstatSync(pathOf(value, "observation")).mode & 0o777, 0o444);
  completeExecutionAuthority(value); const faultSqlInputs = []; let executionCalls = 0; const result = value.module.executeV18({ runCommand: (...args) => { executionCalls += 1; const input = String(args[2]?.input ?? ""); if (/v18-injected-/u.test(input)) faultSqlInputs.push(input); return executionFake(value)(...args); } }); assert.deepEqual(result.faults, [
    { boundary: "before-create", injection_point: "after-validation", catalog_state: "old-present-build-absent", marker: "v18-injected-before-create", sqlstate: "P0001", snapshot_exact: true },
    { boundary: "after-create", injection_point: "after-validation", catalog_state: "old-present-build-present", marker: "v18-injected-after-create", sqlstate: "P0001", snapshot_exact: true },
    { boundary: "after-drop", injection_point: "immediately-after-ddl", catalog_state: "old-absent-build-present", marker: "v18-injected-after-drop", sqlstate: "P0001", snapshot_exact: true },
    { boundary: "before-rename", injection_point: "after-validation", catalog_state: "old-absent-build-present", marker: "v18-injected-before-rename", sqlstate: "P0001", snapshot_exact: true },
  ]); assert.equal(faultSqlInputs.length, 4); const afterDrop = faultSqlInputs[2], beforeRename = faultSqlInputs[3]; assert.ok(afterDrop.indexOf("v18-injected-after-drop") < afterDrop.indexOf("old index still present")); assert.ok(beforeRename.indexOf("old index still present") < beforeRename.indexOf("v18-injected-before-rename")); assert.ok(executionCalls > 200); const terminal = JSON.parse(readFileSync(resolve(value.research, `${prefix}-evidence-20260803/success-${ids.run}.json`), "utf8")); assert.deepEqual(Object.keys(terminal.authority_provenance).sort(), ["execution_authority_raw_sha256", "resource_observation_raw_sha256"]); const manifest = JSON.parse(readFileSync(resolve(value.research, `${prefix}-evidence-20260803/success-${ids.run}.manifest.json`), "utf8")); assert.equal(manifest.status, "SUCCESS"); assert.ok(manifest.files.every((entry) => entry.mode === "0444" && /^[0-9a-f]{64}$/u.test(entry.raw_sha256)));
});

test("v18 rejects every canonical intake path when missing, mutable, or symlinked before creation", async () => {
  for (const key of ["candidate", "manifest", "registry", "staticRecord", "node22Tap", "node24Tap", "databaseReview", "qaReview", "securityReview", "drainReview", "provisionAuthority"]) {
    for (const condition of ["missing", "mutable", "symlink"]) { const value = await fixture(); const path = pathOf(value, key); if (condition === "missing") renameSync(path, `${path}.elsewhere`); else if (condition === "mutable") chmodSync(path, 0o644); else { renameSync(path, `${path}.target`); symlinkSync(`${path}.target`, path); } assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
  }
});

test("v18 rejects exact schema, field, decision, numeric-zero, hash, registry, resource, and live-byte drift before creation", async () => {
  const cases = [
    ["candidate", (v) => ({ ...v, extra: true })], ["candidate", (v) => { delete v.status; return v; }], ["candidate", (v) => ({ ...v, formal_go: "false" })], ["manifest", (v) => ({ ...v, review_chain: [...v.review_chain].reverse() })], ["databaseReview", (v) => ({ ...v, decision: "NO-GO" })], ["qaReview", (v) => ({ ...v, open_p0: "0" })], ["securityReview", (v) => ({ ...v, review_approved: false })], ["drainReview", (v) => ({ ...v, candidate_authority_raw_sha256: "0".repeat(64) })], ["provisionAuthority", (v) => ({ ...v, anonymous_volume: false })], ["provisionAuthority", (v) => ({ ...v, container_execute_authorized: true })], ["provisionAuthority", (v) => ({ ...v, image_reference: "postgres:latest" })], ["registry", (v) => ({ ...v, extra: true })], ["registry", (v) => ({ ...v, resources: v.resources.slice(1) })], ["registry", (v) => ({ ...v, resources: v.resources.map((entry, index) => index ? entry : { ...entry, run_id: ids.run }) })],
  ];
  for (const [key, mutate] of cases) { const value = await fixture(); edit(pathOf(value, key), mutate); assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
  { const value = await fixture(); const path = pathOf(value, "provisionAuthority"); const raw = readFileSync(path, "utf8").replace('"host_port_bindings": 0', '"host_port_bindings": -0'); seal(path, raw); assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
  for (const live of [runnerRelative, specRelative]) { const value = await fixture(); const path = resolve(value.root, live); chmodSync(path, 0o644); writeFileSync(path, `${readFileSync(path, "utf8")}\n`); chmodSync(path, 0o444); assertNoCommands((runCommand) => value.module.provisionV18({ runCommand })); }
});

test("v18 failure receipts use fixed fields, omit secret error text, and reject extra inspect labels", async () => { const secret = "TOP-SECRET-json-or-child-error"; const value = await fixture(); assert.throws(() => value.module.provisionV18({ runCommand: provisionFake(value, { failInspect: true, secret }) })); const receiptRaw = readFileSync(pathOf(value, "observation"), "utf8"), receipt = JSON.parse(receiptRaw); assert.equal(receipt.status, "PROVISION_FAILED"); assert.equal(receipt.run_id_reusable, false); assert.equal(receipt.cleanup_attempted, false); assert.deepEqual(receipt.failure, { code: "B2C_V18_PROVISION_OBSERVATION_FAILED", stage: "post-create-observation", name: "ProvisionObservationError" }); assert.equal(receiptRaw.includes(secret), false); assert.equal(lstatSync(pathOf(value, "observation")).mode & 0o777, 0o444);
  const extra = await fixture(); let calls = 0; assert.throws(() => extra.module.provisionV18({ runCommand: (...args) => { calls += 1; return provisionFake(extra, { extraLabels: { attacker: "label" } })(...args); } })); assert.equal(calls, 2); const extraRaw = readFileSync(pathOf(extra, "observation"), "utf8"); assert.equal(extraRaw.includes("attacker"), false); assert.equal(JSON.parse(extraRaw).status, "PROVISION_FAILED");
  const prefix = await fixture(); assert.throws(() => prefix.module.provisionV18({ runCommand: provisionFake(prefix, { image: ids.imageId }) })); assert.equal(JSON.parse(readFileSync(pathOf(prefix, "observation"), "utf8")).status, "PROVISION_FAILED");
});

test("v18 rejects extra observed labels before execute and extra live labels into a fixed failure terminal", async () => {
  const intake = await fixture({ migrations: true }); intake.module.provisionV18({ runCommand: provisionFake(intake) }); edit(pathOf(intake, "observation"), (value) => ({ ...value, labels: { ...value.labels, attacker: "secret-label" } })); completeExecutionAuthority(intake); assertNoCommands((runCommand) => intake.module.executeV18({ runCommand }));
  const live = await fixture({ migrations: true }); live.module.provisionV18({ runCommand: provisionFake(live) }); completeExecutionAuthority(live); let calls = 0; assert.throws(() => live.module.executeV18({ runCommand: (...args) => { calls += 1; return executionFake(live, { extraLabels: { attacker: "secret-label" } })(...args); } })); assert.equal(calls, 1); const evidence = resolve(live.research, `${prefix}-evidence-20260803`); const combined = readdirSync(evidence).map((name) => readFileSync(resolve(evidence, name), "utf8")).join("\n"); assert.equal(combined.includes("secret-label"), false); const terminal = JSON.parse(readFileSync(resolve(evidence, `failure-${ids.run}.json`), "utf8")); assert.deepEqual(terminal.failure, { code: "B2C_V18_EXECUTION_FAILED", stage: "execution", name: "ExecutionError" });
  const drift = await fixture({ migrations: true }); drift.module.provisionV18({ runCommand: provisionFake(drift) }); completeExecutionAuthority(drift); let driftCalls = 0; assert.throws(() => drift.module.executeV18({ runCommand: (...args) => { driftCalls += 1; return executionFake(drift, { extraLabels: { "desktop.docker.io/wsl-distro": "Ubuntu-24.04" } })(...args); } })); assert.equal(driftCalls, 1);
});

test("v18 execute rejects observation/execution authority schemas, bindings, modes, symlinks, and migration drift with zero child commands", async () => {
  const mutations = [["observation", (v) => ({ ...v, extra: true })], ["observation", (v) => ({ ...v, container_id: "d".repeat(64) })], ["observation", (v) => ({ ...v, host_port_bindings: "0" })], ["executionAuthority", (v) => ({ ...v, container_create_authorized: true })], ["executionAuthority", (v) => ({ ...v, formal_go: true })], ["executionAuthority", (v) => ({ ...v, resource_observation_raw_sha256: "0".repeat(64) })]];
  for (const [key, mutate] of mutations) { const value = await fixture({ migrations: true }); value.module.provisionV18({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); edit(pathOf(value, key), mutate); assertNoCommands((runCommand) => value.module.executeV18({ runCommand })); }
  for (const key of ["observation", "executionAuthority"]) for (const condition of ["mutable", "symlink"]) { const value = await fixture({ migrations: true }); value.module.provisionV18({ runCommand: provisionFake(value) }); completeExecutionAuthority(value); const path = pathOf(value, key); if (condition === "mutable") chmodSync(path, 0o644); else { renameSync(path, `${path}.target`); symlinkSync(`${path}.target`, path); } assertNoCommands((runCommand) => value.module.executeV18({ runCommand })); }
  const drift = await fixture({ migrations: true }); drift.module.provisionV18({ runCommand: provisionFake(drift) }); completeExecutionAuthority(drift); const migration = resolve(drift.root, "database/migrations/000185_property_b_identity_schema_expand.sql"); writeFileSync(migration, `${readFileSync(migration, "utf8")}\n`); assertNoCommands((runCommand) => drift.module.executeV18({ runCommand }));
});

test("v18 snapshot and full P0001 marker contracts reject missing/extra/coerced values and substring matches", async () => { const value = await fixture({ migrations: true }); const snapshot = exactSnapshot(value); assert.doesNotThrow(() => value.module.assertSnapshotV18(snapshot)); for (const changed of [{ ...snapshot, extra: true }, { ...snapshot, forbidden_primary: "0" }, { ...snapshot, approval_rows: -0 }, { ...snapshot, catalog: { ...snapshot.catalog, extra: false } }, { ...snapshot, primary_history: snapshot.primary_history.map((entry, index) => index ? entry : { ...entry, extra: true }) }]) assert.throws(() => value.module.assertSnapshotV18(changed)); assert.doesNotThrow(() => value.module.assertFaultMarkerV18("ERROR:  P0001: v18-injected-after-drop\n", "v18-injected-after-drop")); for (const output of ["ERROR: P0001: prefix-v18-injected-after-drop\n", "ERROR: P0001: v18-injected-after-drop-suffix\n", "ERROR: P0001: v18-injected-after-drop\nERROR: P0001: other\n"]) assert.throws(() => value.module.assertFaultMarkerV18(output, "v18-injected-after-drop")); });
