import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { mkdtempSync, readFileSync, readdirSync, statSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";
import { V6_BASELINE_MANIFEST_SHA256, V6_CORRECT_BUILD_RESIDUE, directBaselineAttestationV6, directBaselinePlanV6, directPgRegressionCandidateV6, runDirectPgRegressionV6 } from "../track-b2c-000197-v11-v6-direct-pg-regression-v6.mjs";
test("v6 seals an exact direct migration inventory without pg_dump", () => { const plan = directBaselinePlanV6(); const canonical = plan.map(({ kind, filename, raw_sha256 }) => ({ kind, filename, raw_sha256 })); assert.equal(plan.length, 194); assert.equal(createHash("sha256").update(JSON.stringify(canonical)).digest("hex"), V6_BASELINE_MANIFEST_SHA256); assert.equal(plan.some(({ filename }) => filename.includes("000175") || filename.includes("000191") || filename.includes("000192") || filename.includes("000197")), false); assert.equal(directBaselineAttestationV6().pg_dump_consumed, false); });
test("v6 candidate is static and uses the migration's real v2 build residue identifier", () => { const candidate = directPgRegressionCandidateV6(); assert.equal(candidate.execution_authorized, false); assert.deepEqual(candidate.fixed_physical_targets, []); assert.equal(candidate.docker_or_database_command_executed, false); assert.equal(V6_CORRECT_BUILD_RESIDUE, "uq_biz_property_approval_request_active_source_v2_build"); const source = readFileSync(new URL("../track-b2c-000197-v11-v6-direct-pg-regression-v6.mjs", import.meta.url), "utf8"); assert.match(source, /active_source_v2_build/u); assert.doesNotMatch(source, /active_source_v4_build/u); });
test("v6 fake execution applies bound bytes through stdin and accepts only the four expected P0001 rollbacks", () => {
  const target = { runId: "b2c197_v11v6_direct_attempt06", container: "jinhu-b2c197-v11v6-direct-attempt06", containerId: "a".repeat(64), database: "jinhu_b2c197_v11v6_direct_db06", volume: "b".repeat(64) };
  const old = { history_primary: null, history_mirror: null, approval_rows: 0, indexdef: "89d630118eeeab3655fffe97cde034d82567c1e253c543f9a33a7a8420768584", predicate: "d47740fefda3dc305edc9f845c359dfae15d6d9fa1c28a096870870129563a37", build_residue: false };
  const calls = []; const fake = (_command, args, options) => { calls.push({ args, input: options.input }); assert.ok(args.every((arg) => !String(arg).includes("CREATE ") && !String(arg).includes("DO $fault$"))); if (args[0] === "inspect") return { status: 0, stdout: `${target.containerId}\n/${target.container}\ntrue\n{}\n[{"Name":"${target.volume}","Destination":"/var/lib/postgresql/data"}]\n`, stderr: "" }; if (options.input === "SHOW server_version_num;") return { status: 0, stdout: "160014\n", stderr: "" }; if (options.input.startsWith("SELECT json_build_object")) return { status: 0, stdout: JSON.stringify(old), stderr: "" }; if (options.input.includes("DO $fault$")) return { status: 3, stdout: "", stderr: `ERROR: P0001: ${options.input.match(/v11-injected-[a-z-]+/u)[0]}\n` }; return { status: 0, stdout: "", stderr: "" }; };
  const evidenceRoot = resolve(mkdtempSync("/tmp/b2c-v6-fake-"), "evidence"); const result = runDirectPgRegressionV6({ target, evidenceRoot, runCommand: fake });
  assert.equal(result.result.fault_count, 4); assert.equal(result.result.final_snapshot_exact, true); assert.equal(calls.some(({ input }) => input.includes("PostgreSQL database dump")), false); assert.equal(calls.filter(({ input }) => input.includes("DO $fault$")).length, 4); assert.ok(readdirSync(evidenceRoot).every((name) => (statSync(resolve(evidenceRoot, name)).mode & 0o777) === 0o444));
});
